Repository leanprover/lean4, pull requests merged in 2022-09, with the labels that each got.

#1513 fix: collision between implicit and auto-bound level names
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Elab/Term.lean
  tests/lean/levelNGen.lean
  tests/lean/levelNGen.lean.expected.out
  tests/lean/run/PPTopDownAnalyze.lean
Labels: waiting review

#1521 doc: update the mdbook instructions
  doc/dev/mdbook.md
Labels: waiting-on-author

#1577 doc: enable syntax highlighting for the Macro Overview
  doc/macro_overview.md
Labels: waiting-on-author

#1596 fix: deindent docstrings with empty lines
  src/Lean/DocString.lean
  tests/lean/docStr.lean
  tests/lean/docStr.lean.expected.out
Labels: bug

#1595 fix: make all syntax accessors non-panicking
  src/Init/Meta.lean
  src/Lean/DocString.lean
  src/Lean/Elab/Quotation.lean
  src/Lean/Linter/MissingDocs.lean
  src/Lean/Syntax.lean
Labels: bug, server

#1614 feat: expose that panic α = default
  src/Init/Prelude.lean
Labels: dev meeting

#1610 feat: goal-diffs
  src/Init/Data/List/Basic.lean
  src/Init/Data/Option/Basic.lean
  src/Lean/Data/RBMap.lean
  src/Lean/Data/RBTree.lean
  src/Lean/Expr.lean
  src/Lean/Meta/Basic.lean
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/SubExpr.lean
  src/Lean/Widget/Diff.lean
  src/Lean/Widget/InteractiveCode.lean
  src/Lean/Widget/InteractiveGoal.lean
  tests/lean/interactive/Diff.lean
  tests/lean/interactive/Diff.lean.expected.out
  tests/lean/interactive/run.lean
Labels: waiting review

#1632 feat: `pattern (occs := ...)` conv
  src/Init/Conv.lean
  src/Lean/Elab/Tactic/Conv/Basic.lean
  src/Lean/Elab/Tactic/Conv/Pattern.lean
  tests/lean/conv1.lean
  tests/lean/conv1.lean.expected.out
Labels: waiting-on-author
