Repository leanprover/lean4, pull requests merged in 2022-11, with the labels that each got.

#1809 feat: allow `doSeq` in `let x <- e | seq`
  src/Lean/Elab/Do.lean
  src/Lean/Parser/Do.lean
  tests/lean/1804.lean
  tests/lean/1804.lean.expected.out
Labels: changelog

#1828 doc: document Init.Data.List.Basic
  src/Init/Data/List/Basic.lean
  tests/lean/run/PPTopDownAnalyze.lean
Labels: waiting on author

#1497 feat: add LLVM C API bindings
  nix/bootstrap.nix
  nix/packages.nix
  script/prepare-llvm-linux.sh
  script/prepare-llvm-macos.sh
  script/prepare-llvm-mingw.sh
  src/CMakeLists.txt
  src/Lean/Compiler/IR.lean
  src/Lean/Compiler/IR/EmitLLVM.lean
  src/Lean/Compiler/IR/LLVMBindings.lean
  src/library/compiler/CMakeLists.txt
  src/library/compiler/llvm.cpp
Labels: waiting on author

#1872 feat: intra-line withPosition formatting
  src/Init/Data/Format/Basic.lean
  src/Init/NotationExtra.lean
  src/Lean/Data/Format.lean
  src/Lean/Parser/Extra.lean
  src/Lean/PrettyPrinter/Formatter.lean
  tests/lean/formatTerm.lean
  tests/lean/formatTerm.lean.expected.out
  tests/lean/sepByIndentQuot.lean.expected.out
  tests/lean/tacUnsolvedGoalsErrors.lean.expected.out
  tests/lean/traceTacticSteps.lean.expected.out
Labels: dev meeting
