Repository leanprover/lean4, pull requests merged in 2022-12, with the labels that each got.

#1911 chore: ignore document version errors
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/Watchdog.lean
Labels: server

#1936 chore: add iff_self to simpOnlyBuiltins
  src/Lean/Elab/Tactic/Simp.lean
  tests/lean/simp_trace.lean.expected.out
Labels: Mathlib4 high prio

#1953 refactor: replace `ignoreLevelMVarDepth` by `levelAssignDepth`
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Coe.lean
  src/Lean/Meta/LevelDefEq.lean
  src/Lean/Meta/SynthInstance.lean
  src/Lean/Meta/Tactic/LinearArith/Nat/Solver.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/MetavarContext.lean
  tests/lean/1018unknowMVarIssue.lean.expected.out
  tests/lean/389.lean.expected.out
  tests/lean/run/1951.lean
Labels: dev meeting
