Repository leanprover/lean4, pull requests merged in 2023-11, with the labels that each got.

#2787 doc: Add docstrings to `dbg_trace` and `assert!` in `do` blocks
  src/Lean/Parser/Do.lean
Labels: builds-mathlib, toolchain-available

#2820 perf: avoid quadratic number of info tree nodes in `DecEq` deriving handler
  src/Lean/Elab/Deriving/DecEq.lean
Labels: builds-mathlib, toolchain-available

#2819 feat: Better error location in structural recursion
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/PreDefinition/Structural/IndPred.lean
  tests/lean/terminationFailure.lean.expected.out
  tests/lean/wf1.lean.expected.out
Labels: toolchain-available

#2834 doc: mention the proof-binding syntax in match
  src/Lean/Parser/Term.lean
Labels: builds-mathlib, toolchain-available

#2851 feat: extend API of KVMap
  src/Lean/Data/KVMap.lean
Labels: builds-mathlib, toolchain-available

#2852 feat: Lean.Linter.logLintIf
  src/Lean/Linter/Util.lean
Labels: builds-mathlib, toolchain-available

#2816 feat: find Decidable instances via unification
  src/Init/Prelude.lean
  src/Init/SimpLemmas.lean
Labels: builds-mathlib, toolchain-available

#2870 fix: re-read HTTP header when skipping notification in `Ipc.readResponseAs`
  src/Lean/Data/JsonRpc.lean
  src/Lean/Data/Lsp/Ipc.lean
Labels: builds-mathlib, toolchain-available

#2866 fix: have parenthesizer copy source info to parenthesized term
  src/Lean/PrettyPrinter/Parenthesizer.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2855 feat: release web assembly
  .github/workflows/ci.yml
  doc/setup.md
Labels: awaiting-author, builds-mathlib, toolchain-available

#2875 doc: code owners
  CODEOWNERS
Labels: toolchain-available

#2884 chore: Issue template: Suggest `#eval Lean.versionString`
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: builds-mathlib, toolchain-available

#2888 fix: support non-identifier library names
  src/Lean/Util/Path.lean
  src/lake/Lake/CLI/Init.lean
  src/lake/tests/init/.gitignore
  src/lake/tests/init/clean.sh
  src/lake/tests/init/test.sh
Labels: awaiting-review, builds-mathlib, toolchain-available

#2889 refactor: lake: use plain lib name for root and native name
  src/lake/Lake/Config/LeanLibConfig.lean
  src/lake/README.md
  src/lake/examples/precompile/foo/lakefile.lean
  src/lake/examples/targets/lakefile.lean
  src/lake/examples/targets/test.sh
Labels: builds-mathlib, toolchain-available

#2890 feat: bare `lake init` & validated pkg names
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Init.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/tests/init/.gitignore
  src/lake/tests/init/clean.sh
  src/lake/tests/init/test.sh
Labels: builds-mathlib, toolchain-available

#2643 Allow trailing comma in tuples, lists, and tactics
  src/Init/Data/List/Basic.lean
  src/Init/Notation.lean
  src/Init/Tactics.lean
  src/Lean/Parser/Term.lean
  tests/compiler/tuple.lean
  tests/compiler/tuple.lean.expected.out
  tests/lean/StxQuot.lean
  tests/lean/trailingComma.lean
  tests/lean/trailingComma.lean.expected.out
Labels: awaiting-review, changelog, toolchain-available

#2645 chore: syntax documentation for `universe`, `open`, `export`, `variable`
  src/Lean/Elab/BuiltinCommand.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2896 fix: lake: whitelist loaded config olean env exts
  src/lake/Lake/Load/Elab.lean
  src/lake/tests/meta/lakefile.lean
  src/lake/tests/meta/test.sh
Labels: awaiting-review, builds-mathlib, toolchain-available

#2886 chore: ignore forgotten Lake test artifacts
  src/lake/tests/old/.gitignore
  tests/pkg/.gitignore
Labels: awaiting-review, toolchain-available

#2918 fix: DecidableEq deriving handler could not handle fields whose types start with an implicit argument
  src/Lean/Elab/Deriving/DecEq.lean
  tests/lean/decEqMutualInductives.lean.expected.out
  tests/lean/run/2914.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2906 doc: release notes for recent lake fixes
  RELEASES.md
Labels: toolchain-available

#2892 fix: PackMutual: Deal with extra arguments
  src/Lean/Elab/PreDefinition/WF/PackMutual.lean
  tests/lean/run/issue2883.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2919 feat: `Lean.MVarId.cleanup` configuration
  src/Lean/Meta/Tactic/Cleanup.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2912 feat: helpful error message about supportInterpreter
  src/library/compiler/ir_interpreter.cpp
Labels: awaiting-review, builds-mathlib, toolchain-available

#2927 doc: Adjust contributor's docs to squash merging
  CONTRIBUTING.md
  doc/dev/commit_convention.md
Labels: toolchain-available

#2462 feat: rename request handler
  src/Lean/Data/Lsp/Basic.lean
  src/Lean/Data/Lsp/Capabilities.lean
  src/Lean/Data/Lsp/LanguageFeatures.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Server/References.lean
  src/Lean/Server/Watchdog.lean
  tests/lean/interactive/codeaction.lean.expected.out
  tests/lean/interactive/rename.lean
  tests/lean/interactive/rename.lean.expected.out
Labels: awaiting-author, builds-mathlib, toolchain-available

#2924 doc: mention `dite` in `ite` docstring
  src/Init/Prelude.lean
Labels: toolchain-available

#2922 refactor: WF.Fix: Pass all remaining goals to `Term.reportUnsolvedGoals`
  src/Lean/Elab/PreDefinition/WF/Fix.lean
Labels: toolchain-available

#2948 chore: run CI on merge_group
  .github/workflows/ci.yml
  .github/workflows/nix-ci.yml
Labels: toolchain-available

#2947 fix: most-recently-nightly-tag does not assume a 'nightly' remote
  script/most-recent-nightly-tag.sh
Labels: toolchain-available

#2926 fix: Use whnf for mutual recursion with types hiding `→`
  src/Lean/Elab/PreDefinition/WF/PackDomain.lean
  src/Lean/Elab/PreDefinition/WF/PackMutual.lean
  tests/lean/run/issue2925.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2946 chore: CI: pin macos-11 to work around 12.7.1 breakage
  .github/workflows/ci.yml
Labels: toolchain-available

#2818 fix: Float RecApp out of applications
  src/Lean/Elab/PreDefinition/Structural/Preprocess.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/PreDefinition/WF/Preprocess.lean
  src/Lean/Elab/RecAppSyntax.lean
  tests/lean/1673.lean.expected.out
  tests/lean/run/2810.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2951 chore: script/most-recent-nightly-tag uses https rather than ssh repo URL
  script/most-recent-nightly-tag.sh
Labels: toolchain-available

#2955 chore: Run CI on all PRs, even base ≠ master
  .github/workflows/ci.yml
  .github/workflows/nix-ci.yml
Labels: awaiting-review, toolchain-available

#2956 doc: Markdown fixes in Lean.Expr
  src/Lean/Expr.lean
Labels: toolchain-available, will-merge-soon

#2943 chore: remove unused MonadBacktrack instance for SimpM
  src/Lean/Meta/Tactic/Simp/Types.lean
Labels: builds-mathlib, toolchain-available

#2864 feat: `pp.beta` to apply beta reduction when pretty printing
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  tests/lean/ppBeta.lean
  tests/lean/ppBeta.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#2935 fix: ignore errors on `IO.FS.Handle` finalization
  .github/workflows/ci.yml
  src/runtime/io.cpp
Labels: toolchain-available

#2766 feat: embed and check githash in .olean
  .github/workflows/ci.yml
  CMakeLists.txt
  src/CMakeLists.txt
  src/library/module.cpp
  src/library/util.cpp
  src/version.h.in
  stage0/src/CMakeLists.txt
  stage0/src/library/module.cpp
Labels: builds-mathlib, toolchain-available

#2053 fix: missing withContext in simp trace
  src/Lean/Elab/Tactic/Simp.lean
  tests/lean/simp_trace.lean
  tests/lean/simp_trace.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2882 feat: Add MatcherApp. and CasesOnApp.refineThrough
  src/Lean/Meta/CasesOn.lean
  src/Lean/Meta/Match/Match.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2928 fix: untar cloud release if no build dir
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Package.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2932 fix: lake: proper exe targets & pkg generation
  src/lake/Lake/CLI/Build.lean
  src/lake/Lake/CLI/Error.lean
  src/lake/Lake/CLI/Init.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/examples/targets/test.sh
  src/lake/tests/init/.gitignore
  src/lake/tests/init/clean.sh
  src/lake/tests/init/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2937 refactor: reverse pkg/lib search & no exe roots in import
  src/lake/Lake/CLI/Build.lean
  src/lake/Lake/Config/LeanExe.lean
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/tests/order/Y.lean
  src/lake/tests/order/bar/Y.lean
  src/lake/tests/order/bar/lakefile.lean
  src/lake/tests/order/foo/Y.lean
  src/lake/tests/order/foo/lakefile.lean
  src/lake/tests/order/lakefile.lean
  src/lake/tests/order/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2954 feat: WF.GuessLex: If there is only one plausible measure, use it
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  tests/lean/guessLexFailures.lean
  tests/lean/guessLexFailures.lean.expected.out
  tests/lean/run/guessLex.lean
  tests/lean/terminationFailure.lean.expected.out
Labels: builds-mathlib, toolchain-available

#2976 fix: remove unnecessary step in pr-release.yml
  .github/workflows/pr-release.yml
Labels: toolchain-available

#2978 chore: Check PR title, not commit, for commit convention
  .github/workflows/pr-title.yml
  .github/workflows/pr.yml
Labels: toolchain-available, will-merge-soon

#2983 chore: CI: Create an all-builds-ok job
  .github/workflows/ci.yml
Labels: toolchain-available

#2984 chore: remove supportInterpreter from lake template
  src/lake/Lake/CLI/Init.lean
  src/lake/README.md
  src/lake/tests/llvm-bitcode-gen/lakefile.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2771 doc: Improve docstrings around Array.mk,.data,.toList
  src/Init/Data/Array/Basic.lean
  src/Init/Prelude.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2987 chore: make PR title check work as a merge_group check
  .github/workflows/pr-title.yml
Labels: toolchain-available

#2986 chore: trim CI set by default
  .github/workflows/ci.yml
Labels: awaiting-review, builds-mathlib, toolchain-available

#2993 test: termination checking and duplicated terms
  tests/lean/issue2981.lean
  tests/lean/issue2981.lean.expected.out
  tests/lean/run/issue2982.lean
Labels: toolchain-available

#2974 refactor: CasesOnApp.refineThrough can return a lambda, not an open term
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Meta/CasesOn.lean
  src/Lean/Meta/Match/Match.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2995 chore: begin development cycle for v4.5.0
  RELEASES.md
  src/CMakeLists.txt
Labels: toolchain-available

#2961 doc: VS Code dev setup
  .github/workflows/ci.yml
  .vscode/settings.json
  doc/dev/index.md
  lean-toolchain
  lean.code-workspace
  src/lean-toolchain
  tests/lean-toolchain
Labels: toolchain-available

#2997 fix: find macOS system libraries in leanc
  src/CMakeLists.txt
Labels: toolchain-available

#2998 chore: CI: in quick mode, only Nix build runs the tests
  .github/workflows/ci.yml
Labels: toolchain-available
