Repository leanprover/lean4, pull requests merged in 2023-10, with the labels that each got.

#2606 docs: update RELEASES.md for #2502
  RELEASES.md
Labels: builds-mathlib, toolchain-available, backport releases/v4.2.0

#2598 Fix linker warnings on macOS
  src/Leanc.lean
Labels: changelog, builds-mathlib, toolchain-available

#2591 feat : derive `DecidableEq` for mutual inductives
  RELEASES.md
  src/Lean/Elab/Deriving/DecEq.lean
  tests/lean/decEqMutualInductives.lean
  tests/lean/decEqMutualInductives.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#2607 fix: withLocation should use withMainContext for target
  src/Lean/Elab/Tactic/Location.lean
  tests/lean/withLocation.lean
  tests/lean/withLocation.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#2601 fix: XML parsing bugs
  src/Lean/Data/Xml/Parser.lean
  tests/lean/xmlParsing.lean
  tests/lean/xmlParsing.lean.expected.out
Labels: toolchain-available

#2599 feat: Web Assembly Build
  .github/workflows/ci.yml
  CMakeLists.txt
  src/CMakeLists.txt
  src/bin/lean.in
  src/include/lean/lean.h
  src/lean.mk.in
  src/library/module.cpp
  src/runtime/io.cpp
  src/runtime/stack_overflow.cpp
  src/runtime/stackinfo.cpp
  src/shell/CMakeLists.txt
  src/stdlib.make.in
  stage0/src/CMakeLists.txt
  stage0/src/library/module.cpp
  stage0/src/shell/CMakeLists.txt
  stage0/src/stdlib.make.in
  tests/common.sh
Labels: awaiting-author, builds-mathlib, toolchain-available

#2604 feat: make `Environment.mk` private
  src/Lean/Environment.lean
  tests/lean/prvCtor.lean
  tests/lean/prvCtor.lean.expected.out
Labels: awaiting-author, breaks-mathlib, toolchain-available

#2623 doc: fix the link to contribution guidelines
  doc/faq.md
Labels: toolchain-available

#2616 feat: show path of failed import
  RELEASES.md
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Util/Cycle.lean
  src/lake/Lake/Util/List.lean
Labels: awaiting-author, builds-mathlib, toolchain-available, missing release notes

#2612 perf: do not inhibit caching of default-level `match` reduction
  src/Lean/Meta/WHNF.lean
  tests/bench/reduceMatch.lean
  tests/bench/speedcenter.exec.velcom.yaml
Labels: builds-mathlib, toolchain-available

#2595 chore: fix MVarId.getType'
  src/Lean/Meta/Tactic/Util.lean
  tests/lean/2505.lean
  tests/lean/2505.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#2617 feat: replay constants into an Environment
  src/Lean/Data/NameMap.lean
  src/Lean/Declaration.lean
  src/Lean/Replay.lean
  src/Lean/Util/FoldConsts.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2652 fix: treat pretty-printed names as strings
  src/Lean/Widget/InteractiveGoal.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2658 feat: `ToMessageData (α × β)` instance
  src/Lean/Message.lean
Labels: breaks-mathlib, toolchain-available

#2671 perf: use quick_is_def_eq first
  src/kernel/type_checker.cpp
Labels: toolchain-available

#2544 fix: `stdin := .null` in `IO.Process.output`
  RELEASES.md
  src/Init/System/IO.lean
Labels: missing documentation, awaiting-review, builds-mathlib, toolchain-available

#2677 test: lake: show module with failed import
  src/lake/Lake/Build/Module.lean
  src/lake/tests/badImport/.gitignore
  src/lake/tests/badImport/Lib/A.lean
  src/lake/tests/badImport/Lib/B.lean
  src/lake/tests/badImport/X.lean
  src/lake/tests/badImport/clean.sh
  src/lake/tests/badImport/lakefile.lean
  src/lake/tests/badImport/test.sh
Labels: builds-mathlib, toolchain-available

#2603 feat: lake: `postUpdate?` + test
  RELEASES.md
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Load/Main.lean
  src/lake/README.md
  src/lake/tests/postUpdate/.gitignore
  src/lake/tests/postUpdate/clean.sh
  src/lake/tests/postUpdate/dep/hello.lean
  src/lake/tests/postUpdate/dep/lakefile.lean
  src/lake/tests/postUpdate/lakefile.lean
  src/lake/tests/postUpdate/test.sh
Labels: awaiting-review, builds-mathlib, toolchain-available

#2651 feat: lake: `--no-build` option to exit before a build
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Context.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/tests/noBuild/.gitignore
  src/lake/tests/noBuild/Test.lean
  src/lake/tests/noBuild/clean.sh
  src/lake/tests/noBuild/lakefile.lean
  src/lake/tests/noBuild/test.sh
Labels: builds-mathlib, toolchain-available

#2501 fix : make `mk_no_confusion_type` handle delta-reduction when generating telescope
  src/library/constructions/no_confusion.cpp
  tests/lean/run/2500.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2621 chore: simp tracing reports ←
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  tests/lean/simp_trace.lean
  tests/lean/simp_trace.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#2533 feat: use nat_gcd in the kernel
  src/Lean/Meta/WHNF.lean
  src/kernel/type_checker.cpp
  src/runtime/object.h
  tests/lean/run/lean_nat_gcd.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2691 fix: pp projection indices starting at 1
  src/library/print.cpp
Labels: builds-mathlib, toolchain-available

#2661 refactor: env extensions can only modify `.extensions`
  src/Lean/Environment.lean
Labels: builds-mathlib, toolchain-available

#2707 feat: lake: `run_io` to execute IO at term elab time
  src/lake/Lake/DSL/Meta.lean
  src/lake/Lake/Util/EvalTerm.lean
  src/lake/tests/meta/lakefile.lean
  src/lake/tests/meta/test.sh
Labels: builds-mathlib, toolchain-available

#2715 feat: add `Simp.Config.ground` for simplifying nested ground terms
  src/Init/Meta.lean
  src/Lean/Meta/Tactic/Simp.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
Labels: builds-mathlib, toolchain-available

#2723 refactor: change `postUpdate?` config to a decl
  RELEASES.md
  src/lake/Lake/Build/Index.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/DSL/Attributes.lean
  src/lake/Lake/DSL/Package.lean
  src/lake/Lake/DSL/Script.lean
  src/lake/Lake/Load/Main.lean
  src/lake/Lake/Load/Package.lean
  src/lake/tests/postUpdate/dep/lakefile.lean
Labels: toolchain-available, backport releases/v4.2.0

#2688 chore: remove unnecessary `%` operations at `Fin.mod` and `Fin.div`
  src/Init/Data/Fin/Basic.lean
Labels: builds-mathlib, toolchain-available

#2743 fix: don't pack `._` files on MacOS
  src/lake/Lake/Build/Actions.lean
Labels: toolchain-available

#2724 chore: remove "paper cut" when using `Fin USize.size`
  src/Init/Data/UInt/Basic.lean
  src/Init/Prelude.lean
  tests/lean/run/1921.lean
Labels: breaks-mathlib, toolchain-available

#2746 chore: typos
  src/Lean/Elab/App.lean
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Elab/Tactic/ElabTerm.lean
  src/Lean/Elab/Term.lean
  src/Lean/Meta/ExprDefEq.lean
Labels: awaiting-review

#2721 fix: version numbers in code actions
  src/Lean/Data/Lsp/Basic.lean
  src/Lean/Server/FileWorker/Utils.lean
  tests/lean/interactive/codeaction.lean
  tests/lean/interactive/codeaction.lean.expected.out
Labels: toolchain-available

#2712 fix: add `instantiateMVars` to `replaceLocalDecl`
  src/Lean/Meta/Tactic/Replace.lean
  tests/lean/replaceLocalDeclInstantiateMVars.lean
  tests/lean/replaceLocalDeclInstantiateMVars.lean.expected.out
Labels: awaiting-review, breaks-mathlib, toolchain-available

#2728 fix: `rw ... at h` unknown fvar bug
  src/Lean/Elab/Tactic/Rewrite.lean
  src/Lean/Meta/Tactic/Replace.lean
  tests/lean/rwWithSynthesizeBug.lean
  tests/lean/rwWithSynthesizeBug.lean.expected.out
Labels: awaiting-review, breaks-mathlib, toolchain-available

#2624 Update contribution guides
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  doc/contributions.md
Labels: awaiting-review, builds-mathlib, toolchain-available

#2709 feat: `LAKE_PKG_URL_MAP`
  src/lake/Lake/CLI/Error.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/Config/Env.lean
  src/lake/Lake/Config/Monad.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/Lake/Load/Main.lean
  src/lake/Lake/Load/Manifest.lean
  src/lake/Lake/Load/Materialize.lean
  src/lake/Lake/Util/Name.lean
  src/lake/tests/clone/test.sh
  src/lake/tests/clone/test/lakefile.lean
  src/lake/tests/env/test.sh
Labels: toolchain-available

#2767 chore: update 'nightly' branch to track nightly releases
  .github/workflows/ci.yml
Labels: awaiting-review, toolchain-available

#2769 chore: run CI against the head of the branch, not a virtual merge with master
  .github/workflows/ci.yml
  .github/workflows/nix-ci.yml
Labels: awaiting-review, builds-mathlib, toolchain-available

#2770 feat: Sensible defaults arguments for math project
  src/lake/Lake/CLI/Init.lean
Labels: builds-mathlib, toolchain-available

#2776 fix: dsimp missing consumeMData when closing goals by rfl
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/2514.lean
  tests/lean/2514.lean.expected.out
Labels: builds-mathlib, toolchain-available

#2780 doc: fix a link in developent documentation
  doc/dev/index.md
Labels: builds-mathlib, toolchain-available

#2774 feat: Array.mem: Avoid DecidableEq, set up decreasing_trivial
  src/Init/Data/Array/Mem.lean
  tests/lean/run/wfOverapplicationIssue.lean
Labels: needs-squash, builds-mathlib, toolchain-available

#2041 fix: replace DecidableEq with BEq/LawfulBEq in List mem theorems
  src/Init/Data/List/Basic.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2738 fix: make `rw [foo]` look in the local context for `foo` before it looks in the environment
  src/Lean/Elab/Tactic/Rewrite.lean
  tests/lean/rwPrioritizesLCtxOverEnv.lean
  tests/lean/rwPrioritizesLCtxOverEnv.lean.expected.out
Labels: awaiting-review, breaks-mathlib, toolchain-available

#2596 feat: withAssignableSyntheticOpaque in assumption
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  tests/lean/2361.lean
  tests/lean/2361.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#2784 fix: fixes #2178
  src/Lean/Elab/Structure.lean
  tests/lean/2178.lean
  tests/lean/2178.lean.expected.out
Labels: builds-mathlib, toolchain-available

#2792 chore: begin development cycle for v4.4.0
  RELEASES.md
  src/CMakeLists.txt
Labels: builds-mathlib, toolchain-available

#2725 feat: reorder Lake help
  src/lake/Lake/CLI/Help.lean
Labels: builds-mathlib, toolchain-available
