Repository leanprover/lean4, pull requests merged in 2023-01, with the labels that each got.

#1997 fix: remove unnecessary hypothesis
  src/Init/Data/List/Control.lean
Labels: dev meeting

#1995 Include timings in trace messages when `profiler` is true
  src/Lean/Util/Trace.lean
Labels: changelog

#2002 perf: do not backtrack after eta-defeq
  src/Lean/Meta/ExprDefEq.lean
Labels: dev meeting

#2020 refactor: redefine `Nat.mod` such that `rfl : 0 % n = 0`
  src/Init/Data/Nat/Div.lean
  src/Init/Data/Nat/Gcd.lean
  tests/lean/run/nat_mod_defeq.lean
Labels: waiting on author

#1917 fix: fuzzy-find bonus for matching last characters of pattern and symbol
  src/Lean/Data/FuzzyMatching.lean
  tests/lean/interactive/completion7.lean.expected.out
  tests/lean/interactive/keywordCompletion.lean.expected.out
  tests/lean/workspaceSymbols.lean
  tests/lean/workspaceSymbols.lean.expected.out
Labels: waiting on author

#1767 Make go-to-definition on a typeclass projection application go to the instance(s)
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/FileWorker/WidgetRequests.lean
  src/Lean/Server/InfoUtils.lean
  src/Lean/Widget/Basic.lean
  src/Lean/Widget/InteractiveCode.lean
  tests/lean/interactive/goTo.lean
  tests/lean/interactive/goTo.lean.expected.out
  tests/lean/interactive/goTo2.lean
  tests/lean/interactive/goTo2.lean.expected.out
Labels: changelog
