Repository leanprover/lean4, pull requests merged in 2023-08, with the labels that each got.

#2378 chore: correct doc-string for elabTerm
  src/Lean/Elab/Term.lean
Labels: waiting review

#2394 doc: writing good tests
  doc/dev/testing.md
Labels: documentation

#2334 feat: add failIfUnchanged flag to simp
  RELEASES.md
  src/Init/Meta.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/SimpAll.lean
  tests/lean/run/constProp.lean
  tests/lean/run/simp_all.lean
  tests/lean/run/simp_failIfUnchanged.lean
Labels: needs-update-stage0, awaiting review

#2400 doc: `IO.Process.getPID` tweak + `IO.FS.Mode`
  src/Init/System/IO.lean
Labels: documentation, awaiting review

#2405 feat: `lake update <pkg>` & related tweaks
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/Config/Dependency.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/Lake/DSL/Require.lean
  src/lake/Lake/Load/Main.lean
  src/lake/Lake/Load/Manifest.lean
  src/lake/Lake/Load/Materialize.lean
  src/lake/Lake/Util/Git.lean
  src/lake/test/manifest/test.sh
Labels: enhancement, awaiting review

#2376 feat: LLVM backend: implement the equivalent of -fstack-clash-protection
  src/Lean/Compiler/IR/EmitLLVM.lean
  src/Lean/Compiler/IR/LLVMBindings.lean
  src/library/compiler/llvm.cpp
Labels: awaiting author

#2336 feat: turning on failIfUnchanged by default in simp
  RELEASES.md
  doc/examples/bintree.lean
  src/Init/Data/Nat/Linear.lean
  src/Init/Meta.lean
  src/Init/WFTactics.lean
  tests/lean/973b.lean
  tests/lean/dsimpZetaIssue.lean
  tests/lean/eraseSimp.lean
  tests/lean/ppProofs.lean
  tests/lean/ppProofs.lean.expected.out
  tests/lean/root.lean
  tests/lean/root.lean.expected.out
  tests/lean/run/1711.lean
  tests/lean/run/341.lean
  tests/lean/run/387.lean
  tests/lean/run/constProp.lean
  tests/lean/run/declareConfigElabBug.lean
  tests/lean/run/discrTreeSimp.lean
  tests/lean/run/eqnsAtSimp2.lean
  tests/lean/run/exfalsoBug.lean
  tests/lean/run/openInScopeBug.lean
  tests/lean/run/simp4.lean
  tests/lean/run/simp6.lean
  tests/lean/run/simpDischargeLoop.lean
  tests/lean/run/simpStar.lean
  tests/lean/run/simp_all.lean
  tests/lean/simpZetaFalse.lean
  tests/lean/simp_dsimp.lean
  tests/pkg/user_attr/UserAttr/Tst.lean
Labels: awaiting review

#2428 feat: `lake env` w/o configuration + more
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/Config/Env.lean
  src/lake/Lake/Config/InstallPath.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/test/env/test.sh
Labels: awaiting review

#2454 doc: improve doc-string for Meta.getConst?
  doc/examples/widgets.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/GetUnfoldableConst.lean
  src/Lean/Meta/WHNF.lean
Labels: documentation, awaiting review

#2435 fix: make sure `refine` preserves pre-existing natural mvars
  src/Lean/Elab/Tactic/ElabTerm.lean
  tests/lean/refinePreservesNaturalMVars.lean
  tests/lean/refinePreservesNaturalMVars.lean.expected.out
Labels: awaiting review, needs-squash

#2460 feat: add labels from comments
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/labels-from-comments.yml
Labels: awaiting review

#2448 feat: create release at lean4-pr-releases for each PR
  .github/workflows/pr-release.yml
Labels: awaiting-review

#2472 chore: update CI to create official releases
  .github/workflows/ci.yml
Labels: awaiting-review

#2397 test: basic tests exercising rw
  tests/lean/rewrite.lean
  tests/lean/rewrite.lean.expected.out
  tests/lean/run/rewrite.lean
Labels: awaiting-review, tests

#2485 fix: revert #2435
  src/Lean/Elab/Tactic/ElabTerm.lean
  tests/lean/refinePreservesNaturalMVars.lean
  tests/lean/refinePreservesNaturalMVars.lean.expected.out
Labels: awaiting-review

#2474 feat: when making PR releases, only download necessary artifacts
  .github/workflows/pr-release.yml
Labels: awaiting-review

#2473 chore: create a mathlib branch for each Lean PR
  .github/workflows/pr-release.yml
Labels: awaiting-review

#2492 feat: add toolchain-available labels to PRs
  .github/workflows/pr-release.yml
Labels: awaiting-review

#2497 fix: 0-arg functions in C need f(void)
  src/include/lean/lean.h
Labels: toolchain-available
