Repository leanprover/lean4, pull requests merged in 2023-09, with the labels that each got.

#2487 fix: simpGoal reports incomplete UsedSimps
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/simp_trace.lean
  tests/lean/simp_trace.lean.expected.out
Labels: awaiting-review, toolchain-available

#2498 chore: in nightly release notes, look for changes since last nightly
  .github/workflows/ci.yml
Labels: awaiting-review, toolchain-available

#2513 doc: fix comment for `Unit`
  src/Init/Prelude.lean
Labels: toolchain-available

#2499 doc: document all parser aliases
  src/Lean/Parser/Basic.lean
  src/Lean/Parser/Command.lean
  src/Lean/Parser/Do.lean
  src/Lean/Parser/Extra.lean
  src/Lean/Parser/StrInterpolation.lean
  src/Lean/Parser/Term.lean
  tests/lean/interactive/hover.lean.expected.out
Labels: awaiting-review, toolchain-available

#2489 fix: simp: include class projections in UsedSimps
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/simp_trace.lean
  tests/lean/simp_trace.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#2523 Update quickstart doc section for first release
  doc/images/code-success.png
  doc/quickstart.md
  doc/setup.md
Labels: documentation

#2537 chore: Do not hide stage0/src/stdlib_flags.h from diffs
  .gitattributes
Labels: awaiting-review

#2470 feat: allow configuring occs in rw
  src/Init/Meta.lean
  src/Init/Tactics.lean
  src/Lean/Data.lean
  src/Lean/Data/Occurrences.lean
  src/Lean/Elab/Tactic/Rewrite.lean
  src/Lean/Meta/KAbstract.lean
  src/Lean/Meta/Tactic/Rewrite.lean
  tests/lean/interactive/1403.lean.expected.out
  tests/lean/rewrite.lean
  tests/lean/rewrite.lean.expected.out
Labels: awaiting-review, toolchain-available

#2545 chore: begin development cycle for 4.2.0
  RELEASES.md
  src/CMakeLists.txt
Labels: builds-mathlib, toolchain-available

#2547 fix: uninterpolated error message in `registerRpcProcedure`
  src/Lean/Server/Rpc/RequestHandling.lean
Labels: awaiting-review, breaks-mathlib, toolchain-available

#2532 Enforce linebreak between `calc` steps
  src/Init/NotationExtra.lean
  src/Lean/Elab/Calc.lean
  tests/lean/calcErrors.lean
  tests/lean/calcErrors.lean.expected.out
Labels: builds-mathlib, toolchain-available

#2530 fix: rename parameter of withImportModules to match doc string
  src/Lean/Environment.lean
Labels: toolchain-available

#2491 perf: reduce allocations in unused variable linter
  src/Lean/Linter/UnusedVariables.lean
Labels: awaiting-review, builds-mathlib

#2556 fix: set `MACOSX_DEPLOYMENT_TARGET` in CI only
  .github/workflows/ci.yml
  src/CMakeLists.txt
Labels: builds-mathlib, toolchain-available

#2546 fix: use MoveFileEx for rename on win
  src/runtime/io.cpp
  tests/lean/run/IO_test.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2529 perf: Use flat ByteArrays in Trie
  src/Init/Data/String/Extra.lean
  src/Lean/Data/Trie.lean
  src/Lean/Parser/Basic.lean
  src/Lean/Parser/Types.lean
  src/include/lean/lean.h
  stage0/src/stdlib_flags.h
  tests/compiler/trie.lean
  tests/compiler/trie.lean.expected.out
  tests/playground/flat_parser2.lean
  tests/playground/parser/parser.lean
Labels: needs-update-stage0, awaiting-review, builds-mathlib, toolchain-available

#2566 chore: update domain
  CONTRIBUTING.md
  README.md
  doc/bin/README.md
  doc/dev/mdbook.md
  doc/faq.md
  doc/fplean.md
  doc/inductive.md
  doc/semantic_highlighting.md
  doc/tpil.md
  doc/whatIsLean.md
  src/Init/Conv.lean
  src/Init/NotationExtra.lean
  src/Init/Prelude.lean
  src/Lean/Expr.lean
  src/Lean/Parser/Command.lean
  src/Lean/Parser/Tactic.lean
  src/stdlib_flags.h
  stage0/src/stdlib_flags.h
  tests/lean/interactive/lean3HoverIssue.lean.expected.out
Labels: builds-mathlib, toolchain-available

#2565 feat: lake: add name to manifest
  src/lake/Lake/Load/Main.lean
  src/lake/Lake/Load/Manifest.lean
Labels: builds-mathlib, toolchain-available

#2502 fix: only return new mvars from `refine`, `elabTermWithHoles`, and `withCollectingNewGoalsFrom`
  src/Lean/Elab/Tactic/ElabTerm.lean
  tests/lean/refineFiltersOldMVars.lean
  tests/lean/refineFiltersOldMVars.lean.expected.out
  tests/lean/run/492.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2390 fix: don't try to generate `below` for nested predicates.
  src/Lean/Meta/IndPredBelow.lean
  tests/lean/run/2389.lean
  tests/lean/run/2389.lean.expected.out
Labels: awaiting-review, needs-squash

#2570 perf: do not detect `lean`'s toolchain
  src/lake/Lake/Config/Env.lean
  src/lake/Lake/Config/InstallPath.lean
  src/lake/tests/env/test.sh
Labels: breaks-mathlib, toolchain-available

#2573 perf: lake: build lakefile environments incrementally
  src/Lean/Environment.lean
  src/lake/Lake/Load/Elab.lean
Labels: awaiting-review, toolchain-available

#2572 perf: lake: no `lean --githash` when collocated
  src/lake/Lake/Config/InstallPath.lean
Labels: builds-mathlib, toolchain-available

#2579 doc: add token error change to RELEASES.md
  RELEASES.md
Labels: builds-mathlib, toolchain-available, backport releases/v4.1.0

#2590 doc: fix doc comment syntax in declModifiers doc comment
  src/Lean/Parser/Command.lean
  tests/lean/interactive/hover.lean.expected.out
Labels: awaiting-review

#2597 chore: add release note about lake startup time
  RELEASES.md
Labels: backport releases/v4.2.0

#2576 chore: Remove unused variables from kernel
  src/kernel/inductive.cpp
  src/library/compiler/csimp.cpp
Labels: awaiting-review, builds-mathlib, toolchain-available

#2605 Fix typos
  src/Lean/ImportingFlag.lean
  src/lake/Lake/DSL/Config.lean
Labels: builds-mathlib, toolchain-available
