Repository leanprover/lean4, pull requests merged in 2023-12, with the labels that each got.

#3002 chore: CI: update github-script
  .github/workflows/ci.yml
  .github/workflows/labels-from-comments.yml
  .github/workflows/pr-title.yml
Labels: toolchain-available

#3003 chore: run CI on new labels
  .github/workflows/ci.yml
Labels: toolchain-available, full-ci

#3005 chore: fix CPP warnings about `static_assert`
  src/runtime/io.cpp
  src/runtime/mpz.cpp
Labels: toolchain-available

#3006 chore: improve tests/lean/copy-produced
  tests/lean/copy-produced
Labels: toolchain-available

#3007 test: expand tests/lean/issue2981.lean a bit
  tests/lean/issue2981.lean
  tests/lean/issue2981.lean.expected.out
Labels: toolchain-available

#3009 chore: run tests with full-ci
  .github/workflows/ci.yml
Labels: toolchain-available, full-ci

#2958 refactor: rewrite TerminationHint elaborators
  src/Lean/Elab/PreDefinition/WF/TerminationHint.lean
  src/Lean/Parser/Command.lean
  stage0/src/stdlib_flags.h
  tests/lean/termination_by2.lean
  tests/lean/termination_by2.lean.expected.out
Labels: needs-update-stage0, awaiting-review, builds-mathlib, toolchain-available

#3015 chore: Nix CI: update setup
  .github/workflows/nix-ci.yml
Labels: toolchain-available

#3008 chore: add vscode cmake configuration
  lean.code-workspace
Labels: awaiting-review, toolchain-available

#3017 refactor: WF.Fix: gather subgoals
  src/Lean/Elab/PreDefinition/WF/Fix.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2960 feat: GuessLex: if no measure is found, explain why
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  tests/lean/guessLexFailures.lean
  tests/lean/guessLexFailures.lean.expected.out
  tests/lean/terminationFailure.lean.expected.out
  tests/lean/wf1.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3012 feat: GuessLex: print inferred termination argument
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/TerminationHint.lean
  tests/lean/guessLex.lean
  tests/lean/guessLex.lean.expected.out
  tests/lean/guessLexTricky.lean
  tests/lean/guessLexTricky.lean.expected.out
  tests/lean/guessLexTricky2.lean
  tests/lean/guessLexTricky2.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3025 doc: add migration guide for per-package server options
  RELEASES.md
Labels: toolchain-available

#2949 feat: detail error message about invalid mutual blocks
  src/Lean/Elab/Declaration.lean
  tests/lean/invalidMutualError.lean
  tests/lean/invalidMutualError.lean.expected.out
Labels: toolchain-available

#3026 doc: fix MetavarContext markdown
  src/Lean/MetavarContext.lean
Labels: toolchain-available, will-merge-soon

#3030 chore: set `warningAsError` in CI only
  .github/workflows/ci.yml
  nix/bootstrap.nix
  src/stdlib.make.in
Labels: toolchain-available

#2821 feat: string gaps for continuing string literals across multiple lines
  RELEASES.md
  doc/lexical_structure.md
  src/Init/Meta.lean
  src/Lean/Parser/Basic.lean
  src/Lean/Parser/StrInterpolation.lean
  tests/lean/string_gaps.lean
  tests/lean/string_gaps.lean.expected.out
  tests/lean/string_gaps_err_newline.lean
  tests/lean/string_gaps_err_newline.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#3037 doc: document constructors of `TransparencyMode`
  src/Init/MetaTypes.lean
Labels: toolchain-available

#3041 chore: update stage0
  stage0/src/CMakeLists.txt
  stage0/src/lean-toolchain
  stage0/src/runtime/io.cpp
  stage0/src/runtime/mpz.cpp
  stage0/src/stdlib.make.in
  stage0/src/stdlib_flags.h
  stage0/stdlib/Init/Meta.c
  stage0/stdlib/Lean/Compiler/LCNF/AuxDeclCache.c
  stage0/stdlib/Lean/Compiler/LCNF/Basic.c
  stage0/stdlib/Lean/Compiler/LCNF/Simp/JpCases.c
  stage0/stdlib/Lean/Compiler/LCNF/Testing.c
  stage0/stdlib/Lean/Data/Array.c
  stage0/stdlib/Lean/DocString.c
  stage0/stdlib/Lean/Elab/Declaration.c
  stage0/stdlib/Lean/Elab/PreDefinition/Main.c
  stage0/stdlib/Lean/Elab/PreDefinition/WF/Fix.c
  stage0/stdlib/Lean/Elab/PreDefinition/WF/GuessLex.c
  stage0/stdlib/Lean/Elab/PreDefinition/WF/TerminationHint.c
  stage0/stdlib/Lean/Elab/Syntax.c
  stage0/stdlib/Lean/Meta/AppBuilder.c
  stage0/stdlib/Lean/Meta/CasesOn.c
  stage0/stdlib/Lean/Meta/IndPredBelow.c
  stage0/stdlib/Lean/Meta/LevelDefEq.c
  stage0/stdlib/Lean/Meta/Match/Match.c
  stage0/stdlib/Lean/Meta/Tactic/ElimInfo.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/Main.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/Rewrite.c
  stage0/stdlib/Lean/MetavarContext.c
  stage0/stdlib/Lean/Parser/Basic.c
  stage0/stdlib/Lean/Parser/Command.c
  stage0/stdlib/Lean/Parser/StrInterpolation.c
Labels: builds-mathlib, toolchain-available

#3044 chore: remove obsolete comment in test
  tests/lean/guessLex.lean
Labels: toolchain-available

#3047 doc: explain how to use custom lexers in the latest minted
  doc/syntax_highlight_in_latex.md
Labels: builds-mathlib, toolchain-available

#3042 chore: stage0 autoupdater action
  .github/workflows/update-stage0.yml
  doc/dev/bootstrap.md
Labels: builds-mathlib, toolchain-available

#3043 fix: Option.getD eagerly evaluates dflt
  src/Init/Prelude.lean
  tests/lean/optionGetD.lean
  tests/lean/optionGetD.lean.expected.out
  tests/lean/smartUnfoldingMatch.lean.expected.out
Labels: builds-mathlib, toolchain-available

#3033 feat: drop support for termination_by'
  RELEASES.md
  src/Lean/Elab/PreDefinition/Main.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/Rel.lean
  src/Lean/Elab/PreDefinition/WF/TerminationHint.lean
  src/Lean/Parser/Command.lean
  stage0/src/stdlib_flags.h
  tests/lean/906.lean
  tests/lean/letRecMissingAnnotation.lean
  tests/lean/mutwf1.lean
  tests/lean/mutwf1.lean.expected.out
  tests/lean/run/860.lean
  tests/lean/run/955.lean
  tests/lean/run/eqnsAtSimp.lean
  tests/lean/run/eqnsAtSimp2.lean
  tests/lean/run/mutwf1.lean
  tests/lean/run/mutwf2.lean
  tests/lean/run/mutwf3.lean
  tests/lean/run/nestedIssueMatch.lean
  tests/lean/run/nestedWF.lean
  tests/lean/run/robinson.lean
  tests/lean/run/wfEqns1.lean
  tests/lean/run/wfEqns2.lean
  tests/lean/run/wfEqns3.lean
  tests/lean/run/wfEqns4.lean
  tests/lean/run/wfSum.lean
  tests/lean/run/wfrecUnary.lean
  tests/lean/substBadMotive.lean
  tests/lean/termination_by.lean
  tests/lean/termination_by.lean.expected.out
  tests/lean/termination_by2.lean
  tests/lean/termination_by2.lean.expected.out
  tests/lean/unfold1.lean
  tests/lean/wf2.lean
  tests/lean/wfrecUnusedLet.lean
  tests/lean/wfrecUnusedLet.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2972 chore: make List.all and List.any short-circuit
  src/Init/Data/List/Basic.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#2923 chore: fix superfluous lemmas in simp.trace
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  tests/lean/simp_trace_backtrack.lean
  tests/lean/simp_trace_backtrack.lean.expected.out
Labels: breaks-mathlib, toolchain-available, will-merge-soon

#2969 fix: omit fvars from simp_all? theorem list
  src/Lean/Elab/Tactic/Simp.lean
  tests/lean/simp_trace.lean
  tests/lean/simp_trace.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3020 chore: refactor pr release workflow
  .github/workflows/pr-release.yml
  script/most-recent-nightly-tag.sh
Labels: toolchain-available

#2917 chore: withLocation * should not fail if it closes the main goal
  src/Lean/Elab/Tactic/Location.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon

#3035 fix: move Lean.List.toSMap to List.toSMap
  src/Lean/Data/SMap.lean
Labels: toolchain-available

#2959 fix: `run_task`/`deactivate_task` race condition on `m_imp->m_closure`
  src/runtime/object.cpp
Labels: builds-mathlib, toolchain-available

#2968 doc: update quickstart guide to reference vs code setup guide
  doc/images/setup_guide.png
  doc/images/show-setup-guide.png
  doc/quickstart.md
Labels: documentation

#3051 chore: robustify PR release workflow
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3055 chore: do not use actions-ecosystem/action-add-labels
  .github/workflows/pr-release.yml
Labels: toolchain-available, will-merge-soon

#2970 feat: test_extern command
  src/Lean/Util.lean
  src/Lean/Util/TestExtern.lean
  tests/lean/test_extern.lean
  tests/lean/test_extern.lean.expected.out
  tests/pkg/test_extern/TestExtern.lean
  tests/pkg/test_extern/TestExtern/BadExtern.lean
  tests/pkg/test_extern/expected.txt
  tests/pkg/test_extern/lakefile.lean
  tests/pkg/test_extern/test.sh
Labels: builds-mathlib, toolchain-available, full-ci

#3036 fix: lake: re-elab if config olean is missing
  src/lake/Lake/Load/Elab.lean
Labels: builds-mathlib, toolchain-available

#3061 chore: pr-release.yaml: remove hardcoded date
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3066 chore: pr-release.yml: use API to get pull request number
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3052 chore: allow updating stage0 via workflow_dispatch
  .github/workflows/update-stage0.yml
  doc/dev/bootstrap.md
Labels: awaiting-review, toolchain-available

#3072 chore: pr-release: revert to originally used action to get PR number
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3071 fix: don't panic in leanPosToLspPos
  src/Lean/Data/Lsp/Utf16.lean
Labels: awaiting-review, toolchain-available, will-merge-soon, full-ci

#2967 fix: reference implementation ByteArray.copySlice
  src/Init/Data/ByteArray/Basic.lean
  tests/lean/run/2966.lean
  tests/lean/test_extern.lean.expected.out
Labels: builds-mathlib, toolchain-available

#3086 doc: Bold "Diaconescu's theorem"
  src/Init/Classical.lean
Labels: toolchain-available

#2973 feat: encode `let_fun` using a `letFun` function
  src/Init/Prelude.lean
  src/Lean/Compiler/LCNF/ToLCNF.lean
  src/Lean/Elab/Binders.lean
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Expr.lean
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/WHNF.lean
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  stage0/src/runtime/object.cpp
  stage0/stdlib/Init/Data/List/Basic.c
  stage0/stdlib/Init/Prelude.c
  stage0/stdlib/Lean/Compiler/ConstFolding.c
  stage0/stdlib/Lean/Compiler/IR/ElimDeadBranches.c
  stage0/stdlib/Lean/Compiler/IR/EmitC.c
  stage0/stdlib/Lean/Compiler/IR/EmitLLVM.c
  stage0/stdlib/Lean/Compiler/IR/EmitUtil.c
  stage0/stdlib/Lean/Compiler/LCNF/ElimDeadBranches.c
  stage0/stdlib/Lean/Compiler/LCNF/PullFunDecls.c
  stage0/stdlib/Lean/Compiler/LCNF/ToLCNF.c
  stage0/stdlib/Lean/Data/SMap.c
  stage0/stdlib/Lean/Elab/App.c
  stage0/stdlib/Lean/Elab/Binders.c
  stage0/stdlib/Lean/Elab/LetRec.c
  stage0/stdlib/Lean/Elab/MutualDef.c
  stage0/stdlib/Lean/Elab/PreDefinition/Eqns.c
  stage0/stdlib/Lean/Elab/Quotation.c
  stage0/stdlib/Lean/Elab/StructInst.c
  stage0/stdlib/Lean/Elab/Structure.c
  stage0/stdlib/Lean/Elab/Tactic/Delta.c
  stage0/stdlib/Lean/Elab/Tactic/Location.c
  stage0/stdlib/Lean/Elab/Tactic/Rewrite.c
  stage0/stdlib/Lean/Elab/Tactic/Simp.c
  stage0/stdlib/Lean/Elab/Tactic/Unfold.c
  stage0/stdlib/Lean/Elab/Term.c
  stage0/stdlib/Lean/Expr.c
  stage0/stdlib/Lean/Linter/UnusedVariables.c
  stage0/stdlib/Lean/Meta/AppBuilder.c
  stage0/stdlib/Lean/Meta/Basic.c
  stage0/stdlib/Lean/Meta/Match/Basic.c
  stage0/stdlib/Lean/Meta/Match/Match.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/Main.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/Rewrite.c
  stage0/stdlib/Lean/Meta/WHNF.c
  stage0/stdlib/Lean/PrettyPrinter/Delaborator/Basic.c
  stage0/stdlib/Lean/PrettyPrinter/Delaborator/Builtins.c
  stage0/stdlib/Lean/PrettyPrinter/Delaborator/TopDownAnalyze.c
  stage0/stdlib/Lean/Server/InfoUtils.c
  stage0/stdlib/Lean/Structure.c
  stage0/stdlib/Lean/Syntax.c
  stage0/stdlib/Lean/Widget/Diff.c
  tests/lean/1026.lean.expected.out
  tests/lean/heapSort.lean.expected.out
  tests/lean/letFun.lean
  tests/lean/letFun.lean.expected.out
Labels: breaks-mathlib, toolchain-available

#3088 refactor: generalize some `simp` methods
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
Labels: builds-mathlib, toolchain-available

#3077 refactor: move unpackArg etc. to WF.PackDomain/WF.PackMutual
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/PackDomain.lean
  src/Lean/Elab/PreDefinition/WF/PackMutual.lean
Labels: toolchain-available, will-merge-soon

#3074 chore: refine PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: toolchain-available, will-merge-soon

#3076 perf: improve avoidance of repeated Expr visits in unused variables linter
  src/Lean/Linter/UnusedVariables.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3078 feat: add `quot_precheck` for expression tree elaborators (`binop%`, etc.)
  src/Lean/Elab/Quotation/Precheck.lean
  tests/lean/binopQuotPrecheck.lean
  tests/lean/binopQuotPrecheck.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#3093 fix: fixing path of the generated binary in documentation
  doc/setup.md
Labels: toolchain-available

#3069 fix: lake: save config trace before elab
  src/lake/Lake/Load/Elab.lean
Labels: toolchain-available, will-merge-soon, full-ci

#3054 feat: snippet extension
  RELEASES.md
  src/Lean/Data/Lsp/Basic.lean
Labels: toolchain-available, will-merge-soon

#3097 chore: pr-release: Also work with older tags
  .github/workflows/pr-release.yml
Labels: toolchain-available

#2929 feat: Rust-style raw string literals
  RELEASES.md
  doc/lexical_structure.md
  src/Init/Meta.lean
  src/Lean/Parser/Basic.lean
  tests/lean/rawStringEOF.lean
  tests/lean/rawStringEOF.lean.expected.out
  tests/lean/run/rawStrings.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#2964 feat: bundle of widget improvements
  doc/examples/widgets.lean
  src/Lean/Attributes.lean
  src/Lean/Elab/InfoTree/Main.lean
  src/Lean/Elab/InfoTree/Types.lean
  src/Lean/Server/Rpc/Basic.lean
  src/Lean/Server/Rpc/Deriving.lean
  src/Lean/Widget/Basic.lean
  src/Lean/Widget/Types.lean
  src/Lean/Widget/UserWidget.lean
  tests/lean/derivingRpcEncoding.lean
  tests/lean/derivingRpcEncoding.lean.expected.out
  tests/lean/interactive/run.lean
  tests/lean/interactive/userWidget.lean
  tests/lean/interactive/userWidget.lean.expected.out
Labels: builds-mathlib, toolchain-available, full-ci

#3098 doc: avoid universe issue in example type class code
  doc/typeclass.md
Labels: toolchain-available

#3092 chore: update tests for #2966 to use test_extern
  tests/lean/run/2966.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#3109 chore: begin development cycle for v4.6.0
  RELEASES.md
  src/CMakeLists.txt
Labels: toolchain-available

#3084 fix: hover info for `cases h : ...`
  src/Lean/Elab/Tactic/Induction.lean
  tests/lean/interactive/hover.lean
  tests/lean/interactive/hover.lean.expected.out
Labels: toolchain-available

#3105 chore: remove workaround in widgets
  src/Lean/Widget/UserWidget.lean
Labels: toolchain-available

#3104 chore: include full build in stdlib benchmark
  tests/bench/accumulate_profile.py
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#3114 doc: fix typos
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Meta/InferType.lean
  src/Lean/Util/Trace.lean
Labels: toolchain-available

#3122 test: test “motive is not type correct”
  tests/lean/motiveNotTypeCorect.lean
  tests/lean/motiveNotTypeCorect.lean.expected.out
Labels: toolchain-available

#3123 chore: remove unused argument at `DiscrTree`
  src/Lean/Meta/DiscrTree.lean
  src/Lean/Meta/Instances.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  src/Lean/Meta/UnificationHint.lean
Labels: toolchain-available
