Repository leanprover/lean4, pull requests merged in 2024-10, with the labels that each got.

#5486 feat: lake: Reservoir build cache
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Basic.lean
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Info.lean
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/Config/Env.lean
  src/lake/Lake/Config/Monad.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Load/Config.lean
  src/lake/Lake/Load/Lean.lean
  src/lake/Lake/Load/Materialize.lean
  src/lake/Lake/Load/Package.lean
  src/lake/Lake/Load/Resolve.lean
  src/lake/Lake/Load/Toml.lean
  src/lake/Lake/Reservoir.lean
  src/lake/tests/noRelease/test.sh
  src/lake/tests/online/barrel.lean
  src/lake/tests/online/require.lean
  src/lake/tests/online/require.toml
  src/lake/tests/online/test.sh
Labels: builds-mathlib, toolchain-available, release-ci

#5546 doc: update README w/ Reservoir package options
  src/lake/Lake/Config/Package.lean
  src/lake/README.md
Labels: builds-mathlib, toolchain-available, backport releases/v4.12.0

#5549 chore: release notes for 4.12.0
  RELEASES.md
  releases_drafts/hashmap.md
  releases_drafts/libuv.md
Labels: toolchain-available

#5508 feat: add BitVec.getElem_[add|add_add_bool|mul|rotateLeft|rotateRight…
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5529 chore: move `@[simp]` from `exists_prop'` to `exists_prop`
  src/Init/Classical.lean
  src/Init/PropLemmas.lean
Labels: builds-mathlib, toolchain-available

#5524 feat: add ac_nf and test [ac_nf|ac_rfl] for BitVec
  src/Init/Tactics.lean
  src/Lean/Meta/Tactic/AC/Main.lean
  tests/lean/run/ac_rfl.lean
Labels: toolchain-available

#5552 chore: switch obvious cases of array "bang"`[]!` indexing to rely on hypothesis
  src/Lean/Compiler/IR/SimpCase.lean
  src/Lean/Compiler/LCNF/Check.lean
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
  src/Lean/Compiler/LCNF/MonoTypes.lean
  src/Lean/Compiler/LCNF/PullFunDecls.lean
  src/Lean/Compiler/LCNF/Simp/DefaultAlt.lean
  src/Lean/Compiler/LCNF/Simp/JpCases.lean
  src/Lean/Compiler/LCNF/SpecInfo.lean
  src/Lean/Compiler/LCNF/ToDecl.lean
  src/Lean/Elab/App.lean
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Elab/DeclNameGen.lean
  src/Lean/Elab/Deriving/Inhabited.lean
  src/Lean/Elab/Deriving/Repr.lean
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/Match.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Nonrec/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/Quotation.lean
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Elab/Tactic/Omega/Core.lean
  src/Lean/Environment.lean
  src/Lean/LocalContext.lean
  src/Lean/Meta/ACLt.lean
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/ArgsPacker.lean
  src/Lean/Meta/CongrTheorems.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/FunInfo.lean
  src/Lean/Meta/IndPredBelow.lean
  src/Lean/Meta/PProdN.lean
  src/Lean/Meta/RecursorInfo.lean
  src/Lean/Meta/Reduce.lean
  src/Lean/Meta/SizeOf.lean
  src/Lean/Meta/Tactic/ElimInfo.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/Server/References.lean
Labels: toolchain-available

#5554 feat: add `Bitvec.[add, sub, mul]_eq_xor` and `width_one_cases`
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5556 feat: expand `invalid projection` type inference error
  src/Lean/Meta/InferType.lean
Labels: builds-mathlib, toolchain-available

#5496 refactor: dead code AttributeExtensionOLeanEntry.decl
  src/Lean/Attributes.lean
Labels: builds-mathlib, toolchain-available, release-ci

#5558 fix: make lean.h compile with MSVC
  src/include/lean/lean.h
Labels: toolchain-available

#5564 fix: remove non-conforming size-0 arrays
  src/include/lean/lean.h
Labels: toolchain-available

#5567 refactor: more idiomatic syntax for `if h:`
  src/Init/Data/ByteArray/Basic.lean
  src/Lean/Compiler/IR/SimpCase.lean
  src/Lean/Compiler/LCNF/Check.lean
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
  src/Lean/Compiler/LCNF/MonoTypes.lean
  src/Lean/Compiler/LCNF/PullFunDecls.lean
  src/Lean/Compiler/LCNF/Simp/DefaultAlt.lean
  src/Lean/Compiler/LCNF/Simp/JpCases.lean
  src/Lean/Compiler/LCNF/SpecInfo.lean
  src/Lean/Compiler/LCNF/ToDecl.lean
  src/Lean/Elab/App.lean
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Elab/DeclNameGen.lean
  src/Lean/Elab/Deriving/Inhabited.lean
  src/Lean/Elab/Deriving/Repr.lean
  src/Lean/Elab/Do.lean
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/Match.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Nonrec/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/Quotation.lean
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVPred.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Elab/Tactic/Omega/Core.lean
  src/Lean/Environment.lean
  src/Lean/LocalContext.lean
  src/Lean/Meta/ACLt.lean
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/ArgsPacker.lean
  src/Lean/Meta/CongrTheorems.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/FunInfo.lean
  src/Lean/Meta/IndPredBelow.lean
  src/Lean/Meta/PProdN.lean
  src/Lean/Meta/RecursorInfo.lean
  src/Lean/Meta/Reduce.lean
  src/Lean/Meta/SizeOf.lean
  src/Lean/Meta/Tactic/ElimInfo.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/Server/References.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftRight.lean
  src/Std/Tactic/BVDecide/LRAT/Parser.lean
  src/lake/Lake/Reservoir.lean
Labels: toolchain-available

#5568 feat: generalize the `bv_normalize` pipeline to support more general preprocessing passes
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVCheck.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available

#5573 feat: get bv_normalize up to date with the current BitVec rewrites
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available

#5572 feat: lake: selective build cache fetch & display
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/Build/Run.lean
  src/lake/Lake/Config/Monad.lean
  src/lake/tests/noRelease/test.sh
  src/lake/tests/online/git.toml
  src/lake/tests/online/test.sh
Labels: toolchain-available, release-ci

#5412 feat: expose Kernel.check for debugging purposes
  src/Lean/Environment.lean
  src/kernel/type_checker.cpp
  tests/lean/run/kernel2.lean
Labels: builds-mathlib, toolchain-available

#5551 chore: upstream Array.flatten lemmas
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
Labels: toolchain-available

#5577 chore: add missing simp to Array.size_feraseIdx
  src/Init/Data/Array/Basic.lean
Labels: toolchain-available

#5578 chore: cleanup unused variables in bv_decide
  src/Std/Sat/AIG/CNF.lean
  src/Std/Sat/AIG/RefVecOperator/Zip.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Carry.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Mul.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/ShiftLeft.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/ShiftRight.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Carry.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Mul.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftLeft.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftRight.lean
Labels: toolchain-available

#5579 chore: cleanup unused variables
  src/Init/Control/Lawful/Basic.lean
  src/Init/Control/Lawful/Instances.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Erase.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/Erase.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Perm.lean
  src/Init/Data/List/Range.lean
  src/Init/Data/List/Sort/Impl.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/List/Zip.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Div.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Data/String/Basic.lean
  src/Init/PropLemmas.lean
  src/Init/WF.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Array.lean
Labels: toolchain-available

#5583 fix: `--no-cache` on server `DependencyBuildMode.never`
  src/Lean/Server/FileWorker/SetupFile.lean
Labels: toolchain-available

#5550 feat: List.unattach and simp lemmas
  src/Init/Data/List/Attach.lean
  tests/lean/run/nested_inductive.lean
  tests/lean/run/simpHigherOrder.lean
Labels: toolchain-available

#5541 fix: rm new shared libs before build for Windows
  src/stdlib.make.in
Labels: needs-update-stage0, builds-mathlib, toolchain-available, release-ci

#5581 feat: Singleton/Insert/Union instances for HashMap/Set
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashSet/Basic.lean
  tests/lean/run/hashmap.lean
Labels: toolchain-available

#5582 feat: HashSet.all/any
  src/Std/Data/HashSet/Basic.lean
  tests/lean/run/hashmap.lean
Labels: toolchain-available

#5587 feat: allow MVarId.assertHypotheses to set BinderInfo/Kind
  src/Lean/Meta/Tactic/Assert.lean
Labels: toolchain-available

#5588 feat: variant of MVarId.tryClearMany
  src/Lean/Meta/Tactic/Clear.lean
Labels: toolchain-available

#5591 feat: HashSet.Raw.all/any
  src/Std/Data/HashSet/Raw.lean
  tests/lean/run/hashmap.lean
Labels: toolchain-available

#5594 chore: induction-friendly `List.min?_cons`
  src/Init/Data/List/MinMax.lean
  src/Init/Data/List/Nat/Basic.lean
Labels: builds-mathlib, toolchain-available

#5599 chore: fix spelling mistakes
  RELEASES.md
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Tactics.lean
  src/Lean/Elab/App.lean
  src/Lean/Elab/StructInst.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
Labels: toolchain-available

#5601 chore: typo in fix-pr-release.yml
  .github/workflows/pr-release.yml
Labels: toolchain-available

#5600 refactor: reduce Reservoir build fetch attempts & warnings
  src/lake/Lake/Build/Package.lean
  src/lake/tests/noRelease/test.sh
  src/lake/tests/online/test.sh
Labels: toolchain-available

#5590 feat: adding Insert/Singleton/Union instances for HashMap/Set.Raw
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/Raw.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Basic.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/Raw.lean
  src/Std/Data/HashSet/RawLemmas.lean
  tests/lean/run/hashmap.lean
Labels: toolchain-available

#5586 feat: Array/Option.unattach
  src/Init/Data/Array/Attach.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/Option/Attach.lean
  tests/lean/run/nested_inductive.lean
Labels: toolchain-available

#5560 fix: call hierarchy into `(builtin_)initialize`
  src/Lean/DeclarationRange.lean
  src/Lean/Elab/Declaration.lean
Labels: builds-mathlib, toolchain-available

#5605 perf: remove List.redLength
  src/Init/Data/Array/Basic.lean
  src/Init/Data/List.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Prelude.lean
Labels: builds-mathlib, toolchain-available

#5608 chore: add bv_toNat tag for toNat_ofInt
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5563 fix: getFunInfo, inferType to use withAtLeastTransparency, not withTransparency
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/FunInfo.lean
  src/Lean/Meta/InferType.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/issue2975.lean
  tests/lean/run/issue5562.lean
Labels: builds-mathlib, toolchain-available

#5618 feat: support `at` in `ac_nf` and use it in `bv_normalize`
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Attr.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/LRAT.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Lean/Meta/Tactic/AC/Main.lean
  tests/lean/run/ac_rfl.lean
  tests/lean/run/bv_arith.lean
  tests/lean/run/bv_axiom_check.lean
  tests/lean/run/bv_bitblast_stress.lean
  tests/lean/run/bv_bitwise.lean
  tests/lean/run/bv_decide_rewriter.lean
  tests/lean/run/bv_errors.lean
  tests/lean/run/bv_substructure.lean
Labels: toolchain-available, will-merge-soon

#5620 feat: Document Bitblasting in a documentation comment
  src/Init/Data/BitVec/Bitblast.lean
Labels: builds-mathlib, toolchain-available

#5617 chore: fix MSYS2 build instructions
  doc/make/msys2.md
Labels: toolchain-available

#5340 fix: shutdown deadlock and crash desync
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/Watchdog.lean
Labels: builds-mathlib, toolchain-available

#5609 feat: lemmas for Bitvector division when denominator is zero
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5635 feat: add auxiliary bitblasters for negation and subtraction
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Neg.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Sub.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Neg.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Sub.lean
Labels: toolchain-available

#5636 doc: remarks about multiplication
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Mul.lean
  tests/lean/run/bv_arith.lean
Labels: toolchain-available

#5637 feat: more getLsbD bitblaster theory
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/GetLsbD.lean
Labels: toolchain-available

#5619 fix: FunInd: avoid over-eta-expanding in preprocessing step
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/issue5602.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5647 chore: add Siddharth to authors list of BitVec
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5645 chore: define udiv normal form to be /, resp. umod and %
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5628 feat: support udiv in bv_decide
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reflect.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVExpr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Basic.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Udiv.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Udiv.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  src/Std/Tactic/BVDecide/Normalize/Canonicalize.lean
  src/Std/Tactic/BVDecide/Reflect.lean
  tests/lean/run/bv_arith.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available

#5652 feat: support umod in bv_decide
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reflect.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVExpr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Basic.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Umod.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Umod.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  src/Std/Tactic/BVDecide/Normalize/Canonicalize.lean
  src/Std/Tactic/BVDecide/Reflect.lean
  tests/lean/run/bv_arith.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available

#5640 fix: have `Lean.Meta.ppGoal` use hard newlines
  src/Lean/Meta/PPGoal.lean
  tests/lean/issue2981.lean.expected.out
  tests/lean/simpDisch.lean.expected.out
Labels: toolchain-available

#5644 fix: now linters in general do not run on `#guard_msgs` itself
  src/Init/Notation.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/GuardMsgs.lean
  src/Lean/Linter/UnusedVariables.lean
  tests/lean/run/guard_msgs.lean
Labels: breaks-mathlib, toolchain-available

#5639 fix: make sure name literals use escaping when pretty printing
  src/Init/NotationExtra.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/1275.lean.expected.out
  tests/lean/ppNotationCode.lean.expected.out
  tests/lean/run/delabName.lean
Labels: builds-mathlib, toolchain-available

#5653 perf: benchmark for modulo on bv_decide
  tests/bench/bv_decide_mod.lean
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#5655 chore: reduce error on bv_check to warning
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVCheck.lean
Labels: toolchain-available

#5517 feat: infer `Prop` for `inductive`/`structure` when defining syntactic subsingletons
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/Structure.lean
  tests/lean/1074b.lean
  tests/lean/etaStructIssue.lean
  tests/lean/run/1074a.lean
  tests/lean/run/2690.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#5641 fix: lake: make package `extraDep` intransitive
  src/lake/Lake/Build/Package.lean
  src/lake/tests/noRelease/Test.lean
  src/lake/tests/noRelease/dep/Dep.lean
  src/lake/tests/noRelease/dep/lakefile.lean
  src/lake/tests/noRelease/test.sh
  src/lake/tests/online/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon, backport releases/v4.13.0

#5399 fix: upgrade instance synth order issues to hard errors
  src/Lean/Meta/Instances.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#5566 fix: use `MessageData.tagged` to mark maxHeartbeat exceptions
  src/Lean/CoreM.lean
  src/Lean/Exception.lean
  tests/lean/run/3554.lean
  tests/lean/run/5565.lean
  tests/lean/run/isDefEqProjIssue.lean
  tests/lean/tcloop.lean.expected.out
Labels: builds-mathlib, toolchain-available

#5658 fix: store local context for 'don't know how to synthesize implicit argument' errors
  src/Lean/Elab/Term.lean
  tests/lean/run/5475.lean
Labels: toolchain-available

#5666 feat: whitespace tactic completion & tactic completion docs
  src/Lean/Elab/InfoTree/Types.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Server/Completion.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/InfoUtils.lean
  src/Lean/Server/Requests.lean
  tests/lean/interactive/completionTactics.lean
  tests/lean/interactive/completionTactics.lean.expected.out
Labels: toolchain-available

#5671 fix: make `@[elab_as_elim]` require at least one discriminant
  src/Lean/Elab/App.lean
  tests/lean/run/elabAsElim.lean
Labels: toolchain-available

#5670 feat: ~~~(-x) bv_decide
  src/Init/Data/BitVec/Lemmas.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/5664.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available

#5542 chore: deprecate `:=` variants of `inductive` and `structure`
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Linter/Basic.lean
  tests/lean/linterMissingDocs.lean
  tests/lean/run/5236.lean
Labels: breaks-mathlib, toolchain-available

#5665 feat: `decide!` tactic for using kernel reduction
  src/Lean/Elab/Tactic/ElabTerm.lean
  src/Lean/Meta/Transform.lean
  src/Lean/Parser/Tactic.lean
  tests/lean/interactive/completionTactics.lean.expected.out
  tests/lean/letRecTheorem.lean.expected.out
  tests/lean/run/decideBang.lean
Labels: builds-mathlib, toolchain-available

#5663 feat: support `let rec` in `#eval`
  src/Lean/Elab/BuiltinEvalCommand.lean
  tests/lean/run/eval.lean
  tests/lean/run/meta5.lean
Labels: builds-mathlib, toolchain-available

#5675 fix: context tracking in bv_decide counter example
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVCheck.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/LRAT.lean
  tests/lean/run/5674.lean
Labels: toolchain-available

#5676 feat: make bv_decide error when the LRAT proof is invalid
  src/Lean/Elab/Tactic/BVDecide/Frontend/LRAT.lean
Labels: toolchain-available

#5678 fix: make IO-bound tasks dedicated
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/Watchdog.lean
Labels: toolchain-available

#5642 refactor: lake: restrict cache fetch to leanprover*
  src/lake/Lake/Build/Package.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, backport releases/v4.13.0

#5685 fix: help message flags, removes -f flag and adds -g flag
  src/util/shell.cpp
Labels: toolchain-available

#5680 feat: expand relationship with BitVec and toFin
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5604 feat: complete `BitVec.[getMsbD|getLsbD|msb]` for shifts
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5623 chore: move BitVec.udiv/umod/sdiv/smod after add/sub/mul/lt
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5693 chore: import orphaned Lean.Replay
  src/Lean.lean
Labels: toolchain-available

#5696 feat: upstream List.mapIdx, and add lemmas
  src/Init/Data.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Function.lean
  src/Init/Data/List.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/MapIdx.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Zip.lean
Labels: builds-mathlib, toolchain-available

#5646 feat: lemmas about BitVector arithmetic inequalities
  src/Init/Data/BitVec/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5706 chore: mark prefix_append_right_inj as simp lemma
  src/Init/Data/List/Sublist.lean
Labels: toolchain-available

#5707 feat: denote deprecations in completion items
  src/Lean/Data/Lsp/LanguageFeatures.lean
  src/Lean/Server/Completion.lean
  tests/lean/interactive/completionDeprecation.lean
  tests/lean/interactive/completionDeprecation.lean.expected.out
Labels: toolchain-available

#5135 feat: use libuv for tempfiles
  .github/workflows/ci.yml
  flake.nix
  script/prepare-llvm-linux.sh
  script/prepare-llvm-mingw.sh
  src/CMakeLists.txt
  src/include/lean/lean.h
  src/runtime/io.cpp
  src/runtime/io.h
Labels: toolchain-available, release-ci

#5710 fix: the `⋯` elaboration warning did not mention `pp.maxSteps`
  src/Lean/Elab/BuiltinTerm.lean
  tests/lean/ppDeepTerms.lean.expected.out
Labels: toolchain-available

#5712 feat: add BitVec.[udiv|umod]_[zero|one|self] theorems
  src/Init/Data/BitVec/Lemmas.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
Labels: toolchain-available

#5673 chore: disable ac_nf by default
  src/Lean/Elab/Tactic/BVDecide/External.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Attr.lean
  src/Std/Tactic/BVDecide/Syntax.lean
  tests/lean/run/bv_decide_rewriter.lean
  tests/lean/run/bv_errors.lean
Labels: toolchain-available

#5711 feat: options `pp.mvars.anonymous` and `pp.mvars.levels`
  src/Lean/Meta/Tactic/TryThis.lean
  src/Lean/PrettyPrinter.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  src/Lean/Widget/InteractiveCode.lean
  tests/lean/run/ppMVars.lean
Labels: builds-mathlib, toolchain-available

#5692 feat: let dot notation see through `CoeFun` instances
  src/Lean/Elab/App.lean
  tests/lean/run/1910.lean
Labels: builds-mathlib, toolchain-available

#5705 chore: better default value for Array.swapAt!
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
Labels: toolchain-available, merge-ci

#5703 chore: upstream List.sum, planning to later deprecate Nat.sum
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Range.lean
Labels: toolchain-available

#5714 feat: bv_decide inequality regression tests
  tests/bench/bv_decide_inequality.lean
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#5722 chore: rename `instDecidableEqQuotientOfDecidableEquiv` to `Quotient.decidableEq`
  src/Init/Core.lean
Labels: toolchain-available

#5718 feat: add BitVec.sdiv_[zero|one|self] theorems
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5716 fix: List.drop_drop addition order
  src/Init/Data/List/Sublist.lean
  src/Init/Data/List/TakeDrop.lean
Labels: builds-mathlib, toolchain-available

#5681 refactor: remove mkRecursorInfoForKernelRec
  src/Lean/Meta/RecursorInfo.lean
Labels: builds-mathlib, toolchain-available

#5632 fix: simpproc to reduce Fin literals consistently
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Fin.lean
  tests/lean/run/issue5630.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5727 chore: make getIntrosize public
  src/Lean/Meta/Tactic/Intro.lean
Labels: toolchain-available

#5728 chore: upstream String.dropPrefix?
  src/Init/Data/String/Basic.lean
Labels: toolchain-available

#5729 feat: Expr helper functions
  src/Lean/Expr.lean
Labels: toolchain-available

#5730 chore: upstream `classical` tactic
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/Classical.lean
  tests/lean/run/classical.lean
Labels: toolchain-available

#5720 feat: push/pop tactic API
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/Calc.lean
  src/Lean/Elab/Tactic/ElabTerm.lean
Labels: builds-mathlib, toolchain-available

#5694 chore: remove instBEqNat, which is redundant with instBEqOfDecidableEq but not defeq
  src/Init/Data/Nat/Basic.lean
  src/Init/Prelude.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Nat.lean
  tests/lean/eagerCoeExpansion.lean.expected.out
  tests/lean/phashmap_inst_coherence.lean.expected.out
Labels: builds-mathlib, toolchain-available

#5323 refactor: redefine unsigned fixed width integers in terms of BitVec
  src/Init/Core.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/BasicAux.lean
  src/Init/Data/Char/Basic.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Power2.lean
  src/Init/Data/Repr.lean
  src/Init/Data/String/Extra.lean
  src/Init/Data/ToString/Basic.lean
  src/Init/Data/UInt.lean
  src/Init/Data/UInt/Basic.lean
  src/Init/Data/UInt/BasicAux.lean
  src/Init/Data/UInt/Bitwise.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Init/Data/UInt/Log2.lean
  src/Init/Prelude.lean
  src/Init/SizeOf.lean
  src/Init/SizeOfLemmas.lean
  src/Lean/Data/PersistentArray.lean
  src/Lean/Data/PersistentHashMap.lean
  src/Lean/ToExpr.lean
  src/Std/Data/DHashMap/Internal/Index.lean
  src/Std/Tactic/BVDecide/Normalize/Canonicalize.lean
  src/lake/Lake/Util/Compare.lean
  tests/lean/run/4465.lean
  tests/lean/sizeof.lean.expected.out
  tests/lean/uintCtors.lean
Labels: builds-mathlib, toolchain-available

#5224 fix: make applyEdit optional in WorkspaceClientCapabilities of LSP
  src/Lean/Data/Lsp/Capabilities.lean
  tests/lean/server/init_exit_with_zed.lean
  tests/lean/server/init_zed_0_150_4.log
Labels: awaiting-review, toolchain-available, P-medium

#5708 fix: ac_nf0, simp_arith: don't tempt the kernel to reduce atoms
  src/Lean/Meta/Tactic/AC/Main.lean
  src/Lean/Meta/Tactic/LinearArith/Nat/Simp.lean
  tests/lean/run/issue5384.lean
  tests/lean/run/issue5699.lean
Labels: builds-mathlib, toolchain-available

#5731 chore: rename List.bind and Array.concatMap to flatMap
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Impl.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Data/List/Perm.lean
  src/Init/Data/String/Extra.lean
  src/Lean/Data/Xml/Parser.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Server/CodeActions/Basic.lean
  src/Lean/Server/CodeActions/Provider.lean
  src/Lean/Server/InfoUtils.lean
  src/Lean/Server/Watchdog.lean
  src/Std/Data/DHashMap/Internal/Defs.lean
  src/Std/Data/DHashMap/Internal/List/Associative.lean
  src/Std/Data/DHashMap/Internal/Model.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/lake/Lake/Build/Imports.lean
  src/lake/Lake/Build/Library.lean
  src/lake/Lake/CLI/Build.lean
  src/lake/Lake/Util/OrderedTagAttribute.lean
Labels: builds-mathlib, toolchain-available

#5735 feat: UIntX.[val_ofNat, toBitVec_ofNat]
  src/Init/Data/UInt/Lemmas.lean
  src/Lean/Data/HashMap.lean
  src/Lean/Data/HashSet.lean
  tests/lean/run/trivial_uint.lean
Labels: toolchain-available

#5736 fix: don't block on snapshot tree if tracing is not enabled
  src/Lean/Elab/Command.lean
Labels: toolchain-available, backport releases/v4.13.0

#5732 chore: rename List.pure to List.singleton
  src/Init/Data/List/Basic.lean
Labels: builds-mathlib, toolchain-available

#5739 chore: upstream material on Prod
  src/Init/Data/Prod.lean
Labels: toolchain-available

#5742 chore: upstream ne_of_mem_of_not_mem
  src/Init/PropLemmas.lean
Labels: toolchain-available

#5743 chore: upstream ne_of_apply_ne
  src/Init/PropLemmas.lean
Labels: toolchain-available

#5741 chore: upstream basic material on Sum
  src/Init/Data/Sum.lean
  src/Init/Data/Sum/Basic.lean
  src/Init/Data/Sum/Lemmas.lean
  tests/lean/run/nofun1.lean
Labels: toolchain-available

#5740 chore: move Antisymm to Std.Antisymm
  src/Init/Core.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/MinMax.lean
  src/Init/Data/Nat/Basic.lean
Labels: breaks-mathlib, toolchain-available

#5744 chore: cleanup in Array/Lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddSound.lean
Labels: toolchain-available

#5745 fix: change String.dropPrefix? signature
  src/Init/Data/String/Basic.lean
Labels: toolchain-available

#5697 chore: upstream List.foldxM_map
  src/Init/Data/List/Monadic.lean
Labels: builds-mathlib, toolchain-available

#5715 feat: change `lake new math` to use `autoImplicit false`
  src/lake/Lake/CLI/Init.lean
Labels: toolchain-available

#5725 doc: point out that `OfScientific` is called with raw literals
  src/Init/Data/OfScientific.lean
Labels: toolchain-available

#5748 chore: move Array.mapIdx lemmas to new file
  src/Init/Data/Array.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/MapIdx.lean
Labels: toolchain-available

#5571 chore: remove `SplitIf.ext` cache
  src/Lean.lean
  src/Lean/LazyInitExtension.lean
  src/Lean/Meta/Tactic/SplitIf.lean
Labels: builds-mathlib, toolchain-available

#5751 doc: remove docstring from implicitDefEqProofs
  src/Init/MetaTypes.lean
Labels: toolchain-available

#5338 perf: do not lint unused variables defined in tactics by default
  src/Init/Data/Option/Attach.lean
  src/Lean/Elab/LetRec.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Linter/ConstructorAsVariable.lean
  src/Lean/Linter/UnusedVariables.lean
  src/Lean/Server/InfoUtils.lean
  tests/lean/1018unknowMVarIssue.lean.expected.out
  tests/lean/linterUnusedVariables.lean
  tests/lean/linterUnusedVariables.lean.expected.out
Labels: builds-mathlib, toolchain-available, merge-ci

#5677 fix: some goal state issues
  src/Init/Tactics.lean
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Induction.lean
  tests/lean/1021.lean.expected.out
  tests/lean/interactive/2881.lean
  tests/lean/interactive/2881.lean.expected.out
Labels: builds-mathlib, toolchain-available

#5752 fix: do not force snapshot tree too early
  src/Lean/Language/Basic.lean
Labels: toolchain-available

#5747 feat: add Hashable instance for Char
  src/Init/Data/Hashable.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5746 chore: deprecate Nat.sum
  src/Init/Data/List/Basic.lean
Labels: builds-mathlib, toolchain-available

#5758 chore: upstream Array.reduceOption
  src/Init/Data/Array/Basic.lean
Labels: toolchain-available

#5759 fix: app unexpander for `sorryAx`
  src/Init/NotationExtra.lean
  tests/lean/1074b.lean.expected.out
  tests/lean/1301.lean.expected.out
  tests/lean/255.lean.expected.out
  tests/lean/StxQuot.lean.expected.out
  tests/lean/binrelTypeMismatch.lean.expected.out
  tests/lean/defInst.lean.expected.out
  tests/lean/macroSwizzle.lean.expected.out
  tests/lean/nameArgErrorIssue.lean.expected.out
  tests/lean/namedHoles.lean.expected.out
  tests/lean/noTabs.lean.expected.out
  tests/lean/run/1163.lean
  tests/lean/run/1910.lean
  tests/lean/run/2283.lean
  tests/lean/run/3554.lean
  tests/lean/run/3943.lean
  tests/lean/run/4365.lean
  tests/lean/run/4670.lean
  tests/lean/run/4920.lean
  tests/lean/run/CoeNew.lean
  tests/lean/run/autoLift.lean
  tests/lean/run/sorry.lean
Labels: toolchain-available

#5760 feat: `Lean.Expr.name?`
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/Util/Recognizers.lean
  tests/lean/run/677.lean
Labels: toolchain-available

#5687 chore: deprecation for Array.data
  src/Init/Data/Array/Basic.lean
Labels: toolchain-available, merge-ci

#5764 chore: check-prelude also for Std
  .github/workflows/check-prelude.yml
  src/Std/Sat/AIG.lean
  src/Std/Sat/AIG/Basic.lean
  src/Std/Sat/AIG/CNF.lean
  src/Std/Sat/AIG/Cached.lean
  src/Std/Sat/AIG/CachedGates.lean
  src/Std/Sat/AIG/CachedGatesLemmas.lean
  src/Std/Sat/AIG/CachedLemmas.lean
  src/Std/Sat/AIG/If.lean
  src/Std/Sat/AIG/LawfulOperator.lean
  src/Std/Sat/AIG/LawfulVecOperator.lean
  src/Std/Sat/AIG/Lemmas.lean
  src/Std/Sat/AIG/RefVec.lean
  src/Std/Sat/AIG/RefVecOperator.lean
  src/Std/Sat/AIG/RefVecOperator/Fold.lean
  src/Std/Sat/AIG/RefVecOperator/Map.lean
  src/Std/Sat/AIG/RefVecOperator/Zip.lean
  src/Std/Sat/AIG/Relabel.lean
  src/Std/Sat/AIG/RelabelNat.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Expr.lean
Labels: toolchain-available

#5765 chore: @hargoniX Std.Sat codeowner, fix Kim's user name
  CODEOWNERS
Labels: toolchain-available

#5650 fix: include references in attributes in call hierarchy
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/BuiltinEvalCommand.lean
  src/Lean/Elab/DeclModifiers.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/DeclarationRange.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/PreDefinition/Structural/SmartUnfolding.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Elab/Tactic/Ext.lean
  src/Lean/Elab/Term.lean
  tests/lean/docStr.lean.expected.out
  tests/lean/interactive/goTo.lean.expected.out
Labels: breaks-mathlib, toolchain-available

#5766 fix: structural nested recursion confused when nested type appears first
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Elab/PreDefinition/Structural/Main.lean
  src/Lean/Meta/InferType.lean
  tests/lean/run/issue5726.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5768 feat: `#version` command
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Parser/Command.lean
Labels: toolchain-available

#5688 fix: have `Lake` not create core aliases into `Lake` namespace
  src/lake/Lake/Build/Executable.lean
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Index.lean
  src/lake/Lake/Build/Info.lean
  src/lake/Lake/Build/Key.lean
  src/lake/Lake/Build/Library.lean
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/Build/Store.lean
  src/lake/Lake/Build/Targets.lean
  src/lake/Lake/CLI/Actions.lean
  src/lake/Lake/CLI/Build.lean
  src/lake/Lake/CLI/Init.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/Config/ExternLib.lean
  src/lake/Lake/Config/FacetConfig.lean
  src/lake/Lake/Config/Monad.lean
  src/lake/Lake/Config/TargetConfig.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/Lake/DSL/Targets.lean
  src/lake/Lake/Load/Package.lean
  src/lake/Lake/Load/Toml.lean
  src/lake/Lake/Util/Name.lean
  src/lake/examples/targets/lakefile.lean
Labels: toolchain-available

#5781 feat: bv_decide introduces uninterpreted symbols everywhere
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVExpr.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVLogical.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVPred.lean
  tests/lean/run/bv_uninterpreted.lean
Labels: toolchain-available

#5749 chore: simplify signature of Array.mapIdx
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/MapIdx.lean
  src/Lean/Elab/Syntax.lean
  src/Lean/Elab/Tactic/Conv/Pattern.lean
  src/Lean/Meta/IndPredBelow.lean
  src/Lean/Meta/Match/CaseArraySizes.lean
  src/Lean/Meta/Match/Match.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Parser/Extra.lean
  src/Lean/Server/Completion.lean
Labels: awaiting-mathlib, breaks-mathlib, toolchain-available, release-ci

#5784 chore: make 'while' available earlier
  src/Init.lean
  src/Init/NotationExtra.lean
  src/Init/While.lean
Labels: toolchain-available

#5782 chore: Array cleanup
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/MapIdx.lean
  src/Init/Data/List/Lemmas.lean
  src/Std/Sat/AIG/Basic.lean
  src/Std/Sat/AIG/Cached.lean
  src/Std/Sat/AIG/CachedLemmas.lean
  src/Std/Sat/AIG/Lemmas.lean
  src/Std/Sat/AIG/RefVec.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  tests/lean/simpArrayIdx.lean
Labels: toolchain-available

#5785 feat: Nat.forall_lt_succ and variants
  src/Init/Data/Nat/Lemmas.lean
Labels: toolchain-available

#5786 feat: simp lemmas for Array.isEqv and beq
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Bootstrap.lean
  src/Init/Data/Array/DecidableEq.lean
  src/Init/Data/Array/GetLit.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Nat.lean
  src/Init/Data/List/Nat/BEq.lean
  tests/lean/run/array_isEqvAux.lean
Labels: toolchain-available

#5679 fix: RecursorVal.getInduct to return name of major argument’s type
  src/Lean/Declaration.lean
  src/Lean/Meta/WHNF.lean
  src/kernel/declaration.cpp
  src/kernel/declaration.h
  src/kernel/inductive.h
  tests/lean/run/issue5661.lean
Labels: builds-mathlib, toolchain-available

#5793 perf: `has_univ_mvar`, `has_univ_mvar`, and `has_fvar` in C++
  src/kernel/expr.cpp
  src/kernel/expr.h
Labels: toolchain-available

#5772 feat: add BitVec.toInt_sub, simplify BitVec.toInt_neg
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/DivModLemmas.lean
Labels: builds-mathlib, toolchain-available

#5796 feat: rename Array.shrink to take, and relate to List.take
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Lean/Compiler/LCNF/PullLetDecls.lean
  src/Lean/Elab/ParseImportsFast.lean
  src/Lean/Meta/Tactic/LinearArith/Solver.lean
  src/Lean/Meta/WHNF.lean
  src/Lean/Parser/Basic.lean
  src/Lean/Parser/Types.lean
  src/Lean/PrettyPrinter/Delaborator/TopDownAnalyze.lean
  src/Lean/PrettyPrinter/Formatter.lean
  src/lake/Lake/Util/Log.lean
  tests/playground/parser/parser.lean
Labels: toolchain-available

#5798 chore: upstream List.modify, add lemmas, relate to Array.modify
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Impl.lean
  src/Init/Data/List/Nat.lean
  src/Init/Data/List/Nat/Modify.lean
Labels: toolchain-available

#5799 feat: relate Array.forIn and List.forIn
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  tests/lean/run/array_simp.lean
Labels: toolchain-available

#5794 doc: stub for ellipsis notation
  src/Lean/Parser/Term.lean
Labels: toolchain-available

#5802 fix: restore synchronous fast-forwarding path in language processor
  src/Lean/Language/Lean.lean
Labels: toolchain-available
