Repository leanprover/lean4, pull requests merged in 2024-12, with the labels that each got.

#6268 chore: post-stage0 cleanup for #6165
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PatternVar.lean
  src/Lean/Elab/StructInst.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
Labels: toolchain-available, changelog-no

#6241 feat: remove runtime bounds checks and partial from qsort
  src/Init/Data/Array/QSort.lean
  tests/bench/qsort/.gitignore
  tests/bench/qsort/Main.lean
  tests/bench/qsort/README.md
  tests/bench/qsort/lakefile.toml
  tests/bench/qsort/lean-toolchain
Labels: toolchain-available, changelog-library

#6271 chore: upstream Vector lemmas
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available

#6272 feat: Array.swap_perm
  src/Init/Data/Array.lean
  src/Init/Data/Array/Perm.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat.lean
  src/Init/Data/List/Nat/Perm.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/Perm.lean
  src/Init/Data/Vector/Basic.lean
Labels: toolchain-available, changelog-library

#6270 fix: have `Lean.Meta.isConstructorApp'?` be aware of `n + k` Nat offsets
  src/Lean/Meta/CtorRecognizer.lean
  tests/lean/run/5064.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6273 feat: make "foo has been deprecated" warning be hoverable
  src/Lean/Linter/Deprecated.lean
Labels: toolchain-available, changelog-language

#6262 chore: remove accidentally added file
  debug.log
Labels: toolchain-available, changelog-no

#6188 feat: more UInt bitwise theorems
  src/Init/Data/UInt/Bitwise.lean
  src/Std/Data/DHashMap/Internal/Index.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6276 feat: omega doesn't get stuck on bare Int.negSucc
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  tests/lean/run/omega.lean
Labels: toolchain-available, changelog-no

#6284 chore: missing Array/Vector injectivity lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-no

#6286 perf: bv_decide uses rfl in reflection if possible
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reflect.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVExpr.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVLogical.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVPred.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedLemmas.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reify.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/SatAtBVLogical.lean
  tests/lean/run/bv_preprocess_stress.lean
  tests/lean/run/bv_reflection_stress.lean
Labels: toolchain-available, changelog-language

#4460 feat: async linting
  src/Init/System/IO.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/GuardMsgs.lean
  src/Lean/Message.lean
  src/runtime/io.cpp
Labels: builds-mathlib, toolchain-available, changelog-language

#6176 feat: lake: build without `leanc`
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Executable.lean
  src/lake/Lake/Build/Trace.lean
  src/lake/Lake/Config/InstallPath.lean
  src/lake/Lake/Config/LeanExe.lean
  src/lake/examples/bootstrap/lakefile.lean
  src/lake/tests/buildArgs/test.sh
Labels: builds-mathlib, toolchain-available, release-ci, changelog-lake

#6288 perf: speed up bv_decide reflection using Lean.RArray
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reflect.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/SatAtBVLogical.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Basic.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Basic.lean
Labels: toolchain-available, changelog-language

#6291 fix: lake: properly prepend job log in `ensureJob`
  src/lake/Lake/Build/Fetch.lean
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Util/Log.lean
Labels: toolchain-available, changelog-lake

#6287 chore: robustify for byAsSorry
  src/Init/Data/Array/Attach.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/Nat/Dvd.lean
  src/Init/GetElem.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#6294 chore: upstream List.length_flatMap
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available, changelog-library

#6293 chore: specialize fold loops
  src/Init/Data/Fin/Fold.lean
Labels: toolchain-available

#6295 feat: simprocs for other Fin operations
  src/Lean/Meta/LitValues.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Fin.lean
  tests/lean/run/simprocFin.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6244 feat: reverse `HashMap.toList`, so it agrees with `HashMap.toArray`
  src/Std/Data/DHashMap/Internal/AssocList/Basic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Lemmas.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Data/DHashMap/Raw.lean
  tests/lean/run/hashmap.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6297 chore: `CMAKE_CXX_SYSROOT_FLAG` is also needed for linking
  src/CMakeLists.txt
  src/bin/leanc.in
  src/util/ffi.cpp
Labels: toolchain-available, release-ci

#6300 feat: add `debug.proofAsSorry`
  src/Lean/Elab/MutualDef.lean
  src/stdlib_flags.h
  tests/lean/run/proofAsSorry.lean
Labels: toolchain-available, changelog-language

#6238 feat: BitVec.toFin/ToInt BitVec.ushiftRight
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Bitwise/Basic.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6305 chore: remove unused imports
  src/Std/Time/Zoned/DateTime.lean
Labels: toolchain-available, changelog-no

#6308 test: do not filter output for non-diff tests
  doc/examples/test_single.sh
  tests/common.sh
  tests/lean/run/test_single.sh
  tests/lean/server/test_single.sh
  tests/lean/trust0/test_single.sh
Labels: toolchain-available

#6311 fix: missing `HEq` support at `ToLCNF`
  src/Lean/Compiler/LCNF/ToLCNF.lean
Labels: toolchain-available, changelog-compiler

#6316 feat: lemmas about for loops over `Option`
  src/Init/Data/Option.lean
  src/Init/Data/Option/Attach.lean
  src/Init/Data/Option/Instances.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Data/Option/List.lean
  src/Init/Data/Option/Monadic.lean
Labels: toolchain-available, changelog-library

#6285 feat: upstream `ToLevel` from mathlib
  src/Lean/ToExpr.lean
  src/Lean/ToLevel.lean
  tests/lean/run/2291.lean
Labels: awaiting-review, toolchain-available, changelog-other

#6315 chore: protect Fin.cast and BitVec.cast
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/Fin/Lemmas.lean
Labels: awaiting-mathlib, breaks-mathlib, toolchain-available, changelog-library

#6318 chore: generalize universe in Array.find?
  src/Init/Data/Array.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
Labels: toolchain-available, changelog-library

#6324 feat: getElem lemmas for Vector operations
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#6196 doc: missing (type := true) in reader monad example
  doc/monads/readers.lean
Labels: builds-mathlib, toolchain-available, P-medium

#6322 chore: remove deprecated aliases for `Int.tdiv` and `Int.tmod`
  src/Init/Data/Int/DivMod.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean
  tests/bench/liasolver.lean
  tests/lean/307.lean
  tests/lean/307.lean.expected.out
  tests/lean/matchOfNatIssue.lean
Labels: toolchain-available, changelog-no

#6337 chore: cleanup of Array lemmas
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/TakeDrop.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/MapIdx.lean
  src/Init/GetElem.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Clause.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/Lemmas.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RatAddSound.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
Labels: toolchain-available, changelog-no

#6204 feat: `_` separators in numeric literals
  doc/lexical_structure.md
  src/Init/Meta.lean
  src/Lean/Parser/Basic.lean
  tests/lean/run/6199.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6339 chore: release notes for 4.14.0
  RELEASES.md
Labels: toolchain-available, changelog-no

#6342 chore: alignment of Array and List lemmas
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Find.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/List/ToArrayImpl.lean
  src/Init/GetElem.lean
Labels: breaks-mathlib, toolchain-available, changelog-library

#6343 chore: cleanup of Array lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/PropLemmas.lean
Labels: toolchain-available, changelog-no

#6344 doc: clarify difference between Expr.hasLooseBVars and Expr.hasLooseBVar
  src/Lean/Expr.lean
Labels: awaiting-review, toolchain-available

#6348 feat: add support for `Float32` to the Lean runtime
  src/Init/Data.lean
  src/Init/Data/Float32.lean
  src/Lean/Compiler/IR/Basic.lean
  src/Lean/Compiler/IR/EmitC.lean
  src/Lean/Compiler/IR/EmitLLVM.lean
  src/Lean/Compiler/IR/Format.lean
  src/include/lean/lean.h
  src/library/compiler/ir.cpp
  src/library/compiler/ir.h
  src/library/compiler/llnf.cpp
  src/library/compiler/llnf.h
  src/library/compiler/util.cpp
  src/library/constants.cpp
  src/library/constants.h
  src/library/constants.txt
  src/runtime/object.cpp
Labels: toolchain-available, changelog-compiler

#6338 feat: BitVec.[toFin|getMsbD]_setWidth and [getMsbD|msb]_signExtend
  src/Init/Data/BitVec/Lemmas.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6349 chore: improve BitVec ext lemmas
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Eq.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_uninterpreted.lean
Labels: toolchain-available

#6350 fix: `Float32` runtime support
  src/Lean/Compiler/IR/Basic.lean
  src/library/compiler/ir.cpp
  src/library/compiler/ir.h
  src/library/compiler/ir_interpreter.cpp
  src/library/compiler/llnf.cpp
  src/library/compiler/llnf.h
  src/runtime/object.h
Labels: toolchain-available, changelog-compiler

#6327 chore: adjust CODEOWNERS
  CODEOWNERS
Labels: builds-mathlib, toolchain-available, will-merge-soon

#6353 chore: alignment of Array.any/all lemmas with List
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/BEq.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Lemmas.lean
  tests/lean/run/wfOverapplicationIssue.lean
Labels: toolchain-available, changelog-library

#6356 refactor: make `mkInhabitantFor` error message configurable
  src/Lean/Elab/PreDefinition/Main.lean
  src/Lean/Elab/PreDefinition/MkInhabitant.lean
Labels: toolchain-available, will-merge-soon

#6357 refactor: WF.EqnInfo.hasInduct
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Meta/Tactic/FunInd.lean
Labels: toolchain-available, will-merge-soon

#6358 refactor: elabWFRel to take names, not `PreDefinition`
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/PreDefinition/WF/Rel.lean
Labels: toolchain-available, will-merge-soon

#6359 refactor: ArgsPacker.unpack to return `Option`
  src/Lean/Elab/PreDefinition/WF/Fix.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Meta/ArgsPacker.lean
  src/Lean/Meta/Tactic/FunInd.lean
Labels: toolchain-available, will-merge-soon

#6365 feat: alignment of Array.set lemmas with List lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/ToArray.lean
Labels: toolchain-available, changelog-library

#6366 feat: add `Float32` support
  src/Init/Data/Float32.lean
  src/Init/Data/OfScientific.lean
  src/library/compiler/ir_interpreter.cpp
  src/runtime/object.h
  tests/lean/run/float32.lean
Labels: toolchain-available, changelog-language

#6367 feat: lemmas about indexing and membership for Vector
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#3696 feat: do not propagate pretty printer errors through messages
  src/Lean/Elab/GuardMsgs.lean
  src/Lean/Message.lean
  src/Lean/PrettyPrinter.lean
  src/Lean/Util/PPExt.lean
  src/Lean/Util/Trace.lean
  src/lake/Lake/Util/Message.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6341 chore: DecidableRel allows a heterogeneous relation
  src/Init/Data/Nat/Dvd.lean
  src/Init/Data/Option/Basic.lean
  src/Init/Prelude.lean
  src/lake/Lake/Util/Log.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6307 chore: preserve reported messages in `MessageLog`
  src/Lean/CoreM.lean
  src/Lean/Message.lean
  src/Lean/Util/SafeExponentiation.lean
Labels: builds-mathlib, toolchain-available

#6334 feat: `Nat.shiftRight_bitwise_distrib`
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#5757 feat: labeled and unique sorries
  src/Init/NotationExtra.lean
  src/Init/Prelude.lean
  src/Init/Tactics.lean
  src/Lean/Data/DeclarationRange.lean
  src/Lean/DeclarationRange.lean
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Elab/Extra.lean
  src/Lean/Elab/InfoTree/Main.lean
  src/Lean/Elab/InfoTree/Types.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/PreDefinition/Main.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/LibrarySearch.lean
  src/Lean/Elab/Term.lean
  src/Lean/Meta.lean
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/Check.lean
  src/Lean/Meta/Sorry.lean
  src/Lean/Meta/Tactic/Util.lean
  src/Lean/Parser/Term.lean
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/FileWorker/WidgetRequests.lean
  src/Lean/Server/InfoUtils.lean
  src/Lean/Util/Sorry.lean
  src/Lean/Widget/InteractiveCode.lean
  src/lake/Lake/CLI/Translate.lean
  tests/lean/run/sorry.lean
  tests/lean/shadow.lean.expected.out
Labels: toolchain-available, changelog-language, changelog-pp

#6369 feat: lemmas about Vector.any/all/set
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#6375 fix: unused `let_fun` elimination in `simp`
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/letFunUnusedVarBug.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6364 chore: run Batteries linter on Lean
  src/Init/Control/Lawful/Basic.lean
  src/Init/Data/Array/Attach.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/BasicAux.lean
  src/Init/Data/Array/Bootstrap.lean
  src/Init/Data/Array/DecidableEq.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/Modify.lean
  src/Init/Data/List/Sort/Impl.lean
  src/Init/Data/List/Sort/Lemmas.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Option/Attach.lean
  src/Init/Data/Sum/Lemmas.lean
  src/Init/GetElem.lean
  src/Init/SimpLemmas.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/Lemmas.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  tests/lean/run/array_simp.lean
Labels: toolchain-available, release-ci, changelog-library

#6376 feat: theorems about `==` on `Vector`
  src/Init/Data/Array/Find.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: breaks-mathlib, toolchain-available, changelog-library

#6377 doc: fix typo reference in doc of lazy discrimination tree
  src/Lean/Meta/LazyDiscrTree.lean
Labels: toolchain-available

#6313 chore: remove Lean.Compiler.LCNF.ForEachExpr
  src/Lean/Compiler/LCNF.lean
  src/Lean/Compiler/LCNF/ForEachExpr.lean
  src/Lean/Compiler/LCNF/Probing.lean
Labels: toolchain-available

#6321 chore: stop running compiler twice during tests
  tests/lean/run/CompilerCSE.lean
  tests/lean/run/CompilerFindJoinPoints.lean
  tests/lean/run/CompilerFloatLetIn.lean
  tests/lean/run/CompilerPullInstances.lean
  tests/lean/run/CompilerSimp.lean
Labels: builds-mathlib, toolchain-available

#6123 fix: propagate `Simp.Config` when reducing terms and checking definitional equality in `simp`
  src/Init/Data/Array/Basic.lean
  src/Init/Data/List/Impl.lean
  src/Lean/Data/RArray.lean
  src/Lean/Elab/PatternVar.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Elab/Term.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/InferType.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  src/Lean/Meta/WHNF.lean
  src/Std/Sat/AIG/Basic.lean
  src/Std/Sat/AIG/CNF.lean
  src/Std/Sat/AIG/Relabel.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RatAddResult.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  src/Std/Time/Date/ValidDate.lean
  tests/lean/run/2670.lean
  tests/lean/run/5455.lean
  tests/lean/run/6123_cat_adjunction.lean
  tests/lean/run/6123_mod_cast.lean
  tests/lean/run/betaSimp.lean
  tests/lean/run/heapSort.lean
  tests/lean/run/simpConfigPropagationIssue1.lean
  tests/lean/run/simpConfigPropagationIssue3.lean
  tests/lean/run/splitIfIssue.lean
  tests/lean/run/zetaDeltaSet.lean
  tests/lean/run/zetaDeltaTryThisIssue.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6362 feat: `lean --error=kind`
  src/Lean/Elab/Frontend.lean
  src/Lean/Language/Basic.lean
  src/util/shell.cpp
Labels: builds-mathlib, toolchain-available, changelog-language

#6380 chore: move implementation details of `mergeSort` into namespace
  src/Init/Data/List/Sort/Basic.lean
  src/Init/Data/List/Sort/Lemmas.lean
Labels: toolchain-available, changelog-no

#6381 fix: `withTrackingZetaDelta` must reset cache
  src/Lean/Meta/Basic.lean
  tests/lean/run/trackZetaDeltaCacheIssue.lean
Labels: toolchain-available, changelog-language

#6383 fix: new code generator must generate code for opaque declarations that are not `@[extern]`
  src/Lean/Compiler/LCNF/Main.lean
  src/Lean/Compiler/LCNF/ToDecl.lean
  src/Lean/Declaration.lean
  tests/lean/run/opaqueNewCodeGen.lean
Labels: toolchain-available, changelog-compiler

#6384 test: add test for issue #4585
  tests/lean/run/4585.lean
Labels: toolchain-available, changelog-no

#6385 fix: `simp_all?` local declarations
  src/Lean/Elab/Tactic/SimpTrace.lean
  tests/lean/run/3519.lean
Labels: toolchain-available, changelog-language

#6387 fix: type incorrect term produced by `contradiction`
  src/Lean/Meta/Tactic/Contradiction.lean
  tests/lean/run/4851.lean
Labels: toolchain-available, changelog-language

#6386 fix: `revertAll` must clear auxiliary declarations
  src/Lean/Meta/Tactic/Grind/RevertAll.lean
  tests/lean/run/6263.lean
Labels: toolchain-available, changelog-language

#6379 feat: replace `List.lt` with `List.Lex`
  doc/examples/ICERM2022/meta.lean
  releases_drafts/list_lex.md
  src/Init/Core.lean
  src/Init/Data/Array.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Lex.lean
  src/Init/Data/Char/Lemmas.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/MinMax.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Ord.lean
  src/Init/Data/String/Basic.lean
  src/Init/Data/String/Lemmas.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Prelude.lean
  src/Lean/Compiler/LCNF/Probing.lean
  tests/lean/run/bubble.lean
  tests/lean/run/constructor_as_variable.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6390 feat: redefine Range.forIn'
  src/Init/Data/Range.lean
  src/Lean/Meta/Tactic/LibrarySearch.lean
  tests/lean/getElem.lean
  tests/lean/run/structure_recursive.lean
Labels: breaks-mathlib, toolchain-available, changelog-library

#6333 feat: generalize `panic` to `Sort`
  src/Init/Prelude.lean
  src/Init/Util.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6340 doc: split the docstring of `LocalContext`
  src/Lean/LocalContext.lean
Labels: toolchain-available

#6382 chore: add gitpod configuration
  .gitpod.Dockerfile
  .gitpod.yml
Labels: toolchain-available

#6396 feat: lemmas about Std.Range
  src/Init/Data/Int/Basic.lean
  src/Init/Data/List/Notation.lean
  src/Init/Data/Nat.lean
  src/Init/Data/Nat/Bitwise/Basic.lean
  src/Init/Data/Nat/Div.lean
  src/Init/Data/Nat/Div/Basic.lean
  src/Init/Data/Nat/Div/Lemmas.lean
  src/Init/Data/Nat/Dvd.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Range.lean
  src/Init/Data/Range/Basic.lean
  src/Init/Data/Range/Lemmas.lean
  tests/lean/run/nat_mod_defeq.lean
Labels: toolchain-available, changelog-library

#6398 fix: `check` must check projections
  src/Lean/Meta/Check.lean
  src/Lean/Meta/InferType.lean
  tests/lean/run/5660.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6363 fix: add missing fields in the profiler datastructures
  src/Lean/Util/Profiler.lean
Labels: toolchain-available, changelog-other

#6401 chore: remove old language manual
  doc/SUMMARY.md
  doc/array.md
  doc/autobound.md
  doc/builtintypes.md
  doc/char.md
  doc/decltypes.md
  doc/do.md
  doc/elaborators.md
  doc/enum.md
  doc/flake.nix
  doc/float.md
  doc/functions.md
  doc/implicit.md
  doc/inductive.md
  doc/int.md
  doc/list.md
  doc/macro_overview.md
  doc/monads/.gitignore
  doc/monads/applicatives.lean
  doc/monads/except.lean
  doc/monads/functors.lean
  doc/monads/intro.md
  doc/monads/laws.lean
  doc/monads/monads.lean
  doc/monads/readers.lean
  doc/monads/states.lean
  doc/monads/transformers.lean
  doc/namespaces.md
  doc/nat.md
  doc/notation.md
  doc/option.md
  doc/organization.md
  doc/reference.md
  doc/sections.md
  doc/string.md
  doc/stringinterp.md
  doc/struct.md
  doc/syntax.md
  doc/task.md
  doc/thunk.md
  doc/typeclass.md
  doc/uint.md
  doc/unifhint.md
Labels: toolchain-available

#6405 feat: support erasure of Decidable.decide in new code generator
  src/Lean/Compiler/LCNF/Probing.lean
  src/Lean/Compiler/LCNF/ToMono.lean
  tests/lean/run/Decidable-decide-erasure.lean
Labels: toolchain-available, changelog-compiler

#6406 chore: in `#print` for structures, mention 'field notation'
  src/Lean/Elab/Print.lean
  tests/lean/diamond1.lean.expected.out
  tests/lean/diamond8.lean.expected.out
  tests/lean/printStructure.lean
  tests/lean/run/print_cmd.lean
Labels: toolchain-available, changelog-no

#6408 fix: ghost goals in autoparam tactic block
  src/Lean/Elab/App.lean
  src/Lean/Elab/StructInst.lean
  src/Lean/Syntax.lean
  tests/lean/interactive/ghostGoals.lean
  tests/lean/interactive/ghostGoals.lean.expected.out
Labels: toolchain-available, changelog-server

#6409 chore: update documentation title and link README to reference
  README.md
  doc/book.toml
Labels: toolchain-available

#6412 feat: reserved names for congruence theorems
  src/Lean/Meta/CongrTheorems.lean
  tests/lean/run/congrReserved.lean
Labels: toolchain-available, changelog-language

#6388 refactor: lake: merge `BuildJob` into `Job`
  src/lake/Lake/Build/Basic.lean
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Executable.lean
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Imports.lean
  src/lake/Lake/Build/Index.lean
  src/lake/Lake/Build/Info.lean
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Build/Library.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/Build/Run.lean
  src/lake/Lake/Build/Targets.lean
  src/lake/Lake/CLI/Build.lean
  src/lake/Lake/Config/ExternLibConfig.lean
  src/lake/Lake/Config/FacetConfig.lean
  src/lake/Lake/Config/LeanExeConfig.lean
  src/lake/Lake/Config/LeanLib.lean
  src/lake/Lake/Config/LeanLibConfig.lean
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Config/Opaque.lean
  src/lake/Lake/Config/TargetConfig.lean
  src/lake/Lake/DSL/Targets.lean
  src/lake/Lake/Util/Opaque.lean
  src/lake/Lake/Util/OpaqueType.lean
  src/lake/README.md
  src/lake/examples/targets/lakefile.lean
  src/lake/tests/logLevel/lakefile.lean
Labels: breaks-mathlib, toolchain-available, release-ci, changelog-lake

#6410 chore: fix some docstrings
  src/Init/Core.lean
Labels: toolchain-available

#6413 feat: `grind` preprocessing and `Expr` internalization
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
  src/Lean/Meta/Transform.lean
  tests/lean/run/foldProjs.lean
Labels: toolchain-available, changelog-language

#6415 fix: `sharecommon` bug
  src/runtime/sharecommon.cpp
  tests/lean/run/sharecommon.lean
Labels: toolchain-available, changelog-compiler

#6417 chore: protect Nat.div_eq_iff
  src/Init/Data/Nat/Div/Lemmas.lean
Labels: toolchain-available, changelog-no

#6399 feat: lemmas about lexicographic order on Array and Vector
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Lex.lean
  src/Init/Data/Array/Lex/Basic.lean
  src/Init/Data/Array/Lex/Lemmas.lean
  src/Init/Data/Array/Monadic.lean
  src/Init/Data/List.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Lex.lean
  src/Init/Data/List/Monadic.lean
  src/Init/Data/List/Range.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Option/Monadic.lean
  src/Init/Data/Range/Basic.lean
  src/Init/Data/Range/Lemmas.lean
  src/Init/Data/String/Lemmas.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Data/Vector/Lex.lean
  src/Init/PropLemmas.lean
Labels: toolchain-available, changelog-library

#6414 fix: process delayed assignment metavariables correctly in `Lean.Meta.Closure`
  src/Lean/Meta/Closure.lean
  tests/lean/run/6354.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6419 fix: multiple bugs in `grind`
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6422 fix: lake: `afterBuildCache*` traces
  src/lake/Lake/Build/Package.lean
Labels: toolchain-available, changelog-lake

#6411 feat: lake: local package overrides
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/Lake/Load/Config.lean
  src/lake/Lake/Load/Manifest.lean
  src/lake/Lake/Load/Resolve.lean
  src/lake/Lake/Load/Workspace.lean
  src/lake/Lake/Util/Version.lean
  src/lake/tests/packageOverrides/bar1/bar.lean
  src/lake/tests/packageOverrides/bar1/lakefile.toml
  src/lake/tests/packageOverrides/bar2/bar.lean
  src/lake/tests/packageOverrides/bar2/lakefile.toml
  src/lake/tests/packageOverrides/clean.sh
  src/lake/tests/packageOverrides/foo/foo.lean
  src/lake/tests/packageOverrides/foo/lakefile.toml
  src/lake/tests/packageOverrides/lakefile.lean
  src/lake/tests/packageOverrides/packages.json
  src/lake/tests/packageOverrides/test.sh
Labels: builds-mathlib, toolchain-available, changelog-lake

#6423 feat: lemmas about List/Array/Vector lexicographic order
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Lex/Lemmas.lean
  src/Init/Data/List/Lex.lean
  src/Init/Data/String/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Data/Vector/Lex.lean
Labels: toolchain-available, changelog-library

#6425 chore: protect some lemmas in List/Array/Vector namespace
  src/Init/Data/Array/Lex/Lemmas.lean
  src/Init/Data/List/Lex.lean
  src/Init/Data/Vector/Lex.lean
Labels: toolchain-available, changelog-no

#6428 fix: normalize universe levels in `grind` preprocessor
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
  tests/lean/run/grindNormLevelIssue.lean
Labels: toolchain-available, changelog-language

#6429 feat: add support for extern LCNF decls
  src/Lean/Compiler/ExternAttr.lean
  src/Lean/Compiler/LCNF/Basic.lean
  src/Lean/Compiler/LCNF/Bind.lean
  src/Lean/Compiler/LCNF/CSE.lean
  src/Lean/Compiler/LCNF/Check.lean
  src/Lean/Compiler/LCNF/CompilerM.lean
  src/Lean/Compiler/LCNF/DeclHash.lean
  src/Lean/Compiler/LCNF/ElimDead.lean
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
  src/Lean/Compiler/LCNF/FixedParams.lean
  src/Lean/Compiler/LCNF/FloatLetIn.lean
  src/Lean/Compiler/LCNF/Internalize.lean
  src/Lean/Compiler/LCNF/JoinPoints.lean
  src/Lean/Compiler/LCNF/LambdaLifting.lean
  src/Lean/Compiler/LCNF/Level.lean
  src/Lean/Compiler/LCNF/Main.lean
  src/Lean/Compiler/LCNF/PrettyPrinter.lean
  src/Lean/Compiler/LCNF/Probing.lean
  src/Lean/Compiler/LCNF/PullFunDecls.lean
  src/Lean/Compiler/LCNF/PullLetDecls.lean
  src/Lean/Compiler/LCNF/ReduceArity.lean
  src/Lean/Compiler/LCNF/ReduceJpArity.lean
  src/Lean/Compiler/LCNF/Renaming.lean
  src/Lean/Compiler/LCNF/Simp.lean
  src/Lean/Compiler/LCNF/Simp/InlineCandidate.lean
  src/Lean/Compiler/LCNF/Simp/InlineProj.lean
  src/Lean/Compiler/LCNF/Specialize.lean
  src/Lean/Compiler/LCNF/Testing.lean
  src/Lean/Compiler/LCNF/ToDecl.lean
  src/Lean/Compiler/LCNF/ToExpr.lean
  src/Lean/Compiler/LCNF/ToMono.lean
  tests/lean/run/opaqueNewCodeGen.lean
Labels: toolchain-available, changelog-compiler

#6430 feat: add `Expr.fvarsSubset`
  src/Lean/Util.lean
  src/Lean/Util/CollectFVars.lean
  src/Lean/Util/FVarSubset.lean
  src/Lean/Util/FindExpr.lean
  src/Lean/Util/ForEachExpr.lean
  tests/lean/run/fvarSubset.lean
Labels: toolchain-available, changelog-language

#6397 fix: ensure `simp` and `dsimp` do not unfold too much
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lex.lean
  src/Init/Data/List/Zip.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/WHNF.lean
  tests/lean/run/1024.lean
  tests/lean/run/5755.lean
  tests/lean/run/946.lean
  tests/lean/run/ac_expr.lean
  tests/lean/run/concatElim.lean
Labels: breaks-mathlib, toolchain-available, merge-ci, changelog-language

#6378 feat: explanations for `cases` applied to non-inductive types
  src/Lean/Elab/Tactic/Induction.lean
  tests/lean/run/casesTactic.lean
Labels: toolchain-available, changelog-language

#6433 feat: canonicalizer for the `grind` tactic
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grindCanonInsts.lean
  tests/lean/run/grindCanonTypes.lean
Labels: toolchain-available, changelog-language

#6435 feat: congruence table for `grind` tactic
  src/Init/Grind/Util.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/MarkNestedProofs.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_congr.lean
  tests/lean/run/grind_nested_proofs.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6437 feat: detect congruent terms in `grind`
  src/Lean/Expr.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_congr.lean
  tests/lean/run/grind_nested_proofs.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6440 test: `grind`
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_canon_insts.lean
  tests/lean/run/grind_canon_types.lean
  tests/lean/run/grind_many_eqs.lean
  tests/lean/run/grind_nested_proofs.lean
  tests/lean/run/grind_norm_levels.lean
Labels: toolchain-available, changelog-no

#6441 feat: truth value propagation for `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_propagate_connectives.lean
Labels: toolchain-available, changelog-language

#6442 fix: `checkParents` in `grind`
  src/Lean/Meta/Tactic/Grind/Inv.lean
  tests/lean/run/grind_propagate_connectives.lean
Labels: toolchain-available, changelog-language

#6443 feat: propagate equality in `grind`
  src/Init/Grind/Lemmas.lean
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_propagate_connectives.lean
Labels: toolchain-available, changelog-language

#6447 refactor: move simplifier support to `GrindM`
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-language

#6448 feat: support for builtin `grind` propagators
  src/Init/Grind.lean
  src/Init/Grind/Propagator.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-language

#6449 feat: support for builtin `grind` propagators (part 2)
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-language

#6451 chore: check whether pointer equality implies structural equality in `grind`
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
Labels: toolchain-available, changelog-no

#6452 feat: equality proof generation for `grind`
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_congr.lean
  tests/lean/run/grind_nested_proofs.lean
  tests/lean/run/grind_propagate_connectives.lean
Labels: toolchain-available, changelog-language

#6453 perf: improve bv_decide performance with large literals
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reflect.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVLogical.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedLemmas.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reify.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Basic.lean
  src/Std/Tactic/BVDecide/Bitblast/BoolExpr/Basic.lean
  src/Std/Tactic/BVDecide/Bitblast/BoolExpr/Circuit.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  src/Std/Tactic/BVDecide/Normalize/Bool.lean
  src/Std/Tactic/BVDecide/Normalize/Prop.lean
  src/Std/Tactic/BVDecide/Reflect.lean
  tests/lean/run/6043.lean
  tests/lean/run/bv_decide_rewriter.lean
  tests/lean/run/bv_substructure.lean
Labels: builds-mathlib, toolchain-available

#6455 fix: bug in `mkEqProof` within `grind`
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_nested_proofs.lean
Labels: toolchain-available, changelog-language

#6456 fix: fix: bug in `mkEqProof` within `grind`
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6457 feat: congruence proofs for `grind`
  src/Init/Grind/Util.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  tests/lean/run/grind_congr1.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6458 feat: use compact congruence proofs in `grind` if applicable
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_congr1.lean
Labels: toolchain-available, changelog-language

#6459 feat: add `grind` tactic
  src/Init/Grind.lean
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  tests/lean/run/grind_congr1.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6460 chore: implement reduceCond for bv_decide
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
Labels: toolchain-available, changelog-no

#6461 fix: missing `Not` propagation rule in `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6463 feat: constructors in `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Expr.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Ctor.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_congr1.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6464 feat: literal values in `grind`
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Ctor.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6465 feat: projections in `grind`
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Proj.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  src/Lean/Meta/Tactic/Grind/PropagatorAttr.lean
  src/Lean/Meta/Tactic/Grind/Run.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6466 fix: check function types when detecting congruences in `grind`
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6468 fix: `Int.reduceNeg` simproc
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean
  tests/lean/run/6467.lean
Labels: toolchain-available, changelog-language

#6469 feat: missing data for `grind` e-match
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-language

#6470 feat: add `grind_pattern` command
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Parser.lean
Labels: toolchain-available, changelog-language

#6450 doc: explain `app_delab`
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
Labels: toolchain-available, changelog-doc

#6472 feat: theorem patterns for heuristic instantiation in `grind`
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/TheoremPatterns.lean
  tests/lean/run/grind_pattern1.lean
Labels: toolchain-available, changelog-language

#6474 feat: check pattern coverage in the `grind_pattern` command
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/TheoremPatterns.lean
  tests/lean/run/grind_pattern1.lean
Labels: toolchain-available, changelog-language

#6475 feat: ematch theorem activation for `grind`
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Run.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_pattern2.lean
Labels: toolchain-available, changelog-language

#6478 fix: internalize nested ground patterns when activating ematch theorems
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  tests/lean/run/grind_pattern2.lean
Labels: toolchain-available, changelog-language

#6480 chore: reduce churn in tests/lean/run/meta5.lean
  tests/lean/run/meta5.lean
Labels: toolchain-available

#6481 feat: E-matching procedure for the `grind` tactic
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Proj.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_congr1.lean
  tests/lean/run/grind_ematch1.lean
  tests/lean/run/grind_pattern1.lean
  tests/lean/run/grind_pattern2.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6473 feat: upstream `ToExpr` deriving handler from Mathlib
  src/Lean/Elab/Deriving.lean
  src/Lean/Elab/Deriving/ToExpr.lean
  src/Lean/ToExpr.lean
  tests/lean/run/derivingToExpr.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6484 chore: add missing diff-exposing in type/value mismatch errors
  src/Lean/Elab/Calc.lean
  src/Lean/Elab/CheckTactic.lean
  src/Lean/Meta/Check.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6485 feat: instantiate ematch theorems in `grind`
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  tests/lean/run/grind_ematch1.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6488 fix: E-matching module for `grind`
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-language

#6490 feat: configuration options for the `grind` tactic
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Run.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_ematch1.lean
Labels: toolchain-available, changelog-language

#6487 fix: make sure parent `structure` projections have 'go to definition' information
  src/Lean/Elab/Structure.lean
Labels: builds-mathlib, toolchain-available, changelog-language
