Repository leanprover/lean4, pull requests merged in 2024-03, with the labels that each got.

#3480 feat: generalize msb_eq_decide to also handle the zero width case
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-review, toolchain-available

#3540 chore: add error recovery to RELEASES.md
  RELEASES.md
Labels: toolchain-available

#3550 chore: correct statement of Int.pow_zero, and protected theorems
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Lemmas.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#3551 chore: protect Int.add_right_inj et al
  src/Init/Data/Int/Lemmas.lean
Labels: toolchain-available

#3549 chore: add library_search and #check_tactic to 4.7 RELEASES.md
  RELEASES.md
Labels: toolchain-available

#3561 doc: update RELEASES.md for #3552
  RELEASES.md
Labels: toolchain-available

#3564 refactor: simplify some nomatch with nofun
  src/Init/Data/List/Basic.lean
  src/Init/Prelude.lean
  src/Lean/Data/PersistentHashMap.lean
  src/Lean/Syntax.lean
Labels: toolchain-available, will-merge-soon

#3572 fix: missing `atomic` at `match_expr` parser
  src/Lean/Parser/Do.lean
  tests/lean/run/match_expr_meta_modifier.lean
Labels: toolchain-available

#3573 fix: `simp?` suggests generated equations lemma names
  src/Lean/Meta/Eqns.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  tests/lean/run/3547.lean
Labels: toolchain-available

#3575 fix: `generalize` excessive resource usage
  src/Lean/Meta/Tactic/Generalize.lean
  tests/lean/run/3524.lean
Labels: toolchain-available

#3580 perf: `match_expr` join points
  src/Lean/Elab/MatchExpr.lean
  tests/lean/run/match_expr_perf.lean
Labels: toolchain-available

#3566 fix: free threadpool threads before process exit
  src/runtime/object.cpp
Labels: builds-mathlib, toolchain-available, full-ci

#3581 fix: `rename_i` in macro
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Util.lean
  tests/lean/run/renameI.lean
Labels: toolchain-available

#3565 chore: add unicode directory name to gitignore
  src/lake/tests/init/.gitignore
Labels: toolchain-available, will-merge-soon

#3560 doc: small improvements to docstrings for `let` and `have` tactics
  src/Init/Tactics.lean
Labels: toolchain-available

#3577 chore: use match_expr in omega
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  stage0/src/runtime/object.cpp
  stage0/stdlib/Lean/Elab/MatchExpr.c
  stage0/stdlib/Lean/Elab/PreDefinition/Eqns.c
  stage0/stdlib/Lean/Elab/Tactic/BuiltinTactic.c
  stage0/stdlib/Lean/Elab/Tactic/Generalize.c
  stage0/stdlib/Lean/Elab/Tactic/Induction.c
  stage0/stdlib/Lean/Elab/Tactic/Omega/Frontend.c
  stage0/stdlib/Lean/Elab/Tactic/RCases.c
  stage0/stdlib/Lean/Elab/Util.c
  stage0/stdlib/Lean/Meta/Eqns.c
  stage0/stdlib/Lean/Meta/Tactic/Generalize.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Char.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Core.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Nat.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/Main.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/Rewrite.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/SimpTheorems.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/Simproc.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/Types.c
  stage0/stdlib/Lean/Parser/Do.c
Labels: toolchain-available

#3582 feat: Nat.mul_mod
  src/Init/Data/Nat.lean
  src/Init/Data/Nat/Mod.lean
Labels: toolchain-available

#3442 fix: expression tree elaborator for relations now localizes error messages to the LHS or RHS
  src/Lean/Elab/Extra.lean
  tests/lean/binrelTypeMismatch.lean
  tests/lean/binrelTypeMismatch.lean.expected.out
Labels: awaiting-review, toolchain-available

#3583 chore: add release notes for #3507 and #3509
  RELEASES.md
Labels: toolchain-available

#3576 chore: replacing proofs in Init/Data/Nat/Bitwise/Lemmas with omega
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: toolchain-available

#3584 feat: `#print equations <decl-name>` command
  src/Lean/Elab/Print.lean
  src/Lean/Parser/Command.lean
  tests/lean/run/printEqns.lean
Labels: toolchain-available

#3585 chore: updates to RELEASES.md
  RELEASES.md
Labels: toolchain-available

#3587 chore: missing double backticks
  src/Lean/Meta/Match/CaseArraySizes.lean
  src/Lean/ParserCompiler.lean
Labels: toolchain-available

#3558 test: add language server startup benchmark
  tests/bench/server_startup.lean
  tests/bench/server_startup.log
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#3592 chore: cherry-picking v4.6.1 release notes
  RELEASES.md
Labels: toolchain-available

#3595 fix: bug at `elimOptParam`
  src/Lean/Meta/Injective.lean
  tests/lean/run/elimOptParam.lean
Labels: toolchain-available

#3508 chore: bool and prop lemmas for Mathlib compatibility and improved confluence
  doc/examples/bintree.lean
  src/Init/ByCases.lean
  src/Init/Classical.lean
  src/Init/Core.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/PropLemmas.lean
  src/Init/SimpLemmas.lean
  src/Lean/Elab/CheckTactic.lean
  src/Lean/Meta.lean
  src/Lean/Meta/CheckTactic.lean
  tests/lean/1079.lean.expected.out
  tests/lean/bool_simp.lean
  tests/lean/bool_simp.lean.expected.out
  tests/playground/bool_exhaust_test.lean
Labels: toolchain-available

#3596 chore: begin development cycle for v4.8.0
  RELEASES.md
  src/CMakeLists.txt
Labels: toolchain-available

#3593 feat: lemmas about BitVec
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#3487 feat: add lemmas about `BitVec.concat` and bitwise ops
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-author, toolchain-available

#3536 feat: checklist for release process
  doc/SUMMARY.md
  doc/dev/release_checklist.md
Labels: toolchain-available

#3597 feat: more BitVec lemmas
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#3598 chore: cleanup a bitblast proof
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: toolchain-available

#3432 feat: functional induction
  .github/workflows/ci.yml
  RELEASES.md
  src/Lean/CoreM.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Match/MatchEqs.lean
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/Tactic.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Parser/Command.lean
  tests/lean/run/funind_demo.lean
  tests/lean/run/funind_expr.lean
  tests/lean/run/funind_mutual_dep.lean
  tests/lean/run/funind_proof.lean
  tests/lean/run/funind_tests.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#3602 feat: partial words import completion
  src/Lean/Server/ImportCompletion.lean
Labels: builds-mathlib, toolchain-available

#3605 chore: shaking imports in Init.Data.Nat/Int
  src/Init/Control/ExceptCps.lean
  src/Init/Control/Lawful.lean
  src/Init/Control/Lawful/Basic.lean
  src/Init/Control/Lawful/Instances.lean
  src/Init/Control/StateCps.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Bitwise/Basic.lean
  src/Init/Data/Nat/Div.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Ord.lean
  src/Init/Omega/Int.lean
  src/Init/Omega/IntList.lean
  src/Init/System/IO.lean
  src/Lean/Elab/Tactic/Omega/MinNatAbs.lean
Labels: toolchain-available

#3606 fix: bug at `Result.mkEqSymm`
  src/Lean/Meta/Tactic/Simp/Types.lean
Labels: toolchain-available

#3607 fix: `dsimp` should reduce kernel projections
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/3395.lean
Labels: toolchain-available

#3608 fix: getInteractiveDiagnostics off-by-one error
  src/Lean/Server/FileWorker/WidgetRequests.lean
Labels: toolchain-available

#3613 feat: further shaking of Nat/Int/Omega
  src/Init/Control/Lawful/Basic.lean
  src/Init/Data/Array/QSort.lean
  src/Init/Data/Int/DivMod.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Dvd.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Nat/Linear.lean
  src/Init/Data/Nat/Log2.lean
  src/Init/Omega/Int.lean
Labels: toolchain-available

#3610 fix: update LazyDiscrTree to not reuse names when caching
  src/Lean/Meta/LazyDiscrTree.lean
  src/Lean/Meta/Tactic/LibrarySearch.lean
Labels: toolchain-available, full-ci

#3614 refactor: `Offset.lean` and related files
  src/Lean/Elab/Syntax.lean
  src/Lean/Expr.lean
  src/Lean/Meta/Coe.lean
  src/Lean/Meta/NatInstTesters.lean
  src/Lean/Meta/Offset.lean
  src/Lean/Meta/SynthInstance.lean
  src/Lean/Meta/Tactic/LinearArith/Nat/Basic.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/String.lean
  src/Lean/ParserCompiler.lean
  tests/lean/run/2615.lean
Labels: toolchain-available

#3616 feat: better support for reducing `Nat.rec`
  src/Lean/Expr.lean
  src/Lean/Meta/CtorRecognizer.lean
  src/Lean/Meta/Offset.lean
  src/Lean/Meta/WHNF.lean
  tests/lean/445.lean.expected.out
  tests/lean/run/3022.lean
  tests/lean/smartUnfolding.lean.expected.out
  tests/lean/unfold1.lean.expected.out
Labels: toolchain-available

#3615 chore: add example to explanation `cond_decide` is not simp
  src/Init/Data/Bool.lean
Labels: toolchain-available

#3624 fix: fold raw `Nat` literals at `dsimp`
  src/Lean/Expr.lean
  src/Lean/Meta/Reduce.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/2916.lean
  tests/lean/run/maze.lean
  tests/lean/run/meta2.lean
Labels: toolchain-available

#3628 fix: `ofScientific` at `simp`
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/2159.lean
Labels: toolchain-available

#3622 fix: stray dbgTraceVal in trace children elision
  src/Lean/Util/Trace.lean
  src/Lean/Widget/InteractiveDiagnostic.lean
Labels: toolchain-available, will-merge-soon

#3632 feat: thread initialization for reverse FFI
  doc/dev/ffi.md
  src/runtime/thread.cpp
  src/runtime/thread.h
Labels: toolchain-available

#3625 fix: make `delabConstWithSignature` avoid using inaccessible names
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/1377.lean.expected.out
  tests/lean/714.lean.expected.out
  tests/lean/974.lean.expected.out
  tests/lean/autoImplicitChainNameIssue.lean.expected.out
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/levelNGen.lean.expected.out
  tests/lean/match1.lean.expected.out
  tests/lean/namePatEqThm.lean.expected.out
  tests/lean/run/2846.lean
  tests/lean/run/funind_demo.lean
  tests/lean/run/funind_mutual_dep.lean
  tests/lean/run/funind_tests.lean
  tests/lean/sizeof.lean.expected.out
  tests/lean/terminationFailure.lean.expected.out
  tests/lean/varBinderUpdate.lean.expected.out
Labels: toolchain-available

#3627 doc: expand an error message about compacting closures
  src/runtime/compact.cpp
Labels: toolchain-available

#3609 feat: lake: `LEAN_GITHASH` override
  src/lake/Lake/Build/Monad.lean
  src/lake/Lake/Config/Env.lean
  src/lake/Lake/Load/Elab.lean
  src/lake/Lake/Load/Main.lean
  src/lake/tests/env/test.sh
Labels: builds-mathlib, toolchain-available

#3634 chore: upstream Std.Data.Nat
  src/Init/Data/Nat.lean
  src/Init/Data/Nat/Compare.lean
  src/Init/Data/Nat/Div.lean
  src/Init/Data/Nat/Dvd.lean
  src/Init/Data/Nat/Gcd.lean
  src/Init/Data/Nat/Lcm.lean
  src/Init/Data/Nat/Lemmas.lean
Labels: toolchain-available, will-merge-soon

#3638 fix: eta-expanded instances at `SynthInstance.lean`
  src/Lean/Meta/SynthInstance.lean
  tests/lean/3057.lean.expected.out
  tests/lean/815b.lean.expected.out
  tests/lean/jason1.lean
  tests/lean/jason1.lean.expected.out
  tests/lean/run/instEtaIssue.lean
Labels: toolchain-available

#3629 feat: custom eliminators for `induction` and `cases` tactics, and beautiful eliminators for `Nat`
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Div.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Meta/Tactic/ElimInfo.lean
  stage0/stdlib/Init/Data/Nat/Basic.c
  stage0/stdlib/Lean/Elab/Tactic/Induction.c
  stage0/stdlib/Lean/Meta/Tactic/ElimInfo.c
  stage0/stdlib/Lean/Meta/Tactic/Simp/Main.c
  tests/lean/inductionErrors.lean.expected.out
  tests/lean/interactive/anonHyp.lean.expected.out
  tests/lean/interactive/goalIssue.lean.expected.out
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/interactive/infoIssues.lean.expected.out
  tests/lean/interactive/plainGoal.lean.expected.out
  tests/lean/run/1337.lean
  tests/lean/run/aStructPerfIssue.lean
  tests/lean/run/casesAnyTypeIssue.lean
  tests/lean/run/compatibleTypesEtaIssue.lean
  tests/lean/run/defaultEliminator.lean
  tests/lean/run/eliminatorImplicitTargets.lean
  tests/lean/run/internalizeCasesIssue.lean
  tests/lean/run/lcnfCastIssue.lean
  tests/lean/run/lcnfInliningIssue.lean
  tests/lean/simp_trace.lean.expected.out
  tests/lean/unfold1.lean.expected.out
  tests/lean/unsolvedIndCases.lean.expected.out
Labels: toolchain-available

#3633 fix: make `elabTermEnsuringType` respect `errToSorry` when there is a type mismatch
  src/Lean/Elab/Term.lean
  tests/lean/issue2260.lean.expected.out
  tests/lean/mulcommErrorMessage.lean.expected.out
  tests/lean/run/haveTactic.lean
  tests/lean/struct1.lean
Labels: builds-mathlib, toolchain-available

#3642 chore: disable some tests on Windows
  src/shell/CMakeLists.txt
Labels: toolchain-available

#3630 feat: GuessLex: avoid writing `sizeOf` in termination argument when not needed
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  tests/lean/guessLex.lean
  tests/lean/guessLex.lean.expected.out
  tests/lean/guessLexTricky.lean.expected.out
  tests/lean/guessLexTricky2.lean.expected.out
  tests/lean/interactive/terminationBySuggestion.lean
  tests/lean/interactive/terminationBySuggestion.lean.expected.out
  tests/lean/issue2981.lean.expected.out
Labels: builds-mathlib, toolchain-available, full-ci

#3612 chore: response file to avoid arg limits in lean static lib build
  src/lean.mk.in
  stage0/src/lean.mk.in
Labels: builds-mathlib, toolchain-available, full-ci

#3652 refactor: termination_by parser to use binderIdent
  src/Lean/Parser/Term.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available, full-ci

#3635 chore: upstream Std.Data.Int
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int.lean
  src/Init/Data/Int/DivMod.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Int/Gcd.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/Int/Pow.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Div.lean
  src/Init/Data/Nat/Dvd.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Random.lean
  src/Init/Omega/Int.lean
  src/Init/Omega/IntList.lean
  src/Lean/Elab/Tactic/Omega/MinNatAbs.lean
  src/Lean/Elab/Tactic/Omega/OmegaM.lean
Labels: toolchain-available, will-merge-soon

#3647 feat: allow `noncomputable unsafe` definitions
  src/Lean/Elab/MutualDef.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3654 fix: make `dsimp?` use and report simprocs
  src/Lean/Elab/Tactic/SimpTrace.lean
Labels: awaiting-review, breaks-mathlib, toolchain-available, full-ci

#3617 feat: guard_msgs to escapes trailing newlines
  src/Lean/Elab/GuardMsgs.lean
  tests/lean/run/guard_msgs.lean
Labels: awaiting-review, toolchain-available

#3639 fix: add `Canonicalizer.lean` and use it to canonicalize terms in `omega`
  src/Lean/Elab/Tactic/Omega/OmegaM.lean
  src/Lean/Meta.lean
  src/Lean/Meta/Canonicalizer.lean
  tests/lean/run/omegaCanon.lean
Labels: toolchain-available

#3579 chore: add @[simp] to Nat.succ_eq_add_one, and cleanup downstream
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Bitwise/Basic.lean
  src/Init/Data/Nat/Div.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Prelude.lean
  tests/lean/guessLexFailures.lean.expected.out
  tests/lean/matchMultAlt.lean
  tests/lean/run/ac_rfl.lean
  tests/lean/run/eqnsAtSimp.lean
  tests/lean/run/eqnsAtSimp2.lean
  tests/lean/run/simp3.lean
  tests/lean/run/simpRwBug.lean
  tests/lean/run/where1.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#3661 chore: rename automatically generated equational theorems
  RELEASES.md
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  tests/lean/1026.lean.expected.out
  tests/lean/1074a.lean.expected.out
  tests/lean/974.lean
  tests/lean/974.lean.expected.out
  tests/lean/986.lean
  tests/lean/986.lean.expected.out
  tests/lean/eqValue.lean
  tests/lean/eqValue.lean.expected.out
  tests/lean/heapSort.lean.expected.out
  tests/lean/namePatEqThm.lean
  tests/lean/namePatEqThm.lean.expected.out
  tests/lean/run/1026.lean
  tests/lean/run/1074a.lean
  tests/lean/run/1080.lean
  tests/lean/run/974.lean
  tests/lean/run/986.lean
  tests/lean/run/byteSliceIssue.lean
  tests/lean/run/eqValue.lean
  tests/lean/run/eqnsAtSimp3.lean
  tests/lean/run/heapSort.lean
  tests/lean/run/instEtaIssue.lean
  tests/lean/run/match_lit_fin_cover.lean
  tests/lean/run/match_lit_issues.lean
  tests/lean/run/namePatEqThm.lean
  tests/lean/run/nestedIssueMatch.lean
  tests/lean/run/nestedWF.lean
  tests/lean/run/overAndPartialAppsAtWF.lean
  tests/lean/run/printEqns.lean
  tests/lean/run/robinson.lean
  tests/lean/run/rossel1.lean
  tests/lean/run/simpAtDefIssue.lean
  tests/lean/run/simp_eqn_bug.lean
  tests/lean/run/splitIssue.lean
  tests/lean/run/splitList.lean
  tests/lean/run/streamEqIssue.lean
  tests/lean/run/structEqns.lean
  tests/lean/run/structuralEqns.lean
  tests/lean/run/structuralEqns2.lean
  tests/lean/run/structuralEqns3.lean
  tests/lean/run/wfEqns1.lean
  tests/lean/run/wfEqns2.lean
  tests/lean/run/wfEqns3.lean
  tests/lean/run/wfEqns4.lean
  tests/lean/structuralEqns.lean.expected.out
Labels: toolchain-available, full-ci

#3659 feat: conv => calc
  src/Init/Conv.lean
  src/Init/NotationExtra.lean
  tests/lean/run/convcalc.lean
Labels: toolchain-available, will-merge-soon

#3662 fix: auxiliary definition nested in theorem should be `def` if its type is not a proposition
  src/Lean/Elab/MutualDef.lean
  tests/lean/run/letrecInThm.lean
Labels: toolchain-available

#3664 doc: fix typo in USize.size docstring
  src/Init/Prelude.lean
Labels: toolchain-available

#3621 refactor: ArgsPacker
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Fix.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/PreDefinition/WF/PackDomain.lean
  src/Lean/Elab/PreDefinition/WF/PackMutual.lean
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/ArgsPacker.lean
  src/Lean/Meta/ArgsPacker/Basic.lean
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/guessLex.lean
  tests/lean/guessLex.lean.expected.out
  tests/lean/guessLexFailures.lean.expected.out
  tests/lean/mutwftypemismatch.lean
  tests/lean/mutwftypemismatch.lean.expected.out
  tests/lean/run/funind_demo.lean
  tests/lean/run/funind_mutual_dep.lean
  tests/lean/run/funind_proof.lean
  tests/lean/run/funind_tests.lean
  tests/lean/run/mutwf3.lean
  tests/lean/run/mutwf4.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon

#3682 chore: build `Lean` `.o`s in parallel to rest of core
  src/lean.mk.in
  src/stdlib.make.in
Labels: toolchain-available

#3271 feat: server -> client requests
  src/Lean/Data/Lsp/Window.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/Watchdog.lean
Labels: toolchain-available

#3656 fix: jump to correct definition when names overlap
  src/Lean/Data/Lsp/Internal.lean
  src/Lean/Linter/UnusedVariables.lean
  src/Lean/Server/References.lean
  src/Lean/Server/Utils.lean
  src/Lean/Server/Watchdog.lean
  tests/lean/run/944.lean
Labels: toolchain-available

#3619 fix: periodically refresh semantic tokens
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
Labels: toolchain-available

#3658 refactor: termination arguments as Expr, not Syntax
  src/Lean/Elab/PreDefinition/WF/Fix.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/PreDefinition/WF/Rel.lean
  src/Lean/Elab/PreDefinition/WF/TerminationArgument.lean
  src/Lean/Elab/PreDefinition/WF/TerminationHint.lean
  src/Lean/Meta/Tactic/Repeat.lean
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  tests/lean/decreasing_by.lean.expected.out
  tests/lean/guessLex.lean.expected.out
  tests/lean/guessLexTricky2.lean.expected.out
  tests/lean/issue2260.lean.expected.out
  tests/lean/issue2981.lean.expected.out
  tests/lean/mutwftypemismatch.lean.expected.out
Labels: toolchain-available, will-merge-soon, full-ci

#3675 feat: reserved names
  src/Init/Core.lean
  src/Init/Prelude.lean
  src/Init/PropLemmas.lean
  src/Lean.lean
  src/Lean/Compiler/ImplementedByAttr.lean
  src/Lean/Compiler/InitAttr.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/BuiltinTerm.lean
  src/Lean/Elab/DeclModifiers.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/Deriving/Basic.lean
  src/Lean/Elab/GenInjective.lean
  src/Lean/Elab/InfoTree/Main.lean
  src/Lean/Elab/InheritDoc.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/Main.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/Print.lean
  src/Lean/Elab/Quotation/Precheck.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Elab/Tactic/Conv/Delta.lean
  src/Lean/Elab/Tactic/Conv/Unfold.lean
  src/Lean/Elab/Tactic/Delta.lean
  src/Lean/Elab/Tactic/Ext.lean
  src/Lean/Elab/Tactic/NormCast.lean
  src/Lean/Elab/Tactic/Rewrite.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Elab/Tactic/Simproc.lean
  src/Lean/Elab/Tactic/Unfold.lean
  src/Lean/Elab/Term.lean
  src/Lean/Environment.lean
  src/Lean/Linter/Deprecated.lean
  src/Lean/Linter/MissingDocs.lean
  src/Lean/Meta/Eqns.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/ParserCompiler/Attribute.lean
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  src/Lean/ReservedNameAction.lean
  src/Lean/ResolveName.lean
  src/Lean/Server/CodeActions/Attr.lean
  tests/lean/run/matchEqs.lean
  tests/lean/run/matchEqsBug.lean
  tests/lean/run/printEqns.lean
  tests/lean/run/reserved.lean
Labels: toolchain-available

#3689 chore: revert periodically refresh semantic tokens (#3619)
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
Labels: toolchain-available

#3601 fix: do not dllexport symbols in core static libraries
  .github/workflows/ci.yml
  RELEASES.md
  nix/buildLeanPackage.nix
  src/CMakeLists.txt
  src/Leanc.lean
  src/include/lean/lean.h
  src/include/lean/lean_gmp.h
  src/lake/Lake/Build/Executable.lean
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Info.lean
  src/lake/Lake/Build/Library.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Config/InstallPath.lean
  src/lake/Lake/Config/LeanExe.lean
  src/lake/Lake/Config/LeanExeConfig.lean
  src/lake/Lake/Config/LeanLib.lean
  src/lake/Lake/Config/LeanLibConfig.lean
  src/lake/Lake/Config/Module.lean
  src/lake/README.md
  src/lake/examples/targets/test.sh
  src/lake/tests/noBuild/test.sh
  src/lean.mk.in
  src/runtime/CMakeLists.txt
  src/shell/CMakeLists.txt
  src/stdlib.make.in
  tests/compiler/link_lake.lean
  tests/plugin/test_single.sh
Labels: toolchain-available, full-ci

#3691 fix: periodically refresh semantic tokens
  src/Lean/Data/Lsp/Ipc.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  tests/lean/interactive/run.lean
Labels: toolchain-available

#3690 chore: CI: mark "Build matrix complete" as cancelled if builds cancelled
  .github/workflows/ci.yml
Labels: toolchain-available

#3685 chore: migrate find functionality into LazyDiscrTree
  src/Lean/Meta/LazyDiscrTree.lean
  src/Lean/Meta/Tactic/LibrarySearch.lean
Labels: toolchain-available

#3665 refactor: pass Measures around as Expr in GuessLex
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  tests/lean/guessLex.lean
  tests/lean/guessLex.lean.expected.out
  tests/lean/guessLexFailures.lean.expected.out
Labels: breaks-mathlib, toolchain-available, will-merge-soon

#3666 feat: infer termination arguments like `xs.size - i`
  RELEASES.md
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Expr.lean
  tests/lean/guessLexDiff.lean
  tests/lean/guessLexDiff.lean.expected.out
  tests/lean/wf1.lean.expected.out
Labels: breaks-mathlib, toolchain-available, full-ci

#3695 fix: substVars in functional inductions removed valuable information
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Meta/Tactic/Subst.lean
  tests/lean/run/funind_tests.lean
Labels: toolchain-available, will-merge-soon

#3700 chore: fix combined CI for mathlib
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3702 chore: in combined CI, check for required Std tag, then Mathlib
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3676 refactor: clean up public API around `Array.eraseIdx`
  src/Init/Data/Array/Basic.lean
  src/Lean/Data/PersistentHashMap.lean
Labels: awaiting-review, toolchain-available

#3672 chore: fix namespaces in recently upstreamed tactics
  src/Lean/Elab/Tactic/ShowTerm.lean
  src/Lean/Elab/Tactic/Simpa.lean
Labels: toolchain-available

#3670 feat: upstream apply helper tactics from Mathlib
  src/Init/PropLemmas.lean
  src/Lean/Meta/Tactic/Apply.lean
Labels: toolchain-available

#3671 feat: upstream Std's rfl tactic
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/Rfl.lean
  src/Lean/Meta/Tactic.lean
  src/Lean/Meta/Tactic/Rfl.lean
Labels: toolchain-available, full-ci

#3704 doc: lake: fix typo
  src/lake/README.md
Labels: toolchain-available

#3707 doc: fix docstring of `List.span`
  src/Init/Data/List/Basic.lean
Labels: toolchain-available

#3708 fix: make attribute based rfl tactic builtin
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Rfl.lean
  tests/lean/run/refl.lean
Labels: toolchain-available

#3712 fix: Build failure of `nix build .` on macOS
  nix/bootstrap.nix
Labels: toolchain-available

#3693 fix: deadlock in `IO.Promise.resolve`
  src/runtime/object.cpp
Labels: toolchain-available, will-merge-soon

#3722 fix: use correct module name in references
  src/Lean/Server/References.lean
Labels: toolchain-available

#3721 feat: BitVec.ofBoolListLE and theorems
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  tests/lean/interactive/completionPrv.lean.expected.out
Labels: awaiting-review, toolchain-available

#3726 feat: `MonadAlwaysExcept` for `MonadCacheT`
  src/Lean/Util/Trace.lean
Labels: toolchain-available

#3725 fix: ignore unused alternatives in `Ord` derive handler
  src/Lean/Elab/Deriving/Ord.lean
  tests/lean/run/3706.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#3186 perf: rewrite UnusedVariables lint
  src/Init/ByCases.lean
  src/Init/Control/ExceptCps.lean
  src/Init/Data/Ord.lean
  src/Lean/Compiler/LCNF/JoinPoints.lean
  src/Lean/Elab/Term.lean
  src/Lean/Linter/UnusedVariables.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Meta/WHNF.lean
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/linterUnusedVariables.lean
  tests/lean/linterUnusedVariables.lean.expected.out
Labels: awaiting-review, breaks-mathlib, toolchain-available, will-merge-soon

#3717 chore: replace shell.nix with a devShell in flake.nix
  .github/workflows/ci.yml
  default.nix
  doc/make/index.md
  flake.lock
  flake.nix
  shell.nix
Labels: builds-mathlib, toolchain-available, full-ci

#3730 fix: use sticky diags in `getInteractiveDiagnostics`
  src/Lean/Server/FileWorker.lean
Labels: toolchain-available

#3733 fix: restore default of `stderrAsMessages`
  src/Lean/Language/Lean.lean
Labels: toolchain-available

#3640 feat: add `pp_using_anonymous_constructor` attribute
  RELEASES.md
  src/Lean/PrettyPrinter/Delaborator/Attributes.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  tests/lean/run/ppUsingAnonymousConstructor.lean
Labels: toolchain-available

#3589 chore: remove the coercion from String to Name
  RELEASES.md
  src/Init/Meta.lean
  src/Init/Prelude.lean
  src/Lean/AuxRecursor.lean
  src/Lean/Compiler/IR/EmitLLVM.lean
  src/Lean/CoreM.lean
  src/Lean/Data/Name.lean
  src/Lean/Data/NameMap.lean
  src/Lean/Elab/App.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Elab/Syntax.lean
  src/Lean/Hygiene.lean
  src/Lean/Meta/ArgsPacker.lean
  src/Lean/Meta/IndPredBelow.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Parser.lean
  src/Lean/Parser/Extra.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/Server/Completion.lean
  src/Lean/Server/Rpc/Deriving.lean
  src/Lean/Widget/Diff.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/Load/Materialize.lean
  src/lake/tests/globs/lakefile.lean
  stage0/src/stdlib_flags.h
  tests/bench/inundation/lakefile.lean
  tests/lean/interactive/run.lean
  tests/lean/run/ofNat_class.lean
Labels: toolchain-available, full-ci

#3663 feat: make `⋯` in Infoview hovers show docstring
  src/Lean/Parser/Term.lean
  src/Lean/Server/InfoUtils.lean
Labels: builds-mathlib, toolchain-available

#3734 doc: fix HDiv and HMod doc-strings
  src/Init/Prelude.lean
Labels: toolchain-available

#3735 feat: apply `pp_using_anonymous_constructor` attribute
  RELEASES.md
  src/Init/Core.lean
  src/Init/Prelude.lean
  tests/lean/1081.lean.expected.out
  tests/lean/243.lean.expected.out
  tests/lean/congrThmIssue.lean.expected.out
  tests/lean/decreasing_by.lean.expected.out
  tests/lean/issue2981.lean.expected.out
  tests/lean/letFun.lean.expected.out
  tests/lean/run/986.lean
  tests/lean/run/PPTopDownAnalyze.lean
  tests/lean/run/funind_tests.lean
  tests/lean/run/litToCtor.lean
  tests/lean/run/ppUsingAnonymousConstructor.lean
Labels: toolchain-available

#3736 chore: omega notices that 0 ≤ (x : Int) % (y : Int)
  src/Init/Omega/Int.lean
  src/Lean/Elab/Tactic/Omega/OmegaM.lean
  tests/lean/run/omega.lean
Labels: toolchain-available

#3737 feat: add `pp.fieldNotation.generalized` for generalized field notation, add `@[pp_nodot]` attribute
  RELEASES.md
  src/Lean/PrettyPrinter/Delaborator/Attributes.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/FieldNotation.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  src/Lean/PrettyPrinter/Delaborator/TopDownAnalyze.lean
  tests/lean/439.lean.expected.out
  tests/lean/delabProjectionApp.lean
  tests/lean/delabProjectionApp.lean.expected.out
  tests/lean/run/PPTopDownAnalyze.lean
  tests/lean/run/delabProjectionApp.lean
Labels: toolchain-available

#3739 chore: more generic import out of date diagnostic
  src/Lean/Server/FileWorker.lean
Labels: toolchain-available

#3742 fix: typos in release notes
  RELEASES.md
Labels: toolchain-available

#3719 feat: upstream rw? tactic
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/Rewrites.lean
  src/Lean/Expr.lean
  src/Lean/Meta/LazyDiscrTree.lean
  src/Lean/Meta/Tactic.lean
  src/Lean/Meta/Tactic/LibrarySearch.lean
  src/Lean/Meta/Tactic/Rewrites.lean
  tests/lean/run/rewrites.lean
Labels: toolchain-available

#3748 doc: fix typo in docstring of `left`
  src/Init/Tactics.lean
Labels: toolchain-available

#3749 feat: flatten parent projections when pretty printing structure instance notation
  RELEASES.md
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  tests/lean/diamond1.lean.expected.out
  tests/lean/diamond2.lean.expected.out
  tests/lean/run/delabStructInst.lean
  tests/lean/structInstExtraEta.lean
  tests/lean/structInstSourcesLeftToRight.lean
  tests/lean/toFieldNameIssue.lean.expected.out
Labels: toolchain-available

#3750 fix: do not pretty print theorems with generalized field notation
  src/Lean/PrettyPrinter/Delaborator/FieldNotation.lean
  tests/lean/1763.lean.expected.out
  tests/lean/arrayGetU.lean.expected.out
  tests/lean/librarySearch.lean
  tests/lean/simpZetaFalse.lean.expected.out
Labels: toolchain-available

#3754 fix: prune universe params in functional induction
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/funind_fewer_levels.lean
Labels: toolchain-available

#3759 chore: ToJson/FromJson Sum
  src/Lean/Data/Json/FromToJson.lean
Labels: toolchain-available

#3760 chore: revert ToJson/FromJson Sum (#3759)
  src/Lean/Data/Json/FromToJson.lean
Labels: toolchain-available

#3237 chore: remove FileMap.lines and add FileMap.getLine
  src/Lean/Data/Position.lean
Labels: builds-mathlib, toolchain-available

#3762 fix: functional induction: preseve order of cases better
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/funind_fewer_levels.lean
  tests/lean/run/funind_proof.lean
  tests/lean/run/funind_tests.lean
Labels: toolchain-available

#3765 fix: change `Quotient.sound` to a `theorem`
  src/Init/Core.lean
Labels: toolchain-available

#3766 feat: ignore explicit proofs in canonicalizer
  src/Lean/Meta/Canonicalizer.lean
  tests/lean/run/omegaCanon.lean
Labels: toolchain-available

#3767 chore: rename automatically generated "unfold" theorems
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Meta/Eqns.lean
  tests/lean/run/1026.lean
  tests/lean/run/nestedWF.lean
  tests/lean/run/reserved.lean
  tests/lean/run/splitIssue.lean
  tests/lean/run/splitList.lean
  tests/lean/run/structEqns.lean
  tests/lean/run/structuralEqns.lean
  tests/lean/run/structuralEqns2.lean
  tests/lean/run/structuralEqns3.lean
  tests/lean/run/wfEqns1.lean
  tests/lean/run/wfEqns2.lean
  tests/lean/run/wfEqns3.lean
  tests/lean/run/wfEqns4.lean
Labels: toolchain-available

#3645 fix: update System.FilePath.parent to handle edge cases for absolute paths
  src/Init/System/FilePath.lean
  tests/lean/filePath.lean
  tests/lean/filePath.lean.expected.out
Labels: awaiting-author, awaiting-review, builds-mathlib, toolchain-available, full-ci

#3648 refactor: simplify `Array.findIdx?` code
  src/Init/Data/Array/Basic.lean
Labels: builds-mathlib, toolchain-available

#3753 fix: actually catch the error code from MoveFileEx
  src/runtime/io.cpp
Labels: builds-mathlib, toolchain-available

#3738 feat: functional induction for structural recursion
  RELEASES.md
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/funind_demo.lean
  tests/lean/run/funind_expr.lean
  tests/lean/run/funind_fewer_levels.lean
  tests/lean/run/funind_structural.lean
  tests/lean/run/funind_tests.lean
Labels: builds-mathlib, toolchain-available

#3771 feat: failing macros to show error from first registered rule
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Basic.lean
  tests/lean/run/issue3770.lean
  tests/lean/runTacticMustCatchExceptions.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3776 feat: use reserved name infrastructure for functional induction
  RELEASES.md
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/funind_errors.lean
  tests/lean/funind_errors.lean.expected.out
  tests/lean/run/funind_demo.lean
  tests/lean/run/funind_expr.lean
  tests/lean/run/funind_fewer_levels.lean
  tests/lean/run/funind_mutual_dep.lean
  tests/lean/run/funind_proof.lean
  tests/lean/run/funind_structural.lean
  tests/lean/run/funind_tests.lean
Labels: toolchain-available

#3769 fix: lemma selection improvements to to rw? and lazy discriminator tree
  src/Lean/Meta/LazyDiscrTree.lean
  src/Lean/Meta/Tactic/Rewrites.lean
  tests/lean/librarySearch.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#3783 chore: rw? uses MVarId.refl not MVarId.applyRfl
  src/Lean/Meta/Tactic/Rewrites.lean
Labels: toolchain-available

#3788 fix: remove derive_functional_induction
  src/Init/Data/Array/Basic.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Parser/Command.lean
Labels: toolchain-available, full-ci

#3715 chore: test results as job summary
  .github/workflows/ci.yml
  .github/workflows/nix-ci.yml
  doc/flake.nix
  flake.lock
  nix/bootstrap.nix
Labels: builds-mathlib, toolchain-available

#3790 chore: reorganising to reduce imports
  src/Init.lean
  src/Init/Conv.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/String/Extra.lean
  src/Init/Ext.lean
  src/Init/MacroTrace.lean
  src/Init/Meta.lean
  src/Init/NotationExtra.lean
  src/Init/Omega/LinearCombo.lean
  src/Init/RCases.lean
  src/Lean/Data/Json/Basic.lean
  src/Lean/Data/Parsec.lean
  src/Lean/Data/PersistentArray.lean
  src/Lean/Data/PersistentHashMap.lean
  src/Lean/Data/Rat.lean
  src/Lean/Data/Xml/Basic.lean
  src/Lean/DocString.lean
  src/Lean/LabelAttribute.lean
  src/Lean/Meta/Tactic/Simp/RegisterCommand.lean
Labels: toolchain-available

#3784 feat: change apply_rfl tactic so that it does not operate on =
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Rfl.lean
  src/Lean/Meta/Tactic/Rfl.lean
  tests/lean/run/rewrites.lean
Labels: toolchain-available

#3751 feat: hovering over omission term shows reason for omission
  src/Lean/Elab/InfoTree/Main.lean
  src/Lean/Elab/InfoTree/Types.lean
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  src/Lean/Server/FileWorker/WidgetRequests.lean
  src/Lean/Server/InfoUtils.lean
Labels: awaiting-review, toolchain-available

#3701 chore: fix rebase suggestion for Mathlib CI
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3746 fix: make generalized field notation for abbreviation types handle optional parameters
  src/Lean/Elab/App.lean
  tests/lean/run/3745.lean
Labels: awaiting-review, toolchain-available

#3743 doc: edit `Lean.MVarId.withReverted`
  src/Lean/Meta/Tactic/Replace.lean
Labels: awaiting-review, toolchain-available

#3660 fix: toUInt64LE! and toUInt64BE! are swapped
  src/Init/Data/ByteArray/Basic.lean
  tests/lean/bytearray.lean
Labels: toolchain-available, will-merge-soon

#3655 feat: add option `tactic.customEliminators` to be able to turn off custom eliminators for `induction` and `cases`
  RELEASES.md
  src/Lean/Elab/Tactic/Induction.lean
  tests/lean/run/customEliminators.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon, full-ci

#3794 fix: remove unused try catch
  src/Lean/Meta/Tactic/Rewrites.lean
Labels: toolchain-available

#3694 chore: extend GetElem with getElem! and getElem?
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Subarray.lean
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/FloatArray/Basic.lean
  src/Init/Data/List/Basic.lean
  src/Init/GetElem.lean
  src/Init/Meta.lean
  src/Init/Prelude.lean
  src/Init/Tactics.lean
  src/Init/Util.lean
  src/Lean/Data/HashMap.lean
  src/Lean/Data/PersistentArray.lean
  src/Lean/Data/PersistentHashMap.lean
  tests/lean/lcnfTypes.lean.expected.out
Labels: toolchain-available

#3796 doc: typo in rcases docs
  src/Init/RCases.lean
Labels: toolchain-available

#3800 chore: fix `simproc` doc-string
  src/Init/Simproc.lean
Labels: toolchain-available

#3799 fix: require `ident`s come in a column after the start of a command
  src/Lean/Parser/Command.lean
Labels: builds-mathlib, toolchain-available

#3795 fix: lake: check normalized packages directory path before rename
  src/lake/Lake/Load/Main.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3803 fix: reserved name resolution
  src/Lean/Meta/Match/MatchEqs.lean
  src/Lean/ResolveName.lean
  tests/lean/run/matchEqsBug.lean
  tests/lean/run/reservedNameResolution.lean
Labels: toolchain-available

#3779 feat: `lake test`
  src/lake/Lake/CLI/Actions.lean
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Translate/Lean.lean
  src/lake/Lake/CLI/Translate/Toml.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/DSL/Attributes.lean
  src/lake/Lake/Load/Elab.lean
  src/lake/Lake/Load/Package.lean
  src/lake/Lake/Load/Toml.lean
  src/lake/tests/test/clean.sh
  src/lake/tests/test/exe.lean
  src/lake/tests/test/exe.toml
  src/lake/tests/test/none.lean
  src/lake/tests/test/none.toml
  src/lake/tests/test/script.lean
  src/lake/tests/test/test.lean
  src/lake/tests/test/test.sh
  src/lake/tests/test/two.lean
  src/lake/tests/translateConfig/out.expected.lean
  src/lake/tests/translateConfig/out.expected.toml
  src/lake/tests/translateConfig/source.lean
  src/lake/tests/translateConfig/source.toml
Labels: builds-mathlib, toolchain-available, will-merge-soon
