Repository leanprover/lean4, pull requests merged in 2024-11, with the labels that each got.

#5880 feat: interim implementation of `HashMap.modify`/`alter`
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/HashMap/Basic.lean
  tests/lean/run/hashmap.lean
Labels: toolchain-available

#5900 chore: remove @[simp] from Sum.forall and Sum.exists
  src/Init/Data/Sum/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5721 feat: add `BitVec.(msb, getMsbD, getLsbD)_(neg, abs)`
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#5912 chore: minor tweaks to Array lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Monadic.lean
Labels: toolchain-available

#5898 feat: activate new tactic configuration syntax for most tactics
  src/Init/Conv.lean
  src/Init/Meta.lean
  src/Init/Tactics.lean
  src/Init/TacticsExtra.lean
  src/Lean/Elab/Tactic/Config.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Elab/Tactic/SimpTrace.lean
  src/Lean/Elab/Tactic/Simpa.lean
  src/Lean/Elab/Tactic/SolveByElim.lean
  stage0/src/stdlib_flags.h
Labels: builds-mathlib, toolchain-available

#5918 fix: bv_normalize loose mvars
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
Labels: toolchain-available

#5919 feat: make "type mismatch" error add numeric type ascriptions
  src/Lean/Expr.lean
  src/Lean/Meta/Check.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/issue3232.lean.expected.out
  tests/lean/run/addPPExplicitToExposeDiff.lean
Labels: toolchain-available

#5922 feat: on "type mismatch" errors, expose differences in functions and pi types
  src/Lean/Expr.lean
  src/Lean/Meta/Check.lean
  tests/lean/run/addPPExplicitToExposeDiff.lean
Labels: toolchain-available

#5888 feat: better error message for invalid induction alternative name
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Message.lean
  tests/lean/inductionErrors.lean.expected.out
  tests/lean/run/inductionCheckAltNames.lean
Labels: builds-mathlib, toolchain-available

#5265 chore: remove unused deriving handler argument syntax
  src/Lean/Elab/BuiltinEvalCommand.lean
  src/Lean/Elab/Deriving/Basic.lean
  src/Lean/Parser/Command.lean
  stage0/src/stdlib_flags.h
Labels: breaks-mathlib, toolchain-available

#5911 feat: make `MapDeclarationExtension` tolerate multiple insertions
  src/Lean/Data/RBMap.lean
  src/Lean/Environment.lean
Labels: builds-mathlib, toolchain-available

#5924 feat: add `text` option for `buildFile*` utilities
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Build/Trace.lean
Labels: builds-mathlib, toolchain-available

#5928 chore: prepare `omega` and `solve_by_elim` for new tactic config syntax
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/Elab/Tactic/SolveByElim.lean
Labels: toolchain-available

#5930 feat: add --short-version (-V) option to display short version
  src/util/shell.cpp
Labels: toolchain-available

#5932 feat: update `omega`/`solve_by_elim` to use new tactic syntax, use new tactic syntax
  src/Init/Data/Array/Bootstrap.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/Nat/Dvd.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Tactics.lean
  src/Init/WFTactics.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/Elab/Tactic/SolveByElim.lean
  src/Std/Sat/AIG/CachedGates.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Add.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Assignment.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RatAddResult.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RatAddSound.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddSound.lean
  src/lake/Lake/Util/Name.lean
  stage0/src/stdlib_flags.h
  tests/lean/interactive/1403.lean.expected.out
Labels: toolchain-available

#5933 fix: `..` in patterns should not make use of optparams or autoparams
  src/Lean/Elab/App.lean
  tests/lean/run/4555.lean
Labels: builds-mathlib, toolchain-available

#5936 chore: begin development cycle for v4.15
  RELEASES.md
  src/CMakeLists.txt
Labels: toolchain-available

#5937 chore: upstream lemmas about Fin.foldX
  src/Init/Data/Fin/Fold.lean
Labels: toolchain-available

#5941 feat: List.mapFinIdx, lemmas, relate to Array version
  src/Init/Data/Array/MapIdx.lean
  src/Init/Data/List/MapIdx.lean
  src/Init/Data/List/Nat/Range.lean
Labels: toolchain-available

#5942 feat: introduce synthetic atoms in bv_decide
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reflect.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVExpr.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVPred.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reify.lean
  tests/lean/run/bv_counterexample.lean
Labels: toolchain-available

#5885 feat: add Int16/Int32/Int64
  src/Init/Data/SInt/Basic.lean
  src/include/lean/lean.h
  src/runtime/mpz.cpp
  src/runtime/mpz.h
  src/runtime/object.cpp
  tests/lean/sint_basic.lean
  tests/lean/sint_basic.lean.expected.out
Labels: builds-mathlib, toolchain-available, release-ci

#5684 feat: update toolchain on `lake update`
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/Build/Topological.lean
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Init.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/Config/Env.lean
  src/lake/Lake/Config/InstallPath.lean
  src/lake/Lake/Config/Monad.lean
  src/lake/Lake/Config/Opaque.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/Lake/Load/Config.lean
  src/lake/Lake/Load/Materialize.lean
  src/lake/Lake/Load/Resolve.lean
  src/lake/Lake/Load/Workspace.lean
  src/lake/Lake/Toml/Data/DateTime.lean
  src/lake/Lake/Util/Date.lean
  src/lake/Lake/Util/Lift.lean
  src/lake/Lake/Util/Log.lean
  src/lake/Lake/Util/MainM.lean
  src/lake/Lake/Util/Version.lean
  src/lake/examples/deps/bar/lake-manifest.expected.json
  src/lake/examples/scripts/expected.out
  src/lake/tests/clone/test.sh
  src/lake/tests/depTree/test.sh
  src/lake/tests/env/test.sh
  src/lake/tests/manifest/lake-manifest-v1.1.0.json
  src/lake/tests/online/test.sh
  src/lake/tests/order/bar/lakefile.lean
  src/lake/tests/order/baz/X.lean
  src/lake/tests/order/baz/lakefile.lean
  src/lake/tests/order/clean.sh
  src/lake/tests/order/test.sh
  src/lake/tests/toolchain/.gitignore
  src/lake/tests/toolchain/clean.sh
  src/lake/tests/toolchain/lakefile.lean
  src/lake/tests/toolchain/test.sh
  src/lake/tests/updateToolchain/.gitignore
  src/lake/tests/updateToolchain/a/lakefile.toml
  src/lake/tests/updateToolchain/b/lakefile.toml
  src/lake/tests/updateToolchain/clean.sh
  src/lake/tests/updateToolchain/lakefile.toml
  src/lake/tests/updateToolchain/test.lean
  src/lake/tests/updateToolchain/test.sh
Labels: builds-mathlib, toolchain-available

#5934 fix: make `all_goals` admit goals on failure
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  tests/lean/run/4888.lean
  tests/lean/run/allGoals.lean
Labels: builds-mathlib, toolchain-available

#5946 chore: release notes for 4.13.0
  RELEASES.md
Labels: builds-mathlib, toolchain-available

#5947 chore: port release notes for v4.13.0 to master
  RELEASES.md
Labels: toolchain-available

#5927 feat: `List.pmap_eq_self`
  src/Init/Data/List/Attach.lean
Labels: toolchain-available

#5926 feat: add `Option.or_some'`
  src/Init/Data/Option/Lemmas.lean
Labels: toolchain-available

#5951 chore: remove @[simp] from BitVec.ofFin_sub and sub_ofFin
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5950 feat: relate Array.takeWhile with List.takeWhile
  src/Init/Data/Array/Bootstrap.lean
  src/Init/Data/Array/GetLit.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/GetElem.lean
Labels: toolchain-available

#5952 feat: relate Array.eraseIdx with List.eraseIdx
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Nat/Erase.lean
Labels: toolchain-available

#5953 chore: CI: give Linux Debug unlimited test stack size
  .github/workflows/ci.yml
Labels: toolchain-available, release-ci

#5961 feat: define ISize and basic operations on it
  src/Init/Data/SInt/Basic.lean
  src/include/lean/lean.h
  src/runtime/int.h
  src/runtime/object.cpp
  tests/lean/sint_basic.lean
  tests/lean/sint_basic.lean.expected.out
Labels: toolchain-available

#5966 fix: do not link statically against pthread/dl/rt
  script/prepare-llvm-linux.sh
Labels: toolchain-available

#5967 chore: fix `all_goals` test, simulate the max rec depth error
  tests/lean/run/4888.lean
  tests/lean/run/allGoals.lean
Labels: toolchain-available

#5970 chore: deprecate Array.split in favour of identical Array.partition
  src/Init/Data/Array/Basic.lean
  src/Lean/Elab/Match.lean
Labels: toolchain-available

#5968 fix: `arg` conv tactic misreported number of arguments on error
  src/Lean/Elab/Tactic/Conv/Congr.lean
  tests/lean/run/conv_arg.lean
Labels: toolchain-available

#5971 feat: relate Array.isPrefixOf with List.isPrefixOf
  src/Init/Data/Array/Lemmas.lean
Labels: toolchain-available

#5949 chore: consolidate `decide_True` and `decide_true_eq_true`
  src/Init/Core.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/SimpLemmas.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Neg.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftLeft.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Ult.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RatAddSound.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddSound.lean
Labels: builds-mathlib, toolchain-available

#5972 feat: relate Array.zipWith/zip/unzip with List versions
  src/Init/Data/Array/Bootstrap.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#5973 chore: exclude leanruntest_task_test_io for now
  .github/workflows/ci.yml
Labels: toolchain-available

#5974 feat: add another List.find?_eq_some lemma
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Nat/Find.lean
  src/Init/Data/List/Nat/Range.lean
Labels: toolchain-available

#5943 chore: tag prerelease builds with `-pre`
  src/CMakeLists.txt
  src/library/module.cpp
  src/library/util.cpp
  src/version.h.in
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5982 feat: minor lemmas about List.ofFn
  src/Init/Data/List/OfFn.lean
Labels: toolchain-available

#5969 chore: upstream List.insertIdx from Batteries, lemmas from Mathlib, and revise lemmas
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Impl.lean
  src/Init/Data/List/Nat.lean
  src/Init/Data/List/Nat/InsertIdx.lean
  src/Init/Data/List/Nat/Modify.lean
Labels: toolchain-available

#5984 feat: interactions between List.foldX and List.filterX
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Monadic.lean
Labels: toolchain-available

#5985 feat: lemmas relating Array.findX and List.findX
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Control.lean
Labels: toolchain-available

#5987 feat: BitVec.getMsbD in bv_decide
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_bitwise.lean
Labels: toolchain-available

#5981 refactor: name the default SizeOf instance
  src/Init/SizeOf.lean
Labels: toolchain-available

#5990 chore: fix test exclusion
  .github/workflows/ci.yml
  tests/lean/run/task_test_io.lean
Labels: toolchain-available, release-ci

#5992 style: fix style in bv_decide normalizer
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_bitwise.lean
Labels: toolchain-available

#5976 chore: new PR changelog template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-body.yml
Labels: builds-mathlib, toolchain-available

#6001 chore: revert "CI: give Linux Debug unlimited test stack size"
  .github/workflows/ci.yml
Labels: toolchain-available

#6007 chore: List.modifyTailIdx naming fix
  src/Init/Data/List/Nat/InsertIdx.lean
  src/Init/Data/List/Nat/Modify.lean
Labels: toolchain-available

#6008 chore: missing @[ext] attribute on monad transformer ext lemmas
  src/Init/Control/Lawful/Instances.lean
Labels: toolchain-available

#5866 feat: verify keys method on HashMaps
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Perm.lean
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Lemmas.lean
  src/Std/Data/DHashMap/Internal/List/Associative.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/Raw.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Basic.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/Raw.lean
  src/Std/Data/HashSet/RawLemmas.lean
Labels: toolchain-available, changelog-library

#6010 feat: change bv_decide to an elaborated config
  src/Lean/Elab/Tactic/BVDecide/External.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Attr.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVCheck.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVTrace.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/LRAT.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Std/Tactic/BVDecide/Syntax.lean
  tests/lean/run/5664.lean
  tests/lean/run/bv_arith.lean
  tests/lean/run/bv_axiom_check.lean
  tests/lean/run/bv_bitwise.lean
  tests/lean/run/bv_decide_rewriter.lean
  tests/lean/run/bv_errors.lean
  tests/lean/run/bv_substructure.lean
Labels: toolchain-available, changelog-language

#5996 fix: avoid max heartbeat error in completion
  src/Lean/Server/Completion.lean
Labels: builds-mathlib, toolchain-available

#5429 perf: avoid negative environment lookup
  src/Lean/Meta/WHNF.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#6002 chore: CI: exempt drafts from PR body check
  .github/workflows/pr-body.yml
Labels: toolchain-available, will-merge-soon

#5999 feat: `decide +revert` and improvements to `native_decide`
  src/Init/Prelude.lean
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/ElabTerm.lean
  src/Lean/Parser/Tactic.lean
  tests/lean/1825.lean.expected.out
  tests/lean/interactive/completionTactics.lean.expected.out
  tests/lean/run/4306.lean
  tests/lean/run/decideBang.lean
  tests/lean/run/decideNative.lean
  tests/lean/run/decideTactic.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#5856 feat: prop `instance` yields theorems
  src/Lean/Elab/DefView.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/PreDefinition/Main.lean
  tests/lean/run/5672.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6014 fix: avoid delaborating with field notation if object is a metavariable
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/474.lean.expected.out
  tests/lean/rewrite.lean.expected.out
  tests/lean/run/5993.lean
  tests/lean/run/meta2.lean
  tests/lean/run/scopedunifhint.lean
Labels: builds-mathlib, toolchain-available, changelog-pp

#6017 fix: bv_decide benchmarks
  tests/bench/bv_decide_inequality.lean
  tests/bench/bv_decide_mod.lean
Labels: toolchain-available, changelog-no

#6021 chore: cleanup
  src/Lean/Meta/Basic.lean
  src/Lean/MetavarContext.lean
Labels: builds-mathlib, toolchain-available

#5616 feat: BitVec lemmas for smtUDiv, smtSDiv when denominator is zero
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-review, toolchain-available, changelog-library

#6023 feat: variants of List.forIn_eq_foldlM
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Monadic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Lemmas.lean
  tests/lean/run/list_simp.lean
Labels: builds-mathlib, toolchain-available

#6025 chore: deprecate duplicated Fin.size_pos
  src/Init/Data/BitVec/Folds.lean
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/Fin/Lemmas.lean
  tests/lean/librarySearch.lean
Labels: toolchain-available

#5988 feat: change Array.set to take a Nat and a tactic provided bound
  src/Init.lean
  src/Init/Data/Array.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/BasicAux.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Set.lean
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/FloatArray/Basic.lean
  src/Init/Meta.lean
  src/Init/Prelude.lean
  src/Init/Syntax.lean
  src/Lean/Data/PersistentArray.lean
  src/Lean/Elab/Inductive.lean
  src/Lean/Environment.lean
  src/Lean/Meta/Closure.lean
  src/Lean/Meta/DiscrTree.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/GeneralizeTelescope.lean
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/SynthInstance.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Sat/AIG/CNF.lean
  src/lake/Lake/Toml/Data/Dict.lean
  tests/lean/arrayGetU.lean
  tests/lean/run/heapSort.lean
  tests/lean/run/inlineWithNestedRecIssue.lean
  tests/lean/run/issue3204.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6029 feat: BitVec normalization rule for udiv by twoPow
  src/Init/Data/BitVec/Lemmas.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#6035 feat: bv_decide and flattening
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Std/Tactic/BVDecide/Normalize/Bool.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#6031 fix: avoid new term info around `def` bodies
  src/Lean/Elab/LetRec.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Term.lean
  src/Lean/Linter/UnusedVariables.lean
  tests/lean/1018unknowMVarIssue.lean.expected.out
  tests/lean/interactive/highlight.lean
  tests/lean/interactive/highlight.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-server, backport releases/v4.14.0

#6037 fix: bv_decide embedded constraint substitution changes models
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#5920 feat: only direct parents of classes create projections
  src/Lean/Elab/Structure.lean
  tests/lean/run/2905.lean
  tests/lean/run/3313.lean
  tests/lean/run/mathlibetaissue.lean
  tests/lean/struct1.lean
  tests/lean/struct1.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language

#6041 chore: review Array operations argument order
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/MapIdx.lean
Labels: toolchain-available

#6044 feat: various minor changes to List/Array API
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/GetElem.lean
Labels: toolchain-available, changelog-no

#6051 chore: mark `Meta.Context.config` as private
  src/Lean/Elab/PreDefinition/WF/Fix.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/DiscrTree.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/GetUnfoldableConst.lean
  src/Lean/Meta/InferType.lean
  src/Lean/Meta/LazyDiscrTree.lean
  src/Lean/Meta/LevelDefEq.lean
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/SynthInstance.lean
  src/Lean/Meta/Tactic/Intro.lean
  src/Lean/Meta/Tactic/Rewrites.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/UnificationHint.lean
  src/Lean/Meta/WHNF.lean
  src/Lean/PrettyPrinter/Delaborator/TopDownAnalyze.lean
Labels: builds-mathlib, toolchain-available

#6054 refactor: mark the `Simp.Context` constructor as private
  src/Lean/Elab/PreDefinition/Nonrec/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Lean/Elab/Tactic/Conv/Pattern.lean
  src/Lean/Elab/Tactic/NormCast.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Elab/Tactic/Simpa.lean
  src/Lean/Meta/Tactic/AC/Main.lean
  src/Lean/Meta/Tactic/Acyclic.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Simp/Attr.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/SimpAll.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  src/Lean/Meta/Tactic/Split.lean
  src/Lean/Meta/Tactic/SplitIf.lean
  src/Lean/Meta/Tactic/Unfold.lean
Labels: breaks-mathlib, toolchain-available

#5991 refactor: omega: avoid MVar machinery
  src/Lean/Elab/Tactic/Omega/Frontend.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#6069 chore: pr-body: run as part of merge_group, but do not do anything
  .github/workflows/pr-body.yml
Labels: toolchain-available, will-merge-soon

#6048 fix: line break in `simp?` output
  src/Init/Tactics.lean
  tests/lean/interactive/builtinCodeactions.lean
  tests/lean/interactive/builtinCodeactions.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language

#6060 feat: Bool.to(U)IntX
  src/Init/Data/SInt/Basic.lean
  src/Init/Data/UInt/Basic.lean
  src/include/lean/lean.h
  tests/lean/bool2int.lean
  tests/lean/bool2int.lean.expected.out
Labels: toolchain-available, changelog-library

#6061 test: synthetic simp_arith benchmark
  tests/bench/simp_arith1.lean
  tests/bench/speedcenter.exec.velcom.yaml
Labels: builds-mathlib, toolchain-available, will-merge-soon

#6024 fix: make sure monad lift coercion elaborator has no side effects
  src/Init/Data/Fin/Lemmas.lean
  src/Lean/Meta/Coe.lean
  tests/lean/1018unknowMVarIssue.lean.expected.out
  tests/lean/1081.lean.expected.out
  tests/lean/1433.lean.expected.out
  tests/lean/755.lean
  tests/lean/755.lean.expected.out
  tests/lean/calcErrors.lean.expected.out
  tests/lean/coeM.lean
  tests/lean/etaStructIssue.lean.expected.out
  tests/lean/isDefEqOffsetBug.lean.expected.out
  tests/lean/mulcommErrorMessage.lean.expected.out
  tests/lean/phashmap_inst_coherence.lean.expected.out
  tests/lean/run/1017.lean
  tests/lean/run/4405.lean
  tests/lean/run/4413.lean
  tests/lean/run/PPTopDownAnalyze.lean
  tests/lean/run/scopedLocalReducibility.lean
  tests/lean/run/sealCommand.lean
  tests/lean/run/wfirred.lean
  tests/pkg/builtin_attr/UserAttr/Tst.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#5945 feat: message kinds
  src/Lean/Elab/Command.lean
  src/Lean/Message.lean
  tests/lean/run/messageKind.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6057 chore: remove >6 month old deprecations
  src/Init/Data/Array/Subarray.lean
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/Option/Basic.lean
  src/Init/Data/String/Basic.lean
  src/Lean/Meta/Tactic/Apply.lean
Labels: toolchain-available

#6056 chore: upstream some NameMap functions
  src/Lean/Data/NameMap.lean
  src/Lean/Data/RBMap.lean
  src/Lean/Data/RBTree.lean
Labels: toolchain-available

#6055 feat: lemmas about for loops over Array
  src/Init/Data/Array.lean
  src/Init/Data/Array/Attach.lean
  src/Init/Data/Array/Bootstrap.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Monadic.lean
  src/Init/Data/List/Impl.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Convert.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/Lemmas.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddSound.lean
Labels: toolchain-available, changelog-library

#6072 feat: add `Context.setConfig`
  src/Lean/Meta/Tactic/Simp/Types.lean
Labels: toolchain-available, changelog-no

#6073 refactor: lake: avoid `v!` in builtin code
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Translate/Lean.lean
  src/lake/Lake/CLI/Translate/Toml.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Load/Manifest.lean
  src/lake/Lake/Load/Toml.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#6074 refactor: allow `Sort u` in `Squash`
  src/Init/Core.lean
Labels: toolchain-available

#6077 feat: add options to configure all of bv_decide's preprocessing
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Std/Tactic/BVDecide/Syntax.lean
Labels: toolchain-available, changelog-language

#6012 fix: validate atoms modulo leading and trailing whitespace
  src/Lean/Elab/Syntax.lean
  tests/lean/242.lean
  tests/lean/242.lean.expected.out
  tests/lean/run/utf8英語.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon, changelog-language

#6070 feat: Lean.RArray
  src/Init/Data.lean
  src/Init/Data/RArray.lean
  src/Lean/Data.lean
  src/Lean/Data/RArray.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6052 feat: implementation of Array.pmap
  src/Init/Data/Array/Attach.lean
Labels: toolchain-available, changelog-library

#6040 chore: join → flatten in docstring
  src/Init/Data/List/Basic.lean
Labels: toolchain-available

#6080 chore: bv_decide remove noop rewrites
  src/Std/Tactic/BVDecide/Normalize/Canonicalize.lean
Labels: toolchain-available, changelog-no

#6087 fix: constant folding for Nat.ble and Nat.blt
  src/Lean/Compiler/ConstFolding.lean
  src/include/lean/lean.h
  tests/lean/run/6086.lean
Labels: toolchain-available, changelog-compiler

#6019 perf: remove `@[specialize]` from mkBinding
  src/Lean/MetavarContext.lean
Labels: builds-mathlib, toolchain-available

#6093 refactor: use mkFreshUserName in ArgsPacker
  src/Lean/Meta/ArgsPacker.lean
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/funind_tests.lean
Labels: toolchain-available, will-merge-soon

#6016 chore: remove `decide!` tactic
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/ElabTerm.lean
  tests/lean/run/decideTacticKernel.lean
Labels: toolchain-available, changelog-language

#2934 feat: `pp.parens` option to pretty print with all parentheses
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  src/Lean/PrettyPrinter/Parenthesizer.lean
  tests/lean/run/ppParens.lean
Labels: toolchain-available, changelog-pp

#6094 feat: add `Float.toBits` and `Float.fromBits`
  src/Init/Data/Float.lean
  src/include/lean/lean.h
  src/runtime/object.cpp
  tests/lean/run/floatBits.lean
Labels: toolchain-available, changelog-library

#6097 chore: naming convention and `NaN` normalization
  src/Init/Data/Float.lean
  src/include/lean/lean.h
  src/runtime/object.cpp
  tests/lean/run/floatBits.lean
Labels: toolchain-available

#6098 fix: use `Expr.equal` instead of `==` in `MVarId.replaceTargetDefEq` and `MVarId.replaceLocalDeclDefEq`
  src/Lean/Meta/Tactic/Replace.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6049 feat: IO.getTID
  src/Init/System/IO.lean
  src/runtime/process.cpp
Labels: builds-mathlib, toolchain-available, release-ci, changelog-library

#6105 fix: circular assignment at structure instance elaborator
  src/Lean/Elab/StructInst.lean
  tests/lean/run/3150.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6082 chore: fix canonicalizer handling over forall/lambda
  src/Lean/Meta/Canonicalizer.lean
  tests/lean/run/canonM_exists_fun.lean
Labels: toolchain-available

#6103 chore: avoid stack overflow in debug tests
  src/include/lean/lean.h
Labels: toolchain-available, release-ci

#6106 chore: fix naming of left/right injectivity lemmas
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Int/Lemmas.lean
Labels: toolchain-available

#6053 fix: `isDefEq`, `whnf`, `simp` caching and configuration
  src/Lean/Elab/Tactic/DiscrTreeKey.lean
  src/Lean/Elab/Tactic/Ext.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Elab/Tactic/Simproc.lean
  src/Lean/Meta/ACLt.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/DiscrTree.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/FunInfo.lean
  src/Lean/Meta/InferType.lean
  src/Lean/Meta/Instances.lean
  src/Lean/Meta/LazyDiscrTree.lean
  src/Lean/Meta/SynthInstance.lean
  src/Lean/Meta/Tactic/Rfl.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/SimpAll.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  src/Lean/Meta/Tactic/Simp/Simproc.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  src/Lean/Meta/Tactic/Symm.lean
  src/Lean/Meta/UnificationHint.lean
  src/Lean/Meta/WHNF.lean
  tests/lean/1018unknowMVarIssue.lean.expected.out
  tests/lean/letFun.lean
  tests/lean/run/ack.lean
  tests/lean/run/meta3.lean
  tests/lean/run/meta5.lean
  tests/lean/run/simp1.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6109 fix: backtrack at `injection` failure
  src/Lean/Meta/Tactic/Injection.lean
Labels: toolchain-available, changelog-language

#6110 chore: document `Lean.Elab.StructInst`, refactor
  src/Lean/Elab/StructInst.lean
Labels: toolchain-available, changelog-doc

#6111 feat: lemmas for `Array.findSome?` and `find?`
  src/Init/Data/Array/Find.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Option/Lemmas.lean
Labels: toolchain-available, changelog-library

#6113 chore: make Lean.Elab.Command.mkMetaContext public
  src/Lean/Elab/Command.lean
Labels: toolchain-available, changelog-no

#6116 fix: handle reordered indices in structural recursion
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Elab/PreDefinition/Structural/IndGroupInfo.lean
  src/Lean/Elab/PreDefinition/Structural/RecArgInfo.lean
  tests/lean/run/issue6015.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, changelog-language

#6121 chore: fix apply? error reporting when out of heartbeats
  src/Lean/Elab/Tactic/LibrarySearch.lean
Labels: toolchain-available, changelog-no

#6108 chore: turn off pp.mvars in apply? results
  src/Lean/Meta/Tactic/TryThis.lean
  tests/lean/librarySearch.lean
  tests/lean/run/3922.lean
  tests/lean/run/show_term.lean
Labels: toolchain-available

#6102 feat: use `BaseIO` at `IO.rand`
  src/Init/Data/Random.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6127 test: fix brittle structure instance completion test
  tests/lean/interactive/completionStructureInstance.lean
  tests/lean/interactive/completionStructureInstance.lean.expected.out
Labels: toolchain-available

#6095 chore: generalize `List.get_mem`
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Lemmas.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
Labels: builds-mathlib, toolchain-available

#5837 fix: don't issue atomic id completions when there is a dangling dot
  src/Lean/Server/Completion/CompletionCollectors.lean
  tests/lean/interactive/completionDanglingDot.lean
  tests/lean/interactive/completionDanglingDot.lean.expected.out
Labels: toolchain-available, changelog-server

#5840 fix: only consider salient bytes in sharecommon eq, hash
  src/include/lean/lean.h
  src/runtime/object.cpp
  src/runtime/sharecommon.cpp
Labels: toolchain-available, P-high, changelog-compiler

#6129 fix: `isDefEq` when `zetaDelta := false`
  src/Lean/Meta/ExprDefEq.lean
  tests/lean/run/heapSort.lean
  tests/lean/run/zetaDeltaFalseDefEqIssue.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#2689 fix: add a missing case to `Level.geq`
  src/Lean/Level.lean
  tests/lean/run/2689.lean
  tests/lean/run/level.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#6131 fix: `isDefEq` for constants with different universe parameters
  src/Lean/Meta/ExprDefEq.lean
  tests/lean/run/6117.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6096 feat: have `#print` show precise fields of structures
  src/Lean/Elab/Print.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/diamond1.lean.expected.out
  tests/lean/diamond8.lean.expected.out
  tests/lean/printStructure.lean
  tests/lean/run/2291.lean
  tests/lean/run/4465.lean
  tests/lean/run/print_cmd.lean
  tests/lean/structAutoBound.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available, changelog-language, changelog-pp

#6132 feat: duplicate List.attach/attachWith/pmap API for Array
  src/Init/Data/Array/Attach.lean
  src/Init/Data/Array/Find.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Control.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Sublist.lean
Labels: toolchain-available, changelog-library

#6133 feat: Array.insertIdx/eraseIdx take a tactic-provided proof
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/BinSearch.lean
  src/Init/Data/Array/Lemmas.lean
  src/Lean/Compiler/LCNF/Basic.lean
  src/Lean/Compiler/LCNF/PassManager.lean
  src/Lean/Compiler/Specialize.lean
  src/Lean/Data/PersistentHashMap.lean
  src/Lean/Elab/App.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/Do.lean
  src/Lean/Elab/PatternVar.lean
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/PreDefinition/WF/PackMutual.lean
  src/Lean/Elab/Quotation.lean
  src/Lean/Elab/Syntax.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Meta/IndPredBelow.lean
  src/Lean/Meta/Match/MatchEqs.lean
  src/Lean/Meta/RecursorInfo.lean
  src/Lean/Meta/Tactic/Clear.lean
  src/Lean/MetavarContext.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/Structure.lean
  tests/lean/interactive/completionDocString.lean
  tests/lean/interactive/completionDocString.lean.expected.out
  tests/lean/run/array_isEqvAux.lean
Labels: toolchain-available, changelog-library

#6137 feat: thread support for trace.profiler.output
  src/Lean/Elab/Frontend.lean
  src/Lean/Language/Basic.lean
  src/Lean/Language/Lean.lean
  src/Lean/Util/Profiler.lean
  src/Lean/Util/Trace.lean
Labels: toolchain-available, changelog-other

#6136 fix: `Inhabited Float` produced a bogus run-time value
  src/Init/Data/Float.lean
  tests/compiler/float.lean
  tests/compiler/float.lean.expected.out
Labels: toolchain-available, changelog-library

#6141 refactor: make use of recursive structures in snapshot types
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Elab/Term.lean
  src/Lean/Language/Lean.lean
  src/Lean/Language/Lean/Types.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/FileWorker/Utils.lean
  src/Lean/Server/Requests.lean
Labels: builds-mathlib, toolchain-available

#6128 fix: type occurs check bug
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/MetavarContext.lean
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/run/meta5.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6144 doc: doc-strings to module docs in Data/Array/Lemmas
  src/Init/Data/Array/Lemmas.lean
Labels: toolchain-available

#6134 chore: avoid runtime array bounds checks
  src/Init/Meta.lean
  src/Init/NotationExtra.lean
  src/Init/System/Uri.lean
  src/Lean/Compiler/IR/EmitC.lean
  src/Lean/Compiler/IR/EmitLLVM.lean
  src/Lean/Compiler/IR/ExpandResetReuse.lean
  src/Lean/Compiler/LCNF/SpecInfo.lean
  src/Lean/Compiler/LCNF/ToLCNF.lean
  src/Lean/Compiler/Specialize.lean
  src/Lean/Elab/Deriving/Util.lean
  src/Lean/Elab/Do.lean
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/LetRec.lean
  src/Lean/Elab/Match.lean
  src/Lean/Elab/Open.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/PreDefinition/TerminationArgument.lean
  src/Lean/Elab/PreDefinition/TerminationHint.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/Syntax.lean
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Environment.lean
  src/Lean/Meta/CongrTheorems.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/ForEachExpr.lean
  src/Lean/Meta/Match/MatchEqs.lean
  src/Lean/Meta/Tactic/ElimInfo.lean
  src/Lean/Meta/Tactic/Simp/SimpAll.lean
  src/Lean/Meta/Tactic/Split.lean
  src/Lean/Meta/Tactic/TryThis.lean
  src/Lean/PrettyPrinter/Delaborator/FieldNotation.lean
  src/Lean/PrettyPrinter/Delaborator/TopDownAnalyze.lean
  src/Lean/Syntax.lean
  src/lake/Lake/Toml/Data/Dict.lean
Labels: toolchain-available, changelog-no

#6126 feat: BitVec.getElem_[sub|neg|sshiftRight'|abs]
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#6147 chore: add changelog-* labels via comment
  .github/workflows/labels-from-comments.yml
Labels: toolchain-available

#6146 fix: nontermination when generating the match-expression splitter theorem
  src/Lean/Meta/Match/MatchEqs.lean
  tests/lean/run/6065.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6159 refactor: one more recursive structure
  src/Lean/Language/Basic.lean
Labels: toolchain-available

#6161 fix: make sure whitespace is printed before tactic configuration
  src/Init/Tactics.lean
  tests/lean/run/tactic_config.lean
Labels: toolchain-available, changelog-pp

#6162 perf: speed up reflection of if in bv_decide
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedLemmas.lean
Labels: toolchain-available, changelog-no

#6158 doc: adjust file reference in Data.Sum
  src/Init/Data/Sum/Basic.lean
Labels: toolchain-available

#6145 fix: `revert` creates natural metavariable goal
  src/Lean/Meta/Tactic/Revert.lean
  tests/lean/run/revertMetavarKind.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6119 feat: display coercions with a type ascription
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  tests/lean/run/coeAttrs.lean
Labels: awaiting-author, toolchain-available, changelog-pp

#6166 feat: add builtin attribute to support elaboration of mutual inductives/structures
  src/Lean/Elab.lean
  src/Lean/Elab/MutualInductive.lean
Labels: toolchain-available, changelog-no

#6139 feat: `Nat.(fold|foldRev|any|all)M?` take a function which sees the upper bound
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Nat.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Control.lean
  src/Init/Data/Nat/Fold.lean
  src/Lean/Compiler/IR/Borrow.lean
  src/Lean/Compiler/IR/Boxing.lean
  src/Lean/Compiler/IR/ElimDeadBranches.lean
  src/Lean/Compiler/IR/EmitC.lean
  src/Lean/Compiler/IR/EmitLLVM.lean
  src/Lean/Compiler/IR/ExpandResetReuse.lean
  src/Lean/Compiler/IR/RC.lean
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
  src/Lean/Compiler/LCNF/InferType.lean
  src/Lean/Data/PersistentArray.lean
  src/Lean/Elab/App.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/LocalContext.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Closure.lean
  src/Lean/Meta/LazyDiscrTree.lean
  src/Lean/Meta/Match/Match.lean
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/Tactic/Apply.lean
  src/Lean/Meta/Tactic/Cases.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Meta/Tactic/Induction.lean
  src/Lean/Meta/Tactic/Subst.lean
  src/Lean/MetavarContext.lean
  src/Lean/PrettyPrinter/Formatter.lean
  src/Lean/PrettyPrinter/Parenthesizer.lean
  tests/bench/qsort.lean
  tests/compiler/phashmap.lean
  tests/compiler/phashmap2.lean
  tests/compiler/phashmap3.lean
  tests/compiler/rbmap_library.lean
  tests/lean/IRbug.lean
  tests/lean/Reformat.lean
  tests/lean/ref1.lean
  tests/lean/run/unexpected_result_with_bind.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6148 feat: create temporary directories
  src/Init/System/IO.lean
  src/runtime/io.cpp
  tests/lean/run/tempfile.lean
Labels: toolchain-available, will-merge-soon, changelog-library

#6143 fix: make the stack handling more robust to sanitizers and `-O3`
  src/runtime/stackinfo.cpp
Labels: toolchain-available, release-ci, changelog-compiler

#6009 doc: fix typo and make docstring more precise
  src/Init/Notation.lean
Labels: builds-mathlib, toolchain-available

#6170 feat: creation and reporting for asynchronous elaboration tasks
  src/Lean/CoreM.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Term.lean
  src/Lean/Language/Basic.lean
  src/Lean/Language/Lean.lean
  src/Lean/Language/Lean/Types.lean
  src/Lean/Language/Util.lean
  src/Lean/Util/Trace.lean
  tests/lean/run/structuralMutual.lean
  tests/lean/unfoldReduceMatch.lean.expected.out
Labels: toolchain-available, changelog-language

#6173 chore: add test for recursive structures
  tests/lean/run/structure_recursive.lean
Labels: toolchain-available, changelog-no
