Repository leanprover/lean4, pull requests merged in 2024-05, with the labels that each got.

#4033 fix: lake: log refactor bugs
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/Build/Run.lean
  src/lake/examples/hello/test.sh
Labels: toolchain-available, full-ci

#4034 fix: use correct expr positions when delaborating `match` patterns
  RELEASES.md
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/SubExpr.lean
  tests/lean/run/delabMatch.lean
Labels: toolchain-available

#4043 feat: include congruence theorems at `simp` diagnostic information
  src/Lean/Meta/Diagnostics.lean
  src/Lean/Meta/Tactic/Simp/Diagnostics.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
Labels: toolchain-available

#4044 perf: improve `simp` cache behavior for well-behaved dischargers
  src/Lean/Elab/Tactic/NormCast.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  tests/lean/run/3943.lean
  tests/lean/run/simpDiag.lean
  tests/lean/run/simp_cache_perf_issue.lean
Labels: toolchain-available

#4045 doc: mention build doc source location
  README.md
Labels: builds-mathlib, toolchain-available

#4048 feat: display diagnostic information at term and tactic `set_option diagnostics true`
  src/Lean/Compiler/ExternAttr.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/BuiltinTerm.lean
  src/Lean/Elab/InfoTree/Main.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Meta/Tactic/Simp/Diagnostics.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/PrettyPrinter.lean
  src/Lean/Replay.lean
  src/lake/Lake/CLI/Translate.lean
  src/lake/Lake/Toml/Load.lean
  tests/lean/run/diagnostics.lean
  tests/lean/run/simpDiag.lean
Labels: toolchain-available

#4049 chore: report used instances correctly in diagnostics
  src/Lean/Meta/Diagnostics.lean
Labels: toolchain-available

#4047 refactor: do not try rfl in mkEqnTypes in WF.mkEqns
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4046 feat: subst notation (heq ▸ h) tries both orientation
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Parser/Term.lean
  tests/lean/substFails.lean
  tests/lean/substFails.lean.expected.out
Labels: toolchain-available, will-merge-soon

#4036 feat: `IO.Process.get/setCurrentDir`
  src/Init/System/IO.lean
  src/runtime/process.cpp
  tests/lean/run/currentDir.lean
Labels: builds-mathlib, toolchain-available, full-ci

#4029 chore: cleanup and remove unnecessary `checkpointDefEq`
  src/Lean/Meta/ExprDefEq.lean
Labels: toolchain-available

#4056 chore: lake: cleanup tests
  src/lake/examples/ffi/app/lakefile.lean
  src/lake/examples/hello/lakefile.lean
  src/lake/examples/targets/test.sh
  src/lake/tests/badImport/test.sh
  src/lake/tests/clone/test.sh
  src/lake/tests/clone/test/lakefile.lean
  src/lake/tests/depTree/test.sh
  src/lake/tests/env/test.sh
  src/lake/tests/init/test.sh
  src/lake/tests/llvm-bitcode-gen/test.sh
  src/lake/tests/lock/test.sh
  src/lake/tests/manifest/lake-manifest-v6.json
  src/lake/tests/manifest/lake-manifest-v7.json
  src/lake/tests/manifest/lakefile.lean
  src/lake/tests/manifest/test.sh
  src/lake/tests/meta/test.sh
  src/lake/tests/order/test.sh
  src/lake/tests/postUpdate/test.sh
  src/lake/tests/precompileArgs/lakefile.lean
  src/lake/tests/precompileArgs/test.sh
  src/lake/tests/rebuild/test.sh
  src/lake/tests/serve/test.sh
  src/lake/tests/test/test.sh
  src/lake/tests/toolchain/test.sh
Labels: toolchain-available

#4057 feat: lake: `require` doc comments
  src/lake/Lake/DSL/Require.lean
  src/lake/examples/deps/bar/lakefile.lean
Labels: toolchain-available

#4058 chore: begin development cycle for v4.9.0
  RELEASES.md
  src/CMakeLists.txt
Labels: toolchain-available

#3328 feat: support idents in auto tactics
  src/Lean/Elab/Binders.lean
  src/Lean/ToExpr.lean
  tests/lean/run/autoparam.lean
Labels: toolchain-available

#3915 doc: layout algorithm
  doc/dev/ffi.md
Labels: toolchain-available

#4052 feat: validate reducibility attribute setting
  src/Lean/Meta/LazyDiscrTree.lean
  src/Lean/ReducibilityAttrs.lean
  tests/lean/run/1123.lean
  tests/lean/run/reducibilityAttrValidation.lean
  tests/lean/run/rewrite.lean
  tests/lean/run/scopedLocalReducibility.lean
  tests/pkg/builtin_attr/UserAttr/Tst.lean
Labels: toolchain-available

#4053 feat: add `seal` and `unseal` commands
  src/Init/Notation.lean
  tests/lean/run/sealCommand.lean
Labels: toolchain-available

#4065 fix: bug in reduceLeDiff simproc proof term
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Nat.lean
  tests/lean/run/simproc1.lean
Labels: toolchain-available, backport releases/v4.8.0

#4067 fix: rfl tactic error messsage when there are no goals
  src/Init/Tactics.lean
  tests/lean/run/issue4063.lean
Labels: toolchain-available, will-merge-soon

#4071 fix: have app unexpanders be considered before field notation
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/FieldNotation.lean
  tests/lean/run/delabProjectionApp.lean
Labels: builds-mathlib, toolchain-available, full-ci

#4059 feat: upstream lemmas about basic List/Array operations
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/TakeDrop.lean
  tests/lean/run/heapSort.lean
  tests/lean/run/rwRegression.lean
  tests/lean/run/structuralIssue2.lean
Labels: toolchain-available, will-merge-soon

#4037 feat: lemmas to simplify equalities with `Option`-typed dependent if-then-else
  src/Init/ByCases.lean
Labels: builds-mathlib, toolchain-available

#3591 fix: Incorrect promotion from index to paramater
  src/Lean/Elab/Inductive.lean
  src/Lean/Util/ForEachExprWhere.lean
  tests/lean/run/3458_2.lean
Labels: builds-mathlib, toolchain-available

#3920 feat: equivalence of bit-vector negation and bitblasted negation
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Folds.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-author, builds-mathlib, toolchain-available

#3398 fix: occurence check in `mkInjectiveTheoremTypeCore?`
  src/Lean/Meta/Injective.lean
  tests/lean/run/3386.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#4074 refactor: Array.feraseIdx: avoid have in definition
  src/Init/Data/Array/Basic.lean
Labels: toolchain-available

#4055 fix: remove `Subtype.instInhabited`
  src/Init/Core.lean
Labels: builds-mathlib, toolchain-available

#4077 chore: move @[simp] attribute on length_eq_zero earlier
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#4080 fix: code duplication at `liftCoreM` and `liftTermElabM` at `Command.lean`
  src/Lean/CoreM.lean
  src/Lean/Elab/Command.lean
Labels: toolchain-available

#4082 feat: collect kernel diagnostic information
  src/Lean/CoreM.lean
  src/Lean/Elab/Command.lean
  src/Lean/Environment.lean
  src/Lean/Meta/Diagnostics.lean
  src/kernel/environment.cpp
  src/kernel/environment.h
  src/kernel/inductive.cpp
  src/kernel/type_checker.cpp
  src/kernel/type_checker.h
  tests/lean/run/ack.lean
Labels: toolchain-available

#4073 chore: allow omega to use classicality, in case Decidable instances are too big
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  tests/lean/run/omega.lean
Labels: toolchain-available, will-merge-soon

#4088 chore: lake: tweak hovers for `family_def` et al
  src/lake/Lake/Build/Data.lean
  src/lake/Lake/Util/Family.lean
  src/lake/Lake/Util/Name.lean
Labels: toolchain-available

#4100 feat: relaxed reset/reuse in the code generator
  src/Lean/Compiler/IR/ResetReuse.lean
  tests/lean/4089.lean
  tests/lean/4089.lean.expected.out
Labels: toolchain-available

#4095 feat: bitvec lemma to turn negation into bitwise not+add
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#4094 fix: swap `Nat.zero_or` and `Nat.or_zero`
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: awaiting-review, toolchain-available

#4092 perf: issue at `binop%` and `binrel%` elaborators
  src/Lean/Elab/Extra.lean
  tests/lean/run/binop_binrel_perf_issue.lean
Labels: toolchain-available, full-ci, backport releases/v4.8.0

#4001 doc: add docstrings and usage examples in `Init.Data.String.Basic`
  src/Init/Data/String/Basic.lean
Labels: awaiting-review, breaks-mathlib, toolchain-available

#3944 fix: make deriving handler for `Repr` be consistent about erasing types and proofs
  src/Lean/Elab/Deriving/Repr.lean
  tests/lean/derivingRepr.lean
  tests/lean/derivingRepr.lean.expected.out
  tests/lean/run/derivingRepr.lean
Labels: toolchain-available, will-merge-soon

#4108 chore: Std -> Batteries renaming
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/pr-release.yml
  doc/BoolExpr.lean
  doc/dev/release_checklist.md
  doc/monads/states.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Omega/Coeffs.lean
  src/Init/Tactics.lean
  src/Lean/Meta/Tactic/LibrarySearch.lean
  tests/lean/librarySearch.lean
Labels: toolchain-available

#4066 fix: mainModuleName should use srcSearchPath
  src/Lean/Elab/Frontend.lean
  src/Lean/Language/Basic.lean
  src/Lean/Language/Lean.lean
  src/Lean/Server/FileWorker.lean
Labels: builds-mathlib, toolchain-available, full-ci

#4109 chore: bug template: point to live.lean-lang.org
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: awaiting-review, toolchain-available

#4098 refactor: make 1 % n reduce without well-founded recursion
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Nat/Div.lean
Labels: builds-mathlib, toolchain-available

#4112 chore: remove dead function`preprocessLevels`
  src/Lean/Meta/SynthInstance.lean
Labels: toolchain-available

#4096 perf: use `withSynthesize` when elaborating `let`/`have` type
  src/Lean/Elab/Binders.lean
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Elab/Extra.lean
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/StructInst.lean
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/ElabTerm.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Elab/Tactic/Meta.lean
  src/Lean/Elab/Tactic/Simp.lean
  tests/lean/run/4051.lean
  tests/lean/run/may_postpone_tc.lean
Labels: builds-mathlib, toolchain-available, full-ci

#3969 fix: generate deprecation warnings for dot notation
  src/Init/Data/Array/Subarray.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Stream.lean
  src/Lean/Data/RBTree.lean
  src/Lean/Elab/Term.lean
  tests/lean/deprecated.lean
Labels: builds-mathlib, toolchain-available, full-ci

#4113 feat: propagate `maxHeartbeats` to kernel
  src/Lean.lean
  src/Lean/AddDecl.lean
  src/Lean/Compiler/InitAttr.lean
  src/Lean/Compiler/Old.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Environment.lean
  src/Lean/Meta/Closure.lean
  src/Lean/Meta/Constructions.lean
  src/Lean/Meta/Eqns.lean
  src/Lean/Meta/Eval.lean
  src/Lean/Meta/SizeOf.lean
  src/Lean/Meta/Tactic/AuxLemma.lean
  src/Lean/Replay.lean
  src/kernel/environment.cpp
  src/runtime/interrupt.cpp
  src/runtime/interrupt.h
  tests/lean/partialIssue.lean
  tests/lean/run/kernel_maxheartbeats.lean
  tests/lean/run/structInstFast.lean
Labels: builds-mathlib, toolchain-available, full-ci

#4075 feat: add BitVec.[toInt_inj|toInt_ne]
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-author, toolchain-available

#2903 fix: segfault in old compiler due to noConfusion assumptions
  src/library/compiler/lcnf.cpp
  tests/lean/run/2901.lean
Labels: builds-mathlib, toolchain-available

#4104 fix: lake: TOML key order bug in `ppTable`
  src/lake/Lake/Toml/Data/Value.lean
  src/lake/tests/translateConfig/out.expected.toml
  src/lake/tests/translateConfig/source.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, backport releases/v4.8.0

#4061 feat: well-founded definitions irreducible by default
  RELEASES.md
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Gcd.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/ReducibilityAttrs.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/1921.lean
  tests/lean/run/2389.lean
  tests/lean/run/ack.lean
  tests/lean/run/casesRec.lean
  tests/lean/run/defaultEliminator.lean
  tests/lean/run/lazylistThunk.lean
  tests/lean/run/splitIssue.lean
  tests/lean/run/splitList.lean
  tests/lean/run/wfirred.lean
  tests/lean/wfrecUnusedLet.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon, full-ci

#4126 chore: remove duplicate check
  src/Lean/Elab/PreDefinition/WF/Main.lean
Labels: toolchain-available

#4125 fix: revert "monadic generalization of FindExpr"
  src/Lean/Meta/Injective.lean
  src/Lean/Util/FindExpr.lean
Labels: toolchain-available

#4128 fix: add `checkSystem` and `withIncRecDepth` to `withAutoBoundImplicit`
  src/Lean/Elab/Term.lean
  tests/lean/4117.lean
  tests/lean/4117.lean.expected.out
  tests/lean/run/simpDiag.lean
Labels: toolchain-available

#4129 refactor: add `tryCatchRuntimeEx` combinator
  src/Lean/CoreM.lean
  src/Lean/Meta/SynthInstance.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
Labels: toolchain-available

#4091 chore: tidying up `Lean.unresolveNameGlobal`
  src/Lean/ResolveName.lean
  tests/lean/run/2291.lean
Labels: toolchain-available

#4097 feat: `IO.TaskState`
  src/Init/System/IO.lean
  src/include/lean/lean.h
  src/runtime/io.cpp
  src/runtime/object.cpp
  src/runtime/object.h
  tests/lean/run/taskState.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, backport releases/v4.8.0

#4130 feat: recover from runtime errors in tactics
  src/Lean/CoreM.lean
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Elab/Tactic/Basic.lean
  tests/lean/run/3554.lean
Labels: toolchain-available

#4133 test: for issue 2558
  tests/lean/run/2558.lean
Labels: toolchain-available

#4132 fix: auto/option params should not break `sorry`
  src/Lean/Elab/BuiltinNotation.lean
  tests/lean/run/2649.lean
Labels: builds-mathlib, toolchain-available

#4139 fix: typo in `Meta.unfoldProjInstWhenInstances?`
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/WHNF.lean
Labels: toolchain-available

#4135 fix: check that funind-reserved names are available
  src/Lean/Elab/PreDefinition/Main.lean
  tests/lean/funind_reserved.lean
  tests/lean/funind_reserved.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4141 chore: incorrect lemma resolution in omega
  src/Lean/Elab/Tactic/Omega/OmegaM.lean
  tests/lean/run/omega.lean
Labels: toolchain-available

#4143 chore: move have to decreasing_by in substrEq.loop
  src/Init/Data/String/Basic.lean
Labels: toolchain-available

#4148 feat: BitVec.shiftLeft_shiftLeft, BitVec.shiftRight_shiftRight
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-author, toolchain-available

#4136 chore: rerun CI only when full-ci label is added or removed
  .github/workflows/ci.yml
  .github/workflows/nix-ci.yml
  .github/workflows/restart-on-label.yml
Labels: toolchain-available

#4145 refactor: let Nat.mod reduce more
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Nat/Div.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#4153 refactor: no need for `simpMatchWF?`
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  tests/lean/run/reserved.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4115 refactor: lake: import errors, job captions, log grouping
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Basic.lean
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Fetch.lean
  src/lake/Lake/Build/Imports.lean
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/DSL/Targets.lean
  src/lake/Lake/Util/EStateT.lean
  src/lake/Lake/Util/EquipT.lean
  src/lake/Lake/Util/Log.lean
  src/lake/Lake/Util/Proc.lean
  src/lake/examples/targets/lakefile.lean
  src/lake/examples/targets/test.sh
  src/lake/tests/badImport/.gitignore
  src/lake/tests/badImport/Lib/B.lean
  src/lake/tests/badImport/Lib/C.lean
  src/lake/tests/badImport/clean.sh
  src/lake/tests/badImport/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon, full-ci, backport releases/v4.8.0

#4119 fix: type class issues with `maxSynthPendingDepth := 1`
  src/Lean/CoreM.lean
  src/Lean/Elab/Calc.lean
  src/Lean/Elab/Term.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Diagnostics.lean
  src/Lean/Meta/SynthInstance.lean
  tests/lean/1007.lean.expected.out
  tests/lean/1102.lean.expected.out
  tests/lean/1163.lean.expected.out
  tests/lean/2040.lean.expected.out
  tests/lean/2220.lean.expected.out
  tests/lean/2273.lean.expected.out
  tests/lean/297.lean.expected.out
  tests/lean/345.lean.expected.out
  tests/lean/386.lean.expected.out
  tests/lean/448.lean.expected.out
  tests/lean/attrCmd.lean.expected.out
  tests/lean/calcErrors.lean.expected.out
  tests/lean/defInst.lean.expected.out
  tests/lean/defaultInstance.lean.expected.out
  tests/lean/eagerUnfoldingIssue.lean.expected.out
  tests/lean/eraseInsts.lean.expected.out
  tests/lean/forErrors.lean.expected.out
  tests/lean/kernelMVarBug.lean.expected.out
  tests/lean/macroStack.lean.expected.out
  tests/lean/macroSwizzle.lean.expected.out
  tests/lean/openScoped.lean.expected.out
  tests/lean/prvCtor.lean.expected.out
  tests/lean/run/3313.lean
  tests/lean/run/3996.lean
  tests/lean/run/guard_msgs.lean
  tests/lean/sanitychecks.lean.expected.out
  tests/lean/scopedLocalInsts.lean.expected.out
  tests/lean/semicolonOrLinebreak.lean.expected.out
  tests/lean/setLit.lean.expected.out
  tests/lean/tcloop.lean.expected.out
  tests/lean/typeOf.lean.expected.out
Labels: breaks-mathlib, toolchain-available, full-ci

#3967 chore: add dates to @[deprecated] attributes
  src/Init/Data/Array/Subarray.lean
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Option/Basic.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Tactic/Apply.lean
  src/Lean/Meta/Tactic/Assert.lean
  src/Lean/Meta/Tactic/Assumption.lean
  src/Lean/Meta/Tactic/Cases.lean
  src/Lean/Meta/Tactic/Cleanup.lean
  src/Lean/Meta/Tactic/Clear.lean
  src/Lean/Meta/Tactic/Constructor.lean
  src/Lean/Meta/Tactic/Contradiction.lean
  src/Lean/Meta/Tactic/Delta.lean
  src/Lean/Meta/Tactic/Generalize.lean
  src/Lean/Meta/Tactic/Induction.lean
  src/Lean/Meta/Tactic/Intro.lean
  src/Lean/Meta/Tactic/Refl.lean
  src/Lean/Meta/Tactic/Rename.lean
  src/Lean/Meta/Tactic/Replace.lean
  src/Lean/Meta/Tactic/Revert.lean
  src/Lean/Meta/Tactic/Rewrite.lean
  src/Lean/Meta/Tactic/Util.lean
  src/Lean/MetavarContext.lean
  src/Lean/Widget/UserWidget.lean
Labels: toolchain-available

#4164 feat: `grind` normalization theorems
  src/Init.lean
  src/Init/Grind.lean
  src/Init/Grind/Norm.lean
Labels: toolchain-available

#4165 chore: delete double namespace BitVec.BitVec
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#4170 feat: `grind` preprocessor skeleton
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available

#4163 [Backport releases/v4.8.0] refactor: lake: import errors, job captions, log grouping
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Basic.lean
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Fetch.lean
  src/lake/Lake/Build/Imports.lean
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/DSL/Targets.lean
  src/lake/Lake/Util/EStateT.lean
  src/lake/Lake/Util/EquipT.lean
  src/lake/Lake/Util/Log.lean
  src/lake/Lake/Util/Proc.lean
  src/lake/examples/targets/lakefile.lean
  src/lake/examples/targets/test.sh
  src/lake/tests/badImport/.gitignore
  src/lake/tests/badImport/Lib/B.lean
  src/lake/tests/badImport/Lib/C.lean
  src/lake/tests/badImport/clean.sh
  src/lake/tests/badImport/test.sh
Labels: builds-mathlib, toolchain-available

#4172 fix: List.length_pos no @[simp]
  src/Init/Data/List/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#4176 fix: make erased names in `simp` clickable
  src/Lean/Elab/Tactic/Simp.lean
Labels: toolchain-available

#4180 feat: add `cleanupAnnotations` parameter to `forallTelescope` methods
  src/Lean/Meta/Basic.lean
  tests/lean/docStr.lean.expected.out
  tests/lean/run/cleanup_forallTelescope.lean
Labels: toolchain-available

#4184 chore: fix bug in omega
  src/Lean/Elab/Tactic/Omega/OmegaM.lean
  tests/lean/run/omega.lean
Labels: toolchain-available

#4185 fix: cleanup type annotations in congruence theorems
  src/Lean/Meta/CongrTheorems.lean
  tests/lean/run/congrThm2.lean
Labels: toolchain-available

#4178 feat: bitblasting theorems about unsigned bitvector inequalities
  src/Init/Data/BitVec/Bitblast.lean
Labels: awaiting-review, toolchain-available

#4189 style: fix whitespace and remove duplicate docstring
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Lemmas.lean
Labels: awaiting-review, toolchain-available

#4186 chore: update RELEASES.md
  RELEASES.md
Labels: builds-mathlib, toolchain-available

#4194 feat: simprocs for applying `shiftLeft_shiftLeft` and `shiftRight_shiftRight`
  src/Init/Data/BitVec/Lemmas.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  tests/lean/run/bitvec_simproc.lean
Labels: toolchain-available

#4202 feat: add `Simp.Config.index`
  src/Init/MetaTypes.lean
  src/Lean/Meta/DiscrTree.lean
  src/Lean/Meta/Tactic/Simp/Diagnostics.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  tests/lean/run/4171.lean
Labels: toolchain-available

#4208 feat: pretty print `Array DiscrTree.Key`
  src/Lean/Meta/DiscrTree.lean
  src/Lean/Meta/Tactic/Simp/Diagnostics.lean
  tests/lean/run/4171.lean
  tests/lean/run/simpIndexDiag.lean
Labels: toolchain-available

#4127 feat: lake: build monitor improvements
  src/lake/Lake/Build/Basic.lean
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Executable.lean
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Fetch.lean
  src/lake/Lake/Build/Imports.lean
  src/lake/Lake/Build/Index.lean
  src/lake/Lake/Build/Info.lean
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Build/Key.lean
  src/lake/Lake/Build/Library.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/Build/Run.lean
  src/lake/Lake/CLI/Build.lean
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/DSL/Targets.lean
  src/lake/Lake/Util/EStateT.lean
  src/lake/Lake/Util/Log.lean
  src/lake/Lake/Util/MainM.lean
  src/lake/examples/targets/test.sh
  src/lake/tests/noRelease/clean.sh
  src/lake/tests/noRelease/dep/lakefile.lean
  src/lake/tests/noRelease/lakefile.lean
  src/lake/tests/noRelease/test.sh
  src/lake/tests/old/expected.out
  src/lake/tests/old/test.sh
  tests/pkg/test_extern/expected.txt
Labels: builds-mathlib, toolchain-available, will-merge-soon, full-ci, backport releases/v4.8.0

#4147 feat: lake: add readme to package templates
  src/lake/Lake/CLI/Init.lean
Labels: toolchain-available

#4210 fix: ensure a local instance is not registered multiple times
  src/Lean/Meta/Basic.lean
  tests/lean/run/4203.lean
Labels: toolchain-available

#4211 fix: `split at h` when `h` has forward dependencies
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Tactic/Split.lean
  tests/lean/run/3731.lean
Labels: toolchain-available

#3929 feat: apply’s error message should show implicit arguments as needed
  RELEASES.md
  src/Lean/CoreM.lean
  src/Lean/Exception.lean
  src/Lean/Message.lean
  src/Lean/Meta/Tactic/Apply.lean
  src/Lean/PrettyPrinter.lean
  src/Lean/Util/PPExt.lean
  src/Lean/Widget/InteractiveDiagnostic.lean
  tests/lean/issue3232.lean
  tests/lean/issue3232.lean.expected.out
Labels: breaks-mathlib, toolchain-available

#4216 fix: `canonInstances := true` issue
  src/Lean/Meta/SynthInstance.lean
  tests/lean/run/4213.lean
Labels: builds-mathlib, toolchain-available

#4215 fix: use maxType when building expression in expression tree elaborator
  src/Lean/Elab/Extra.lean
  tests/lean/binopIssues.lean
  tests/lean/binopIssues.lean.expected.out
  tests/lean/run/binop.lean
Labels: builds-mathlib, toolchain-available

#4206 fix: oversight in `isReadOnlyOrSyntheticOpaque`
  src/Lean/Meta/Basic.lean
  tests/lean/syntheticOpaqueReadOnly.lean
  tests/lean/syntheticOpaqueReadOnly.lean.expected.out
Labels: builds-mathlib, toolchain-available

#4217 fix: missing occurs-check at delayed assignment
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/MetavarContext.lean
  tests/lean/run/4144.lean
Labels: builds-mathlib, toolchain-available

#4222 chore: move release notes about MessageData to v4.9.0
  RELEASES.md
Labels: toolchain-available

#4220 chore: lake: cloud release build output fixes & related touchups
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/Build/Run.lean
  src/lake/tests/noRelease/Test.lean
  src/lake/tests/noRelease/clean.sh
  src/lake/tests/noRelease/dep/lakefile.lean
  src/lake/tests/noRelease/lakefile.lean
  src/lake/tests/noRelease/test.sh
Labels: toolchain-available, full-ci, backport releases/v4.8.0

#4199 feat: `Nat.shiftLeft_shiftRight`
  src/Init/Data/Nat/Lemmas.lean
Labels: toolchain-available

#3903 feat: make frontend normalize line endings to LF
  src/Init/Data/String/Extra.lean
  src/Lean/Data/Position.lean
  src/Lean/Parser/Basic.lean
  src/Lean/Parser/Extension.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/Utils.lean
  src/Lean/Server/Watchdog.lean
  src/lake/Lake/Build/Trace.lean
  src/lake/Lake/Util/Newline.lean
  src/lake/tests/toml/Test.lean
  tests/lean/run/crlfToLf.lean
  tests/lean/run/string_gaps.lean
  tests/lean/string_gaps.lean.expected.out
Labels: toolchain-available, full-ci

#4232 feat: lake: ANSI monitor: only display progress + running job info
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Basic.lean
  src/lake/Lake/Build/Fetch.lean
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Build/Run.lean
  src/lake/Lake/Util/Log.lean
  src/lake/Lake/Util/Opaque.lean
  src/lake/Lake/Util/Task.lean
Labels: breaks-mathlib, toolchain-available, full-ci, backport releases/v4.8.0

#4233 feat: some string `simproc`s
  src/Init/Data/String/Basic.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Char.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/String.lean
  tests/lean/run/simp6.lean
  tests/lean/run/string_simprocs.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#4235 feat: add `grind.cases` tactic
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Cases.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Induction.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available

#4236 chore: lake: spinner icon for computing step
  src/lake/Lake/Build/Run.lean
Labels: toolchain-available, backport releases/v4.8.0

#4229 feat: define rotateLeft/Right with modulo
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#4166 doc: add docstrings and examples for String functions
  src/Init/Data/String/Basic.lean
  tests/lean/run/string.lean
Labels: toolchain-available, will-merge-soon

#4231 feat: some `Char`, `UInt`, and `Fin` theorems
  src/Init/Data/Char.lean
  src/Init/Data/Char/Lemmas.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/String.lean
  src/Init/Data/String/Lemmas.lean
  src/Init/Data/UInt.lean
  src/Init/Data/UInt/Basic.lean
  src/Init/Data/UInt/Lemmas.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, full-ci

#4239 chore: Lake details & improve formatting in changelog
  RELEASES.md
Labels: toolchain-available

#4192 fix: hovers on binders with metavariables
  src/Lean/Elab/Term.lean
  tests/lean/1018unknowMVarIssue.lean.expected.out
  tests/lean/interactive/4078.lean
  tests/lean/interactive/4078.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#4243 feat: add `grind.injection`
  src/Lean/Meta/CtorRecognizer.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Injection.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available

#4244 chore: lake: fix `noRelease` test when lean repo is tagged
  src/lake/tests/noRelease/test.sh
Labels: breaks-mathlib, toolchain-available, full-ci

#4248 chore: fix implicitness in HashMap.ofList
  src/Lean/Data/HashMap.lean
Labels: toolchain-available

#4200 feat: characterize `BitVec.toInt` in terms of `BitVec.msb`
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, will-merge-soon

#3940 feat: incremental elaboration of definition headers, bodies, and tactics
  RELEASES.md
  doc/examples/test_single.sh
  nix/bootstrap.nix
  src/CMakeLists.txt
  src/Init/Data/String/Basic.lean
  src/Init/Prelude.lean
  src/Init/System/IO.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/DefView.lean
  src/Lean/Elab/Exception.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Elab/Term.lean
  src/Lean/Elab/Util.lean
  src/Lean/Language/Basic.lean
  src/Lean/Language/Lean.lean
  src/Lean/Message.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Parser/Module.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/Utils.lean
  src/Lean/Server/Snapshots.lean
  src/Lean/Syntax.lean
  src/runtime/alloc.cpp
  src/runtime/alloc.h
  src/runtime/io.cpp
  tests/lean/1079.lean.expected.out
  tests/lean/inductionErrors.lean
  tests/lean/inductionErrors.lean.expected.out
  tests/lean/interactive/editAfterError.lean
  tests/lean/interactive/editAfterError.lean.expected.out
  tests/lean/interactive/editCompletion.lean
  tests/lean/interactive/editCompletion.lean.expected.out
  tests/lean/interactive/incrementalCombinator.lean
  tests/lean/interactive/incrementalCombinator.lean.expected.out
  tests/lean/interactive/incrementalInduction.lean
  tests/lean/interactive/incrementalInduction.lean.expected.out
  tests/lean/interactive/incrementalMutual.lean
  tests/lean/interactive/incrementalMutual.lean.expected.out
  tests/lean/interactive/incrementalTactic.lean
  tests/lean/interactive/incrementalTactic.lean.expected.out
  tests/lean/interactive/run.lean
  tests/lean/interactive/unterminatedDocComment.lean
  tests/lean/interactive/unterminatedDocComment.lean.expected.out
  tests/lean/run/anonymous_ctor_error_msg.lean
  tests/lean/run/meta3.lean
  tests/lean/server/test_single.sh
  tests/pkg/frontend/Frontend/Compile.lean
Labels: breaks-mathlib, toolchain-available

#4252 fix: `case` tactic in macros
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  tests/lean/run/caseTacInMacros.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#4201 feat: bitblasting theorems for signed comparisons
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Int/Order.lean
Labels: toolchain-available

#4188 perf: faster `Nat.testBit`
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Nat/Bitwise/Basic.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: toolchain-available

#4247 chore: set up procedure for preparing release notes
  RELEASES.md
  releases_drafts/README.md
  releases_drafts/messagedata.md
  releases_drafts/wf.md
Labels: toolchain-available

#4238 fix: docstring in `Attributes.lean`
  src/Lean/Attributes.lean
Labels: toolchain-available

#4032 chore: modernize build instructions
  .github/workflows/ci.yml
  CMakePresets.json
  doc/make/index.md
  doc/make/msvc.md
  doc/make/msys2.md
Labels: toolchain-available, full-ci

#4259 fix: ensure incremental commands and tactics are reached only on supported paths
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Term.lean
  tests/lean/interactive/incrementalCommand.lean
  tests/lean/interactive/incrementalCommand.lean.expected.out
  tests/lean/interactive/run.lean
Labels: toolchain-available

#4255 chore: CI: move some expensive checks from merge queue to releases
  .github/workflows/ci.yml
  .github/workflows/restart-on-label.yml
Labels: toolchain-available, release-ci

#4205 chore: fix the `MonadStore` type classes, with semiOutParam
  src/lake/Lake/Util/Family.lean
  src/lake/Lake/Util/Store.lean
  src/lake/Lake/Util/StoreInsts.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#4264 chore: better `omega` error message if no facts found
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  tests/lean/omega-failure.lean
  tests/lean/omega-failure.lean.expected.out
  tests/lean/run/omega.lean
Labels: toolchain-available

#4265 chore: CI: native-compile aarch64 macOS
  .github/workflows/ci.yml
  doc/setup.md
Labels: toolchain-available, merge-ci

#4267 feat: show signature elaboration errors on body parse error
  src/Lean/Elab/DefView.lean
  src/Lean/Elab/MutualDef.lean
  tests/lean/3989_1.lean.expected.out
  tests/lean/3989_2.lean.expected.out
  tests/lean/799.lean.expected.out
  tests/lean/mutualdef1.lean.expected.out
  tests/lean/sanitychecks.lean.expected.out
  tests/lean/syntheticOpaqueReadOnly.lean.expected.out
Labels: toolchain-available

#4083 refactor: lake: manifest semver & code cleanup
  src/lake/Lake/Load/Main.lean
  src/lake/Lake/Load/Manifest.lean
  src/lake/Lake/Load/Materialize.lean
  src/lake/Lake/Util/JsonObject.lean
  src/lake/Lake/Util/Version.lean
  src/lake/examples/deps/bar/lake-manifest.expected.json
  src/lake/tests/manifest/lake-manifest-v1.0.0.json
  src/lake/tests/manifest/lake-manifest-v4.json
  src/lake/tests/manifest/lake-manifest-v5.json
  src/lake/tests/manifest/lake-manifest-v6.json
  src/lake/tests/manifest/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4261 feat: `lake test` improvements & `lake lint`
  src/lake/Lake/CLI/Actions.lean
  src/lake/Lake/CLI/Build.lean
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Translate/Lean.lean
  src/lake/Lake/CLI/Translate/Toml.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/DSL/Attributes.lean
  src/lake/Lake/DSL/AttributesCore.lean
  src/lake/Lake/Load/Elab.lean
  src/lake/Lake/Load/Main.lean
  src/lake/Lake/Load/Package.lean
  src/lake/Lake/Load/Toml.lean
  src/lake/Lake/Toml/Encode.lean
  src/lake/README.md
  src/lake/tests/driver/Test.lean
  src/lake/tests/driver/clean.sh
  src/lake/tests/driver/dep-invalid.lean
  src/lake/tests/driver/dep-invalid.toml
  src/lake/tests/driver/dep-unknown.lean
  src/lake/tests/driver/dep-unknown.toml
  src/lake/tests/driver/dep.lean
  src/lake/tests/driver/dep.toml
  src/lake/tests/driver/dep/lakefile.lean
  src/lake/tests/driver/driver.lean
  src/lake/tests/driver/exe.lean
  src/lake/tests/driver/exe.toml
  src/lake/tests/driver/lib.lean
  src/lake/tests/driver/lib.toml
  src/lake/tests/driver/none.lean
  src/lake/tests/driver/none.toml
  src/lake/tests/driver/runner.lean
  src/lake/tests/driver/runner.toml
  src/lake/tests/driver/script.lean
  src/lake/tests/driver/test.sh
  src/lake/tests/driver/two.lean
  src/lake/tests/driver/unknown.lean
  src/lake/tests/driver/unknown.toml
  src/lake/tests/test/exe.toml
  src/lake/tests/test/test.sh
  src/lake/tests/translateConfig/out.expected.lean
  src/lake/tests/translateConfig/out.expected.toml
  src/lake/tests/translateConfig/source.lean
  src/lake/tests/translateConfig/source.toml
Labels: breaks-mathlib, toolchain-available, will-merge-soon, release-ci

#4270 feat: `lake pack` / `lake unpack`
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/CLI/Actions.lean
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/examples/hello/test.sh
  src/lake/tests/noRelease/test.sh
Labels: breaks-mathlib, toolchain-available, will-merge-soon, release-ci

#4273 refactor: lake: ensure job actions can be lifted to `FetchM`
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Basic.lean
  src/lake/Lake/Build/Fetch.lean
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Build/Trace.lean
  src/lake/Lake/Util/IO.lean
Labels: toolchain-available

#4274 fix: do not include internal `match` equational theorems at simp trace
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Meta/Match/MatchEqsExt.lean
  tests/lean/run/4251.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#4268 fix: stray tokens in tactic block should not inhibit incrementality
  src/Lean/Parser/Command.lean
  tests/lean/interactive/incrementalTactic.lean
  tests/lean/interactive/incrementalTactic.lean.expected.out
Labels: toolchain-available

#4254 feat: widget messages
  src/Lean/Message.lean
  src/Lean/Widget/InteractiveDiagnostic.lean
  src/Lean/Widget/Types.lean
  src/Lean/Widget/UserWidget.lean
Labels: toolchain-available

#4294 fix: incorrect docstring for named pattern syntax
  src/Lean/Parser/Term.lean
Labels: toolchain-available, will-merge-soon

#4298 feat: upstream BitVec.toFin_ofNat and BitVec.toFin_neg
  src/Init/Data/BitVec/Lemmas.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4304 chore: add namespace in Init/Data/Fin/Fold
  src/Init/Data/Fin/Fold.lean
Labels: toolchain-available

#4307 feat: quotations for parser aliases
  src/Lean/Elab/MacroArgUtil.lean
  src/Lean/Elab/Quotation.lean
  src/Lean/Elab/Syntax.lean
  src/Lean/Parser/Extension.lean
  tests/lean/StxQuot.lean
  tests/lean/StxQuot.lean.expected.out
Labels: toolchain-available

#4311 fix: miscompilation in constant folding
  src/Lean/Compiler/ConstFolding.lean
  tests/lean/run/4306.lean
Labels: toolchain-available
