Repository leanprover/lean4, pull requests merged in 2024-08, with the labels that each got.

#4890 perf: precise cache for `expr_eq_fn`
  src/kernel/environment.cpp
  src/kernel/expr_eq_fn.cpp
  src/kernel/replace_fn.cpp
  src/runtime/sharecommon.cpp
  src/runtime/sharecommon.h
Labels: toolchain-available

#4884 fix: export symbols needed by Verso
  src/Lean/Compiler/IR/EmitC.lean
Labels: toolchain-available, will-merge-soon

#4893 fix: `LEAN_EXPORT` in sharecommon
  src/runtime/sharecommon.h
  stage0/src/runtime/sharecommon.h
Labels: toolchain-available, changes-stage0, release-ci

#4896 chore: revert "fix: make import resolution case-sensitive on all platforms"
  src/Lean/Elab/Import.lean
  src/Lean/Environment.lean
  src/Lean/Util/Path.lean
  src/lake/Lake/Build/Module.lean
  tests/pkg/import-case/.gitignore
  tests/pkg/import-case/ImportCase.lean
  tests/pkg/import-case/ImportCase/Basic.lean
  tests/pkg/import-case/lakefile.toml
  tests/pkg/import-case/test.sh
Labels: toolchain-available

#4648 doc: add docstring to `IO.FS.realpath`
  src/Init/System/IO.lean
Labels: toolchain-available

#4873 feat: getLsb_replicate
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Nat/Div.lean
Labels: toolchain-available

#4895 chore: deprecate Nix-based build, remove interactive components
  .github/workflows/nix-ci.yml
  doc/flake.lock
  doc/flake.nix
  flake.lock
  flake.nix
  nix/bootstrap.nix
  nix/buildLeanPackage.nix
  nix/packages.nix
Labels: builds-mathlib, toolchain-available

#4741 feat: accept user-defined options on the cmdline
  src/Lean/Elab/Frontend.lean
  src/util/shell.cpp
  tests/pkg/user_opt/UserOptCmdline.lean
  tests/pkg/user_opt/lakefile.lean
  tests/pkg/user_opt/lakefile.toml
Labels: builds-mathlib, toolchain-available

#4700 perf: fix implementation of move constructors and move assignment ope…
  src/kernel/declaration.h
  src/kernel/expr.h
  src/kernel/level.h
  src/kernel/local_ctx.h
  src/library/compiler/specialize.cpp
  src/library/projection.h
  src/runtime/array_ref.h
  src/runtime/list_ref.h
  src/runtime/option_ref.h
  src/runtime/optional.h
  src/runtime/string_ref.h
  src/util/kvmap.h
  src/util/name.h
  src/util/nat.h
Labels: builds-mathlib, toolchain-available, release-ci, P-high

#4903 perf: use `NatPow Int` instead of `HPow Int Nat Int`
  src/Init/Data/Int/Basic.lean
  tests/lean/2040.lean
  tests/lean/2040.lean.expected.out
  tests/lean/2220.lean
  tests/lean/2220.lean.expected.out
  tests/lean/run/2220.lean
  tests/lean/run/4861.lean
Labels: builds-mathlib, toolchain-available

#4910 perf: add `lean_instantiate_level_mvars`
  src/Lean/MetavarContext.lean
  src/kernel/CMakeLists.txt
  src/kernel/instantiate_mvars.cpp
  src/kernel/level.h
  src/runtime/object_ref.h
  src/runtime/option_ref.h
Labels: toolchain-available

#4911 chore: cli help text: comma-separate alternative option forms
  src/util/shell.cpp
Labels: toolchain-available

#4912 perf: use `lean_instantiate_level_mvars`
  src/Lean/MetavarContext.lean
Labels: toolchain-available

#4913 chore: require docs in BitVec
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Folds.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#4914 chore: remove unnecessary steps from release checklist
  doc/dev/release_checklist.md
Labels: toolchain-available

#4919 chore: missing include on Windows
  src/runtime/thread.cpp
Labels: toolchain-available

#3106 feat: new snapshot architecture on the cmdline
  src/Lean/Elab/Frontend.lean
  src/Lean/Language/Lean.lean
  tests/lean/2505.lean.expected.out
  tests/lean/4089.lean.expected.out
  tests/lean/4240.lean.expected.out
  tests/lean/Process.lean.expected.out
  tests/lean/computedFieldsCode.lean.expected.out
  tests/lean/csimpAttr.lean.expected.out
  tests/lean/csimpAttrAppend.lean.expected.out
  tests/lean/dbgMacros.lean.expected.out
  tests/lean/doubleReset.lean.expected.out
  tests/lean/etaReducedMvarAssignments.lean.expected.out
  tests/lean/listLength.lean.expected.out
  tests/lean/lit_values.lean.expected.out
  tests/lean/unboxStruct.lean.expected.out
  tests/lean/updateExprIssue.lean.expected.out
Labels: builds-mathlib, toolchain-available

#4921 chore: cleanup `betaRev`
  src/Lean/Expr.lean
Labels: toolchain-available

#4922 perf: use `lean_instantiate_expr_mvars` at `instantiateExprMVars`
  src/Lean/MetavarContext.lean
Labels: toolchain-available

#4923 chore: profile `instantiateMVars` at `MutualDef.lean`
  src/Lean/Elab/MutualDef.lean
Labels: toolchain-available

#4924 feat: theorem diagnostics
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Util.lean
  src/Lean/Util/NumApps.lean
Labels: toolchain-available

#4925 chore: ignore stale leanpkg tests
  src/shell/CMakeLists.txt
Labels: toolchain-available

#4774 feat: generalized `Parsec`
  src/Init/Data/ByteArray/Basic.lean
  src/Lean/Data/Json/Parser.lean
  src/Lean/Data/Parsec.lean
  src/Lean/Data/Parsec/Basic.lean
  src/Lean/Data/Parsec/ByteArray.lean
  src/Lean/Data/Parsec/String.lean
  src/Lean/Data/Xml/Parser.lean
  tests/lean/1363.lean
  tests/lean/interactive/run.lean
Labels: toolchain-available

#4931 chore: reduce stack space usage at `instantiate_mvars_fn`
  src/kernel/instantiate_mvars.cpp
  tests/bench/dag_hassorry_issue.lean.args
Labels: toolchain-available

#4897 chore: wrap diagnostic results in `MessageData.trace`s
  src/Lean/Meta/Diagnostics.lean
  src/Lean/Meta/Tactic/Simp/Diagnostics.lean
  tests/lean/run/3313.lean
  tests/lean/run/4171.lean
  tests/lean/run/ack.lean
  tests/lean/run/diagRec.lean
  tests/lean/run/diagnostics.lean
  tests/lean/run/simpDiag.lean
Labels: toolchain-available

#4926 fix: ensure autoparam errors have correct positions
  src/Lean/Elab/App.lean
  src/Lean/Elab/StructInst.lean
  tests/lean/interactive/4880.lean
  tests/lean/interactive/4880.lean.expected.out
Labels: toolchain-available

#4934 perf: `expr_eq_fn`
  src/kernel/expr_eq_fn.cpp
Labels: toolchain-available

#4935 perf: skip `eraseRecAppSyntaxExpr` if it is not needed
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/RecAppSyntax.lean
Labels: toolchain-available

#4936 perf: skip `betaReduceLetRecApps` if it is not needed
  src/Lean/Elab/PreDefinition/Main.lean
Labels: toolchain-available

#4937 chore: minor fixes to release checklist
  doc/dev/release_checklist.md
Labels: toolchain-available

#4821 fix: language server windows issues
  src/Lean/Server/Watchdog.lean
  src/lake/Lake/Util/Proc.lean
Labels: toolchain-available

#4906 feat: Revamp file reading and writing
  src/Init/System/IO.lean
  src/runtime/io.cpp
  src/runtime/object.h
  tests/lean/run/3546.lean
Labels: toolchain-available

#4940 test: unflakify test cases
  tests/lean/Process.lean
  tests/lean/Process.lean.expected.out
Labels: toolchain-available

#4889 feat: sshiftRight bitblasting
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-review, toolchain-available, P-high

#4667 feat: add ushiftRight_*_distrib theorems
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-review, toolchain-available

#4945 feat: upstream utilities around `Array`, `Bool` and `Prod` from LeanSAT
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Prod.lean
Labels: toolchain-available

#4943 feat: deprecated variants of hash map query methods
  src/Std/Data/HashMap/Basic.lean
Labels: toolchain-available, will-merge-soon

#4930 chore: name variables in Data/BitVec consistently
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#4948 chore: Revert "feat: Revamp file reading and writing"
  src/Init/System/IO.lean
  src/runtime/io.cpp
  src/runtime/object.h
  tests/lean/run/3546.lean
Labels: toolchain-available

#4950 feat: revamp file IO, this time Windows compatible
  src/Init/System/IO.lean
  src/runtime/io.cpp
  stage0/src/runtime/io.cpp
  stage0/src/runtime/object.h
  tests/lean/run/3546.lean
Labels: changes-stage0, release-ci

#4955 doc: `stderrAsMessages` is now the default on the cmdline as well
  doc/dev/debugging.md
Labels: toolchain-available

#4956 fix: export more symbols needed by Verso
  src/Lean/Compiler/IR/EmitC.lean
Labels: toolchain-available, release-ci, backport releases/v4.11.0

#4647 chore: add parallelism fallback for macOS on build
  doc/make/index.md
Labels: toolchain-available

#4969 chore: upstream Thunk.ext
  src/Init/Ext.lean
Labels: toolchain-available

#4970 feat: add [ext] attribute to Array.ext
  src/Init/Ext.lean
  tests/lean/run/ext.lean
Labels: toolchain-available, new-user-papercuts, will-merge-soon

#4974 fix: resolve parser promise before starting elaboration
  src/Lean/Language/Lean.lean
Labels: needs-update-stage0, toolchain-available

#4833 fix: make cdot anonymous function notation handle ambiguous notation
  src/Lean/Elab/BuiltinNotation.lean
  tests/lean/diamond1.lean.expected.out
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/run/cdotTests.lean
Labels: builds-mathlib, toolchain-available, release-ci

#4976 feat: `@[app_delab]`
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  tests/lean/run/delabApp.lean
Labels: toolchain-available

#4981 feat: add Std.[Associative|Commutative] instances for BitVec.[and|or|xor]
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#4987 fix: regular mvar assignments take precedence over delayed ones
  src/kernel/instantiate_mvars.cpp
  tests/lean/run/4920.lean
Labels: toolchain-available

#4988 fix: panic at `reducePow`
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Nat.lean
  tests/lean/run/4947.lean
Labels: toolchain-available

#4989 fix: omega regression
  src/Init/Omega/Int.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  tests/lean/run/omega.lean
Labels: toolchain-available, backport releases/v4.11.0

#4986 chore: begin development cycle for v4.12.0
  RELEASES.md
  doc/dev/release_checklist.md
  releases_drafts/mutualStructural.md
  src/CMakeLists.txt
Labels: toolchain-available

#4977 feat: add BitVec.neg_neg
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#4990 chore: fix typo in hash code for `Expr` equality test
  src/kernel/expr_eq_fn.cpp
Labels: toolchain-available

#4514 fix: naming convention for `UInt` lemmas
  src/Init/Data/UInt/Lemmas.lean
  src/Std/Data/DHashMap/Internal/Index.lean
Labels: toolchain-available, P-medium

#4951 feat: add BitVec.[sshiftRight/shiftLeft]_*_distrib
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, P-high

#4960 feat: `TransGen r` is transitive
  src/Init/Core.lean
Labels: toolchain-available

#4957 chore: add deprecation for Array.get_modify
  src/Init/Data/Array/Lemmas.lean
Labels: toolchain-available

#4967 chore: when a linter crashes, prefix its name
  src/Lean/Elab/Command.lean
  tests/plugin/SnakeLinter.lean.expected.out
Labels: toolchain-available

#4995 chore: upstream `List.findIdx` lemmas
  src/Init/Data/List/Find.lean
Labels: toolchain-available

#4971 fix: handle SIGBUS when looking for stack overflows
  src/runtime/stack_overflow.cpp
Labels: toolchain-available, will-merge-soon, release-ci

#4996 fix: reduce default max depth for ext tactic
  src/Lean/Elab/Tactic/Ext.lean
Labels: toolchain-available

#4973 feat: handle \r on all operating systems in IO.FS.lines
  src/Init/System/IO.lean
  tests/lean/run/4573.lean
Labels: toolchain-available

#5001 fix: disable incremental body elaboration in presence of `where`
  src/Lean/Elab/MutualDef.lean
  tests/lean/interactive/incrementalCommand.lean
  tests/lean/interactive/incrementalCommand.lean.expected.out
Labels: toolchain-available

#4952 feat: output panics into Lean's redirected stderr
  src/runtime/object.cpp
  tests/lean/run/structure.lean
Labels: toolchain-available

#4963 feat: link LibUV
  .github/workflows/ci.yml
  doc/make/index.md
  doc/make/msys2.md
  doc/make/osx-10.9.md
  doc/make/ubuntu.md
  flake.nix
  nix/bootstrap.nix
  script/prepare-llvm-linux.sh
  script/prepare-llvm-macos.sh
  script/prepare-llvm-mingw.sh
  src/CMakeLists.txt
  src/Lean/Runtime.lean
  src/cmake/Modules/FindLibUV.cmake
  src/include/lean/lean_libuv.h
  src/runtime/CMakeLists.txt
  src/runtime/libuv.cpp
  src/runtime/libuv.h
  tests/lean/run/libuv.lean
Labels: toolchain-available, will-merge-soon, release-ci

#5003 chore: upgrade cache action to silence warnings
  .github/workflows/ci.yml
  .github/workflows/nix-ci.yml
  .github/workflows/update-stage0.yml
Labels: toolchain-available

#4982 fix: check is valid structure projection when pretty printing
  src/Lean/Elab/Print.lean
  src/Lean/PrettyPrinter/Delaborator/FieldNotation.lean
  tests/lean/run/4670.lean
Labels: toolchain-available

#5004 perf: avoid MT marking environment in language processor
  src/Lean/Language/Lean.lean
Labels: toolchain-available

#5009 chore: speedcenter: reduce number of runs for "fast" benchmarks from 10 to 3
  tests/bench/speedcenter.yaml
Labels: toolchain-available

#5010 feat: use save-always in cache action
  .github/workflows/ci.yml
  .github/workflows/nix-ci.yml
Labels: toolchain-available

#5014 chore: pr-release: adjust lakefile editing sed to new `git` syntax
  .github/workflows/pr-release.yml
Labels: toolchain-available, will-merge-soon

#5012 refactor: state `WellFoundedRelation Nat` using `<`, not `Nat.lt`
  src/Init/WF.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, release-ci

#5022 chore: ci.yaml: build MacOS Aarch64 release for PRs by default
  .github/workflows/ci.yml
Labels: toolchain-available

#5025 chore: pr-release: pass `--retry` to `curl`
  .github/workflows/pr-release.yml
Labels: toolchain-available, will-merge-soon

#5011 chore: use `≠` in `Fin.ne_of_val_ne`
  src/Init/Data/Fin/Basic.lean
  src/Init/Prelude.lean
Labels: toolchain-available

#5007 feat: express `BitVec.extractLsb'` in terms of `extractLsb`
  src/Init/Data/BitVec/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#4997 feat: add BitVec.toNat_[udiv|umod] and [udiv|umod]_eq
  src/Init/Data/BitVec/Lemmas.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#5029 feat: new+old lemmas about List.Sublist
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat.lean
  src/Init/Data/List/Nat/Basic.lean
  src/Init/Data/List/Nat/Sublist.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/Nat/Basic.lean
Labels: toolchain-available

#5030 chore: remove dead code in Lake.Util.Compare
  src/lake/Lake/Util/Compare.lean
  src/lake/Lake/Util/Name.lean
Labels: toolchain-available

#5031 chore: use local instance in Lsp.Diagnostics
  src/Lean/Data/Lsp/Diagnostics.lean
Labels: toolchain-available

#5033 chore: fix inconsistent style in internal hash map lemmas
  src/Std/Data/DHashMap/Internal/List/Perm.lean
  src/Std/Data/DHashMap/Internal/List/Sublist.lean
Labels: toolchain-available

#5018 fix: report info trees on cmdline for .ileans
  src/Lean/Language/Lean.lean
Labels: toolchain-available

#5037 fix: array_get_dec etc. tactics to solve more cases
  src/Init/Data/Array/Mem.lean
  src/Init/Data/List/BasicAux.lean
  tests/lean/run/issue5027.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5040 perf: mark entire reported info tree as persistent
  src/Lean/Language/Lean.lean
Labels: toolchain-available

#5042 chore: reduce usage of refine'
  src/Init/Control/ExceptCps.lean
  src/Init/Control/Lawful/Basic.lean
  src/Init/Control/StateCps.lean
  src/Init/Data/List/TakeDrop.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Config/Workspace.lean
  tests/lean/1870.lean
  tests/lean/1870.lean.expected.out
  tests/lean/run/2461.lean
  tests/lean/run/structWithAlgTCSynth.lean
Labels: toolchain-available

#5044 chore: upstream #time command
  src/Init/Notation.lean
  src/Lean/Elab.lean
  src/Lean/Elab/Time.lean
  tests/lean/run/time.lean
Labels: toolchain-available

#5045 chore: add libuv to the required packages heading in macos docs
  doc/make/osx-10.9.md
Labels: toolchain-available

#5047 chore: upstream List.Pairwise lemmas
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/PropLemmas.lean
Labels: toolchain-available

#5034 fix: macOS: install name of libleanshared_1
  src/CMakeLists.txt
  src/stdlib.make.in
Labels: toolchain-available

#5048 feat: more List.Sublist theorems
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Sublist.lean
Labels: toolchain-available

#5049 doc: add release note drafts for LibUV and hash map deprecation
  releases_drafts/hashmap.md
  releases_drafts/libuv.md
Labels: toolchain-available

#5053 feat: more List.find?/findSome?/findIdx? theorems
  src/Init/Data/List/Erase.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Range.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/Option/Lemmas.lean
Labels: toolchain-available

#5051 fix: Windows stage 0
  src/stdlib.make.in
  stage0/src/stdlib.make.in
Labels: toolchain-available, changes-stage0

#5052 chore: CI: fix 32bit stage 0 builds
  .github/workflows/ci.yml
Labels: toolchain-available

#5057 chore: avoid rebuilding `leanmanifest` in each build
  src/shell/CMakeLists.txt
Labels: toolchain-available

#5056 chore: remove stray `markPersistent`
  src/Lean/Language/Lean.lean
Labels: toolchain-available, release-ci

#5039 feat: List.foldlRecOn
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#5067 chore: minimize some imports
  src/Init/Data/AC.lean
  src/Init/Data/Queue.lean
  src/Lean/Util/Diff.lean
Labels: toolchain-available

#5068 refactor: generalize addMatcherInfo
  src/Lean/Meta/Match/MatcherInfo.lean
Labels: toolchain-available

#5070 fix: remove partially copied code comment
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
Labels: toolchain-available

#5073 feat: simp debug trace tag to use “dpre” in `rlfOnly` mode
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
Labels: toolchain-available, will-merge-soon

#5072 feat: make structure type clickable in “not a field” error
  src/Lean/Elab/StructInst.lean
Labels: toolchain-available, will-merge-soon

#4717 fix: instantiate mvars of indices before instantiating fvars
  src/Lean/Elab/Inductive.lean
  tests/lean/run/3242.lean
Labels: awaiting-review, builds-mathlib, toolchain-available, release-ci, P-medium

#5077 chore: fix implicitness in refl/rfl lemma binders
  src/Init/Data/List/Sublist.lean
Labels: toolchain-available

#5069 feat: upstream List.Perm
  src/Init/Data/List.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Perm.lean
  src/Std/Data/DHashMap/Internal/AssocList/Lemmas.lean
  src/Std/Data/DHashMap/Internal/List/Associative.lean
  src/Std/Data/DHashMap/Internal/List/Pairwise.lean
  src/Std/Data/DHashMap/Internal/List/Perm.lean
  src/Std/Data/DHashMap/Internal/Model.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  tests/lean/run/constructor_as_variable.lean
Labels: toolchain-available

#5080 fix: correct typo in invalid reassignment error
  src/Lean/Elab/Do.lean
  tests/lean/doNotation1.lean.expected.out
Labels: toolchain-available

#5071 feat: expose `index` option to `dsimp` tactic
  src/Init/MetaTypes.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5062 fix: Do not overwrite existing signal handlers
  src/runtime/stack_overflow.cpp
Labels: builds-mathlib, toolchain-available, P-high

#5090 fix: disable incrementality in `case .. | ..`
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  tests/lean/interactive/incrementalCombinator.lean
  tests/lean/interactive/incrementalCombinator.lean.expected.out
Labels: toolchain-available

#5066 refactor: rename new option to debug.rawDecreasingByGoal
  src/Lean/Elab/PreDefinition/WF/Basic.lean
  tests/lean/run/4928.lean
Labels: toolchain-available, will-merge-soon

#5074 feat: import LeanSAT LRAT
  src/Lean/Elab/Tactic/BVDecide.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Actions.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Checker.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Actions.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Assignment.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/CNF.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Clause.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Convert.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Entails.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Formula.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Formula/Class.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Formula/Implementation.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Formula/Instance.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Formula/Lemmas.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Formula/RatAddResult.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Formula/RatAddSound.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/Formula/RupAddSound.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/LRATChecker.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/LRATCheckerSound.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Internal/PosFin.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Trim.lean
Labels: toolchain-available

#5055 feat: unify equational theorems between wf and structural recursion
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  tests/lean/run/986.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5041 feat: mutual recursion: allow common prefix up to alpha-equivalence
  src/Lean/Elab/PreDefinition/Structural/Main.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  tests/lean/run/recCommonPrefixAlpha.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5054 feat: explain `reduce` steps in `trace.Debug.Meta.Tactic.simp`
  src/Lean/Meta/Tactic/Simp/Main.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5092 feat: List.mergeSort
  src/Init/Data/Bool.lean
  src/Init/Data/List.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Data/List/Perm.lean
  src/Init/Data/List/Sort.lean
  src/Init/Data/List/Sort/Basic.lean
  src/Init/Data/List/Sort/Impl.lean
  src/Init/Data/List/Sort/Lemmas.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/List/TakeDrop.lean
  tests/bench/mergeSort/.gitignore
  tests/bench/mergeSort/Bench.lean
  tests/bench/mergeSort/README.md
  tests/bench/mergeSort/bench.py
  tests/bench/mergeSort/lakefile.lean
  tests/bench/mergeSort/lean-toolchain
  tests/lean/run/mergeSort.lean
  tests/lean/run/mergeSortCPDT.lean
Labels: breaks-mathlib, toolchain-available

#5099 chore: restart-on-label: Also filter by commit SHA
  .github/workflows/restart-on-label.yml
Labels: toolchain-available

#5100 feat: LeanSAT's LRAT parsers + SAT solver interface
  src/Init/Data/String/Basic.lean
  src/Lean/Data/Parsec/Basic.lean
  src/Lean/Data/Parsec/ByteArray.lean
  src/Lean/Data/Parsec/String.lean
  src/Lean/Elab/Tactic/BVDecide.lean
  src/Lean/Elab/Tactic/BVDecide/External.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Parser.lean
  tests/lean/run/lrat_roundtrip.lean
Labels: toolchain-available

#5107 chore: add mergeSort lemmas
  src/Init/Data/List/Sort/Basic.lean
  src/Init/Data/List/Sort/Lemmas.lean
Labels: toolchain-available

#5103 feat: more aggressive simp lemmas for List.subset
  src/Init/Data/List/Sublist.lean
Labels: builds-mathlib, toolchain-available

#5105 chore: remove @[simp] from mem_of_find?_eq_some
  src/Init/Data/List/Find.lean
Labels: builds-mathlib, toolchain-available

#5101 feat: lemmas about Option/if-then-else
  src/Init/Data/Option/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5104 feat: Nat.add_left_eq_self and relatives
  src/Init/Data/List/Sort/Impl.lean
  src/Init/Data/Nat/Lemmas.lean
  tests/lean/run/2669.lean
  tests/lean/run/4290.lean
  tests/lean/run/letDeclSimp.lean
  tests/lean/simp_trace.lean
  tests/lean/simp_trace.lean.expected.out
Labels: builds-mathlib, toolchain-available

#5102 feat: adjust List simp lemmas
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5106 feat: change statement of List.getLast?_cons
  src/Init/Data/List/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5112 feat: basic instances for ULift and PLift
  src/Init/Data.lean
  src/Init/Data/PLift.lean
  src/Init/Data/ULift.lean
Labels: toolchain-available

#5115 chore: move Lean.Data.Parsec to Std.Internal.Parsec
  src/Lean/Data.lean
  src/Lean/Data/Json/Parser.lean
  src/Lean/Data/Xml/Parser.lean
  src/Lean/Elab/Tactic/BVDecide/External.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Parser.lean
  src/Std.lean
  src/Std/Internal.lean
  src/Std/Internal/Parsec.lean
  src/Std/Internal/Parsec/Basic.lean
  src/Std/Internal/Parsec/ByteArray.lean
  src/Std/Internal/Parsec/String.lean
  tests/lean/1363.lean
  tests/lean/interactive/run.lean
Labels: toolchain-available

#5117 fix: count let-bound variables in `induction … with` correctly
  src/Lean/Elab/Tactic/Induction.lean
  tests/lean/run/indUsingLet.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5119 fix: `get_elem_tactic_trivial` to not loop in the presence of mvars
  src/Init/GetElem.lean
  tests/lean/run/issue5061.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5118 fix: hover text over `_` in `?_`
  src/Lean/Elab/Term.lean
  src/Lean/Parser/Term.lean
  stage0/src/stdlib_flags.h
  tests/lean/interactive/issue5021.lean
  tests/lean/interactive/issue5021.lean.expected.out
Labels: builds-mathlib, toolchain-available, release-ci

#5123 feat: range/iota lemmas
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Sublist.lean
Labels: toolchain-available

#5124 feat: lemmas about List.find?
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#5130 feat: lemmas about List.join
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5131 feat: more lemmas about List.append
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/Sublist.lean
Labels: builds-mathlib, toolchain-available

#5128 feat: Option lemmas
  src/Init/Data/Option/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5125 feat: support for secure temporary files
  src/Init/System/IO.lean
  src/runtime/io.cpp
  tests/lean/run/tempfile.lean
Labels: toolchain-available, release-ci

#5109 doc: `unfold` tactic docstring
  src/Init/Tactics.lean
Labels: builds-mathlib, toolchain-available

#5138 fix: improper handling of strict-implicit section variables
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/Command.lean
Labels: breaks-mathlib, toolchain-available, backport releases/v4.11.0

#5132 feat: lemmas about membership of sublists
  src/Init/Data/List/Erase.lean
  src/Init/Data/List/Sublist.lean
Labels: builds-mathlib, toolchain-available

#5127 feat: misc List lemma updates
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Zip.lean
  tests/lean/run/list_simp.lean
Labels: builds-mathlib, toolchain-available

#4325 feat: ship cadical
  CMakeLists.txt
  LICENSES
  flake.lock
  flake.nix
  nix/bootstrap.nix
  src/CMakeLists.txt
  src/cadical.mk
Labels: builds-mathlib, toolchain-available

#5142 fix: mixing variable binder updates and declarations
  src/Lean/Elab/BuiltinCommand.lean
  tests/lean/run/2143.lean
Labels: toolchain-available

#5006 doc: update user widget manual
  doc/examples/widgets.lean
  src/Lean/Widget/UserWidget.lean
Labels: toolchain-available

#5133 chore: running the simpNF linter over Lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Perm.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/SimpLemmas.lean
  src/Std/Data/DHashMap/Internal/List/Associative.lean
Labels: builds-mathlib, toolchain-available

#5146 feat: missing Nat.and_xor_distrib_(left|right)
  src/Init/Data/Bool.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: toolchain-available

#5148 feat: improve Nat simp lemma confluence
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Lemmas.lean
Labels: toolchain-available

#5153 feat: lemmas about List.attach/pmap
  src/Init/Data/List/Attach.lean
Labels: toolchain-available

#5151 feat: improving confluence of List simp lemmas
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/Sublist.lean
Labels: builds-mathlib, toolchain-available

#5129 feat: same equational lemmas for recursive and non-recursive functions
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Meta/Eqns.lean
  tests/lean/run/wfEqns5.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, release-ci
