Repository leanprover/lean4, pull requests merged in 2024-02, with the labels that each got.

#3226 feat: lake: improved platform information & control
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Config/LeanConfig.lean
  src/lake/Lake/Config/LeanLib.lean
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Load/Elab.lean
  src/lake/Lake/Util/Platform.lean
  src/lake/README.md
Labels: builds-mathlib, toolchain-available, will-merge-soon, full-ci

#2478 feat: use supplied structure fields left to right and eta reduce terms in structure instance elaboration
  RELEASES.md
  src/Lean/Elab/StructInst.lean
  tests/lean/run/463.lean
  tests/lean/run/structInstFast.lean
  tests/lean/run/structWithAlgTCSynth.lean
  tests/lean/structInstExtraEta.lean
  tests/lean/structInstExtraEta.lean.expected.out
  tests/lean/structInstSourcesLeftToRight.lean
  tests/lean/structInstSourcesLeftToRight.lean.expected.out
Labels: awaiting-review, Mathlib4 high prio, builds-mathlib, toolchain-available, full-ci

#2933 feat: `pp.numericTypes` option for printing number literals with type ascriptions
  RELEASES.md
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  tests/lean/ppNumericTypes.lean
  tests/lean/ppNumericTypes.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#3238 chore: CI: do not fail on broken links
  .github/workflows/nix-ci.yml
Labels: toolchain-available

#3236 doc: fix typos
  src/Init/Prelude.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Exception.lean
  src/Lean/Expr.lean
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/Basic.lean
  tests/lean/interactive/hover.lean.expected.out
Labels: awaiting-author, toolchain-available

#3243 chore: begin development cycle for v4.7.0
  RELEASES.md
  src/CMakeLists.txt
Labels: toolchain-available

#3252 refactor: add helper function `evalPropStep`
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Fin.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Nat.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/UInt.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Util.lean
Labels: builds-mathlib, toolchain-available

#3255 feat: improve termination_by error messages
  src/Lean/Elab/LetRec.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/PreDefinition/WF/Rel.lean
  src/Lean/Elab/PreDefinition/WF/TerminationHint.lean
  tests/lean/decreasing_by.lean
  tests/lean/interactive/hover.lean
  tests/lean/termination_by_vars.lean
  tests/lean/termination_by_vars.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3249 doc: add links to folder references
  doc/dev/ffi.md
  doc/dev/testing.md
Labels: builds-mathlib, toolchain-available

#3259 fix: don't drop doc-comments on simprocs
  src/Init/Simproc.lean
  tests/lean/run/simproc1.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#3256 fix: let induction handle parameters
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Meta/Tactic/ElimInfo.lean
  tests/lean/run/issue3212.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3262 feat: InfoTree helper function used in code actions
  src/Lean/Server/InfoUtils.lean
Labels: awaiting-review, builds-mathlib, toolchain-available, will-merge-soon

#3269 fix: we should not crash when `simp` loops
  src/Lean/Meta/Tactic/Simp/Main.lean
Labels: builds-mathlib, toolchain-available

#3263 feat: upstream helper functions for Name
  src/Lean/Data/Name.lean
Labels: awaiting-review, breaks-mathlib, toolchain-available, will-merge-soon, full-ci

#3261 feat: upstream TSyntax helper functions
  src/Init/Meta.lean
  src/Lean/Syntax.lean
Labels: awaiting-review, breaks-mathlib, toolchain-available, will-merge-soon, full-ci

#3264 feat: additional options for Format.pretty
  src/Init/Data/Format/Basic.lean
  src/library/trace.cpp
Labels: awaiting-review, builds-mathlib, toolchain-available, will-merge-soon

#3265 feat: upstreaming the json% term elaborator
  src/Lean/Data/Json.lean
  src/Lean/Data/Json/Elab.lean
  tests/lean/run/toFromJson.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon, full-ci

#3275 chore: upstream Std.Lean.LocalContext
  src/Lean/LocalContext.lean
Labels: awaiting-review, toolchain-available, will-merge-soon

#3283 chore: upstream Divides class and syntax
  src/Init/Notation.lean
  src/Init/Prelude.lean
Labels: toolchain-available

#3278 chore: upstream Std.Lean.Tactic
  src/Lean/Elab/Tactic/Basic.lean
Labels: toolchain-available

#3282 chore: upstream Std.Data.Array.Init.Basic
  src/Init/Data/Array/Basic.lean
Labels: toolchain-available

#3285 feat: nary `nomatch`
  src/Lean/Elab/Match.lean
  src/Lean/Parser/Term.lean
  stage0/stdlib/Init.c
  stage0/stdlib/Init/Data/Array/Basic.c
  stage0/stdlib/Init/Notation.c
  stage0/stdlib/Init/Tactics.c
  stage0/stdlib/Init/TacticsExtra.c
  stage0/stdlib/Lean/Attributes.c
  stage0/stdlib/Lean/Compiler/IR/Basic.c
  stage0/stdlib/Lean/Data/Json.c
  stage0/stdlib/Lean/Data/Json/Elab.c
  stage0/stdlib/Lean/Elab/ComputedFields.c
  stage0/stdlib/Lean/Elab/Deriving/FromToJson.c
  stage0/stdlib/Lean/Elab/InfoTree/Main.c
  stage0/stdlib/Lean/Elab/Match.c
  stage0/stdlib/Lean/Elab/Tactic.c
  stage0/stdlib/Lean/Elab/Tactic/Basic.c
  stage0/stdlib/Lean/Elab/Tactic/ByCases.c
  stage0/stdlib/Lean/LocalContext.c
  stage0/stdlib/Lean/Parser/Term.c
  stage0/stdlib/Lean/Parser/Types.c
  stage0/stdlib/Lean/PrettyPrinter/Delaborator/Builtins.c
  stage0/stdlib/Lean/Widget/InteractiveGoal.c
  stage0/stdlib/Lean/Widget/UserWidget.c
  tests/lean/run/nary_nomatch.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon, full-ci

#3281 feat: allow overriding getSimpTheorems in mkSimpContext
  src/Lean/Elab/Tactic/Simp.lean
Labels: toolchain-available

#3284 chore: upstream MetavarContext helpers
  src/Lean/MetavarContext.lean
Labels: toolchain-available, will-merge-soon

#3280 chore: upstream Std.Tactic.CoeExt to Lean.Elab.CoeExt
  src/Init/Coe.lean
  src/Init/Notation.lean
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Meta.lean
  src/Lean/Meta/CoeAttr.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/1021.lean.expected.out
  tests/lean/coeAttr1.lean
  tests/lean/coeAttr1.lean.expected.out
Labels: breaks-mathlib, toolchain-available, full-ci

#3273 refactor: make `Promise` implementation opaque
  src/Init/System/Promise.lean
  src/runtime/object.cpp
Labels: toolchain-available

#3260 feat: upstream some Syntax/Position helper functions used in code actions in Std
  src/Init/Data/String/Basic.lean
  src/Lean/Data/Position.lean
  src/Lean/Syntax.lean
Labels: awaiting-review, breaks-mathlib, toolchain-available, full-ci

#3288 feat: add `[builtin_widget_module]`
  src/Lean/Widget/UserWidget.lean
Labels: toolchain-available

#3289 feat: add `[builtin_code_action_provider]`
  src/Lean/Server/CodeActions.lean
Labels: toolchain-available

#3295 fix: extended `coe` notation and delaborator
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/coe.lean
  tests/lean/coe.lean.expected.out
Labels: toolchain-available

#3296 fix: `nomatch` regression
  src/Lean/Elab/Match.lean
  tests/lean/run/nomatch_regression.lean
Labels: toolchain-available

#3294 chore: add `nomatch` tactic
  src/Init/Tactics.lean
  tests/lean/run/nomatch_tac.lean
Labels: toolchain-available

#3299 chore: `rwa` tactic macro
  src/Init/Core.lean
  src/Init/Tactics.lean
  tests/lean/run/1842.lean
  tests/lean/run/deq.lean
  tests/lean/run/rw_inst_mvars.lean
  tests/lean/runTacticMustCatchExceptions.lean.expected.out
Labels: toolchain-available

#3292 chore: upstream rcases
  src/Init.lean
  src/Init/RCases.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/RCases.lean
  src/Lean/Meta/Tactic/FVarSubst.lean
  tests/lean/run/rcases1.lean
Labels: toolchain-available

#3301 doc: implicit type arguments are indexed in the discrtree
  src/Lean/Meta/DiscrTree.lean
Labels: toolchain-available

#3297 feat: upstream guard_expr
  src/Init.lean
  src/Init/Guard.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/Guard.lean
  tests/lean/run/guardexpr.lean
Labels: toolchain-available

#3309 doc: fix typos around inductiveCheckResultingUniverse
  src/Lean/Elab/Inductive.lean
  tests/lean/univInference.lean.expected.out
Labels: toolchain-available

#3311 fix: `add_decl_doc` should check that declarations are local
  src/Lean/Elab/BuiltinCommand.lean
  tests/lean/docStr.lean
  tests/lean/docStr.lean.expected.out
Labels: toolchain-available

#3307 chore: upstream left/right tactics
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Meta/Tactic/Apply.lean
Labels: toolchain-available

#3303 chore: DiscrTree helper functions
  src/Lean/Meta/DiscrTree.lean
Labels: toolchain-available

#3304 chore: upstream liftCommandElabM
  src/Lean/Elab/Command.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#3308 chore: upstream change tactic
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/Change.lean
  src/Lean/Meta/Tactic/Replace.lean
  tests/lean/run/change_tac.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#3225 fix: type mismatches in the LLVM backend
  src/Lean/Compiler/IR/EmitLLVM.lean
  src/Lean/Compiler/IR/LLVMBindings.lean
  src/library/compiler/llvm.cpp
Labels: toolchain-available

#3305 chore: upstream repeat/split_ands/subst_eqs
  src/Init/Tactics.lean
  src/Init/TacticsExtra.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Repeat.lean
  src/Lean/Meta/Tactic.lean
  src/Lean/Meta/Tactic/Repeat.lean
  tests/lean/run/and_intros.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#3319 doc: Add a docstring to `Simp.Result` and its fields
  src/Lean/Meta/Tactic/Simp/Types.lean
Labels: toolchain-available

#3244 perf: LLVM backend, put all allocas in the first BB to enable mem2reg
  src/Lean/Compiler/IR/EmitLLVM.lean
  src/Lean/Compiler/IR/LLVMBindings.lean
  src/library/compiler/llvm.cpp
Labels: toolchain-available

#3318 fix: trailing whitespace in `location` formatter
  src/Init/Tactics.lean
  tests/lean/formatTerm.lean
  tests/lean/formatTerm.lean.expected.out
  tests/lean/simp_trace.lean.expected.out
Labels: toolchain-available

#3323 fix: `#eval` command was leaking auxiliary declarations into the environment
  src/Lean/Elab/BuiltinCommand.lean
  tests/lean/evalLeak.lean
  tests/lean/evalLeak.lean.expected.out
Labels: toolchain-available

#3266 feat: upstream 'Try this:' widgets
  src/Lean/Meta/Tactic.lean
  src/Lean/Meta/Tactic/TryThis.lean
  tests/lean/interactive/completionOption.lean.expected.out
Labels: breaks-mathlib, toolchain-available, full-ci

#3321 chore: upstream replace tactic
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  tests/lean/run/replace_tac.lean
Labels: toolchain-available

#3324 chore: upstream `run_cmd` and fixes bugs
  src/Init/Notation.lean
  src/Init/Tactics.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Elab/Eval.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  tests/lean/1021.lean.expected.out
  tests/lean/run/run_cmd.lean
Labels: toolchain-available

#3312 chore: upstream Std.Logic
  doc/examples/bintree.lean
  src/Init.lean
  src/Init/ByCases.lean
  src/Init/Classical.lean
  src/Init/Core.lean
  src/Init/Data/Array/DecidableEq.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Linear.lean
  src/Init/PropLemmas.lean
  src/Init/SimpLemmas.lean
  tests/lean/1079.lean.expected.out
  tests/lean/276.lean
  tests/lean/276.lean.expected.out
  tests/lean/run/1549.lean
  tests/lean/run/1842.lean
  tests/lean/run/2552.lean
  tests/lean/run/968.lean
  tests/lean/run/ac_rfl.lean
  tests/lean/run/constProp.lean
  tests/lean/run/eq_some_iff_get_eq_issue.lean
  tests/lean/run/recInfo1.lean
  tests/lean/run/simp4.lean
  tests/lean/run/simp6.lean
  tests/lean/run/wfOverapplicationIssue.lean
  tests/lean/simp_trace.lean.expected.out
Labels: toolchain-available, full-ci

#3320 chore: upstream Std.Util.ExtendedBinders
  src/Init.lean
  src/Init/BinderPredicates.lean
  src/Lean/Elab.lean
  src/Lean/Elab/BinderPredicates.lean
  src/Lean/Parser/Syntax.lean
  stage0/stdlib/Init.c
  stage0/stdlib/Init/BinderPredicates.c
  stage0/stdlib/Init/Core.c
  stage0/stdlib/Init/Guard.c
  stage0/stdlib/Init/Meta.c
  stage0/stdlib/Init/RCases.c
  stage0/stdlib/Init/System/IO.c
  stage0/stdlib/Init/Tactics.c
  stage0/stdlib/Lean/Compiler/CSimpAttr.c
  stage0/stdlib/Lean/Compiler/LCNF/PullLetDecls.c
  stage0/stdlib/Lean/Compiler/LCNF/Specialize.c
  stage0/stdlib/Lean/Data/Lsp/Capabilities.c
  stage0/stdlib/Lean/Data/Lsp/LanguageFeatures.c
  stage0/stdlib/Lean/Elab.c
  stage0/stdlib/Lean/Elab/App.c
  stage0/stdlib/Lean/Elab/BinderPredicates.c
  stage0/stdlib/Lean/Elab/Binders.c
  stage0/stdlib/Lean/Elab/BuiltinCommand.c
  stage0/stdlib/Lean/Elab/BuiltinNotation.c
  stage0/stdlib/Lean/Elab/Command.c
  stage0/stdlib/Lean/Elab/Inductive.c
  stage0/stdlib/Lean/Elab/Match.c
  stage0/stdlib/Lean/Elab/PreDefinition/WF/GuessLex.c
  stage0/stdlib/Lean/Elab/Print.c
  stage0/stdlib/Lean/Elab/Structure.c
  stage0/stdlib/Lean/Elab/Tactic.c
  stage0/stdlib/Lean/Elab/Tactic/BuiltinTactic.c
  stage0/stdlib/Lean/Elab/Tactic/Change.c
  stage0/stdlib/Lean/Elab/Tactic/Guard.c
  stage0/stdlib/Lean/Elab/Tactic/RCases.c
  stage0/stdlib/Lean/Environment.c
  stage0/stdlib/Lean/Linter/MissingDocs.c
  stage0/stdlib/Lean/LocalContext.c
  stage0/stdlib/Lean/Meta/CoeAttr.c
  stage0/stdlib/Lean/Meta/DiscrTree.c
  stage0/stdlib/Lean/Meta/Tactic/Apply.c
  stage0/stdlib/Lean/Meta/Tactic/FVarSubst.c
  stage0/stdlib/Lean/Meta/Tactic/LinearArith/Solver.c
  stage0/stdlib/Lean/Meta/Tactic/Replace.c
  stage0/stdlib/Lean/Meta/WHNF.c
  stage0/stdlib/Lean/Parser/Syntax.c
  stage0/stdlib/Lean/PrettyPrinter/Delaborator/Builtins.c
  stage0/stdlib/Lean/Server/FileWorker.c
  stage0/stdlib/Lean/Server/FileWorker/RequestHandling.c
  stage0/stdlib/Lean/Server/ImportCompletion.c
  stage0/stdlib/Lean/Server/Watchdog.c
  tests/lean/binder_predicates.lean
  tests/lean/binder_predicates.lean.expected.out
  tests/lean/interactive/keywordCompletion.lean.expected.out
Labels: breaks-mathlib, toolchain-available, full-ci

#3326 feat: delaboration collapses parent projections
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/delabProjectionApp.lean
  tests/lean/delabProjectionApp.lean.expected.out
  tests/lean/diamond2.lean.expected.out
  tests/lean/diamond3.lean.expected.out
  tests/lean/structInstSourcesLeftToRight.lean.expected.out
  tests/lean/toFieldNameIssue.lean.expected.out
Labels: awaiting-review, toolchain-available

#3334 fix: `run_meta` macro
  src/Init/Notation.lean
  src/Lean/Elab/BuiltinCommand.lean
  tests/lean/run/run_meta1.lean
  tests/lean/run_meta1.lean
  tests/lean/run_meta1.lean.expected.out
Labels: toolchain-available

#3331 chore: upstream of Std.Data.Nat.Init
  src/Init/Data/Nat.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Div.lean
  src/Init/Data/Nat/Dvd.lean
  src/Init/Data/Nat/Gcd.lean
  src/Init/Data/Nat/Linear.lean
  src/Init/Data/Nat/MinMax.lean
  src/Init/Data/Nat/Power2.lean
  src/Init/Prelude.lean
  src/Init/PropLemmas.lean
  tests/lean/run/1380.lean
  tests/lean/run/simproc_panic.lean
Labels: WIP, toolchain-available, full-ci

#3335 chore: upstream Std.Data.List.Init.Basic
  src/Init/Data/List/Basic.lean
Labels: toolchain-available

#3337 chore: upstream Std.Data.Fin.Init.Lemmas
  src/Init/Data/Fin/Basic.lean
  tests/lean/run/1302.lean
Labels: toolchain-available

#3340 chore: upstream Std.Classes.LawfulMonad (except SatisfiesM)
  src/Init/Control/Lawful.lean
Labels: toolchain-available

#3339 chore: upstream set notation
  src/Init/BinderPredicates.lean
  src/Init/Core.lean
  tests/lean/run/macro.lean
Labels: toolchain-available

#3338 chore: upstream Std.Data.Prod.Lex
  src/Init/WF.lean
Labels: toolchain-available

#3341 chore: upstream Std.Data.List.Init.Lemmas
  src/Init/Data/List.lean
  src/Init/Data/List/Lemmas.lean
  tests/lean/allFieldForConstants.lean
  tests/lean/run/mutualDefThms.lean
  tests/lean/run/structuralIssue2.lean
Labels: toolchain-available

#3343 chore: upstream Std.Data.Array.Init.Lemmas
  src/Init/Data/Array.lean
  src/Init/Data/Array/Lemmas.lean
Labels: toolchain-available

#3344 chore: a missing List lemma in Init
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#3346 chore: avoid libleanshared symbol limit
  src/Lean/Compiler/IR/EmitC.lean
Labels: toolchain-available

#3327 fix: make `withOverApp` annotate the expression position and register `TermInfo`
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
Labels: awaiting-review, toolchain-available

#3347 chore: upstream NatCast and IntCast
  src/Init/Data.lean
  src/Init/Data/Cast.lean
  src/Init/Data/Int/Basic.lean
  src/Lean/Server/Utils.lean
  tests/lean/1298.lean
  tests/lean/binopInfoTree.lean.expected.out
  tests/lean/binopIssues.lean.expected.out
  tests/lean/binrel_binop.lean.expected.out
  tests/lean/hpow.lean.expected.out
  tests/lean/run/constProp.lean
  tests/lean/run/mathlibetaissue.lean
  tests/lean/run/rational.lean
Labels: toolchain-available

#3357 chore: upstream HashSet.merge
  src/Lean/Data/HashSet.lean
Labels: toolchain-available

#3359 chore: upstream Expr.getAppFnArgs
  src/Lean/Expr.lean
Labels: toolchain-available, will-merge-soon

#3356 chore: upstream Option material from Std
  src/Init/Data/Option.lean
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Instances.lean
  src/Init/Data/Option/Lemmas.lean
  tests/lean/run/eq_some_iff_get_eq_issue.lean
  tests/lean/run/inductionLetIssue.lean
  tests/lean/run/lex.lean
Labels: toolchain-available

#3362 chore: upstream MVarId.applyConst
  src/Lean/Meta/Tactic/Apply.lean
Labels: toolchain-available

#3361 chore: upstream exfalso
  src/Init/Tactics.lean
Labels: toolchain-available

#3365 chore: upstream Std's material on Ord and Ordering
  src/Init/Data/Ord.lean
Labels: toolchain-available

#3360 chore: upstream Expr.nat? and int? for recognising 'normal form' numerals
  src/Lean/Expr.lean
Labels: toolchain-available, will-merge-soon

#3364 chore: upstream Std.Data.Int.Init modules
  src/Init/Data/Int.lean
  src/Init/Data/Int/Basic.lean
  src/Init/Data/Int/Bitwise.lean
  src/Init/Data/Int/DivMod.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Int/Gcd.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/Random.lean
  src/Lean/Data/Json/Basic.lean
  src/Lean/Data/Rat.lean
  src/Lean/ToExpr.lean
  tests/lean/binopIssues.lean
  tests/lean/matchOfNatIssue.lean.expected.out
  tests/lean/run/inaccessibleAnnotDefEqIssue.lean
  tests/lean/run/mathlibetaissue.lean
Labels: toolchain-available

#3366 chore: upstream basic statements about inequalities
  src/Init/Core.lean
  tests/lean/letFun.lean.expected.out
  tests/lean/simp_trace.lean.expected.out
  tests/lean/simp_trace_backtrack.lean
  tests/lean/simp_trace_backtrack.lean.expected.out
Labels: toolchain-available

#3368 refactor: let MatcherApp.addArg? check if argument was refined
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/PreDefinition/WF/Fix.lean
  src/Lean/Meta/CasesOn.lean
  src/Lean/Meta/Match/Match.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3372 fix: liasolver benchmark bug introduced by #3364
  tests/bench/liasolver.lean
Labels: toolchain-available

#3248 fix: cloud release trace & `lake build :release` errors
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Build/Package.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, full-ci

#3254 fix: lake: open config trace as read-only first & avoid deadlock
  src/lake/Lake/Load/Elab.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, full-ci

#3314 fix: `simp` fails to discharge `autoParam` premises even when it can reduce them to `True`
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  tests/lean/run/3257.lean
Labels: toolchain-available

#3315 fix: `simp` gets stuck on `autoParam`
  src/Lean/Expr.lean
  src/Lean/Meta/MatchUtil.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Core.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/SimpAll.lean
  tests/lean/run/2862.lean
Labels: toolchain-available

#3317 fix: `simp` fails when custom discharger makes no progress
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Elab/Tactic/Simp.lean
  tests/lean/2634.lean
  tests/lean/2634.lean.expected.out
Labels: toolchain-available

#3316 fix: an equation lemma with `autoParam` arguments fails to rewrite
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Eqns.lean
  tests/lean/run/2243.lean
  tests/lean/run/2939.lean
Labels: toolchain-available

#3370 feat: infoview.maxTraceChildren
  src/Lean/Message.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Util/Trace.lean
  src/Lean/Widget/InteractiveDiagnostic.lean
Labels: builds-mathlib, toolchain-available

#3379 chore: `pp.proofs.withType` is now false by default
  RELEASES.md
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  tests/lean/1074a.lean.expected.out
  tests/lean/1081.lean.expected.out
  tests/lean/1856.lean.expected.out
  tests/lean/986.lean.expected.out
  tests/lean/congrThm.lean.expected.out
  tests/lean/congrThmIssue.lean.expected.out
  tests/lean/diamond9.lean.expected.out
  tests/lean/heapSort.lean.expected.out
  tests/lean/letFun.lean.expected.out
  tests/lean/match1.lean.expected.out
  tests/lean/ppProofs.lean.expected.out
  tests/lean/run/PPTopDownAnalyze.lean
  tests/lean/wfrecUnusedLet.lean.expected.out
Labels: breaks-mathlib, toolchain-available, full-ci

#3369 refactor: drop CasesOnApp, use MatcherApp
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/PreDefinition/WF/Fix.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Meta.lean
  src/Lean/Meta/CasesOn.lean
  src/Lean/Meta/Match/MatcherInfo.lean
Labels: builds-mathlib, toolchain-available

#3246 fix: instantiate the types of inductives with the right parameters
  src/Lean/Elab/Inductive.lean
  tests/lean/run/3242.lean
Labels: builds-mathlib, toolchain-available

#3381 feat: delaborator for `Char` literals
  src/Init/Meta.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/ToExpr.lean
Labels: toolchain-available

#3382 feat: simprocs for `Char`
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Char.lean
  tests/lean/simprocChar.lean
  tests/lean/simprocChar.lean.expected.out
Labels: toolchain-available

#3383 fix: exposeRelevantUniverses was inserting the whole expression into itself
  src/Lean/Meta/Basic.lean
  tests/lean/343.lean.expected.out
Labels: breaks-mathlib, toolchain-available, full-ci

#3380 feat: make loose fvars pretty print as `_fvar.123` instead of `_uniq.123`
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/474.lean.expected.out
Labels: builds-mathlib, toolchain-available

#3378 chore: add @[simp] to Nat.sub_add_cancel
  src/Init/Data/Nat/Basic.lean
Labels: builds-mathlib, toolchain-available

#3240 feat: conv => fun
  src/Init/Conv.lean
  src/Lean/Elab/Tactic/Conv/Congr.lean
  tests/lean/conv1.lean
  tests/lean/conv1.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#3329 fix: `savePanelWidgetInfo` on `@[builtin_widget_module]`
  src/Lean/Widget/UserWidget.lean
Labels: toolchain-available

#3367 chore: upstream omega
  src/Init.lean
  src/Init/Data/List/Basic.lean
  src/Init/Meta.lean
  src/Init/Omega.lean
  src/Init/Omega/Coeffs.lean
  src/Init/Omega/Constraint.lean
  src/Init/Omega/Int.lean
  src/Init/Omega/IntList.lean
  src/Init/Omega/LinearCombo.lean
  src/Init/Omega/Logic.lean
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/Omega.lean
  src/Lean/Elab/Tactic/Omega/Core.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/Elab/Tactic/Omega/MinNatAbs.lean
  src/Lean/Elab/Tactic/Omega/OmegaM.lean
  src/Lean/LocalContext.lean
  tests/bench/reduceMatch.lean
  tests/lean/run/mergeSortCPDT.lean
  tests/lean/run/omega.lean
Labels: toolchain-available

#3390 chore: upstream Std.Data.Fin.Basic
  src/Init/Data/Fin.lean
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/Fin/Fold.lean
Labels: toolchain-available

#3389 chore: upstream Std.Data.Bool
  src/Init/Data.lean
  src/Init/Data/Bool.lean
  tests/lean/run/arthur1.lean
  tests/lean/run/arthur2.lean
Labels: toolchain-available

#3391 chore: upstream (most of) Std.Data.Nat.Lemmas
  src/Init/Data/Nat.lean
  src/Init/Data/Nat/Lemmas.lean
  tests/lean/matchMultAlt.lean
  tests/lean/run/1380.lean
  tests/lean/run/ac_rfl.lean
  tests/lean/run/concatElim.lean
  tests/lean/run/eqTheoremForVec.lean
  tests/lean/run/eqnsAtSimp.lean
  tests/lean/run/simproc_panic.lean
  tests/lean/run/splitIssue.lean
  tests/lean/run/wfEqns1.lean
  tests/lean/simp_trace.lean
  tests/lean/simp_trace.lean.expected.out
Labels: toolchain-available

#3392 chore: upstream Std.Data.Fin.Iterate
  src/Init/Data/Fin.lean
  src/Init/Data/Fin/Iterate.lean
Labels: toolchain-available

#3394 refactor: use isAppOfArity
  src/Lean/Meta/Tactic/Split.lean
Labels: toolchain-available

#3371 fix: broken trace tree on elab runtime exception
  RELEASES.md
  src/Lean/CoreM.lean
  src/Lean/Elab/Command.lean
  src/Lean/Util/Trace.lean
  tests/lean/exceptionalTrace.lean
  tests/lean/exceptionalTrace.lean.expected.out
Labels: breaks-mathlib, toolchain-available, full-ci

#3396 chore: upstream simpa
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/Simpa.lean
Labels: toolchain-available

#3376 feat: introduce native functions for Int.ediv / Int.emod
  src/Init/Data/Int/DivMod.lean
  src/include/lean/lean.h
  src/runtime/mpz.cpp
  src/runtime/mpz.h
  src/runtime/object.cpp
  tests/lean/int_div_mod.lean
  tests/lean/int_div_mod.lean.expected.out
Labels: toolchain-available, full-ci

#3402 chore: Nix CI: stop pushing to cachix
  .github/workflows/nix-ci.yml
  .github/workflows/update-stage0.yml
Labels: toolchain-available

#3407 feat: simprocs for `BitVec`
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  tests/lean/run/bitvec_simproc.lean
Labels: toolchain-available

#3409 feat: add simproc for `BitVec.signExtend`
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  tests/lean/run/bitvec_simproc.lean
Labels: toolchain-available

#3348 chore: set literal notation
  src/Init/NotationExtra.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Server/Rpc/Deriving.lean
  tests/lean/interactive/fieldCompletion.lean.expected.out
  tests/lean/run/setStructInstNotation.lean
  tests/lean/semicolonOrLinebreak.lean.expected.out
  tests/lean/setLit.lean
  tests/lean/setLit.lean.expected.out
Labels: toolchain-available

#3411 chore: add missing copyright headers
  script/apply.lean
  src/Init/Data/BitVec.lean
  src/Init/Data/Nat/Bitwise.lean
  src/Init/Data/Nat/Dvd.lean
  src/Init/Data/Nat/MinMax.lean
  src/Init/Omega.lean
  src/Lean/Data/Json/Elab.lean
  src/Lean/Data/Xml.lean
  src/Lean/Data/Xml/Basic.lean
  src/Lean/Linter.lean
  src/Lean/Linter/Basic.lean
  src/Lean/Linter/Builtin.lean
  src/Lean/Linter/MissingDocs.lean
  src/Lean/Linter/UnusedVariables.lean
  src/Lean/Linter/Util.lean
  src/Lean/Util/TestExtern.lean
  src/Lean/Widget/Basic.lean
  src/Leanc.lean
  src/lake/Lake/Config/LeanConfig.lean
  src/lake/lakefile.lean
Labels: toolchain-available

#3412 chore: CI checks for copyright headers
  .github/workflows/copyright-header.yml
Labels: toolchain-available

#3415 chore: typo
  .github/workflows/copyright-header.yml
Labels: toolchain-available

#3416 doc: prelude convention in Lean
  doc/dev/index.md
Labels: toolchain-available

#3417 chore: pr-release to suggest a git rebase command
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3300 chore: add documentation for the `String.iterator` API
  src/Init/Data/String/Basic.lean
  src/Init/Prelude.lean
Labels: toolchain-available

#3420 doc: fix confusing language in Expr.isProp
  src/Lean/Expr.lean
Labels: toolchain-available

#3418 chore: speedcenter: count max symbols in shared libraries
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#3424 chore: upstream List.get?_append
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#3408 chore: upstream solve_by_elim
  src/Init/Data.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/String/Extra.lean
  src/Init/Data/Sum.lean
  src/Init/Meta.lean
  src/Init/System/Uri.lean
  src/Init/Tactics.lean
  src/Lean.lean
  src/Lean/Data/RBMap.lean
  src/Lean/DocString.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/SolveByElim.lean
  src/Lean/Elab/Tactic/Symm.lean
  src/Lean/LabelAttribute.lean
  src/Lean/Meta.lean
  src/Lean/Meta/CollectMVars.lean
  src/Lean/Meta/Iterator.lean
  src/Lean/Meta/Tactic.lean
  src/Lean/Meta/Tactic/Assert.lean
  src/Lean/Meta/Tactic/Backtrack.lean
  src/Lean/Meta/Tactic/IndependentOf.lean
  src/Lean/Meta/Tactic/SolveByElim.lean
  src/Lean/Meta/Tactic/Symm.lean
  src/Lean/Meta/Tactic/Util.lean
  src/Lean/Util/Trace.lean
  tests/lean/interactive/1265.lean.expected.out
Labels: toolchain-available, full-ci

#3425 fix: bug in omega's elimination selection
  src/Lean/Elab/Tactic/Omega/Core.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  tests/lean/run/omega.lean
Labels: toolchain-available

#3426 chore: simplify decide (b = true) and variants
  src/Init/Data/Bool.lean
Labels: toolchain-available

#3428 chore: remove mkAppN macro in omega
  src/Lean/Elab/Tactic/Omega/Frontend.lean
Labels: toolchain-available

#3429 fix: address symm and label bugs from #3408
  src/Init/Meta.lean
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Symm.lean
  src/Lean/LabelAttribute.lean
Labels: toolchain-available

#3433 feat: omega handles shift operators, and normalises ground term exponentials
  src/Init/Omega/Int.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/Elab/Tactic/Omega/OmegaM.lean
  tests/lean/run/omega.lean
Labels: toolchain-available

#3434 chore: add @[simp] to BitVec.toNat_mul
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#3437 fix: match pattern missing test
  src/Lean/Elab/PatternVar.lean
  tests/lean/binop_at_pattern_issue.lean
  tests/lean/binop_at_pattern_issue.lean.expected.out
Labels: toolchain-available

#3427 feat: support for Fin in omega
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Omega/Int.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  tests/lean/run/omega.lean
Labels: toolchain-available

#3438 chore: explicit `DecidableEq` instance for `BitVec`
  src/Init/Data/BitVec/Basic.lean
Labels: toolchain-available

#3413 feat: custom error recovery in parser
  src/Lean/Parser.lean
  src/Lean/Parser/Basic.lean
  src/Lean/Parser/Command.lean
  src/Lean/Parser/Extension.lean
  src/Lean/Parser/Module.lean
  src/Lean/Parser/Types.lean
  src/Lean/PrettyPrinter/Formatter.lean
  src/Lean/PrettyPrinter/Parenthesizer.lean
  stage0/src/stdlib_flags.h
  tests/lean/1971.lean.expected.out
  tests/lean/parserRecovery.lean
  tests/lean/parserRecovery.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#3440 feat: `Int.toNat` simproc
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean
  tests/lean/run/simproc2.lean
Labels: toolchain-available

#3430 feat: BitVec.ofNatLt and updates to use it
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  tests/lean/interactive/inWordCompletion.lean
  tests/lean/interactive/inWordCompletion.lean.expected.out
Labels: toolchain-available

#3443 fix: support for `Fin` and `BitVec` literal normalization
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Fin.lean
  tests/lean/run/bitvec_fin_literal_norm.lean
Labels: toolchain-available

#3444 fix: structural equation proof generator
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  tests/lean/run/simp_eqn_bug.lean
Labels: toolchain-available

#3441 fix: allow users to disable builtin simprocs in simp args
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/ResolveName.lean
  tests/lean/run/simproc_disable_issue.lean
Labels: toolchain-available

#3446 doc: correct typo "can calls"
  doc/monads/except.lean
Labels: awaiting-review, toolchain-available

#3436 feat: setup simp lemmas: 'msb -> getLsb -> decide ...'
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-review, toolchain-available

#3448 chore: address copyright inconsistencies
  src/Init/ByCases.lean
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/Fin/Iterate.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/PropLemmas.lean
  src/Lean/Meta/CompletionName.lean
  src/Lean/Meta/Iterator.lean
  src/Lean/Util/TestExtern.lean
Labels: toolchain-available

#3445 feat: show basic properties of BitVec multiplication
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Fin/Lemmas.lean
Labels: toolchain-available, will-merge-soon

#3453 chore: namespacing in solve_by_elim
  src/Lean/Elab/Tactic/SolveByElim.lean
Labels: toolchain-available

#3454 chore: more List lemmas for auto
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#3464 refactor: reduced unsed imports
  src/Init/Conv.lean
  src/Init/Data/String/Extra.lean
Labels: toolchain-available, will-merge-soon, full-ci

#3459 fix: `zetaDelta := false` regression
  src/Lean/Elab/StructInst.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/WHNF.lean
  tests/lean/run/zetaDeltaIssue.lean
  tests/lean/structInstExtraEta.lean.expected.out
Labels: toolchain-available

#3421 fix: split `libInit_shared` out of `libleanshared`
  .github/workflows/ci.yml
  nix/bootstrap.nix
  nix/buildLeanPackage.nix
  src/CMakeLists.txt
  src/lake/examples/reverse-ffi/Makefile
  src/runtime/apply.h
  src/runtime/compact.h
  src/runtime/debug.h
  src/runtime/exception.h
  src/runtime/init_module.cpp
  src/runtime/init_module.h
  src/runtime/interrupt.h
  src/runtime/io.h
  src/runtime/load_dynlib.h
  src/runtime/memory.h
  src/runtime/mpz.h
  src/runtime/object.h
  src/runtime/object_ref.h
  src/runtime/stackinfo.cpp
  src/runtime/stackinfo.h
  src/runtime/thread.h
  src/runtime/utf8.h
  src/stdlib.make.in
  tests/compiler/foreign/Makefile
Labels: breaks-mathlib, toolchain-available, full-ci

#3461 refactor: make `BitVec.carry` take bitvector arguments
  src/Init/Data/BitVec/Bitblast.lean
Labels: toolchain-available

#3466 chore: remove @[simp] from some new BitVec lemmas
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#3468 chore: cleanup in BitVec/Bitblast.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#3457 feat: add `BitVec.getLsb_concat`
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Bool.lean
Labels: awaiting-review, toolchain-available

#3450 feat: omega uses b^(e+1) = b^e*b when b constant
  src/Init/Data/Int/Lemmas.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  tests/lean/run/omega.lean
Labels: awaiting-review, toolchain-available

#3469 chore: rename Bool.toNat_le_one
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/Bool.lean
Labels: toolchain-available

#3471 feat: add `BitVec.toNat_concat`
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#3472 feat: replace ToExpr Int
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/ToExpr.lean
  tests/lean/run/omega.lean
Labels: toolchain-available
