Repository leanprover/lean4, pull requests merged in 2024-09, with the labels that each got.

#5225 perf: cache visited exprs at `CheckAssignmentQuick`
  src/Lean/Meta/ExprDefEq.lean
Labels: toolchain-available

#5226 perf: maximize term sharing at `instantiateMVarDeclMVars`
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/MetavarContext.lean
  tests/lean/run/linearCategory_perf_issue.lean
Labels: toolchain-available

#5221 chore: release notes for 4.11.0
  RELEASES.md
  releases_drafts/new-variable.md
Labels: toolchain-available

#5229 chore: remove unused lemmas from a non-terminal simp
  src/Lean/Data/HashMap.lean
  src/Lean/Data/HashSet.lean
Labels: toolchain-available

#5218 feat: `pp.exprSizes` debugging option
  src/Lean/Expr.lean
  src/Lean/PrettyPrinter.lean
  src/kernel/for_each_fn.cpp
Labels: toolchain-available

#5230 doc: correct docstrings for integer division and modulus
  src/Init/Data/Int/DivMod.lean
Labels: documentation, toolchain-available, will-merge-soon

#4770 feat: lake: Reservoir-related configuration for packages
  debug.log
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Init.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Translate/Lean.lean
  src/lake/Lake/CLI/Translate/Toml.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Load/Manifest.lean
  src/lake/Lake/Load/Toml.lean
  src/lake/Lake/Toml/Data/Value.lean
  src/lake/Lake/Toml/Decode.lean
  src/lake/Lake/Util/Git.lean
  src/lake/Lake/Util/Version.lean
  src/lake/tests/driver/build.lean
  src/lake/tests/driver/build.toml
  src/lake/tests/driver/test.sh
  src/lake/tests/reservoirConfig/clean.sh
  src/lake/tests/reservoirConfig/expected.json
  src/lake/tests/reservoirConfig/lakefile.lean
  src/lake/tests/reservoirConfig/test.sh
  src/lake/tests/translateConfig/source.lean
  src/lake/tests/translateConfig/source.toml
  src/lake/tests/versionTags/clean.sh
  src/lake/tests/versionTags/lakefile.lean
  src/lake/tests/versionTags/test.sh
Labels: builds-mathlib, toolchain-available, release-ci

#5239 chore: use `Expr.numObjs` instead of `lean_expr_size_shared`
  src/Lean/Expr.lean
  src/Lean/PrettyPrinter.lean
  src/kernel/for_each_fn.cpp
Labels: toolchain-available

#5228 feat: gaps in Bool lemmas
  src/Init/Data/Bool.lean
  src/Init/PropLemmas.lean
  tests/lean/bool_simp.lean
Labels: builds-mathlib, toolchain-available

#5240 chore: remove BitVec simps with complicated RHS
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5242 chore: improve naming for List.mergeSort lemmas
  src/Init/Data/List/Sort/Lemmas.lean
Labels: toolchain-available

#5241 feat: add @[simp] to Nat.add_eq_zero_iff
  src/Init/Data/Nat/Lemmas.lean
  tests/lean/run/simp4.lean
  tests/lean/run/simpStar.lean
Labels: builds-mathlib, toolchain-available

#3772 refactor: rfl tactic: do not use Kernel.isDefEq
  src/Lean/Meta/Tactic/Refl.lean
  tests/lean/run/4644.lean
  tests/lean/run/ack.lean
  tests/lean/run/treeNode.lean
  tests/lean/run/wfirred.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, P-medium

#5245 chore: avoid importing List.Basic without List.Impl
  src/Init/Data/Int/Basic.lean
  src/Init/Data/List/Impl.lean
  src/Lean/Data/AssocList.lean
  src/Lean/Data/HashSet.lean
  src/Lean/Data/Json/Basic.lean
  src/Lean/Data/KVMap.lean
  src/Lean/Util/Path.lean
  src/Lean/Util/SCC.lean
  tests/lean/run/discrTreeSimp.lean
Labels: toolchain-available

#5246 chore: cleanup imports of Array.Lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Range.lean
  src/Init/Data/List/Sort/Basic.lean
  src/Init/Data/List/Sort/Lemmas.lean
Labels: toolchain-available

#5247 feat: BitVec.getElem_zeroExtend
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5248 feat: simp lemmas for BitVec, improving confluence
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5249 chore: remove @[simp] from some BitVec lemmas
  src/Init/Data/BitVec/Lemmas.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
Labels: toolchain-available

#5251 chore: remove redundant simp annotations
  src/Init/ByCases.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/PropLemmas.lean
Labels: toolchain-available

#5252 chore: change BitVec.intMin/Max from abbrev to def
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5253 chore: remove Int simp lemmas that can't fire
  src/Init/Data/Int/Order.lean
Labels: builds-mathlib, toolchain-available

#5256 chore: don't use simp_arith when simp will do
  src/Init/Data/Array/BasicAux.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/Nat/Log2.lean
  src/Init/SizeOfLemmas.lean
  src/Lean/Util/Diff.lean
Labels: toolchain-available

#5211 refactor: make `extractLsb'` the primitive bv_decide understands, rather than `extractLsb`
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/ReifiedBVExpr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Basic.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Extract.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Extract.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  src/Std/Tactic/BVDecide/Reflect.lean
  tests/lean/run/bv_extract.lean
Labels: toolchain-available, will-merge-soon

#5237 fix: include identifier before cursor in document highlight request
  src/Lean/Server/FileWorker/RequestHandling.lean
Labels: toolchain-available

#5255 chore: split Init.Data.Array.Lemmas for better bootstrapping
  src/Init/Data/Array.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Bootstrap.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/Data/List/Impl.lean
  src/Init/Data/List/Lemmas.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Clause.lean
Labels: toolchain-available

#5254 chore: variables appearing on both sides of an iff should be implicit
  src/Init/Classical.lean
  src/Init/Core.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/BEq.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Erase.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/MinMax.lean
  src/Init/Data/List/Nat/Basic.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Nat/Sublist.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Data/List/Range.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/List/Zip.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Div.lean
  src/Init/Data/Nat/Dvd.lean
  src/Init/Data/Nat/Gcd.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Nat/Mod.lean
  src/Init/Data/String/Basic.lean
  src/Init/Omega/Int.lean
  src/Init/Omega/IntList.lean
  src/Init/Omega/Logic.lean
  src/Init/PropLemmas.lean
  src/Init/SimpLemmas.lean
  src/Init/WF.lean
  src/lake/Lake/Util/Name.lean
Labels: toolchain-available

#5222 perf: reduce allocations in `Json.compress`
  src/Lean/Data/Json/Printer.lean
Labels: toolchain-available

#5260 chore: review of List API
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Erase.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/Basic.lean
  src/Init/Data/List/Nat/Pairwise.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/Perm.lean
  src/Init/Data/List/Range.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/String/Lemmas.lean
  src/Lean/Elab/Tactic/Omega/MinNatAbs.lean
  src/Std/Sat/CNF/Basic.lean
  src/Std/Sat/CNF/RelabelFin.lean
Labels: toolchain-available

#5264 chore: review of List API
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/TakeDrop.lean
Labels: toolchain-available

#5266 fix: preserve order of overapplied arguments in `elab_as_elim` procedure
  src/Lean/Elab/App.lean
  tests/lean/run/elabAsElim.lean
Labels: builds-mathlib, toolchain-available

#5267 chore: protect some Nat bitwise theorems
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: toolchain-available

#5268 chore: fix binders on ite_eq_left_iff
  src/Init/PropLemmas.lean
Labels: toolchain-available

#5250 chore: missing lemma about Fin.ofNat'
  src/Init/Data/Fin/Lemmas.lean
Labels: toolchain-available

#5262 chore: Nat.testBit_add_one should not be a global simp lemma
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5269 chore: remove HashMap's duplicated Pairwise and Sublist
  src/Std/Data/DHashMap/Internal/List/Associative.lean
  src/Std/Data/DHashMap/Internal/List/Defs.lean
  src/Std/Data/DHashMap/Internal/List/Pairwise.lean
  src/Std/Data/DHashMap/Internal/List/Sublist.lean
Labels: toolchain-available

#5272 feat: remove @[simp] from Option.pmap/pbind and add simp lemmas
  src/Init/Data/Option/Instances.lean
  src/Init/Data/Option/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5275 chore: reverse direction of List.tail_map
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#5277 feat: more List.attach lemmas
  src/Init/Data/List/Attach.lean
  src/Init/Data/Option/Lemmas.lean
Labels: toolchain-available

#5087 doc: mention that `inferType` does not ensure type correctness
  src/Lean/Meta/Basic.lean
Labels: documentation, builds-mathlib, toolchain-available

#4979 fix: make pretty printer escape identifiers that are tokens
  src/Init/Meta.lean
  src/Lean/PrettyPrinter/Formatter.lean
  tests/lean/run/4686.lean
Labels: builds-mathlib, toolchain-available

#4834 feat: let `unfold` do zeta-delta reduction of local definitions
  src/Init/Conv.lean
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Conv/Unfold.lean
  src/Lean/Elab/Tactic/Unfold.lean
  src/Lean/Meta/Tactic/Unfold.lean
  src/Lean/Meta/Transform.lean
  tests/lean/run/unfoldTactic.lean
Labels: toolchain-available

#4729 feat: have IR checker suggest `noncomputable`
  src/Lean/Compiler/IR/Checker.lean
  tests/lean/run/1785.lean
Labels: toolchain-available, P-medium

#5284 chore: turn off `Inhabited (Sum α β)` instances
  src/Init/Core.lean
Labels: builds-mathlib, toolchain-available

#5271 chore: remove @[simp] from List.head_mem and similar
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  tests/lean/run/list_simp.lean
Labels: builds-mathlib, toolchain-available

#5285 feat: List.count lemmas
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Nat.lean
  src/Init/Data/List/Nat/Basic.lean
  src/Init/Data/List/Nat/Count.lean
  src/Init/Data/List/Perm.lean
  src/Init/Data/Option/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5143 feat: Lake shared library
  nix/bootstrap.nix
  nix/buildLeanPackage.nix
  script/lib/update-stage0
  src/CMakeLists.txt
  src/lake/LakeMain.lean
  src/stdlib.make.in
Labels: toolchain-available

#5286 fix: do not link to Lake_shared with absolute path
  src/stdlib.make.in
Labels: toolchain-available

#5263 feat: allow simplifying dite_not/decide_not with only Decidable (¬p)
  src/Init/Classical.lean
  src/Init/PropLemmas.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#5205 feat: use incrementality for completion in tactic blocks
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/Requests.lean
  src/Lean/Widget/UserWidget.lean
Labels: toolchain-available

#5287 chore: use boolean predicates in List.filter
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5289 feat: List.mem_ite_nil_left and analogues
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Option/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5290 chore: fix Nix update-stage0
  nix/bootstrap.nix
Labels: toolchain-available

#5293 feat: cleanup of List.findIdx / List.take lemmas
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/TakeDrop.lean
Labels: toolchain-available

#5235 doc: code comments about reflection support
  src/Lean/Elab/Tactic/ElabTerm.lean
  src/kernel/type_checker.cpp
Labels: builds-mathlib, toolchain-available, will-merge-soon

#5257 fix: travelling auto-completion
  src/Lean/Elab/App.lean
  src/Lean/Server/Completion.lean
  src/Lean/Server/InfoUtils.lean
  tests/lean/interactive/completionBracketedDot.lean
  tests/lean/interactive/completionBracketedDot.lean.expected.out
  tests/lean/interactive/travellingCompletions.lean
  tests/lean/interactive/travellingCompletions.lean.expected.out
Labels: toolchain-available

#5292 refactor: `Lean.Elab.Deriving.FromToJson`
  src/Lean/Elab/Deriving/FromToJson.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#5300 feat: more List.findIdx theorems
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/PropLemmas.lean
Labels: builds-mathlib

#5304 chore: Array.not_mem_empty
  src/Init/Data/Array/Lemmas.lean
Labels: toolchain-available

#5301 chore: rename Int.div/mod to tdiv/tmod
  src/Init/Data/Int/DivMod.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Lean/Data/Rat.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean
Labels: builds-mathlib, toolchain-available

#5305 chore: rename Nat bitwise lemmas
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: toolchain-available

#5307 chore: restoring Option simp confluence
  src/Init/Data/Option/Lemmas.lean
Labels: toolchain-available

#5310 chore: fix List.all/any lemmas
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#5311 chore: fix List.countP lemmas
  src/Init/Data/List/Count.lean
Labels: toolchain-available

#5313 feat: more basic BitVec ordering theory for UInt
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5316 feat: List.tail lemma
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#5302 feat: provide mergeSort comparator autoParam
  src/Init/Data/List/Sort/Basic.lean
  src/Init/Data/List/Sort/Impl.lean
  src/Init/Data/List/Sort/Lemmas.lean
  tests/lean/run/mergeSort.lean
  tests/lean/run/mergeSortCPDT.lean
Labels: builds-mathlib, toolchain-available

#5306 chore: add Nat.self_sub_mod lemma
  src/Init/Data/Nat/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5320 feat: add ediv_nonneg_of_nonpos_of_nonpos to DivModLemmas
  src/Init/Data/Int/DivModLemmas.lean
Labels: toolchain-available

#5314 feat: toNat_sub_of_le
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5244 feat: (`DHashMap`|`HashMap`|`HashSet`).(`getKey?`|`getKey`|`getKey!`|`getKeyD`)
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Basic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Lemmas.lean
  src/Std/Data/DHashMap/Internal/Defs.lean
  src/Std/Data/DHashMap/Internal/List/Associative.lean
  src/Std/Data/DHashMap/Internal/Model.lean
  src/Std/Data/DHashMap/Internal/Raw.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/Raw.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Basic.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/Raw.lean
  src/Std/Data/HashSet/RawLemmas.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#3918 feat: @[builtin_doc] attribute (part 2)
  src/Lean/Elab/InheritDoc.lean
  src/Lean/Parser/Basic.lean
  src/Lean/Parser/Command.lean
  src/Lean/Parser/Do.lean
  src/Lean/Parser/Extra.lean
  src/Lean/Parser/StrInterpolation.lean
  src/Lean/Parser/Term.lean
  src/Lean/Parser/Types.lean
  tests/lean/interactive/hoverException.lean.expected.out
Labels: builds-mathlib, toolchain-available, release-ci, P-medium

#5337 fix: inaccessible pattern vars reported as binders
  src/Lean/Elab/Match.lean
  tests/lean/linterUnusedVariables.lean
Labels: toolchain-available

#5329 refactor: tag `Iff.refl` with `@[refl]`
  src/Init/Core.lean
  tests/lean/run/variable.lean
Labels: builds-mathlib, toolchain-available

#5322 fix: invalid namespace completions
  src/Lean/Environment.lean
  tests/lean/stdio.lean
Labels: builds-mathlib, toolchain-available

#5343 feat: allow addition of `release-ci` label via comment
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/labels-from-comments.yml
Labels: toolchain-available

#5344 fix: set check level correctly during workflow
  .github/workflows/ci.yml
Labels: toolchain-available

#5348 test: tracing and test case for #5347
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/issue5347.lean
Labels: toolchain-available

#5350 feat: List.replicate lemmas
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Lemmas.lean
Labels: toolchain-available

#5303 feat: cleanup of List.getElem_append variants
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/Sublist.lean
  src/Std/Data/DHashMap/Internal/Model.lean
Labels: builds-mathlib, toolchain-available

#5352 feat: List.attachWith lemmas
  src/Init/Data/List/Attach.lean
Labels: breaks-mathlib, toolchain-available

#5353 feat: List.head_mem_head?
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#5355 feat: simp lemmas for LawfulBEq
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Option/Lemmas.lean
Labels: toolchain-available

#5331 chore: fix implicitness of List.getElem_mem
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5294 chore: switch primes on List.getElem_take
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Nat/TakeDrop.lean
Labels: builds-mathlib, toolchain-available

#5354 chore: remove @[simp] from Option.bind_map
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/Option/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5357 feat: BitVec.truncate lemmas
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5349 doc: add documentation for `groupBy.loop`
  src/Init/Data/List/Basic.lean
Labels: documentation, toolchain-available

#5356 chore: Fin.ofNat' uses NeZero
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/UInt/Basic.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Fin.lean
  tests/lean/run/generalizeMany.lean
Labels: builds-mathlib, toolchain-available

#5278 feat: add `BitVec.getElem_truncate`
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-review, builds-mathlib, toolchain-available, P-high

#5360 feat: lemmas about List.tail
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/Basic.lean
  src/Init/Data/List/Nat/Count.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Range.lean
  src/Init/Data/List/Zip.lean
Labels: toolchain-available

#4768 fix: do not ban `..` with a `.` on the next line
  src/Lean/Parser/Term.lean
  tests/lean/run/4768.lean
Labels: awaiting-review, toolchain-available, P-medium

#5373 chore: fix name of List.length_mergeSort
  src/Init/Data/List/Sort/Lemmas.lean
Labels: toolchain-available

#5378 chore: modify signature of lemmas about mergeSort
  src/Init/Data/List/Sort/Lemmas.lean
Labels: toolchain-available

#5379 chore: remove some @[simp]s from Fin lemmas
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Fin/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5375 feat: add `bv_decide` normalization rules for `ofBool (a.getLsbD i)` and `ofBool a[i]`
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_extract.lean
Labels: toolchain-available

#5359 chore: ensure that the `rfl` tactic tries `Iff.rfl`
  src/Init/Core.lean
  tests/lean/run/5359.lean
Labels: builds-mathlib, toolchain-available

#5377 chore: upstream map_mergeSort
  src/Init/Data/List/Sort/Lemmas.lean
Labels: toolchain-available

#5332 chore: notation ^^ for Bool.xor
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Std/Sat/AIG/CNF.lean
  src/Std/Sat/AIG/CachedGatesLemmas.lean
  src/Std/Sat/AIG/Lemmas.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Add.lean
  src/Std/Tactic/BVDecide/Bitblast/BoolExpr/Basic.lean
  src/Std/Tactic/BVDecide/Normalize/Bool.lean
  src/Std/Tactic/BVDecide/Reflect.lean
  tests/bench/bv_decide_realworld.lean
  tests/lean/run/bv_substructure.lean
  tests/lean/run/scopedParsers2.lean
Labels: builds-mathlib, toolchain-available

#5382 chore: fixes spurious omega error in #5315
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  tests/lean/run/omega.lean
Labels: toolchain-available

#5380 feat: missing Fin @[simp] lemmas
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Nat/Div.lean
  tests/lean/run/regressions3210.lean
Labels: builds-mathlib, toolchain-available

#5381 chore: cleaning up redundant simp lemmas
  src/Init/ByCases.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/Basic.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Zip.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/SimpLemmas.lean
  src/Std/Tactic/BVDecide/LRAT/Checker.lean
Labels: builds-mathlib, toolchain-available

#5374 feat: add Nonempty instances for products
  src/Init/Core.lean
Labels: builds-mathlib, toolchain-available

#5365 feat: bv_decide diagnosis
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVCheck.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  tests/lean/run/bv_counterexample.lean
  tests/lean/run/bv_unused.lean
Labels: builds-mathlib, toolchain-available

#5362 refactor: remove the last use of Lean.(HashSet|HashMap)
  src/Lean/Util/ShareCommon.lean
Labels: builds-mathlib, toolchain-available

#5385 feat: add BitVec.ofBool_[and|or|xor]_ofBool theorems
  src/Init/Data/BitVec/Lemmas.lean
  tests/lean/interactive/completionPrv.lean.expected.out
Labels: toolchain-available

#5391 feat: review of List.erase / List.find lemmas
  src/Init/Data/List/Erase.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat.lean
  src/Init/Data/List/Nat/Basic.lean
  src/Init/Data/List/Nat/Erase.lean
  src/Init/Data/List/Nat/Find.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Range.lean
  src/Init/Data/List/Zip.lean
  src/Init/Data/Nat/Lemmas.lean
Labels: toolchain-available

#5392 feat: List.fold / attach lemmas
  src/Init/Data/List/Attach.lean
Labels: toolchain-available

#5394 feat: lemmas about List.maximum?
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Nat/Basic.lean
Labels: toolchain-available

#5335 fix: unused variable false positive when combining alias and non-lexical use
  src/Lean/Elab/InfoTree/Main.lean
  src/Lean/Linter/UnusedVariables.lean
  tests/lean/1018unknowMVarIssue.lean.expected.out
  tests/lean/linterUnusedVariables.lean
Labels: builds-mathlib, toolchain-available

#5396 doc: mark «tacticHave'_:=_» as an alternative form of have'
  src/Init/Tactics.lean
Labels: builds-mathlib, toolchain-available

#5393 feat: List.fold relators
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#5400 chore: reorganization in Array/Basic
  src/Init/Data/Array.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/GetLit.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Meta.lean
Labels: toolchain-available

#5369 feat: HashSet.ofArray (unverified)
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashSet/Basic.lean
Labels: breaks-mathlib, toolchain-available

#5370 feat: HashSet.partition (unverified)
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashSet/Basic.lean
Labels: toolchain-available

#5376 fix: modify projection instance binder info
  src/Lean/Meta/Instances.lean
  src/Lean/ProjFns.lean
  src/library/constructions/projection.cpp
  tests/lean/run/5333.lean
  tests/lean/run/synthOrderRegression.lean
  tests/lean/synthorder.lean.expected.out
Labels: builds-mathlib, toolchain-available

#5372 doc: add Verso to release checklist process
  doc/dev/release_checklist.md
Labels: toolchain-available

#5401 feat: instance for `Inhabited (TacticM α)`
  src/Lean/Elab/Tactic/Basic.lean
Labels: toolchain-available

#3714 feat: apply_rfl tactic: handle Eq, HEq, better error messages
  src/Lean/Meta/Tactic/Refl.lean
  src/Lean/Meta/Tactic/Rfl.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/rflApplyFoApprox.lean
  tests/lean/run/rflTacticErrors.lean
Labels: builds-mathlib, toolchain-available, P-medium

#5408 chore: basic cleanups for bv_decide
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/LRAT.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Basic.lean
Labels: toolchain-available

#5413 feat: add `_self`, `_zero`, and `_allOnes` for BitVec.[and|or|xor]
  src/Init/Data/BitVec/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5415 feat: implement `Repr Empty`
  src/Init/Data/Repr.lean
  tests/lean/run/repr_empty.lean
Labels: builds-mathlib, toolchain-available

#5420 chore: make `Array` functions either semireducible or use structural recursion
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/DecidableEq.lean
  src/Lean/Elab/PatternVar.lean
  tests/lean/run/array_isEqvAux.lean
  tests/lean/run/overAndPartialAppsAtWF.lean
Labels: toolchain-available

#5405 chore: reverse direction of List.set_map
  src/Init/Data/List/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#5422 feat: refactor DecidableEq (Array α)
  src/Init/Data/Array/DecidableEq.lean
Labels: toolchain-available

#5410 feat: BitVec analogues of Nat.{mul_two, two_mul, mul_succ, succ_mul}
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5403 feat: theorems about List.toArray
  src/Init/Core.lean
  src/Init/Data/Array/BasicAux.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/TakeDrop.lean
  src/Init/Data/Repr.lean
  src/Init/Prelude.lean
  src/Lean/Compiler/LCNF/Simp/ConstantFold.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Convert.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/Lemmas.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddSound.lean
  tests/lean/run/2670.lean
Labels: builds-mathlib, toolchain-available

#5423 feat: enhance the rewriting rules of bv_decide
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/SatAtBVLogical.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Std/Sat/AIG/RefVec.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Mul.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Mul.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  src/Std/Tactic/BVDecide/Normalize/Bool.lean
  src/Std/Tactic/BVDecide/Normalize/Prop.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available

#5418 feat: decidable quantifers for BitVec
  src/Init/Data/BitVec/Lemmas.lean
  tests/lean/run/bitvec.lean
Labels: toolchain-available

#5419 fix: must not reduce `ite` in the discriminant of match-expression when reducibility setting is `.reducible`
  src/Init/GetElem.lean
  src/Lean/Meta/WHNF.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  tests/lean/run/5388.lean
  tests/lean/run/bv_math_lit_perf.lean
Labels: builds-mathlib, toolchain-available

#5425 chore: fix spelling mistakes in error messages/exceptions
  src/Lean/Compiler/Old.lean
  src/Lean/Data/JsonRpc.lean
  src/Lean/Data/Lsp/InitShutdown.lean
  src/Lean/Elab/Match.lean
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Basic.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/Tactic/FunInd.lean
Labels: toolchain-available

#5426 chore: fix spelling mistakes in src/Lean/
  src/Lean/Compiler/IR/ResetReuse.lean
  src/Lean/Declaration.lean
  src/Lean/Environment.lean
  src/Lean/Expr.lean
  src/Lean/Parser/Command.lean
  src/Lean/Parser/Term.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/Replay.lean
  src/Lean/ResolveName.lean
  src/Lean/Server/FileWorker.lean
Labels: toolchain-available

#5428 fix: worker: make sure to always report some recent range as progress when waiting
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Language/Basic.lean
  src/Lean/Server/FileWorker.lean
Labels: toolchain-available

#5433 feat: present the bv_decide counter example at the API
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVCheck.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
Labels: toolchain-available

#5431 chore: fix spelling mistakes in src/Std/
  src/Std/Data/DHashMap/Internal/Defs.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Sat/AIG/Cached.lean
  src/Std/Sat/AIG/If.lean
  src/Std/Tactic.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/Class.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/Implementation.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/Lemmas.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  src/Std/Tactic/BVDecide/Syntax.lean
Labels: toolchain-available

#5427 chore: fix spelling mistakes in src/Init/
  src/Init/Classical.lean
  src/Init/Core.lean
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/Fin/Iterate.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Div.lean
  src/Init/Data/Nat/Mod.lean
  src/Init/Prelude.lean
  src/Init/Tactics.lean
  src/Init/WFTactics.lean
  tests/lean/getElem.lean.expected.out
  tests/lean/run/4920.lean
  tests/lean/run/issue5061.lean
Labels: toolchain-available

#5430 chore: fix spelling mistakes in non-Lean files
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/ci.yml
  script/lib/update-stage0
  src/kernel/instantiate_mvars.cpp
  src/runtime/process.cpp
  src/util/output_channel.h
Labels: toolchain-available

#5434 chore: fix spelling mistakes in examples (doc/examples/)
  doc/examples/ICERM2022/ctor.lean
  doc/examples/deBruijn.lean
  doc/examples/phoas.lean
  doc/examples/widgets.lean
Labels: toolchain-available

#5435 chore: fix spelling mistakes in src/Lean/Elab/
  src/Lean/Elab/AuxDef.lean
  src/Lean/Elab/Binders.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/DeclModifiers.lean
  src/Lean/Elab/Extra.lean
  src/Lean/Elab/Match.lean
  src/Lean/Elab/PreDefinition/Main.lean
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Elab/PreDefinition/Structural/IndGroupInfo.lean
  src/Lean/Elab/PreDefinition/Structural/Preprocess.lean
  src/Lean/Elab/PreDefinition/Structural/RecArgInfo.lean
  src/Lean/Elab/PreDefinition/TerminationArgument.lean
  src/Lean/Elab/PreDefinition/TerminationHint.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/Preprocess.lean
  src/Lean/Elab/RecAppSyntax.lean
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Elab/Tactic/BVDecide.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Attr.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  src/Lean/Elab/Tactic/Conv/Congr.lean
  src/Lean/Elab/Tactic/Omega.lean
  src/Lean/Elab/Tactic/Omega/Core.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/Elab/Term.lean
Labels: toolchain-available

#5437 chore: remove (syntactically) duplicate imports
  src/Init/Data.lean
  src/Lean/Meta/Offset.lean
  src/Std/Tactic/BVDecide/LRAT/Internal.lean
Labels: toolchain-available

#5436 chore: fix spelling mistakes in src/Lean/Meta/
  src/Lean/Meta/ArgsPacker.lean
  src/Lean/Meta/ArgsPacker/Basic.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/CompletionName.lean
  src/Lean/Meta/Constructions/BRecOn.lean
  src/Lean/Meta/Eqns.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/Injective.lean
  src/Lean/Meta/Iterator.lean
  src/Lean/Meta/LazyDiscrTree.lean
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/PProdN.lean
  src/Lean/Meta/SynthInstance.lean
  src/Lean/Meta/Tactic/Cases.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
  src/Lean/Meta/Tactic/LibrarySearch.lean
  src/Lean/Meta/Tactic/Rewrites.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  src/Lean/Meta/Tactic/Subst.lean
  src/Lean/Meta/WHNF.lean
Labels: toolchain-available

#5444 chore: Mathlib's lean-pr-testing-NNNN branches should use Batteries' lean-pr-testing-NNNN branches
  .github/workflows/pr-release.yml
Labels: toolchain-available

#5440 chore: fix spelling mistakes in RELEASES.md
  RELEASES.md
Labels: toolchain-available

#5439 chore: fix spelling mistakes in tests
  src/lake/examples/scripts/expected.out
  src/lake/examples/scripts/test.sh
  src/lake/tests/init/test.sh
  src/lake/tests/toml/tests/valid/comment/everywhere.toml
  tests/compiler/trie.lean
  tests/lean/1007.lean
  tests/lean/277a.lean
  tests/lean/277a.lean.expected.out
  tests/lean/bool_simp.lean
  tests/lean/guessLex.lean
  tests/lean/implicitArgumentError.lean
  tests/lean/indUsingTerm.lean
  tests/lean/interactive/catHover.lean
  tests/lean/interactive/catHover.lean.expected.out
  tests/lean/run/2846.lean
  tests/lean/run/3643.lean
  tests/lean/run/DVec.lean
  tests/lean/run/bv_math_lit_perf.lean
  tests/lean/run/eqnsProjections.lean
  tests/lean/run/funind_structural_mutual.lean
  tests/lean/run/funind_tests.lean
  tests/lean/run/issue4146.lean
  tests/lean/run/issue4671.lean
  tests/lean/run/issue5027.lean
  tests/lean/run/match_lit_fin_cover.lean
  tests/lean/run/repr_empty.lean
  tests/lean/run/simprocNat.lean
  tests/lean/run/structuralOverNested.lean
  tests/lean/run/trace.lean
  tests/pkg/user_attr/UserAttr/Tst.lean
  tests/playground/bool_exhaust_test.lean
  tests/playground/eval.lean
Labels: toolchain-available

#5421 feat: implement `To/FromJSON Empty`
  src/Lean/Data/Json/FromToJson.lean
  tests/lean/run/json_empty.lean
Labels: toolchain-available

#5416 feat: add LawCommIdentity + IdempotentOp for BitVec.[and|or|xor]
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-review, toolchain-available

#5438 chore: remove repeated words
  doc/dev/bootstrap.md
  doc/examples/tc.lean
  doc/expressions.md
  doc/monads/laws.lean
  src/Init/Meta.lean
  src/Init/Tactics.lean
  src/Lean/Compiler/LCNF/JoinPoints.lean
  src/Lean/Data/HashMap.lean
  src/Lean/Elab/Extra.lean
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/Quotation.lean
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Environment.lean
  src/Lean/Message.lean
  src/Lean/Meta/ArgsPacker.lean
  src/Lean/Meta/CongrTheorems.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Meta/Tactic/Intro.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  src/Lean/Parser/Term.lean
  src/Lean/Server/FileWorker.lean
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/Config/LeanExe.lean
  src/lake/Lake/Config/LeanLib.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Config/Script.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/Lake/Toml/Decode.lean
  src/library/compiler/csimp.cpp
  tests/lean/new-compiler/CompilerElimDeadBranches.lean
  tests/lean/run/rflApplyFoApprox.lean
Labels: toolchain-available

#5411 feat: BitVec.toNat_{add,sub,mul_of_lt} for BitVector non-overflow reasoning
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#5447 chore: update Pi instance names
  src/Init/Core.lean
  src/Init/Prelude.lean
Labels: toolchain-available

#5402 feat: localize universe metavariable errors at `let` bindings and `fun` binders
  src/Lean/Elab/Binders.lean
  src/Lean/Elab/DeclUtil.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/PreDefinition/Main.lean
  src/Lean/Elab/Term.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Util.lean
  src/Lean/Util/CollectLevelMVars.lean
  tests/lean/interactive/2058.lean
  tests/lean/interactive/2058.lean.expected.out
  tests/lean/run/2058.lean
  tests/lean/run/2226.lean
Labels: awaiting-review, builds-mathlib, toolchain-available, P-high

#5449 chore: update copyrights
  src/Init/Data/BitVec.lean
  src/Init/Data/Nat/Bitwise.lean
  src/Init/Data/Nat/Mod.lean
  src/Init/Omega.lean
  src/Init/Omega/Coeffs.lean
  src/Init/Omega/Constraint.lean
  src/Init/Omega/Int.lean
  src/Init/Omega/IntList.lean
  src/Init/Omega/LinearCombo.lean
  src/Init/Omega/Logic.lean
  src/Lean/Elab/Tactic/FalseOrByContra.lean
  src/Lean/Elab/Tactic/LibrarySearch.lean
  src/Lean/Elab/Tactic/Omega.lean
  src/Lean/Elab/Tactic/Omega/Core.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/Elab/Tactic/Omega/MinNatAbs.lean
  src/Lean/Elab/Tactic/Omega/OmegaM.lean
  src/Lean/Elab/Tactic/Repeat.lean
  src/Lean/Elab/Tactic/Rewrites.lean
  src/Lean/Elab/Tactic/ShowTerm.lean
  src/Lean/Elab/Tactic/SolveByElim.lean
  src/Lean/Elab/Tactic/Symm.lean
  src/Lean/LabelAttribute.lean
  src/Lean/Meta/DiscrTree.lean
  src/Lean/Meta/LazyDiscrTree.lean
  src/Lean/Meta/Tactic/Backtrack.lean
  src/Lean/Meta/Tactic/Generalize.lean
  src/Lean/Meta/Tactic/LibrarySearch.lean
  src/Lean/Meta/Tactic/Repeat.lean
  src/Lean/Meta/Tactic/Rewrites.lean
  src/Lean/Meta/Tactic/SolveByElim.lean
  src/Lean/Meta/Tactic/Symm.lean
  src/Lean/Replay.lean
  src/Lean/Util/TestExtern.lean
  tests/lean/run/match_expr_perf.lean
  tests/lean/run/show_term.lean
  tests/lean/run/solve_by_elim.lean
Labels: toolchain-available
