Repository leanprover/lean4, pull requests merged in 2024-07, with the labels that each got.

#4598 chore: pr-release: adjust to new lakefile.lean syntax
  .github/workflows/pr-release.yml
Labels: toolchain-available, will-merge-soon

#4584 fix: adapt kernel interruption to new cancellation system
  src/Init/System/IO.lean
  src/Lean/AddDecl.lean
  src/Lean/Environment.lean
  src/kernel/environment.cpp
  src/runtime/interrupt.cpp
  src/runtime/interrupt.h
  tests/lean/run/kernelInterrupt.lean
Labels: builds-mathlib, toolchain-available, backport releases/v4.9.0

#4612 feat: omega error message: normalize constraint order
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  tests/lean/run/omega.lean
Labels: toolchain-available, will-merge-soon

#4611 fix: diagnostics: show kernel diags even if it is the only section
  src/Lean/Meta/Diagnostics.lean
  tests/lean/run/ack.lean
Labels: toolchain-available, will-merge-soon

#4542 feat: termination_by structural
  src/Lean/Elab/Binders.lean
  src/Lean/Elab/LetRec.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/PreDefinition/Main.lean
  src/Lean/Elab/PreDefinition/Structural/Main.lean
  src/Lean/Elab/PreDefinition/TerminationArgument.lean
  src/Lean/Elab/PreDefinition/TerminationHint.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/PreDefinition/WF/Rel.lean
  src/Lean/Elab/Term.lean
  src/Lean/Message.lean
  src/Lean/Parser/Term.lean
  stage0/src/stdlib_flags.h
  tests/lean/interactive/terminationBySuggestion.lean
  tests/lean/interactive/terminationBySuggestion.lean.expected.out
  tests/lean/run/terminationByStructurally.lean
  tests/lean/termination_by.lean
  tests/lean/termination_by.lean.expected.out
Labels: builds-mathlib, toolchain-available

#4568 feat: mul recurrence theorems for LeanSAT
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#4593 fix: unresolve name avoiding locals
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/ResolveName.lean
  tests/lean/4591.lean
  tests/lean/4591.lean.expected.out
Labels: toolchain-available

#4597 feat: Nat.and_le_(left|right)
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: toolchain-available

#4599 feat: additional lemmas for Option
  src/Init/Data/Option/Lemmas.lean
Labels: toolchain-available

#4602 feat: additional lemmas for lists
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/TakeDrop.lean
Labels: toolchain-available

#4603 feat: getElem_congr
  src/Init/GetElem.lean
Labels: toolchain-available

#4604 feat: additional lemmas for cond
  src/Init/Data/Bool.lean
Labels: toolchain-available

#4605 feat: additional lemmas for bounded integers
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/UInt/Lemmas.lean
Labels: toolchain-available

#4619 chore: defs that should be theorems
  src/Init/WF.lean
Labels: toolchain-available

#4618 chore: delete deprecations from 2022
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Tactic/Apply.lean
  src/Lean/Meta/Tactic/Assert.lean
  src/Lean/Meta/Tactic/Assumption.lean
  src/Lean/Meta/Tactic/Cases.lean
  src/Lean/Meta/Tactic/Cleanup.lean
  src/Lean/Meta/Tactic/Clear.lean
  src/Lean/Meta/Tactic/Constructor.lean
  src/Lean/Meta/Tactic/Contradiction.lean
  src/Lean/Meta/Tactic/Delta.lean
  src/Lean/Meta/Tactic/Generalize.lean
  src/Lean/Meta/Tactic/Induction.lean
  src/Lean/Meta/Tactic/Intro.lean
  src/Lean/Meta/Tactic/Refl.lean
  src/Lean/Meta/Tactic/Rename.lean
  src/Lean/Meta/Tactic/Replace.lean
  src/Lean/Meta/Tactic/Revert.lean
  src/Lean/Meta/Tactic/Rewrite.lean
  src/Lean/Meta/Tactic/Util.lean
  src/Lean/MetavarContext.lean
  tests/lean/run/depElim1.lean
  tests/lean/run/genindices.lean
  tests/lean/run/meta.lean
  tests/lean/run/meta2.lean
  tests/lean/run/meta5.lean
  tests/lean/run/meta6.lean
  tests/lean/run/meta7.lean
  tests/lean/run/tactic.lean
Labels: toolchain-available

#4616 chore: satisfy duplicate namespace linter
  src/Init/Data/Char/Lemmas.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
Labels: toolchain-available

#4620 chore: follow simpNF linter's advice
  src/Init/Control/Lawful/Instances.lean
  src/Init/Data/Array/Mem.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/PropLemmas.lean
  src/Init/SimpLemmas.lean
  tests/lean/run/exfalsoBug.lean
Labels: toolchain-available

#4617 chore: add 'since' dates to deprecated
  src/Init/Data/Option/Basic.lean
  src/Init/GetElem.lean
  src/Lean/Message.lean
  src/Lean/Meta/Tactic/Replace.lean
  src/lake/Lake/Build/Basic.lean
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Fetch.lean
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Build/Trace.lean
  src/lake/Lake/Util/Log.lean
Labels: toolchain-available

#4625 chore: make constructor-as-variable test more robust
  tests/lean/run/constructor_as_variable.lean
Labels: toolchain-available

#4596 fix: enforce `isDefEqStuckEx` at `unstuckMVar` procedure
  src/Lean/Elab/App.lean
  src/Lean/Meta/ExprDefEq.lean
  tests/lean/run/2736.lean
  tests/lean/run/439.lean
  tests/lean/run/scopedunifhint.lean
Labels: builds-mathlib, toolchain-available, release-ci

#4628 fix: Windows build
  src/runtime/interrupt.cpp
  src/runtime/interrupt.h
Labels: toolchain-available, backport releases/v4.9.0, backport releases/v4.10.0

#4632 chore: pr-release: use right tag name
  .github/workflows/pr-release.yml
Labels: toolchain-available

#4558 fix: set default value of `pp.instantiateMVars` to true and make the option be effective
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  src/Lean/Server/FileWorker/WidgetRequests.lean
  src/Lean/Util/PPExt.lean
  src/Lean/Widget/InteractiveCode.lean
  tests/lean/run/4406.lean
Labels: toolchain-available

#4629 feat: USize.and_toNat
  src/Init/Data/Fin/Bitwise.lean
  src/Init/Data/UInt.lean
  src/Init/Data/UInt/Bitwise.lean
Labels: toolchain-available

#4600 feat: Option.or
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Lemmas.lean
Labels: toolchain-available

#4635 chore: typo
  src/Lean/Elab/BuiltinNotation.lean
Labels: toolchain-available

#4637 feat: safe exponentiation
  src/Lean/CoreM.lean
  src/Lean/Message.lean
  src/Lean/Meta/Offset.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Nat.lean
  src/Lean/Meta/WHNF.lean
  src/Lean/Util.lean
  src/Lean/Util/SafeExponentiation.lean
  src/kernel/type_checker.cpp
  src/kernel/type_checker.h
  tests/lean/run/lean_nat_gcd.lean
  tests/lean/run/safeExp.lean
Labels: builds-mathlib, toolchain-available

#4631 fix: make sure syntax nodes always run their formatters
  src/Lean/PrettyPrinter/Formatter.lean
  tests/lean/run/4561.lean
Labels: toolchain-available

#4638 chore: manual nightly trigger
  .github/workflows/ci.yml
Labels: toolchain-available

#4640 chore: CI: restart-on-label: view run more often
  .github/workflows/restart-on-label.yml
Labels: toolchain-available, will-merge-soon

#4643 fix: snapshot subtree was not restored on reuse
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Term.lean
  tests/lean/interactive/incrementalTactic.lean
  tests/lean/interactive/incrementalTactic.lean.expected.out
Labels: builds-mathlib, toolchain-available

#4646 fix: improve `synthAppInstances`
  src/Lean/Meta/Tactic/Apply.lean
  tests/lean/run/synthInstsIssue.lean
Labels: builds-mathlib, toolchain-available

#4607 feat: EquivBEq and LawfulHashable classes
  src/Init/Data/BEq.lean
  src/Init/Data/Hashable.lean
Labels: toolchain-available, will-merge-soon

#4627 feat: additional lemmas for arrays
  src/Init/Data/Array/TakeDrop.lean
Labels: toolchain-available, will-merge-soon

#4651 fix: universe level in .below and .brecOn construction
  src/Lean/Meta/Constructions/BRecOn.lean
  tests/lean/run/issue4650.lean
Labels: toolchain-available, will-merge-soon, backport releases/v4.10.0

#4656 refactor: Split Constructions module
  src/Lean/Elab/ComputedFields.lean
  src/Lean/Meta/Constructions.lean
  src/Lean/Meta/Constructions/CasesOn.lean
  src/Lean/Meta/Constructions/NoConfusion.lean
  src/Lean/Meta/IndPredBelow.lean
Labels: toolchain-available, will-merge-soon

#4663 chore: restart-on-label: wait for 30s
  .github/workflows/restart-on-label.yml
Labels: toolchain-available, will-merge-soon

#4665 fix: don't set `pp.tagAppFns` when pretty printing signatures
  src/Lean/PrettyPrinter.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
Labels: toolchain-available

#4661 fix: move Std from libleanshared to much smaller libInit_shared
  src/CMakeLists.txt
  src/stdlib.make.in
  stage0/src/CMakeLists.txt
  stage0/src/stdlib.make.in
Labels: release-ci

#4668 fix: explicitly initialize `Std` in `lean_initialize`
  src/CMakeLists.txt
  src/Std/Data/DHashMap.lean
  src/initialize/init.cpp
Labels: toolchain-available, release-ci

#4666 chore: make Antisymm a Prop
  src/Init/Core.lean
Labels: toolchain-available

#4672 fix: `hasBadParamDep?` to look at term, not type
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  tests/lean/run/issue4671.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4664 chore: bump actions/checkout and actions/upload-artifacts
  .github/workflows/actionlint.yml
  .github/workflows/ci.yml
  .github/workflows/nix-ci.yml
  .github/workflows/pr-release.yml
  .github/workflows/update-stage0.yml
Labels: awaiting-review, builds-mathlib, toolchain-available

#4621 chore: cleanup unused arguments (from linter)
  src/Init/Control/Lawful/Instances.lean
  src/Init/Control/StateRef.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Option/Basic.lean
  src/Init/GetElem.lean
  src/Lean/Exception.lean
  src/Lean/ResolveName.lean
Labels: toolchain-available

#4680 fix: unorphan modules in Init
  src/Init/Data.lean
  src/Init/Data/Array.lean
Labels: toolchain-available

#4682 chore: `Inhabited` instances for `Std.HashMap`
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashMap/Raw.lean
  src/Std/Data/HashSet/Basic.lean
  src/Std/Data/HashSet/Raw.lean
Labels: toolchain-available

#4669 chore: fix "max dynamic symbols" metric
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#4657 fix: calculate error suppression per snapshot
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Term.lean
  tests/lean/interactive/incrementalMutual.lean
  tests/lean/interactive/incrementalMutual.lean.expected.out
  tests/lean/interactive/incrementalTactic.lean
  tests/lean/interactive/incrementalTactic.lean.expected.out
Labels: toolchain-available, backport releases/v4.9.0, backport releases/v4.10.0

#4683 chore: update comments in kernel/declaration.h
  src/kernel/declaration.h
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4660 feat: `Process.tryWait`
  src/Init/System/IO.lean
  src/runtime/process.cpp
  tests/lean/Process.lean
  tests/lean/Process.lean.expected.out
Labels: toolchain-available, release-ci

#4687 chore: adjust `List.replicate` simp lemmas
  src/Init/Data/List/TakeDrop.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/List.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/list_simp.lean
Labels: toolchain-available

#4688 chore: forward and backward directions of not_exists
  src/Init/PropLemmas.lean
Labels: toolchain-available

#4690 chore: upstream SMap.foldM
  src/Lean/Data/SMap.lean
Labels: toolchain-available

#4691 chore: improve compatibility of tests/list_simp with Mathlib
  tests/lean/run/list_simp.lean
Labels: toolchain-available

#4693 chore: add step to release checklist
  doc/dev/release_checklist.md
Labels: toolchain-available

#4543 feat: make `@[ext]` derive `ext_iff` theorems from user `ext` theorems
  src/Init/Data/Char/Lemmas.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Ext.lean
  src/Lean/Elab/Tactic/Ext.lean
  tests/lean/run/3643.lean
  tests/lean/run/etaStructProofIrrelIssue.lean
  tests/lean/run/ext.lean
  tests/lean/run/ext1.lean
Labels: awaiting-mathlib, breaks-mathlib, toolchain-available, release-ci

#4689 chore: upstream eq_iff_true_of_subsingleton
  src/Init/Core.lean
  tests/lean/discrTreeIota.lean
  tests/lean/run/1829.lean
Labels: toolchain-available

#4694 chore: make use of `ext_iff` realization now that stage0 is updated
  src/Init/Data/Char/Lemmas.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Ext.lean
  src/Lean/Elab/Tactic/Ext.lean
Labels: toolchain-available

#4692 feat: lake: `require @ git`
  src/lake/Lake/CLI/Translate/Lean.lean
  src/lake/Lake/DSL/Require.lean
  src/lake/tests/translateConfig/out.expected.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4695 feat: omega doesn't push coercion over multiplication unnecessarily
  src/Init/Omega/LinearCombo.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  tests/lean/run/omega.lean
Labels: toolchain-available

#4697 feat: chore upstream `List.Sublist` and API from Batteries
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  tests/lean/run/constructor_as_variable.lean
Labels: toolchain-available

#4652 fix: prefer original module in const2ModIdx
  src/Lean/Environment.lean
Labels: toolchain-available

#4704 feat: characterisations of List.Sublist
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/SimpLemmas.lean
Labels: toolchain-available

#4706 feat: basic material on List.Pairwise and Nodup
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  tests/lean/run/1842.lean
  tests/lean/run/constructor_as_variable.lean
Labels: toolchain-available

#4458 doc: update release checklist for new release notes workflow
  doc/dev/release_checklist.md
Labels: toolchain-available

#4678 feat: lemmas for List.head and List.getLast
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/Option/Lemmas.lean
  tests/lean/run/list_simp.lean
Labels: toolchain-available, release-ci

#4707 feat: simp normal form tests for Pairwise and Nodup
  src/Init/Data/List/Lemmas.lean
  tests/lean/run/list_simp.lean
Labels: toolchain-available

#4708 chore: reorganise lemmas on list getters
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#4709 fix: `Repr` instances for `Int` and `Float`
  src/Init/Data/Float.lean
  src/Init/Data/Repr.lean
  tests/lean/run/4677.lean
Labels: toolchain-available

#4711 fix: `decide` tactic transparency
  src/Lean/Elab/Tactic/ElabTerm.lean
  tests/lean/run/4644.lean
Labels: toolchain-available

#4710 fix: make iff theorem generated by `@[ext]` preserve inst implicits
  src/Lean/Elab/Tactic/Ext.lean
  tests/lean/run/ext.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4713 fix: deprecated warnings for overloaded symbols
  src/Lean/Elab/App.lean
  src/Lean/Elab/Term.lean
  tests/lean/run/4636.lean
Labels: toolchain-available

#4715 fix: mutual structural recursion: check that datatype parameters agree
  src/Lean/Elab/PreDefinition/Structural/Main.lean
  tests/lean/run/structuralMutual.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4720 feat: upstream more erase API
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Impl.lean
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#4719 chore: fix typo in doc-string
  src/Lean/Parser/Command.lean
Labels: awaiting-review, toolchain-available

#4723 feat: further theorems for List.erase
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/PropLemmas.lean
Labels: toolchain-available

#4724 fix: make matcher pretty printer sensitive to `pp.explicit`
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
Labels: toolchain-available

#4728 fix: nested structural recursion over reflexive data type
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  tests/lean/run/issue4726.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4674 feat: detailed feedback on `decide` tactic failure
  src/Lean/Elab/Tactic/ElabTerm.lean
  src/Lean/PrettyPrinter.lean
  tests/lean/2161.lean
  tests/lean/2161.lean.expected.out
  tests/lean/decideTactic.lean
  tests/lean/decideTactic.lean.expected.out
  tests/lean/run/2161.lean
  tests/lean/run/4644.lean
  tests/lean/run/decideTactic.lean
Labels: toolchain-available

#4731 feat: Meta.withErasedFVars
  src/Lean/Elab/BuiltinTerm.lean
  src/Lean/Elab/Match.lean
  src/Lean/Meta/Basic.lean
Labels: toolchain-available, will-merge-soon

#4447 feat: add `#discr_tree_key` command and `discr_tree_key` tactic
  src/Init/Notation.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/DiscrTreeKey.lean
  tests/lean/run/discrTreeKey.lean
Labels: toolchain-available

#4658 feat: .below and .brecOn for nested inductive
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Meta/Constructions/BRecOn.lean
  tests/lean/run/nestedInductiveConstructions.lean
  tests/lean/run/structuralMutual.lean
Labels: builds-mathlib, toolchain-available, release-ci

#4734 refactor: use `indVal.numNested` or `indVal.numTypeFormers` where applicable
  src/Lean/Declaration.lean
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/PreDefinition/Structural/Basic.lean
  src/Lean/Meta/SizeOf.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/MonadEnv.lean
  tests/lean/run/structuralMutual.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4735 feat: lake: cleaner release handling & related touchups
  src/lake/Lake/Build/Basic.lean
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Fetch.lean
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/Build/Run.lean
  src/lake/Lake/Util/Git.lean
  src/lake/Lake/Util/MainM.lean
  src/lake/tests/noRelease/lakefile.lean
  src/lake/tests/noRelease/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon, release-ci

#4737 doc: fix misplaced docstring for `getThe`
  src/Init/Prelude.lean
Labels: toolchain-available

#4738 refactor: IndGroupInfo and IndGroupInst
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/PreDefinition/Structural/Basic.lean
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Elab/PreDefinition/Structural/IndGroupInfo.lean
  src/Lean/Elab/PreDefinition/Structural/IndPred.lean
  src/Lean/Elab/PreDefinition/Structural/Main.lean
  src/Lean/Elab/PreDefinition/Structural/RecArgInfo.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/Tactic/FunInd.lean
Labels: toolchain-available, will-merge-soon

#4740 test: extend test for #4671 with nice example reported on zulip
  tests/lean/run/issue4671.lean
Labels: toolchain-available, will-merge-soon

#4733 feat: structural recursion over nested datatypes
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Elab/PreDefinition/Structural/IndGroupInfo.lean
  src/Lean/Elab/PreDefinition/Structural/Main.lean
  tests/lean/run/funind_proof.lean
  tests/lean/run/nestedTypeFormers.lean
  tests/lean/run/structuralMutual.lean
  tests/lean/run/structuralOverNested.lean
Labels: toolchain-available

#4747 feat: PProd and MProd syntax (part 1)
  src/Init/Notation.lean
  src/Init/NotationExtra.lean
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Parser/Term.lean
  stage0/src/stdlib_flags.h
  tests/lean/348.lean.expected.out
  tests/lean/interactive/incrementalTactic.lean.expected.out
  tests/lean/trailingComma.lean.expected.out
Labels: toolchain-available, will-merge-soon

#4730 feat: PProd and MProd syntax (part 2)
  src/Init/NotationExtra.lean
  src/Lean/Elab/BuiltinNotation.lean
  tests/lean/run/PUnit_syntax.lean
Labels: toolchain-available, will-merge-soon

#4746 chore: exclude more symbols to get below Windows symbol limit
  src/Lean/Compiler/IR/EmitC.lean
Labels: toolchain-available, release-ci

#4725 chore: rename HashMap.remove to HashMap.erase
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Basic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Lemmas.lean
  src/Std/Data/DHashMap/Internal/Defs.lean
  src/Std/Data/DHashMap/Internal/List/Associative.lean
  src/Std/Data/DHashMap/Internal/Model.lean
  src/Std/Data/DHashMap/Internal/Raw.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/Raw.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Basic.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/Raw.lean
  src/Std/Data/HashSet/RawLemmas.lean
Labels: toolchain-available

#4753 chore: missing `profileitM`
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/PreDefinition/Main.lean
Labels: toolchain-available

#4754 feat: add `Lean.Expr.numObjs`
  src/Lean/Util.lean
  src/Lean/Util/NumObjs.lean
Labels: toolchain-available

#4760 chore: rename TC to Relation.TransGen
  src/Init/Core.lean
  src/Init/WF.lean
Labels: toolchain-available

#4764 chore: add comment for why anonymous constructor notation isn't flattened during pretty printing
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
Labels: toolchain-available

#4756 feat: PProd syntax (part 3)
  src/Init/Notation.lean
  src/Init/NotationExtra.lean
  src/Init/Prelude.lean
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Parser/Term.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/348.lean.expected.out
  tests/lean/interactive/incrementalTactic.lean.expected.out
  tests/lean/run/PProd_syntax.lean
  tests/lean/run/PUnit_syntax.lean
  tests/lean/trailingComma.lean.expected.out
Labels: toolchain-available, will-merge-soon

#4766 refactor: move Synax.hasIdent, shake dependencies
  src/Lean/Compiler/LCNF/Main.lean
  src/Lean/Compiler/LCNF/PrettyPrinter.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/PreDefinition/TerminationArgument.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/Syntax.lean
  src/Lean/Widget/InteractiveCode.lean
Labels: toolchain-available, will-merge-soon

#4767 perf: add `ShareCommon.shareCommon'`
  src/Init/ShareCommon.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/include/lean/lean.h
  src/runtime/sharecommon.cpp
Labels: toolchain-available

#4765 feat: simprocs for #[1,2,3,4,5][2]
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/LitValues.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Array.lean
  tests/lean/run/array_simp.lean
Labels: builds-mathlib, toolchain-available

#4732 chore: fix BEq argument order in hash map lemmas
  src/Std/Data/DHashMap/Internal/AssocList/Basic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Lemmas.lean
  src/Std/Data/DHashMap/Internal/List/Associative.lean
  src/Std/Data/DHashMap/Internal/Model.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/RawLemmas.lean
Labels: toolchain-available, will-merge-soon

#4759 fix: resolve instances for `HashMap` via unification
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashSet/Basic.lean
  src/Std/Data/HashSet/Lemmas.lean
  tests/lean/run/hashmap-implicits.lean
Labels: toolchain-available

#4771 doc: mention linearity in hash map docstring
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/RawDef.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashMap/Raw.lean
  src/Std/Data/HashSet/Basic.lean
  src/Std/Data/HashSet/Raw.lean
Labels: toolchain-available

#4775 chore: simplify `shareCommon'`
  src/runtime/sharecommon.cpp
Labels: toolchain-available

#4776 perf: `Replacement.apply`
  src/Lean/Data/RBMap.lean
  src/Lean/Elab/MutualDef.lean
Labels: toolchain-available

#4777 fix: missing assignment validation at `closeMainGoal`
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/ElabTerm.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/ExprDefEq.lean
  tests/lean/run/2243.lean
  tests/lean/run/4773.lean
Labels: toolchain-available

#4762 feat: improve `@[ext]` error message when `ext_iff` generation fails
  src/Init/Ext.lean
  src/Lean/Elab/Tactic/Ext.lean
  tests/lean/run/ext.lean
Labels: builds-mathlib, toolchain-available

#4778 feat: add some low level helper APIs
  src/Init/Util.lean
  src/include/lean/lean.h
Labels: toolchain-available

#4722 fix: have elabAsElim check inferred motive for type correctness
  src/Lean/Elab/App.lean
  tests/lean/elabAsElim.lean
  tests/lean/elabAsElim.lean.expected.out
Labels: toolchain-available

#4779 perf: ensure `Expr.replaceExpr` preserve DAG structure in `Expr`s
  src/Lean/Util/PtrSet.lean
  src/Lean/Util/ReplaceExpr.lean
Labels: toolchain-available

#4783 chore: document `replaceUnsafeM` issue
  src/Lean/Util/ReplaceExpr.lean
Labels: toolchain-available

#4712 fix: `.eq_def` theorem generation with messy universes
  src/Lean/Elab/PreDefinition/Eqns.lean
  tests/lean/run/4673.lean
Labels: builds-mathlib, toolchain-available

#4784 chore: `Simp.Config.implicitDefEqProofs := true` by default
  src/Init/MetaTypes.lean
Labels: toolchain-available

#4787 refactor: IndGroupInst.brecOn
  src/Lean/AuxRecursor.lean
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/PreDefinition/Structural/IndGroupInfo.lean
  tests/lean/run/funind_structural.lean
  tests/lean/run/structuralMutual.lean
Labels: toolchain-available, will-merge-soon

#4788 refactor: add numFixed to Structural.EqnInfo
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Main.lean
Labels: toolchain-available, will-merge-soon

#4792 fix: add term elaborator for `Lean.Parser.Term.namedPattern`
  src/Lean/Elab/BuiltinTerm.lean
  tests/lean/run/4662.lean
Labels: toolchain-available

#4742 feat: theory from LeanSAT
  src/Init/Data/List/Lemmas.lean
  src/Init/PropLemmas.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4794 perf: `for_each` with precise cache
  src/Lean/Util/FindExpr.lean
  src/kernel/declaration.cpp
  src/kernel/expr.cpp
  src/kernel/for_each_fn.cpp
  src/kernel/for_each_fn.h
  src/kernel/type_checker.cpp
Labels: toolchain-available

#4795 perf: `find?` and `findExt?`
  src/Lean/Util/FindExpr.lean
Labels: toolchain-available

#4796 perf: kernel `replace` with precise cache
  src/Lean/Util/ReplaceExpr.lean
  src/kernel/cache_stack.h
  src/kernel/replace_fn.cpp
Labels: toolchain-available

#4797 fix: `for_each_fn.cpp`
  src/kernel/for_each_fn.cpp
Labels: toolchain-available

#4799 perf: `Expr.replace`
  src/Lean/Util/ReplaceExpr.lean
Labels: toolchain-available

#4782 doc: remove reference to HashMap.find? from Option docstring
  src/Init/Prelude.lean
Labels: toolchain-available, will-merge-soon

#4790 fix: remove typeclass assumptions for Nodup.eraseP
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#4801 feat: usize for array types
  src/Init/Data/Array/Basic.lean
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/FloatArray/Basic.lean
  stage0/src/stdlib_flags.h
Labels: awaiting-review, toolchain-available

#4802 feat: use usize for array types
  src/Init/Data/Array/Basic.lean
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/FloatArray/Basic.lean
  tests/lean/doubleReset.lean.expected.out
Labels: awaiting-review, toolchain-available

#4789 refactor: FunInd overhaul
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/funind_structural.lean
  tests/lean/run/funind_tests.lean
  tests/lean/run/structuralMutual.lean
Labels: builds-mathlib, toolchain-available

#4772 feat: functional induction for mutual structural recursion
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/funind_structural_mutual.lean
  tests/lean/run/funind_tests.lean
  tests/lean/run/structuralMutual.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4809 feat: unnecessary termination_by clauses cause warnings, not errors
  src/Lean/Elab/PreDefinition/Main.lean
  src/Lean/Elab/PreDefinition/TerminationHint.lean
  tests/lean/termination_by.lean.expected.out
Labels: toolchain-available, will-merge-soon

#4748 doc: document `Command.Scope`
  src/Lean/Elab/Command.lean
  src/Lean/Parser/Command.lean
Labels: awaiting-review, toolchain-available, P-medium

#4800 fix: make `elab_as_elim` eagerly elaborate arguments for parameters appearing in the types of targets
  src/Lean/Elab/App.lean
  tests/lean/elabAsElim.lean
  tests/lean/elabAsElim.lean.expected.out
  tests/lean/run/elabAsElim.lean
Labels: builds-mathlib, toolchain-available, release-ci

#4803 feat: more hash map lemmas
  src/Std/Data/DHashMap/Internal/List/Associative.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/RawLemmas.lean
Labels: toolchain-available

#4806 doc: update quickstart guide
  doc/images/code-ext.png
  doc/images/setup_guide.png
  doc/images/show-setup-guide.png
  doc/quickstart.md
Labels: toolchain-available

#4808 chore: release notes for mutual structural induction
  releases_drafts/mutualStructural.md
Labels: toolchain-available

#4810 feat: safer #eval, and #eval!
  doc/examples/interp.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/Print.lean
  src/Lean/Parser/Command.lean
  src/Lean/Util/CollectAxioms.lean
  stage0/src/stdlib_flags.h
  tests/lean/277a.lean.expected.out
  tests/lean/277b.lean.expected.out
  tests/lean/440.lean.expected.out
  tests/lean/evalSorry.lean.expected.out
  tests/lean/phashmap_inst_coherence.lean.expected.out
  tests/lean/prvCtor.lean.expected.out
  tests/lean/run/1697.lean
  tests/lean/run/3713.lean
  tests/lean/run/compiler_proj_bug.lean
  tests/lean/run/lcnfEtaExpandBug.lean
  tests/lean/scientific.lean.expected.out
  tests/lean/terminationFailure.lean
Labels: toolchain-available, will-merge-soon

#4815 test: update test output following stage0 update
  tests/lean/ppMotives.lean.expected.out
  tests/lean/run/diagRec.lean
  tests/lean/unusedLet.lean.expected.out
Labels: toolchain-available, will-merge-soon

#4819 test: test case for #4751
  src/Lean/Meta/IndPredBelow.lean
  tests/lean/run/4751.lean
Labels: toolchain-available, will-merge-soon

#4820 chore: List.filterMapM runs and returns left-to-right
  src/Init/Data/List/Control.lean
  tests/lean/run/array1.lean
Labels: toolchain-available

#4580 feat: trailing whitespace changes should not invalidate imports
  src/Init/Meta.lean
  src/Lean/Language/Lean.lean
  tests/lean/interactive/incrementalCommand.lean
  tests/lean/interactive/incrementalCommand.lean.expected.out
Labels: toolchain-available

#4727 feat: respond to info view requests as soon as relevant tactic has finished execution
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Elab/Term.lean
  src/Lean/Language/Basic.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/Requests.lean
  src/Lean/Widget/UserWidget.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4818 fix: make sure anonymous dot notation works with pi-type-valued type synonyms
  src/Lean/Elab/App.lean
  tests/lean/run/4761.lean
Labels: builds-mathlib, toolchain-available

#4608 feat: create ci workflow on lake new/init
  src/lake/Lake/CLI/Init.lean
Labels: toolchain-available

#4786 fix: filter duplicate subexpressions
  src/Lean/PrettyPrinter/Parenthesizer.lean
Labels: toolchain-available

#4829 test: make #1697 test case Linux-Debug safe
  tests/lean/run/1697.lean
Labels: toolchain-available, will-merge-soon, release-ci

#4830 chore: report github actions failure on zulip
  .github/workflows/ci.yml
Labels: toolchain-available, will-merge-soon

#4831 fix: structural recursion: do not check for brecOn too early
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Elab/PreDefinition/Structural/IndGroupInfo.lean
  tests/lean/guessLexFailures.lean.expected.out
  tests/lean/run/structuralMutual.lean
  tests/lean/run/terminationByStructurally.lean
Labels: toolchain-available, will-merge-soon

#4836 chore: upstream IsPrefix/IsSuffix/IsInfix
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#4835 feat: gaps/cleanup in List lemmas
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Lemmas.lean
  src/Std/Data/DHashMap/Internal/List/Associative.lean
Labels: toolchain-available

#4837 feat: List.IsPrefix/IsSuffix is decidable
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#4838 chore: upon nightly release, trigger nightly_bump_toolchain on mathlib4
  .github/workflows/ci.yml
Labels: toolchain-available, will-merge-soon
