Repository leanprover/lean4, pull requests merged in 2024-04, with the labels that each got.

#3815 fix: matcher splitter is code
  src/Lean/Meta/Eqns.lean
  src/Lean/Meta/Match/MatchEqs.lean
  tests/lean/run/matchEqsBug.lean
Labels: toolchain-available

#3816 fix: `.yesWithDeltaI` behavior
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/WHNF.lean
  tests/lean/run/simp_proj_transparency_issue.lean
Labels: toolchain-available

#3819 fix: loose bound variables at ACLt
  src/Lean/Meta/ACLt.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  tests/lean/run/3705.lean
Labels: toolchain-available

#3820 fix: do not lift `(<- ...)` over pure if-then-else
  src/Lean/Compiler/IR/EmitLLVM.lean
  src/Lean/Compiler/LCNF/LambdaLifting.lean
  src/Lean/Elab/BuiltinTerm.lean
  src/Lean/Elab/Deriving/DecEq.lean
  src/Lean/Elab/Do.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Elab/Tactic/Ext.lean
  src/Lean/Meta/AbstractMVars.lean
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/Tactic/Rewrites.lean
  tests/lean/run/3713.lean
Labels: toolchain-available

#3821 fix: `simp` usedSimps
  src/Lean/Data/PersistentHashMap.lean
  src/Lean/Expr.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  tests/lean/run/3710.lean
Labels: toolchain-available

#3824 fix: `simp only` should break `Char` literals
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/3686.lean
Labels: toolchain-available

#3818 feat: weight lazy discriminator tree results early matches
  src/Lean/Meta/LazyDiscrTree.lean
  tests/lean/librarySearch.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#3828 fix: omega works as a simp discharger
  src/Lean/Elab/Tactic/FalseOrByContra.lean
  tests/lean/run/omegaDischarger.lean
Labels: toolchain-available

#3832 fix: `String.splitOn` bug
  src/Init/Data/String/Basic.lean
  tests/lean/string_imp.lean
  tests/lean/string_imp.lean.expected.out
Labels: toolchain-available

#3692 chore: `update-stage0-commit` cmake target
  CMakeLists.txt
  doc/dev/bootstrap.md
  src/CMakeLists.txt
Labels: toolchain-available, will-merge-soon

#3808 fix: replace unary Nat.succ simp rules with simprocs
  src/Init/Core.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Nat/Linear.lean
  src/Init/Data/Nat/Simproc.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Nat.lean
  tests/lean/run/funind_structural.lean
  tests/lean/run/simprocNat.lean
Labels: breaks-mathlib, toolchain-available, full-ci

#3834 chore: when setting up Mathlib CI, make sure nightly-with-mathlib branch has been fetched
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3806 fix: typo in `withSetOptionIn`
  src/Lean/Elab/Command.lean
  tests/lean/withSetOptionIn.lean
  tests/lean/withSetOptionIn.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#3844 fix: remove unused trace.Elab.syntax option
  src/Lean/Elab/Syntax.lean
Labels: builds-mathlib, toolchain-available

#3853 fix: omega: ignore levels in canonicalizer
  src/Lean/Meta/Canonicalizer.lean
  tests/lean/run/issue3848.lean
Labels: builds-mathlib, toolchain-available

#3875 refactor: Canonicalizer: run `getFunInfo` on expression, not key
  src/Lean/Meta/Canonicalizer.lean
Labels: toolchain-available

#3878 chore: update CODEOWNERS
  CODEOWNERS
Labels: toolchain-available

#3874 doc: moduleDoc
  src/Lean/Parser/Command.lean
Labels: documentation, toolchain-available

#3868 doc: some doc-strings for Option
  src/Init/Data/Option/Basic.lean
Labels: documentation, toolchain-available

#3880 feat: add BitVec Int add & mul lemmas
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/DivModLemmas.lean
Labels: builds-mathlib, toolchain-available

#3861 doc: doc-string for Ord and Ord.compare
  src/Init/Data/Ord.lean
Labels: documentation, toolchain-available

#3884 chore: protect Std.BitVec
  src/Init/Data/BitVec/Basic.lean
Labels: toolchain-available

#3887 perf: fix linearity in (HashSet|HashMap).erase
  src/Lean/Data/HashMap.lean
  src/Lean/Data/HashSet.lean
Labels: toolchain-available

#3869 doc: Leo-Henrik retreat doc
  src/Init/Data/Repr.lean
  src/Init/WF.lean
  src/Lean/Meta/Basic.lean
Labels: toolchain-available

#3870 doc: describe all `simp` configuration options
  src/Init/MetaTypes.lean
Labels: documentation, builds-mathlib, toolchain-available

#3893 chore: use `Ordering.then` in `deriving Ord`
  src/Lean/Elab/Deriving/Ord.lean
Labels: toolchain-available

#3894 doc: fix `simp` configuration option default value for `decide`
  src/Init/MetaTypes.lean
Labels: toolchain-available

#3896 feat: hover / go-to-def for `attribute` cmd
  src/Lean/Elab/Declaration.lean
  tests/lean/interactive/hover.lean
  tests/lean/interactive/hover.lean.expected.out
Labels: toolchain-available

#3851 chore: rename fields of Subarray to follow Lean conventions
  CODEOWNERS
  RELEASES.md
  src/Init/Data/Array/Subarray.lean
  src/Init/Data/Stream.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon, full-ci

#3858 doc: docstrings for some Fin definitions
  src/Init/Data/Fin/Basic.lean
  src/Init/Prelude.lean
Labels: documentation, toolchain-available

#3856 chore: add doc-string for Prod.mk
  src/Init/Prelude.lean
Labels: documentation, toolchain-available

#3857 doc: add docstring for Nat.gcd
  src/Init/Data/Nat/Gcd.lean
Labels: documentation, toolchain-available

#3867 doc: docstrings for List.mapM and friends
  src/Init/Data/List/Control.lean
Labels: toolchain-available

#3883 feat: whitespace and message ordering configurations for `#guard_msgs`
  RELEASES.md
  src/Init/Notation.lean
  src/Lean/Elab/GuardMsgs.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/guard_msgs.lean
Labels: toolchain-available

#3900 doc: rephrase a couple RELEASES entries
  RELEASES.md
Labels: toolchain-available

#3747 feat: make `rcases` use the custom `Nat` eliminator
  src/Lean/Elab/Tactic/RCases.lean
  src/Lean/Meta/Tactic/Cases.lean
  tests/lean/run/rcases.lean
Labels: toolchain-available

#3902 doc: update RELEASES for `rcases` using the custom `Nat` eliminator
  RELEASES.md
Labels: toolchain-available

#3089 feat: shorten auto-generated instance names
  RELEASES.md
  src/Init/Control/Lawful/Instances.lean
  src/Init/Data/Int/Basic.lean
  src/Init/Data/Nat/Div.lean
  src/Init/Prelude.lean
  src/Init/System/IO.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/DeclNameGen.lean
  src/Lean/Elab/DeclUtil.lean
  src/Lean/Elab/DefView.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Expr.lean
  src/Lean/Meta/NatInstTesters.lean
  src/Lean/Meta/Offset.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Nat.lean
  tests/lean/621.lean
  tests/lean/621.lean.expected.out
  tests/lean/755.lean.expected.out
  tests/lean/951.lean
  tests/lean/951.lean.expected.out
  tests/lean/run/lcnf1.lean
  tests/lean/run/regressions3210.lean
  tests/lean/run/structWithAlgTCSynth.lean
  tests/lean/synthorder.lean.expected.out
Labels: builds-mathlib, toolchain-available, full-ci

#3801 feat: trace.profiler export to Firefox Profiler
  .github/workflows/copyright-header.yml
  script/collideProfiles.lean
  src/Lean/Compiler/Main.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Term.lean
  src/Lean/Message.lean
  src/Lean/PrettyPrinter.lean
  src/Lean/Util/Profiler.lean
  src/Lean/Util/Trace.lean
  src/Lean/Widget/InteractiveDiagnostic.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon

#3860 doc: docstrings for Alternative
  src/Init/Control/Basic.lean
Labels: documentation, toolchain-available

#3864 doc: docstrings for List.head/tail/getLast variants
  src/Init/Data/List/BasicAux.lean
Labels: documentation, toolchain-available

#3863 doc: add docstring to add_decl_doc
  src/Lean/Parser/Command.lean
Labels: documentation, toolchain-available

#3862 doc: instantiateMVars
  src/Lean/MetavarContext.lean
Labels: documentation, toolchain-available

#3897 doc: crosslink {realize,resolve}GlobalName[NoOverload]?[WithInfo]?,
  src/Lean/ReservedNameAction.lean
  src/Lean/ResolveName.lean
Labels: documentation, toolchain-available

#3898 feat: FunInd: reserve name `.mutual_induct`
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/funind_tests.lean
Labels: toolchain-available, will-merge-soon

#3849 feat: basic incrementality API
  src/Lean/CoreM.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/Term.lean
  src/Lean/Language/Basic.lean
  src/Lean/Language/Lean.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/Utils.lean
  src/Lean/Server/Snapshots.lean
Labels: builds-mathlib, toolchain-available, full-ci

#3847 feat: omega: more helpful error messages
  src/Init/Data/Repr.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  tests/lean/omega-failure.lean
  tests/lean/omega-failure.lean.expected.out
Labels: builds-mathlib, toolchain-available

#3924 chore: bring back tactic cache while incrementality is in-development
  src/Lean/Language/Lean.lean
Labels: builds-mathlib, toolchain-available

#3925 fix: do not send as many semantic token refresh requests
  src/Lean/Server/FileWorker.lean
Labels: builds-mathlib, toolchain-available

#3921 doc: fix docstring for `Lean.Meta.mkEqOfHEq`
  src/Lean/Meta/AppBuilder.lean
Labels: documentation, toolchain-available

#3833 doc: update release checklist based on experience with 4.7.0
  doc/dev/release_checklist.md
Labels: toolchain-available

#3859 doc: add doc-string for LawfulMonad/Applicative
  src/Init/Control/Lawful/Basic.lean
Labels: documentation, toolchain-available

#3865 chore: rename Option.toMonad and remove argument
  RELEASES.md
  src/Init/Data/Option/Basic.lean
Labels: toolchain-available

#3891 chore: move docstrings for open, variable, universe, export from elaborator to parser
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Parser/Command.lean
Labels: documentation, toolchain-available, will-merge-soon

#3890 feat: add lemma Int.add_bmod
  src/Init/Data/Int/DivModLemmas.lean
Labels: toolchain-available, will-merge-soon

#3917 doc: docstrings on binder types, make sure hovers work
  src/Lean/Parser/Term.lean
Labels: documentation, toolchain-available

#3931 fix: add unused variables ignore function for `#guard_msgs`
  src/Lean/Linter/UnusedVariables.lean
  tests/lean/run/guard_msgs.lean
Labels: toolchain-available

#3888 chore: Nat.repr microbenchmark
  tests/bench/nat_repr.lean
  tests/bench/nat_repr.lean.args
  tests/bench/nat_repr.lean.expected.out
  tests/bench/speedcenter.exec.velcom.yaml
Labels: builds-mathlib, toolchain-available

#3934 feat: make anonymous instance names not include proofs
  src/Lean/Elab/DeclNameGen.lean
Labels: builds-mathlib, toolchain-available

#3938 feat: make linter options more explicitly discoverable
  src/Lean/Linter/Util.lean
  tests/lean/linterMissingDocs.lean.expected.out
  tests/lean/linterSuspiciousUnexpanderPatterns.lean.expected.out
  tests/lean/linterUnusedVariables.lean.expected.out
  tests/lean/run/ext.lean
  tests/lean/run/guard_msgs.lean
  tests/lean/warningAsError.lean.expected.out
Labels: toolchain-available

#3932 fix: semantic tokens performance
  src/Lean/Data/Lsp/LanguageFeatures.lean
  src/Lean/Elab/App.lean
  src/Lean/Parser/Term.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
Labels: builds-mathlib, toolchain-available

#3916 fix: built-in parser attributes link to the wrong place
  src/Lean/Parser/Extension.lean
Labels: toolchain-available

#3930 feat: `isTty`
  src/Init/System/IO.lean
  src/runtime/io.cpp
Labels: builds-mathlib, toolchain-available, will-merge-soon, full-ci

#3912 feat: show diffs when #guard_msgs fails
  RELEASES.md
  src/Init/Data.lean
  src/Init/Data/Array/Subarray.lean
  src/Init/Data/Array/Subarray/Split.lean
  src/Lean/Elab/GuardMsgs.lean
  src/Lean/Util/Diff.lean
  tests/lean/run/diff.lean
  tests/lean/run/diff.lean.expected.out
  tests/lean/run/guard_msgs.lean
  tests/lean/run/subarray_split.lean
  tests/lean/run/subarray_split.lean.expected.out
Labels: builds-mathlib, toolchain-available

#3911 chore: remove @ from rw? suggestions, and enable hover on constants in #check
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Meta/Tactic/TryThis.lean
  src/Lean/PrettyPrinter.lean
  tests/lean/run/rewrites.lean
Labels: breaks-mathlib, toolchain-available

#3947 feat: upstream false_or_by_contra tests
  src/Lean/Elab/Tactic/FalseOrByContra.lean
Labels: toolchain-available

#3948 chore: update Authors: line in BitVec files
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#3949 feat: upstream false_or_by_contra tests (2nd attempt)
  tests/lean/run/false_or_by_contra.lean
Labels: toolchain-available

#3953 feat: @[builtin_doc] attribute (part 1)
  src/Lean/BuiltinDocAttr.lean
  src/Lean/Elab/Util.lean
  src/Lean/Parser/Extension.lean
Labels: toolchain-available

#3959 feat: String.Pos.isValid
  src/Init/Data/String/Basic.lean
  src/runtime/object.cpp
Labels: toolchain-available

#3960 fix: don't use modulo for UInt upcasting
  src/Init/Data/UInt/Basic.lean
Labels: breaks-mathlib, toolchain-available

#3958 feat: UTF-8 string validation
  src/Init/Data/String/Extra.lean
  src/Init/System/IO.lean
  src/Init/System/Uri.lean
  src/Lean/Data/Json/Stream.lean
  src/lake/tests/toml/Test.lean
  src/runtime/object.cpp
  src/runtime/utf8.cpp
  src/runtime/utf8.h
  tests/lean/run/utf8英語.lean
Labels: builds-mathlib, toolchain-available

#3964 fix: `ReducibilityHints.lt`
  src/Lean/Declaration.lean
Labels: toolchain-available

#3837 perf: improve heuristic at `isDefEq`
  src/Lean/Meta/ExprDefEq.lean
  tests/lean/run/3807.lean
Labels: toolchain-available

#3965 perf: improve `isDefEq` for contraints of the form `t.i =?= s.i`
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/WHNF.lean
  tests/lean/run/proj_delta_issue.lean
Labels: toolchain-available

#3966 chore: remove dead code at kernel `compare`
  src/kernel/declaration.cpp
Labels: toolchain-available

#3830 perf: ensure linearity in Parsec.many*Core
  src/Lean/Data/Parsec.lean
Labels: builds-mathlib, toolchain-available

#3590 feat: add `inductive.autoPromoteIndices` option
  src/Lean/Elab/Inductive.lean
  tests/lean/run/3458_1.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#3962 fix: solveByElim would add symm hypotheses to local context and make impossible-to-elaborate terms
  src/Lean/Meta/Tactic/SolveByElim.lean
  tests/lean/run/3922.lean
Labels: builds-mathlib, toolchain-available, full-ci

#3873 doc: section/namespace/end
  src/Lean/Parser/Command.lean
Labels: documentation, toolchain-available, will-merge-soon

#3908 doc: update `norm_cast` and `push_cast` documentation
  src/Init/Tactics.lean
Labels: documentation, awaiting-review, toolchain-available

#3871 doc: Classical.choice
  src/Init/Classical.lean
Labels: documentation, toolchain-available

#3882 chore: use compareLex in lexOrd
  src/Init/Data/Ord.lean
Labels: toolchain-available

#3951 refactor: make throwTacticEx parameter `msg` optional
  src/Lean/Elab/Tactic/Split.lean
  src/Lean/Message.lean
  src/Lean/Meta/Tactic/Assumption.lean
  src/Lean/Meta/Tactic/Contradiction.lean
  src/Lean/Meta/Tactic/Refl.lean
  src/Lean/Meta/Tactic/Util.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3954 chore: fix Util.Heartbeats module-doc
  src/Lean/Util/Heartbeats.lean
Labels: awaiting-review, toolchain-available

#3866 chore: deprecate Option.toBool in favour of Option.isSome
  src/Init/Control/Option.lean
  src/Init/Data/Option/Basic.lean
Labels: toolchain-available

#3872 doc: Command.set_option
  src/Lean/Parser/Command.lean
Labels: documentation, toolchain-available

#3961 feat: add model implementation for UTF8 enc/dec
  src/Init/Data/String/Extra.lean
  src/runtime/utf8.cpp
  tests/lean/run/utf8英語.lean
Labels: awaiting-review, breaks-mathlib, toolchain-available

#3939 feat: lean CLI option to print messages as JSON
  src/Lean/Data/Position.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Language/Basic.lean
  src/Lean/Message.lean
  src/util/shell.cpp
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3972 fix: `simp` caching
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  tests/lean/run/3943.lean
Labels: toolchain-available

#3971 chore: prevent stage0 changes via the merge queue
  .github/workflows/check-stage0.yml
Labels: awaiting-review, toolchain-available

#3957 fix: lake: package duplication in workspace
  src/lake/Lake/Load/Main.lean
  src/lake/examples/deps/bar/lake-manifest.expected.json
  src/lake/examples/deps/test.sh
Labels: builds-mathlib, toolchain-available, full-ci

#3968 feat: improve @[deprecated] attr
  doc/examples/Certora2022/ex8.lean
  doc/examples/ICERM2022/ctor.lean
  doc/examples/ICERM2022/meta.lean
  doc/examples/NFM2022/nfm8.lean
  src/Init/Notation.lean
  src/Lean/Attributes.lean
  src/Lean/Linter/Deprecated.lean
  tests/lean/deprecated.lean
  tests/lean/deprecated.lean.expected.out
Labels: awaiting-author, toolchain-available

#3977 fix: improve `isDefEqProj`
  src/Lean/Meta/ExprDefEq.lean
  tests/lean/run/3965.lean
  tests/lean/run/3965_2.lean
Labels: toolchain-available

#3978 feat: make `pp.mvars false` pretty print universe mvars as `_`
  RELEASES.md
  src/Lean/Level.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  tests/lean/run/ppMVars.lean
Labels: awaiting-review, toolchain-available

#3768 feat: `#print` command shows structure fields
  src/Lean/Elab/Print.lean
  tests/lean/diamond1.lean.expected.out
  tests/lean/diamond8.lean.expected.out
  tests/lean/printStructure.lean
  tests/lean/printStructure.lean.expected.out
  tests/lean/structAutoBound.lean.expected.out
Labels: awaiting-review, toolchain-available

#3975 chore: upstream Std material from Data/List|Array/Init
  CODEOWNERS
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available, will-merge-soon

#3075 feat: improvements to test_extern command
  src/Lean/Util/TestExtern.lean
  tests/lean/run/utf8英語.lean
  tests/lean/test_extern.lean
  tests/lean/test_extern.lean.expected.out
Labels: awaiting-review, toolchain-available

#3952 feat: script to summarize issues
  script/issues_summary.sh
Labels: toolchain-available

#3919 doc: docstrings for List.rotateRight/Left and example for List.partitionM
  src/Init/Data/List/BasicAux.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#3942 fix: add instances to make ac_rfl work out of the box
  src/Init/Core.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Gcd.lean
  src/Init/Data/Nat/Lcm.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Nat/MinMax.lean
  src/Init/SimpLemmas.lean
  tests/lean/run/ac_rfl.lean
Labels: toolchain-available, will-merge-soon

#3979 chore: ci to set “changes-stage0” label
  .github/workflows/check-stage0.yml
  doc/dev/bootstrap.md
Labels: toolchain-available

#3946 fix: use `Name.appendCore` instead of `Name.append` in `unresolveNameGlobal`
  src/Init/Prelude.lean
  src/Lean/ResolveName.lean
  tests/lean/run/2291.lean
Labels: awaiting-review, toolchain-available

#3981 feat: universe constraint approximations
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/LevelDefEq.lean
  src/Lean/Meta/SynthInstance.lean
  tests/lean/run/3965.lean
  tests/lean/run/univCnstrApprox.lean
Labels: toolchain-available

#3992 chore: CI: pin macos-13
  .github/workflows/ci.yml
Labels: toolchain-available, full-ci

#4005 chore: remove dead code at `Structure.lean`
  src/Lean/Elab/Structure.lean
Labels: toolchain-available

#4004 perf: `isDefEqProj`
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/SynthInstance.lean
  tests/lean/run/3965_3.lean
Labels: toolchain-available, full-ci

#4007 fix: `match_expr` parser
  src/Lean/Parser/Term.lean
  tests/lean/3989_1.lean
  tests/lean/3989_1.lean.expected.out
  tests/lean/3989_2.lean
  tests/lean/3989_2.lean.expected.out
Labels: toolchain-available

#4006 fix: proposition fields must be theorems
  src/Lean/Elab/StructInst.lean
  src/Lean/Elab/Structure.lean
  src/kernel/declaration.cpp
  src/kernel/declaration.h
  src/library/constructions/projection.cpp
  tests/lean/run/2575.lean
Labels: toolchain-available

#4008 chore: add backward compatibility option for TC optimization
  src/Lean/Meta/SynthInstance.lean
Labels: toolchain-available, full-ci

#4009 chore: code convention
  src/Lean/Meta/ExprLens.lean
  src/Lean/SubExpr.lean
Labels: toolchain-available

#4014 chore: move `trace.cpp` to kernel
  src/kernel/CMakeLists.txt
  src/kernel/init_module.cpp
  src/kernel/trace.cpp
  src/kernel/trace.h
  src/library/CMakeLists.txt
  src/library/compiler/borrowed_annotation.cpp
  src/library/compiler/compiler.cpp
  src/library/compiler/csimp.cpp
  src/library/compiler/eager_lambda_lifting.cpp
  src/library/compiler/extract_closed.cpp
  src/library/compiler/ir.cpp
  src/library/compiler/ir_interpreter.cpp
  src/library/compiler/lambda_lifting.cpp
  src/library/compiler/llnf.cpp
  src/library/compiler/specialize.cpp
  src/library/compiler/struct_cases_on.cpp
  src/library/compiler/util.cpp
  src/library/init_module.cpp
  src/library/time_task.cpp
  src/util/shell.cpp
Labels: toolchain-available

#4012 chore: add backward compatibility flags for recent `isDefEq` changes
  src/Lean/Meta/ExprDefEq.lean
  tests/lean/run/isDefEqProjIssue.lean
Labels: toolchain-available

#3994 fix: subst notation (heq ▸ h) should fail if it does't subst
  src/Lean/Elab/BuiltinNotation.lean
  tests/lean/substFails.lean
  tests/lean/substFails.lean.expected.out
Labels: builds-mathlib, toolchain-available

#4010 feat: use structural recursion in Fin.induction
  src/Init/Data/Fin/Lemmas.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4016 feat: add `set_option diag true` for diagnostic counters
  src/Lean/Compiler/ExternAttr.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/BuiltinTerm.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/InfoTree/Main.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/LazyDiscrTree.lean
  src/Lean/Meta/WHNF.lean
  src/Lean/PrettyPrinter.lean
  src/Lean/Replay.lean
  src/lake/Lake/CLI/Translate.lean
  src/lake/Lake/Toml/Load.lean
Labels: toolchain-available

#4018 fix: theorems should never be marked as `extern`
  src/Lean/Compiler/ExternAttr.lean
Labels: toolchain-available

#4019 feat: `set_option diag true` tracks how many times an instance is used
  src/Lean/CoreM.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/SynthInstance.lean
Labels: toolchain-available

#4020 feat: `set_option diag true` tracks recursor reduction
  src/Lean/Meta/WHNF.lean
  tests/lean/run/diagRec.lean
Labels: toolchain-available

#4021 chore: disable #4006
  src/library/constructions/projection.cpp
  tests/lean/run/2575.lean
Labels: toolchain-available, full-ci

#4024 test: add guard_msgs to wfEqns tests
  tests/lean/run/wfEqns1.lean
  tests/lean/run/wfEqns2.lean
  tests/lean/run/wfEqns3.lean
  tests/lean/run/wfEqns4.lean
  tests/lean/run/wfEqns5.lean
Labels: toolchain-available, will-merge-soon

#3991 perf: use with_reducible in special-purpose decreasing_trivial macros
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/BasicAux.lean
  src/Init/Data/Array/DecidableEq.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Mem.lean
  src/Init/Data/Array/QSort.lean
  src/Init/Data/Fin/Fold.lean
  src/Init/Data/Fin/Iterate.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/String/Extra.lean
  src/Init/Meta.lean
  src/Init/WFTactics.lean
  src/Lean/Data/HashMap.lean
  src/Lean/Data/HashSet.lean
  src/Lean/Meta/Tactic/LinearArith/Solver.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4028 fix: double `reset` bug at `ResetReuse`
  src/Lean/Compiler/IR/RC.lean
  src/Lean/Compiler/IR/ResetReuse.lean
  tests/lean/doubleReset.lean
  tests/lean/doubleReset.lean.expected.out
Labels: toolchain-available, full-ci

#3999 chore: lake: error on package name mismatch + std special case
  src/lake/Lake/Load/Main.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4030 chore: rename `set_option diag true` to `set_option diagnostics true`
  src/Lean/CoreM.lean
  src/Lean/Meta/Basic.lean
  tests/lean/run/diagRec.lean
Labels: toolchain-available

#4031 feat: improve `set_option diagnostics true`
  src/Lean/Elab/Command.lean
  src/Lean/Meta.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Diagnostics.lean
  src/Lean/Meta/Instances.lean
  src/Lean/ReducibilityAttrs.lean
  tests/lean/run/diagRec.lean
Labels: toolchain-available

#4035 fix: mismatch between `TheoremVal` in Lean and C++
  src/Lean/Declaration.lean
  src/kernel/declaration.cpp
  src/kernel/declaration.h
Labels: toolchain-available

#4038 chore: restore #4006
  src/library/constructions/projection.cpp
  tests/lean/run/2575.lean
Labels: toolchain-available

#4039 chore: remove @[simp] from BitVec.of_length_zero
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available
