Repository leanprover/lean4, pull requests merged in 2024-01, with the labels that each got.

#3116 feat: delaborate `have` inside `do` blocks
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/delabDoLetFun.lean
  tests/lean/delabDoLetFun.lean.expected.out
Labels: toolchain-available

#3131 doc: fix typo “reursive”
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
Labels: toolchain-available

#2539 feat: do not instantiate metavariables in kabstract/rw for disallowed occurrences
  src/Init/Tactics.lean
  src/Lean/Meta/KAbstract.lean
  tests/lean/interactive/1403.lean.expected.out
  tests/lean/rewrite.lean
  tests/lean/rewrite.lean.expected.out
Labels: awaiting-review, builds-mathlib, toolchain-available

#3138 chore: Netlify deployment for manual
  .github/workflows/nix-ci.yml
Labels: toolchain-available

#3139 fix: reduceNat? match terms with free or meta variables
  src/Lean/Meta/WHNF.lean
  tests/elabissues/reduceNatWithMeta.lean
Labels: toolchain-available

#3137 chore: pr-release.yaml: indicate information using github status
  .github/workflows/pr-release.yml
Labels: builds-mathlib, toolchain-available

#3132 feat: let get_elem_tactic_trivial handle [a]'h.2
  src/Init/Data/Range.lean
  src/Lean/Data/Array.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/Rel.lean
  tests/lean/getElem.lean
Labels: toolchain-available, will-merge-soon

#3148 chore: pr-release.yml: Suggest `nightly-with-mathlib`
  .github/workflows/pr-release.yml
Labels: toolchain-available, will-merge-soon

#3058 fix: manage all declarations in a given derive
  src/Lean/Elab/Deriving/BEq.lean
  src/Lean/Elab/Deriving/DecEq.lean
  src/Lean/Elab/Deriving/FromToJson.lean
  src/Lean/Elab/Deriving/Hashable.lean
  src/Lean/Elab/Deriving/Ord.lean
  src/Lean/Elab/Deriving/Repr.lean
  src/Lean/Elab/Deriving/SizeOf.lean
  tests/lean/3057.lean
  tests/lean/3057.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3147 doc: Document that `Float` corresponds to 64-bit `double` in C
  src/Init/Data/Float.lean
Labels: toolchain-available, will-merge-soon

#3133 refactor: WF.Eqns: remove unreachable fix-folding
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3154 chore: fix typo from #3148 in pr-release bot
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3157 doc: state that `Float` is IEEE compliant
  src/Init/Data/Float.lean
Labels: toolchain-available

#3083 feat: extract `delabAppCore`, define `withOverApp`, and make over-applied projections pretty print
  src/Lean/Expr.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/SubExpr.lean
  src/Lean/Widget/InteractiveCode.lean
  tests/lean/283.lean.expected.out
  tests/lean/439.lean.expected.out
  tests/lean/delabApp.lean
  tests/lean/delabApp.lean.expected.out
  tests/lean/eagerCoeExpansion.lean.expected.out
  tests/lean/ppMotives.lean.expected.out
  tests/lean/sorryAtError.lean.expected.out
Labels: builds-mathlib, toolchain-available

#2994 fix: do not strip dotted components from lean module names
  src/Init/System/FilePath.lean
  src/Lean/Server/Watchdog.lean
  src/Lean/Util/Path.lean
  src/lake/Lake/CLI/Init.lean
  src/lake/Lake/Config/InstallPath.lean
  src/lake/Lake/Config/LeanExe.lean
  src/lake/tests/init/.gitignore
  src/lake/tests/init/clean.sh
  src/lake/tests/init/test.sh
  tests/lean/filePath.lean
  tests/lean/filePath.lean.expected.out
Labels: builds-mathlib, toolchain-available, full-ci

#3158 chore: actually include full build in benchmark
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#3016 doc: mention termination_by and decreasing_by
  doc/declarations.md
  doc/functions.md
Labels: toolchain-available, will-merge-soon

#3149 feat: `lake update` from unsupported manifest versions
  src/lake/Lake/Load/Main.lean
  src/lake/Lake/Load/Manifest.lean
  src/lake/tests/manifest/lake-manifest-v4.json
  src/lake/tests/manifest/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3134 feat: add bitwise operations to reduceNat? and kernel
  src/Lean/Meta/WHNF.lean
  src/kernel/type_checker.cpp
  tests/elabissues/reduceNatWithMeta.lean
  tests/lean/run/lean_nat_bitwise.lean
Labels: builds-mathlib, toolchain-available

#3165 chore: use more specific import in OfScientific
  src/Init/Data/OfScientific.lean
Labels: builds-mathlib, toolchain-available

#3164 chore: use termination_by in Nat.gcd
  src/Init/Data/Nat/Gcd.lean
Labels: builds-mathlib, toolchain-available

#3169 chore: pr-release.yml: parentheses are significant in jq
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3173 chore: pr-release: more robust comment id recognition
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3176 fix: Fix/GuessLex: refine through more casesOnApp/matcherApp
  src/Lean/Elab/PreDefinition/WF/Fix.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  tests/lean/run/issue3175.lean
  tests/lean/treeMap.lean.expected.out
Labels: builds-mathlib, toolchain-available

#3180 feat: lake: GNU/BSD OS detection in test scripts
  src/lake/tests/buildArgs/test.sh
  src/lake/tests/clone/test.sh
  src/lake/tests/depTree/test.sh
  src/lake/tests/init/test.sh
  src/lake/tests/lock/test.sh
  src/lake/tests/manifest/test.sh
  src/lake/tests/serve/test.sh
  src/lake/tests/toolchain/test.sh
  tests/ir/lirc
Labels: toolchain-available

#3178 doc: fix typos
  src/Init/Prelude.lean
  src/Lean/Expr.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Eqns.lean
Labels: builds-mathlib, toolchain-available

#3156 chore: CI: add actionlint action, fix actions
  .github/workflows/actionlint.yml
  .github/workflows/ci.yml
  .github/workflows/pr-release.yml
Labels: toolchain-available

#3189 test: failed to infer implicit target
  tests/lean/indimpltarget.lean
  tests/lean/indimpltarget.lean.expected.out
Labels: toolchain-available

#3191 fix: `derive BEq` on structure with `Prop`-fields
  src/Lean/Elab/Deriving/BEq.lean
  src/Lean/Elab/Deriving/DecEq.lean
  tests/lean/3140.lean
  tests/lean/3140.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3171 fix: `checkTargets` check for duplicate target
  src/Lean/Elab/Tactic/Induction.lean
  tests/lean/inductionGen.lean
  tests/lean/inductionGen.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3197 fix: reducing out-of-bounds swap! should return `a`, not `default`
  src/Init/Data/Array/Basic.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3199 chore: CI looks for nightly-testing-YYYY-MM-DD at Mathlib as either a branch or tag
  .github/workflows/pr-release.yml
Labels: awaiting-review, toolchain-available

#3183 doc: clarify and expand docstrings for the `instantiate` functions
  src/Lean/Expr.lean
Labels: documentation, builds-mathlib, toolchain-available, will-merge-soon

#3200 chore: CI creates lean-pr-testing-NNNN branches at Std too
  .github/workflows/pr-release.yml
Labels: awaiting-review, toolchain-available

#3205 doc: update RELEASES.md for #3159
  RELEASES.md
Labels: toolchain-available

#2900 feat: make `mkApp`, `mkApp2`, ..., `mkApp10` have `@[match_pattern]` attribute
  src/Lean/Expr.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#3060 fix: allow generalization in let
  src/Lean/Elab/Do.lean
  tests/lean/run/doLetElse.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#3204 fix: predefinition preprocessing: float .mdata out of non-unary applications
  src/Lean/Elab/PreDefinition/Structural/Preprocess.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/PreDefinition/WF/Preprocess.lean
  tests/lean/run/2810.lean
  tests/lean/run/issue3204.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3207 feat: System.Platform.target
  .github/workflows/ci.yml
  src/CMakeLists.txt
  src/Init/Data/UInt/Basic.lean
  src/Init/System/Platform.lean
  src/include/lean/lean.h
  src/library/util.cpp
  src/version.h.in
Labels: toolchain-available, full-ci

#3195 feat: cleanups to ACI and Identity classes
  src/Init/Core.lean
  src/Init/Data/AC.lean
  src/Init/Tactics.lean
  src/Lean/Meta/Tactic/AC/Main.lean
  tests/lean/run/1202.lean
  tests/lean/run/ac_rfl.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, full-ci

#3216 fix: broken internal links in the docs
  .github/workflows/nix-ci.yml
  doc/functions.md
  doc/make/index.md
  doc/metaprogramming-arith.md
  doc/tour.md
  doc/whatIsLean.md
Labels: toolchain-available

#3013 feat: synchronous execution of task continuations
  src/Init/Core.lean
  src/Init/System/IO.lean
  src/include/lean/lean.h
  src/runtime/io.cpp
  src/runtime/object.cpp
  src/runtime/object.h
Labels: builds-mathlib, toolchain-available

#3082 feat: add call hierarchy support
  RELEASES.md
  src/Lean/Data/HashMap.lean
  src/Lean/Data/Lsp/Capabilities.lean
  src/Lean/Data/Lsp/Internal.lean
  src/Lean/Data/Lsp/LanguageFeatures.lean
  src/Lean/Data/Lsp/Utf16.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/GoTo.lean
  src/Lean/Server/References.lean
  src/Lean/Server/Watchdog.lean
  tests/lean/linterUnusedVariables.lean
  tests/lean/linterUnusedVariables.lean.expected.out
Labels: server, builds-mathlib, toolchain-available

#3188 feat: induction using <term>
  src/Init/Tactics.lean
  src/Lean/Elab/App.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Elab/Term.lean
  src/Lean/Meta/AbstractMVars.lean
  src/Lean/Meta/Tactic/ElimInfo.lean
  tests/lean/indUsingTerm.lean
  tests/lean/indUsingTerm.lean.expected.out
  tests/lean/indimpltarget.lean
  tests/lean/indimpltarget.lean.expected.out
  tests/lean/inductionErrors.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3203 refactor: fuse nested mkCongrArg calls
  src/Lean/Meta/AppBuilder.lean
  tests/lean/simpZetaFalse.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3218 doc: update link target
  doc/metaprogramming-arith.md
Labels: toolchain-available

#3220 doc: adjust RELEASES.md call hierarchy url
  RELEASES.md
Labels: documentation, toolchain-available

#3224 fix: do not throw C++ heartbeat exceptions in pure functions
  src/runtime/interrupt.cpp
  src/runtime/interrupt.h
Labels: toolchain-available, will-merge-soon

#2777 doc: expand docstring for `intros`
  src/Init/Tactics.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#3235 chore: add GitHub token to manual link checker
  .github/workflows/nix-ci.yml
Labels: toolchain-available

#3115 feat: make `intro` be aware of `let_fun`
  src/Lean/Meta/Tactic/Intro.lean
  tests/lean/run/introLetFun.lean
Labels: builds-mathlib, toolchain-available

#3217 chore: remove unused GH Pages deployment
  .github/workflows/nix-ci.yml
Labels: toolchain-available

#3230 refactor: forallAltTelescope to take altNumParams
  src/Lean/Meta/Match/MatchEqs.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#3201 feat: elidible subterms
  RELEASES.md
  src/Init/NotationExtra.lean
  src/Lean/Elab/InfoTree/Main.lean
  src/Lean/Elab/InfoTree/Types.lean
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  src/Lean/Server/FileWorker/WidgetRequests.lean
  src/Lean/Server/InfoUtils.lean
  tests/lean/run/deepTerms.lean
  tests/lean/run/deepTerms.lean.expected.out
Labels: builds-mathlib, toolchain-available, full-ci

#3184 feat: `@[unused_variables_ignore_fn]` attribute
  src/Lean/Linter/UnusedVariables.lean
  tests/lean/linterUnusedVariables.lean
  tests/lean/linterUnusedVariables.lean.expected.out
Labels: builds-mathlib, toolchain-available, full-ci

#3221 doc: add doc for FileMap
  src/Lean/Data/Position.lean
Labels: toolchain-available
