Repository leanprover/lean4, pull requests merged in 2024-06, with the labels that each got.

#4314 chore: remove @[simp] from bind_eq_some
  src/Init/Data/Option/Lemmas.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4299 feat: add BitVec _assoc lemmas
  src/Init/Data/BitVec/Lemmas.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4317 doc: updated build instructions for mac os X
  doc/make/osx-10.9.md
Labels: documentation

#4257 feat: getLsb_{rotateLeft, rotateRight}
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#4179 feat: getLsb_sshiftRight
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/Bitwise/Lemmas.lean
  src/Init/Data/Int/DivModLemmas.lean
Labels: toolchain-available

#4177 feat: simp to still work even if one simp arg does not work
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Elab/Util.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  tests/lean/eraseSimp.lean.expected.out
  tests/lean/interactive/plainGoal.lean.expected.out
  tests/lean/run/simproc1.lean
Labels: awaiting-review, toolchain-available, new-user-papercuts

#4335 fix: partial `calc` tactic would fail due to mdata or uninstantiated mvars
  src/Lean/Elab/Tactic/Calc.lean
  tests/lean/run/4334.lean
Labels: toolchain-available

#4333 chore: update batteries in manifest when creating lean-pr-testing-NNNN at Mathlib
  .github/workflows/pr-release.yml
Labels: toolchain-available

#4338 doc: improve docstrings for `repeat*` tactics
  src/Init/Tactics.lean
Labels: toolchain-available

#4321 chore: deprecate shiftLeft_shiftLeft, shiftRight_shiftRight
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
Labels: awaiting-review, toolchain-available

#4308 feat: incremental `have`
  src/Init/Data/Format/Syntax.lean
  src/Init/Tactics.lean
  src/Lean/Elab/Deriving/DecEq.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Language/Basic.lean
  tests/lean/interactive/haveInfo.lean
  tests/lean/interactive/haveInfo.lean.expected.out
  tests/lean/interactive/incrementalCombinator.lean
  tests/lean/interactive/incrementalCombinator.lean.expected.out
Labels: toolchain-available

#4340 fix: incorrect info tree reuse
  src/Lean/CoreM.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Term.lean
  src/Lean/Meta/Basic.lean
  tests/lean/interactive/incrementalMutual.lean
  tests/lean/interactive/incrementalMutual.lean.expected.out
Labels: toolchain-available

#4341 fix: panic when applying `@[simp]` to malformed theorem syntax
  src/Lean/Elab/Term.lean
  tests/lean/4309.lean
  tests/lean/4309.lean.expected.out
Labels: toolchain-available

#4342 fix: mutual inductives with instance parameters
  src/Lean/Elab/DeclUtil.lean
  src/Lean/Elab/Level.lean
  tests/lean/run/4310.lean
Labels: toolchain-available

#4346 test: lake: more robust `tests/serve`
  src/lake/tests/serve/.gitignore
  src/lake/tests/serve/clean.sh
  src/lake/tests/serve/test.sh
Labels: toolchain-available

#4345 fix: `simp` must not use the forward version of an user-specified backward theorem
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  tests/lean/run/4290.lean
Labels: toolchain-available

#4348 chore: upstream Char lemmas from Mathlib
  src/Init/Data/Char/Basic.lean
  src/Init/Data/Char/Lemmas.lean
Labels: toolchain-available

#4343 fix: lake: track trace of cached build logs
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/Trace.lean
  src/lake/Lake/Load/Elab.lean
  src/lake/tests/reversion/Hello.lean
  src/lake/tests/reversion/Main.lean
  src/lake/tests/reversion/clean.sh
  src/lake/tests/reversion/lakefile.lean
  src/lake/tests/reversion/test.sh
Labels: toolchain-available, backport releases/v4.8.0, release-ci

#4344 [Backport releases/v4.8.0] refactor: lake: ensure job actions can be lifted to `FetchM`
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Basic.lean
  src/lake/Lake/Build/Fetch.lean
  src/lake/Lake/Build/Job.lean
  src/lake/Lake/Build/Trace.lean
  src/lake/Lake/Util/IO.lean
Labels: toolchain-available

#4352 fix: missing `dsimp` simplification when applying auto-congr theorems
  src/Lean/Meta/Tactic/Simp/Types.lean
  tests/lean/run/4339.lean
Labels: toolchain-available

#4353 fix: lake: track trace of cached build logs (#4343) [Backport releases/v4.8.0]
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/Trace.lean
  src/lake/Lake/Load/Elab.lean
  src/lake/tests/reversion/Hello.lean
  src/lake/tests/reversion/Main.lean
  src/lake/tests/reversion/clean.sh
  src/lake/tests/reversion/lakefile.lean
  src/lake/tests/reversion/test.sh
Labels: toolchain-available

#4351 perf: lake: fix `LogIO` inling/lifting
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/Util/Cli.lean
  src/lake/Lake/Util/Lift.lean
  src/lake/Lake/Util/Log.lean
  src/lake/Lake/Util/MainM.lean
Labels: toolchain-available

#4355 chore: simplify lean4checker step in release checklist
  doc/dev/release_checklist.md
Labels: toolchain-available

#4350 chore: apply naming convention to `IsLawfulSingleton`
  src/Init/Core.lean
Labels: toolchain-available

#4349 fix: `split` (for `if`-expressions) should work on non-propositional goals
  src/Init/Data/AC.lean
  src/Init/Data/Array/DecidableEq.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/System/IO.lean
  src/Lean/Meta/Tactic/Cases.lean
  src/Lean/Meta/Tactic/SplitIf.lean
  src/lake/Lake/Util/Compare.lean
  tests/lean/run/4313.lean
Labels: toolchain-available

#4187 feat: getLsb_signExtend
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-review, toolchain-available

#4332 doc: add docstrings and examples for `String` functions
  src/Init/Data/String/Basic.lean
  tests/lean/run/string.lean
Labels: toolchain-available, release-ci

#4358 chore: use match_expr in omega
  src/Lean/Elab/Tactic/Omega/Frontend.lean
Labels: toolchain-available

#4329 fix: GuessLex: delaborate unused parameters as _
  src/Lean/Elab/PreDefinition/WF/TerminationArgument.lean
  tests/lean/run/4230.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon, release-ci

#4327 fix: FunInd: support structural recursion on reflexive types
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/ReservedNameAction.lean
  tests/lean/run/4320.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon, release-ci

#4359 fix: without recover bad simp arg should fail
  src/Lean/Elab/Tactic/Simp.lean
  tests/lean/interactive/plainGoal.lean.expected.out
  tests/lean/run/simp-elab-recover.lean
Labels: toolchain-available

#4361 chore: CI: pr-release: install elan
  .github/workflows/pr-release.yml
Labels: toolchain-available, will-merge-soon

#4362 feat: ppOrigin to use MessageData.ofConst
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  tests/lean/1079.lean.expected.out
  tests/lean/973b.lean.expected.out
  tests/lean/discrTreeIota.lean.expected.out
  tests/lean/run/1234.lean
  tests/lean/run/1380.lean
  tests/lean/run/1815.lean
  tests/lean/run/3257.lean
  tests/lean/run/790.lean
  tests/lean/simp_trace.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4364 feat: incrementality for careful command macros such as `set_option in theorem`, `theorem foo.bar`, `lemma`
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Language/Basic.lean
  src/Lean/Language/Lean.lean
  tests/lean/interactive/incrementalMutual.lean
  tests/lean/interactive/incrementalMutual.lean.expected.out
  tests/lean/shadow.lean.expected.out
Labels: toolchain-available

#4356 chore: lake: add build log file path to warning
  src/lake/Lake/Build/Common.lean
Labels: toolchain-available, will-merge-soon

#4354 chore: upstream basic String lemmas
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/String/Basic.lean
  src/Init/Data/String/Extra.lean
Labels: toolchain-available

#4368 feat: improve error messages for numerals
  src/Lean/Elab/App.lean
  src/Lean/Elab/BuiltinTerm.lean
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Elab/Term.lean
  tests/lean/1163.lean
  tests/lean/297.lean.expected.out
  tests/lean/345.lean
  tests/lean/run/1163.lean
  tests/lean/run/345.lean
  tests/lean/run/4365.lean
  tests/lean/run/guard_msgs.lean
Labels: toolchain-available

#4369 chore: missing `registerTraceClass`
  src/Lean/Elab/Binders.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Quotation.lean
  src/Lean/Elab/StructInst.lean
  src/Lean/Elab/Syntax.lean
  src/Lean/Elab/Term.lean
  src/Lean/Meta/DecLevel.lean
  src/Lean/Meta/SizeOf.lean
  src/Lean/Meta/Tactic/Simp/SimpAll.lean
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
Labels: toolchain-available

#4374 chore: begin development cycle for v4.10.0
  RELEASES.md
  src/CMakeLists.txt
Labels: toolchain-available

#4370 fix: `variable` must execute pending tactics and elaboration problems
  src/Lean/Elab/BuiltinCommand.lean
  tests/lean/run/2226.lean
  tests/lean/run/3214.lean
Labels: builds-mathlib, toolchain-available, release-ci

#4380 chore: remove partial TODO
  src/Lean/Level.lean
Labels: toolchain-available

#4382 perf: remove `@[inline]` from `NameMap.find?`
  src/Lean/Data/NameMap.lean
Labels: builds-mathlib, toolchain-available

#4377 chore: clear releases_drafts for start of 4.10.0
  releases_drafts/messagedata.md
  releases_drafts/wf.md
Labels: toolchain-available

#4389 chore: upstream @[simp] attribute
  src/Init/Data/Array/Basic.lean
Labels: toolchain-available

#4399 chore: make Array.reverse_data proof more robust
  src/Init/Data/Array/Lemmas.lean
Labels: toolchain-available

#4401 fix: improve `split` discriminant generalization strategy
  src/Lean/Elab/Tactic/Split.lean
  src/Lean/Meta/Tactic/Split.lean
  tests/lean/run/4390.lean
Labels: builds-mathlib, toolchain-available

#4372 perf: linearity in HashMap.(insert|erase)
  src/Lean/Data/HashMap.lean
  src/Lean/Data/HashSet.lean
Labels: builds-mathlib, toolchain-available

#4403 fix: misleading type at `Option.forM`
  src/Init/Data/Option/Instances.lean
Labels: toolchain-available

#4384 refactor: lake: `inputBinFile` / `inputTextFile`
  src/lake/Lake/Build/Common.lean
  src/lake/examples/ffi/lib/lakefile.lean
  src/lake/examples/targets/lakefile.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4395 fix: incremental reuse leading to goals in front of the text cursor being shown
  src/Lean/Elab/Command.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Term.lean
  src/Lean/Syntax.lean
  tests/lean/interactive/incrementalTactic.lean
  tests/lean/interactive/incrementalTactic.lean.expected.out
Labels: toolchain-available

#4407 fix: non-incremental command blocking further incremental reporting in macro
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Language/Basic.lean
Labels: toolchain-available

#4416 feat: order the output of #print axioms
  src/Lean/Elab/Print.lean
Labels: builds-mathlib, toolchain-available

#4410 fix: kernel exception from fvars left from `?m a b` instantiation
  src/Lean/MetavarContext.lean
  tests/lean/4375.lean
  tests/lean/4375.lean.expected.out
Labels: builds-mathlib, toolchain-available

#4408 fix: universe parameter order discrepancy between `theorem` and `def`
  src/Lean/Elab/DeclUtil.lean
  src/Lean/Elab/Term.lean
  tests/lean/run/3965.lean
  tests/lean/run/4171.lean
  tests/lean/run/univParamIssue.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4420 fix: occurs check at metavariable types
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/MetavarContext.lean
  tests/lean/run/4405.lean
  tests/lean/run/typeOccursCheckIssue.lean
Labels: builds-mathlib, toolchain-available, release-ci

#4385 fix: `rw` should not include existing goal metavariables in the resulting subgoals
  src/Lean/Meta/Tactic/Rewrite.lean
  tests/lean/run/4381.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4357 chore: unify `String.csize : Nat` and `Char.utf8Size : UInt32` as `Char.size : Nat`
  src/Init/Data/Char/Lemmas.lean
  src/Init/Data/String/Basic.lean
  src/Init/Data/String/Extra.lean
  src/Init/Prelude.lean
Labels: toolchain-available, will-merge-soon, full-ci

#4421 perf: a `isDefEq` friendly `Fin.sub`
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Omega/Int.lean
  tests/lean/run/4413.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4428 fix: missing `simproc` for `BitVec` equality
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  tests/lean/run/bitvec_simproc.lean
Labels: toolchain-available

#4430 feat: `dsimproc`s for `ite` and `dite`
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Core.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  tests/lean/run/ite_dsimproc.lean
Labels: toolchain-available

#4431 chore: fix typo in trace.split.failure error message
  src/Lean/Elab/Tactic/Split.lean
  tests/lean/run/4390.lean
Labels: toolchain-available

#4436 fix: tactics in terms in tactics may break incremental reporting
  src/Lean/Elab/SyntheticMVars.lean
  tests/lean/interactive/incrementalTactic.lean
  tests/lean/interactive/incrementalTactic.lean.expected.out
Labels: toolchain-available, backport releases/v4.9.0

#4427 chore: CI: use Namespace runners
  .github/workflows/ci.yml
  .github/workflows/nix-ci.yml
  flake.nix
Labels: toolchain-available

#4371 refactor: lake: simplify load code
  src/lake/Lake/CLI/Translate.lean
  src/lake/Lake/Config/Monad.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/Lake/Load.lean
  src/lake/Lake/Load/Lean.lean
  src/lake/Lake/Load/Lean/Elab.lean
  src/lake/Lake/Load/Lean/Eval.lean
  src/lake/Lake/Load/Main.lean
  src/lake/Lake/Load/Materialize.lean
  src/lake/Lake/Load/Package.lean
  src/lake/Lake/Load/Resolve.lean
  src/lake/Lake/Load/Toml.lean
  src/lake/Lake/Load/Workspace.lean
  src/lake/Lake/Util/StoreInsts.lean
  src/lake/tests/order/bar/lakefile.lean
  src/lake/tests/order/clean.sh
  src/lake/tests/order/foo/lakefile.lean
  src/lake/tests/order/lakefile.lean
  src/lake/tests/order/leaf/Z.lean
  src/lake/tests/order/leaf/lakefile.lean
  src/lake/tests/order/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon, release-ci

#4440 chore: CI: fix speedcenter tests
  .github/workflows/ci.yml
  .github/workflows/nix-ci.yml
Labels: toolchain-available, release-ci

#4441 chore: CI: fix workflow change breaking unrebased PRs
  .github/workflows/ci.yml
Labels: toolchain-available

#4442 chore: CI: fix Wasm release-ci
  .github/workflows/ci.yml
Labels: toolchain-available, release-ci

#4425 fix: redundant and wrong case in `forEachModuleInDir`
  src/Lean/Util/Path.lean
Labels: toolchain-available

#4424 fix: bad 'unknown package' error message
  src/Lean/Util/Path.lean
  src/lake/tests/badImport/test.sh
Labels: toolchain-available

#3886 feat: support Lake for building Lean core oleans
  .gitignore
  doc/examples/compiler/.gitignore
  script/lib/update-stage0
  src/CMakeLists.txt
  src/lakefile.toml.in
  src/stdlib.make.in
  tests/compiler/foreign/.gitignore
Labels: builds-mathlib, toolchain-available, release-ci

#4446 chore: `src/lake/lakefile.toml`
  src/lake/lakefile.lean
  src/lake/lakefile.toml
Labels: toolchain-available

#4402 feat: lake: reliably cache logs and hashes
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/Trace.lean
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Util/IO.lean
Labels: builds-mathlib, toolchain-available, release-ci, backport releases/v4.9.0

#4454 chore: make `Name.isInternalDetail` public, to remove duplication downstream
  src/Lean/Data/Name.lean
  src/Lean/Meta/LazyDiscrTree.lean
Labels: toolchain-available

#3056 chore: prefer `· == a` over `a == ·`
  src/Init/Data/Array/Basic.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Prelude.lean
  tests/lean/run/wfOverapplicationIssue.lean
Labels: toolchain-available

#4301 feat: add a linter for local vars that clash with their constructors
  releases_drafts/varCtorNameLint.md
  src/Lean/Data/Lsp/LanguageFeatures.lean
  src/Lean/Data/SMap.lean
  src/Lean/Elab/PatternVar.lean
  src/Lean/Linter.lean
  src/Lean/Linter/ConstructorAsVariable.lean
  src/Lean/Meta/Tactic/AC/Main.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  tests/lean/autoImplicitChain.lean
  tests/lean/inductionMutual.lean
  tests/lean/run/constructor_as_variable.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon, release-ci

#4451 perf: replace `hasMVar` by `hasExprMVar` in `CollectMVars`, `FindMVar`
  src/Lean/Util/CollectMVars.lean
  src/Lean/Util/FindMVar.lean
Labels: builds-mathlib, toolchain-available

#4426 fix: show argument name in implicit argument error
  src/Lean/Elab/App.lean
  src/Lean/Elab/Term.lean
  tests/lean/1616.lean.expected.out
  tests/lean/217.lean.expected.out
  tests/lean/argNameAtPlaceholderError.lean.expected.out
  tests/lean/evalNone.lean.expected.out
  tests/lean/evalWithMVar.lean.expected.out
  tests/lean/hidingInaccessibleNames.lean.expected.out
  tests/lean/holeErrors.lean.expected.out
  tests/lean/holes.lean.expected.out
  tests/lean/implicitArgumentError.lean
  tests/lean/implicitArgumentError.lean.expected.out
  tests/lean/jason2.lean.expected.out
Labels: builds-mathlib, toolchain-available

#4360 feat: use lazy MessageData for omega errors
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/Meta/Tactic/Apply.lean
  src/Lean/PrettyPrinter.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4456 chore: write release notes for 4.9.0
  RELEASES.md
  releases_drafts/messagedata.md
  releases_drafts/wf.md
Labels: builds-mathlib, toolchain-available

#4400 feat: switching List lookup normal forms to `L[n]` and `L[n]?`
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/GetElem.lean
  src/Init/Omega/IntList.lean
Labels: awaiting-review, builds-mathlib, toolchain-available, release-ci

#4438 doc: documenting Char and upstreaming extensionality from batteries
  doc/char.md
  src/Init/Data/Char/Lemmas.lean
Labels: awaiting-author

#4469 chore: reorganisation of `List` API
  src/Init/Data/Array/BasicAux.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/List.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Control.lean
  src/Init/Data/List/Impl.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Notation.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Prelude.lean
  tests/lean/run/delabMatch.lean
  tests/lean/run/maze.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4470 feat: improvements to `List.set` and `List.concat` API
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/TakeDrop.lean
Labels: toolchain-available

#4242 feat: add missing theorems for `+ 1` and `- 1` normal form
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Gcd.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Prelude.lean
  src/Init/WFTactics.lean
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/interactive/hoverDot.lean.expected.out
  tests/lean/librarySearch.lean
  tests/lean/run/wfEqnsIssue.lean
Labels: awaiting-author, builds-mathlib, toolchain-available, release-ci, full-ci

#4472 feat: lemmas about List.filter
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Basic.lean
Labels: toolchain-available

#4473 feat: cleanup @[simp] annotations for List
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#4475 chore: add forgotten deprecation
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#4468 chore: lake: fix `tests/init` cleanup
  src/lake/tests/init/clean.sh
Labels: toolchain-available

#4434 feat: use priorities to ensure simp applies eqational lemmas in order
  src/Init/Tactics.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  tests/lean/run/eqnsPrio.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4479 chore: missing instances
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Fin.lean
Labels: toolchain-available

#4481 fix: `simp` support for `OfNat` instances that are functions
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/4462.lean
Labels: toolchain-available

#4484 fix: `deprecated` warning position at `simp` arguments
  src/Lean/Elab/Term.lean
  tests/lean/4452.lean
  tests/lean/4452.lean.expected.out
Labels: toolchain-available

#4486 chore: @[simp] Nat.min_assoc
  src/Init/Data/Nat/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#4489 chore: missing withSynthesize in #check_tactic
  src/Lean/Elab/CheckTactic.lean
Labels: toolchain-available

#4488 chore: @[simp] List.getElem?_eq_getElem
  src/Init/Data/List/Lemmas.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4476 chore: nix shell: add gdb
  flake.nix
Labels: awaiting-review, toolchain-available

#4459 feat: incremental `next` and tactic `if`
  src/Init/Tactics.lean
  src/Init/TacticsExtra.lean
  tests/lean/interactive/incrementalCombinator.lean
  tests/lean/interactive/incrementalCombinator.lean.expected.out
  tests/lean/run/by_cases.lean
Labels: toolchain-available

#4492 test: for `isDefEq` issue
  tests/lean/run/2461.lean
Labels: toolchain-available

#4494 chore: cleanup
  src/Init/Prelude.lean
  src/Lean/Meta/SynthInstance.lean
Labels: toolchain-available

#4387 fix: eta reduce mvar assignments in `isDefEq`
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/SynthInstance.lean
  src/Lean/MetavarContext.lean
  tests/lean/etaReducedMvarAssignments.lean
  tests/lean/etaReducedMvarAssignments.lean.expected.out
Labels: builds-mathlib, toolchain-available, release-ci

#4388 chore: remove redundant `if-else` in `isDefEqQuickOther`
  src/Lean/Meta/ExprDefEq.lean
Labels: builds-mathlib, toolchain-available

#4258 doc: add docstrings for `dsimp` configuration
  src/Init/MetaTypes.lean
Labels: documentation, awaiting-review, toolchain-available

#4497 fix: global definition shadowing a local one when using dot-notation
  src/Lean/Elab/Term.lean
  tests/lean/run/3079.lean
Labels: toolchain-available

#4474 refactor: constructions: modify environment in lean world
  src/Lean/AuxRecursor.lean
  src/Lean/Declaration.lean
  src/Lean/Meta/CompletionName.lean
  src/Lean/Meta/Constructions.lean
  src/Lean/Meta/InferType.lean
  src/Lean/Modifiers.lean
  src/library/CMakeLists.txt
  src/library/aux_recursors.cpp
  src/library/aux_recursors.h
  src/library/constructions/brec_on.cpp
  src/library/constructions/brec_on.h
  src/library/constructions/cases_on.cpp
  src/library/constructions/cases_on.h
  src/library/constructions/no_confusion.cpp
  src/library/constructions/no_confusion.h
  src/library/constructions/rec_on.cpp
  src/library/constructions/rec_on.h
  src/library/constructions/util.cpp
  src/library/init_module.cpp
  src/library/protected.cpp
  src/library/protected.h
  src/library/util.cpp
  src/library/util.h
Labels: builds-mathlib, toolchain-available

#3963 fix: validate UTF-8 at C++ -> Lean boundary
  src/Init/Data/String/Extra.lean
  src/Lean/Compiler/IR/EmitC.lean
  src/Lean/Compiler/IR/EmitLLVM.lean
  src/include/lean/lean.h
  src/runtime/io.cpp
  src/runtime/object.cpp
  src/runtime/object.h
  src/runtime/utf8.cpp
  src/runtime/utf8.h
  src/util/shell.cpp
  tests/lean/1690.lean.expected.out
  tests/lean/1707.lean.expected.out
  tests/lean/301.lean.expected.out
Labels: toolchain-available, full-ci

#4502 chore: fix linter errors
  src/Init/Control/Except.lean
  src/Init/Control/Lawful/Basic.lean
  src/Init/Control/Lawful/Instances.lean
  src/Init/Control/Option.lean
  src/Init/Control/Reader.lean
  src/Init/Control/State.lean
  src/Init/Control/StateCps.lean
  src/Init/Control/StateRef.lean
  src/Init/Core.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Nat/Linear.lean
  src/Init/Prelude.lean
  src/Init/WF.lean
  src/Lean/Attributes.lean
  src/Lean/DocString.lean
  src/Lean/Elab/Attributes.lean
  src/Lean/Elab/SyntheticMVars.lean
  src/Lean/Elab/Term.lean
  src/Lean/Environment.lean
  src/Lean/HeadIndex.lean
  src/Lean/Meta/DiscrTree.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  src/Lean/Meta/Transform.lean
  src/Lean/ReducibilityAttrs.lean
  src/Lean/ResolveName.lean
  src/Lean/Util/ForEachExprWhere.lean
  tests/lean/run/meta3.lean
Labels: builds-mathlib, toolchain-available

#4498 refactor: port mk_definition_inferring_unsafe to Lean
  src/Lean/Environment.lean
  src/Lean/Meta/Closure.lean
  src/Lean/Meta/Match/Match.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4505 feat: `open _root_.<namespace>`
  src/Lean/ResolveName.lean
  tests/lean/run/3045.lean
Labels: toolchain-available

#4508 fix: `[implemented_by]` at functions defined by well-founded recursion
  src/Lean/Elab/DeclModifiers.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/DefView.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/Structure.lean
  tests/lean/run/2899.lean
Labels: toolchain-available

#4467 fix: `dsimp` missing theorems for literals
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Transform.lean
  tests/lean/run/dsimpNatLitIssue.lean
Labels: builds-mathlib, toolchain-available, release-ci

#4509 chore: cherry-pick stray test from #3850
  tests/lean/librarySearch.lean
Labels: toolchain-available

#3850 feat: complete Int div/mod simprocs
  src/Init/Data/Int/Order.lean
  src/Init/Data/Nat/Div.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4512 fix: missing unboxing in interpreter when loading initialized value
  src/library/compiler/ir_interpreter.cpp
  tests/pkg/initialize/.gitignore
  tests/pkg/initialize/Initialize.lean
  tests/pkg/initialize/Initialize/Basic.lean
  tests/pkg/initialize/lakefile.toml
  tests/pkg/initialize/test.sh
Labels: toolchain-available

#4518 refactor: lake: more robust trace reading
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Trace.lean
  src/lake/Lake/Util/JsonObject.lean
  src/lake/tests/trace/Foo.lean
  src/lake/tests/trace/clean.sh
  src/lake/tests/trace/lakefile.toml
  src/lake/tests/trace/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon, backport releases/v4.9.0

#4521 feat: lemmas about List.map
  src/Init/Core.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Omega/IntList.lean
  tests/lean/run/list_simp.lean
Labels: awaiting-review, toolchain-available

#4499 feat: introduce `Std`
  nix/bootstrap.nix
  nix/buildLeanPackage.nix
  src/CMakeLists.txt
  src/Std.lean
  src/Std/remove-after-adding-other-files
  src/lakefile.toml.in
  src/library/compiler/ir_interpreter.cpp
  src/stdlib.make.in
Labels: builds-mathlib, toolchain-available, release-ci

#4501 doc: more detailed docstring for PersistentEnvExtension
  src/Lean/Environment.lean
Labels: toolchain-available

#4524 chore: fix statement of List.filter_congr
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#4525 chore: fix statement of List.filter_congr
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#4526 chore: missing Prod.map lemmas
  src/Init/Core.lean
Labels: toolchain-available

#4490 feat: more infrastructure for tactic documentation
  src/Lean/BuiltinDocAttr.lean
  src/Lean/DocString.lean
  src/Lean/DocString/Extension.lean
  src/Lean/Elab.lean
  src/Lean/Elab/InheritDoc.lean
  src/Lean/Elab/Tactic/Doc.lean
  src/Lean/Parser.lean
  src/Lean/Parser/Attr.lean
  src/Lean/Parser/Command.lean
  src/Lean/Parser/Tactic.lean
  src/Lean/Parser/Tactic/Doc.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/InfoUtils.lean
  src/lake/Lake/Load/Lean/Eval.lean
  src/stdlib_flags.h
  tests/lean/interactive/hoverTacticExt.lean
  tests/lean/interactive/hoverTacticExt.lean.expected.out
  tests/lean/run/tacticDoc.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4528 fix: cdot parser error message range
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  tests/lean/interactive/issue4527.lean
  tests/lean/interactive/issue4527.lean.expected.out
  tests/lean/refineFiltersOldMVars.lean.expected.out
  tests/lean/tacUnsolvedGoalsErrors.lean.expected.out
Labels: awaiting-review, toolchain-available

#4477 feat: expose flags for the bundled C compiler
  src/Lean/Compiler/FFI.lean
  src/Leanc.lean
  src/util/ffi.cpp
Labels: toolchain-available, release-ci

#4478 fix: lake: remove module dynlib from platform-independent trace
  src/lake/Lake/Build/Module.lean
  src/lake/examples/precompile/test.sh
  src/lake/tests/precompileArgs/lakefile.lean
  src/lake/tests/precompileArgs/test.sh
Labels: builds-mathlib, toolchain-available, release-ci

#4533 chore: fix explicitness of Prod.map lemmas
  src/Init/Core.lean
Labels: toolchain-available

#4504 chore: Remove simp from `Option.elim`, replace with individal simp lemmas
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Lemmas.lean
Labels: builds-mathlib, toolchain-available, release-ci

#4516 refactor: port recOn construction to Lean
  src/Lean/Meta/Constructions.lean
  src/Lean/Meta/Constructions/RecOn.lean
  src/library/constructions/CMakeLists.txt
  src/library/constructions/rec_on.cpp
  src/library/constructions/rec_on.h
  src/library/suffixes.h
  tests/lean/run/3214.lean
  tests/lean/run/335.lean
  tests/lean/run/345.lean
  tests/lean/run/anonymous_ctor_error_msg.lean
Labels: toolchain-available, will-merge-soon

#4522 chore: move @[simp] from pred_le to sub_one_le
  src/Init/Data/Nat/Basic.lean
  tests/lean/guessLexTricky.lean
Labels: builds-mathlib, toolchain-available

#4404 chore: fix typo and incorrect name in doc
  src/Init/Tactics.lean
  tests/lean/run/wfirred.lean
  tests/lean/runTacticMustCatchExceptions.lean.expected.out
Labels: builds-mathlib, toolchain-available

#4537 chore: unset parseQuotWithCurrentStage in stage1’s src/stdlib_flags.h
  src/stdlib_flags.h
Labels: toolchain-available, merge-ci

#4530 fix: cached results at `synthInstance?`
  src/Lean/Meta/AbstractMVars.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/SynthInstance.lean
  tests/lean/infoFromFailure.lean.expected.out
  tests/lean/run/2283.lean
Labels: builds-mathlib, toolchain-available

#4417 feat: BitVec.twoPow and lemmas, toward bitblasting multiplication for LeanSAT
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: awaiting-review, toolchain-available

#4532 feat: change `succ` to `+ 1`
  src/Init/Data/Nat/Div.lean
Labels: builds-mathlib, toolchain-available, release-ci

#4544 chore: mark releases as prerelease
  .github/workflows/ci.yml
Labels: toolchain-available

#4493 fix: discrepancy `theorem` vs `example`
  src/Lean/Elab/MutualDef.lean
  tests/lean/1682.lean.expected.out
  tests/lean/813.lean.expected.out
  tests/lean/interactive/plainGoal.lean.expected.out
  tests/lean/ppProofs.lean.expected.out
  tests/lean/run/1575.lean
  tests/lean/run/4398.lean
  tests/lean/run/multiTargetCasesInductionIssue.lean
  tests/lean/rwEqThms.lean.expected.out
Labels: breaks-mathlib, toolchain-available, release-ci

#4550 feat: maximum?_eq_some_iff'
  src/Init/Data/List/TakeDrop.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4554 fix: tactics in terms in tactic combinators breaking incrementality
  src/Lean/Elab/Tactic/ElabTerm.lean
  tests/lean/interactive/incrementalTactic.lean
  tests/lean/interactive/incrementalTactic.lean.expected.out
Labels: toolchain-available, backport releases/v4.9.0

#4536 fix: block implicit lambda feature for type-free type ascription
  src/Lean/Elab/Term.lean
Labels: builds-mathlib, toolchain-available

#4562 fix: two functions with the same name in a `where`/`let rec` block
  src/Lean/Elab/LetRec.lean
  tests/lean/run/4547.lean
Labels: toolchain-available

#4563 fix: `IndPredBelow` should not add auxiliary declarations containing `sorry`
  src/Lean/Meta/IndPredBelow.lean
  src/Lean/Meta/Match/Match.lean
Labels: toolchain-available

#4529 fix: lake: exe bad import errors & related touchups
  src/lake/Lake/Build/Executable.lean
  src/lake/Lake/Build/Module.lean
  src/lake/tests/badImport/.gitignore
  src/lake/tests/badImport/Etc.lean
  src/lake/tests/badImport/Lib/A.lean
  src/lake/tests/badImport/Lib/B.lean
  src/lake/tests/badImport/Lib/B1.lean
  src/lake/tests/badImport/Lib/C.lean
  src/lake/tests/badImport/Lib/S.lean
  src/lake/tests/badImport/Lib/U.lean
  src/lake/tests/badImport/X.lean
  src/lake/tests/badImport/X1.lean
  src/lake/tests/badImport/clean.sh
  src/lake/tests/badImport/lakefile.lean
  src/lake/tests/badImport/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon, release-ci

#4564 fix: lake: non-ident script names
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/DSL/Script.lean
  src/lake/examples/scripts/expected.out
  src/lake/examples/scripts/lakefile.lean
  src/lake/examples/scripts/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon, release-ci

#4567 fix: avoid unnecessary proof steps in `simp`
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  tests/lean/run/4534.lean
Labels: toolchain-available

#4517 refactor: port below and brecOn construction to Lean
  src/Lean/Meta/Constructions.lean
  src/Lean/Meta/Constructions/BRecOn.lean
  src/library/constructions/CMakeLists.txt
  src/library/constructions/brec_on.cpp
  src/library/constructions/brec_on.h
  src/library/constructions/util.cpp
  src/library/constructions/util.h
Labels: toolchain-available, will-merge-soon

#4549 refactor: extract withRecArgInfo from findRecArg
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Elab/PreDefinition/Structural/Main.lean
  tests/lean/1673.lean.expected.out
  tests/lean/guessLexDiff.lean.expected.out
  tests/lean/guessLexFailures.lean.expected.out
  tests/lean/sanitychecks.lean.expected.out
  tests/lean/terminationFailure.lean.expected.out
  tests/lean/wf1.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon

#4482 fix: discrepancy in the elaborators for `theorem`, `def`, and `example`
  src/Lean/Elab/MutualDef.lean
  tests/lean/autoPPExplicit.lean.expected.out
Labels: breaks-mathlib, toolchain-available, release-ci

#4560 feat: remove Decidable instances from GetElem
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Subarray.lean
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/FloatArray/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/GetElem.lean
  src/Lean/Data/HashMap.lean
  src/Lean/Data/PersistentArray.lean
  src/Lean/Data/PersistentHashMap.lean
  tests/lean/run/1299.lean
  tests/lean/run/constructor_as_variable.lean
Labels: breaks-mathlib, toolchain-available, release-ci

#4569 fix: interrupt exception was swallowed by some `tryCatchRuntimeEx` uses
  src/Lean/CoreM.lean
  src/Lean/Elab/Command.lean
  tests/lean/interactive/incrementalCommand.lean
  tests/lean/interactive/incrementalCommand.lean.expected.out
Labels: builds-mathlib, toolchain-available, backport releases/v4.9.0

#4566 fix: lake: computation of precompiled libs
  src/lake/Lake/Build/Module.lean
  src/lake/examples/ffi/app/lakefile.lean
  src/lake/examples/ffi/lib/lakefile.lean
  src/lake/examples/ffi/package.sh
  src/lake/examples/ffi/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon, release-ci

#4576 feat: add option `debug.byAsSorry true`
  src/Lean/Elab/BuiltinTerm.lean
  tests/lean/run/byAsSorry.lean
Labels: toolchain-available
