Repository leanprover/lean4, pull requests merged in 2025-10, with the labels that each got.

#10635 chore: add an internal String function
  src/Init/Data/String/Bootstrap.lean
Labels: changelog-no

#10634 refactor: incorporate UTF8 material from String.Extra into String.Basic
  src/Init/Data/String/Basic.lean
  src/Init/Data/String/Decode.lean
  src/Init/Data/String/Extra.lean
  tests/lean/run/utf8英語.lean
Labels: changelog-library

#10638 feat: disable "experimental" warning for `mvcgen`
  src/Lean/Elab/Tactic/Do/VCGen.lean
  src/Lean/Elab/Tactic/Do/VCGen/Basic.lean
Labels: toolchain-available, changelog-language

#10641 fix: spurious invariant instantiation in `mspec` by `rfl`
  src/Lean/Elab/Tactic/Do/Spec.lean
  tests/lean/run/mspecInvariantInstantiation.lean
Labels: changelog-language

#10642 feat: introduce `List.Cursor.pos` as an abbreviation for `prefix.length`
  src/Std/Do/Triple/SpecLemmas.lean
  tests/lean/run/bhaviksSampler.lean
  tests/lean/run/doLogicTests.lean
Labels: changelog-library

#10631 fix: expose `Int*` definitions for simprocs and `decide` (fixes #10546)
  src/Init/Data/SInt/Basic.lean
  tests/lean/run/simpSInt.lean
  tests/lean/run/simprocSInt.lean
  tests/lean/run/simprocUInt.lean
  tests/lean/sint_basic.lean
  tests/lean/sint_basic.lean.expected.out
  tests/lean/test_single.sh
Labels: builds-mathlib, toolchain-available, changelog-library

#10632 chore: docstring review for ByteArray
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/ByteArray/Bootstrap.lean
  src/Init/Data/ByteArray/Extra.lean
  src/Init/Data/String/Basic.lean
  src/Init/Data/String/Decode.lean
  src/Init/Prelude.lean
Labels: builds-mathlib, toolchain-available, changelog-doc

#10643 chore: module system fixes and refinements from Mathlib porting
  script/Modulize.lean
  src/Init/Classical.lean
  src/Init/Core.lean
  src/Init/Data/Array/Attach.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Vector/Attach.lean
  src/Init/Data/Zero.lean
  src/Init/PropLemmas.lean
  src/Lean/AddDecl.lean
  src/Lean/Attributes.lean
  src/Lean/Compiler/CSimpAttr.lean
  src/Lean/Compiler/IR/CompilerM.lean
  src/Lean/Data/Options.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/DefView.lean
  src/Lean/Elab/Deriving/ToExpr.lean
  src/Lean/Elab/Exception.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Tactic/ElabTerm.lean
  src/Lean/Language/Basic.lean
  src/Lean/Linter/MissingDocs.lean
  src/Lean/Linter/Sets.lean
  src/Lean/Meta/AbstractNestedProofs.lean
  src/Lean/Meta/Tactic/AuxLemma.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  src/Lean/MonadEnv.lean
  src/Lean/Server/Rpc/RequestHandling.lean
  tests/lean/run/10213.lean
  tests/lean/run/grind_bintree.lean
  tests/lean/run/noncomputable_decide.lean
Labels: toolchain-available

#10650 fix: improve error message for `mstart` when goal is not a `Prop`
  src/Lean/Elab/Tactic/Do/ProofMode/Basic.lean
  tests/lean/run/mintroErrorMessage.lean
Labels: changelog-language

#10664 fix: eliminate potential source of inlay hint flakiness
  src/Lean/Server/AsyncList.lean
  src/Lean/Server/ServerTask.lean
Labels: changelog-no

#10669 test: temporarily disable all new tests that use `waitForILeans`
  tests/lean/interactive/findReferences.lean.disabled
  tests/lean/interactive/incomingCallHierarchy.lean.disabled
  tests/lean/interactive/moduleHierarchyImports.lean.disabled
  tests/lean/interactive/outgoingCallHierarchy.lean.disabled
  tests/lean/interactive/projects/InverseModuleHierarchy/InverseModuleHierarchy/BasicTest.lean.disabled
  tests/lean/interactive/unknownIdentifierCodeActions.lean.disabled
  tests/lean/interactive/workspaceSymbols.lean.disabled
Labels: changelog-no

#10672 fix: lake: outdated traces w/ cache
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Module.lean
  src/lake/tests/cache/Test/ImportIgnored.lean
  src/lake/tests/cache/test.sh
Labels: toolchain-available, changelog-no

#10673 test: disable flaky interactive diag tests
  tests/lean/interactive/highlightMatches.lean.disabled
  tests/lean/interactive/interactiveDiagnostics.lean.disabled
  tests/lean/interactive/interactiveTraces.lean.disabled
Labels: changelog-no

#10677 feat: `grind` interactive mode basic tactics
  src/Init/Grind/Interactive.lean
  src/Init/Grind/Tactics.lean
  src/Init/Notation.lean
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Elab/Tactic/Grind/Basic.lean
  src/Lean/Elab/Tactic/Grind/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Grind/Main.lean
  src/Lean/Elab/Tactic/Try.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/SearchM.lean
  src/Lean/Meta/Tactic/Grind/Solve.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_canon_insts.lean
  tests/lean/run/grind_canon_types.lean
  tests/lean/run/grind_congr.lean
  tests/lean/run/grind_diseq_api.lean
  tests/lean/run/grind_interactive.lean
  tests/lean/run/grind_many_eqs.lean
  tests/lean/run/grind_nested_proofs.lean
  tests/lean/run/grind_norm_levels.lean
  tests/lean/run/grind_pp_attr.lean
  tests/lean/run/grind_propagate_connectives.lean
  tests/lean/run/sharecommon_mpz.lean
Labels: changelog-tactics

#10682 fix: instance name for deriving ToExpr
  src/Lean/Elab/Deriving/Inhabited.lean
  src/Lean/Elab/Deriving/ToExpr.lean
  tests/lean/run/issue10678.lean
Labels: changelog-language

#10685 feat: `LT` and `LE` instances on new position types
  src/Init/Data/String/Basic.lean
  src/Init/Data/String/Pattern/String.lean
Labels: toolchain-available, changelog-library

#10676 feat: `IO.FS.hardLink`
  src/Init/System/IO.lean
  src/runtime/io.cpp
  tests/lean/run/IO_test.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#10510 feat: add `Std.CancellationToken` type
  src/Std/Sync.lean
  src/Std/Sync/CancellationToken.lean
  tests/lean/run/async_cancellation.lean
  tests/lean/run/broadcast.lean
Labels: toolchain-available, changelog-library

#10690 feat: add `show_*` and `instantiate` grind tactics
  src/Init/Grind/Interactive.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Elab/Tactic/Grind/Basic.lean
  src/Lean/Elab/Tactic/Grind/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Grind/Show.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_interactive.lean
Labels: changelog-tactics

#10668 doc: typo in docstring of Std.Time.DateTime.now
  src/Std/Time/Zoned.lean
Labels: toolchain-available

#10628 doc: fix url to profile.ts source
  src/Lean/Util/Profiler.lean
Labels: toolchain-available

#10606 refactor: structural recursion: prove `.eq_def` directly
  src/Init/Data/Dyadic/Basic.lean
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Meta/Constructions/BRecOn.lean
  src/Lean/Meta/Tactic/Refl.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/2961.lean
  tests/lean/run/5667.lean
  tests/lean/run/eqValue.lean
  tests/lean/run/issue10195.lean
  tests/lean/run/issue10424.lean
  tests/lean/run/issue10431.lean
  tests/lean/run/issue2237.lean
  tests/lean/run/issue2962.lean
  tests/lean/run/issue6592.lean
  tests/lean/run/issue9846.lean
  tests/lean/run/partial_fixpoint.lean
  tests/lean/run/structuralEqn6.lean
  tests/lean/run/structuralEqns2.lean
  tests/lean/run/structuralEqns4.lean
  tests/lean/run/structuralEqns5.lean
Labels: builds-mathlib, toolchain-available, builds-manual

#10649 fix: `Nat.and_distrib_right` -> `Nat.and_or_distrib_right`
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: toolchain-available, changelog-library

#10333 feat: add `coinductive` command to specify coinductive predicates
  src/Lean/Elab/Coinductive.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/MutualInductive.lean
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Eqns.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Induction.lean
  src/Lean/Meta/Eqns.lean
  src/Lean/Meta/MkIffOfInductiveProp.lean
  src/Lean/Parser/Command.lean
  tests/lean/run/coinductive_syntax.lean
  tests/lean/versoDocMissing.lean.expected.out
  tests/pkg/user_attr_app/UserAttr/BlaAttr.lean
  tests/pkg/user_attr_app/UserAttr/Tst.lean
Labels: toolchain-available, changelog-language

#10627 feat: add forall_fin_zero and exists_fin_zero
  src/Init/Data/Fin/Lemmas.lean
Labels: toolchain-available, changelog-library

#10706 feat: `have` tactic for `grind` interactive mode
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Elab/Tactic/Grind/Have.lean
  tests/lean/run/grind_interactive.lean
Labels: changelog-tactics

#10707 feat: make `finish` fail when the goal is not closed
  src/Lean/Elab/Tactic/Grind/Basic.lean
  src/Lean/Elab/Tactic/Grind/BuiltinTactic.lean
  tests/lean/run/grind_interactive.lean
Labels: changelog-tactics

#9855 feat: lake: `allowImportAll` configuration option
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Config/LeanLib.lean
  src/lake/Lake/Config/LeanLibConfig.lean
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Config/PackageConfig.lean
  src/lake/schemas/lakefile-toml-schema.json
  tests/lake/tests/module/ErrorTest/CrossPackageImportAll.lean
  tests/lake/tests/module/Test/CrossPackageImportAll.lean
  tests/lake/tests/module/dep/Dep/AllowImportAll.lean
  tests/lake/tests/module/dep/Dep/NoImportAll.lean
  tests/lake/tests/module/dep/lakefile.toml
  tests/lake/tests/module/test.sh
Labels: builds-mathlib, toolchain-available, changelog-lake, breaks-manual

#10709 feat: anchors for referencing terms in the `grind` state
  src/Init/Grind/Interactive.lean
  src/Lean/Elab/Tactic/Grind/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Grind/Show.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Anchor.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_interactive.lean
Labels: changelog-tactics

#10630 fix: add `cancel` function to the Timer API to make it behave correctly with finalizers and selectables
  src/Std/Internal/Async/Basic.lean
  src/Std/Internal/Async/Timer.lean
  src/Std/Internal/UV/Timer.lean
  src/runtime/uv/timer.cpp
  src/runtime/uv/timer.h
  tests/lean/run/async_sleep.lean
Labels: toolchain-available, changelog-library
