Repository leanprover/lean4, pull requests merged in 2025-02, with the labels that each got.

#6895 fix: `grind` issues exposed by `grind_constProp`
  src/Lean/Meta/Tactic/Grind/CasesMatch.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  src/Lean/Meta/Tactic/Grind/MatchCond.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  src/Lean/Meta/Tactic/Grind/ProveEq.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
  tests/lean/run/grind_constProp.lean
  tests/lean/run/grind_ematch2.lean
Labels: toolchain-available, changelog-language

#6897 feat: attributes `[grind =>]` and `[grind <=]`
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  tests/lean/run/grind_attrs.lean
  tests/lean/run/grind_constProp.lean
  tests/lean/run/grind_ematch2.lean
  tests/lean/run/grind_eq_bwd.lean
  tests/lean/run/grind_pattern2.lean
  tests/lean/run/grind_trace.lean
  tests/lean/run/no_grind_constProp.lean
Labels: toolchain-available, changelog-language

#6890 feat: teach bv_normalize to rewrite subtractions to additions
  src/Init/Data/BitVec/Lemmas.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  src/Std/Tactic/BVDecide/Normalize/Equal.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-library

#6900 doc: correct docstring for TransGen.tail and TransGen.trans
  src/Init/Core.lean
Labels: toolchain-available

#6901 refactor: simpMatch to not etaStruct
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  src/Lean/Meta/Tactic/Split.lean
  tests/lean/run/prefixTableStep.lean
  tests/lean/run/simpMatchEta.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon

#6904 feat: add `Grind.Config.verbose` and `reportIssue!` macro
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Grind/Ctor.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Ext.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/MatchCond.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Solve.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6703 feat: modify delaborator to tag generalized field notation
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Formatter.lean
Labels: toolchain-available, changelog-pp

#6729 feat: make coeFun delaborator respect `pp.tagAppFns`
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
Labels: toolchain-available, changelog-pp

#6730 feat: make all app unexpanders respond to `pp.tagAppFns`
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
Labels: toolchain-available, changelog-pp

#6907 chore: fixing short-circuiting issue in `Ordering.then`
  src/Init/Data/Ord.lean
  tests/lean/run/Ord.lean
Labels: toolchain-available

#6908 test: `grind_guide.lean`
  tests/lean/grind_guide.lean
  tests/lean/grind_guide.lean.expected.out
Labels: toolchain-available, changelog-no

#6910 chore: improve `grind` pattern pretty printer
  src/Init/Grind/Util.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  tests/lean/grind_guide.lean.expected.out
  tests/lean/run/grind_ctor_ematch.lean
  tests/lean/run/grind_ematch_patterns.lean
  tests/lean/run/grind_eq_pattern.lean
  tests/lean/run/grind_offset.lean
  tests/lean/run/grind_pattern1.lean
  tests/lean/run/grind_pattern2.lean
  tests/lean/run/grind_pattern_proj.lean
Labels: toolchain-available, changelog-language

#6911 chore: improve `grind` case-split trace
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/grind_guide.lean.expected.out
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_split_issue.lean
Labels: toolchain-available, changelog-language

#6912 feat: align `findX` theorems across `List/Array/Vector`
  src/Init/Data/Array/Attach.lean
  src/Init/Data/Array/Find.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Vector/Attach.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/Find.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#6913 chore: fix release_checklist.py tag lookup bug
  script/release_checklist.py
Labels: toolchain-available

#6915 chore: use --since in release_notes.py
  doc/dev/release_checklist.md
  script/release_checklist.py
  script/release_notes.py
Labels: toolchain-available

#6916 chore: add a few lines to the v4.16.0 release notes
  RELEASES.md
Labels: toolchain-available

#6823 feat: builtin as_aux_lemma tactic and tree_tac simp attribute
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/AsAuxLemma.lean
  src/Lean/Elab/Tactic/TreeTacAttr.lean
  tests/lean/run/as_aux_lemma.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6917 chore: undo small change
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available

#6898 refactor: WF: create unfold theorems eagerly
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/Nonrec/Eqns.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Eqns.lean
  src/Lean/Elab/PreDefinition/WF.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/PreDefinition/WF/Unfold.lean
  tests/lean/run/simpDiag.lean
  tests/lean/run/wfUnfold.lean
Labels: builds-mathlib, toolchain-available

#6920 refactor: post-stage0 clean-up for #6898
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/PreDefinition/WF/Unfold.lean
Labels: toolchain-available, will-merge-soon

#6918 chore: split RELEASES.md into releases/ folder
  RELEASES.md
  releases/v4.0.0-m4.md
  releases/v4.0.0-m5.md
  releases/v4.0.0.md
  releases/v4.1.0.md
  releases/v4.10.0.md
  releases/v4.11.0.md
  releases/v4.12.0.md
  releases/v4.13.0.md
  releases/v4.14.0.md
  releases/v4.15.0.md
  releases/v4.16.0.md
  releases/v4.2.0.md
  releases/v4.3.0.md
  releases/v4.4.0.md
  releases/v4.5.0.md
  releases/v4.6.0.md
  releases/v4.6.1.md
  releases/v4.7.0.md
  releases/v4.8.0.md
  releases/v4.9.0.md
Labels: toolchain-available

#6869 feat: `recommended_spelling` command
  src/Lean/DocString.lean
  src/Lean/Elab.lean
  src/Lean/Elab/RecommendedSpelling.lean
  src/Lean/Parser/Command.lean
  src/Lean/Parser/Term.lean
  src/Lean/Parser/Term/Doc.lean
  tests/lean/run/recommendedSpelling.lean
Labels: needs-update-stage0, builds-mathlib, toolchain-available, will-merge-soon, changelog-language

#6919 chore: update release_checklist.md
  doc/dev/release_checklist.md
  script/release_checklist.py
  script/release_repos.yml
Labels: toolchain-available

#6922 feat: LawfulBEq instances for Array and Vector
  src/Init/Data/Array/DecidableEq.lean
  src/Init/Data/Vector/DecidableEq.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#6886 doc: add recommended spellings for many term notations
  src/Init/Control/Basic.lean
  src/Init/Core.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/Bool.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Notation.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/GetElem.lean
  src/Init/Notation.lean
  src/Init/NotationExtra.lean
  src/Lean/Parser/Term.lean
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/run/recommendedSpelling.lean
Labels: toolchain-available, changelog-doc

#6923 refactor: FunInd: erase, not clear
  src/Lean/Meta/Tactic/FunInd.lean
Labels: builds-mathlib, toolchain-available

#6924 feat: bv_decide implement EQUAL_ITE rules
  src/Std/Tactic/BVDecide/Normalize/Equal.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#6770 feat: asynchronous code generation
  src/Lean/AddDecl.lean
  src/Lean/Compiler/IR/CompilerM.lean
  src/Lean/Compiler/LCNF/AuxDeclCache.lean
  src/Lean/Compiler/LCNF/PhaseExt.lean
  src/Lean/Compiler/Specialize.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/PreDefinition/Main.lean
  src/Lean/Environment.lean
  src/Lean/Meta/Eval.lean
  src/Lean/Util/Profiler.lean
  tests/lean/computedFieldsCode.lean.expected.out
  tests/lean/ll_infer_type_bug.lean
  tests/lean/run/2291.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6741 feat: bv_decide lower ||| to &&& and add and_eq_allOnes
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reify.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Simproc.lean
  src/Std/Tactic/BVDecide/Normalize/Canonicalize.lean
  src/Std/Tactic/BVDecide/Normalize/Equal.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#6925 doc: add highlights section to v4.16.0 release notes
  releases/v4.16.0.md
Labels: toolchain-available

#6931 chore: report total commits by category in release notes
  script/release_notes.py
Labels: toolchain-available

#6932 chore: release notes use more paragraphs when needed
  script/release_notes.py
Labels: toolchain-available

#6933 chore: release_checklist.py checks for bump/v4.X.0 branches
  doc/dev/release_checklist.md
  script/release_checklist.py
  script/release_repos.yml
Labels: toolchain-available

#6935 feat: `expose_names` tactic
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/ExposeNames.lean
  src/Lean/Meta/Tactic/ExposeNames.lean
  tests/lean/run/exposeNames.lean
Labels: toolchain-available, changelog-language

#6934 chore: release_checklist.py checks if 'begin dev cycle' PR is needed
  script/release_checklist.py
Labels: toolchain-available

#6930 fix: don't strip macro scopes in names of specialized LCNF decls
  src/Lean/Compiler/LCNF/Specialize.lean
Labels: toolchain-available, changelog-compiler

#6937 feat: improve `grind` error messages
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/ExposeNames.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/grind_guide.lean.expected.out
  tests/lean/run/grind_ctor_ematch.lean
  tests/lean/run/grind_eq.lean
  tests/lean/run/grind_guide.lean
  tests/lean/run/grind_offset_cnstr.lean
  tests/lean/run/grind_offset_model.lean
  tests/lean/run/grind_params.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_split_issue.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6940 feat: improve `grind` case-split on `Iff`
  src/Init/Grind/Lemmas.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6941 chore: more updates to release_checklist.py
  script/release_checklist.py
Labels: toolchain-available

#6943 chore: begin development cycle for v4.18.0
  src/CMakeLists.txt
Labels: toolchain-available

#6944 chore: add commit hash to error message in script/release_notes.py
  script/release_notes.py
Labels: toolchain-available

#6948 feat: align List/Array/Vector.insertIdx lemmas
  src/Init/Data/Array.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/InsertIdx.lean
  src/Init/Data/List/Nat/InsertIdx.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Vector.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/InsertIdx.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#6326 feat: add `BitVec.(getMsbD, msb)_replicate, replicate_one`
  src/Init/Data/BitVec/Lemmas.lean
Labels: awaiting-review, builds-mathlib, toolchain-available, changelog-library

#6866 feat: add `Hashable` instances for `PUnit` and `PEmpty`
  src/Init/Data/Hashable.lean
Labels: toolchain-available, changelog-library

#6891 fix: make `rewrite`/`rw` tactic abort on elaboration errors
  src/Lean/Elab/Tactic/Rewrite.lean
  tests/lean/run/rwWithElabError.lean
Labels: awaiting-review, builds-mathlib, toolchain-available, changelog-language

#6951 feat: improve simp trace formatting
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  tests/lean/1079.lean.expected.out
  tests/lean/discrTreeIota.lean.expected.out
  tests/lean/run/1234.lean
  tests/lean/run/1380.lean
  tests/lean/run/1815.lean
  tests/lean/run/3257.lean
  tests/lean/run/790.lean
  tests/lean/simp_trace.lean.expected.out
Labels: toolchain-available, changelog-language

#6795 feat: add `BitVec.(getElem_umod_of_lt, getElem_umod, getLsbD_umod, getMsbD_umod)`
  src/Init/Data/BitVec/Bitblast.lean
Labels: awaiting-review, toolchain-available, P-medium, changelog-library

#6768 feat: inlay hints for auto-implicits
  src/Init/Prelude.lean
  src/Lean/Data/Lsp/Basic.lean
  src/Lean/Data/Lsp/Capabilities.lean
  src/Lean/Data/Lsp/CodeActions.lean
  src/Lean/Data/Lsp/LanguageFeatures.lean
  src/Lean/Data/Lsp/Utf16.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/DeclarationRange.lean
  src/Lean/Elab/DefView.lean
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/InfoTree/InlayHints.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/MutualInductive.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Elab/Term.lean
  src/Lean/Server/AsyncList.lean
  src/Lean/Server/FileSource.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/InlayHints.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/FileWorker/SemanticHighlighting.lean
  src/Lean/Server/Requests.lean
  src/Lean/Server/Watchdog.lean
  src/Lean/Syntax.lean
  tests/lean/1018unknowMVarIssue.lean.expected.out
Labels: toolchain-available, changelog-server

#6942 chore: restore example after stage0 update
  src/Lean/Data/Lsp/LanguageFeatures.lean
Labels: toolchain-available

#6952 test: more equational theorem generation tests
  tests/lean/run/2961.lean
  tests/lean/run/3219.lean
  tests/lean/run/5667.lean
Labels: toolchain-available, will-merge-soon

#6939 fix: show error messages on name conflicts in `mutual` blocks
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/MutualInductive.lean
  tests/lean/run/6694.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6628 feat: add SMT-LIB overflow on addition for bitvectors `BitVec.(uadd_overflow, sadd_overflow, uadd_overflow_eq, sadd_overflow_eq)` and support theorems
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/LemmasAux.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: awaiting-author, toolchain-available, P-medium, changelog-library

#6953 chore: fix variable names in List lemmas
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/ToArray.lean
  src/Lean/Linter.lean
  src/Lean/Linter/List.lean
  src/Std/Time/Zoned/ZonedDateTime.lean
  tests/lean/run/index_variables_linter.lean
Labels: toolchain-available, merge-ci

#6634 feat: allow updating binders to and from strict- and instance-implicit
  src/Lean/Elab/BuiltinCommand.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/varBinderUpdate.lean
  tests/lean/varBinderUpdate.lean
  tests/lean/varBinderUpdate.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language

#6961 feat: `evalAndSuggest` helper tactic
  src/Init/Try.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Elab/Tactic/Try.lean
  tests/lean/run/eval_suggest1.lean
Labels: toolchain-available, changelog-language

#6962 doc: improve List.toArray doc-string
  src/Init/Prelude.lean
Labels: toolchain-available, changelog-doc

#6963 chore: further cleanup of index variable naming in List
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/List/ToArray.lean
  src/Lean/Linter/List.lean
Labels: toolchain-available, changelog-library

#6964 feat: `#info_trees in` command
  src/Init/Notation.lean
  src/Lean/Elab.lean
  src/Lean/Elab/InfoTrees.lean
  tests/lean/run/info_trees.lean
Labels: toolchain-available, changelog-language

#6965 feat: implement `try?` using `evalAndSuggest`
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Elab/Tactic/Try.lean
  tests/lean/run/eval_suggest1.lean
  tests/lean/run/grind_constProp.lean
  tests/lean/run/try_trace1.lean
Labels: toolchain-available, changelog-language

#6966 feat: add internal linter for List/Array/Vector variable names
  src/Init/Data/Array/DecidableEq.lean
  src/Lean/Linter/List.lean
  src/Lean/Server/InfoUtils.lean
  tests/lean/run/list_name_linter.lean
Labels: toolchain-available, changelog-library

#6967 feat: use `expose_names` in `try?`
  src/Lean/Elab/Tactic/Try.lean
  tests/lean/run/try_trace1.lean
Labels: toolchain-available, changelog-language

#6968 chore: rename Nat.not_eq_zero_of_lt
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Linear.lean
Labels: toolchain-available

#6947 feat: binderNameHint
  src/Init.lean
  src/Init/BinderNameHint.lean
  src/Lean/Meta.lean
  src/Lean/Meta/BinderNameHint.lean
  src/Lean/Meta/Tactic/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  tests/lean/run/binderNameHint.lean
  tests/lean/run/binderNameHintScope.lean
  tests/lean/run/binderNameHintSimp.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6971 refactor: bv_decide's type analysis to prepare for enum support
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Basic.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Structures.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/TypeAnalysis.lean
  src/Std/Tactic/BVDecide/Syntax.lean
  tests/lean/run/bv_structures.lean
Labels: toolchain-available, changelog-no

#6972 refactor: rename auto_attach attribute to wf_preprocess
  src/Init/Tactics.lean
  src/Lean/Elab/PreDefinition/WF/AutoAttach.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available

#6959 feat: inlay hint refinements
  src/Lean/Elab/InfoTree/InlayHints.lean
  src/Lean/Elab/Term.lean
  src/Lean/Server/AsyncList.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/InlayHints.lean
  src/Lean/Server/FileWorker/SemanticHighlighting.lean
  src/Lean/Server/Requests.lean
Labels: toolchain-available, changelog-server

#6978 fix: inlay hints in untitled files
  src/Lean/Server/FileWorker/InlayHints.lean
Labels: toolchain-available, changelog-server

#6979 feat: `try?` composite suggestions
  src/Init/Try.lean
  src/Lean/Elab/Tactic/Try.lean
  src/Lean/Meta/Tactic/Try.lean
  src/Lean/Meta/Tactic/Try/Collect.lean
  tests/lean/run/grind_constProp.lean
  tests/lean/run/try_trace1.lean
Labels: toolchain-available, changelog-language

#6830 feat: improve some files separation and standardize error messages in UV modules
  src/Std/Internal/UV.lean
  src/Std/Internal/UV/Loop.lean
  src/Std/Internal/UV/Timer.lean
  src/runtime/libuv.h
  src/runtime/uv/event_loop.cpp
  src/runtime/uv/net_addr.h
  src/runtime/uv/timer.cpp
Labels: awaiting-review, toolchain-available, changelog-library

#6980 feat: `try?` validation and cleanup
  src/Lean/Elab/Tactic/Try.lean
  tests/lean/run/eval_suggest1.lean
  tests/lean/run/try_trace1.lean
Labels: toolchain-available, changelog-language

#6981 feat: `try?` tactic improvements
  src/Init/Try.lean
  src/Lean/Elab/Tactic/Try.lean
  tests/lean/run/grind_constProp.lean
  tests/lean/run/grind_eval_suggest.lean
  tests/lean/run/grind_try_trace.lean
Labels: toolchain-available, changelog-language

#6970 chore: linting List
  src/Init/Data/Array/Lex/Basic.lean
  src/Init/Data/List/Monadic.lean
  src/Init/Data/List/Notation.lean
  src/Init/Data/List/OfFn.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Data/List/Perm.lean
  src/Init/Data/List/Range.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/List/ToArrayImpl.lean
  src/Init/Data/List/Zip.lean
  src/Lean/Linter/List.lean
  tests/lean/run/list_name_linter.lean
Labels: toolchain-available, changelog-no

#6982 feat: improve monadic Array lemmas
  src/Init/Control/Lawful/Lemmas.lean
  src/Init/Data/Array/MapIdx.lean
  src/Init/Data/Array/Monadic.lean
  src/Init/Data/List/Control.lean
  src/Init/Data/Vector/MapIdx.lean
  src/Init/Data/Vector/Monadic.lean
Labels: toolchain-available, changelog-library

#6976 feat: respect `Task.map/bind (sync := true)` after waiting
  src/Init/Core.lean
  src/runtime/object.cpp
Labels: builds-mathlib, toolchain-available, changelog-compiler

#6984 perf: avoid taking mutex on already-resolved promises
  src/runtime/object.cpp
Labels: toolchain-available

#6958 feat: API to avoid deadlocks from dropped promises
  src/Init/System/IO.lean
  src/Init/System/Promise.lean
  src/Lean/AddDecl.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Environment.lean
  src/Lean/Language/Basic.lean
  src/Lean/Language/Lean.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/Requests.lean
  src/Std/Internal/Async/Basic.lean
  src/Std/Sync/Channel.lean
  src/bin/lean-gdb.py
  src/include/lean/lean.h
  src/runtime/compact.cpp
  src/runtime/compact.h
  src/runtime/io.cpp
  src/runtime/object.cpp
  src/runtime/object.h
  src/runtime/sharecommon.cpp
  src/runtime/uv/timer.cpp
  tests/lean/promise.lean
  tests/lean/run/taskState.lean
Labels: builds-mathlib, toolchain-available, release-ci, changelog-library

#6988 fix: convert kernel interrupt into elab interrupt
  src/Lean/CoreM.lean
  src/Lean/Elab/Tactic/BVDecide/External.lean
  src/Lean/Elab/Util.lean
  src/Lean/Exception.lean
  tests/lean/run/allGoals.lean
Labels: toolchain-available, changelog-language

#6991 feat: improve `try?` suggestion
  src/Lean/Elab/Tactic/Try.lean
  src/Lean/Meta/Tactic/Try.lean
Labels: toolchain-available, changelog-language

#6329 feat: parallel progress notifications
  .github/workflows/ci.yml
  src/Lean/Data/Lsp/Basic.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Language/Lean.lean
  src/Lean/Server/FileWorker.lean
Labels: builds-mathlib, toolchain-available, changelog-server

#6994 feat: compress `try?` suggestions
  src/Init/Try.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Elab/Tactic/Try.lean
  src/Lean/Meta/Tactic/Try/Collect.lean
  tests/lean/run/grind_try_trace.lean
Labels: toolchain-available, changelog-language

#6995 feat: `exact?` in `try?`
  src/Lean/Elab/Tactic/Try.lean
  tests/lean/run/grind_eval_suggest.lean
  tests/lean/run/grind_try_exact.lean
Labels: toolchain-available, changelog-language

#6977 refactor: elaborate forIn notation without extra let
  src/Lean/Elab/Extra.lean
  tests/lean/run/forInColErr.lean
Labels: builds-mathlib, toolchain-available

#6829 chore: change Lake configuration error message
  src/lake/Lake/CLI/Serve.lean
  src/lake/tests/serve/test.sh
Labels: builds-mathlib, toolchain-available, P-medium, changelog-lake

#6998 doc: mention `Prop`s are equal to `True` or `False`
  src/Lean/Parser/Term.lean
Labels: toolchain-available, changelog-doc

#7000 feat: add `Int.Linear` normalization support
  src/Init/Data/Int.lean
  src/Init/Data/Int/Linear.lean
  tests/lean/run/liaByRefl.lean
Labels: toolchain-available, changelog-language

#7002 feat: linear integer arith normalizer
  src/Init/Data/Int/Linear.lean
  src/Lean/Expr.lean
  src/Lean/Meta/IntInstTesters.lean
  src/Lean/Meta/Tactic/LinearArith/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Int.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Simp.lean
  src/Lean/Meta/Tactic/LinearArith/Nat/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Nat/Simp.lean
  tests/lean/run/liaByRefl.lean
Labels: toolchain-available, changelog-language

#7005 chore: remove unused Int simp lemmas
  src/Init/Data/Int/Lemmas.lean
Labels: builds-mathlib, toolchain-available

#7009 feat: `bv_decide` hint
  src/Init/Tactics.lean
  src/Std/Tactic/BVDecide/Syntax.lean
Labels: toolchain-available, changelog-language

#7010 chore: improve `expose_names` doc string
  src/Init/Tactics.lean
Labels: toolchain-available, changelog-no

#7011 feat: `simp +arith` for integers
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/LinearArith/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Simp.lean
  src/Lean/Meta/Tactic/LinearArith/Simp.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  tests/lean/run/2615.lean
  tests/lean/run/grind_regression.lean
  tests/lean/run/simp_int_arith.lean
Labels: toolchain-available, changelog-language

#7012 chore: improve `withAbstractAtoms`
  src/Lean/Meta/Tactic/LinearArith/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Simp.lean
  src/Lean/Meta/Tactic/LinearArith/Nat/Simp.lean
  tests/lean/run/simp_int_arith.lean
Labels: toolchain-available, changelog-language

#7003 chore: unprotect List.foldlM
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Control.lean
Labels: toolchain-available

#7015 feat: `simp +arith` normalizes coefficient in linear integer polynomials
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Simp.lean
  tests/lean/run/simp_int_arith.lean
Labels: toolchain-available, changelog-language

#6946 feat: basic support for handling enum inductives in bv_decide
  src/Init/Data/BitVec/Bitblast.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Enums.lean
  tests/lean/run/bv_enums.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7014 chore: add @[simp] to List.flatten_toArray
  src/Init/Data/Array/Lemmas.lean
Labels: toolchain-available

#7004 chore: replace HashMap.get_ lemmas with getElem_ versions
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
Labels: toolchain-available

#7018 chore: rename simp sets
  src/Lean/Elab/Tactic/BoolToPropSimps.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
Labels: toolchain-available

#7016 chore: `Task.get` block profiling
  src/library/time_task.cpp
  src/library/time_task.h
  src/runtime/object.cpp
  src/util/shell.cpp
Labels: builds-mathlib, toolchain-available

#7019 fix: correct trace nodes in bv_decide
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVCheck.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/LRAT.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Basic.lean
Labels: toolchain-available, changelog-language

#7013 feat: improvements to simp confluence
  src/Init/Data/Array/Attach.lean
  src/Init/Data/Array/Count.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Lex.lean
  src/Init/Data/Option/Attach.lean
  src/Init/Data/Vector/Attach.lean
  src/Init/Data/Vector/Lemmas.lean
  tests/lean/run/treeNode.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7021 feat: add basic extract theorems for bv_decide
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Enums.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Simproc.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#7022 chore: deprecated compile_time_search_path%
  src/Lean/Util/SearchPath.lean
Labels: toolchain-available

#7017 chore: rename simp sets
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/PropLemmas.lean
  src/Init/Tactics.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/omega.lean
Labels: toolchain-available, changelog-library

#7026 doc: misc. style guide and naming scheme additions
  doc/std/naming.md
  doc/std/style.md
Labels: toolchain-available, changelog-doc

#6744 feat: nested well-founded recursion via automatic preprocessing
  src/Init/ByCases.lean
  src/Init/Control/Basic.lean
  src/Init/Data/Array/Attach.lean
  src/Init/Data/List/Attach.lean
  src/Init/WF.lean
  src/Lean/Elab/PreDefinition/WF/AutoAttach.lean
  src/Lean/Elab/PreDefinition/WF/FloatRecApp.lean
  src/Lean/Elab/PreDefinition/WF/Ite.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/PreDefinition/WF/Preprocess.lean
  src/Lean/Elab/PreDefinition/WF/Unfold.lean
  src/Lean/Meta/BinderNameHint.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  tests/lean/run/wfWithSidecondition.lean
  tests/lean/run/wf_preprocess.lean
  tests/lean/run/wf_preprocess_leak.lean
  tests/lean/treeMap.lean.expected.out
Labels: builds-mathlib, toolchain-available, will-merge-soon, changelog-language

#7028 chore: trivial changes from async-proofs branch
  src/Lean.lean
  src/Lean/Elab/Term.lean
  src/Lean/Expr.lean
  src/Lean/Language/Lean.lean
  src/Lean/Replay.lean
  src/lean.mk.in
  src/library/elab_environment.h
Labels: toolchain-available

#6989 chore: build Lean with `Elab.async`
  src/stdlib.make.in
Labels: builds-mathlib, toolchain-available

#7024 feat: lake: provide help on Elan's `+` option
  src/lake/Lake/CLI/Error.lean
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Main.lean
Labels: builds-mathlib, toolchain-available, changelog-lake

#7030 feat: linear integer inequality normalization using `gcd` of coefficients
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Simp.lean
  tests/lean/run/simp_int_arith.lean
Labels: toolchain-available, changelog-language

#7033 feat: present bv_decide counter examples for UIntX and enums better
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  tests/lean/run/5674.lean
  tests/lean/run/bv_counterexample.lean
  tests/lean/run/bv_enums.lean
  tests/lean/run/bv_uint.lean
  tests/lean/run/bv_unused.lean
Labels: toolchain-available, changelog-language

#7040 feat: `simp +arith` sorts linear atoms
  src/Init/Data/Nat/Linear.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Simp.lean
  src/Lean/Meta/Tactic/LinearArith/Nat/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Nat/Simp.lean
  src/Lean/Util.lean
  src/Lean/Util/SortExprs.lean
  tests/lean/run/simp_int_arith.lean
  tests/lean/run/simp_nat_arith.lean
Labels: toolchain-available, changelog-language

#7042 chore: remove dead code from `Nat/Linear.lean`
  src/Init/Data/Nat/Linear.lean
  tests/lean/run/linearByRefl.lean
Labels: toolchain-available, changelog-no

#7043 chore: `simp_arith` has been deprecated
  doc/examples/bintree.lean
  src/Init/Data/Array/BasicAux.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Mem.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Sort/Lemmas.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Nat/Power2.lean
  src/Init/Meta.lean
  src/Init/SizeOfLemmas.lean
  src/Init/Tactics.lean
  src/Lean/Compiler/LCNF/AlphaEqv.lean
  src/Lean/Compiler/LCNF/PassManager.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/SimpArith.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  src/Std/Sat/AIG/CachedLemmas.lean
  src/Std/Sat/AIG/Lemmas.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Udiv.lean
  tests/lean/1081.lean
  tests/lean/allFieldForConstants.lean
  tests/lean/run/1228.lean
  tests/lean/run/1236.lean
  tests/lean/run/1302.lean
  tests/lean/run/2042.lean
  tests/lean/run/2615.lean
  tests/lean/run/addDecorationsWithoutPartial.lean
  tests/lean/run/bigop.lean
  tests/lean/run/binrec.lean
  tests/lean/run/caseTacInMacros.lean
  tests/lean/run/combinatorsAndWF.lean
  tests/lean/run/congrTactic.lean
  tests/lean/run/constProp.lean
  tests/lean/run/conv2.lean
  tests/lean/run/elabAsElim.lean
  tests/lean/run/grind_t1.lean
  tests/lean/run/inductionLetIssue.lean
  tests/lean/run/issue5384.lean
  tests/lean/run/lazyListRotateUnfoldProof.lean
  tests/lean/run/mergeSortCPDT.lean
  tests/lean/run/mutualDefThms.lean
  tests/lean/run/no_grind_constProp.lean
  tests/lean/run/posView.lean
  tests/lean/run/seval1.lean
  tests/lean/run/shrinkFn.lean
  tests/lean/run/simpArith1.lean
  tests/lean/run/simpArithCacheIssue.lean
  tests/lean/run/simpAutoUnfold.lean
  tests/lean/run/simp_arith_deprecated.lean
  tests/lean/run/simproc1.lean
  tests/lean/run/splitList.lean
  tests/lean/run/treeNode.lean
  tests/lean/run/unfoldMany.lean
  tests/lean/run/wfForIn.lean
  tests/lean/run/zetaDSimpIssue.lean
  tests/lean/splitIssue.lean
  tests/lean/wildcardAlt.lean
  tests/pkg/user_attr/UserAttr/Tst.lean
Labels: toolchain-available, changelog-language

#7044 chore: fix `linter.listVariables` naming
  src/Init/Data/Array/Lex/Basic.lean
  src/Init/Data/List/Monadic.lean
  src/Init/Data/List/Notation.lean
  src/Init/Data/List/OfFn.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Data/List/Perm.lean
  src/Init/Data/List/Range.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/List/ToArrayImpl.lean
  src/Init/Data/List/Zip.lean
  src/Lean/Linter/List.lean
  tests/lean/run/list_name_linter.lean
Labels: toolchain-available

#7034 feat: wf_preprocess for {List,Array}.Monadic functions
  src/Init/Data/Array/Monadic.lean
  src/Init/Data/List/Monadic.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7041 fix: make several LCNF environment extensions have asyncMode of .sync
  src/Lean/Compiler/LCNF/Passes.lean
  src/Lean/Compiler/LCNF/Simp/ConstantFold.lean
  src/Lean/Compiler/LCNF/SpecInfo.lean
  src/Lean/Compiler/LCNF/Specialize.lean
Labels: toolchain-available, changelog-compiler

#7047 chore: remove `save` tactic
  src/Init/Tactics.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Cache.lean
  src/Lean/Elab/Term.lean
  src/Lean/Language/Lean.lean
  src/Lean/Language/Lean/Types.lean
  src/Lean/Server/Snapshots.lean
  tests/playground/bool_exhaust_test.lean
Labels: toolchain-available, changelog-language

#7039 feat: propagate wfParam through let
  src/Lean/Elab/PreDefinition/WF/Preprocess.lean
  tests/lean/run/wf_preprocess.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, changelog-language

#7048 feat: `IntX.ofBitVec`
  src/Init/Data/SInt/Basic.lean
  tests/lean/sint_basic.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7046 chore: rename `UIntX.mk` -> `UIntX.ofBitVec`
  src/Init/Data/UInt/Basic.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Init/Prelude.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  tests/lean/run/trivial_uint.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7058 refactor: move `grind` offset constraint module to `Grind/Arith/Offset`
  src/Lean/Meta/Tactic/Grind/Arith/Model.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset/Main.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset/Model.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
Labels: toolchain-available, changelog-no

#7060 chore: upstream an Int lemma
  src/Init/Data/Int/Lemmas.lean
Labels: toolchain-available

#7050 chore: rename `UIntX.val` -> `UIntX.toFin`
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/FloatArray/Basic.lean
  src/Init/Data/UInt/Basic.lean
  src/Init/Data/UInt/BasicAux.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Init/Data/UInt/Log2.lean
  tests/lean/run/trivial_uint.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7053 feat: binderNameHint in congr
  src/Init/BinderNameHint.lean
  src/Lean/Meta/BinderNameHint.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/binderNameHint_congr.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7063 feat: missing conversion functions for `ISize`
  src/Init/Data/SInt/Basic.lean
  src/include/lean/lean.h
  tests/lean/run/sint_conversions.lean
Labels: toolchain-available, changelog-library

#7036 feat: deprecated find, fold, foldM, mergeBy functions for the tree map
  src/Std/Data/DTreeMap/Basic.lean
  src/Std/Data/DTreeMap/Raw.lean
  src/Std/Data/TreeMap/Basic.lean
  src/Std/Data/TreeMap/Raw.lean
  src/Std/Data/TreeSet/Basic.lean
  src/Std/Data/TreeSet/Raw.lean
Labels: toolchain-available, changelog-library

#7062 chore: make `IntX` constructor private, provide `UIntX.toIntX`
  src/Init/Data/SInt/Basic.lean
Labels: toolchain-available, changelog-library

#7064 chore: rename `BitVec.ofNatLt` -> `BitVec.ofNatLT`
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/UInt/BasicAux.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Init/Prelude.lean
  src/Lean/Meta/LitValues.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7067 doc: fix typo
  src/Init/Classical.lean
Labels: toolchain-available

#7068 chore: dsimproc for UIntX.ofNatLT
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/UInt.lean
  tests/lean/simprocEval3.lean
  tests/lean/simprocEval3.lean.expected.out
Labels: toolchain-available, changelog-library

#7061 feat: premise selection API
  src/Init/Notation.lean
  src/Init/Tactics.lean
  src/Lean.lean
  src/Lean/PremiseSelection.lean
  tests/lean/run/premise_selection.lean
Labels: toolchain-available, changelog-language

#7001 feat: lake: support plugins
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Imports.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/Target.lean
  src/lake/Lake/Build/Target/Basic.lean
  src/lake/Lake/Build/Target/Fetch.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/Config/Defaults.lean
  src/lake/Lake/Config/Dynlib.lean
  src/lake/Lake/Config/LeanConfig.lean
  src/lake/Lake/Config/LeanLib.lean
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Config/OutFormat.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Util/Family.lean
  src/lake/examples/ffi/test.sh
  src/lake/examples/targets/test.sh
  src/lake/tests/driver/test.sh
  src/lake/tests/globs/test.sh
  src/lake/tests/init/test.sh
  src/lake/tests/lean/test.sh
  src/lake/tests/noBuild/test.sh
  src/lake/tests/precompileArgs/test.sh
  src/lake/tests/trace/test.sh
  src/lake/tests/translateConfig/source.toml
  tests/pkg/frontend/Frontend/Compile.lean
  tests/pkg/user_attr_app/Main.lean
  tests/pkg/user_attr_app/test.sh
Labels: builds-mathlib, toolchain-available, release-ci, changelog-lake

#7077 feat: support theorems for cutsat `Div-Solve` rule
  src/Init/Data/Int.lean
  src/Init/Data/Int/Cutsat.lean
Labels: toolchain-available, changelog-language

#7078 feat: simprocs for `Int` and `Nat` divides predicates
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Nat/Dvd.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Nat.lean
  tests/lean/run/dvd_simproc.lean
Labels: toolchain-available, changelog-language

#7071 chore: rename `UIntX.ofNatCore`, `UIntX.ofNat'` -> `UIntX.ofNatLT`
  src/Init/Data/Char/Basic.lean
  src/Init/Data/Repr.lean
  src/Init/Data/UInt/Basic.lean
  src/Init/Data/UInt/BasicAux.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Init/Prelude.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/UInt.lean
  tests/lean/simprocEval3.lean
  tests/lean/simprocEval3.lean.expected.out
Labels: toolchain-available, changelog-library

#7051 feat: insertMany, ofList, ofArray, foldr, foldM functions for the tree map
  src/Std/Data/DTreeMap/Basic.lean
  src/Std/Data/DTreeMap/Internal/Operations.lean
  src/Std/Data/DTreeMap/Internal/WF/Def.lean
  src/Std/Data/DTreeMap/Raw.lean
  src/Std/Data/TreeMap/Basic.lean
  src/Std/Data/TreeMap/Raw.lean
  src/Std/Data/TreeSet/Basic.lean
  src/Std/Data/TreeSet/Raw.lean
Labels: toolchain-available, changelog-library

#7054 feat: request cancellation
  src/Lean/Server/CodeActions/Basic.lean
  src/Lean/Server/Completion.lean
  src/Lean/Server/Completion/CompletionCollectors.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/InlayHints.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/FileWorker/SemanticHighlighting.lean
  src/Lean/Server/RequestCancellation.lean
  src/Lean/Server/Requests.lean
Labels: toolchain-available, changelog-server

#7080 feat: `UIntX.ofNatTruncate`
  src/Init/Data/UInt/BasicAux.lean
Labels: toolchain-available, changelog-library

#7081 feat: `IntX.minValue`, `IntX.maxValue`, `IntX.ofIntLE`, `IntX.ofIntTruncate`
  src/Init/Data/SInt/Basic.lean
Labels: toolchain-available, changelog-library

#7079 feat: `Fin.toNat`
  src/Init/Data/Fin/Basic.lean
Labels: toolchain-available, changelog-library

#7074 feat: make binders in `#check` be hoverable
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
Labels: builds-mathlib, toolchain-available, changelog-pp

#7091 feat: add helper theorems for normalizing divisibility constraints
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Simp.lean
Labels: toolchain-available, changelog-language

#7088 fix: ensure `get_elem_tactic` works in absence of goals
  src/Init/Tactics.lean
  tests/lean/run/6999.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7092 feat: divisibility constraint normalizer
  src/Init/Data/Int/DivModLemmas.lean
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Nat/Dvd.lean
  src/Init/Omega/IntList.lean
  src/Lean/Expr.lean
  src/Lean/Meta/IntInstTesters.lean
  src/Lean/Meta/Tactic/LinearArith/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Simp.lean
  src/Lean/Meta/Tactic/LinearArith/Simp.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  tests/lean/run/simp_int_arith.lean
Labels: toolchain-available, changelog-language

#7093 refactor: `Int.Linear` module
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Simp.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  tests/lean/run/liaByRefl.lean
  tests/lean/run/simp_int_arith.lean
Labels: toolchain-available, changelog-no

#7094 refactor: add `denote'` functions to `Int/Linear.lean`
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Basic.lean
  src/Lean/Meta/Tactic/LinearArith/Int/Simp.lean
  tests/lean/run/liaByRefl.lean
  tests/lean/run/simp_int_arith.lean
Labels: toolchain-available, changelog-no

#7095 chore: cleanup and missing `grind` normalization rules
  src/Init/Data/Int/Linear.lean
  src/Init/Grind/Norm.lean
  tests/lean/run/grind_offset_cnstr.lean
Labels: toolchain-available, changelog-no

#5498 feat: make `BitVec.getElem` the simp normal form and use it in `ext`
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Folds.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Eq.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftRight.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Udiv.lean
  tests/lean/run/bitvec_simproc.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7097 feat: cutsat preparations
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Arith.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Inv.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Var.lean
  src/Lean/Meta/Tactic/Grind/Arith/Inv.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset.lean
  src/Lean/Meta/Tactic/Grind/Arith/Types.lean
  src/Lean/Meta/Tactic/LinearArith.lean
  src/Lean/Meta/Tactic/LinearArith/Nat.lean
  src/Lean/Meta/Tactic/LinearArith/Nat/Solver.lean
  src/Lean/Meta/Tactic/LinearArith/Solver.lean
  src/Lean/Meta/Tactic/Simp.lean
  src/Lean/Meta/Tactic/Simp/Arith.lean
  src/Lean/Meta/Tactic/Simp/Arith/Int.lean
  src/Lean/Meta/Tactic/Simp/Arith/Int/Basic.lean
  src/Lean/Meta/Tactic/Simp/Arith/Int/Simp.lean
  src/Lean/Meta/Tactic/Simp/Arith/Nat.lean
  src/Lean/Meta/Tactic/Simp/Arith/Nat/Basic.lean
  src/Lean/Meta/Tactic/Simp/Arith/Nat/Simp.lean
  src/Lean/Meta/Tactic/Simp/Arith/Util.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Util/SortExprs.lean
  tests/lean/run/liaByRefl.lean
  tests/lean/run/simpCnstr1.lean
  tests/lean/run/simp_int_arith.lean
Labels: toolchain-available, changelog-language
