Repository leanprover/lean4, pull requests merged in 2025-07, with the labels that each got.

#9116 chore: improve readability of a zipWith call
  src/Lean/Compiler/LCNF/SpecInfo.lean
Labels: toolchain-available

#9118 chore: begin development cycle for v4.23.0
  src/CMakeLists.txt
Labels: toolchain-available

#9112 chore: update doc/dev/ffi.md after #9088
  doc/dev/ffi.md
Labels: toolchain-available

#9119 chore: improvements to release automation
  script/release_checklist.py
Labels: toolchain-available

#9121 feat: `attribute [grind cases eager] PProd MProd`
  src/Init/Grind/Cases.lean
Labels: toolchain-available, changelog-library

#9123 chore: grind test case for matching Nat arguments
  tests/lean/grind/algebra/hyperoperations.lean
Labels: toolchain-available

#9094 chore: create iterator benchmark
  tests/bench/iterators.lean
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#9107 perf: add missing `std::move`s
  src/kernel/environment.h
  src/library/elab_environment.h
  src/runtime/pair_ref.h
Labels: toolchain-available

#9090 fix: match against app fn for reducing recursor in `whnfCore`
  src/Lean/Meta/WHNF.lean
  tests/lean/run/9089.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9128 fix: pretty-printing of `grind` syntax
  src/Init/Grind/Tactics.lean
  tests/lean/run/grind_pp_attr.lean
Labels: toolchain-available, changelog-no

#9133 feat: `pow_add` normalization in `grind`
  src/Lean/Expr.lean
  src/Lean/Meta/Tactic/Grind/Arith.lean
  src/Lean/Meta/Tactic/Grind/Arith/Simproc.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
  tests/lean/grind/algebra/hyperoperations.lean
  tests/lean/run/grind_bitvec2.lean
  tests/lean/run/grind_hyper_ex.lean
Labels: toolchain-available, changelog-language

#9131 feat: add `usedLetOnly` to `LocalContext` binder functions
  src/Lean/LocalContext.lean
Labels: builds-mathlib, toolchain-available, changelog-language, force-mathlib-ci

#9108 fix: account for namespaces/open decls in `inlineExpr`
  src/Lean/Message.lean
  tests/lean/run/inlineExpr.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9140 chore: cache IR types of named types
  src/Lean/Compiler/IR/ToIR.lean
  src/Lean/Compiler/IR/ToIRType.lean
Labels: toolchain-available

#9146 feat: polynomial operations with deep recursion and heartbeat checks
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/SafePoly.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Util.lean
  tests/lean/run/grind_big_poly.lean
Labels: toolchain-available, changelog-language

#9149 feat: `pow_add` for any semirings in `grind`
  src/Lean/Meta/Tactic/Grind/Arith/Simproc.lean
  tests/lean/run/grind_pow_add_semiring.lean
Labels: toolchain-available, changelog-language

#9151 chore: simproc and helper theorems for `grind`
  src/Init/Grind/Ring/Field.lean
  src/Lean/Meta/DecLevel.lean
  src/Lean/Meta/Tactic/Grind/Arith/Simproc.lean
  tests/lean/run/grind_pow_zero.lean
Labels: toolchain-available, changelog-no

#9152 doc: update obsolete docstring for `registerDerivingHandler`
  src/Lean/Elab/Deriving/Basic.lean
Labels: toolchain-available, changelog-doc

#9153 feat: improve linarith `markVars`
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Types.lean
  tests/lean/run/grind_linarith_spurious_issues.lean
Labels: toolchain-available, changelog-language

#9096 feat: remove unnecessary decidability requirements
  src/Init/Data/Array/Lex/Lemmas.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Lex.lean
  src/Init/Data/Vector/Lex.lean
Labels: toolchain-available, changelog-library, force-mathlib-ci

#9154 fix: tighten IR typing rules for applications of closures
  src/Lean/Compiler/IR/Checker.lean
  src/Lean/Compiler/IR/ToIR.lean
Labels: toolchain-available, changelog-compiler

#9157 fix: add groups around `simpLemma` and `grindLemma` syntax
  src/Init/Grind/Tactics.lean
  src/Init/Tactics.lean
  tests/lean/run/grind_trace.lean
  tests/lean/run/simpTrace.lean
Labels: toolchain-available, merge-ci, changelog-no

#9158 fix: use `patternIgnore(...)` in grind syntax
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
  stage0/src/stdlib_flags.h
Labels: builds-mathlib, toolchain-available, merge-ci, changelog-no

#9161 chore: fixes for #9158 after stage0 update
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
Labels: toolchain-available

#9162 refactor: lake: use `r` for `ir` key in content hashes
  src/lake/Lake/Build/ModuleArtifacts.lean
Labels: builds-mathlib, toolchain-available, changelog-lake

#9159 fix: don't inline computed fields `_override` implementations in base phase
  src/Lean/Compiler/LCNF/Simp/InlineCandidate.lean
Labels: toolchain-available, changelog-compiler

#9166 chore: add test for #9156 after stage0 update
  tests/lean/run/9156.lean
Labels: toolchain-available

#9167 chore: remove VarInfo defaults in IR RC pass
  src/Lean/Compiler/IR/RC.lean
Labels: toolchain-available

#9165 fix: lake: recreate static archives & use `T`, not `--thin`
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Util/IO.lean
Labels: builds-mathlib, toolchain-available, changelog-lake

#9169 feat: add `[grind symbol <prio>]` attribute
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/grind/grind_sym_prio.lean
Labels: toolchain-available, changelog-no

#9168 fix: refactor grind's module/ring design to avoid a diamond
  src/Init/Data/BitVec/Basic.lean
  src/Init/Grind/Module/Basic.lean
  src/Init/Grind/Module/Envelope.lean
  src/Init/Grind/Ordered/Linarith.lean
  src/Init/Grind/Ordered/Module.lean
  src/Init/Grind/Ordered/Ring.lean
  src/Init/Grind/Ring/Basic.lean
  src/Init/Grind/Ring/Envelope.lean
  src/Init/Grind/Ring/Field.lean
  src/Init/Grind/Ring/OfSemiring.lean
  src/Init/Grind/Ring/Poly.lean
  src/Init/GrindInstances/Ring/BitVec.lean
  src/Init/GrindInstances/Ring/Fin.lean
  src/Init/GrindInstances/Ring/Int.lean
  src/Init/GrindInstances/Ring/SInt.lean
  src/Init/GrindInstances/Ring/UInt.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Types.lean
  tests/lean/grind/algebra/nat_mod.lean
  tests/lean/run/async_base_functions.lean
  tests/lean/run/infoFromFailure.lean
  tests/lean/run/lossy_casts.lean
Labels: toolchain-available, changelog-language

#9172 fix: bug at `matchEqBwdPat`
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  tests/lean/run/grind_eq_bwd_pat_bug.lean
Labels: toolchain-available, changelog-language

#9145 fix: typos in Std.Classes.Ord.Basic
  src/Std/Classes/Ord/Basic.lean
Labels: toolchain-available, changelog-library

#9174 doc: use modern configuration syntax in the Simp.Config documentation
  src/Init/MetaTypes.lean
Labels: awaiting-review, toolchain-available

#9173 fix: exposed wellfounded recursion
  src/Lean/Meta/Transform.lean
  tests/lean/run/8938.lean
Labels: toolchain-available, changelog-language

#9106 fix: undefined symbol without `LEAN_USE_GMP`
  src/runtime/mpz.cpp
Labels: toolchain-available, changelog-other

#9017 refactor: replace some Subarray functions with generic slice functions
  src/Init/Data/Array/Subarray.lean
  src/Init/Data/Iterators/Consumers.lean
  src/Init/Data/Iterators/Consumers/Access.lean
  src/Init/Data/Iterators/Consumers/Stream.lean
  src/Init/Data/Iterators/ToIterator.lean
  src/Init/Data/Range/Polymorphic.lean
  src/Init/Data/Range/Polymorphic/Iterators.lean
  src/Init/Data/Range/Polymorphic/Stream.lean
  src/Init/Data/Slice/Array/Iterator.lean
  src/Init/Data/Slice/Array/Lemmas.lean
  src/Init/Data/Slice/Lemmas.lean
  src/Init/Data/Slice/Operations.lean
  src/Lean/Message.lean
  src/Lean/Util/Diff.lean
Labels: builds-mathlib, toolchain-available, breaks-manual, force-manual-ci

#9179 chore: CI: restore cache in `update-stage0`
  .github/workflows/build-template.yml
  .github/workflows/update-stage0.yml
Labels: toolchain-available

#9182 feat: pattern inference using symbol priorities in `grind`
  src/Init/Data/Array/Erase.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Lex/Lemmas.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Function.lean
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Data/Vector/Erase.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Data/Vector/Lex.lean
  src/Init/GetElem.lean
  src/Init/Grind.lean
  src/Init/Grind/Attr.lean
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  stage0/stdlib/Init/Data/Array/Lemmas.c
  stage0/stdlib/Init/Data/Function.c
  stage0/stdlib/Init/Data/Option/Basic.c
  stage0/stdlib/Init/Data/Option/Lemmas.c
  stage0/stdlib/Init/Grind.c
  stage0/stdlib/Init/Grind/Attr.c
  stage0/stdlib/Init/Grind/Tactics.c
  stage0/stdlib/Lean/Elab/Tactic/Grind.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/EMatchTheorem.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Main.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Types.c
  tests/lean/run/grind_bitvec2.lean
  tests/lean/run/grind_constProp.lean
  tests/lean/run/grind_getLast_dropLast.lean
  tests/lean/run/grind_issue_9125.lean
  tests/lean/run/grind_list.lean
  tests/lean/run/grind_list_find.lean
  tests/lean/run/grind_pattern1.lean
  tests/lean/run/grind_qsort.lean
  tests/lean/run/grind_regression.lean
  tests/lean/run/grind_trace.lean
  tests/lean/run/prelude-injectivity.lean
Labels: changes-stage0, changelog-language

#9183 chore: move test to `run`
  tests/lean/run/grind_sym_prio.lean
Labels: toolchain-available, changelog-no

#9184 fix: Scope `PostCond.total` to `Std.Do` by making it non-builtin
  src/Lean/Elab/Tactic/Do/Syntax.lean
  src/Std/Do/PostCond.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available, changelog-language

#9197 chore: #9196 part 2
  src/Init/Grind/Norm.lean
Labels: toolchain-available, changelog-no

#9198 fix: consider Prop-rebundled higher-order params to be fixed
  src/Lean/Compiler/LCNF/FixedParams.lean
  tests/lean/run/specFixedHOParamModuloErased.lean
Labels: toolchain-available, changelog-compiler

#9199 perf: unfold `GT.gt` and `GE.ge` in the `grind` normalizer
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available, changelog-no

#9200 perf: normalize `exists` expressions using a simproc in `grind`
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available, changelog-language

#9201 chore: remove old normalizers
  src/Init/Grind/Norm.lean
Labels: toolchain-available, changelog-no

#9203 chore: convert local functions to use `where` instead
  src/Lean/Compiler/IR/ToIR.lean
Labels: toolchain-available

#9202 perf: simproc for `grind` normalizations and decls to unfold
  src/Init/Data/Vector/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available, changelog-language

#9204 chore: replace custom instances with deriving for IR types
  src/Lean/Compiler/IR/Basic.lean
  src/Lean/Compiler/IR/Borrow.lean
  src/Lean/Compiler/IR/ElimDeadBranches.lean
  src/Lean/Compiler/IR/LiveVars.lean
Labels: toolchain-available

#9205 chore: remove old `grind` normalizers
  src/Init/Grind/Norm.lean
Labels: toolchain-available, changelog-no

#9209 fix: correctly handle constructor params in elimDeadBranches
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
  tests/lean/run/elimDeadBranchesCtorParams.lean
Labels: toolchain-available, changelog-compiler

#9210 chore: add `deriving Repr` to IR.Arg
  src/Lean/Compiler/IR/Basic.lean
Labels: toolchain-available

#9211 feat: track type class inference time in grind
  src/Lean/Meta/SynthInstance.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/RingId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/ToInt.lean
  src/Lean/Meta/Tactic/Grind/Arith/Insts.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Simproc.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Ext.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/LawfulEqCmp.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  src/Lean/Meta/Tactic/Grind/ReflCmp.lean
  src/Lean/Meta/Tactic/Grind/SynthInstance.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-no

#9213 chore: adopt do notation in IR checker
  src/Lean/Compiler/IR/Checker.lean
Labels: toolchain-available

#9214 feat: local and scoped `grind_pattern`
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Parser.lean
  stage0/stdlib/Lean/Compiler/IR/Basic.c
  stage0/stdlib/Lean/Compiler/IR/Borrow.c
  stage0/stdlib/Lean/Compiler/IR/Boxing.c
  stage0/stdlib/Lean/Compiler/IR/Checker.c
  stage0/stdlib/Lean/Compiler/IR/ElimDeadBranches.c
  stage0/stdlib/Lean/Compiler/IR/ElimDeadVars.c
  stage0/stdlib/Lean/Compiler/IR/EmitC.c
  stage0/stdlib/Lean/Compiler/IR/EmitLLVM.c
  stage0/stdlib/Lean/Compiler/IR/EmitUtil.c
  stage0/stdlib/Lean/Compiler/IR/ExpandResetReuse.c
  stage0/stdlib/Lean/Compiler/IR/LiveVars.c
  stage0/stdlib/Lean/Compiler/IR/PushProj.c
  stage0/stdlib/Lean/Compiler/IR/RC.c
  stage0/stdlib/Lean/Compiler/IR/ResetReuse.c
  stage0/stdlib/Lean/Compiler/IR/ToIR.c
  stage0/stdlib/Lean/Compiler/LCNF/ElimDeadBranches.c
  stage0/stdlib/Lean/Compiler/LCNF/ToMono.c
  stage0/stdlib/Lean/Elab/Tactic/Grind.c
  stage0/stdlib/Lean/Meta/SynthInstance.c
  stage0/stdlib/Lean/Meta/Tactic/Grind.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Arith/CommRing/RingId.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Arith/Cutsat/ToInt.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Arith/Insts.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Arith/Linear/PropagateEq.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Arith/Simproc.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Arith/Util.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/EMatch.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/EMatchTheorem.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Ext.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/ForallProp.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/LawfulEqCmp.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Lookahead.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Parser.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Propagate.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/ReflCmp.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/SynthInstance.c
  stage0/stdlib/Lean/Meta/Tactic/Grind/Types.c
  stage0/stdlib/Lean/Meta/Tactic/LibrarySearch.c
  tests/lean/run/grind_pattern3.lean
Labels: changes-stage0, changelog-language

#9219 chore: remove IRType.{isStruct,isUnion}
  src/Lean/Compiler/IR/Basic.lean
  src/Lean/Compiler/IR/Checker.lean
Labels: toolchain-available

#9221 fix: delete code with false assumption that LCNF local vars can occur in types
  src/Lean/Compiler/LCNF/ElimDead.lean
  src/Lean/Compiler/LCNF/Simp/Used.lean
Labels: toolchain-available, changelog-compiler

#9220 chore: use Array instead of PArray in elimDeadBranches state
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
Labels: toolchain-available

#9224 fix: erase args for erased app params in toMono
  src/Lean/Compiler/LCNF/ToMono.lean
Labels: toolchain-available, changelog-compiler

#9228 perf: generate `grind ring` instances on demand
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/PP.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/RingId.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Util.lean
  tests/lean/run/grind_const_pattern.lean
  tests/lean/run/grind_cutsat_diseq_2.lean
  tests/lean/run/grind_cutsat_div_1.lean
  tests/lean/run/grind_cutsat_eq_1.lean
  tests/lean/run/grind_cutsat_nat_le.lean
  tests/lean/run/grind_split_issue.lean
Labels: toolchain-available, changelog-language

#9229 chore: remove unused code in the axiom path of toIR
  src/Lean/Compiler/IR/ToIR.lean
Labels: toolchain-available

#9231 perf: bv_decide rewriting benchmark
  tests/bench/bv_decide_rewriter.lean
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available, changelog-no

#9237 chore: tests for #9206
  tests/lean/run/grind_cutsat_nat_eq.lean
Labels: toolchain-available, changelog-no

#9239 chore: consolidate `noncomputable` diagnostics
  src/Lean/Compiler/IR/ToIR.lean
  tests/lean/496.lean.expected.out
Labels: toolchain-available

#9240 chore: remove unreachable branches
  src/Lean/Compiler/IR/ToIR.lean
Labels: toolchain-available

#9242 chore: improve pattern matching
  src/Lean/Compiler/IR/ToIR.lean
Labels: toolchain-available

#9243 chore: reduce rightward drift
  src/Lean/Compiler/IR/ToIR.lean
Labels: toolchain-available

#9244 perf: optimize instance generation in `grind linarith`
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  tests/lean/run/grind_module_normalization.lean
Labels: toolchain-available, changelog-language

#9246 chore: profile `grind` satellite solvers
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Search.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
Labels: toolchain-available, changelog-no

#9249 feat: add `BitVec.clzAuxRec_eq_clzAuxRec_of_getLsbD_false`
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#9225 fix: let the `congr` tactic handle "under-applied" applications
  src/Init/Data/List/FinRange.lean
  src/Init/Data/List/Find.lean
  src/Lean/Meta/CongrTheorems.lean
  src/Lean/Meta/FunInfo.lean
  src/Lean/Meta/Tactic/Congr.lean
  src/Std/Data/Iterators/Lemmas/Equivalence/Basic.lean
  tests/lean/run/congrTactic.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#8842 fix: walk through types of axioms in `collectAxioms`
  src/Lean/Util/CollectAxioms.lean
  tests/lean/run/bv_axiom_check.lean
  tests/lean/run/collectAxioms.lean
  tests/lean/run/decideNative.lean
  tests/lean/run/nativeReflBackdoor.lean
Labels: toolchain-available, changelog-language

#9259 chore: clean up getDeclNamesForCodeGen
  src/Lean/Compiler/Old.lean
Labels: toolchain-available

#9262 chore: remove unnecessary include of ir_interpreter.h
  src/library/elab_environment.cpp
Labels: toolchain-available

#9268 fix: move lean_add_extern implementation to Lean
  src/Lean/Compiler/ExternAttr.lean
  src/Lean/Compiler/IR.lean
  src/Lean/Compiler/IR/AddExtern.lean
  src/library/compiler/ir.cpp
Labels: toolchain-available, changelog-compiler

#9270 chore: move llvm.cpp from library/compiler to library
  src/library/CMakeLists.txt
  src/library/compiler/CMakeLists.txt
  src/library/llvm.cpp
Labels: toolchain-available

#9272 chore: move compiler.extract_closed option from C++ to Lean
  src/Lean/Compiler/LCNF/ConfigOptions.lean
  src/Lean/Compiler/LCNF/ExtractClosed.lean
  src/library/compiler/compiler.cpp
Labels: toolchain-available

#9273 chore: move compiler.ir trace class registration to Lean
  src/Lean/Compiler/IR.lean
  src/Lean/Compiler/IR/Borrow.lean
  src/Lean/Compiler/IR/Boxing.lean
  src/Lean/Compiler/IR/ElimDeadBranches.lean
  src/Lean/Compiler/IR/ElimDeadVars.lean
  src/Lean/Compiler/IR/ExpandResetReuse.lean
  src/Lean/Compiler/IR/PushProj.lean
  src/Lean/Compiler/IR/RC.lean
  src/Lean/Compiler/IR/ResetReuse.lean
  src/Lean/Compiler/IR/SimpCase.lean
  src/library/compiler/compiler.cpp
Labels: toolchain-available

#9274 chore: remove options from 'run' tests that are now meaningless
  tests/lean/run/new_compiler.lean
  tests/lean/run/rc_tests.lean
Labels: toolchain-available

#9263 fix: typos in ISO 8601 formatted datetime (#9235)
  src/Std/Time/Format.lean
  tests/lean/run/timeFormats.lean
Labels: toolchain-available, changelog-library

#9277 chore: remove now-unused Lean.Compiler.ConstFolding
  src/Lean/Compiler.lean
  src/Lean/Compiler/ConstFolding.lean
Labels: toolchain-available

#9281 refactor: remove unnecessary export attributes
  src/Lean/Compiler/BorrowedAnnotation.lean
  src/Lean/Compiler/CSimpAttr.lean
  src/Lean/Compiler/ClosedTermCache.lean
  src/Lean/Compiler/ExportAttr.lean
  src/Lean/Compiler/ExternAttr.lean
  src/Lean/Compiler/IR.lean
  src/Lean/Compiler/ImplementedByAttr.lean
  src/Lean/Compiler/InitAttr.lean
  src/Lean/Compiler/NeverExtractAttr.lean
  src/Lean/Compiler/NoncomputableAttr.lean
  src/Lean/Compiler/Old.lean
  src/library/ir_interpreter.cpp
  src/library/util.cpp
  src/library/util.h
Labels: toolchain-available

#9284 chore: remove comment indicating that implicit conversion should be removed
  src/library/elab_environment.h
Labels: toolchain-available

#9289 refactor: remove unused addBoxedVersion variants
  src/Lean/Compiler/IR.lean
Labels: toolchain-available

#9290 refactor: use getEnv/modifyEnv more in IR
  src/Lean/Compiler/IR/CompilerM.lean
  src/Lean/Compiler/IR/ElimDeadBranches.lean
Labels: toolchain-available

#9291 refactor: base the IR phase of the compiler on CoreM
  src/Lean/Compiler/IR.lean
  src/Lean/Compiler/IR/Checker.lean
  src/Lean/Compiler/IR/CompilerM.lean
  src/Lean/Compiler/IR/Sorry.lean
  src/Lean/Compiler/LCNF/Main.lean
Labels: toolchain-available

#9293 perf: use custom `reduceCtorEq` simproc in `grind`
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
Labels: toolchain-available, changelog-language

#9285 fix: remove `BEq` from `(Array|Vector).(any|all)_push`
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#9305 perf: use `mkCongrSimpForConst?`
  src/Init/MetaTypes.lean
  src/Lean/Elab/PreDefinition/WF/Preprocess.lean
  src/Lean/Meta/CongrTheorems.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
Labels: toolchain-available, changelog-language

#9313 chore: clean up loop over ctor fields
  src/Lean/Compiler/IR/ToIR.lean
Labels: toolchain-available

#9319 chore: move Nat.succ lowering from toIR to toMono
  src/Lean/Compiler/IR/ToIR.lean
  src/Lean/Compiler/LCNF/ToMono.lean
Labels: toolchain-available

#9324 perf: `isDiseq` and `mkDiseqProof?` in `grind`
  src/Lean/Meta/Tactic/Grind/Diseq.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-language

#9325 perf: `propagateBoolDiseq`
  src/Lean/Meta/Tactic/Grind/Diseq.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
Labels: toolchain-available, changelog-language

#9326 perf: `propagateEqUp`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
Labels: toolchain-available, changelog-language

#9331 refactor: port IR Checker to CompilerM (and thus CoreM)
  src/Lean/Compiler/IR/Checker.lean
Labels: toolchain-available

#9335 chore: remove superfluous whitespace from error message
  src/Lean/Elab/MutualInductive.lean
Labels: toolchain-available, changelog-no

#9339 refactor: rename "irrelevant" to "erased" in IR
  src/Lean/Compiler/IR/Basic.lean
  src/Lean/Compiler/IR/Boxing.lean
  src/Lean/Compiler/IR/EmitC.lean
  src/Lean/Compiler/IR/EmitLLVM.lean
  src/Lean/Compiler/IR/Format.lean
  src/Lean/Compiler/IR/RC.lean
  src/Lean/Compiler/IR/ToIR.lean
  src/Lean/Compiler/IR/ToIRType.lean
Labels: toolchain-available

#9343 refactor: more "efficient" contraint propagation theorems
  src/Init/Data/Int/Linear.lean
Labels: toolchain-available, changelog-no

#9347 chore: remove leftovers
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/OfNat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  tests/lean/run/grind_cutsat_nat_le.lean
Labels: toolchain-available, changelog-no

#9349 chore: remove outdated comments
  src/Lean/Compiler/IR/Boxing.lean
Labels: toolchain-available

#9351 perf: use `inShareCommon` to skip preprocessing steps
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Grind/MarkNestedSubsingletons.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_getLast_dropLast.lean
Labels: toolchain-available, changelog-language

#9353 chore: Grove: update and enable on master
  .github/workflows/grove.yml
  doc/std/grove/GroveStdlib/Generated/associative-query-operations.lean
  doc/std/grove/lake-manifest.json
Labels: toolchain-available, changelog-no, grove

#9354 chore: Grove: add some data
  doc/std/grove/GroveStdlib/Generated.lean
  doc/std/grove/GroveStdlib/Generated/associative-all-operations-covered.lean
  doc/std/grove/GroveStdlib/Generated/associative-create-then-query.lean
  doc/std/grove/GroveStdlib/Generated/associative-creation-operations.lean
  doc/std/grove/GroveStdlib/Generated/associative-modification-operations.lean
  doc/std/grove/GroveStdlib/Generated/associative-query-operations.lean
  doc/std/grove/GroveStdlib/Std/CoreTypesAndOperations/Containers.lean
  doc/std/grove/lake-manifest.json
Labels: toolchain-available, changelog-no, grove

#9352 chore: CI: do not use large runners for secondary jobs
  .github/workflows/ci.yml
Labels: builds-mathlib, toolchain-available

#9359 doc: expand `elab_as_elim` docstring and fix typo
  src/Lean/Elab/App.lean
Labels: toolchain-available, changelog-no

#9367 perf: add `unfoldReducible'` using `inShareCommon`
  src/Lean/Meta/Tactic/Grind/Simp.lean
Labels: changelog-language

#9360 perf: allow boxed scalars passed to scalar params to be borrowed
  src/Lean/Compiler/IR/Borrow.lean
Labels: toolchain-available, changelog-compiler

#8263 feat: improve infer binder type failure message and range
  src/Lean/Elab/Binders.lean
  src/Lean/Elab/MutualDef.lean
  tests/lean/331.lean.expected.out
  tests/lean/autoImplicitCtorParamIssue.lean.expected.out
  tests/lean/holeErrors.lean.expected.out
  tests/lean/holes.lean.expected.out
  tests/lean/implicitTypePos.lean.expected.out
  tests/lean/interactive/2058.lean.expected.out
  tests/lean/multiConstantError.lean.expected.out
  tests/lean/run/2058.lean
  tests/lean/run/2226.lean
  tests/lean/run/5475.lean
  tests/lean/run/forInColErr.lean
  tests/lean/run/inferTypeFailure.lean
  tests/lean/run/structBinderUpdates.lean
  tests/lean/run/type_as_hole.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#9369 perf: skip unnecessary preprocessing steps in `grind` when possible
  src/Lean/Meta/Tactic/Grind/MarkNestedSubsingletons.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
Labels: changelog-language

#9190 doc: correct the `Option.getD` docString example
  src/Init/Prelude.lean
Labels: toolchain-available

#9385 perf: avoid `isDefEq` test at `simpEq` simproc used in `grind`
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
Labels: changelog-language

#9386 fix: improve error message when projecting from zero-field type
  src/Lean/Elab/App.lean
  tests/lean/run/9312.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9398 perf: avoid `inferType` at `simpArith`
  src/Lean/Meta/Tactic/Simp/Arith.lean
  src/Lean/Meta/Tactic/Simp/Arith/Int/Simp.lean
  src/Lean/Meta/Tactic/Simp/Arith/Nat/Simp.lean
  src/Lean/Meta/Tactic/Simp/Arith/Util.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
Labels: changelog-language

#9053 feat: lake: pre-resolve module imports
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Info.lean
  src/lake/Lake/Build/Job/Monad.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/tests/cache/Test.lean
  src/lake/tests/cache/Test/Imported.lean
  src/lake/tests/cache/test.sh
  src/lake/tests/lean/test.sh
  src/lake/tests/setupFile/ImportTest.lean
  src/lake/tests/setupFile/test.sh
Labels: builds-mathlib, toolchain-available, merge-ci, changelog-lake

#9100 refactor: `module`-ize `Std.Time`
  src/Std/Internal/Parsec.lean
  src/Std/Internal/Parsec/Basic.lean
  src/Std/Internal/Parsec/ByteArray.lean
  src/Std/Internal/Parsec/String.lean
  src/Std/Internal/Rat.lean
  src/Std/Time.lean
  src/Std/Time/Date.lean
  src/Std/Time/Date/Basic.lean
  src/Std/Time/Date/PlainDate.lean
  src/Std/Time/Date/Unit/Basic.lean
  src/Std/Time/Date/Unit/Day.lean
  src/Std/Time/Date/Unit/Month.lean
  src/Std/Time/Date/Unit/Week.lean
  src/Std/Time/Date/Unit/Weekday.lean
  src/Std/Time/Date/Unit/Year.lean
  src/Std/Time/Date/ValidDate.lean
  src/Std/Time/DateTime.lean
  src/Std/Time/DateTime/PlainDateTime.lean
  src/Std/Time/DateTime/Timestamp.lean
  src/Std/Time/Duration.lean
  src/Std/Time/Format.lean
  src/Std/Time/Format/Basic.lean
  src/Std/Time/Internal.lean
  src/Std/Time/Internal/Bounded.lean
  src/Std/Time/Internal/UnitVal.lean
  src/Std/Time/Notation.lean
  src/Std/Time/Notation/Spec.lean
  src/Std/Time/Time.lean
  src/Std/Time/Time/Basic.lean
  src/Std/Time/Time/HourMarker.lean
  src/Std/Time/Time/PlainTime.lean
  src/Std/Time/Time/Unit/Basic.lean
  src/Std/Time/Time/Unit/Hour.lean
  src/Std/Time/Time/Unit/Millisecond.lean
  src/Std/Time/Time/Unit/Minute.lean
  src/Std/Time/Time/Unit/Nanosecond.lean
  src/Std/Time/Time/Unit/Second.lean
  src/Std/Time/Zoned.lean
  src/Std/Time/Zoned/Database.lean
  src/Std/Time/Zoned/Database/Basic.lean
  src/Std/Time/Zoned/Database/TZdb.lean
  src/Std/Time/Zoned/Database/TzIf.lean
  src/Std/Time/Zoned/Database/Windows.lean
  src/Std/Time/Zoned/DateTime.lean
  src/Std/Time/Zoned/Offset.lean
  src/Std/Time/Zoned/TimeZone.lean
  src/Std/Time/Zoned/ZoneRules.lean
  src/Std/Time/Zoned/ZonedDateTime.lean
Labels: toolchain-available

#9403 perf: add a benchmark for simp on local hypotheses
  tests/bench/simp_local.lean
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available, changelog-no

#9408 perf: avoid "dependent implications" as local E-matching theorems in `grind`
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
Labels: changelog-language

#9411 feat: compiler support for casesOn of subsingletons
  src/Lean/Compiler/LCNF/ToLCNF.lean
  tests/lean/run/subsingletonCasesOn.lean
Labels: changelog-compiler

#9315 feat: add named argument hints
  src/Lean/Elab/App.lean
  src/Lean/Elab/Arg.lean
  src/Lean/Elab/Match.lean
  src/Lean/Elab/PatternVar.lean
  src/Lean/Meta/Hint.lean
  tests/lean/invalidNamedArgs.lean
  tests/lean/invalidNamedArgs.lean.expected.out
  tests/lean/nameArgErrorIssue.lean.expected.out
  tests/lean/run/matchPatternVarErrors.lean
  tests/lean/run/patternInvalidNamedArg.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9316 feat: add case name hints
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  tests/lean/caseSuggestions.lean
  tests/lean/caseSuggestions.lean.expected.out
  tests/lean/run/allGoals.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9317 feat: add hints for missing structure instance fields
  src/Lean/Elab.lean
  src/Lean/Elab/StructInst.lean
  src/Lean/Elab/StructInstHint.lean
  tests/lean/instance1.lean.expected.out
  tests/lean/interactive/structInstFieldHints.lean
  tests/lean/interactive/structInstFieldHints.lean.expected.out
  tests/lean/run/461b.lean
  tests/lean/run/structInst.lean
  tests/lean/semicolonOrLinebreak.lean.expected.out
  tests/lean/setLit.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language

#9414 perf: `isArrowProposition`
  src/Lean/Meta/InferType.lean
Labels: changelog-language

#9397 fix: lake: test script bugs w/ Mathlib & non-Linux
  src/lake/Lake/CLI/Init.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/tests/cache/test.sh
  src/lake/tests/common.sh
  src/lake/tests/env/test.sh
  src/lake/tests/init/test.sh
  src/lake/tests/inputFile/clean.sh
  src/lake/tests/inputFile/test.sh
  src/lake/tests/noRelease/clean.sh
  src/lake/tests/noRelease/test.sh
  src/lake/tests/reservoirConfig/clean.sh
  src/lake/tests/reservoirConfig/test.sh
  src/lake/tests/versionTags/clean.sh
  src/lake/tests/versionTags/test.sh
Labels: toolchain-available, release-ci, changelog-no

#9404 perf: simp subexpr benchmark
  tests/bench/simp_subexpr.lean
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available, changelog-no

#9361 chore: benchmark using `USE_LAKE`
  .github/workflows/build-template.yml
  script/bench.sh
  src/CMakeLists.txt
  src/lakefile.toml.in
  src/stdlib.make.in
  tests/bench/speedcenter.exec.velcom.yaml
Labels: builds-mathlib, toolchain-available

#9421 fix: open error explanations in new window in web editor
  src/Lean/Log.lean
Labels: toolchain-available, changelog-language

#9422 chore: lake: module system tests & fixes
  src/Lean/Elab/ParseImportsFast.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Config/OutFormat.lean
  src/lake/tests/cache/Module.lean
  src/lake/tests/cache/lakefile.toml
  src/lake/tests/cache/test.sh
  src/lake/tests/module/.gitignore
  src/lake/tests/module/Test/ModuleImport.lean
  src/lake/tests/module/Test/ModuleImportAll.lean
  src/lake/tests/module/Test/ModulePrivateImport.lean
  src/lake/tests/module/Test/ModulePromoteImport.lean
  src/lake/tests/module/Test/ModuleTransPrivateImport.lean
  src/lake/tests/module/Test/ModuleTransPromoteImport.lean
  src/lake/tests/module/Test/NonModuleImport.lean
  src/lake/tests/module/Test/NonModuleTransImport.lean
  src/lake/tests/module/clean.sh
  src/lake/tests/module/lakefile.toml
  src/lake/tests/module/test.sh
Labels: builds-mathlib, toolchain-available, changelog-no

#9234 chore: reintroduce Subarray.foldl on top of Slice.foldl
  src/Init/Data/Array/Subarray.lean
  src/Init/Data/Range/Polymorphic/Iterators.lean
  src/Init/Data/Slice/Array/Iterator.lean
Labels: builds-mathlib, toolchain-available

#9431 fix: make IRType.erased a tobject when boxing it
  src/Lean/Compiler/IR/Basic.lean
  tests/lean/computedFieldsCode.lean.expected.out
Labels: changelog-no

#9387 feat: add hints for tuple projections
  src/Lean/Elab/App.lean
  tests/lean/run/invalidProjection.lean
  tests/lean/run/invalidTupleProjHints.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9436 feat: lake: job count in build success message
  src/lake/Lake/Build/Context.lean
  src/lake/Lake/Build/Run.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/examples/targets/test.sh
  src/lake/tests/noRelease/test.sh
Labels: builds-mathlib, toolchain-available, changelog-lake

#9447 fix: Close pure, trivial goals in `mvcgen` (#9362)
  src/Lean/Elab/Tactic/Do/VCGen.lean
  tests/lean/run/9362.lean
Labels: changelog-language

#9441 fix: behavior of `String.prev`
  src/Init/Data/String/Basic.lean
  src/runtime/object.cpp
  tests/lean/run/string.lean
Labels: awaiting-review, toolchain-available, changelog-library

#9040 feat: improved go to definition
  src/Lean/Data/JsonRpc.lean
  src/Lean/Data/Lsp/Internal.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/FileWorker/WidgetRequests.lean
  src/Lean/Server/GoTo.lean
  src/Lean/Server/InfoUtils.lean
  src/Lean/Server/Watchdog.lean
  stage0/src/stdlib_flags.h
  tests/lean/interactive/definition.lean.expected.out
  tests/lean/interactive/goTo.lean
  tests/lean/interactive/goTo.lean.expected.out
  tests/lean/interactive/goTo2.lean
  tests/lean/interactive/goTo2.lean.expected.out
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/interactive/jumpMutual.lean.expected.out
Labels: toolchain-available, changelog-server

#9457 perf: update type information in cases arms for RC optimizations
  src/Lean/Compiler/IR/RC.lean
Labels: toolchain-available

#9461 perf: make function types object rather than tobject
  src/Lean/Compiler/IR/ToIRType.lean
  tests/lean/computedFieldsCode.lean.expected.out
Labels: toolchain-available

#9449 fix: behavior of `String.next`
  src/runtime/object.cpp
  tests/lean/run/string.lean
Labels: toolchain-available, changelog-library

#9356 perf: minimize exported codegen data
  .github/workflows/build-template.yml
  src/Lean/Compiler/IR.lean
  src/Lean/Compiler/IR/AddExtern.lean
  src/Lean/Compiler/IR/CompilerM.lean
  src/Lean/Compiler/IR/ElimDeadBranches.lean
  src/Lean/Compiler/IR/Meta.lean
  src/Lean/Compiler/ImplementedByAttr.lean
  src/Lean/Compiler/LCNF/Basic.lean
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
  src/Lean/Compiler/LCNF/Passes.lean
  src/Lean/Compiler/LCNF/PhaseExt.lean
  src/Lean/Compiler/LCNF/Visibility.lean
  src/Lean/Environment.lean
  stage0/src/stdlib_flags.h
  tests/pkg/misc/Misc.lean
  tests/pkg/misc/Misc/Foo.lean
  tests/pkg/rebuild/.gitignore
  tests/pkg/rebuild/Rebuild.lean
  tests/pkg/rebuild/lakefile.toml
  tests/pkg/rebuild/lean-toolchain
  tests/pkg/rebuild/test.sh
Labels: builds-mathlib, toolchain-available

#9464 fix: PProdN.reduceProjs to also look for projection functions
  src/Lean/Meta/PProdN.lean
  tests/lean/run/issue9462.lean
Labels: toolchain-available, changelog-language

#9476 fix: `assertNatCast` in `grind`
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  tests/lean/run/grind_9467.lean
Labels: changelog-language

#9478 feat: lake: `meta import` support
  src/Lean/Environment.lean
  src/Lean/Setup.lean
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Module.lean
  src/lake/tests/cache/test.sh
  src/lake/tests/module/Test/ModuleMetaImport.lean
  src/lake/tests/module/Test/ModuleMetaTransImport.lean
  src/lake/tests/module/Test/ModulePrivateMetaImport.lean
  src/lake/tests/module/Test/ModulePromoteImport.lean
  src/lake/tests/module/Test/ModuleTransMetaImport.lean
  src/lake/tests/module/Test/ModuleTransPrivateMetaImport.lean
  src/lake/tests/module/test.sh
  src/lake/tests/toml/Test.lean
Labels: toolchain-available, changelog-lake

#9084 fix: add `binrel%` macros for notation in `Init.Core`
  src/Init/Core.lean
Labels: builds-mathlib, toolchain-available, P-medium, changelog-language

#9479 fix: improve `evalInt?`
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/ToInt.lean
  src/Lean/Meta/Tactic/Grind/Arith/EvalNum.lean
  src/Lean/Meta/Tactic/Grind/Arith/Insts.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Clause.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/grind_9427.lean
Labels: changelog-language

#9468 refactor: private field use in `Meta.Context`
  src/Lean/Elab/Command.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/LazyDiscrTree.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available

#9482 chore: disable artifacts cache for building stage2+
  src/CMakeLists.txt
Labels: toolchain-available

#9465 perf: do not export specializations
  src/Lean/Compiler/IR/EmitC.lean
  src/Lean/Compiler/LCNF/MonoTypes.lean
  src/Lean/Compiler/LCNF/Specialize.lean
  src/Lean/Compiler/LCNF/Visibility.lean
  tests/lean/lcnfTypes.lean.expected.out
  tests/pkg/rebuild/test.sh
Labels: toolchain-available

#8391 feat: unexpand `Vector.mk #[...] _` to `#v[...]`
  src/Init/Data/Vector/Basic.lean
  tests/lean/run/ppVector.lean
Labels: builds-mathlib, toolchain-available, P-medium, changelog-pp

#9480 feat: custom `structure` constructors can update binder kinds of parameters
  src/Lean/Elab/Structure.lean
  src/Lean/Parser/Command.lean
  tests/lean/run/structBinderUpdates.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9487 fix: incorrect proof term in `grind linarith`
  src/Lean/Meta/Tactic/Grind/Arith/Linear/PropagateEq.lean
  tests/lean/run/grind_9485.lean
Labels: toolchain-available, changelog-language

#9443 feat: make cdot expansion take hygiene into account
  src/Init/Data/List/MinMax.lean
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Elab/Extra.lean
  src/Lean/Elab/Notation.lean
  src/Lean/Elab/Quotation/Precheck.lean
  src/Lean/Elab/Term.lean
  src/Lean/Parser/Term.lean
  tests/lean/notationDelab.lean
  tests/lean/run/Reparen.lean
  tests/lean/run/cdotTests.lean
Labels: builds-mathlib, toolchain-available, changelog-language
