Repository leanprover/lean4, pull requests merged in 2025-09, with the labels that each got.

#10184 perf: use matcher as splitter
  src/Lean/Meta/Match/MatchEqs.lean
Labels: builds-mathlib, toolchain-available

#10205 feat: critical pairs for `grind ac`
  src/Lean/Meta/Tactic/Grind/AC.lean
  src/Lean/Meta/Tactic/Grind/AC/Eq.lean
  src/Lean/Meta/Tactic/Grind/AC/Proof.lean
  src/Lean/Meta/Tactic/Grind/AC/Seq.lean
  src/Lean/Meta/Tactic/Grind/AC/Types.lean
  tests/lean/run/grind_ac_1.lean
  tests/lean/run/grind_ac_3.lean
Labels: changelog-language

#10206 feat: critical pairs (non commutative case) for `grind ac`
  src/Init/Grind/AC.lean
  src/Lean/Meta/Tactic/Grind/AC/Eq.lean
  src/Lean/Meta/Tactic/Grind/AC/Proof.lean
  src/Lean/Meta/Tactic/Grind/AC/Seq.lean
  src/Lean/Meta/Tactic/Grind/AC/Types.lean
  tests/lean/run/grind_ac_4.lean
Labels: changelog-language

#10207 chore: cleanup `superposeAC?`
  src/Init/Grind/AC.lean
  src/Lean/Meta/Tactic/Grind/AC/Eq.lean
  src/Lean/Meta/Tactic/Grind/AC/Proof.lean
  src/Lean/Meta/Tactic/Grind/AC/Seq.lean
  src/Lean/Meta/Tactic/Grind/AC/Types.lean
Labels: changelog-no

#10194 feat: (approximate) inverses of dyadic rationals
  src/Init/Data/Dyadic.lean
  src/Init/Data/Dyadic/Basic.lean
  src/Init/Data/Dyadic/Inv.lean
  src/Init/Data/Int/DivMod/Bootstrap.lean
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/Rat/Basic.lean
  src/Init/Data/Rat/Lemmas.lean
  src/Init/Grind/Ring/Poly.lean
  src/Init/Omega/Int.lean
Labels: breaks-mathlib, toolchain-available, changelog-library

#9127 chore: demote a panic to an exception in saveModuleData
  src/runtime/compact.cpp
Labels: toolchain-available, changelog-library

#10218 perf: `EqCnstr.superposeWith`
  src/Lean/Meta/Tactic/Grind/AC/Eq.lean
  tests/lean/run/grind_ac_2.lean
Labels: changelog-no

#10214 fix: make csimp equivalence criteria more strict
  src/Lean/Compiler/CSimpAttr.lean
  tests/lean/run/10213.lean
Labels: toolchain-available, changelog-compiler

#10223 feat: equality propagation from AC module to grind core
  src/Init/Grind/AC.lean
  src/Lean/Meta/Tactic/Grind/AC.lean
  src/Lean/Meta/Tactic/Grind/AC/Eq.lean
  src/Lean/Meta/Tactic/Grind/AC/Internalize.lean
  src/Lean/Meta/Tactic/Grind/AC/Proof.lean
  src/Lean/Meta/Tactic/Grind/AC/Types.lean
  tests/lean/run/grind_ac_1.lean
  tests/lean/run/grind_ac_2.lean
  tests/lean/run/grind_ac_4.lean
Labels: changelog-language

#10224 feat: generalize universes in monadic operators for collections
  src/Lean/Data/AssocList.lean
  src/Lean/Data/PersistentHashSet.lean
  src/Lean/Data/RBMap.lean
  src/Lean/Data/SMap.lean
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Basic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Lemmas.lean
  src/Std/Data/DHashMap/Internal/Defs.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/DTreeMap/Internal/Balancing.lean
  src/Std/Data/DTreeMap/Internal/Lemmas.lean
  src/Std/Data/DTreeMap/Internal/Operations.lean
  src/Std/Data/DTreeMap/Internal/Queries.lean
  src/Std/Data/DTreeMap/Internal/WF/Defs.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/Raw.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Basic.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/Raw.lean
  src/Std/Data/HashSet/RawLemmas.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#10228 feat: support visibility modifiers on syntax abbrevs
  src/Lean/Elab/Syntax.lean
  src/Lean/Parser/Syntax.lean
Labels: changelog-no

#10229 perf: do not export `EqnInfo` for non-exposed defs
  src/Lean/Elab/PreDefinition/PartialFixpoint/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/EnvExtension.lean
  src/Lean/Environment.lean
  src/Lean/ResolveName.lean
  tests/pkg/rebuild/test.sh
Labels: toolchain-available

#10237 fix: `grind` canonicalizer
  src/Lean/Meta/Tactic/Grind/Canon.lean
  tests/lean/run/grind_10232.lean
Labels: changelog-language

#10239 fix: universe polymorphic E-matching
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  tests/lean/run/grind_10233.lean
Labels: changelog-language

#8891 feat: improve error message when passing local hypotheses to `grind`
  src/Lean/Elab/Tactic/Grind.lean
  tests/lean/run/grind_local_hyps.lean
Labels: toolchain-available, changelog-language

#10241 chore: add test cases for `grind` on `Fin` lemmas
  src/Init/Data/Array/Find.lean
  src/Init/Data/Fin/Lemmas.lean
  tests/lean/grind/grind_fin.lean
  tests/lean/run/grind_fin.lean
Labels: changelog-language

#10250 fix: solve two problems with `LinearOrderPackage` factories
  src/Init/Data/Order/PackageFactories.lean
  tests/lean/run/order.lean
Labels: changelog-library

#10251 chore: fix typo
  src/Init/Grind/Attr.lean
Labels: changelog-no

#10263 fix: `meta structure/inductive` should create `meta` ctor
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/Structure.lean
Labels: changelog-no

#10267 feat: infrastructure for `NatModule` in `grind linarith`
  src/Init/Grind/Module/Envelope.lean
  src/Init/Grind/Module/OfNatModule.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/IneqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Inv.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/LinearM.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/MBTC.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Model.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/OfNatModule.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/PP.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/PropagateEq.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/SearchM.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/ToExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Var.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/VarRename.lean
  tests/lean/run/grind_nat_module.lean
Labels: changelog-language

#10262 feat: `maxErrors` option
  src/Lean/Language/Basic.lean
  src/lakefile.toml.in
  tests/lean/run/errorExplanationElab.lean
Labels: changelog-other

#10260 fix: do not apply private instances in public scope
  src/Lean/Meta/SynthInstance.lean
Labels: toolchain-available, changelog-no

#10273 fix: casesOnSameCtor: export if not private
  src/Lean/Meta/Constructions/CasesOnSameCtor.lean
Labels: changelog-language

#10275 refactor: lake: rm `public syntax` workarounds
  src/lake/Lake/Config/Meta.lean
  src/lake/Lake/DSL/DeclUtil.lean
  src/lake/Lake/DSL/Syntax.lean
Labels: changelog-no

#10278 feat: `NatModule` inequalities and equalities in `grind linarith`
  src/Lean/Meta/Tactic/Grind/Arith/Linear/IneqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/OfNatModule.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/PropagateEq.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Types.lean
  tests/lean/run/grind_nat_module.lean
  tests/lean/run/grind_nat_module_2.lean
Labels: changelog-language

#10274 refactor: use `match decEq`, not `if h :` in `deriving DecidableEq`
  src/Lean/Elab/Deriving/DecEq.lean
  tests/lean/decEqMutualInductives.lean.expected.out
  tests/lean/run/derivingDecidableEq.lean
  tests/lean/run/derivingDecidableEqLinear.lean
Labels: breaks-mathlib, toolchain-available, changelog-language

#10276 refactor: lake: mv `verLit` into the `DSL` namespace
  src/lake/Lake/DSL/Syntax.lean
  src/lake/Lake/DSL/VerLit.lean
Labels: builds-mathlib, toolchain-available, changelog-lake

#10280 feat: `NatModule` equation normalization theorem
  src/Init/Grind/Module.lean
  src/Init/Grind/Module/NatModuleNorm.lean
Labels: changelog-language

#10282 feat: improve `grind linarith` counterexamples for `NatModule`
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Model.lean
  src/Lean/Meta/Tactic/Grind/Arith/ModelUtil.lean
  tests/lean/run/grind_nat_module.lean
Labels: changelog-language

#10283 feat: `grind ac` module diagnostics
  src/Lean/Meta/Tactic/Grind/AC.lean
  src/Lean/Meta/Tactic/Grind/AC/PP.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_sort_eqc.lean
Labels: changelog-language

#10284 test: `grind ac` diagnostics
  tests/lean/run/grind_ac_5.lean
Labels: changelog-no

#10264 chore: move `String.utf8EncodeChar` to the prelude
  src/Init/Data/BitVec/BasicAux.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Div/Basic.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/String/Extra.lean
  src/Init/Data/UInt/BasicAux.lean
  src/Init/GrindInstances/Ring/UInt.lean
  src/Init/Prelude.lean
  src/lake/Lake/Reservoir.lean
  tests/lean/librarySearch.lean
  tests/lean/run/PPTopDownAnalyze.lean
  tests/lean/run/grind_bitvec2.lean
Labels: changelog-no

#10289 chore: reorganize `Init` imports around strings
  src/Init/Control/EState.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/Bool.lean
  src/Init/Data/ByteArray.lean
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/ByteArray/Extra.lean
  src/Init/Data/Char/Lemmas.lean
  src/Init/Data/Format/Basic.lean
  src/Init/Data/Format/Instances.lean
  src/Init/Data/Format/Syntax.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Random.lean
  src/Init/Data/Repr.lean
  src/Init/Data/Stream.lean
  src/Init/Data/String.lean
  src/Init/Data/String/Basic.lean
  src/Init/Data/String/Lemmas.lean
  src/Init/Data/String/Repr.lean
  src/Init/Data/ToString.lean
  src/Init/Data/ToString/Basic.lean
  src/Init/Data/ToString/Name.lean
  src/Init/Grind/PP.lean
  src/Init/Meta.lean
  src/Init/Omega/Constraint.lean
  src/Init/Omega/LinearCombo.lean
  src/Init/Simproc.lean
  src/Init/System/FilePath.lean
  src/Init/System/IOError.lean
  src/Init/System/Platform.lean
  src/Init/Util.lean
  src/Lean/Compiler/FFI.lean
  src/Lean/Data/FuzzyMatching.lean
  src/Lean/Data/KVMap.lean
  src/Lean/Data/LOption.lean
  src/Lean/Data/OpenDecl.lean
  src/Lean/Data/PersistentArray.lean
  src/Lean/Data/PersistentHashMap.lean
  src/Lean/InternalExceptionId.lean
  src/Lean/LabelAttribute.lean
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  src/Lean/Server/FileWorker/Utils.lean
  src/Lean/Util/Path.lean
  src/Std/Internal/Async/Select.lean
  src/Std/Internal/Parsec/Basic.lean
  src/Std/Internal/Parsec/String.lean
  src/Std/Tactic/BVDecide/Bitblast/BoolExpr/Basic.lean
  src/Std/Time/Zoned/Database/TzIf.lean
  src/lake/Lake/CLI/Error.lean
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/Config/Dependency.lean
  src/lake/Lake/Config/InputFileConfig.lean
  src/lake/Lake/Util/Cli.lean
  src/lake/Lake/Util/Cycle.lean
  src/lake/Lake/Util/Family.lean
  src/lake/Lake/Version.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available, changelog-no

#10269 chore: don't include redundant empty strings in string interpolation
  src/Init/Meta.lean
  tests/lean/run/strInterpolation.lean
Labels: awaiting-review, toolchain-available, changelog-language

#10309 feat: intermediate tactic info on simpa
  src/Lean/Elab/Tactic/Simpa.lean
  tests/lean/interactive/plainGoal.lean
  tests/lean/interactive/plainGoal.lean.expected.out
  tests/lean/run/5634.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#10320 fix: bug at `assignUnassignedLevelMVars` in `grind`
  src/Lean/Meta/Tactic/Grind/EMatch.lean
Labels: changelog-no

#10322 feat: `cutsat` and `grobner` frontends for `grind`
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  tests/lean/run/grind_cutsat_tests.lean
  tests/lean/run/grind_ring_2.lean
Labels: toolchain-available, changelog-language

#10162 chore: remove over-eager grind lemma `eq_empty_of_append_eq_empty`
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  tests/lean/run/grind_list2.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#10292 chore: add grind test for numeral normalization
  tests/lean/run/grind_canon_ofnat.lean
Labels: toolchain-available

#10261 fix: further exporting control
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Environment.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
Labels: toolchain-available, merge-ci, changelog-no

#10217 fix: run `@[init]` declarations in declaration order
  src/Lean/Attributes.lean
  src/Lean/Compiler/InitAttr.lean
Labels: builds-mathlib, toolchain-available, changelog-other

#10328 doc: testing Lean while avoiding rebuilds for downstream projects
  doc/dev/index.md
Labels: builds-mathlib, toolchain-available

#10335 fix: over applied `Grind.nestedProof` marker
  src/Lean/Meta/Tactic/Grind/MarkNestedSubsingletons.lean
  tests/lean/run/grind_over_applied_nestedProof.lean
Labels: changelog-language

#10371 refactor: import `Lake.Util.*` from `Lake`
  src/lake/Lake.lean
  src/lake/Lake/Util.lean
  src/lakefile.toml.in
Labels: toolchain-available, changelog-no

#10373 feat: add `unicode(...)` parser syntax and `pp.unicode` option
  src/Init/Prelude.lean
  src/Lean/Elab/DocString/Builtin.lean
  src/Lean/Elab/Mixfix.lean
  src/Lean/Elab/Notation.lean
  src/Lean/Elab/Syntax.lean
  src/Lean/Parser.lean
  src/Lean/Parser/Basic.lean
  src/Lean/Parser/Extension.lean
  src/Lean/Parser/Syntax.lean
  src/Lean/Parser/Term.lean
  src/Lean/ParserCompiler.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  src/Lean/PrettyPrinter/Formatter.lean
  src/Lean/PrettyPrinter/Parenthesizer.lean
  tests/lean/242.lean
  tests/lean/242.lean.expected.out
  tests/lean/run/ppUnicode.lean
Labels: breaks-mathlib, toolchain-available, changelog-language, changelog-pp

#10306 fix: make `rw` collect only new goals, occurs check
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Fin/Fold.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Conv/Rewrite.lean
  src/Lean/Elab/Tactic/Rewrite.lean
  src/Lean/Meta/Tactic/Rewrite.lean
  src/Std/Data/DTreeMap/Internal/Lemmas.lean
  src/Std/Sat/AIG/CachedGatesLemmas.lean
  src/Std/Sat/AIG/If.lean
  src/Std/Sat/AIG/RefVecOperator/Map.lean
  src/Std/Sat/AIG/RefVecOperator/Zip.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Add.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Const.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Add.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Extract.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Mul.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Replicate.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/RotateLeft.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/RotateRight.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftLeft.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftRight.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Udiv.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Ult.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Umod.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ZeroExtend.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Var.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  tests/lean/run/10172.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#10374 feat: add option `pp.piBinderNames`
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  tests/lean/276.lean.expected.out
  tests/lean/eagerCoeExpansion.lean.expected.out
  tests/lean/run/meta1.lean
  tests/lean/run/ppPiBinderNames.lean
  tests/lean/unifHintAndTC.lean.expected.out
Labels: changelog-pp

#10381 feat: syntax name heuristic for `unicode(...)`
  src/Lean/Elab/Syntax.lean
  tests/lean/run/ppUnicode.lean
Labels: changelog-no

#10382 feat: improvements to Verso docstrings
  src/Lean/DocString/Add.lean
  src/Lean/DocString/Extension.lean
  src/Lean/DocString/Markdown.lean
  src/Lean/DocString/Parser.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/DocString.lean
  src/Lean/Elab/DocString/Builtin.lean
  src/Lean/Elab/DocString/Builtin/Keywords.lean
  src/Lean/Elab/DocString/Builtin/Parsing.lean
  src/Lean/Elab/DocString/Builtin/Postponed.lean
  src/Lean/Elab/DocString/Builtin/Scopes.lean
  src/Lean/Environment.lean
  src/Lean/Parser/Command.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/versoDocs.lean
Labels: toolchain-available, changelog-language

#10389 fix: trailing whitespace setting for string literals was ignored
  src/Lean/Parser/Basic.lean
  tests/lean/docparse/arg_val_0005.expected.out
  tests/lean/docparse/codeBlock_0014.expected.out
  tests/lean/docparse/directive_0003.expected.out
  tests/lean/docparse/nameAndArgs_0010.expected.out
Labels: toolchain-available, changelog-other

#10302 feat: @[method_specs] to generate specification theorems from class instances
  src/Init/Tactics.lean
  src/Lean/Meta.lean
  src/Lean/Meta/MethodSpecs.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  tests/lean/run/methodSpecs.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#10346 feat: use @[method_specs] when deriving BEq and Ord
  src/Lean/Elab/Deriving/BEq.lean
  src/Lean/Elab/Deriving/Ord.lean
  src/Lean/Elab/Deriving/Util.lean
  tests/lean/run/methodSpecsDeriving.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#10394 feat: reduceBEq and reduceOrd simprocs
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/MethodSpecs.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/reduceBEqSimproc.lean
Labels: changelog-language

#10417 fix: use with_reducible in deriving_LawfulEq_tactic_step
  src/Init/LawfulBEqTactics.lean
  tests/lean/run/issue10416.lean
Labels: changelog-language

#10419 feat: helper theorem for normalizing non-commutative semirings
  src/Init/Grind/Ring/CommSemiringAdapter.lean
Labels: changelog-language

#10421 feat: non-commutative semiring normalizer in `grind`
  src/Lean/Meta/Tactic/Grind/Arith/CommRing.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/NonCommSemiringM.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/RingId.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/SemiringM.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Types.lean
  tests/lean/grind/algebra/ring_normalization.lean
  tests/lean/run/grind_noncomm_semiring.lean
Labels: changelog-language

#10423 fix: elaborate private inductive ctor in the private scope
  src/Lean/Elab/Inductive.lean
Labels: changelog-no

#10425 feat: `split` to generalize proof discriminants
  src/Lean/Meta/Tactic/Split.lean
  tests/lean/run/issue10195.lean
  tests/lean/run/issue10424.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#10415 refactor: change how equations for structural recursion are proved
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/5667.lean
  tests/lean/run/issue10195.lean
  tests/lean/run/issue10424.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#10397 doc: update URLs that are currently pointing to redirects
  README.md
  src/Lean/Expr.lean
  src/Lean/Parser/Term.lean
  src/Lean/Widget/Types.lean
Labels: toolchain-available

#10428 chore: missing `grind` modifiers and local `grind` theorems config
  src/Init/Control/Lawful/Basic.lean
  src/Init/Data/Array/Attach.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Data/Option/List.lean
  src/Init/Data/Sum/Basic.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/RawLemmas.lean
Labels: changelog-language

#10430 feat: minimal indexable subexpressions in `grind` parameters
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/grind_bitvec2.lean
  tests/lean/run/grind_constProp.lean
  tests/lean/run/grind_countP.lean
  tests/lean/run/grind_ematch1.lean
  tests/lean/run/grind_list_find.lean
  tests/lean/run/grind_option.lean
  tests/lean/run/grind_pat_sel.lean
  tests/lean/run/grind_sym_prio.lean
  tests/lean/run/grind_trace.lean
Labels: changelog-language

#10434 feat: add `reprove` command for re-proving theorems with a specified tactic
  src/Lean/Util.lean
  src/Lean/Util/Reprove.lean
  tests/lean/run/reprove.lean
Labels: changelog-language

#10304 feat: redefine `String`, part one
  src/Init/Core.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/ByteArray.lean
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/ByteArray/Bootstrap.lean
  src/Init/Data/ByteArray/Lemmas.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Data/String.lean
  src/Init/Data/String/Basic.lean
  src/Init/Data/String/Bootstrap.lean
  src/Init/Data/String/Decode.lean
  src/Init/Data/String/Extra.lean
  src/Init/Data/UInt/Bitwise.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Init/Prelude.lean
  src/Init/SizeOf.lean
  src/Lean/DocString/Parser.lean
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/run/2846.lean
  tests/lean/run/arthur1.lean
  tests/lean/run/arthur2.lean
  tests/lean/run/fun_cases.lean
  tests/lean/run/lex.lean
  tests/lean/run/printEqns.lean
  tests/lean/setLit.lean.expected.out
  tests/lean/sizeof.lean.expected.out
  tests/lean/string_imp2.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#10441 chore: missing `grind` modifier
  src/Init/Data/ByteArray/Lemmas.lean
Labels: changelog-no

#10456 feat: `mvcgen invariants?` to scaffold initial invariants
  src/Lean/Elab/Tactic/Do/VCGen.lean
  src/Lean/Elab/Tactic/Do/VCGen/SuggestInvariant.lean
  src/Std/Do/Triple/SpecLemmas.lean
  src/Std/Tactic/Do/Syntax.lean
  tests/lean/run/mvcgenInvariantsSuggestions.lean
Labels: changelog-language

#10270 feat: linear-size Ord instance
  src/Lean/DocString/Types.lean
  src/Lean/Elab/Deriving/Ord.lean
  tests/lean/run/Ord.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#10462 chore: `mbtc` in `grind cutsat`
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/MBTC.lean
  src/Lean/Meta/Tactic/Grind/MBTC.lean
Labels: changelog-no

#10469 fix: grind canonicalizer
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_canon_bug_2.lean
Labels: changelog-tactics

#10470 chore: lake: fix `tests/lean`
  src/lake/tests/lean/test.sh
Labels: toolchain-available, changelog-no

#10459 fix: lake: GH action template condition
  src/lake/Lake/CLI/Init.lean
Labels: toolchain-available, changelog-lake

#10473 fix: message context in `grind` code actions
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
Labels: changelog-tactics

#10474 doc: `!` modifier in `grind` parameters
  src/Init/Grind/Tactics.lean
Labels: changelog-tactics

#10367 feat: add vectored write and fix rc issue in tcp and udp cancel functions
  src/Std/Internal/Async/TCP.lean
  src/Std/Internal/Async/UDP.lean
  src/Std/Internal/UV/TCP.lean
  src/Std/Internal/UV/UDP.lean
  src/runtime/uv/tcp.cpp
  src/runtime/uv/tcp.h
  src/runtime/uv/udp.cpp
  src/runtime/uv/udp.h
Labels: toolchain-available, changelog-library

#10480 fix: equality resolution in `grind`
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  tests/lean/run/grind_eqres_bug.lean
Labels: changelog-tactics

#10481 refactor: generalize theorem activation in `grind`
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
Labels: changelog-tactics

#10482 fix: `[grind inj]` attribute
  src/Lean/Meta/Tactic/Grind/Injective.lean
  tests/lean/run/grind_inj.lean
Labels: changelog-tactics

#10484 chore: remove bootstrapping workaround
  src/Init/Notation.lean
  src/Lean/Elab/DocString.lean
  tests/lean/run/versoDocs.lean
Labels: changelog-no

#10491 chore: improve `grind` imports
  src/Lean/Meta/Tactic/Grind/AlphaShareCommon.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/LeCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Main.lean
  src/Lean/Meta/Tactic/Grind/Beta.lean
  src/Lean/Meta/Tactic/Grind/Cases.lean
  src/Lean/Meta/Tactic/Grind/CasesMatch.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Ctor.lean
  src/Lean/Meta/Tactic/Grind/Diseq.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/EqResolution.lean
  src/Lean/Meta/Tactic/Grind/ExprPtr.lean
  src/Lean/Meta/Tactic/Grind/Ext.lean
  src/Lean/Meta/Tactic/Grind/ExtAttr.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Injection.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/LawfulEqCmp.lean
  src/Lean/Meta/Tactic/Grind/MBTC.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/MarkNestedSubsingletons.lean
  src/Lean/Meta/Tactic/Grind/MatchCond.lean
  src/Lean/Meta/Tactic/Grind/MatchDiscrOnly.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Parser.lean
  src/Lean/Meta/Tactic/Grind/Proj.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  src/Lean/Meta/Tactic/Grind/PropagateInj.lean
  src/Lean/Meta/Tactic/Grind/PropagatorAttr.lean
  src/Lean/Meta/Tactic/Grind/ProveEq.lean
  src/Lean/Meta/Tactic/Grind/ReflCmp.lean
  src/Lean/Meta/Tactic/Grind/RevertAll.lean
  src/Lean/Meta/Tactic/Grind/SearchM.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/SynthInstance.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
  src/Lean/Meta/Tactic/Grind/VarRename.lean
  src/Lean/Meta/Tactic/Try/Collect.lean
Labels: changelog-no

#10486 doc: extra `grind` docstrings
  src/Init/Grind/Attr.lean
  src/Init/Grind/Tactics.lean
Labels: toolchain-available, changelog-tactics

#10487 feat: add vectored write and fix rc issue in tcp and udp cancel function
  src/Std/Internal/Async/TCP.lean
  src/Std/Internal/Async/UDP.lean
  src/Std/Internal/UV/TCP.lean
  src/Std/Internal/UV/UDP.lean
  src/runtime/uv/tcp.cpp
  src/runtime/uv/tcp.h
  src/runtime/uv/udp.cpp
  src/runtime/uv/udp.h
Labels: toolchain-available, release-ci, changelog-library

#10435 chore: remove unhelpful grind annotations
  src/Init/Data/Array/Attach.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/Option/Attach.lean
  src/Init/Data/Vector/Attach.lean
  src/Init/Data/Vector/Lemmas.lean
  tests/lean/run/grind_array_attach.lean
Labels: toolchain-available

#10442 feat: unknown identifier code actions for auto-implicits
  src/Lean/Elab/InfoTree/Main.lean
  src/Lean/Elab/InfoTree/Types.lean
  src/Lean/Elab/Term/TermElabM.lean
  src/Lean/Server/CodeActions/UnknownIdentifier.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/Requests.lean
Labels: builds-mathlib, toolchain-available, changelog-server

#10533 feat: docstring role for module names, plus improved suggestions
  src/Lean/Elab/DocString.lean
  src/Lean/Elab/DocString/Builtin.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/versoDocs.lean
Labels: toolchain-available, changelog-language

#10536 fix: simpHaveTelescope: calculate used fvars transitiviely
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/issue10353.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#10460 feat: `scripts/Modulize.lean`
  lean.code-workspace
  script/Modulize.lean
  script/lakefile.toml
  script/lean-toolchain
Labels: toolchain-available, changelog-other, force-mathlib-ci

#10505 chore: update bench/riskv-ast.lean
  tests/bench/riscv-ast.lean
Labels: toolchain-available

#10508 fix: .congr_simp for non-defs
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/MutualInductive.lean
  src/Lean/Environment.lean
  src/Lean/Meta/CongrTheorems.lean
  tests/lean/run/congrSimpDeclKinds.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#10523 fix: `String` regressions
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/String/Basic.lean
  src/Init/Data/String/Bootstrap.lean
  src/Init/Data/String/Decode.lean
Labels: toolchain-available, changelog-no

#8402 chore: turn some crashes into errors
  src/kernel/inductive.cpp
  src/kernel/type_checker.cpp
  tests/lean/run/bvarcrash.lean
  tests/lean/run/recconstructorcrash.lean
Labels: toolchain-available, changelog-no

#10538 fix: use `_Exit` in the language server
  src/Init/System/IO.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/Watchdog.lean
  src/runtime/io.cpp
Labels: toolchain-available, release-ci, changelog-server

#10554 doc: `meta` modifier
  src/Lean/Parser/Command.lean
Labels: toolchain-available

#10553 feat: infrastructure for `grind order`
  src/Init/Grind.lean
  src/Init/Grind/Order.lean
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Order.lean
  src/Lean/Meta/Tactic/Grind/Order/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Order/OrderM.lean
  src/Lean/Meta/Tactic/Grind/Order/StructId.lean
  src/Lean/Meta/Tactic/Grind/Order/Types.lean
  src/Lean/Meta/Tactic/Grind/OrderInsts.lean
  tests/lean/run/grind_linarith_1.lean
  tests/lean/run/infoFromFailure.lean
  tests/lean/run/info_trees.lean
Labels: changelog-tactics

#10452 feat: lake: rename dependencies
  src/lake/Lake/CLI/Translate/Lean.lean
  src/lake/Lake/CLI/Translate/Toml.lean
  src/lake/Lake/Config/Meta.lean
  src/lake/Lake/Config/MetaClasses.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Config/PackageConfig.lean
  src/lake/Lake/DSL/Config.lean
  src/lake/Lake/DSL/Extensions.lean
  src/lake/Lake/DSL/Package.lean
  src/lake/Lake/DSL/Syntax.lean
  src/lake/Lake/DSL/Targets.lean
  src/lake/Lake/Load/Config.lean
  src/lake/Lake/Load/Lean.lean
  src/lake/Lake/Load/Lean/Elab.lean
  src/lake/Lake/Load/Resolve.lean
  src/lake/Lake/Load/Toml.lean
  src/lake/tests/depRenaming/clean.sh
  src/lake/tests/depRenaming/dep/lakefile.lean
  src/lake/tests/depRenaming/lakefile.toml
  src/lake/tests/depRenaming/test.sh
  src/shell/CMakeLists.txt
Labels: builds-mathlib, toolchain-available, changelog-lake

#10560 feat: more metadata for Verso docstrings
  src/Lean/Elab/DocString.lean
  src/Lean/Elab/DocString/Builtin.lean
  tests/lean/run/versoDocs.lean
Labels: toolchain-available, changelog-language

#10188 feat: `lake cache` (& remote cache support)
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Context.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/ModuleArtifacts.lean
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/Build/Run.lean
  src/lake/Lake/Build/Trace.lean
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/Config/Artifact.lean
  src/lake/Lake/Config/Cache.lean
  src/lake/Lake/Config/Env.lean
  src/lake/Lake/Config/Monad.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/Lake/Load/Manifest.lean
  src/lake/Lake/Load/Package.lean
  src/lake/Lake/Load/Resolve.lean
  src/lake/Lake/Load/Workspace.lean
  src/lake/Lake/Reservoir.lean
  src/lake/Lake/Toml/Data/DateTime.lean
  src/lake/Lake/Toml/Data/Value.lean
  src/lake/Lake/Util.lean
  src/lake/Lake/Util/Date.lean
  src/lake/Lake/Util/Git.lean
  src/lake/Lake/Util/JsonObject.lean
  src/lake/Lake/Util/Log.lean
  src/lake/Lake/Util/Proc.lean
  src/lake/Lake/Util/Reservoir.lean
  src/lake/Lake/Util/String.lean
  src/lake/Lake/Util/Url.lean
  src/lake/Makefile
  src/lake/tests/cache/clean.sh
  src/lake/tests/cache/non-reservoir.toml
  src/lake/tests/cache/online-test.sh
  src/lake/tests/cache/reservoir.toml
  src/lake/tests/cache/reservoir2.toml
  src/lake/tests/cache/test.sh
  src/lake/tests/common.sh
  src/lake/tests/env/test.sh
  src/lake/tests/trace/test.sh
  src/shell/CMakeLists.txt
Labels: builds-mathlib, toolchain-available, changelog-lake

#10468 refactor: lake: introduce `LogConfig`
  src/lake/Lake/Build/Context.lean
  src/lake/Lake/Build/Run.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/Util/Log.lean
  src/lake/Lake/Util/MainM.lean
Labels: builds-mathlib, toolchain-available, changelog-lake

#10562 feat: internalization for `grind order`
  src/Init/Data/Int/OfNat.lean
  src/Init/Grind.lean
  src/Init/Grind/Order.lean
  src/Init/Grind/Ring/CommSolver.lean
  src/Lean/Expr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Poly.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  src/Lean/Meta/Tactic/Grind/Order/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Order/StructId.lean
  src/Lean/Meta/Tactic/Grind/Order/Types.lean
  src/Lean/Meta/Tactic/Grind/OrderInsts.lean
  tests/lean/run/grind_const_pattern.lean
  tests/lean/run/grind_cutsat_nat_le.lean
  tests/lean/run/grind_cutsat_toint_1.lean
  tests/lean/run/infoFromFailure.lean
  tests/lean/run/info_trees.lean
Labels: changelog-tactics

#10563 feat: upstream ReduceEval instances from quote4
  src/Lean/Meta/ReduceEval.lean
Labels: changelog-language

#10567 fix: make `getArg!'` compute the correct arg index to access
  src/Lean/Expr.lean
  tests/lean/run/getArgPrime.lean
Labels: changelog-language

#10556 fix: import-merging theorems under the module system
  src/Lean/Environment.lean
  tests/pkg/module/Module/Basic2.lean
  tests/pkg/module/Module/ConflictingImported.lean
  tests/pkg/module/test.sh
Labels: toolchain-available, changelog-no

#10550 fix: privacy checks and `import all`
  src/Lean/Environment.lean
  src/Lean/Modifiers.lean
  src/Lean/ResolveName.lean
  tests/lean/ctor_layout.lean
  tests/lean/ctor_layout.lean.expected.out
  tests/pkg/module/Module.lean
  tests/pkg/module/Module/Basic.lean
  tests/pkg/module/Module/ImportedAll.lean
  tests/pkg/module/Module/ImportedAllImportedAll.lean
Labels: changelog-no

#10518 chore: `CommandElabM.liftCoreM` should not reset `InfoState.lazyAssignment`
  src/Lean/Elab/Command.lean
Labels: toolchain-available

#10545 fix: allow `meta` decls in `#eval`
  src/Lean/Compiler/LCNF/Visibility.lean
  src/Lean/Compiler/Options.lean
  src/Lean/Elab/BuiltinEvalCommand.lean
  tests/pkg/module/Module/Basic.lean
Labels: toolchain-available, changelog-no

#10576 feat: lake: `restoreAllArtifacts`
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Config/PackageConfig.lean
  src/lake/tests/cache/lakefile.lean
  src/lake/tests/cache/lakefile.toml
  src/lake/tests/cache/online-test.sh
  src/lake/tests/cache/test.sh
Labels: toolchain-available, changelog-lake

#10587 chore: invalidate Lake CI cache
  .github/workflows/build-template.yml
  .github/workflows/update-stage0.yml
Labels: changelog-no

#10579 refactor: lake: `libPrefixOnWindows` on `libName`
  src/lake/Lake/Config/LeanLib.lean
Labels: toolchain-available, release-ci, changelog-lake

#10582 chore: `restoreAllArtifacts = true` for core
  src/lakefile.toml.in
Labels: toolchain-available, changelog-no

#10586 fix: lake: ill-formed build output handling
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Config/Artifact.lean
  src/lake/Lake/Config/Cache.lean
  src/lake/tests/cache/test.sh
Labels: toolchain-available, changelog-no

#10588 chore: lake: `restoreAllArtifacts` / CMake build types in TOML schema
  src/lake/schemas/lakefile-toml-schema.json
Labels: toolchain-available, changelog-no

#10590 feat: proof construction for `grind order`
  src/Lean/Meta/Tactic/Grind/Order.lean
  src/Lean/Meta/Tactic/Grind/Order/Assert.lean
  src/Lean/Meta/Tactic/Grind/Order/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Order/OrderM.lean
  src/Lean/Meta/Tactic/Grind/Order/Proof.lean
  src/Lean/Meta/Tactic/Grind/Order/StructId.lean
  src/Lean/Meta/Tactic/Grind/Order/Types.lean
  src/Lean/Meta/Tactic/Grind/Order/Util.lean
Labels: changelog-tactics

#10594 feat: proofs for theory propagation in `grind order`
  src/Init/Grind/Order.lean
  src/Lean/Meta/Tactic/Grind/Order/OrderM.lean
  src/Lean/Meta/Tactic/Grind/Order/Proof.lean
Labels: changelog-tactics

#10596 feat: add `addEdge` to `grind order`
  src/Init/Grind/Order.lean
  src/Lean/Meta/Tactic/Grind/Order/Assert.lean
  src/Lean/Meta/Tactic/Grind/Order/OrderM.lean
  src/Lean/Meta/Tactic/Grind/Order/Proof.lean
  src/Lean/Meta/Tactic/Grind/Order/Types.lean
  src/Lean/Meta/Tactic/Grind/Order/Util.lean
Labels: changelog-tactics

#10598 feat: `grind order` positive constraints
  src/Init/Grind/Order.lean
  src/Lean/Meta/Tactic/Grind/Order.lean
  src/Lean/Meta/Tactic/Grind/Order/Assert.lean
  src/Lean/Meta/Tactic/Grind/Order/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Order/Proof.lean
  src/Lean/Meta/Tactic/Grind/Order/Types.lean
  src/Lean/Meta/Tactic/Grind/Order/Util.lean
  tests/lean/run/grind_cutsat_trim_context.lean
  tests/lean/run/grind_linarith_trim_context.lean
  tests/lean/run/grind_order_1.lean
Labels: changelog-tactics

#10599 fix: `Nat` adapter in `grind order`
  src/Init/Grind/Order.lean
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset/Main.lean
  src/Lean/Meta/Tactic/Grind/Order/Assert.lean
  tests/lean/run/grind_order_2.lean
Labels: changelog-tactics

#10600 feat: `grind order` negative constraints
  src/Init/Grind/Order.lean
  src/Lean/Meta/Tactic/Grind/Order/Assert.lean
  src/Lean/Meta/Tactic/Grind/Order/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Order/OrderM.lean
  src/Lean/Meta/Tactic/Grind/Order/Proof.lean
  tests/lean/run/grind_offset_cnstr.lean
  tests/lean/run/grind_order_3.lean
Labels: changelog-tactics

#10601 fix: `isPartialOrder` in `grind order`
  src/Lean/Meta/Tactic/Grind/Order/Assert.lean
  tests/lean/run/grind_order_3.lean
Labels: changelog-tactics

#10602 fix: lake: module artifact restoration for ir/bc
  src/lake/Lake/Build/Module.lean
  src/lake/tests/cache/test.sh
Labels: toolchain-available, changelog-no

#10604 feat: process `grind` core equalities in `grind order`
  src/Init/Grind/Order.lean
  src/Lean/Meta/Tactic/Grind/Order.lean
  src/Lean/Meta/Tactic/Grind/Order/Assert.lean
  src/Lean/Meta/Tactic/Grind/Order/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Order/Proof.lean
  src/Lean/Meta/Tactic/Grind/Order/Types.lean
  src/Lean/Meta/Tactic/Grind/Order/Util.lean
  tests/lean/run/grind_const_pattern.lean
  tests/lean/run/grind_order_3.lean
Labels: changelog-tactics

#10575 feat: `shake` import minimizer aware of the module system and arbitrary elaboration dependencies
  script/Shake.lean
  script/lakefile.toml
  src/Init/Prelude.lean
  src/Lean.lean
  src/Lean/Compiler/LCNF/Visibility.lean
  src/Lean/Elab/BuiltinTerm.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/RecommendedSpelling.lean
  src/Lean/Elab/Syntax.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/Config.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/Elab/Util.lean
  src/Lean/EnvExtension.lean
  src/Lean/Environment.lean
  src/Lean/ExtraModUses.lean
  src/Lean/KeyedDeclsAttribute.lean
  src/Lean/Linter/Deprecated.lean
  src/Lean/Meta/Coe.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  src/Lean/Parser/Extension.lean
  src/Lean/Setup.lean
  tests/lean/run/methodsRetInhabited.lean
Labels: toolchain-available, changelog-other

#10584 feat: suggest qualified names while editing Verso docstrings
  src/Lean/Elab/DocString/Builtin.lean
  tests/lean/run/versoDocs.lean
Labels: toolchain-available, changelog-server

#10607 feat: infrastructure for `grind` interactive mode
  src/Init/Grind.lean
  src/Init/Grind/Interactive.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Elab/Tactic/Grind/Basic.lean
  src/Lean/Elab/Tactic/Grind/Main.lean
  src/Lean/Elab/Term/TermElabM.lean
  stage0/src/stdlib_flags.h
Labels: changelog-tactics

#10610 feat: consistent type ABI regardless of transparency
  src/Lean/Compiler/LCNF/Types.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/compiler_type_transparency.lean
Labels: toolchain-available, changelog-compiler

#10619 fix: unknown identifier code actions with nested `open`
  src/Lean/Server/Completion/CompletionUtils.lean
Labels: toolchain-available, changelog-server

#10612 fix: instantiate mvars in types of mvars in abstractMVars
  src/Lean/Meta/AbstractMVars.lean
  tests/lean/run/abstractMVars.lean
Labels: builds-mathlib, toolchain-available, changelog-language
