Repository leanprover/lean4, pull requests merged in 2025-05, with the labels that each got.

#8190 doc: lake: add `needs` and native library options to README
  src/lake/README.md
Labels: builds-mathlib, toolchain-available, changelog-lake

#8187 chore: lake: backport dynlib fixes
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Fetch.lean
  src/lake/Lake/Build/Imports.lean
  src/lake/Lake/Build/Library.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/Target/Basic.lean
  src/lake/Lake/Config/Dynlib.lean
  src/lake/Lake/Load/Resolve.lean
  src/lake/Lake/Util/Cycle.lean
  src/lake/README.md
  src/lake/tests/badImport/test.sh
  src/lake/tests/buildArgs/test.sh
  src/lake/tests/common.sh
  src/lake/tests/precompileArgs/clean.sh
  src/lake/tests/precompileArgs/test.sh
  src/lake/tests/precompileLink/Downstream.lean
  src/lake/tests/precompileLink/Downstream/Import.lean
  src/lake/tests/precompileLink/Foo.lean
  src/lake/tests/precompileLink/Foo/Bar.lean
  src/lake/tests/precompileLink/Foo/Baz.lean
  src/lake/tests/precompileLink/FooDep.lean
  src/lake/tests/precompileLink/FooDepDep.lean
  src/lake/tests/precompileLink/Indirect.lean
  src/lake/tests/precompileLink/clean.sh
  src/lake/tests/precompileLink/lakefile.lean
  src/lake/tests/precompileLink/orderTest.lean
  src/lake/tests/precompileLink/test.sh
  src/shell/CMakeLists.txt
Labels: breaks-mathlib, toolchain-available

#8191 doc: Fix typo in Tactics.lean: fun_cass -> fun_cases
  src/Init/Tactics.lean
Labels: toolchain-available

#8193 fix: go to import
  src/Lean/Server/FileWorker/RequestHandling.lean
Labels: toolchain-available, changelog-no, backport releases/v4.20.0

#8196 feat: improve E-matching pattern inference in `grind`
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/grind/hashmap_list.lean
  tests/lean/grind/mvar.lean
  tests/lean/run/grind_ematch1.lean
  tests/lean/run/grind_eq_pattern.lean
  tests/lean/run/grind_hashmap_list.lean
  tests/lean/run/grind_mvar.lean
  tests/lean/run/grind_pattern1.lean
  tests/lean/run/grind_pattern2.lean
Labels: toolchain-available, changelog-language

#8197 chore: remove dead code
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
Labels: toolchain-available, changelog-no

#8198 fix: theory propagation in `grind`
  src/Lean/Meta/Tactic/Grind/Core.lean
  tests/lean/run/grind_qpartition.lean
Labels: toolchain-available, changelog-language

#8202 feat: Bitvector 0 equals bitvector 1 iff width is zero
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#8182 feat: add ofList_eq_insertMany_empty lemmas for map types
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/ExtDHashMap/Lemmas.lean
  src/Std/Data/ExtHashMap/Lemmas.lean
  src/Std/Data/ExtHashSet/Lemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/TreeMap/Lemmas.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeSet/Lemmas.lean
  src/Std/Data/TreeSet/Raw/Lemmas.lean
Labels: toolchain-available, changelog-library

#8188 feat: add simpler `getElem_map` statements given `LawfulBEq` for all HashMap variants
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/ExtDHashMap/Lemmas.lean
  src/Std/Data/ExtHashMap/Lemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
Labels: toolchain-available, changelog-library

#8207 chore: remove grind ext lemmas for List/Array/Vector
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Ext.lean
  tests/lean/run/grind_list2.lean
Labels: toolchain-available

#8201 fix: cadical distribution on Linux
  CMakeLists.txt
  script/prepare-llvm-linux.sh
  src/cadical.mk
Labels: toolchain-available, changelog-no, backport releases/v4.20.0

#8209 fix: nondeterminism in `grind`
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Model.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/MBTC.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_getLast_dropLast
Labels: toolchain-available, changelog-language

#8211 feat: LCNF -> IR translation
  src/Lean/Compiler/IR.lean
  src/Lean/Compiler/IR/ToIR.lean
  src/Lean/Compiler/LCNF/Main.lean
  src/Lean/CoreM.lean
Labels: toolchain-available, changelog-compiler

#8186 chore: consistently add @[simp] to getKey_eq map lemmas
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/DTreeMap/Internal/Lemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/ExtDHashMap/Lemmas.lean
  src/Std/Data/ExtHashMap/Lemmas.lean
  src/Std/Data/ExtHashSet/Lemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/RawLemmas.lean
Labels: toolchain-available, changelog-library

#8217 chore: cleanup of `@[grind]` lemmas for `Option`
  src/Init/Data/Option/Lemmas.lean
  src/Std/Data/Internal/List/Associative.lean
  tests/lean/run/grind_option.lean
Labels: toolchain-available

#8218 chore: more @[grind] annotations for List/Array/Vector
  src/Init/Data/Array/Attach.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Bootstrap.lean
  src/Init/Data/Array/Count.lean
  src/Init/Data/Array/DecidableEq.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Lex/Lemmas.lean
  src/Init/Data/Array/MapIdx.lean
  src/Init/Data/Array/Monadic.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Option/Attach.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/DecidableEq.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Data/Vector/Lex.lean
  tests/lean/run/grind_array.lean
  tests/lean/run/grind_vector.lean
Labels: toolchain-available, changelog-library

#8024 feat: `lean --setup`
  src/Lean/Data/Json/FromToJson.lean
  src/Lean/Data/NameMap.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/Import.lean
  src/Lean/Environment.lean
  src/Lean/Language/Lean.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Setup.lean
  src/Lean/Util/LeanOptions.lean
  src/lake/Lake/Util/Name.lean
  src/util/shell.cpp
  tests/pkg/setup/Dep.lean
  tests/pkg/setup/Test.lean
  tests/pkg/setup/clean.sh
  tests/pkg/setup/setup.json
  tests/pkg/setup/test.sh
Labels: builds-mathlib, toolchain-available, will-merge-soon, changelog-language

#8224 feat: diagnostics for comm ring procedure in `grind`
  src/Lean/Message.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/PP.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Util.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  tests/lean/run/grind_qpartition.lean
Labels: toolchain-available, changelog-language

#8226 fix: `simplifyBasis`
  src/Lean/Meta/Tactic/Grind/Arith/CommRing.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/EqCnstr.lean
Labels: toolchain-available, changelog-language

#8192 feat: upgrades to `release_checklist.py` script
  doc/dev/release_checklist.md
  script/merge_remote.py
  script/release_checklist.py
  script/release_repos.yml
  script/release_steps.py
Labels: builds-mathlib, toolchain-available, changelog-other

#8231 fix: `apply?` produces a non-synthetic sorry
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/LibrarySearch.lean
  tests/lean/librarySearch.lean
  tests/lean/librarySearch.lean.expected.out
Labels: toolchain-available, changelog-language, backport releases/v4.20.0

#8235 chore: update release_checklist.py to check new release notes page
  script/release_checklist.py
Labels: toolchain-available

#8236 fix: `extern_lib` and `precompileModules` on macOS
  src/CMakeLists.txt
Labels: toolchain-available, changelog-compiler, backport releases/v4.20.0

#8238 fix: make sure all kernel constants are persisted eventually
  src/Lean/Environment.lean
Labels: toolchain-available, changelog-no, backport releases/v4.20.0

#8242 fix: broken goals accomplished
  src/Lean/Elab/MutualDef.lean
Labels: toolchain-available, changelog-server, backport releases/v4.20.0

#8171 feat: FunInd: omit cases proved by contradiction
  src/Lean/Meta/Tactic/FunInd.lean
  src/Std/Data/DTreeMap/Internal/Balancing.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/issue7550.lean
  tests/lean/run/issue8103.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, changelog-language

#8249 chore: make builtinRuntimeTypes an Array rather than a List
  src/Lean/Compiler/LCNF/Util.lean
Labels: toolchain-available

#8250 chore: post-stage0 fixes for #8171
  src/Lean/Meta/Tactic/FunInd.lean
  src/Std/Data/DTreeMap/Internal/Balancing.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available, will-merge-soon

#8241 fix: have `rename` ignore implementation detail hypotheses
  src/Lean/Elab/Tactic/ElabTerm.lean
  tests/lean/run/renameSelf.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#8254 fix: exponential compilation times due to inlined instances
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Subarray.lean
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/Float.lean
  src/Init/Data/Float32.lean
  src/Init/Data/Repr.lean
  src/Lean/Data/Json/FromToJson.lean
  tests/lean/run/tojson_fromjson_perf_issue.lean
Labels: toolchain-available, changelog-language

#8255 chore: fix typo in `Int/DivMod/Basic`
  src/Init/Data/Int/DivMod/Basic.lean
Labels: toolchain-available

#8225 feat: add labeled subcomponents and helper functions for error messages
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Message.lean
  src/Lean/Meta.lean
  src/Lean/Meta/Hint.lean
  src/Lean/Meta/Tactic/TryThis.lean
  src/Lean/Meta/TryThis.lean
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/Server/Completion/CompletionResolution.lean
  src/Lean/Widget/Types.lean
  src/Lean/Widget/UserWidget.lean
  tests/lean/run/2161.lean
  tests/lean/run/decideTactic.lean
  tests/lean/run/hintSuggestionMessage.lean
  tests/lean/run/inductionCheckAltNames.lean
  tests/lean/run/inlineExpr.lean
  tests/lean/run/mutual_termination_by_errors.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#8264 chore: improve application type mismatch error message
  src/Lean/Meta/Check.lean
  tests/lean/243.lean.expected.out
  tests/lean/283.lean.expected.out
  tests/lean/389.lean.expected.out
  tests/lean/423.lean.expected.out
  tests/lean/autoPPExplicit.lean.expected.out
  tests/lean/doErrorMsg.lean.expected.out
  tests/lean/doIssue.lean.expected.out
  tests/lean/elseifDoErrorPos.lean.expected.out
  tests/lean/evalSorry.lean.expected.out
  tests/lean/macroSwizzle.lean.expected.out
  tests/lean/modBug.lean.expected.out
  tests/lean/motiveNotTypeCorect.lean.expected.out
  tests/lean/nameArgErrorIssue.lean.expected.out
  tests/lean/namedHoles.lean.expected.out
  tests/lean/phashmap_inst_coherence.lean.expected.out
  tests/lean/run/439.lean
  tests/lean/run/4405.lean
  tests/lean/run/4670.lean
  tests/lean/run/4888.lean
  tests/lean/run/DVec.lean
  tests/lean/run/check.lean
  tests/lean/run/duplicatedArgumentApplicationTypeMismatch.lean
  tests/lean/run/scopedunifhint.lean
  tests/lean/run/variable.lean
  tests/lean/simpArgTypeMismatch.lean.expected.out
  tests/lean/sorryAtError.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language

#8261 feat: improve 'apply' unification error message
  src/Lean/Elab/Tactic/ElabTerm.lean
  src/Lean/Meta/Tactic/Apply.lean
  src/Lean/Meta/Tactic/Rfl.lean
  tests/lean/issue3232.lean.expected.out
  tests/lean/run/1870.lean
  tests/lean/run/apply_error.lean
  tests/lean/run/rflTacticErrors.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#8271 feat: consider universes and projections in `addPPExplicitToExposeDiff`
  src/Lean/Meta/Check.lean
  tests/lean/issue3232.lean
  tests/lean/issue3232.lean.expected.out
  tests/lean/run/exposeDiff.lean
Labels: toolchain-available, changelog-language

#8262 fix: improve type-as-hole error message
  src/Lean/Elab/MutualDef.lean
  tests/lean/331.lean.expected.out
  tests/lean/holeErrors.lean.expected.out
  tests/lean/holes.lean.expected.out
  tests/lean/multiConstantError.lean.expected.out
  tests/lean/run/2226.lean
  tests/lean/run/5475.lean
  tests/lean/run/type_as_hole.lean
  tests/lean/theoremType.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language

#8275 feat: add support for `implies_congr` in `grind`
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_congr.lean
Labels: toolchain-available, changelog-language

#8268 feat: optimize lean_nat_shiftr for scalars
  src/include/lean/lean.h
  src/runtime/object.cpp
  tests/compiler/nat_shiftr.lean
  tests/compiler/nat_shiftr.lean.expected.out
Labels: toolchain-available, changelog-compiler

#8280 fix: arrow congruence in `grind`
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  tests/lean/run/grind_congr.lean
Labels: toolchain-available, changelog-language

#8281 feat: improve procedure for proving auxiliary type casting equalities in `grind`
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/ProveEq.lean
Labels: toolchain-available, changelog-language

#8215 fix: rfl theorem tracking in the module system
  src/Lean/AddDecl.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#8277 fix: FunInd: rewrite matches more reliably in `.induct_unfolding`
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/funind_unfolding.lean
  tests/lean/run/issue8103.lean
  tests/lean/run/issue8195.lean
  tests/lean/run/issue8213.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#8287 chore: begin development cycle for v4.21.0
  src/CMakeLists.txt
Labels: toolchain-available

#8289 chore: add failing grind tests
  tests/lean/grind/grind_congrArg.lean
  tests/lean/grind/qsort_ematch_local_theorem.lean
Labels: toolchain-available

#8270 fix: bv_decide can handle universe polymorphic enums
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Enums.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/TypeAnalysis.lean
  tests/lean/run/bv_decide_enum_universe.lean
  tests/lean/run/bv_enums.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#8206 feat: BitVec.neg_ofNat_eq_ofInt_neg
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#8295 chore: adjust `@[grind]` attributes on List lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/Vector/Lemmas.lean
  tests/lean/run/grind_heapsort.lean
  tests/lean/run/grind_list2.lean
Labels: toolchain-available

#8299 feat: abstract metavars in `grind` preprocessor
  src/Lean/Meta/AbstractMVars.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/SynthInstance.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
  tests/lean/run/grind_abstract_mvars.lean
Labels: toolchain-available, changelog-language

#8301 feat: unfolding induction theorems to unfold `bif`
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/funind_unfolding.lean
Labels: toolchain-available, changelog-language

#8302 fix: cases to fail gracefully when motive has complex argument of dependent type
  src/Lean/Elab/Tactic/Induction.lean
  tests/lean/run/inductionComplexMotive.lean
Labels: toolchain-available, changelog-language

#8305 chore: add @zwarich to the compiler CODEOWNERS
  CODEOWNERS
Labels: toolchain-available

#8308 fix: make new compiler's specialization closure behavior match old compiler
  src/Lean/Compiler/LCNF/Closure.lean
Labels: toolchain-available, changelog-compiler

#8246 feat: add `@[grind]` annotations for HashMap
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/ExtDHashMap/Lemmas.lean
  src/Std/Data/ExtHashMap/Lemmas.lean
  src/Std/Data/ExtHashSet/Lemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/RawLemmas.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeSet/Lemmas.lean
  src/Std/Data/TreeSet/Raw/Lemmas.lean
  tests/lean/grind/experiments/map.lean
  tests/lean/run/grind_map.lean
  tests/lean/run/grind_map_uniform.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#8311 chore: remove accidental grind trace options
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/ExtDHashMap/Lemmas.lean
  src/Std/Data/ExtHashMap/Lemmas.lean
  src/Std/Data/ExtHashSet/Lemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/RawLemmas.lean
  tests/lean/run/grind_map_uniform.lean
Labels: toolchain-available

#8310 chore: add grind test for fastEraseDups
  src/Init/Data/BEq.lean
  src/Init/Data/List/Lemmas.lean
  tests/lean/run/grind_fastEraseDups.lean
Labels: toolchain-available

#8314 chore: cleaning up imports
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/Hashable.lean
  src/Init/Data/Ord.lean
  src/Init/System/IO.lean
  src/Std/Classes/Ord.lean
  src/lake/Lake/Util/Compare.lean
Labels: toolchain-available

#8091 feat: improve workspace symbol performance
  src/Lean/Server/Completion/CompletionCollectors.lean
  src/Lean/Server/Completion/CompletionUtils.lean
  src/Lean/Server/References.lean
  src/Lean/Server/Watchdog.lean
Labels: builds-mathlib, toolchain-available, changelog-server

#8180 fix: broken unknown identifier code actions
  src/Lean/Server/CodeActions/UnknownIdentifier.lean
  src/Lean/Server/Requests.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#8298 feat: `Option` lemmas and cleanup
  src/Init/Core.lean
  src/Init/Data/Option.lean
  src/Init/Data/Option/Array.lean
  src/Init/Data/Option/Attach.lean
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Data/Option/List.lean
  src/Init/Data/Option/Monadic.lean
  tests/lean/run/grind_option.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#8104 feat: fun_induction to unfold function application in the goal
  src/Init/Data/Int/Linear.lean
  src/Init/Grind/CommRing/Poly.lean
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Meta/Tactic/FunIndCollect.lean
  src/Lean/Meta/Tactic/FunIndInfo.lean
  src/Lean/Meta/Tactic/Try/Collect.lean
  stage0/src/stdlib_flags.h
  tests/lean/grind/grind_ite_funinduction.lean
  tests/lean/run/funInduction.lean
  tests/lean/run/fun_cases.lean
  tests/lean/run/funinduction_ident.lean
  tests/lean/run/grind_heapsort.lean
  tests/lean/run/grind_ite.lean
  tests/lean/run/grind_try_trace.lean
  tests/lean/run/issue7550.lean
  tests/lean/run/issue8293.lean
Labels: builds-mathlib, toolchain-available, merge-ci, changelog-language

#8312 chore: remove >6 month old deprecations
  src/Init/ByCases.lean
  src/Init/Core.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Bootstrap.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/MinMax.lean
  src/Init/Data/List/Nat/Basic.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Data/List/Perm.lean
  src/Init/Data/List/Sort/Lemmas.lean
  src/Init/Data/List/Sublist.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/UInt/Basic.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Lean/Elab/Deriving/Basic.lean
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Info.lean
  src/lake/Lake/Build/Package.lean
  tests/lean/run/4230.lean
  tests/lean/run/bigop.lean
  tests/lean/run/simpHigherOrder.lean
Labels: toolchain-available

#8315 feat: split Std.Classes.Ord
  src/Std/Classes/Ord.lean
  src/Std/Classes/Ord/Basic.lean
  src/Std/Classes/Ord/BitVec.lean
  src/Std/Classes/Ord/SInt.lean
  src/Std/Classes/Ord/String.lean
  src/Std/Classes/Ord/UInt.lean
  src/Std/Classes/Ord/Vector.lean
  src/Std/Data/DTreeMap/Internal/Cell.lean
  src/Std/Data/DTreeMap/Internal/Def.lean
  src/Std/Data/DTreeMap/Internal/Operations.lean
  src/Std/Data/DTreeMap/Internal/Ordered.lean
  src/Std/Data/DTreeMap/Internal/Queries.lean
  src/Std/Data/DTreeMap/Internal/WF/Lemmas.lean
  src/Std/Data/Internal/List/Associative.lean
  src/Std/Time/Internal/Bounded.lean
  src/Std/Time/Internal/UnitVal.lean
Labels: toolchain-available, changelog-library

#8276 feat: add instance `Grind.CommRing (Fin n)`
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Int/Cooper.lean
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/LemmasAux.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/Int/Pow.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/UInt/Bitwise.lean
  src/Init/Data/Zero.lean
  src/Init/Grind/CommRing.lean
  src/Init/Grind/CommRing/Fin.lean
  src/Init/Omega/Int.lean
  tests/lean/run/3807.lean
  tests/lean/run/delabMatch.lean
  tests/lean/run/grind_ring_2.lean
  tests/lean/run/simp_int_arith.lean
  tests/lean/run/structWithAlgTCSynth.lean
Labels: breaks-mathlib, toolchain-available, changelog-language

#8169 fix: correct whitespace in omit/include
  src/Lean/Parser/Command.lean
Labels: toolchain-available, changelog-language

#8319 test: goals accomplished
  src/Lean/Server/Test/Runner.lean
  tests/lean/interactive/cancellation.lean.expected.out
  tests/lean/interactive/goalsAccomplished.lean
  tests/lean/interactive/goalsAccomplished.lean.expected.out
Labels: toolchain-available, changelog-no

#8320 test: more fundind unfolding test for #8293
  tests/lean/run/funind_unfolding.lean
Labels: toolchain-available

#8321 fix: GuessLex: also look for negations of Nat comparisons
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  tests/lean/guessLexDiff.lean.expected.out
  tests/lean/run/issue8257.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#8323 feat: bv_decide support for BitVec.reverse
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reflect.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reify.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Structures.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Basic.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Reverse.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Reverse.lean
  src/Std/Tactic/BVDecide/Reflect.lean
  tests/lean/run/bv_bitwise.lean
Labels: toolchain-available, changelog-language

#8326 chore: cleanup of grind if-then-else example
  tests/lean/run/grind_ite.lean
Labels: toolchain-available

#8327 feat: add `@[grind]` annotations for generic `GetElem` lemmas
  src/Init/GetElem.lean
  src/Std/Data/ExtHashMap/Lemmas.lean
Labels: toolchain-available, changelog-library

#8328 feat: add `@[grind]` annotations to `contains_iff_mem` lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/ExtDHashMap/Lemmas.lean
  src/Std/Data/ExtHashMap/Lemmas.lean
  src/Std/Data/ExtHashSet/Lemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/RawLemmas.lean
  src/Std/Data/TreeMap/Lemmas.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeSet/Lemmas.lean
  src/Std/Data/TreeSet/Raw/Lemmas.lean
Labels: toolchain-available, changelog-library

#8318 feat: follow-up to lemmas about `List.intersperse`
  src/Init/Data/List/Nat/Basic.lean
Labels: toolchain-available, changelog-library

#8329 chore: update grind test
  tests/lean/grind/palindrome.lean
Labels: toolchain-available

#8330 feat: structure extensionality in `grind`
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/ExtAttr.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/MarkNestedProofs.lean
  tests/lean/grind/grind_congrArg.lean
  tests/lean/run/grind_etaStruct.lean
Labels: toolchain-available, changelog-language

#8324 chore: fix spelling mistakes
  doc/dev/release_checklist.md
  src/Init/Core.lean
  src/Init/Data/BitVec/Folds.lean
  src/Init/Data/Option/Coe.lean
  src/Init/Prelude.lean
  src/Init/System/IO.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/StructInst.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/AC.lean
  src/Lean/Environment.lean
  src/Lean/Meta/ArgsPacker.lean
  src/Lean/Meta/Order.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Util.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/MBTC.lean
  src/Lean/Meta/TryThis.lean
  src/Lean/Parser/Basic.lean
  src/Lean/Setup.lean
  src/Std/Sync/Channel.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/Trace.lean
  src/lake/Lake/Config/Kinds.lean
  src/lake/Lake/Config/Pattern.lean
  src/lake/Lake/Util/IO.lean
  src/lake/README.md
  src/lake/tests/badImport/test.sh
  src/lake/tests/driver/test.sh
  src/lake/tests/setupFile/test.sh
  tests/lean/grind/experiments/list.lean
  tests/lean/run/inductionComplexMotive.lean
  tests/lean/run/lift_lets.lean
Labels: builds-mathlib, toolchain-available

#8322 fix: reduce ambiguity of "final" in application type mismatch message
  src/Lean/Meta/Check.lean
  tests/lean/243.lean.expected.out
  tests/lean/283.lean.expected.out
  tests/lean/389.lean.expected.out
  tests/lean/423.lean.expected.out
  tests/lean/autoPPExplicit.lean.expected.out
  tests/lean/doErrorMsg.lean.expected.out
  tests/lean/doIssue.lean.expected.out
  tests/lean/elseifDoErrorPos.lean.expected.out
  tests/lean/evalSorry.lean.expected.out
  tests/lean/macroSwizzle.lean.expected.out
  tests/lean/modBug.lean.expected.out
  tests/lean/motiveNotTypeCorect.lean.expected.out
  tests/lean/nameArgErrorIssue.lean.expected.out
  tests/lean/namedHoles.lean.expected.out
  tests/lean/phashmap_inst_coherence.lean.expected.out
  tests/lean/run/439.lean
  tests/lean/run/4405.lean
  tests/lean/run/4670.lean
  tests/lean/run/4888.lean
  tests/lean/run/DVec.lean
  tests/lean/run/check.lean
  tests/lean/run/duplicatedArgumentApplicationTypeMismatch.lean
  tests/lean/run/issue8213.lean
  tests/lean/run/scopedunifhint.lean
  tests/lean/run/variable.lean
  tests/lean/simpArgTypeMismatch.lean.expected.out
  tests/lean/sorryAtError.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-no

#8332 chore: use mutual inductives for data structures in the new compiler
  src/Lean/Compiler/IR/Basic.lean
  src/Lean/Compiler/IR/ToIR.lean
  src/Lean/Compiler/LCNF/Basic.lean
  src/Lean/Compiler/LCNF/Bind.lean
  src/Lean/Compiler/LCNF/CompilerM.lean
  src/Lean/Compiler/LCNF/InferType.lean
  src/Lean/Compiler/LCNF/Probing.lean
  src/Lean/Compiler/LCNF/Renaming.lean
  src/Lean/Compiler/LCNF/ToExpr.lean
  src/Lean/Compiler/LCNF/ToMono.lean
Labels: toolchain-available

#6973 perf: `dsimp` shouldn't visit proofs
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/dsimp_proofs.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7428 perf: store `dsimp` cache in a `simp` call
  src/Lean/Meta/Tactic/Simp/Main.lean
  src/Lean/Meta/Tactic/Simp/Types.lean
  src/Lean/Meta/Transform.lean
Labels: builds-mathlib, toolchain-available, P-medium

#8106 feat: implement "linter sets" that can be turned on as a group
  src/Lean/Elab/Tactic/Simpa.lean
  src/Lean/Linter.lean
  src/Lean/Linter/Basic.lean
  src/Lean/Linter/Builtin.lean
  src/Lean/Linter/Deprecated.lean
  src/Lean/Linter/MissingDocs.lean
  src/Lean/Linter/Sets.lean
  src/Lean/Linter/UnusedVariables.lean
  tests/pkg/linter_set/LinterSet.lean
  tests/pkg/linter_set/LinterSet/Def.lean
  tests/pkg/linter_set/lakefile.toml
  tests/pkg/linter_set/test.sh
Labels: builds-mathlib, toolchain-available, changelog-language

#8341 fix: `propagateCtor`
  src/Lean/Meta/Tactic/Grind/Ctor.lean
Labels: toolchain-available, changelog-language

#8342 chore: initial work on `grind` attributes for `TreeMap`
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Std/Classes/Ord/Basic.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/ExtDHashMap/Lemmas.lean
  src/Std/Data/ExtHashMap/Lemmas.lean
  src/Std/Data/ExtHashSet/Lemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/RawLemmas.lean
  src/Std/Data/TreeMap/Lemmas.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeSet/Lemmas.lean
  src/Std/Data/TreeSet/Raw/Lemmas.lean
  tests/lean/grind/experiments/bitvec.lean
  tests/lean/grind/experiments/list.lean
  tests/lean/run/grind_ite.lean
  tests/lean/run/grind_map.lean
Labels: toolchain-available

#8344 fix: `etaStruct` and preprocessing issues in `grind`
  src/Init/Grind/Ext.lean
  src/Lean/Meta/Tactic/Grind/Ext.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/MarkNestedProofs.lean
  tests/lean/run/grind_cat.lean
  tests/lean/run/grind_congrArg.lean
  tests/lean/run/grind_etaStruct.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#8345 chore: upstream Inv notation typeclass
  src/Init/Notation.lean
  src/Init/Prelude.lean
  tests/lean/diamond7.lean
  tests/lean/run/3807.lean
  tests/lean/run/KyleAlg.lean
  tests/lean/run/KyleAlgAbbrev.lean
  tests/lean/run/alg.lean
  tests/lean/run/grind_regression.lean
  tests/lean/run/mathlibetaissue.lean
  tests/lean/run/structWithAlgTCSynth.lean
Labels: toolchain-available

#8346 feat: missing lemmas about Int order/multiplication
  src/Init/Data/Int/Order.lean
Labels: toolchain-available, changelog-library

#8349 fix: fix typo in inhabited instance for ExtDHashMap
  src/Std/Data/ExtDHashMap/Basic.lean
Labels: toolchain-available, changelog-library

#8351 chore: fix `Inv.inv` notation
  src/Init/Notation.lean
  src/Init/Prelude.lean
Labels: toolchain-available

#8232 fix: deduplicate elaboration of constant argument to `rw`
  src/Lean/Elab/Tactic/Rewrite.lean
  tests/lean/interactive/rwElabConst.lean
  tests/lean/interactive/rwElabConst.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language

#8352 chore: tame some slow benchmarks
  tests/bench/channel.lean
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#8356 fix: FunInd: clean up packed arguments more throughly
  src/Lean/Meta/Tactic/FunInd.lean
Labels: toolchain-available, changelog-language

#8354 fix: FunInd: strip MData when creating the unfolding theorem
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/funind_unfolding.lean
  tests/lean/run/grind_congrArg.lean
Labels: builds-mathlib, toolchain-available, merge-ci, changelog-language

#8361 fix: cases tactic to handle non-atomic eliminator well
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Meta/Tactic/ElimInfo.lean
  tests/lean/run/issue8360.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#8365 fix: use `withReducibleAndIntances` to match ground patterns
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  tests/lean/run/grind_ematch_ground_implicit_inst.lean
Labels: toolchain-available, changelog-language

#8366 fix: give Ordering.then the `expose` attribute
  src/Init/Data/Ord.lean
Labels: toolchain-available, changelog-other

#8367 feat: add an LCNF pass to convert structure projections to cases expressions
  src/Lean/Compiler/LCNF/Passes.lean
  src/Lean/Compiler/LCNF/StructProjCases.lean
Labels: toolchain-available, changelog-compiler

#8369 fix: `instantiateTheorem` in `grind`
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  tests/lean/grind/palindrome.lean
  tests/lean/run/grind_ematch_type_error.lean
  tests/lean/run/grind_palindrome2.lean
Labels: toolchain-available, changelog-language

#8370 chore: cleanup previously failing grind test
  tests/lean/grind/qsort_ematch_local_theorem.lean
Labels: toolchain-available

#8371 fix: revert #8023 now that it is redundant
  src/Lean/Compiler/IR/ExpandResetReuse.lean
Labels: toolchain-available, changelog-compiler

#8374 chore: adopt Option.getD
  src/Lean/Compiler/LCNF/StructProjCases.lean
Labels: toolchain-available

#8357 chore: variants of `dite_eq_left_iff`
  src/Init/Data/Array/OfFn.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/PropLemmas.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Proof.lean
  src/Std/Data/Internal/List/Associative.lean
Labels: breaks-mathlib, toolchain-available, changelog-library

#8336 chore: build `leanc` with Lake under `USE_LAKE`
  src/CMakeLists.txt
  src/lakefile.toml.in
  src/stdlib.make.in
Labels: toolchain-available

#8359 feat: more parameters in `.fun_cases` theorem
  src/Lean/Elab/PreDefinition/FixedParams.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Std/Data/DTreeMap/Internal/Balancing.lean
  src/Std/Data/DTreeMap/Internal/Model.lean
  src/Std/Data/DTreeMap/Internal/WF/Lemmas.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/fun_cases.lean
  tests/lean/run/funind_unfolding.lean
  tests/lean/run/issue8195.lean
  tests/lean/run/issue8213.lean
  tests/lean/run/issue8293.lean
Labels: toolchain-available, changelog-language

#8377 chore: try refining some benchmark settings
  tests/bench/speedcenter.exec.velcom.yaml
  tests/bench/speedcenter.yaml
Labels: toolchain-available

#8382 chore: update DTreeMap proofs with more unfolding induction
  src/Std/Data/DTreeMap/Internal/Balancing.lean
  src/Std/Data/DTreeMap/Internal/Model.lean
Labels: toolchain-available, changelog-library

#8375 fix: mapError to store message data context
  src/Lean/Elab/PreDefinition/PartialFixpoint/Induction.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Main.lean
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Elab/PreDefinition/Structural/Main.lean
  src/Lean/Elab/PreDefinition/WF/Unfold.lean
  src/Lean/Elab/Tactic/Monotonicity.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/Tactic/FunInd.lean
  tests/lean/run/issue8213.lean
Labels: toolchain-available, changelog-language

#8363 feat: revamp aux decl name generation
  src/Lean/Compiler/InitAttr.lean
  src/Lean/CoreM.lean
  src/Lean/Data/Name.lean
  src/Lean/Elab/AuxDef.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Basic.lean
  src/Lean/Elab/Tactic/AsAuxLemma.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/Elab/Term.lean
  src/Lean/Meta/AbstractNestedProofs.lean
  src/Lean/Meta/Closure.lean
  src/Lean/Meta/Tactic/AuxLemma.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
  src/Lean/MonadEnv.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/arthur2.lean
  tests/lean/run/auxinvariable.lean
  tests/lean/run/bv_enums.lean
  tests/lean/run/decideTacticKernel.lean
  tests/lean/run/grind_offset_cnstr.lean
  tests/lean/run/noncomputable_decide.lean
  tests/lean/run/partial_fixpoint_aeneas2.lean
  tests/lean/run/sharecommon_mpz.lean
  tests/lean/run/structInst.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#8372 feat: pretty print `letFun` using `have` syntax
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/commandPrefix.lean.expected.out
  tests/lean/consumePPHint.lean.expected.out
  tests/lean/letFun.lean.expected.out
  tests/lean/ppBeta.lean.expected.out
  tests/lean/ppNotationCode.lean.expected.out
  tests/lean/precissues.lean.expected.out
  tests/lean/run/1026.lean
  tests/lean/run/821.lean
  tests/lean/run/decideNative.lean
  tests/lean/run/delabApp.lean
  tests/lean/run/delabMatch.lean
  tests/lean/run/extract_lets.lean
  tests/lean/run/heapSort.lean
  tests/lean/run/lift_lets.lean
  tests/lean/run/prefixTableStep.lean
  tests/lean/run/structInst3.lean
  tests/lean/run/zetaUnused.lean
Labels: breaks-mathlib, toolchain-available, changelog-pp

#8386 fix: tests that suffer from renaming
  tests/lean/run/simp_int_arith.lean
Labels: toolchain-available, changelog-no

#8383 fix: lake: `import Lake` w/ precompiled modules on MacOS
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Config/InstallPath.lean
  src/lake/tests/precompileLink/LakeTest.lean
  src/lake/tests/precompileLink/lakefile.lean
  src/lake/tests/precompileLink/test.sh
Labels: builds-mathlib, toolchain-available, changelog-lake

#8393 chore: rename LetValue.value to .lit
  src/Lean/Compiler/IR/ToIR.lean
  src/Lean/Compiler/LCNF/AlphaEqv.lean
  src/Lean/Compiler/LCNF/Basic.lean
  src/Lean/Compiler/LCNF/Check.lean
  src/Lean/Compiler/LCNF/Closure.lean
  src/Lean/Compiler/LCNF/CompilerM.lean
  src/Lean/Compiler/LCNF/DependsOn.lean
  src/Lean/Compiler/LCNF/ElimDead.lean
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
  src/Lean/Compiler/LCNF/FVarUtil.lean
  src/Lean/Compiler/LCNF/InferType.lean
  src/Lean/Compiler/LCNF/Level.lean
  src/Lean/Compiler/LCNF/PrettyPrinter.lean
  src/Lean/Compiler/LCNF/ReduceArity.lean
  src/Lean/Compiler/LCNF/Simp/ConstantFold.lean
  src/Lean/Compiler/LCNF/Simp/DiscrM.lean
  src/Lean/Compiler/LCNF/Simp/FunDeclInfo.lean
  src/Lean/Compiler/LCNF/Simp/InlineProj.lean
  src/Lean/Compiler/LCNF/Simp/JpCases.lean
  src/Lean/Compiler/LCNF/Simp/Main.lean
  src/Lean/Compiler/LCNF/Simp/SimpValue.lean
  src/Lean/Compiler/LCNF/Simp/Used.lean
  src/Lean/Compiler/LCNF/StructProjCases.lean
  src/Lean/Compiler/LCNF/Testing.lean
  src/Lean/Compiler/LCNF/ToLCNF.lean
  src/Lean/Compiler/LCNF/ToMono.lean
Labels: toolchain-available

#8394 chore: rename LitValue.natVal/strVal to .nat/str
  src/Lean/Compiler/IR/ToIR.lean
  src/Lean/Compiler/LCNF/Basic.lean
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
  src/Lean/Compiler/LCNF/InferType.lean
  src/Lean/Compiler/LCNF/Simp/ConstantFold.lean
  src/Lean/Compiler/LCNF/Simp/DiscrM.lean
  src/Lean/Compiler/LCNF/Simp/JpCases.lean
  src/Lean/Compiler/LCNF/Simp/Main.lean
  src/Lean/Compiler/LCNF/ToLCNF.lean
  src/Lean/Compiler/LCNF/ToMono.lean
Labels: toolchain-available

#8396 chore: add failing grind tests for noncommutative/non-negation rings
  tests/lean/grind/ring_normalization.lean
Labels: toolchain-available

#8392 fix: change `Array.` lemma to be about `Array`
  src/Init/Data/Array/Lex/Lemmas.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#8398 chore: use LitValue.toExpr instead of duplicating its definition
  src/Lean/Compiler/LCNF/Basic.lean
Labels: toolchain-available

#8400 chore: remove redundant ToFormat/ToString debug printing instances
  src/Lean/Compiler/IR/ElimDeadBranches.lean
Labels: toolchain-available

#8397 chore: remove duplicate instances
  src/Init/Classical.lean
  src/Init/Core.lean
  src/Init/Data/Float.lean
  src/Init/Data/Float32.lean
  src/Init/Data/Hashable.lean
  src/Init/Data/Int/LemmasAux.lean
  src/Init/Data/Ord.lean
  src/Init/Data/SInt/Basic.lean
  src/Init/Data/String/Lemmas.lean
  src/Init/Data/Sum/Basic.lean
  src/Init/Data/UInt/Basic.lean
  src/Init/Data/UInt/BasicAux.lean
  src/Init/Data/Vector/DecidableEq.lean
  src/Init/Grind/CommRing/Poly.lean
  src/Init/Prelude.lean
  src/Init/PropLemmas.lean
  src/Init/WF.lean
  src/Lean/Data/Json/Basic.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Types.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Widget/Basic.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Basic.lean
  tests/lean/run/4928.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#8379 feat: `Option` lemmas
  src/Init/Data/Option/Array.lean
  src/Init/Data/Option/Attach.lean
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Data/Option/List.lean
  src/Init/Data/Option/Monadic.lean
  src/Init/Internal/Order/Lemmas.lean
  src/Std/Data/Internal/List/Associative.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#8403 fix: add monotonicity lemmas for universal quantifiers
  src/Init/Internal/Order/Basic.lean
  tests/lean/run/coinductive_predicates.lean
Labels: toolchain-available, changelog-language

#8401 chore: upstream HSMul notation typeclass
  src/Init/Notation.lean
  src/Init/Prelude.lean
  tests/lean/run/2461.lean
  tests/lean/run/3807.lean
  tests/lean/run/binop_binrel_perf_issue.lean
  tests/lean/run/dsimpNatLitIssue.lean
  tests/lean/run/linearCategory_perf_issue.lean
  tests/lean/run/nestedtc.lean
  tests/lean/run/structWithAlgTCSynth.lean
  tests/lean/run/synthInstsIssue.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#8338 feat: improve inductive type parameter error messages
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/MutualInductive.lean
  tests/lean/inductive1.lean.expected.out
  tests/lean/run/inductiveParamMismatchError.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#8368 feat: improve error messages in invalid match alternatives
  src/Lean/Elab/Binders.lean
  src/Lean/Elab/Match.lean
  src/Lean/Elab/MatchAltView.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PatternVar.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Meta/Match/Basic.lean
  src/Lean/Meta/Match/Match.lean
  tests/lean/1057.lean.expected.out
  tests/lean/1079.lean
  tests/lean/1079.lean.expected.out
  tests/lean/690.lean.expected.out
  tests/lean/binop_at_pattern_issue.lean.expected.out
  tests/lean/funParen.lean.expected.out
  tests/lean/inductionErrors.lean.expected.out
  tests/lean/inductionGen.lean.expected.out
  tests/lean/inductionParse.lean.expected.out
  tests/lean/invalidPatternIssue.lean.expected.out
  tests/lean/match1.lean.expected.out
  tests/lean/match2.lean.expected.out
  tests/lean/matchErrorMsg.lean.expected.out
  tests/lean/matchMissingCasesAsStuckError.lean.expected.out
  tests/lean/matchOrIssue.lean.expected.out
  tests/lean/matchUnknownFVarBug.lean.expected.out
  tests/lean/patvar.lean.expected.out
  tests/lean/redundantAlt.lean.expected.out
  tests/lean/run/7170.lean
  tests/lean/run/constructor_as_variable.lean
  tests/lean/run/funInduction.lean
  tests/lean/run/funinduction_ident.lean
  tests/lean/run/inductionCheckAltNames.lean
  tests/lean/run/matchPatternVarErrors.lean
  tests/lean/tooManyVarsAtInduction.lean.expected.out
  tests/lean/typeIncorrectPat.lean.expected.out
  tests/lean/wildcardAlt.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language

#8408 chore: remove dependency of pretty-printing LCNF.LitValue on toExpr
  src/Lean/Compiler/LCNF/PrettyPrinter.lean
Labels: toolchain-available

#8409 feat: support native literals of size unsigned integer types
  src/Lean/Compiler/IR/EmitC.lean
  src/Lean/Compiler/IR/ToIR.lean
  src/Lean/Compiler/LCNF/Basic.lean
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
  src/Lean/Compiler/LCNF/InferType.lean
  src/Lean/Compiler/LCNF/PrettyPrinter.lean
  src/Lean/Compiler/LCNF/Simp/ConstantFold.lean
Labels: toolchain-available, changelog-compiler

#8410 fix: case-splitting in `grind`
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  tests/lean/run/grind_palindrome2.lean
Labels: toolchain-available, changelog-language

#8412 fix: `markNestedProofs` preprocessor in `grind`
  src/Lean/Meta/Tactic/Grind/MarkNestedProofs.lean
  tests/lean/run/grind_mark_nested_proofs_bug.lean
Labels: toolchain-available, changelog-language

#8413 feat: missing normalization rules in `grind`
  src/Init/Grind/Norm.lean
  tests/lean/run/grind_palindrome2.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#8399 feat: add `HashMap.get*_filter*` lemmas specialized for `LawfulBEq`
  src/Lean/Expr.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/ExtDHashMap/Lemmas.lean
  src/Std/Data/ExtHashMap/Lemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  tests/lean/grind/hashmap_getKey_eq.lean
  tests/lean/run/grind_map.lean
Labels: toolchain-available, changelog-library

#8414 chore: use HMul in Lean.Grind.Module
  src/Init/Grind/Module/Basic.lean
  src/Init/Grind/Module/Int.lean
Labels: toolchain-available

#8389 feat: add List/Array/Vector.ofFnM
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Monadic.lean
  src/Init/Data/Array/OfFn.lean
  src/Init/Data/Fin/Fold.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/List/FinRange.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Monadic.lean
  src/Init/Data/List/OfFn.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Nat/Fold.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Data/Vector/Monadic.lean
  src/Init/Data/Vector/OfFn.lean
Labels: toolchain-available, merge-ci, changelog-library

#8416 chore: deduplicate Grind.RatModule and Grind.NoNatZeroDivisors
  src/Init/Grind/CommRing/Basic.lean
  src/Init/Grind/CommRing/Fin.lean
  src/Init/Grind/Module/Basic.lean
  src/Init/Grind/Module/Int.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/RingId.lean
  tests/lean/grind/module_normalization.lean
  tests/lean/grind/module_relations.lean
  tests/lean/grind/ordered_modules.lean
  tests/lean/run/infoFromFailure.lean
Labels: toolchain-available

#8422 feat: LT for Timestamp and Duration
  src/Std/Time/DateTime/Timestamp.lean
  src/Std/Time/Duration.lean
Labels: toolchain-available, changelog-library

#8415 fix: simplify `isCasesAttrCandidate?` in `grind`
  src/Init/Grind/Cases.lean
  src/Lean/Meta/Tactic/Grind/Cases.lean
  tests/lean/run/grind_palindrome2.lean
Labels: toolchain-available, changelog-no

#8358 feat: minimal iterator library
  src/Std/Data.lean
  src/Std/Data/Iterators.lean
  src/Std/Data/Iterators/Basic.lean
  src/Std/Data/Iterators/Consumers.lean
  src/Std/Data/Iterators/Consumers/Collect.lean
  src/Std/Data/Iterators/Consumers/Loop.lean
  src/Std/Data/Iterators/Consumers/Monadic.lean
  src/Std/Data/Iterators/Consumers/Monadic/Collect.lean
  src/Std/Data/Iterators/Consumers/Monadic/Loop.lean
  src/Std/Data/Iterators/Consumers/Monadic/Partial.lean
  src/Std/Data/Iterators/Consumers/Partial.lean
  src/Std/Data/Iterators/Internal.lean
  src/Std/Data/Iterators/Internal/Termination.lean
  src/Std/Data/Iterators/Producers.lean
  src/Std/Data/Iterators/Producers/List.lean
  src/Std/Data/Iterators/Producers/Monadic.lean
  src/Std/Data/Iterators/Producers/Monadic/List.lean
  tests/lean/run/iterators.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#8423 chore: remove `Grind.Config.failures` options
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Solve.lean
Labels: toolchain-available, changelog-no

#8411 doc: Fix doc bug in Resolve.lean
  src/lake/Lake/Load/Resolve.lean
Labels: toolchain-available, changelog-lake

#8425 chore: fix name of new Fin.foldlM_eq_finRange_foldlM lemmas
  src/Init/Data/Array/OfFn.lean
  src/Init/Data/List/FinRange.lean
Labels: toolchain-available

#8426 feat: `[grind?]` attribute
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Model.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_attrs.lean
  tests/lean/run/grind_countP.lean
  tests/lean/run/grind_eq.lean
  tests/lean/run/grind_getLast_dropLast.lean
Labels: toolchain-available, changelog-language

#8427 chore: restore @[simp] to List.ofFn_succ
  src/Init/Data/List/OfFn.lean
Labels: toolchain-available

#8428 chore: cleanup grind palindrome test
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Ext.lean
  tests/lean/grind/grind_palindrome.lean
  tests/lean/run/grind_palindrome2.lean
Labels: toolchain-available

#8331 doc: clarify that `.now` returns a date(time) in the local time zone
  src/Std/Time/Zoned.lean
Labels: awaiting-review, toolchain-available, changelog-library

#7631 fix: normalize `imax 1 u` to `u`
  src/Lean/Level.lean
  src/kernel/level.cpp
  tests/lean/binrelTypeMismatch.lean.expected.out
  tests/lean/run/7096.lean
  tests/lean/run/issue4726.lean
Labels: toolchain-available, P-low, changelog-language

#8380 feat: lemmas about iterator collectors
  src/Std/Data/Iterators.lean
  src/Std/Data/Iterators/Basic.lean
  src/Std/Data/Iterators/Consumers.lean
  src/Std/Data/Iterators/Consumers/Access.lean
  src/Std/Data/Iterators/Consumers/Monadic/Collect.lean
  src/Std/Data/Iterators/Lemmas.lean
  src/Std/Data/Iterators/Lemmas/Basic.lean
  src/Std/Data/Iterators/Lemmas/Consumers.lean
  src/Std/Data/Iterators/Lemmas/Consumers/Collect.lean
  src/Std/Data/Iterators/Lemmas/Consumers/Monadic.lean
  src/Std/Data/Iterators/Lemmas/Consumers/Monadic/Collect.lean
  src/Std/Data/Iterators/Lemmas/Monadic.lean
  src/Std/Data/Iterators/Lemmas/Monadic/Basic.lean
  src/Std/Data/Iterators/Producers/List.lean
  src/Std/Data/Iterators/Producers/Monadic/List.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#8438 fix: `grind` diagnostics at `maxHeartbeats`
  src/Lean/Meta/Tactic/Grind/Combinators.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  src/Lean/Meta/Tactic/Grind/Lookahead.lean
  src/Lean/Meta/Tactic/Grind/Solve.lean
  tests/lean/run/grind_heartbeats.lean
Labels: toolchain-available, changelog-language

#8362 fix: unknown identifier ranges
  src/Lean/Elab/App.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/Extra.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Elab/Term.lean
  src/Lean/Exception.lean
  src/Lean/Language/Basic.lean
  src/Lean/Language/Lean.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/GetUnfoldableConst.lean
  src/Lean/ResolveName.lean
  src/Lean/Server/CodeActions/UnknownIdentifier.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/Requests.lean
  src/Lean/Server/ServerTask.lean
  src/Lean/Syntax.lean
  tests/lean/scientific.lean.expected.out
Labels: toolchain-available, changelog-server

#8434 feat: add `List.drop_cons`
  src/Init/Data/List/TakeDrop.lean
Labels: toolchain-available, changelog-library

#8443 feat: lemmas about ordered rings and fields for grind
  src/Init/Grind/CommRing/Field.lean
  src/Init/Grind/Ordered.lean
  src/Init/Grind/Ordered/Field.lean
  src/Init/Grind/Ordered/Module.lean
  src/Init/Grind/Ordered/Order.lean
  src/Init/Grind/Ordered/Ring.lean
Labels: toolchain-available, changelog-language

#8350 fix: namespace completion to only use the short name
  src/Lean/Server/Completion/CompletionCollectors.lean
  src/Lean/Server/Completion/CompletionUtils.lean
  tests/lean/interactive/compNamespace.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-server

#8445 feat: add simp lemma writing `Vector.tail` in terms of `Vector.extract`
  src/Init/Data/Vector/Basic.lean
Labels: toolchain-available, changelog-library

#8384 feat: lemmas about list iterators
  src/Std/Data/Iterators/Basic.lean
  src/Std/Data/Iterators/Consumers/Monadic/Collect.lean
  src/Std/Data/Iterators/Lemmas.lean
  src/Std/Data/Iterators/Lemmas/Producers.lean
  src/Std/Data/Iterators/Lemmas/Producers/List.lean
  src/Std/Data/Iterators/Lemmas/Producers/Monadic.lean
  src/Std/Data/Iterators/Lemmas/Producers/Monadic/List.lean
Labels: builds-mathlib, toolchain-available, changelog-library
