Repository leanprover/lean4, pull requests merged in 2025-03, with the labels that each got.

#7279 feat: helper theorems for `cooper_dvd_left`
  src/Init/Data/Int/Linear.lean
Labels: toolchain-available, changelog-language

#7284 feat: non-chronological backtracking for cutsat
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/SearchM.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  tests/lean/run/grind_cutsat_diseq_3.lean
  tests/lean/run/grind_cutsat_le_2.lean
Labels: toolchain-available, changelog-language

#7286 chore: add Fin.mk_eq_zero simp lemma
  src/Init/Data/Fin/Lemmas.lean
Labels: toolchain-available

#7287 refactor: change iff lowering rule in bv_decide
  src/Std/Tactic/BVDecide/Normalize/Bool.lean
  src/Std/Tactic/BVDecide/Normalize/Canonicalize.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-no

#7290 feat: `cooper_left` helper theorem for cutsat
  src/Init/Data/Int/Cooper.lean
  src/Init/Data/Int/Linear.lean
Labels: toolchain-available, changelog-language

#7292 feat: helper theorems for `cooper_dvd_right`
  src/Init/Data/Int/Linear.lean
Labels: toolchain-available, changelog-language

#7291 feat: lake: display newest job in monitor
  src/lake/Lake/Build/Run.lean
Labels: builds-mathlib, toolchain-available, changelog-lake

#7293 feat: `cooper_right` helper theorem for cutsat
  src/Init/Data/Int/Cooper.lean
  src/Init/Data/Int/Linear.lean
Labels: toolchain-available, changelog-language

#7294 fix: `Rat.floor` and `Rat.ceil`
  src/Std/Internal/Rat.lean
  tests/lean/run/Rat.lean
  tests/lean/run/grind_cutsat_le_2.lean
Labels: toolchain-available, changelog-language

#7277 fix: Float32.ofInt
  src/Init/Data/OfScientific.lean
  tests/lean/run/float32.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7295 chore: reimplement `mk_projections` in Lean
  src/Lean/Elab/Structure.lean
  src/Lean/Expr.lean
  src/Lean/Meta/Structure.lean
  src/library/constructions/CMakeLists.txt
  src/library/constructions/init_module.cpp
  src/library/constructions/projection.cpp
  src/library/constructions/projection.h
  src/library/elab_environment.cpp
  tests/lean/autoImplicitForbidden.lean.expected.out
  tests/lean/run/345.lean
  tests/lean/run/structure_recursive.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#6825 perf: use free_sized in mpz.cpp
  src/runtime/mpz.cpp
Labels: awaiting-review, toolchain-available, release-ci

#7241 fix: cancel computations within command elaboration as soon as reuse is ruled out
  src/Lean/CoreM.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/DefView.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Elab/Term.lean
  src/Lean/Language/Lean.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/Test/Cancel.lean
  tests/lean/interactive/cancellation.lean
  tests/lean/interactive/cancellation.lean.expected.out
Labels: toolchain-available, changelog-no

#7298 feat: bv_decide add rewrites around ite + operations
  src/Init/Data/BitVec/Lemmas.lean
  src/Std/Tactic/BVDecide/Normalize/Bool.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#7276 feat: use `realizeConst` for `bv_decide` helper constants
  src/Lean/Elab/MutualInductive.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Enums.lean
Labels: toolchain-available, changelog-no

#7289 feat: HashMap getKey lemmas
  src/Init/Data/BEq.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/RawLemmas.lean
  src/Std/Data/Internal/List/Associative.lean
Labels: toolchain-available, changelog-library

#7256 feat: `debug_assert!`
  src/Lean/Elab/BuiltinNotation.lean
  src/Lean/Elab/Do.lean
  src/Lean/Parser/Do.lean
  src/Lean/Parser/Term.lean
  src/lake/Lake/Config/LeanConfig.lean
  src/lake/Lake/Config/LeanLib.lean
  tests/lean/1021.lean.expected.out
  tests/pkg/debug/Main.lean
  tests/pkg/debug/lakefile.toml
  tests/pkg/debug/test.sh
Labels: toolchain-available, changelog-language

#7247 feat: `realizeConst` for match equations
  src/Lean/Attributes.lean
  src/Lean/Environment.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Match/MatchEqs.lean
  src/Lean/Meta/Match/MatchEqsExt.lean
  src/Lean/Modifiers.lean
Labels: toolchain-available, changelog-language

#7309 fix: bv_decide structures pass instantiate mvars
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Structures.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/TypeAnalysis.lean
  tests/bv_relation.lean
Labels: toolchain-available, changelog-language

#7311 chore: deprecate Environment.replay; use lean4checker
  src/Lean/Replay.lean
Labels: toolchain-available

#7312 feat: proof generation for `cooper_dvd_left` and variants in cutsat
  src/Init/Data/Int/Linear.lean
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Cooper.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/SearchM.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
Labels: toolchain-available, changelog-language

#7314 chore: re-enable synthesis checkpoint for structure parent elaboration
  src/Lean/Elab/Structure.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7317 chore: add missing period to `grind` warning message
  src/Lean/Elab/Tactic/Grind.lean
Labels: toolchain-available

#7320 feat: allow `cond` to be used in proofs (stage0 update prep)
  src/Lean/Elab/Deriving/DecEq.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Enums.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available, will-merge-soon, changelog-no

#7321 chore: harden use of panics in `Lean.Environment`
  src/Lean/Environment.lean
Labels: toolchain-available

#7319 feat: alignment of `Int.ediv/fdiv/tdiv` lemmas
  src/Init/Data/Int/DivMod/Bootstrap.lean
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Int/Order.lean
  tests/lean/run/simp_int_arith.lean
Labels: toolchain-available, changelog-library

#7325 chore: copy v4.17.0 release notes from releases/v4.17.0 branch
  releases/v4.17.0.md
Labels: toolchain-available

#7270 feat: tree map lemmas for foldlM, foldl, foldrM and foldr
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/DTreeMap/Basic.lean
  src/Std/Data/DTreeMap/Internal/Lemmas.lean
  src/Std/Data/DTreeMap/Internal/Queries.lean
  src/Std/Data/DTreeMap/Internal/WF/Lemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Basic.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/Internal/List/Associative.lean
  src/Std/Data/TreeMap/Lemmas.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeSet/Lemmas.lean
  src/Std/Data/TreeSet/Raw/Lemmas.lean
Labels: toolchain-available, merge-ci, changelog-library

#7141 feat: allow `cond` to be used in proofs
  src/Init/Data/Bool.lean
  src/Init/Prelude.lean
  src/Lean/Elab/Deriving/DecEq.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Enums.lean
Labels: builds-mathlib, toolchain-available, merge-ci, changelog-library

#7324 feat: WF/Fix.lean: only refine fix’s ih for atomic discriminant onlys
  src/Lean/Elab/PreDefinition/WF/Fix.lean
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  tests/lean/run/issue7322.lean
Labels: builds-mathlib, toolchain-available, merge-ci, changelog-language

#7336 fix: enable realizations for inductives as late as possible
  src/Lean/Elab/MutualInductive.lean
  src/Lean/Environment.lean
Labels: toolchain-available, changelog-no

#7333 fix: allow aux decls to be generated by decreasing_by tactics
  src/Lean/Elab/PreDefinition/WF/Fix.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  tests/lean/run/issue7332.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, changelog-language

#7166 feat: identify more fixed parameters
  src/Lean/Elab/PreDefinition/FixedParams.lean
  src/Lean/Elab/PreDefinition/Mutual.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Eqns.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Induction.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Main.lean
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Elab/PreDefinition/Structural/IndPred.lean
  src/Lean/Elab/PreDefinition/Structural/Main.lean
  src/Lean/Elab/PreDefinition/Structural/RecArgInfo.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Elab/PreDefinition/WF/PackMutual.lean
  src/Lean/Elab/PreDefinition/WF/Rel.lean
  src/Lean/Meta/ArgsPacker.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Meta/Tactic/FunIndInfo.lean
  tests/lean/1673.lean.expected.out
  tests/lean/guessLexFailures.lean.expected.out
  tests/lean/run/4928.lean
  tests/lean/run/fixedParams.lean
  tests/lean/run/fixedParamsAnnot.lean
  tests/lean/run/fixedParamsDep.lean
  tests/lean/run/fixedParamsReorder.lean
  tests/lean/run/fixedParamsStructDeps.lean
  tests/lean/run/funind_structural.lean
  tests/lean/run/funind_tests.lean
  tests/lean/run/funinduction_generalize.lean
  tests/lean/run/funinduction_ident.lean
  tests/lean/run/grind_constProp.lean
  tests/lean/run/issue2102.lean
  tests/lean/run/issue2108.lean
  tests/lean/run/issue2113.lean
  tests/lean/run/issue4671.lean
  tests/lean/run/issue6281.lean
  tests/lean/run/omega.lean
  tests/lean/run/partial_fixpoint_induct.lean
  tests/lean/run/structuralMutual.lean
  tests/lean/run/structuralRec2.lean
  tests/lean/wf2.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language

#7338 feat: add @[simp] to Int.neg_inj
  src/Init/Data/Int/Lemmas.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7339 feat: cooper resolution in cutsat
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/LeCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/SearchM.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  tests/lean/run/grind_cutsat_cooper.lean
  tests/lean/run/grind_cutsat_div_1.lean
Labels: toolchain-available, changelog-language

#7274 feat: `IntX` conversion lemmas
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Int/LemmasAux.lean
  src/Init/Data/SInt/Lemmas.lean
Labels: toolchain-available, will-merge-soon, changelog-library

#7337 feat: force-mathlib-ci label
  .github/workflows/pr-release.yml
Labels: toolchain-available, changelog-no

#7343 fix: inlay hints inserted at wrong position after edit
  src/Lean/Server/FileWorker/InlayHints.lean
Labels: toolchain-available, changelog-server

#7344 feat: combined auto-implicit inlay hint tooltip
  src/Lean/Elab/Term.lean
Labels: toolchain-available, changelog-server

#7348 feat: use `realizeConst` for all equation and unfold theorems
  src/Lean/Elab/PreDefinition/EqUnfold.lean
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Unfold.lean
  src/Lean/Meta/Eqns.lean
  src/lean.mk.in
  tests/lean/run/5667.lean
Labels: toolchain-available, changelog-language

#7340 feat: finite type conversions (`Nat`/`Int`/`Fin`/`BitVec` -> `UIntX` -> *)
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/SInt/Lemmas.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Std/Data/DHashMap/Internal/Index.lean
Labels: toolchain-available, changelog-library

#7306 fix: never transfer constants from checked environment into elab branches
  src/Init/System/Promise.lean
  src/Lean/AddDecl.lean
  src/Lean/Declaration.lean
  src/Lean/Elab/MutualInductive.lean
  src/Lean/Environment.lean
  src/Lean/MonadEnv.lean
Labels: breaks-mathlib, toolchain-available, changelog-no, force-mathlib-ci

#7351 feat: avoid cooper case analysis for univariate polynomials
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  tests/lean/run/grind_cutsat_cooper.lean
Labels: toolchain-available, changelog-language

#7354 test: cutsat cooper resolution
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Model.lean
  tests/lean/run/grind_cutsat_cooper.lean
  tests/lean/run/grind_cutsat_le_2.lean
Labels: toolchain-available, changelog-no

#7357 feat: mod and div in cutsat
  src/Init/Data/Int/Linear.lean
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DivMod.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  tests/lean/run/grind_cutsat_div_mod.lean
Labels: toolchain-available, changelog-language

#7288 fix: doc in `List.removeAll`
  src/Init/Data/List/Basic.lean
Labels: toolchain-available, changelog-doc

#7359 chore: protect Int.sub_eq_iff_eq_add
  src/Init/Data/Int/LemmasAux.lean
Labels: toolchain-available

#7331 feat: tree map lemmas for insertMany
  src/Std/Classes/Ord.lean
  src/Std/Data/DTreeMap/Internal/Lemmas.lean
  src/Std/Data/DTreeMap/Internal/WF/Lemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/Internal/List/Associative.lean
  src/Std/Data/TreeMap/Lemmas.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeSet/Lemmas.lean
  src/Std/Data/TreeSet/Raw/Lemmas.lean
Labels: toolchain-available, changelog-library

#7361 fix: remove incorrect `Environment.findAsyncCore?` shortcut
  src/Lean/Environment.lean
Labels: toolchain-available, changelog-no

#7358 feat: parity between `Int.ediv/tdiv/fdiv` theorems
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/Bitwise/Lemmas.lean
  src/Init/Data/Int/DivMod/Basic.lean
  src/Init/Data/Int/DivMod/Bootstrap.lean
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/Nat/Div/Lemmas.lean
Labels: breaks-mathlib, toolchain-available, changelog-library

#7363 feat: add async support to more extensions and constructions
  src/Lean/Environment.lean
  src/Lean/Meta/Match/Match.lean
  src/Lean/Meta/Match/MatcherInfo.lean
  src/Lean/Meta/Tactic/AuxLemma.lean
  src/Lean/MonadEnv.lean
  src/Lean/ReducibilityAttrs.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#7261 feat: use `realizeConst` for all equation, unfold, induction, and partial fixpoint theorems
  src/Lean.lean
  src/Lean/AddDecl.lean
  src/Lean/Elab/PreDefinition/Mutual.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Induction.lean
  src/Lean/Elab/PreDefinition/WF/Main.lean
  src/Lean/Environment.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/CongrTheorems.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Namespace.lean
  src/Lean/ResolveName.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7362 fix: allow simp dischargers to add aux decls to the environment
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Elab/Term.lean
  tests/lean/run/issue7318.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7360 feat: tree map lemmas for ofList
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/DTreeMap/Internal/Lemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeMap/Lemmas.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeSet/Lemmas.lean
  src/Std/Data/TreeSet/Raw/Lemmas.lean
Labels: toolchain-available, changelog-library

#7369 feat: let-decls for polynomials in cutsat proof terms
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  tests/lean/run/grind_cutsat_cooper.lean
Labels: toolchain-available, changelog-language

#7370 feat: simplify cooper case-split proof
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
Labels: toolchain-available, changelog-language

#7371 feat: combine two cutsat proof steps
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
Labels: toolchain-available, changelog-no

#7372 test: cutsat
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  tests/lean/run/grind_cutsat_auto.lean
Labels: changelog-no

#7373 feat: cutsat missing case: disequality+inequality+divisibility conflict
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_cutsat_diseq_cooper.lean
Labels: toolchain-available, changelog-language

#7329 feat: bv_decide support for simple pattern matching on enum inductives
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/ApplyControlFlow.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Basic.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Enums.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/IntToBitVec.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Structures.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/TypeAnalysis.lean
  tests/lean/run/bv_enums.lean
Labels: toolchain-available, changelog-language

#7366 feat: 'unsolved goals' & 'goals accomplished' diagnostics
  src/Lean/AddDecl.lean
  src/Lean/Data/Lsp/Capabilities.lean
  src/Lean/Data/Lsp/Diagnostics.lean
  src/Lean/Elab/GuardMsgs.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Language/Basic.lean
  src/Lean/Language/Util.lean
  src/Lean/Log.lean
  src/Lean/Message.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Widget/InteractiveDiagnostic.lean
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Load/Lean/Elab.lean
  tests/lean/interactive/4880.lean.expected.out
  tests/lean/interactive/haveInfo.lean.expected.out
  tests/lean/interactive/incrementalCombinator.lean.expected.out
  tests/lean/interactive/incrementalTactic.lean.expected.out
  tests/lean/interactive/issue4527.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-server

#7378 feat: integer prerequisites for finite type lemmas
  src/Init/Data/Int/LemmasAux.lean
  src/Init/Data/Int/Linear.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7376 feat: support `weak` options coming from `lake setup-file`
  src/Lean/Language/Lean.lean
Labels: toolchain-available, changelog-server

#7390 feat: bv_decide remove casts
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_decide_rewriter.lean
  tests/lean/run/bv_relation.lean
Labels: toolchain-available, changelog-language

#7392 fix: if-then-else split + normalization issue in `grind`
  src/Init/Grind/Util.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  tests/lean/run/grind_ite_split_issue.lean
Labels: toolchain-available, changelog-language

#7394 feat: infrastructure for supporting `Nat` in cutsat
  src/Init/Data/Int.lean
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/OfNat.lean
  src/Init/Grind/Norm.lean
  src/Lean/Expr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DivMod.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/LeCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Norm.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Var.lean
  src/Lean/Meta/Tactic/Grind/Arith/Main.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset/Model.lean
  src/Lean/Meta/Tactic/Grind/Beta.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Ext.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  src/Lean/Meta/Tactic/Grind/ProveEq.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_ematch2.lean
  tests/lean/run/grind_natCast.lean
  tests/lean/run/grind_offset_model.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#7341 feat: equivalence on hash maps
  src/Init/Data/List/Perm.lean
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/Raw.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Basic.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/Raw.lean
  src/Std/Data/HashSet/RawLemmas.lean
  src/Std/Data/Internal/List/Associative.lean
Labels: toolchain-available, changelog-library

#7396 fix: bug in cutsat model construction
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  tests/lean/run/grind_cutsat_upper_bug.lean
Labels: toolchain-available, changelog-language

#7397 fix: `Poly.mul p 0`
  src/Init/Data/Int/Linear.lean
  tests/lean/run/grind_Poly_mul_0_bug.lean
Labels: toolchain-available, changelog-language

#7398 fix: properly handle scoping of join point candidates in cce
  src/library/compiler/cse.cpp
  tests/lean/run/cceScoping.lean
Labels: toolchain-available, changelog-compiler

#7198 doc: Char docstring proofreading
  src/Init/Data/Char/Basic.lean
  src/Init/Data/Repr.lean
  src/Init/Data/String/Basic.lean
  src/Init/Prelude.lean
  src/Lean/Data/Lsp/Utf16.lean
  src/Lean/Meta/LitValues.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Char.lean
Labels: toolchain-available, changelog-doc

#7204 doc: docstrings for Id
  src/Init/Control/Id.lean
Labels: builds-mathlib, toolchain-available, changelog-doc

#7387 fix: bv_omega to use -implicitDefEqProofs
  src/Init/Tactics.lean
  src/kernel/type_checker.cpp
Labels: builds-mathlib, toolchain-available, changelog-language

#7401 feat: tight inequalities using divisibility constraints in cutsat
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  tests/lean/run/grind_cutsat_cooper.lean
Labels: toolchain-available, changelog-language

#7402 chore: remove workaround
  tests/lean/run/grind_cutsat_auto.lean
Labels: toolchain-available, changelog-no

#7399 chore: lake: revert builtin inits, elabs, & macros
  src/lake/Lake/DSL/Attributes.lean
  src/lake/Lake/DSL/AttributesCore.lean
  src/lake/Lake/DSL/Config.lean
  src/lake/Lake/DSL/Extensions.lean
  src/lake/Lake/DSL/Meta.lean
  src/lake/Lake/DSL/Package.lean
  src/lake/Lake/DSL/Require.lean
  src/lake/Lake/DSL/Script.lean
  src/lake/Lake/DSL/Targets.lean
  src/lake/Lake/Util/Version.lean
Labels: needs-update-stage0, builds-mathlib, toolchain-available, changelog-lake

#7403 fix: cutsat conflict resolution bug
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  tests/lean/run/grind_cutsat_decompose.lean
Labels: toolchain-available, changelog-no

#7404 chore: cutsat minor improvements
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
Labels: toolchain-available, changelog-language

#7407 feat: add more multiplication lemmas to bv_normalize
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Simproc.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#7409 fix: WellFounded preprocessing: use dsimp
  src/Init/Data/Array/Monadic.lean
  src/Init/Data/List/Monadic.lean
  src/Lean/Elab/PreDefinition/WF/Preprocess.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/issue7408.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7411 test: cutsat
  tests/lean/run/grind_cutsat_tests.lean
Labels: toolchain-available, changelog-no

#7368 feat: finite type conversions (`Nat`/`Int`/`Fin`/`BitVec` -> `IntX` -> *)
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/SInt/Lemmas.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Init/System/Platform.lean
  tests/lean/run/simpSInt.lean
  tests/lean/run/simprocSInt.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7342 chore: enforce `awaiting-mathlib` label
  .github/workflows/awaiting-mathlib.yml
Labels: toolchain-available

#7367 feat: tree map lemmas for alter
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/DTreeMap/Internal/Lemmas.lean
  src/Std/Data/DTreeMap/Internal/Queries.lean
  src/Std/Data/DTreeMap/Internal/WF/Lemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/Internal/List/Associative.lean
  src/Std/Data/TreeMap/Lemmas.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
Labels: toolchain-available, changelog-library

#7380 refactor: make DHashMap.Raw.foldRev(M) internal
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Data/DHashMap/Raw.lean
Labels: toolchain-available, changelog-library

#7384 feat: make more constructions async-compatible
  src/Lean/Elab/Tactic/AsAuxLemma.lean
  src/Lean/Environment.lean
  src/Lean/ScopedEnvExtension.lean
Labels: builds-mathlib, toolchain-available, changelog-no, force-mathlib-ci

#7416 fix: only log goals accomplished in language server
  src/Lean/CoreM.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Language/Lean.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#5998 feat: omega to abstract its own proofs
  src/Lean/Data/Name.lean
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/Elab/Term.lean
  tests/lean/run/auxinvariable.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7414 feat: remaining lemmas about iterated conversions of finite types
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/SInt/Lemmas.lean
  src/Init/Data/UInt/Lemmas.lean
Labels: toolchain-available, changelog-library

#7415 feat: `BitVec` conversion lemmas
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#7178 fix: language server dropping requests
  src/Lean/Server/FileWorker/SemanticHighlighting.lean
  src/Lean/Server/Watchdog.lean
Labels: toolchain-available, changelog-server

#7356 feat: lemmas about `pure` for `{List,Array,Vector}.{mapM,foldlM,foldrM,anyM,allM,findM?,findSomeM?}`
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Monadic.lean
  src/Init/Data/List/Control.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Monadic.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Data/Vector/Monadic.lean
Labels: toolchain-available, changelog-library

#7417 feat: bv_decide support enum inductive matches with default branches
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Basic.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Enums.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/TypeAnalysis.lean
  tests/lean/run/bv_enums.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7419 feat: tree map lemmas for modify
  src/Std/Data/DTreeMap/Internal/Lemmas.lean
  src/Std/Data/DTreeMap/Internal/Operations.lean
  src/Std/Data/DTreeMap/Internal/WF/Lemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeMap/Lemmas.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
Labels: toolchain-available, changelog-library

#7393 feat: lake: config field autocomplete in whitespace
  src/lake/Lake/DSL/DeclUtil.lean
Labels: builds-mathlib, toolchain-available, changelog-lake

#7421 test: expand f91 test
  tests/lean/run/partial_fixpoint_f91.lean
Labels: builds-mathlib, toolchain-available

#7304 fix: correctly collect let-rec fvars through delayed-assigned mvar
  src/Lean/Elab/MutualDef.lean
  tests/lean/run/6927.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7385 fix: find realizations from other env branches
  src/Lean/DeclarationRange.lean
  src/Lean/Elab/Tactic/Ext.lean
  src/Lean/Environment.lean
  src/Lean/Meta/WHNF.lean
  stage0/src/stdlib_flags.h
Labels: builds-mathlib, toolchain-available, changelog-no, force-mathlib-ci

#7223 feat: parallel watchdog requests
  src/Lean/Data/Lsp/Internal.lean
  src/Lean/Server/References.lean
  src/Lean/Server/Watchdog.lean
Labels: toolchain-available, changelog-server

#7426 feat: BitVec.extractLsb'_eq_self
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#7425 refactor: add definitions to allow turnstiles anywhere in locations
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Location.lean
  src/stdlib_flags.h
Labels: builds-mathlib, toolchain-available, changelog-no

#7429 feat: bv_decide add BV_EXTRACT_FULL preprocessing rule
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#7430 doc: reference mkEmpty in Array doc-string
  src/Init/Prelude.lean
Labels: toolchain-available

#7420 chore: generalize BitVec.toInt_[lt|le]'
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/SInt/Lemmas.lean
Labels: toolchain-available, changelog-library

#7406 fix: make the `Subsingleton` instance for `Squash` work for an arbitrary `Sort`
  src/Init/Core.lean
  tests/lean/run/7405.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7104 feat: add BitVec.[toNat|toFin|toInt]_[sshiftRight|sshiftRight']
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/Bitwise/Lemmas.lean
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Nat/Bitwise/Basic.lean
  src/Init/Data/SInt/Lemmas.lean
Labels: awaiting-review, breaks-mathlib, toolchain-available, P-medium, changelog-library

#7427 feat: BitVec.extractLsb'_append_extractLsb'_eq_extractLsb'
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#7438 feat: add more constant related rewrites to bv_decide
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#7431 feat: allow turnstiles anywhere in location sequences
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Location.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7334 chore: unconditionally re-enable `realizeConst`
  src/Lean/Environment.lean
  src/Lean/Language/Lean.lean
  src/Lean/Meta/Basic.lean
  src/lake/Lake/Load/Lean/Elab.lean
  tests/lean/run/issue7322.lean
Labels: builds-mathlib, toolchain-available, force-mathlib-ci

#7443 doc: correct typo in PSigma projection docstrings
  src/Init/Core.lean
Labels: toolchain-available

#7441 feat: bv_decide rewrites for concatenation and extraction
  src/Init/Data/BitVec/Lemmas.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reflect.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reify.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Simproc.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Basic.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  src/Std/Tactic/BVDecide/Reflect.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#7448 chore: fix duplicated namespaces
  src/Init/Data/Array/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Nat/Div/Basic.lean
Labels: toolchain-available

#7449 chore: better hypothesis for Vector.getElem_take
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available

#7446 chore: use `∅` notation in favour of `.empty` functions
  src/Lean/Compiler/LCNF/JoinPoints.lean
  src/Lean/Data/NameMap.lean
  src/Lean/Elab/Tactic/Omega/OmegaM.lean
  src/Lean/Linter/UnusedVariables.lean
  src/Lean/Meta/Canonicalizer.lean
  src/Lean/Meta/Tactic/AC/Main.lean
  src/Lean/Server/References.lean
  src/Lean/Util/Diff.lean
  src/Lean/Util/HasConstCache.lean
  src/Lean/Util/MonadCache.lean
  src/Lean/Util/SortExprs.lean
  src/Std/Sat/AIG/Basic.lean
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Util/OrdHashSet.lean
Labels: toolchain-available, changelog-library

#7435 feat: revision of Nat/Int lemmas
  src/Init/Data/Int/Basic.lean
  src/Init/Data/Int/Bitwise.lean
  src/Init/Data/Int/Bitwise/Basic.lean
  src/Init/Data/Int/Bitwise/Lemmas.lean
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Int/Gcd.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/LemmasAux.lean
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/Int/Pow.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Lcm.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Nat/MinMax.lean
  src/Init/Omega/Constraint.lean
  src/Init/Omega/Int.lean
  src/Init/Omega/IntList.lean
  tests/lean/run/funind_structural.lean
Labels: toolchain-available, changelog-library

#7240 feat: language reference links and examples in docstrings
  src/Lean/DocString.lean
  src/Lean/DocString/Add.lean
  src/Lean/DocString/Extension.lean
  src/Lean/DocString/Links.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Elab/DeclModifiers.lean
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/InheritDoc.lean
  src/Lean/Elab/LetRec.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Server/FileWorker/ExampleHover.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/include/lean/lean.h
  src/version.h.in
  stage0/src/stdlib_flags.h
  tests/bench/identifier_completion.lean
  tests/bench/identifier_completion_didOpen.log
  tests/bench/ilean_roundtrip.lean
  tests/lean/docstringLinkValidation.lean
  tests/lean/docstringLinkValidation.lean.expected.out
  tests/lean/interactive/docstringLinksExamples.lean
  tests/lean/interactive/docstringLinksExamples.lean.expected.out
  tests/lean/run/3497.lean
  tests/lean/run/docstringRewrites.lean
Labels: breaks-mathlib, toolchain-available, will-merge-soon, changelog-server

#7454 feat: BitVec.signExtend_eq_append_extractLsb'
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#7326 fix: indenting in release notes script
  script/release_notes.py
Labels: toolchain-available, changelog-other

#7445 chore: rename `Array.mkEmpty` to `emptyWithCapacity`
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/FloatArray/Basic.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Prelude.lean
  src/Init/System/IO.lean
  src/Lean/Elab/Tactic/BVDecide/LRAT/Trim.lean
  src/Std/Tactic/BVDecide/LRAT/Parser.lean
Labels: toolchain-available, changelog-library

#7432 feat: Nat.add_div_of_dvd_add_add_one
  src/Init/Data/Nat/Div/Lemmas.lean
  src/Init/Data/Nat/Lemmas.lean
Labels: toolchain-available, changelog-library

#7466 feat: cleanup of `Int` simp lemmas
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/OfNat.lean
  src/Init/Data/Int/Order.lean
Labels: toolchain-available, changelog-library

#7467 fix: `Repr` instance for `Int32`
  src/Init/Data/SInt/Basic.lean
Labels: toolchain-available, changelog-no

#7412 feat: new tree map lemmas for getKey
  src/Std/Data/DTreeMap/Internal/Lemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeMap/Lemmas.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeSet/Lemmas.lean
  src/Std/Data/TreeSet/Raw/Lemmas.lean
Labels: toolchain-available, changelog-library

#7465 feat: BitVec.lt_allOnes
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#7469 chore: reset stdlib_flags
  src/stdlib_flags.h
Labels: toolchain-available

#7468 fix: make `Term.mkAuxName` async-compatible
  src/Lean/Elab/Term.lean
Labels: awaiting-mathlib, breaks-mathlib, toolchain-available, changelog-no, force-mathlib-ci

#7457 feat: allow async elab tasks to contribute to info trees reported to linters and request handlers
  src/Init.lean
  src/Init/System/IO.lean
  src/Init/Task.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/InfoTree/Main.lean
  src/Lean/Elab/InfoTree/Types.lean
  src/Lean/Elab/InfoTrees.lean
  src/Lean/Language/Lean.lean
  src/Lean/Language/Lean/Types.lean
  src/Lean/Server/FileWorker/Utils.lean
  src/Lean/Server/Requests.lean
  src/Lean/Server/Snapshots.lean
  tests/lean/1018unknowMVarIssue.lean.expected.out
  tests/lean/binopInfoTree.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language, force-mathlib-ci

#7473 fix: heartbeats from `realizeConst` should be ignored
  src/Init/System/IO.lean
  src/Lean/CoreM.lean
  src/Lean/Environment.lean
  src/runtime/alloc.cpp
  src/runtime/alloc.h
  src/runtime/io.cpp
Labels: builds-mathlib, toolchain-available, changelog-no

#7365 doc: manual docstring review for smaller namespaces
  src/Init/Control/Basic.lean
  src/Init/Control/Except.lean
  src/Init/Control/ExceptCps.lean
  src/Init/Control/Lawful/Basic.lean
  src/Init/Core.lean
  src/Init/Data/Array/Subarray.lean
  src/Init/Data/Array/Subarray/Split.lean
  src/Init/Data/Fin/Basic.lean
  src/Init/Data/Fin/Fold.lean
  src/Init/Data/Fin/Iterate.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Fin/Log2.lean
  src/Init/Data/Format/Instances.lean
  src/Init/Data/Function.lean
  src/Init/Data/Hashable.lean
  src/Init/Data/Nat/Fold.lean
  src/Init/Data/Option/Attach.lean
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/BasicAux.lean
  src/Init/Data/Option/Instances.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Data/Ord.lean
  src/Init/Data/Prod.lean
  src/Init/Data/Repr.lean
  src/Init/Data/Sum/Basic.lean
  src/Init/Prelude.lean
  src/Init/WF.lean
Labels: toolchain-available, changelog-doc

#7452 doc: review List docstrings for manual
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/FloatArray/Basic.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/BasicAux.lean
  src/Init/Data/List/Control.lean
  src/Init/Data/List/FinRange.lean
  src/Init/Data/List/Impl.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/MapIdx.lean
  src/Init/Data/List/Monadic.lean
  src/Init/Data/List/OfFn.lean
  src/Init/Data/List/Sort/Basic.lean
  src/Init/Data/List/ToArrayImpl.lean
  src/Init/Data/String/Basic.lean
  src/Init/Data/ToString/Basic.lean
  src/Init/Prelude.lean
  src/Lean/Data/PersistentArray.lean
  src/Std/Data/HashMap/Basic.lean
  tests/lean/interactive/hover.lean.expected.out
Labels: toolchain-available, changelog-doc

#7477 fix: bv_decide don't analyze terms under binders by accident
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Enums.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/IntToBitVec.lean
  tests/lean/run/7475.lean
Labels: toolchain-available, changelog-language

#7471 fix: report replay kernel errors as standard diagnostics
  src/Lean/AddDecl.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Term.lean
  src/Lean/Environment.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Server/Test/Cancel.lean
  tests/lean/run/6065.lean
  tests/lean/run/998Export.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#7433 feat: mark `forIn_pure_yield` lemmas simp
  src/Init/Data/Array/Monadic.lean
  src/Init/Data/List/Monadic.lean
  src/Init/Data/Option/Monadic.lean
  src/Init/Data/Vector/Monadic.lean
  tests/lean/run/list_simp.lean
Labels: toolchain-available, changelog-library

#7084 feat: elaborate theorem bodies in parallel
  src/Lean/Elab/Command.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/Main.lean
  src/Lean/Elab/Tactic/AsAuxLemma.lean
  src/Lean/Meta/CongrTheorems.lean
  src/Lean/Meta/Eqns.lean
  src/Lean/Meta/Match/MatchEqs.lean
  src/Lean/MonadEnv.lean
  src/Lean/ReservedNameAction.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Structure.lean
  src/stdlib_flags.h
  tests/lean/run/ack.lean
  tests/lean/run/allGoals.lean
  tests/lean/run/decideTacticKernel.lean
  tests/lean/run/eqnsReducible.lean
  tests/lean/run/grind_attrs.lean
  tests/lean/run/info_trees.lean
  tests/lean/run/variable.lean
  tests/lean/shadow.lean.expected.out
  tests/lean/syntaxPrec.lean.expected.out
Labels: breaks-mathlib, toolchain-available, changelog-language, force-mathlib-ci

#7483 perf: Environment blocker removals from `async-proofs` branch
  src/Lean/Compiler/ImplementedByAttr.lean
  src/Lean/Compiler/Old.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/StructInst.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Elab/Term.lean
  src/Lean/Environment.lean
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/Check.lean
  src/Lean/Meta/Eqns.lean
  src/Lean/Meta/GetUnfoldableConst.lean
  src/Lean/Meta/InferType.lean
  src/Lean/Meta/Tactic/Simp/Attr.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  src/Lean/MonadEnv.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/Server/References.lean
Labels: toolchain-available

#7486 feat: add BitVec.add_neg_mul to bv_decide
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#7482 feat: BitVec.extract_Lsb'_append_[ite|of_lt|of_le]
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#7494 feat: `Nat` inequalities in cutsat
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/OfNat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/LeCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  tests/lean/run/grind_cutsat_nat_le.lean
Labels: toolchain-available, changelog-language

#7495 feat: `Nat` divisibility constraints in cutsat
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/OfNat.lean
  src/Lean/Meta/NatInstTesters.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  tests/lean/run/grind_cutsat_nat_dvd.lean
Labels: toolchain-available, changelog-language

#7485 feat: enable `Elab.async` by default
  src/Lean/CoreM.lean
  src/Lean/Elab/Binders.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Server/FileWorker.lean
  src/stdlib_flags.h
  src/util/shell.cpp
Labels: breaks-mathlib, toolchain-available, changelog-no, force-mathlib-ci

#7496 fix: include async elaboration time in elaboration profile
  src/Lean/Elab/MutualDef.lean
Labels: toolchain-available, changelog-no

#4466 chore: USE_LAKE: integrate into CMake
  src/CMakeLists.txt
  src/Lean/Data/Lsp.lean
  src/Std/Data/TreeSet.lean
  src/lakefile.toml.in
  src/lean.mk.in
  src/stdlib.make.in
Labels: toolchain-available, release-ci

#7497 perf: remove more async blockers
  src/Lean/Environment.lean
  src/Lean/Meta/Eqns.lean
  src/Lean/ResolveName.lean
  src/Lean/Util/Profiler.lean
Labels: toolchain-available

#7500 perf: remove most remaining async blockers in `Init.Data.List.Sublist`
  src/Lean/CoreM.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Tactic/Rewrite.lean
  src/Lean/Meta/Eval.lean
  src/Lean/Meta/IndPredBelow.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  src/Lean/MonadEnv.lean
  src/library/time_task.cpp
  src/library/time_task.h
  src/util/shell.cpp
Labels: toolchain-available

#7501 feat: `Nat` equalities and disequalities in cutsat
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/OfNat.lean
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DivMod.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Var.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_canon_insts.lean
  tests/lean/run/grind_cutsat_div_mod.lean
  tests/lean/run/grind_cutsat_nat_eq.lean
  tests/lean/run/grind_cutsat_nat_le.lean
  tests/lean/run/grind_eq.lean
  tests/lean/run/grind_lazy_ite.lean
  tests/lean/run/grind_offset.lean
  tests/lean/run/grind_regression.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#7502 feat: `Nat` div/mod in cutsat
  src/Lean/Expr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DivMod.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  tests/lean/run/grind_cutsat_nat_eq.lean
Labels: toolchain-available, changelog-language

#7503 feat: `Nat.sub` in cutsat
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean
  tests/lean/run/grind_cutsat_nat_eq.lean
Labels: toolchain-available, changelog-language

#7491 perf: speedup bv_decide's LRAT checker by improving input validaton
  src/Std/Sat/CNF/Literal.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Actions.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Assignment.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Clause.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Convert.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/Implementation.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/PosFin.lean
Labels: toolchain-available, changelog-language

#7509 perf: disable implicitDefEqProofs in bv_decide
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/EmbeddedConstraint.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Enums.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/IntToBitVec.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Rewrite.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Structures.lean
Labels: toolchain-available, changelog-language
