Repository leanprover/lean4, pull requests merged in 2025-01, with the labels that each got.

#6492 fix: theorem instantiation in `grind`
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Run.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_ematch1.lean
Labels: toolchain-available, changelog-language

#6497 fix: another bug in theorem instantiation in `grind`
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-language

#6498 feat: dependent forall propagator in `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Run.lean
  tests/lean/run/grind_prop_arrow.lean
Labels: toolchain-available, changelog-language

#6499 fix: proof canonicalizer in `grind`
  src/Lean/Meta/Tactic/Grind/Canon.lean
Labels: toolchain-available, changelog-language

#6500 fix: bug in `markNestedProofs` within `grind`
  src/Lean/Meta/Tactic/Grind/MarkNestedProofs.lean
  tests/lean/run/grind_nested_proof_issue.lean
Labels: toolchain-available, changelog-language

#6501 feat: add `PersistentHashSet.toList`
  src/Lean/Data/PersistentHashSet.lean
Labels: toolchain-available, changelog-no

#6502 fix: proof generation for `grind` tactic
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_heq_proof_issue.lean
Labels: toolchain-available, changelog-language

#6503 feat: `grind` simple strategy
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Preprocessor.lean
  src/Lean/Meta/Tactic/Grind/Run.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_canon_types.lean
  tests/lean/run/grind_ematch1.lean
  tests/lean/run/grind_nested_proofs.lean
  tests/lean/run/grind_pattern2.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6504 feat: a basic async event loop implementation
  src/Std/Internal.lean
  src/Std/Internal/UV.lean
  src/runtime/CMakeLists.txt
  src/runtime/init_module.cpp
  src/runtime/libuv.cpp
  src/runtime/libuv.h
  src/runtime/uv/event_loop.cpp
  src/runtime/uv/event_loop.h
Labels: changelog-library

#6438 fix: ignore `no_index` around `OfNat.ofNat` in `norm_cast`
  src/Lean/Elab/Tactic/NormCast.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6506 feat: partial_fixpoint: monotonicity tactic
  src/Init.lean
  src/Init/Internal/Order.lean
  src/Init/Internal/Order/Tactic.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/Monotonicity.lean
  tests/lean/run/partial_fixpoint_monotonicity.lean
Labels: toolchain-available, will-merge-soon, changelog-language

#6510 feat: custom congruence rule for equality in `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_diseq.lean
  tests/lean/run/grind_ematch2.lean
Labels: toolchain-available, changelog-language

#6512 feat: add user-defined fallback procedure for the `grind` tactic
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_canon_insts.lean
  tests/lean/run/grind_canon_types.lean
  tests/lean/run/grind_congr.lean
  tests/lean/run/grind_ematch2.lean
  tests/lean/run/grind_many_eqs.lean
  tests/lean/run/grind_nested_proofs.lean
  tests/lean/run/grind_norm_levels.lean
  tests/lean/run/grind_propagate_connectives.lean
Labels: toolchain-available, changelog-language

#6513 feat: `ite` and `dite` support in `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6514 perf: avoid unnecessary assert/intro pairs in `grind`
  src/Lean/Meta/Tactic/Grind/Intro.lean
Labels: toolchain-available, changelog-language

#6494 feat: bdiv and bmod lemmas
  src/Init/Data/Int/DivModLemmas.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6516 feat: improve `cases` tactic used in `grind`
  src/Lean/Meta/Tactic/Cases.lean
  src/Lean/Meta/Tactic/Grind/Cases.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  tests/lean/run/grind_cases_tac.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6517 fix: cond reflection bug in bv_decide
  src/Std/Tactic/BVDecide/Reflect.lean
Labels: toolchain-available, changelog-no

#6520 chore: cherry-pick release notes from releases/v4.15.0 and releases/v4.16.0
  RELEASES.md
  releases_drafts/list_lex.md
Labels: toolchain-available, changelog-no

#6519 feat: add script for generating release notes
  doc/dev/release_checklist.md
  script/release_notes.py
Labels: toolchain-available, changelog-other

#6521 feat: add support for `match`-expressions to `grind`
  src/Init/Grind/Norm.lean
  src/Init/Grind/Tactics.lean
  src/Init/Grind/Util.lean
  src/Lean/Meta/Tactic/Grind/DoNotSimp.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_match1.lean
Labels: toolchain-available, changelog-language

#6524 chore: upstream some List.Perm lemmas
  src/Init/Data/List/Perm.lean
  src/Init/Data/List/Sort/Lemmas.lean
Labels: toolchain-available, changelog-library

#6525 chore: add plausible to release checklist
  doc/dev/release_checklist.md
Labels: toolchain-available

#6522 chore: import cleanup in Init
  src/Lean/Data/Lsp/Utf16.lean
  src/Lean/Linter/MissingDocs.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/Server/Completion.lean
  src/Lean/Util/ShareCommon.lean
  src/Std/Sat/AIG/Basic.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/Implementation.lean
  src/Std/Time/DateTime/Timestamp.lean
  src/Std/Time/Internal/Bounded.lean
Labels: toolchain-available, changelog-no

#6523 chore: cleanup imports in Lean.Lsp
  src/Lean/Data/Lsp.lean
  src/Lean/Data/Lsp/Basic.lean
  src/Lean/Data/Lsp/CancelParams.lean
Labels: toolchain-available, changelog-no

#6527 doc: fix broken code blocks in RELEASES.md
  RELEASES.md
Labels: toolchain-available

#6528 fix: missing propagation in `grind`
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  tests/lean/run/grind_propagate_connectives.lean
Labels: toolchain-available, changelog-language

#6529 feat: add support for `let`-declarations to `grind`
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6530 fix: nondeterministic failure in `grind`
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/MarkNestedProofs.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
Labels: toolchain-available, changelog-language

#6531 fix: `let_fun` support in `grind`
  src/Lean/Meta/Tactic/Grind/Intro.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6532 chore: fix signature of perm_insertIdx
  src/Init/Data/List/Perm.lean
Labels: toolchain-available, changelog-no

#6533 feat: add term offset support to the `grind` E-matching modulo
  src/Init/Grind/Norm.lean
  src/Init/Grind/Util.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  tests/lean/run/grind_offset.lean
Labels: toolchain-available, changelog-language

#6534 fix: allow projections in E-matching patterns
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  tests/lean/run/grind_pattern_proj.lean
Labels: toolchain-available, changelog-language

#6536 fix: E-matching thresholds in the `grind` tactic
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_offset.lean
Labels: toolchain-available, changelog-language

#6538 feat: pattern normalization in the `grind` tactic
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
  tests/lean/run/grind_ematch2.lean
Labels: toolchain-available, changelog-language

#6539 feat: `[grind_eq]` attribute for the `grind` tactic
  src/Lean/Meta/Tactic/Grind/Ctor.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  tests/lean/run/grind_eq.lean
  tests/lean/run/grind_pattern1.lean
Labels: toolchain-available, changelog-language

#6535 fix: remove unused `-static-libgcc` MinGW linker arg
  script/prepare-llvm-mingw.sh
Labels: builds-mathlib, toolchain-available, release-ci, changelog-compiler, backport releases/v4.16.0

#6545 feat: attribute `[grind]`
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  tests/lean/run/grind_ematch1.lean
  tests/lean/run/grind_eq.lean
  tests/lean/run/grind_pattern1.lean
Labels: toolchain-available, changelog-language

#6542 feat: release checklist script
  doc/dev/release_checklist.md
  script/release_checklist.py
  script/release_repos.yml
Labels: builds-mathlib, toolchain-available, changelog-other

#6549 doc: modify aesop usage example of `omegaDefault`
  src/Lean/Elab/Tactic/Omega/Frontend.lean
Labels: toolchain-available, changelog-doc

#6554 fix: avoid new tokens `_=_` and `=_`
  src/Init/Grind/Tactics.lean
  tests/lean/run/grind_ematch1.lean
Labels: toolchain-available, changelog-no

#6543 feat: `grind` tests for basic category theory
  tests/lean/run/grind_cat.lean
  tests/lean/run/grind_ematch1.lean
  tests/lean/run/grind_ematch2.lean
  tests/lean/run/grind_shelf.lean
Labels: toolchain-available, changelog-language

#6556 feat: propagate implication in the `grind` tactic
  src/Init/Grind/Lemmas.lean
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
Labels: toolchain-available, changelog-language

#6546 feat: Array lemma alignment; fold and map
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6559 feat: basic case-split for `grind`
  src/Init/Grind/Lemmas.lean
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Combinators.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_implies.lean
  tests/lean/run/grind_match1.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_split.lean
Labels: toolchain-available, changelog-language

#6566 feat: add support for erasing the `[grind]` attribute
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  tests/lean/run/grind_erase_attr.lean
Labels: toolchain-available, changelog-language

#6567 feat: trace messages for working and closing goals in the `grind` tactic
  src/Lean/Meta/Tactic/Grind/Cases.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Ctor.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Proj.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  src/Lean/Util/Trace.lean
  tests/lean/run/grind_erase_attr.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_split.lean
Labels: toolchain-available, changelog-language

#6568 feat: add support for `cast`, `Eq.rec`, `Eq.ndrec` to `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6507 feat: add `Int.emod_sub_emod` and `Int.sub_emod_emod`
  src/Init/Data/Int/DivModLemmas.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6486 feat: let `induction` take zero alteratives
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Induction.lean
  tests/lean/inductionParse.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language

#6346 feat: `BitVec.toInt_shiftLeft` theorem
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#6569 feat: split on `match`-expressions in the `grind` tactic
  src/Init/Grind/Util.lean
  src/Lean/Meta/Tactic/Cases.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/CasesMatch.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  tests/lean/run/grind_match1.lean
  tests/lean/run/grind_match2.lean
Labels: toolchain-available, changelog-language

#6479 perf: speed up JSON serialisation
  src/Lean/Data/Json/Printer.lean
Labels: builds-mathlib, toolchain-available, changelog-other

#6574 fix: set LLVM sysroot consistently
  script/prepare-llvm-linux.sh
  script/prepare-llvm-macos.sh
  script/prepare-llvm-mingw.sh
Labels: builds-mathlib, toolchain-available, release-ci, changelog-compiler, backport releases/v4.16.0

#6575 feat: make `classical` tactic incremental
  src/Lean/Elab/Tactic/Classical.lean
Labels: toolchain-available, changelog-language

#6578 fix: forall propagation in `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  tests/lean/run/grind_cat.lean
Labels: toolchain-available, changelog-language

#6581 feat: add `grind` configuration options to control case-splitting
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  tests/lean/run/grind_match2.lean
  tests/lean/run/grind_split.lean
Labels: toolchain-available, changelog-language

#6582 feat: apply E-matching for local lemmas in `grind`
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6584 feat: add helper theorems for handling offsets in `grind`
  src/Init/Grind.lean
  src/Init/Grind/Offset.lean
Labels: changelog-language

#6585 fix: `grind` canonicalizer
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Canon.lean
  tests/lean/run/grind_canon_bug.lean
Labels: toolchain-available, changelog-language

#6586 feat: aligning `List/Array/Vector` lemmas for `map`
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#6589 feat: align `List/Array` lemmas for `filter/filterMap`
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available, changelog-library

#6588 feat: improve `grind` canonicalizer diagnostics
  src/Lean/Meta/Tactic/Grind/Canon.lean
  tests/lean/run/grind_cat2.lean
Labels: toolchain-available, changelog-language

#6591 feat: add UInt32.{lt, le}
  src/Init/Data/UInt/Basic.lean
Labels: toolchain-available, changelog-library

#6563 feat: `Std.Net.Addr`
  src/Std.lean
  src/Std/Net.lean
  src/Std/Net/Addr.lean
  src/runtime/CMakeLists.txt
  src/runtime/uv/net_addr.cpp
  src/runtime/uv/net_addr.h
  tests/lean/run/net_addr.lean
Labels: builds-mathlib, toolchain-available, release-ci, changelog-library

#6595 feat: improve inequality offset support theorems for `grind`
  src/Init/Grind/Offset.lean
  tests/lean/run/grind_offset_ineq_thms.lean
Labels: toolchain-available, changelog-language

#6593 feat: add `simp?` and `dsimp?` in conversion mode
  src/Init/Conv.lean
  src/Lean/Elab/Tactic/Conv/Simp.lean
  tests/lean/run/6164.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6402 feat: BitVec.{toInt, toFin, msb}_udiv
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Nat/Div/Lemmas.lean
Labels: breaks-mathlib, toolchain-available, changelog-library

#6587 feat: add decidable instances for comparison operations of time offset types
  src/Std/Time/Date/Unit/Month.lean
  src/Std/Time/Date/Unit/Week.lean
  src/Std/Time/Time/Unit/Hour.lean
  src/Std/Time/Time/Unit/Millisecond.lean
  src/Std/Time/Time/Unit/Minute.lean
  src/Std/Time/Time/Unit/Nanosecond.lean
  src/Std/Time/Time/Unit/Second.lean
Labels: awaiting-review, toolchain-available, changelog-library

#6306 feat: asynchronous timer API
  src/Std/Internal.lean
  src/Std/Internal/Async.lean
  src/Std/Internal/Async/Basic.lean
  src/Std/Internal/Async/Timer.lean
  tests/lean/run/async_surface_sleep.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#6404 feat: `BitVec.{toFin, toInt, msb}_umod`
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Nat/Div/Lemmas.lean
Labels: toolchain-available, changelog-library

#6599 doc: update FFI description for Int and signed fixed-width ints
  doc/dev/ffi.md
Labels: toolchain-available, changelog-doc

#6596 chore: add lean4-cli to release checklist
  doc/dev/release_checklist.md
  script/release_repos.yml
Labels: toolchain-available

#6606 fix: pattern selection for local lemmas
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6607 feat: add support for splitting on `<->` to `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  tests/lean/run/grind_implies.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6608 fix: `simp_arith`
  src/Lean/Meta/Tactic/LinearArith/Nat/Simp.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6609 feat: improve case-split heuristic used in `grind`
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6610 fix: bug in the `grind` propagator
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_propagate_connectives.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6611 fix: `checkParents` in `grind`
  src/Lean/Meta/Tactic/Grind/Inv.lean
Labels: toolchain-available, changelog-language

#6612 feat: lemmas about Array.append
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/ToArray.lean
Labels: toolchain-available, changelog-library

#6613 feat: improve case split heuristic used in `grind`
  src/Lean/Meta/Tactic/Grind/Split.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6614 feat: improve `[grind =]` attribute
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  tests/lean/run/grind_eq_pattern.lean
Labels: toolchain-available, changelog-language

#6602 fix: allow dot idents to resolve to local names
  src/Lean/Elab/App.lean
  src/Lean/Parser/Basic.lean
  src/Lean/Server/Requests.lean
  src/Std/Time/Date/Unit/Month.lean
  src/Std/Time/Date/Unit/Year.lean
  tests/lean/6601.lean
  tests/lean/6601.lean.expected.out
Labels: breaks-mathlib, toolchain-available, changelog-language

#6603 feat: offset constraints support for the `grind` tactic
  src/Init/Grind/Offset.lean
  src/Lean/Data/AssocList.lean
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/Tactic/FVarSubst.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Arith.lean
  src/Lean/Meta/Tactic/Grind/Arith/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Inv.lean
  src/Lean/Meta/Tactic/Grind/Arith/Main.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset.lean
  src/Lean/Meta/Tactic/Grind/Arith/ProofUtil.lean
  src/Lean/Meta/Tactic/Grind/Arith/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  src/Lean/Meta/Tactic/Grind/ENodeKey.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Inv.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_offset_cnstr.lean
  tests/lean/run/grind_offset_ineq_thms.lean
Labels: toolchain-available, changelog-language

#6615 feat: avoid some redundant proof terms in `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/Tactic/Grind/Arith/ProofUtil.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  tests/lean/run/grind_offset_cnstr.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6616 chore: cleaunp `grind` tests
  tests/lean/run/grind_canon_insts.lean
  tests/lean/run/grind_canon_types.lean
  tests/lean/run/grind_congr.lean
  tests/lean/run/grind_nested_proofs.lean
  tests/lean/run/grind_norm_levels.lean
  tests/lean/run/grind_propagate_connectives.lean
  tests/lean/run/grind_revertAll.lean
Labels: toolchain-available, changelog-no

#6617 feat: finish alignment of `List/Array/Vector.append` lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Zip.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#6605 doc: commit conventions and Mathlib CI
  doc/dev/commit_convention.md
  doc/dev/index.md
Labels: toolchain-available

#6618 feat: exhaustive offset constraint propagation in the `grind` tactic
  src/Init/Grind/Offset.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Arith/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Main.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset.lean
  src/Lean/Meta/Tactic/Grind/Arith/ProofUtil.lean
  src/Lean/Meta/Tactic/Grind/Arith/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  tests/lean/run/grind_offset_cnstr.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6597 fix: trace indentation in info view
  src/Lean/Widget/InteractiveDiagnostic.lean
Labels: builds-mathlib, toolchain-available, changelog-server

#6627 fix: lake: v4.16.0-rc1 trace issues
  src/lake/Lake/Build/Job.lean
Labels: builds-mathlib, toolchain-available, changelog-lake, backport releases/v4.16.0

#6625 feat: UIntX.toBitVec lemmas
  src/Init/Data/UInt/Bitwise.lean
Labels: toolchain-available, changelog-library

#6427 feat: `lean --src-deps`
  src/Lean/Elab/Import.lean
  src/Lean/Util/Path.lean
  src/util/shell.cpp
Labels: toolchain-available, changelog-language

#6505 feat: implement basic async IO with timers
  src/Std/Internal.lean
  src/Std/Internal/Async.lean
  src/Std/Internal/Async/Basic.lean
  src/Std/Internal/Async/Timer.lean
  src/Std/Internal/UV.lean
  src/runtime/CMakeLists.txt
  src/runtime/init_module.cpp
  src/runtime/libuv.cpp
  src/runtime/libuv.h
  src/runtime/object.h
  src/runtime/uv/event_loop.cpp
  src/runtime/uv/event_loop.h
  src/runtime/uv/timer.cpp
  src/runtime/uv/timer.h
  tests/lean/run/async_sleep.lean
  tests/lean/run/async_surface_sleep.lean
Labels: builds-mathlib, toolchain-available, release-ci, changelog-language

#6600 chore: remove functions for compiling decls from Environment
  src/Lean/AddDecl.lean
  src/Lean/Compiler/InitAttr.lean
  src/Lean/Compiler/Old.lean
  src/Lean/CoreM.lean
  src/Lean/ParserCompiler.lean
  tests/lean/run/toExpr.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#6631 fix: lake: set `MACOSX_DEPLOYMENT_TARGET` for shared libs
  src/lake/Lake/Build/Actions.lean
Labels: builds-mathlib, toolchain-available, changelog-lake, backport releases/v4.16.0

#6633 feat: improve `grind` failure message
  src/Init/Grind.lean
  src/Init/Grind/PP.lean
  src/Init/Grind/Util.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_erase_attr.lean
  tests/lean/run/grind_nested_proofs.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6635 chore: display E-matching theorems in `goalToMessageData`
  src/Lean/Meta/Tactic/Grind/PP.lean
Labels: toolchain-available, changelog-no

#6636 feat: model construction for offset constraints
  src/Lean/Meta/Tactic/Grind/Arith/Model.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6622 fix: Windows stage0 linking
  .github/workflows/ci.yml
  CMakeLists.txt
  flake.nix
  nix/bootstrap.nix
  src/CMakeLists.txt
  src/cmake/Modules/FindLibUV.cmake
  stage0/src/CMakeLists.txt
  stage0/src/cmake/Modules/FindLibUV.cmake
Labels: toolchain-available, changes-stage0, release-ci, changelog-no

#6573 feat: faster, linear HashMap.alter and modify
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Basic.lean
  src/Std/Data/DHashMap/Internal/AssocList/Lemmas.lean
  src/Std/Data/DHashMap/Internal/Defs.lean
  src/Std/Data/DHashMap/Internal/List/Associative.lean
  src/Std/Data/DHashMap/Internal/Model.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/HashMap/Basic.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6637 chore: update release checklist
  script/push_repo_release_tag.py
  script/release_checklist.py
Labels: toolchain-available, changelog-no

#6638 chore: fix docstring in `Bitvec.toNat_add_of_lt`
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-doc

#6639 refactor: bv_normalize simp set and implementation
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/AC.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/AndFlatten.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Basic.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/EmbeddedConstraint.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Rewrite.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Simproc.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  src/Std/Tactic/BVDecide/Normalize/Bool.lean
  src/Std/Tactic/BVDecide/Normalize/Canonicalize.lean
  src/Std/Tactic/BVDecide/Normalize/Equal.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-language

#6643 fix: indicate dependency on pkgconf in macOS docs
  doc/make/osx-10.9.md
Labels: toolchain-available, changelog-doc

#6645 feat: offset equalities in `grind`
  src/Init/Grind/Offset.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Arith/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Model.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset.lean
  src/Lean/Meta/Tactic/Grind/Arith/ProofUtil.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_offset.lean
  tests/lean/run/grind_offset_cnstr.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6640 feat: align `List/Array/Vector` `flatten` lemmas
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Bootstrap.lean
  src/Init/Data/Array/Find.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset.lean
  tests/lean/guessLexFailures.lean
Labels: toolchain-available, changelog-library

#6647 chore: fib_correct monadic reasoning example as a test
  tests/lean/run/fib_correct.lean
Labels: toolchain-available

#6648 feat: literals, lower and upper bounds in the offset constraint module within `grind`
  src/Init/Grind/Offset.lean
  src/Lean/Meta/Tactic/Grind/Arith/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Model.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_offset_cnstr.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6646 fix: indicate dependency on pkgconf in ubuntu docs
  doc/make/ubuntu.md
Labels: toolchain-available, changelog-doc

#6649 fix: `grind` canonicalizer state management
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-language

#6641 perf: improve bv_decide preprocessing based on Bitwuzla optimisations
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/AndFlatten.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Basic.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/EmbeddedConstraint.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Rewrite.lean
  tests/lean/run/bv_decide_bool.lean
Labels: toolchain-available, changelog-language

#6211 feat: verify insertMany method for adding lists to HashMaps
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Internal/List/Associative.lean
  src/Std/Data/DHashMap/Internal/Model.lean
  src/Std/Data/DHashMap/Internal/Raw.lean
  src/Std/Data/DHashMap/Internal/RawLemmas.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/HashMap/Basic.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/Raw.lean
  src/Std/Data/HashMap/RawLemmas.lean
  src/Std/Data/HashSet/Basic.lean
  src/Std/Data/HashSet/Lemmas.lean
  src/Std/Data/HashSet/Raw.lean
  src/Std/Data/HashSet/RawLemmas.lean
Labels: builds-mathlib, toolchain-available, P-medium, changelog-library

#6653 fix: improve E-matching pattern selection heuristics
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6654 feat: better support for partial applications in the E-matching procedure
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
Labels: toolchain-available, changelog-language

#6656 feat: improve`grind` diagnostic information
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Ctor.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6650 feat: more grind tests
  tests/lean/run/grind_assoc.lean
  tests/lean/run/grind_list.lean
Labels: toolchain-available, changelog-no

#6657 feat: improve `grind` search procedure
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Solve.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_pre.lean
Labels: toolchain-available, changelog-language

#6290 refactor: lake: use `StateRefT` for `BuildStore`
  src/lake/Lake/Build/Fetch.lean
  src/lake/Lake/Util/StoreInsts.lean
Labels: builds-mathlib, toolchain-available, changelog-lake

#6658 feat: improve case-split heuristic used in `grind`
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_split_issue.lean
Labels: toolchain-available, changelog-language

#6659 fix: `grind` term preprocessor
  src/Lean/Meta/Tactic/Grind/Simp.lean
  tests/lean/run/grind_cat.lean
Labels: toolchain-available, changelog-language

#6662 feat: canonicalizer diagnostics
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_cat2.lean
Labels: toolchain-available, changelog-language

#6660 feat: align List/Array/Vector.flatMap
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Impl.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#6661 feat: Vector.getElem_flatMap
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#6667 feat: align List.replicate/Array.mkArray/Vector.mkVector lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#6630 feat: add `Nat.[shiftLeft_or_distrib`, shiftLeft_xor_distrib`, shiftLeft_and_distrib`, `testBit_mul_two_pow`, `bitwise_mul_two_pow`, `shiftLeft_bitwise_distrib]`
  src/Init/Data/Nat/Bitwise/Lemmas.lean
Labels: toolchain-available, P-medium, changelog-library

#6663 feat: equality resolution for `grind`
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EqResolution.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6669 fix: add workaround for `MessageData` limitations
  src/Lean/Meta/Diagnostics.lean
  src/Lean/Meta/Tactic/Simp/Diagnostics.lean
  tests/lean/run/4171.lean
  tests/lean/run/ack.lean
  tests/lean/run/diagRec.lean
  tests/lean/run/diagnostics.lean
  tests/lean/run/simpDiag.lean
Labels: toolchain-available, changelog-language

#6675 feat: add `simp`-like parameters to `grind`
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  tests/lean/run/grind_params.lean
Labels: toolchain-available, changelog-language

#6664 fix: don't filter out local instances in LCNF toMono pass
  src/Lean/Compiler/LCNF/ToMono.lean
Labels: toolchain-available, changelog-compiler

#6665 feat: add lcAny constant to Prelude
  src/Init/Prelude.lean
Labels: needs-update-stage0, toolchain-available, changelog-compiler

#6682 feat: extensionality theorems in `grind`
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/EqResolution.lean
  src/Lean/Meta/Tactic/Grind/Ext.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#6686 fix: `grind` parameter issues and configuration
  src/Lean/Declaration.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
  tests/lean/run/grind_ematch_patterns.lean
Labels: toolchain-available, changelog-language

#6685 fix: make `#check_failure`'s output be info
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Message.lean
  tests/lean/run/autoLift.lean
Labels: toolchain-available, changelog-language

#6214 refactor: move registration of namespaces on kernel add into elaborator
  src/Lean/AddDecl.lean
  src/Lean/Elab/BuiltinCommand.lean
  src/Lean/Environment.lean
  src/Lean/Replay.lean
  src/library/elab_environment.cpp
Labels: toolchain-available

#6689 chore: `init_grind_norm` command parser
  src/Lean/Meta/Tactic/Grind/Parser.lean
Labels: toolchain-available, changelog-no

#5997 refactor: `getUnfoldableConst*?`
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/GetUnfoldableConst.lean
  src/Lean/Meta/WHNF.lean
Labels: builds-mathlib, toolchain-available

#6688 feat: regression tests for `grind` adapted from `lean-egg`
  tests/lean/run/grind_regression.lean
Labels: toolchain-available, changelog-no

#6690 feat: `init_grind_norm` elaborator
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
Labels: toolchain-available, changelog-no

#6691 feat: Environment.addConstAsync
  src/Lean/AddDecl.lean
  src/Lean/Data/NameTrie.lean
  src/Lean/Data/PrefixTree.lean
  src/Lean/Environment.lean
  src/Lean/Modifiers.lean
  src/Lean/PrivateName.lean
  src/lake/Lake/Load/Lean/Elab.lean
  stage0/src/stdlib_flags.h
  tests/lean/interactive/completionAtPrint.lean
  tests/lean/interactive/completionAtPrint.lean.expected.out
  tests/lean/prvCtor.lean
  tests/lean/prvCtor.lean.expected.out
Labels: toolchain-available, changelog-language

#6692 chore: remove `[grind_norm]` attribute
  src/Init/Grind/Norm.lean
  src/Init/Tactics.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
  tests/lean/run/grind_ematch2.lean
Labels: toolchain-available, changelog-language

#6695 feat: align List/Array/Vector.reverse lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
  tests/lean/run/grind_offset.lean
Labels: toolchain-available, changelog-library

#6696 chore: remove deprecations from 2024-06
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Char/Lemmas.lean
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/List/Zip.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/UInt/Lemmas.lean
Labels: toolchain-available

#6697 feat: refactor List/Array.mapFinIdx to unbundle the Fin argument
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/MapIdx.lean
  src/Init/Data/List/MapIdx.lean
  src/Lean/Meta/IndPredBelow.lean
Labels: toolchain-available, changelog-library

#6698 perf: optimize `setImportedEntries`
  src/Lean/Environment.lean
Labels: toolchain-available

#6700 feat: beta reduction in `grind`
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Beta.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_beta.lean
  tests/lean/run/grind_canon_insts.lean
  tests/lean/run/grind_canon_types.lean
  tests/lean/run/grind_congr.lean
  tests/lean/run/grind_many_eqs.lean
  tests/lean/run/grind_nested_proofs.lean
  tests/lean/run/grind_norm_levels.lean
Labels: toolchain-available, changelog-language

#6705 feat: add `[grind cases]` and `[grind cases eager]` attributes
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
  src/Lean/Meta/Tactic/Grind/Cases.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  tests/lean/run/grind_cases.lean
Labels: toolchain-available, changelog-language

#6707 feat: align `{List/Array/Vector}.{foldl, foldr, foldlM, foldrM}` lemmas
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#6701 feat: complete alignment of `{List,Array,Vector}.{mapIdx,mapFinIdx}`
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/MapIdx.lean
  src/Init/Data/List/MapIdx.lean
  src/Init/Data/Vector.lean
  src/Init/Data/Vector/Basic.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Data/Vector/MapIdx.lean
Labels: toolchain-available, changelog-library

#6668 fix: negative timestamps and `PlainDateTime`s before 1970
  src/Std/Time/DateTime/PlainDateTime.lean
  src/Std/Time/Duration.lean
  src/Std/Time/Internal/UnitVal.lean
  tests/lean/run/timeAPI.lean
  tests/lean/run/timeNegative.lean
  tests/lean/run/timeParse.lean
Labels: toolchain-available, changelog-library
