Repository leanprover/lean4, pull requests merged in 2025-06, with the labels that each got.

#8567 chore: adjust test
  tests/lean/grind/casting.lean
  tests/lean/run/grind_casting_issue.lean
Labels: toolchain-available, changelog-no

#8486 fix: improve error-message hint rendering and API
  src/Lean/Message.lean
  src/Lean/Meta/Hint.lean
  src/Lean/Util/Diff.lean
  tests/lean/run/hintSuggestionMessage.lean
Labels: breaks-mathlib, toolchain-available, changelog-no

#8570 fix: ematch generalized patterns
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  tests/lean/run/grind_ematch_gen_pattern.lean
Labels: toolchain-available, changelog-language

#8259 fix: invalid field notation error for mvar
  src/Lean/Elab/App.lean
  tests/lean/run/4144.lean
  tests/lean/run/invalid_field_notation_mvar.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#8571 doc: fix a typo in ULift's documentation
  src/Init/Prelude.lean
Labels: toolchain-available

#8572 feat: generalized `Option` theorems for `grind`
  src/Init/Data/Option/Lemmas.lean
  src/Init/Grind/Tactics.lean
  src/Init/Grind/Util.lean
  tests/lean/run/grind_ematch_gen_pattern.lean
Labels: toolchain-available, changelog-language

#8575 fix: make simpAppApp? actually bail out on trivial aliases as intended
  src/Lean/Compiler/LCNF/Simp/SimpValue.lean
Labels: toolchain-available, changelog-compiler

#8581 chore: make ToMonoM.State.typeParams an FVarIdHashSet rather than an FVarIdSet
  src/Lean/Compiler/LCNF/ToMono.lean
Labels: toolchain-available

#8579 chore: CI: fix cache
  .github/workflows/build-template.yml
Labels: toolchain-available

#8589 chore: initial `grind` annotations for `List.erase`
  src/Init/Data/List/Erase.lean
Labels: changelog-library

#8592 chore: use HashMap in ToMonoM.State.noncomputableVars
  src/Lean/Compiler/LCNF/ToMono.lean
Labels: toolchain-available

#8594 fix: remove incorrect strictOr/strictAnd optimizations
  src/Lean/Compiler/ConstFolding.lean
  tests/compiler/strictOrSimp.lean
Labels: toolchain-available, changelog-compiler

#8253 feat: add `toInt_smod` and auxilliary theorems
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#8585 feat: improve BitVec.extractLsb' lemma on appended vectors
  src/Init/Data/BitVec/Lemmas.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Simproc.lean
Labels: toolchain-available, changelog-library

#8599 chore: add failing grind test
  tests/lean/grind/grind_local_namespace.lean
Labels: toolchain-available

#8600 chore: grind annotations for List/Array/Vector.any/all
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available, changelog-library

#8602 fix: support Eq.recOn in the new compiler
  src/Lean/Compiler/LCNF/ToLCNF.lean
  tests/lean/run/eqRecursors.lean
Labels: toolchain-available, changelog-compiler

#8604 fix: support compiler.extract_closed option in the new compiler
  src/Lean/Compiler/LCNF/ExtractClosed.lean
Labels: toolchain-available, changelog-compiler

#8590 chore: grind annotations for getElem?_pos and variants
  src/Init/GetElem.lean
  tests/lean/run/grind_list2.lean
Labels: toolchain-available, changelog-library

#8420 feat: introduce `drop` iterator combinator
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/TakeDrop.lean
  src/Std/Data/Iterators/Combinators.lean
  src/Std/Data/Iterators/Combinators/Drop.lean
  src/Std/Data/Iterators/Combinators/Monadic.lean
  src/Std/Data/Iterators/Combinators/Monadic/Drop.lean
  src/Std/Data/Iterators/Combinators/Monadic/Take.lean
  src/Std/Data/Iterators/Lemmas/Combinators.lean
  src/Std/Data/Iterators/Lemmas/Combinators/Drop.lean
  src/Std/Data/Iterators/Lemmas/Combinators/Monadic.lean
  src/Std/Data/Iterators/Lemmas/Combinators/Monadic/Drop.lean
  src/Std/Data/Iterators/Producers/Repeat.lean
  tests/lean/run/iterators.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#8605 chore: add `@[grind]` annotations to `Fin.getElem_fin`
  src/Init/GetElem.lean
Labels: toolchain-available, changelog-library

#8606 chore: initial `@[grind]` annotations for `Array/Vector.range`
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Range.lean
  src/Init/Data/Vector/Range.lean
Labels: toolchain-available, changelog-library

#8608 chore: add failing grind test
  tests/lean/grind/grind_lrat_internal_error.lean
Labels: toolchain-available

#8609 feat: use `grind` to shorten some proofs in the LRAT checker
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Grind.lean
  src/Std/Sat/CNF/Literal.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Assignment.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/CNF.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Clause.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Convert.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/Class.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/Lemmas.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RatAddResult.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RatAddSound.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddSound.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/LRATCheckerSound.lean
Labels: toolchain-available, changelog-language

#8596 feat: make guard_msgs.diff=true the default
  src/Lean/Elab/GuardMsgs.lean
Labels: toolchain-available, changelog-language

#8617 fix: let private names be unresolved in the pretty printer, fix shadowing bug when `pp.universes` is true
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/ResolveName.lean
  tests/lean/private.lean
  tests/lean/private.lean.expected.out
  tests/lean/run/delabConst.lean
Labels: builds-mathlib, toolchain-available, changelog-pp

#8621 fix: bug in the equality resolution procedure in `grind`
  src/Lean/Meta/Tactic/Grind/EqResolution.lean
  tests/lean/grind/lrat_mvar.lean
  tests/lean/run/grind_eqres_bug.lean
Labels: toolchain-available, changelog-language

#8622 feat: add `grind` use case example `IndexMap`
  src/Init/Data/Array/Lemmas.lean
  tests/lean/run/grind_indexmap.lean
  tests/lean/run/grind_indexmap_pre.lean
Labels: toolchain-available, changelog-language

#8624 refactor: move read-only data to `Grind.Context`
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-no

#8620 fix: remove global `NatCast (Fin n)` instance
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Grind/CommRing/Basic.lean
  src/Init/Grind/CommRing/Fin.lean
  src/Init/Grind/CommRing/Poly.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/RingId.lean
  tests/lean/run/fin_coercions.lean
Labels: breaks-mathlib, toolchain-available, changelog-library

#8625 feat: improve `grind` diagnostics for successful case
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-language

#8630 chore: remove slow and unnecessary `@[grind]` annotations
  src/Init/Data/Array/Lemmas.lean
  src/Init/GetElem.lean
  tests/lean/run/grind_indexmap.lean
  tests/lean/run/grind_ite.lean
Labels: toolchain-available

#8631 feat: AIG.relabel(Nat)_unsat_iff for AIGs with empty variable types
  src/Std/Sat/AIG/Relabel.lean
  src/Std/Sat/AIG/RelabelNat.lean
Labels: toolchain-available, changelog-library

#8633 feat: track case-split source in `grind`
  src/Lean/Meta/Tactic/Grind/Beta.lean
  src/Lean/Meta/Tactic/Grind/Ext.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  src/Lean/Meta/Tactic/Grind/MBTC.lean
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_split_issue.lean
Labels: toolchain-available, changelog-language

#8634 fix: don't treat types with erased constructor types as having trivial structure
  src/Lean/Compiler/LCNF/MonoTypes.lean
  tests/lean/run/projWithIrrelevantFields.lean
Labels: toolchain-available, changelog-compiler

#8635 chore: fix formatting
  src/Lean/Compiler/LCNF/Simp/ConstantFold.lean
Labels: toolchain-available

#8637 feat: background theorems for `IntModule`
  src/Init/Grind/CommRing/Basic.lean
  src/Init/Grind/Module/Basic.lean
  src/Init/Grind/Ordered.lean
  src/Init/Grind/Ordered/Linarith.lean
Labels: toolchain-available, changelog-language

#8638 feat: sort equivalence classes in `grind` diagnostics
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Model.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_congr.lean
  tests/lean/run/grind_nested_proofs.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_propagate_connectives.lean
  tests/lean/run/grind_sort_eqc.lean
  tests/lean/run/grind_split_issue.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#8203 feat: bitvector trichotomy lemmas
  src/Init/Data/BitVec/Lemmas.lean
Labels: builds-mathlib, toolchain-available, P-medium, changelog-library

#8640 feat: add `BitVec.setWidth'_eq` to `bv_normalize`
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-library

#8639 feat: complete `grind`'s `ToInt` framework
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Grind/CommRing/BitVec.lean
  src/Init/Grind/CommRing/Fin.lean
  src/Init/Grind/CommRing/SInt.lean
  src/Init/Grind/CommRing/UInt.lean
  src/Init/Grind/Module/Basic.lean
  src/Init/Grind/ToInt.lean
Labels: toolchain-available, changelog-language

#8647 fix: improve precision of the new compiler's noncomputable check for proj
  src/Lean/Compiler/LCNF/ToMono.lean
Labels: toolchain-available, changelog-compiler

#8650 feat: helper theorems for equality detection and coefficent normalization
  src/Init/Grind/Ordered/Linarith.lean
Labels: toolchain-available, changelog-language

#8657 doc: typo in IO.lean
  src/Init/System/IO.lean
Labels: toolchain-available

#8615 feat: introduce empty iterator
  src/Std/Data/Iterators/Combinators/Monadic/Drop.lean
  src/Std/Data/Iterators/Consumers/Monadic/Loop.lean
  src/Std/Data/Iterators/Lemmas/Consumers/Loop.lean
  src/Std/Data/Iterators/Lemmas/Consumers/Monadic.lean
  src/Std/Data/Iterators/Lemmas/Producers.lean
  src/Std/Data/Iterators/Lemmas/Producers/Empty.lean
  src/Std/Data/Iterators/Lemmas/Producers/Monadic.lean
  src/Std/Data/Iterators/Lemmas/Producers/Monadic/Empty.lean
  src/Std/Data/Iterators/Producers.lean
  src/Std/Data/Iterators/Producers/Empty.lean
  src/Std/Data/Iterators/Producers/Monadic.lean
  src/Std/Data/Iterators/Producers/Monadic/Empty.lean
  tests/lean/run/iterators.lean
Labels: toolchain-available, changelog-library

#8663 refactor: AIG doesn't need to be modified for constants
  src/Std/Sat/AIG/Cached.lean
  src/Std/Sat/AIG/CachedGatesLemmas.lean
  src/Std/Sat/AIG/CachedLemmas.lean
  src/Std/Sat/AIG/LawfulOperator.lean
  src/Std/Sat/AIG/RefVecOperator/Fold.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Const.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Add.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Extract.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/GetLsbD.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Mul.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Neg.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/ShiftLeft.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/ShiftRight.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Udiv.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Ult.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Umod.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/ZeroExtend.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Pred.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Substructure.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Const.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Add.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Extract.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/GetLsbD.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Mul.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Neg.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftLeft.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftRight.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Udiv.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Ult.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Umod.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ZeroExtend.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Pred.lean
Labels: toolchain-available, changelog-no

#8419 feat: explicit `defeq` attribute
  src/Init/Data/Fin/Fold.lean
  src/Lean.lean
  src/Lean/AddDecl.lean
  src/Lean/Attributes.lean
  src/Lean/Declaration.lean
  src/Lean/DefEqAttrib.lean
  src/Lean/Elab/DeclModifiers.lean
  src/Lean/Elab/DefView.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/PreDefinition/EqUnfold.lean
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/Nonrec/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Unfold.lean
  src/Lean/Elab/Print.lean
  src/Lean/Meta/Eqns.lean
  src/Lean/Meta/SizeOf.lean
  src/Lean/Meta/Tactic/AuxLemma.lean
  src/Lean/Meta/Tactic/Simp/Rewrite.lean
  src/Lean/Meta/Tactic/Simp/SimpTheorems.lean
  stage0/src/stdlib_flags.h
  tests/lean/1081.lean
  tests/lean/1081.lean.expected.out
  tests/lean/1113.lean
  tests/lean/1433.lean
  tests/lean/1433.lean.expected.out
  tests/lean/dsimpViaConst.lean
  tests/lean/etaStructIssue.lean
  tests/lean/etaStructIssue.lean.expected.out
  tests/lean/interactive/isRflParallel.lean
  tests/lean/interactive/isRflParallel.lean.expected.out
  tests/lean/isDefEqOffsetBug.lean
  tests/lean/isDefEqOffsetBug.lean.expected.out
  tests/lean/run/2961.lean
  tests/lean/run/5667.lean
  tests/lean/run/6789.lean
  tests/lean/run/def20.lean
  tests/lean/run/defeqAttrib.lean
  tests/lean/run/dsimp1.lean
  tests/lean/run/eqnOptions.lean
  tests/lean/run/issue5661.lean
  tests/lean/run/partial_fixpoint.lean
  tests/lean/run/printEqns.lean
  tests/lean/run/proofAsSorry.lean
  tests/lean/run/structuralOverNested.lean
  tests/lean/run/unfoldLemma.lean
  tests/lean/run/wfEqns5.lean
  tests/pkg/module/Module/Basic.lean
  tests/pkg/module/Module/Imported.lean
  tests/pkg/module/Module/ImportedAll.lean
  tests/pkg/module/Module/NonModule.lean
Labels: builds-mathlib, toolchain-available, merge-ci, changelog-language

#8670 feat: `CommRing` interface for `grind` linarith
  src/Init/Grind/CommRing/Poly.lean
  src/Init/Grind/Ordered/Linarith.lean
  src/Init/Grind/Ordered/Order.lean
Labels: toolchain-available, changelog-language

#7738 feat: lake: builtin facet `memoize` toggle
  src/lake/Lake/Build/Executable.lean
  src/lake/Lake/Build/ExternLib.lean
  src/lake/Lake/Build/Index.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Config/FacetConfig.lean
Labels: builds-mathlib, toolchain-available, changelog-lake

#8668 chore: do not interpret `meta` as `noncomputable`
  src/Lean/Elab/DeclModifiers.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available

#8672 chore: support `meta` in `ParseImportsFast`
  src/Lean/Elab/ParseImportsFast.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available

#8675 fix: increase precision of new compiler's noncomputable check
  src/Lean/Compiler/LCNF/ToMono.lean
Labels: toolchain-available, changelog-compiler

#8676 fix: update maxHeartbeats in tests/lean/run/match_expr_perf.lean
  tests/lean/run/match_expr_perf.lean
Labels: toolchain-available, changelog-no

#8677 feat: `grind` linarith module infrastructure
  src/Init/Grind/CommRing/Poly.lean
  src/Init/Grind/Ordered/Linarith.lean
  src/Lean/Meta/Tactic/Grind/Arith.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/IneqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Var.lean
  src/Lean/Meta/Tactic/Grind/Arith/Main.lean
  src/Lean/Meta/Tactic/Grind/Arith/Types.lean
Labels: toolchain-available, changelog-language

#8680 feat: reification and denotation for linarith module in `grind`
  src/Lean/Meta/Tactic/Grind/Arith/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/IneqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Main.lean
Labels: toolchain-available, changelog-language

#8681 fix: only mark a cases discriminant used if it has non-default alt
  src/Lean/Compiler/LCNF/Simp/Main.lean
Labels: toolchain-available, changelog-compiler

#8682 feat: use `CommRing` to normalize linarith expressions
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/IneqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Util.lean
Labels: toolchain-available, changelog-language

#8683 fix: only mark single-alt cases discriminant as used if any param is used
  src/Lean/Compiler/LCNF/Simp/Main.lean
Labels: toolchain-available, changelog-compiler

#8685 chore: fix `LEAN_PATH` for building stage2+ Leanc.lean
  src/stdlib.make.in
Labels: toolchain-available

#8447 feat: lake: use `lean --setup`
  src/Lean/Elab/ParseImportsFast.lean
  src/Lean/Setup.lean
  src/Lean/Util/LeanOptions.lean
  src/lake/Lake/Build.lean
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Executable.lean
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Imports.lean
  src/lake/Lake/Build/Info.lean
  src/lake/Lake/Build/Job/Monad.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/Config/LeanConfig.lean
  src/lake/Lake/Config/LeanLib.lean
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/Lake/Util/FilePath.lean
  src/lake/tests/lean/test.sh
  src/lake/tests/noBuild/ImportTest.lean
  src/lake/tests/noBuild/test.sh
  src/lake/tests/precompileLink/ImportDownstream.lean
  src/lake/tests/precompileLink/test.sh
  src/lake/tests/setupFile/ImportFoo.lean
  src/lake/tests/setupFile/test.sh
Labels: toolchain-available, changelog-lake

#8687 feat: proof term construction infrastructure for linarith in `grind`
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/IneqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/ToExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  tests/lean/run/grind_linarith_1.lean
Labels: toolchain-available, changelog-language

#8689 feat: proof terms generation for `CommRing` and linarith interface
  src/Init/Grind/CommRing/Poly.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/IneqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Util.lean
  tests/lean/run/grind_linarith_1.lean
Labels: toolchain-available, changelog-language

#8692 chore: revert "fix `LEAN_PATH` for building stage2+ Leanc.lean"
  src/stdlib.make.in
Labels: toolchain-available

#8693 fix: denotation functions for interfacing `CommRing` and linarith
  src/Init/Grind/CommRing/Poly.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/DenoteExpr.lean
  tests/lean/run/grind_linarith_1.lean
Labels: toolchain-available, changelog-language

#8669 fix: make unsafeBaseIO noinline
  src/Init/System/IO.lean
Labels: toolchain-available, changelog-library

#8694 feat: `One.one` support in linarith
  src/Init/Grind/Ordered/Linarith.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/IneqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Util.lean
  tests/lean/run/grind_linarith_1.lean
Labels: toolchain-available, changelog-language

#8701 fix: lake: export `LeanOption` in `Lean` from `Lake`
  src/lake/Lake/Config/LeanConfig.lean
Labels: changelog-lake

#8702 feat: add SHA-suffixed PR release tags
  .github/workflows/pr-release.yml
Labels: changelog-other

#8656 feat: enable auto-implicits in lake math template
  src/lake/Lake/CLI/Init.lean
Labels: toolchain-available, changelog-lake

#8704 fix: import completion after `meta import`
  src/Lean/Server/Completion/ImportCompletion.lean
Labels: changelog-no

#8642 chore: begin development cycle for v4.22.0
  src/CMakeLists.txt
Labels: toolchain-available, changelog-no

#8210 feat: equivalence of tree maps
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Std/Data/DTreeMap/AdditionalOperations.lean
  src/Std/Data/DTreeMap/Basic.lean
  src/Std/Data/DTreeMap/Internal/Lemmas.lean
  src/Std/Data/DTreeMap/Internal/Model.lean
  src/Std/Data/DTreeMap/Internal/Queries.lean
  src/Std/Data/DTreeMap/Internal/WF/Lemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Basic.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/Internal/Cut.lean
  src/Std/Data/Internal/List/Associative.lean
  src/Std/Data/TreeMap/Basic.lean
  src/Std/Data/TreeMap/Lemmas.lean
  src/Std/Data/TreeMap/Raw/Basic.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeSet/AdditionalOperations.lean
  src/Std/Data/TreeSet/Basic.lean
  src/Std/Data/TreeSet/Lemmas.lean
  src/Std/Data/TreeSet/Raw/Basic.lean
  src/Std/Data/TreeSet/Raw/Lemmas.lean
Labels: awaiting-review, toolchain-available, changelog-library

#8586 chore: improvements to release checklist and scripts
  doc/dev/release_checklist.md
  script/release_checklist.py
  script/release_steps.py
Labels: documentation, toolchain-available, changelog-no

#8712 fix: erase code of an erased type in LCNF simp
  src/Lean/Compiler/LCNF/Simp/Main.lean
Labels: toolchain-available, changelog-compiler

#8713 fix: ring module in `grind`
  src/Lean/Meta/Tactic/Grind/Arith/CommRing.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Inv.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/PP.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Poly.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Var.lean
  tests/lean/run/grind_ring_1.lean
  tests/lean/run/grind_ring_2.lean
Labels: toolchain-available, changelog-language

#8715 feat: infrastructure for disequality constraints in `grind linarith`
  src/Init/Grind/Ordered/Linarith.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/IneqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/PropagateEq.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Util.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  tests/lean/run/grind_linarith_2.lean
Labels: toolchain-available, changelog-language

#8716 fix: consider any type application of an erased term to be erased
  src/Lean/Compiler/LCNF/MonoTypes.lean
Labels: toolchain-available, changelog-compiler

#8678 feat: strengthen finIdxOf? lemmas
  src/Init/Data/Array/Find.lean
  src/Init/Data/List/Find.lean
Labels: awaiting-author, toolchain-available, changelog-library

#8654 feat: server-side for module hierarchy
  src/Lean/Data/Lsp/Capabilities.lean
  src/Lean/Data/Lsp/Extra.lean
  src/Lean/Data/Lsp/Internal.lean
  src/Lean/Elab/Frontend.lean
  src/Lean/Elab/Import.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/References.lean
  src/Lean/Server/Watchdog.lean
Labels: toolchain-available, changelog-server

#8173 doc: add documentation for builtin attributes
  src/Lean/BuiltinDocAttr.lean
  src/Lean/Class.lean
  src/Lean/Compiler/CSimpAttr.lean
  src/Lean/Compiler/ExportAttr.lean
  src/Lean/Compiler/IR/UnboxResult.lean
  src/Lean/Compiler/ImplementedByAttr.lean
  src/Lean/Compiler/InitAttr.lean
  src/Lean/Compiler/InlineAttrs.lean
  src/Lean/Compiler/NeverExtractAttr.lean
  src/Lean/Compiler/NoncomputableAttr.lean
  src/Lean/Compiler/Specialize.lean
  src/Lean/Elab/App.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/ComputedFields.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/InheritDoc.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/MutualInductive.lean
  src/Lean/Elab/Quotation/Precheck.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/Monotonicity.lean
  src/Lean/Elab/Term.lean
  src/Lean/Elab/Util.lean
  src/Lean/Meta/Coe.lean
  src/Lean/Meta/Instances.lean
  src/Lean/Meta/Match/MatchPatternAttr.lean
  src/Lean/Meta/Tactic/ElimInfo.lean
  src/Lean/Meta/Tactic/Rfl.lean
  src/Lean/Meta/Tactic/Simp/SimpCongrTheorems.lean
  src/Lean/Meta/Tactic/Symm.lean
  src/Lean/PrettyPrinter/Delaborator/Attributes.lean
  src/Lean/PrettyPrinter/Delaborator/Basic.lean
  src/Lean/PrettyPrinter/Formatter.lean
  src/Lean/PrettyPrinter/Parenthesizer.lean
  stage0/src/stdlib_flags.h
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/run/builtinInitStx.lean
Labels: builds-mathlib, toolchain-available, will-merge-soon, P-medium

#8724 fix: allow mixing `module`s and non-`modules` when root is not a `module`
  src/Lean/Environment.lean
Labels: toolchain-available, changelog-no

#8649 feat: pre-stage0 groundwork for named error messages
  src/Lean/DocString/Links.lean
  src/Lean/Exception.lean
  src/Lean/Log.lean
  src/Lean/Message.lean
  src/Lean/Meta/Hint.lean
  src/Lean/Meta/Tactic/TryThis.lean
  src/Lean/Parser/Command.lean
  src/Lean/Parser/Term.lean
  src/Lean/Widget/InteractiveDiagnostic.lean
  tests/lean/docstringLinkValidation.lean.expected.out
  tests/lean/run/docstringRewrites.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#8729 fix: use Arg in LCNF FVarSubst rather than Expr
  src/Lean/Compiler/LCNF/CompilerM.lean
  src/Lean/Compiler/LCNF/JoinPoints.lean
  src/Lean/Compiler/LCNF/Simp/Main.lean
  src/Lean/Compiler/LCNF/Simp/SimpM.lean
  src/Lean/Compiler/LCNF/Specialize.lean
  src/Lean/Compiler/LCNF/ToLCNF.lean
Labels: toolchain-available, changelog-compiler

#8731 chore: fix a typo in a doc comment
  src/Lean/Compiler/LCNF/CompilerM.lean
Labels: toolchain-available

#8735 chore: cleanup of grind tests
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  tests/lean/grind/algebra/field_normalization.lean
  tests/lean/grind/algebra/module_normalization.lean
  tests/lean/grind/algebra/module_relations.lean
  tests/lean/grind/algebra/ordered_modules.lean
  tests/lean/grind/algebra/ring_normalization.lean
  tests/lean/grind/experiments/list.lean
  tests/lean/grind/experiments/list_count.lean
  tests/lean/grind/experiments/map.lean
  tests/lean/grind/grind_local_namespace.lean
  tests/lean/grind/grind_lrat_internal_error.lean
  tests/lean/run/grind_list_count.lean
  tests/lean/run/grind_map.lean
Labels: toolchain-available

#8736 chore: partially revert "feat: lake: use `lean --setup`"
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Facets.lean
  src/lake/Lake/Build/Info.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/Config/Module.lean
  src/lake/tests/lean/test.sh
Labels: builds-mathlib, toolchain-available, changelog-lake

#8737 chore: add failing grind tests from Mathlib
  tests/lean/grind/omega_regressions.lean
  tests/lean/grind/ring_regressions.lean
Labels: toolchain-available

#8752 fix: move structProjCases pass before extendJoinPointContext
  src/Lean/Compiler/LCNF/Passes.lean
Labels: toolchain-available, changelog-compiler

#8754 fix: enable more optimizations on inductives with computed fields in the new compiler
  src/Lean/Compiler/LCNF/ToLCNF.lean
  src/Lean/Compiler/LCNF/ToMono.lean
Labels: toolchain-available, changelog-compiler

#7395 fix: change `show` tactic to work as documented
  src/Init/Control/Lawful/Basic.lean
  src/Init/Control/Lawful/Instances.lean
  src/Init/Core.lean
  src/Init/Data/Array/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/Int/DivMod/Bootstrap.lean
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/Linear.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/List/Zip.lean
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Div/Basic.lean
  src/Init/Data/Nat/Linear.lean
  src/Init/Data/String/Basic.lean
  src/Init/Data/String/Extra.lean
  src/Init/Grind/CommRing/Poly.lean
  src/Init/Internal/Order/Basic.lean
  src/Init/Meta.lean
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic.lean
  src/Lean/Elab/Tactic/Change.lean
  src/Lean/Elab/Tactic/Show.lean
  src/lake/Lake/Util/Name.lean
  tests/lean/interactive/incrementalTactic.lean.expected.out
  tests/lean/run/showTactic.lean
Labels: awaiting-review, builds-mathlib, toolchain-available, P-medium, changelog-language

#8755 chore: rewrite mkFieldParamsForCtorType in a more readable style
  src/Lean/Compiler/LCNF/StructProjCases.lean
Labels: toolchain-available

#8753 fix: refine how `simp` tracks unfolded local definitions
  src/Lean/Elab/MutualDef.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Meta/Closure.lean
  src/Lean/Meta/Tactic/Simp/Main.lean
  tests/lean/run/6655.lean
Labels: builds-mathlib, toolchain-available, changelog-language, force-mathlib-ci

#8757 chore: add test case with bad grind pattern
  tests/lean/grind/dhashmap_pattern.lean
Labels: toolchain-available

#8758 fix: cache TrivialStructureInfo in LCNF toMono
  src/Lean/Compiler/LCNF/MonoTypes.lean
Labels: toolchain-available, changelog-compiler

#8759 feat: model based theory combination for `grind mbtc`
  src/Lean/Meta/Tactic/Grind/Arith/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/MBTC.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/PropagateEq.lean
  src/Lean/Meta/Tactic/Grind/Solve.lean
  tests/lean/run/grind_linarith_2.lean
Labels: toolchain-available, changelog-language

#8739 chore: CI: make "Linux Lake" primary PR CI job
  .github/workflows/build-template.yml
  .github/workflows/ci.yml
  tests/lean/run/importStructure.lean
Labels: toolchain-available

#8534 fix: resolve symbolic links through `IO.FS.realPath` on windows
  src/runtime/io.cpp
  src/util/path.cpp
  src/util/path.h
  tests/lean/run/parsePrelude.lean
  tests/lean/run/realPath.lean
Labels: toolchain-available, release-ci, changelog-library

#8661 perf: update free_sized declaration to be compatible with glibc
  src/include/lean/lean.h
  src/runtime/object.cpp
Labels: toolchain-available

#8776 fix: `natCast` in grind cutsat
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  tests/lean/grind/omega_regressions.lean
  tests/lean/run/grind_cutsat_nat_le.lean
  tests/lean/run/grind_natCast_issue.lean
Labels: changelog-language

#8770 chore: convert `ExtDHashMap` into a one-field structure
  src/Std/Data/ExtDHashMap/Basic.lean
  src/Std/Data/ExtDHashMap/Lemmas.lean
Labels: toolchain-available

#7639 fix: allow arbitrary sorts in structural recursion over reflexive inductive types
  src/Lean/Elab/PreDefinition/Structural/BRecOn.lean
  src/Lean/Elab/PreDefinition/Structural/FindRecArg.lean
  src/Lean/Meta/Constructions/BRecOn.lean
  src/library/suffixes.h
  tests/lean/run/7638.lean
  tests/lean/run/issue4650.lean
Labels: awaiting-review, builds-mathlib, toolchain-available, P-low, changelog-language

#8777 feat: `Field` support in `grind ring`
  src/Init/Grind/CommRing/Poly.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/RingId.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Types.lean
  tests/lean/run/grind_field_div.lean
Labels: changelog-language

#8783 fix: `meta` tag can be added async
  src/Lean/Compiler/MetaAttr.lean
Labels: changelog-no

#8786 feat: improve support for `Field` in grind
  src/Init/Grind/CommRing/Poly.lean
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Util.lean
  tests/lean/run/grind_field_div.lean
Labels: changelog-language

#8789 feat: Rabinowitsch transformation in `grind`
  src/Init/Grind/CommRing/Poly.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/RingId.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Types.lean
  tests/lean/grind/algebra/field_normalization.lean
  tests/lean/grind/ring_regressions.lean
  tests/lean/run/grind_const_pattern.lean
  tests/lean/run/grind_cutsat_diseq_2.lean
  tests/lean/run/grind_cutsat_div_1.lean
  tests/lean/run/grind_cutsat_eq_1.lean
  tests/lean/run/grind_cutsat_nat_le.lean
  tests/lean/run/grind_field_div.lean
  tests/lean/run/grind_field_norm.lean
  tests/lean/run/grind_ring_1.lean
  tests/lean/run/grind_split_issue.lean
Labels: changelog-language

#8751 feat: add the `nondep` field of `Expr.letE` to the C++ data model
  src/Lean/Compiler/LCNF/Level.lean
  src/Lean/Compiler/LCNF/ToLCNF.lean
  src/Lean/Elab/PreDefinition/WF/Preprocess.lean
  src/Lean/Expr.lean
  src/Lean/Meta/AbstractMVars.lean
  src/Lean/Meta/Closure.lean
  src/Lean/Meta/ExprDefEq.lean
  src/Lean/Meta/ExprLens.lean
  src/Lean/Meta/InferType.lean
  src/Lean/Meta/KAbstract.lean
  src/Lean/Meta/SynthInstance.lean
  src/Lean/Meta/Tactic/Lets.lean
  src/Lean/Meta/Transform.lean
  src/Lean/MetavarContext.lean
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/Util/ReplaceExpr.lean
  src/Lean/Util/ReplaceLevel.lean
  src/kernel/expr.cpp
  src/kernel/expr.h
  src/kernel/expr_eq_fn.cpp
  src/library/expr_lt.cpp
  src/library/print.cpp
  tests/lean/run/addDecorationsWithoutPartial.lean
  tests/lean/run/letNonDep.lean
  tests/lean/run/update.lean
Labels: awaiting-review, builds-mathlib, toolchain-available, changelog-language, force-mathlib-ci

#8568 fix: add terminfo for structure fields
  src/Lean/Elab/Structure.lean
Labels: toolchain-available, changelog-language

#8794 feat: `Expr.collectLooseBVars`
  src/Lean/Util.lean
  src/Lean/Util/CollectLooseBVars.lean
  tests/lean/run/collectLooseBVars.lean
Labels: changelog-language

#8795 fix: `grind` ring + linarith internalization
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  tests/lean/run/grind_ring_1.lean
Labels: changelog-language

#8796 fix: `grind linarith` internalization and `HSMul` support
  src/Init/Grind/Module/Basic.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Types.lean
  tests/lean/grind/algebra/module_normalization.lean
  tests/lean/run/grind_linarith_2.lean
  tests/lean/run/grind_module_normalization.lean
Labels: changelog-language

#8800 feat: `Inv.lean` for grind linarith
  src/Lean/Meta/Tactic/Grind/Arith/Inv.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Inv.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Util.lean
  tests/lean/run/grind_field_div.lean
  tests/lean/run/grind_field_norm.lean
  tests/lean/run/grind_linarith_1.lean
  tests/lean/run/grind_linarith_2.lean
  tests/lean/run/grind_module_normalization.lean
Labels: toolchain-available, changelog-no

#8802 fix: prevent floatLetIn from artificially blocking code motion
  src/Lean/Compiler/LCNF/FloatLetIn.lean
Labels: changelog-compiler

#8765 feat: grind annotations for List.Perm
  src/Init/Data/Array/Count.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Array/Perm.lean
  src/Init/Data/Array/Range.lean
  src/Init/Data/List/Count.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/Count.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Data/List/Perm.lean
  src/Init/Data/Vector/Count.lean
  src/Init/Data/Vector/Range.lean
  tests/lean/run/grind_list2.lean
  tests/lean/run/grind_list_count.lean
  tests/lean/run/grind_list_perm.lean
  tests/lean/run/grind_t1.lean
Labels: changelog-library

#8808 feat: missing Nat lemmas
  src/Init/Data/Nat/Basic.lean
Labels: changelog-library

#8722 chore: follow up on #8173 post-stage0 update
  src/Lean/BuiltinDocAttr.lean
  src/Lean/Elab/InheritDoc.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Tactic/Monotonicity.lean
  src/Lean/Elab/Term.lean
  src/Lean/Meta/Instances.lean
  src/Lean/Meta/Tactic/ElimInfo.lean
  src/Lean/Meta/Tactic/Rfl.lean
  src/Lean/Meta/Tactic/Simp/SimpCongrTheorems.lean
  src/Lean/Meta/Tactic/Symm.lean
Labels: toolchain-available, changelog-no

#8805 feat: additional grind annotations for List/Array/Vector lemmas
  src/Init/Data/Array/Count.lean
  src/Init/Data/Array/Extract.lean
  src/Init/Data/Array/InsertIdx.lean
  src/Init/Data/Array/Range.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/Basic.lean
  src/Init/Data/List/Nat/Count.lean
  src/Init/Data/List/Nat/Erase.lean
  src/Init/Data/List/Nat/InsertIdx.lean
  src/Init/Data/List/Nat/Modify.lean
  src/Init/Data/List/Nat/Range.lean
  src/Init/Data/List/Nat/Sublist.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/TakeDrop.lean
  src/Init/Data/Vector/Extract.lean
  src/Init/Data/Vector/InsertIdx.lean
  src/Init/Data/Vector/Range.lean
  tests/lean/run/grind_indexmap.lean
  tests/lean/run/grind_indexmap_pre.lean
  tests/lean/run/grind_list_erase.lean
Labels: toolchain-available, changelog-library

#8812 chore: CI: provide more than 8GB RAM
  .github/workflows/ci.yml
Labels: toolchain-available

#8772 chore: add missing `instance`
  src/Init/Internal/Order/Basic.lean
Labels: toolchain-available

#8817 chore: Run “Linux release” for PRs as secondary job
  .github/workflows/ci.yml
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Proof.lean
Labels: toolchain-available, will-merge-soon

#8822 fix: add a cache for constructor info in toIR
  src/Lean/Compiler/IR/ToIR.lean
Labels: changelog-compiler

#8827 chore: rename BitVec.getLsb' back to BitVec.getLsb
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#8829 chore: reorganize BitVec files
  src/Init/Data/BitVec.lean
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Bootstrap.lean
  src/Init/Data/BitVec/Decidable.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Nat/Div/Lemmas.lean
  src/Init/Data/SInt/Lemmas.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Init/Grind/CommRing/BitVec.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Basic.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Add.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftLeft.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftRight.lean
  src/Std/Tactic/BVDecide/Normalize/Bool.lean
  src/Std/Tactic/BVDecide/Normalize/Canonicalize.lean
  src/Std/Tactic/BVDecide/Normalize/Equal.lean
  src/Std/Tactic/BVDecide/Reflect.lean
Labels: toolchain-available, changelog-library

#8830 chore: move `grind` algebra instances into Init.GrindInstances
  src/Init.lean
  src/Init/Grind.lean
  src/Init/Grind/CommRing.lean
  src/Init/Grind/Norm.lean
  src/Init/Grind/Ordered/Field.lean
  src/Init/Grind/Ordered/Int.lean
  src/Init/Grind/Ordered/Linarith.lean
  src/Init/Grind/Ordered/Ring.lean
  src/Init/Grind/Ring.lean
  src/Init/Grind/Ring/Basic.lean
  src/Init/Grind/Ring/Field.lean
  src/Init/Grind/Ring/Poly.lean
  src/Init/Grind/ToInt.lean
  src/Init/GrindInstances.lean
  src/Init/GrindInstances/Ring.lean
  src/Init/GrindInstances/Ring/BitVec.lean
  src/Init/GrindInstances/Ring/Fin.lean
  src/Init/GrindInstances/Ring/Int.lean
  src/Init/GrindInstances/Ring/SInt.lean
  src/Init/GrindInstances/Ring/UInt.lean
  src/Init/GrindInstances/ToInt.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Poly.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/RingId.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/ToExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/IneqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/PropagateEq.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
Labels: toolchain-available, changelog-library

#8831 fix: cache scalar type info in toIR
  src/Lean/Compiler/IR/ToIR.lean
Labels: changelog-compiler

#8836 feat: generalize embedding of CommSemiring into its CommRing envelope to the noncommutative case
  src/Init/Grind/Ring/Envelope.lean
Labels: toolchain-available, changelog-language

#8811 feat: add `BitVec.(toNat, toInt, toFin)_shiftLeftZeroExtend`
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#8845 feat: proof-by-reflection support for converting semiring terms into ring ones
  src/Init/Grind/Ring.lean
  src/Init/Grind/Ring/Envelope.lean
  src/Init/Grind/Ring/OfSemiring.lean
Labels: changelog-language

#8850 feat: grind annotations for Prod
  src/Init/Data/Prod.lean
  tests/lean/run/grind_prod.lean
Labels: toolchain-available, changelog-library

#8792 feat: make sure `clear_value` preserves local context order
  src/Lean/Meta/Tactic/Replace.lean
  src/Lean/Meta/Tactic/Revert.lean
  tests/lean/run/clear_value.lean
Labels: builds-mathlib, toolchain-available, changelog-language, force-mathlib-ci

#8858 chore: add a failing `grind` test
  tests/lean/grind/nat_repeat.lean
Labels: toolchain-available, changelog-no

#8856 fix: set public aux decl prefix in `init_grind_norm`
  src/Lean/Elab/Tactic/Grind.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available, changelog-no

#8863 chore: add missing List.eraseIdx_insertIdx deprecation
  src/Init/Data/List/Nat/InsertIdx.lean
Labels: toolchain-available

#8546 feat: add leading zero counter `BitVec.clz` and bitblaster circuit/infrastructure
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reflect.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/BVDecide/Reify.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Basic.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Impl/Operations/Clz.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Clz.lean
  src/Std/Tactic/BVDecide/Reflect.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: toolchain-available, changelog-library

#8873 chore: delete disabled new-compiler tests that are no longer very useful
  tests/lean/new-compiler/CompilerConstantFold.lean
  tests/lean/new-compiler/CompilerConstantFold.lean.expected.out
  tests/lean/new-compiler/unhygienicCode.lean.expected.out
Labels: toolchain-available

#8875 chore: remove brittle new compiler tests that depend on internal decls
  tests/lean/run/CompilerCSE.lean
  tests/lean/run/CompilerFindJoinPoints.lean
  tests/lean/run/CompilerFloatLetIn.lean
  tests/lean/run/CompilerPullInstances.lean
  tests/lean/run/CompilerSimp.lean
Labels: toolchain-available

#8847 feat: generalize Lean.Grind.IsCharP to semirings
  src/Init/Grind/Ordered/Ring.lean
  src/Init/Grind/Ring/Basic.lean
  src/Init/GrindInstances/Ring/BitVec.lean
  src/Init/GrindInstances/Ring/Fin.lean
  src/Init/GrindInstances/Ring/Int.lean
  src/Init/GrindInstances/Ring/SInt.lean
  src/Init/GrindInstances/Ring/UInt.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/RingId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
Labels: toolchain-available, changelog-language

#8878 feat: add grind annotations for List/Array/Vector monadic functions
  src/Init/Data/Array/Monadic.lean
  src/Init/Data/List/Control.lean
  src/Init/Data/List/Monadic.lean
  src/Init/Data/Vector/Monadic.lean
Labels: toolchain-available, changelog-library

#8879 chore: remove redundant field from Lean.Grind.IntModule
  src/Init/Grind/Module/Basic.lean
  src/Init/Grind/Ring/Basic.lean
Labels: toolchain-available

#8178 feat: BitVec.msb_sdiv
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#8882 chore: @[expose] defs that appear in grind proof terms
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/OfNat.lean
  src/Init/Grind/Util.lean
Labels: toolchain-available, changelog-language

#8889 chore: minimize grind panic
  tests/lean/grind/panic.lean
Labels: toolchain-available

#8387 feat: improve error behavior of `end` command
  src/Lean/Elab/BuiltinCommand.lean
  tests/lean/invalidEnd.lean
  tests/lean/invalidEnd.lean.expected.out
  tests/lean/run/endErrors.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#8872 style: replace `HEq x y` with `x ≍ y`
  src/Init/Data/List/Perm.lean
  src/Init/Grind/Util.lean
  src/Init/Prelude.lean
  src/Init/PropLemmas.lean
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Ext.lean
  src/Lean/Meta/AppBuilder.lean
  src/Lean/Meta/CongrTheorems.lean
  src/Lean/Meta/Injective.lean
  src/Lean/Meta/Match/MatchEqs.lean
  src/Lean/Meta/Match/MatcherApp/Transform.lean
  src/Lean/Meta/Tactic/Congr.lean
  src/Lean/Meta/Tactic/Contradiction.lean
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/MatchCond.lean
  src/Lean/Meta/Tactic/Grind/Proof.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  src/Lean/Meta/Tactic/Subst.lean
  src/Std/Data/Iterators/Lemmas/Equivalence/StepCongr.lean
  tests/lean/223.lean
  tests/lean/223.lean.expected.out
  tests/lean/calcErrors.lean
  tests/lean/calcErrors.lean.expected.out
  tests/lean/doSeqRightIssue.lean
  tests/lean/doSeqRightIssue.lean.expected.out
  tests/lean/match3.lean
  tests/lean/ppMotives.lean
  tests/lean/run/congrTactic.lean
  tests/lean/run/discrRefinement2.lean
  tests/lean/run/ext.lean
  tests/lean/run/ext1.lean
  tests/lean/run/grind_bool_prop.lean
  tests/lean/run/grind_congr1.lean
  tests/lean/run/grind_eq.lean
  tests/lean/run/grind_heq_proof_issue.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_propagate_connectives.lean
  tests/lean/run/grind_t1.lean
  tests/lean/run/heqSubst.lean
  tests/lean/run/injHEq.lean
  tests/lean/run/linearNoConfusion.lean
  tests/lean/run/rflTacticErrors.lean
  tests/lean/run/splitList.lean
Labels: toolchain-available

#8893 fix: missing `isEqFalse`
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  tests/lean/run/grind_dvd_propagate_issue.lean
Labels: toolchain-available, changelog-language

#8761 chore: convert `DHashMap` to a structure
  src/Std/Data/DHashMap/Basic.lean
  src/Std/Data/DHashMap/Lemmas.lean
Labels: toolchain-available

#8897 chore: Init: clean up some simp calls
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/List/Range.lean
  src/Init/Data/Option/Array.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/DTreeMap/Lemmas.lean
  src/Std/Data/DTreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeMap/Lemmas.lean
  src/Std/Data/TreeMap/Raw/Lemmas.lean
  src/Std/Data/TreeSet/Lemmas.lean
  src/Std/Data/TreeSet/Raw/Lemmas.lean
Labels: toolchain-available, changelog-library

#8899 fix: make `mkHCongrWithArityForConst?` compatible with parallelism
  src/Lean/Meta/CongrTheorems.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#8906 chore: a few missing grind typeclass docstrings
  src/Init/Grind/Module/Basic.lean
  src/Init/Grind/Ring/Basic.lean
Labels: toolchain-available

#8907 chore: add a test for #4716, which is fixed by the new compiler
  tests/lean/run/4716.lean
Labels: toolchain-available

#8892 feat: fix pretty printing of grind attributes
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/grind_pp_attr.lean
Labels: toolchain-available, changelog-language
