Repository leanprover/lean4, pull requests merged in 2025-08, with the labels that each got.

#9656 chore: failing test cases for grind regressions vs omega
  tests/lean/grind/algebra/omega.lean
  tests/lean/grind/algebra/products.lean
Labels: changelog-language

#9634 feat: use name resolution for dot identifier notation
  src/Lean/Elab/App.lean
  src/Lean/Expr.lean
  src/Lean/Meta/WHNF.lean
  src/Lean/Server/CodeActions/UnknownIdentifier.lean
  src/Lean/Server/Completion/CompletionCollectors.lean
  src/Lean/Server/Completion/CompletionUtils.lean
  tests/lean/interactive/dottedIdentNotation.lean
  tests/lean/interactive/dottedIdentNotation.lean.expected.out
  tests/lean/run/dottedIdentNotation.lean
  tests/lean/scientific.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language

#9652 fix: build with libuv pre-1.45.0 (part 2)
  src/runtime/uv/system.cpp
  tests/lean/run/async_systems_info.lean
Labels: toolchain-available, changelog-no

#9660 chore: bump stack limit in benchmark
  tests/bench/speedcenter.exec.velcom.yaml
Labels: changelog-no

#9667 chore: make datokrat code owner for iterators, ranges and slices
  CODEOWNERS
Labels: toolchain-available

#9670 fix: add `CommRing.Expr.intCast k` and `CommRing.Expr.natCast k`
  src/Init/Grind/Ring/Poly.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/SafePoly.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/ToExpr.lean
  tests/lean/run/grind_linarith_2.lean
  tests/lean/run/grind_natCast_intCast.lean
Labels: changelog-language

#9671 fix: normalize `SMul.smul` for `Semiring` and `Ring`
  src/Init/Grind/Norm.lean
  tests/lean/run/grind_smul_issue.lean
Labels: changelog-language

#9673 fix: user provided `ToInt.toInt` applications
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  tests/lean/run/grind_toInt_issue.lean
Labels: changelog-no, changelog-language

#9675 feat: `Fin.val` support in `grind cutsat`
  src/Init/Data/Int/OfNat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  tests/lean/run/grind_finVal.lean
Labels: changelog-language

#9679 feat: warn `grind` redundant parameters
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  tests/lean/run/grind_warn_param.lean
Labels: changelog-language

#9683 chore: update `tests/lean/grind` todo folder
  tests/lean/grind/algebra/bitvec.lean
  tests/lean/grind/algebra/exponents.lean
  tests/lean/grind/algebra/linarith_cc.lean
  tests/lean/grind/algebra/nat_module.lean
  tests/lean/grind/algebra/nat_semiring.lean
  tests/lean/grind/algebra/omega.lean
Labels: changelog-no

#9681 perf: properly specialize through `PrefixTree`
  src/Lean/Data/PrefixTree.lean
Labels: builds-mathlib, toolchain-available

#9686 feat: clear `implDetail` local declarations in `grind`
  src/Lean/Meta/Tactic/Grind/Main.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
  tests/lean/run/grind_ignore_impl_detail.lean
Labels: changelog-language

#9646 perf: create unfolding theorem for wf-rec in one go
  src/Lean/Elab/PreDefinition/Main.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Lean/Elab/PreDefinition/WF/Unfold.lean
  src/Lean/Meta/Constructions/CasesOn.lean
  src/Lean/Meta/Match/MatcherApp/Basic.lean
  tests/lean/run/issue9646.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9688 chore: avoid calling into `lake` twice from CMake build
  src/CMakeLists.txt
  src/stdlib.make.in
Labels: toolchain-available

#9604 fix: lake: thin archives for Windows bootstrap only
  src/lake/Lake/Build/Actions.lean
  src/lake/Lake/Build/Library.lean
  stage0/src/stdlib_flags.h
Labels: toolchain-available, changelog-lake

#9697 fix: lake: module lookup by source w/ multiple `.`
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Util/FilePath.lean
  src/lake/tests/lean/Lib/Foo.Bar.lean
  src/lake/tests/lean/test.sh
  src/lake/tests/setupFile/Test/Foo.Bar.lean
  src/lake/tests/setupFile/test.sh
Labels: toolchain-available, changelog-lake

#9698 feat: lake: improve query formatting
  src/lake/Lake/Config/Dynlib.lean
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Config/OutFormat.lean
  src/lake/Lake/Config/Package.lean
Labels: changelog-lake

#9643 perf: MatchEqs.simpH: do not use contradiction
  src/Lean/Meta/Match/MatchEqs.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9699 feat: propagation for functions with singleton domain in `grind`
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_fun_singleton.lean
Labels: changelog-language

#9700 fix: assertion violations at `grind` `checkInvariants`
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
Labels: changelog-language

#9701 fix: Use non-overloading `Std.Do.Triple` notation in SpecLemmas.lean
  src/Std/Do/Triple/SpecLemmas.lean
Labels: changelog-language, changelog-library

#9706 perf: add `Poy.combine_mul_k`
  src/Init/Data/Int/Linear.lean
Labels: changelog-language

#9708 chore: minor improvements
  src/Init/Data/String/Basic.lean
  src/Std/Data/DHashMap/Internal/WF.lean
Labels: changelog-no

#9714 perf: `Expr.toPoly` in `grind`
  src/Init/Grind/Ring/Poly.lean
  tests/lean/grind/algebra/omega.lean
Labels: changelog-language

#9702 fix: mark __x patterns as impl details in match and intro
  src/Lean/Elab/Binders.lean
  src/Lean/Elab/BindersUtil.lean
  src/Lean/Elab/Match.lean
  tests/lean/run/implDetailBinder.lean
Labels: toolchain-available, changelog-language

#9703 fix: correctly handle non-`Nat` literal types in LCNF `elimDeadBranches`
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
  tests/lean/run/elimDeadBranchesUInt64Literal.lean
Labels: toolchain-available, changelog-compiler

#9720 fix: remove incorrect error in LCNF's `check`
  src/Lean/Compiler/LCNF/Check.lean
  tests/lean/run/9692.lean
Labels: changelog-compiler

#9721 fix: tag S/UInt conversions with int_toBitVec
  src/Init/Data/SInt/Lemmas.lean
  src/Init/Data/UInt/Lemmas.lean
  tests/lean/run/bv_uint.lean
Labels: changelog-library

#9666 feat: default `let rec` and `where` decls to private under the module system
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Fin/Fold.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/List/Impl.lean
  src/Init/Data/List/Sort/Impl.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Nat/Fold.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Grind/Ordered/Linarith.lean
  src/Lean/DeclarationRange.lean
  src/Lean/Elab/LetRec.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Sat/AIG/CNF.lean
  tests/pkg/module/Module/ImportedAll.lean
Labels: builds-mathlib, toolchain-available, merge-ci, changelog-language

#9722 chore: show `@[expose]` attribute in `#print`
  src/Lean/Elab/Print.lean
  tests/lean/run/derivingRepr.lean
  tests/pkg/module/Module/Basic.lean
Labels: toolchain-available

#9716 refactor: move import validation to parser & Lake
  src/Lean/Elab/Import.lean
  src/Lean/Elab/ParseImportsFast.lean
  src/Lean/Parser/Module.lean
  src/lake/Lake/Build/Module.lean
  src/lake/tests/module/ErrorTest/CrossPackageImportAll.lean
  src/lake/tests/module/clean.sh
  src/lake/tests/module/dep/Dep/Module.lean
  src/lake/tests/module/dep/lakefile.toml
  src/lake/tests/module/lakefile.toml
  src/lake/tests/module/test.sh
  tests/lean/moduleKeywords.lean
  tests/lean/moduleKeywords.lean.expected.out
  tests/pkg/module/Module.lean
  tests/pkg/module/Module/NonModule.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9507 fix: Make `mvcgen` `mintro` let/have bindings (#9474)
  src/Lean/Elab/Tactic/Do/VCGen.lean
  tests/lean/run/9365.lean
  tests/lean/run/9474.lean
  tests/lean/run/doLogicTests.lean
Labels: changelog-language

#9734 doc: more careful `Promise.result!` docstring
  src/Init/System/Promise.lean
Labels: builds-mathlib, toolchain-available

#9709 chore: add `lakeprof` benchmarks
  script/bench.sh
  tests/bench/accumulate_profile.py
  tests/bench/speedcenter.exec.velcom.yaml
Labels: builds-mathlib, toolchain-available

#9715 refactor: simplify `AddConstAsyncResult.commitCheckEnv` use
  src/Lean/Elab/MutualDef.lean
  src/Lean/Environment.lean
Labels: builds-mathlib, toolchain-available

#9762 refactor: restore `Subarray.foldl` and `Subarray.forIn` signatures
  src/Init/Data/Slice/Array/Iterator.lean
Labels: builds-mathlib, toolchain-available

#9757 feat: Add `grind` annotations for key `SPred` lemmas
  src/Lean/Elab/Tactic/Do/ProofMode/Specialize.lean
  src/Std/Do/SPred/DerivedLaws.lean
  src/Std/Do/SPred/SPred.lean
  src/Std/Do/SPred/SVal.lean
  src/Std/Do/Triple/Basic.lean
Labels: changelog-library

#9759 feat: default `let rec` and `where` decls to private under the module system
  src/Init/Data/Array/Basic.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/Fin/Fold.lean
  src/Init/Data/Fin/Lemmas.lean
  src/Init/Data/Int/Basic.lean
  src/Init/Data/List/Impl.lean
  src/Init/Data/List/Sort/Impl.lean
  src/Init/Data/List/ToArray.lean
  src/Init/Data/Nat/Fold.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Grind/Ordered/Linarith.lean
  src/Init/Grind/Ring/Envelope.lean
  src/Init/Grind/Ring/OfSemiring.lean
  src/Init/Grind/Ring/Poly.lean
  src/Lean/DeclarationRange.lean
  src/Lean/Elab/LetRec.lean
  src/Lean/Elab/PreDefinition/WF/Eqns.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Sat/AIG/CNF.lean
  stage0/src/stdlib_flags.h
  tests/lean/doubleReset.lean.expected.out
  tests/lean/run/986.lean
  tests/lean/run/998.lean
  tests/lean/run/atomValidation.lean
  tests/lean/run/grind_qsort.lean
  tests/lean/run/hintWordDiff.lean
  tests/lean/run/wfUnfold.lean
  tests/pkg/module/Module/ImportedAll.lean
Labels: toolchain-available, changelog-no

#9761 fix: panic on duplicate private def in public section
  src/Lean/Elab/DeclModifiers.lean
  tests/pkg/module/Module/Basic.lean
Labels: changelog-no

#9772 fix: projection propagation in `grind`
  src/Lean/Meta/Tactic/Grind/Proj.lean
  tests/lean/run/grind_9769.lean
Labels: changelog-language

#9776 fix: merge simplification and unfolding steps in `grind`
  src/Lean/Meta/Tactic/Grind/Simp.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
  tests/lean/run/grind_9610.lean
Labels: toolchain-available, changelog-language

#9780 feat: extend grind category theory tests
  tests/lean/run/grind_cat.lean
Labels: changelog-language

#9781 fix: proper hygiene for goals generated by `mvcgen`
  src/Lean/Elab/Tactic/Do/VCGen/Basic.lean
  tests/lean/run/doLogicTests.lean
Labels: changelog-language

#9778 feat: use the metavariable index when pretty printing
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/815b.lean.expected.out
  tests/lean/interactive/autoBoundIssue.lean.expected.out
  tests/lean/run/4144.lean
  tests/lean/run/haveTactic.lean
  tests/lean/run/inferTypeFailure.lean
  tests/lean/run/ppMVars.lean
Labels: toolchain-available, changelog-pp

#9792 fix: `@[expose]` `String.firstDiffPos` and `String.extract`
  src/Init/Data/String/Basic.lean
Labels: breaks-mathlib, toolchain-available, changelog-library, force-mathlib-ci

#9793 chore: `@[expose]` `List.filterMapTR`
  src/Init/Data/List/Impl.lean
Labels: breaks-mathlib, toolchain-available, force-mathlib-ci

#9794 chore: `@[expose]` `List.mapIdxM`
  src/Init/Data/List/MapIdx.lean
Labels: toolchain-available

#9782 fix: `Inhabited` instance of `StdGen`
  src/Init/Data/Random.lean
Labels: toolchain-available, changelog-library

#9805 feat: Improved API for invariants and postconditions
  src/Lean/Elab/Tactic/Do/Spec.lean
  src/Lean/Elab/Tactic/Do/Syntax.lean
  src/Lean/Elab/Tactic/Do/VCGen.lean
  src/Std/Do/PostCond.lean
  src/Std/Do/Triple/Basic.lean
  src/Std/Do/Triple/SpecLemmas.lean
  src/Std/Do/WP/Basic.lean
  src/Std/Tactic/Do/Syntax.lean
  tests/lean/run/bhaviksSampler.lean
  tests/lean/run/doLogicTests.lean
  tests/lean/run/pairsSumToZero.lean
Labels: changelog-library

#9808 chore: remove leftover
  src/Lean/Meta/CongrTheorems.lean
Labels: changelog-no

#9812 chore: include generation in `grind.internalize` trace message
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  tests/lean/run/grind_implies.lean
  tests/lean/run/grind_pattern2.lean
Labels: changelog-no

#9814 perf: `normalizeLevels` in `grind`
  src/Lean/Level.lean
  src/Lean/Meta/Tactic/Grind/Util.lean
Labels: changelog-language

#9816 refactor: split the LCNF pass list into separate base/mono lists
  src/Lean/Compiler/LCNF/CompilerM.lean
  src/Lean/Compiler/LCNF/Main.lean
  src/Lean/Compiler/LCNF/PassManager.lean
  src/Lean/Compiler/LCNF/Passes.lean
  src/Lean/Compiler/LCNF/Testing.lean
  tests/lean/run/inlineApp.lean
Labels: toolchain-available

#9819 fix: have `unsafe` term produce an opaqueDecl
  src/Lean/Elab/BuiltinNotation.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9818 fix: get `DecidableEq` deriving handler to work for enumerations in higher universes
  src/Lean/Elab/Deriving/DecEq.lean
  tests/lean/run/9541.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9824 refactor: lake: reorganize `tests/module`
  src/lake/tests/module/Test/Module/Import.lean
  src/lake/tests/module/Test/Module/ImportAll.lean
  src/lake/tests/module/Test/Module/ImportAllImport.lean
  src/lake/tests/module/Test/Module/ImportAllImportAll.lean
  src/lake/tests/module/Test/Module/ImportAllMetaImport.lean
  src/lake/tests/module/Test/Module/ImportImport.lean
  src/lake/tests/module/Test/Module/ImportImportAll.lean
  src/lake/tests/module/Test/Module/ImportMetaImport.lean
  src/lake/tests/module/Test/Module/ImportPublicMetaImport.lean
  src/lake/tests/module/Test/Module/MetaImport.lean
  src/lake/tests/module/Test/Module/MetaImportPublicImport.lean
  src/lake/tests/module/Test/Module/PromoteImport.lean
  src/lake/tests/module/Test/Module/PromoteTransImport.lean
  src/lake/tests/module/Test/Module/PublicImport.lean
  src/lake/tests/module/Test/Module/PublicMetaImport.lean
  src/lake/tests/module/Test/ModuleAllTransImportAll.lean
  src/lake/tests/module/Test/ModuleAllTransMetaImport.lean
  src/lake/tests/module/Test/ModuleAllTransPrivateImport.lean
  src/lake/tests/module/Test/ModuleMetaTransImport.lean
  src/lake/tests/module/Test/ModulePromoteTransImport.lean
  src/lake/tests/module/Test/ModuleTransImportAll.lean
  src/lake/tests/module/Test/ModuleTransMetaImport.lean
  src/lake/tests/module/Test/ModuleTransPrivateImport.lean
  src/lake/tests/module/Test/ModuleTransPrivateMetaImport.lean
  src/lake/tests/module/Test/NonModule/Import.lean
  src/lake/tests/module/Test/NonModule/ImportModuleImport.lean
  src/lake/tests/module/Test/NonModuleTransImport.lean
  src/lake/tests/module/test.sh
Labels: toolchain-available, changelog-no

#9800 feat: make delta deriving more robust and handle binders
  src/Lean/AddDecl.lean
  src/Lean/Elab/Deriving/Basic.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Parser/Command.lean
  src/lake/Lake/Config/ConfigDecl.lean
  src/lake/Lake/Config/FacetConfig.lean
  src/lake/Lake/Config/Script.lean
  tests/lean/defInst.lean
  tests/lean/defInst.lean.expected.out
  tests/lean/run/derivingDelta.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9827 fix: support overapplication of `Quot.lift` in the compiler
  src/Lean/Compiler/LCNF/ToMono.lean
  tests/lean/run/9806.lean
Labels: changelog-compiler

#9831 feat: Add delaborator for `Std.Range`
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
Labels: changelog-language

#9833 fix: Work around a DefEq bug in `mspec` involving delayed assignments
  src/Lean/Elab/Tactic/Do/ProofMode/Pure.lean
  src/Lean/Elab/Tactic/Do/Spec.lean
Labels: changelog-language

#9723 refactor: reduce `omega`'s dependency on fvar IDs
  src/Lean/Elab/Tactic/Omega/Frontend.lean
  src/Lean/Elab/Tactic/Omega/OmegaM.lean
Labels: builds-mathlib, toolchain-available

#9799 fix: replace 'D' with 'd' for day representation in long date format
  src/Std/Time/Format.lean
  tests/lean/run/timeCanonFormats.lean
Labels: toolchain-available, changelog-library, builds-manual

#9847 fix: check for recursive decls before instance proj inlining
  src/Lean/Compiler/LCNF/Simp/InlineProj.lean
  tests/lean/run/9624.lean
Labels: changelog-compiler

#9853 fix: additional numeral normalization in `grind`
  src/Lean/Meta/Tactic/Grind/Arith/Simproc.lean
  tests/lean/run/grind_9828.lean
Labels: changelog-language

#9857 fix: E-matching patterns containing ground universe polymorphic patterns in `grind`
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  tests/lean/run/grind_univ_poly_ground_pattern.lean
Labels: changelog-language

#9860 fix: `grind` theorem activation
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  tests/lean/run/grind_9856.lean
Labels: changelog-language

#9864 feat: add array access functions that return a borrowed result
  src/Init/Prelude.lean
  src/include/lean/lean.h
Labels: toolchain-available, changelog-compiler

#9866 perf: avoid ref count increments for borrowed array accesses
  src/Lean/Compiler/IR/RC.lean
Labels: changelog-compiler

#9878 chore: `Eq.refl`
  src/Lean/Expr.lean
  src/Lean/Meta/LitValues.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
Labels: changelog-no

#9865 feat: kernel hint for proof-by-reflection
  src/Init/Core.lean
  src/Lean/Expr.lean
  src/Lean/Meta/LitValues.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/ToInt.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Proof.lean
  src/Lean/Meta/Tactic/Grind/Core.lean
  src/Lean/Meta/Tactic/Simp/Arith/Int/Simp.lean
  src/Lean/Meta/Tactic/Simp/Arith/Nat/Simp.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Nat.lean
  src/kernel/type_checker.cpp
  src/kernel/type_checker.h
  tests/lean/run/grind_9854.lean
  tests/lean/run/grind_linarith_2.lean
  tests/lean/run/simp_int_arith.lean
Labels: toolchain-available, changelog-language

#9883 feat: warning based on patterns for `grind`
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Std/Tactic/BVDecide/LRAT/Internal/Formula/RupAddResult.lean
  tests/lean/run/grind_warn_param.lean
Labels: toolchain-available, changelog-language

#9884 chore: move tests that are working
  tests/lean/grind/algebra/omega.lean
  tests/lean/run/grind_omega_tests.lean
Labels: toolchain-available, changelog-no

#9889 feat: `simp` and `grind` rules for `ExceptCond`s
  src/Std/Do/PostCond.lean
Labels: changelog-library

#9888 feat: Aggressively eta expand before applying a spec in `mvcgen`
  src/Lean/Elab/Tactic/Do/ProofMode/MGoal.lean
  src/Lean/Elab/Tactic/Do/ProofMode/Pure.lean
  src/Lean/Elab/Tactic/Do/VCGen.lean
  src/Lean/Elab/Tactic/Do/VCGen/Split.lean
  src/Lean/Expr.lean
  src/Std/Tactic/Do/Syntax.lean
  tests/lean/run/9581.lean
  tests/lean/run/bhaviksSampler.lean
  tests/lean/run/doLogicTests.lean
Labels: changelog-language

#9894 fix: Rename M.by_wp lemmas according to naming convention
  src/Std/Do/WP/Basic.lean
  tests/lean/run/doLogicTests.lean
  tests/lean/run/pairsSumToZero.lean
Labels: changelog-library

#9901 fix: normalize `Nat.cast` and `Int.cast` of numerals in `grind`
  src/Init/Grind/Ring/Basic.lean
  src/Init/MetaTypes.lean
  src/Lean/Meta/Tactic/Grind/Arith/Simproc.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/BitVec.lean
  tests/lean/run/grind_9321.lean
Labels: changelog-language

#9902 fix: panic at invalid pattern in `grind`
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  tests/lean/run/grind_9899.lean
  tests/lean/run/grind_pattern1.lean
Labels: changelog-language

#9877 fix: fun_induction to instantiateMVars
  src/Lean/Meta/Tactic/FunIndCollect.lean
  tests/lean/run/issue9844.lean
Labels: toolchain-available, changelog-language

#9914 fix: duplicate private instance name avoidance under the module system
  src/Lean/Elab/MutualDef.lean
  stage0/src/stdlib_flags.h
Labels: changelog-no

#9863 feat: review of `grind` annotations for `Option`
  src/Init/Data/Option/Lemmas.lean
  tests/lean/run/grind_list2.lean
  tests/lean/run/grind_option.lean
Labels: changelog-library

#9822 perf: local `metaExt`
  src/Lean/Compiler/MetaAttr.lean
Labels: toolchain-available

#9786 fix: do not show progress bar for checking/compiling helper decls
  src/Lean/AddDecl.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Language/Basic.lean
  src/Lean/Language/Lean.lean
  src/Lean/Language/Util.lean
  src/Lean/Server/FileWorker.lean
Labels: toolchain-available, changelog-server

#9890 fix: do not allow access to private primitives in public scope
  src/Lean/Compiler/IR/Format.lean
  src/Lean/Compiler/LCNF/Basic.lean
  src/Lean/Data/Json/Basic.lean
  src/Lean/Data/Trie.lean
  src/Lean/Data/Xml/Basic.lean
  src/Lean/Elab/MutualInductive.lean
  src/Lean/Elab/StructInst.lean
  src/Lean/Elab/Tactic/Config.lean
  src/Lean/LoadDynlib.lean
  src/Lean/Meta/ReduceEval.lean
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/ResolveName.lean
  src/Lean/Server/Rpc/RequestHandling.lean
  src/Lean/Structure.lean
  src/Lean/Widget/TaggedText.lean
  src/Std/Internal/UV/TCP.lean
  src/Std/Internal/UV/Timer.lean
  src/Std/Internal/UV/UDP.lean
  src/Std/Sync/Channel.lean
  stage0/src/stdlib_flags.h
  tests/pkg/module/Module/Basic.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#9919 fix: div/norm normalization assumptions in `grind`
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  tests/lean/run/grind_9907.lean
Labels: toolchain-available, changelog-language

#9921 feat: missing `grind` annotations
  src/Init/Data/List/TakeDrop.lean
  tests/lean/run/grind_list_drop_take.lean
Labels: changelog-language

#9923 fix: panic in ProofMode/Delab
  src/Lean/Elab/Tactic/Do/ProofMode/Delab.lean
Labels: changelog-language

#9920 fix: panic in `delabPRange`
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/ellipsisProjIssue.lean.expected.out
  tests/lean/run/delabStdRange.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#9922 fix: erase dependencies on let-bound fvars in `internalizeCode`
  src/Lean/Compiler/LCNF/CompilerM.lean
  src/Lean/Compiler/LCNF/Internalize.lean
Labels: toolchain-available, changelog-compiler

#9928 chore: complete `riscv_ast` benchmark
  src/Lean/Meta/Constructions/BRecOn.lean
  src/Lean/Meta/Constructions/CasesOn.lean
  src/Lean/Meta/Constructions/NoConfusion.lean
  src/Lean/Meta/Injective.lean
  tests/bench/riscv-ast.lean
Labels: builds-mathlib, toolchain-available

#9938 fix: remove duplicate `mpure_intro` tactic definition
  src/Lean/Elab/Tactic/Do/ProofMode/Pure.lean
Labels: changelog-language

#9939 fix: delegate to `exact` in `mvcgen using invariants` to avoid MVar mishaps
  src/Lean/Elab/Tactic/Do/VCGen.lean
  tests/lean/run/9581.lean
Labels: changelog-language

#9945 feat: trim `grind cutsat` proof context
  src/Lean/Meta/Tactic/Grind/Arith.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/VarRename.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/VarRename.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/ProofUtil.lean
  src/Lean/Meta/Tactic/Grind/Arith/VarRename.lean
  tests/lean/run/grind_cutsat_trim_context.lean
Labels: changelog-language

#9946 feat: trim `grind ring` proof context
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/VarRename.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  tests/lean/run/grind_ring_trim_context.lean
Labels: changelog-language

#9947 feat: trim `grind linarith` proof context
  src/Lean/Meta/Tactic/Grind/Arith/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/VarRename.lean
  tests/lean/run/grind_linarith_2.lean
  tests/lean/run/grind_linarith_trim_context.lean
Labels: changelog-language

#9950 chore: fix failing `mk*Sorry` in bootstrapping contexts
  src/Lean/Elab/Term.lean
  src/Lean/Meta/Sorry.lean
  tests/lean/bootstrapSorry.lean
  tests/lean/bootstrapSorry.lean.expected.out
Labels: builds-mathlib, toolchain-available, builds-manual

#9615 chore: add fixed `grind` tests for `Nat` and `Int` ring structure
  tests/lean/run/grind_cutsat_instances.lean
Labels: toolchain-available

#9980 fix: variable reordering in `grind cutsat`
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/ReorderVars.lean
  tests/lean/run/grind_9948.lean
Labels: changelog-language

#9876 doc: documentation of p,+ macro should mention that it maps to sepBy1, not sepBy
  src/Init/Notation.lean
Labels: toolchain-available

#9797 feat: package factories for order typeclasses
  src/Init/Data/Order.lean
  src/Init/Data/Order/Classes.lean
  src/Init/Data/Order/Lemmas.lean
  src/Init/Data/Order/LemmasExtra.lean
  src/Init/Data/Order/PackageFactories.lean
  tests/lean/run/info_trees.lean
  tests/lean/run/order.lean
Labels: breaks-mathlib, toolchain-available, changelog-library

#9989 feat: change extended syntax for `mvcgen invariants ... with ...`
  src/Lean/Elab/Tactic/Do/VCGen.lean
  src/Std/Tactic/Do/Syntax.lean
  tests/lean/run/9581.lean
  tests/lean/run/mvcgenInvariantsWith.lean
Labels: changelog-language

#9999 chore: fewer Nat.bitwise grind attributes for distributivity
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  tests/lean/run/grind_nat_bitwise.lean
Labels: builds-mathlib, toolchain-available, changelog-library, builds-manual

#9916 feat: package factories for order typeclasses based on `Ord`
  src/Init/Data/Order/ClassesExtra.lean
  src/Init/Data/Order/FactoriesExtra.lean
  src/Init/Data/Order/Lemmas.lean
  src/Init/Data/Order/LemmasExtra.lean
  src/Init/Data/Order/PackageFactories.lean
  tests/lean/run/order.lean
Labels: breaks-mathlib, toolchain-available, changelog-library

#9987 feat: better get-elem tactic for ranges
  src/Init/Data/Range/Polymorphic.lean
  src/Init/Data/Range/Polymorphic/Basic.lean
  src/Init/Data/Range/Polymorphic/GetElemTactic.lean
  tests/lean/run/rangePolymorphic.lean
Labels: builds-mathlib, toolchain-available, changelog-library, builds-manual

#10007 fix: #print attributes in the right order
  src/Lean/Elab/Print.lean
Labels: changelog-language

#10008 fix: have `#eval` save the info context
  src/Lean/Elab/BuiltinEvalCommand.lean
  tests/lean/interactive/hover.lean
  tests/lean/interactive/hover.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-language, builds-manual

#10010 feat: nonlinear `/` and `%` support in `grind cutsat`
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Var.lean
  tests/lean/run/grind_linearize.lean
Labels: changelog-language

#10009 chore: miscellaneous documentation typos
  src/Init/Prelude.lean
  src/Lean/Elab/BuiltinTerm.lean
  src/Lean/Environment.lean
  src/Lean/ImportingFlag.lean
  src/Lean/Meta/InferType.lean
  src/Lean/Meta/Tactic/TryThis.lean
  src/Std/Sync/Channel.lean
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Data.lean
  src/lake/Lake/Build/Job/Monad.lean
Labels: awaiting-review, toolchain-available

#10017 perf: disable reuse when a value's last use is an owned argument
  src/Lean/Compiler/IR.lean
  src/Lean/Compiler/IR/ResetReuse.lean
Labels: toolchain-available, changelog-compiler

#10021 feat: minor quality of life improvements in script/AnalyzeGrindAnnotations
  script/AnalyzeGrindAnnotations.lean
Labels: changelog-language

#10015 feat: `@[expose]` on `Name.append` & friends
  src/Init/Prelude.lean
Labels: builds-mathlib, toolchain-available, changelog-library, builds-manual

#10018 feat: `deriving BEq, Hashable` for `Lean.Import`
  src/Lean/Setup.lean
  src/lake/Lake/Load/Lean/Elab.lean
Labels: builds-mathlib, toolchain-available, changelog-library, builds-manual

#10001 chore: simplify `require` config in lakefile.toml schema
  src/lake/schemas/lakefile-toml-schema.json
Labels: toolchain-available, changelog-no

#10016 chore: make `USE_LAKE` the default
  .github/workflows/ci.yml
  .github/workflows/update-stage0.yml
  CMakeLists.txt
  doc/dev/bootstrap.md
  doc/dev/index.md
  doc/make/index.md
  script/bench.sh
  src/CMakeLists.txt
Labels: toolchain-available

#10019 feat: `@[expose]` on `Lean.ParserState.setPos`
  src/Lean/Parser/Types.lean
Labels: builds-mathlib, toolchain-available, changelog-library, builds-manual

#10022 feat: improve `grind cutsat` support for `Fin n` when `n` is not a numeral
  src/Init/Grind/ToInt.lean
  src/Init/Grind/ToIntLemmas.lean
  src/Init/MetaTypes.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/ToInt.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/ToIntInfo.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean
  src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Nat.lean
  src/Lean/Util/SafeExponentiation.lean
  tests/lean/run/grind_cutsat_toint_1.lean
Labels: toolchain-available, changelog-language

#10033 refactor: split out an `isInductivePredicateVal` function
  src/Lean/Meta/Basic.lean
Labels: toolchain-available

#10023 fix: support `casesOn` for inductive predicates with computations on fields
  src/Lean/Compiler/LCNF/ToLCNF.lean
  tests/lean/run/casesOnAcc.lean
Labels: toolchain-available, changelog-compiler

#10038 fix: `grind` error messages
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/ToInt.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
  src/Lean/Meta/Tactic/Grind/Cases.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/ExtAttr.lean
  tests/lean/run/grind_ematch1.lean
  tests/lean/run/grind_ematch_patterns.lean
  tests/lean/run/grind_ite.lean
Labels: toolchain-available, changelog-language

#10040 fix: incorporate info from `_redArg` decls for `noncomputable` check
  src/Lean/Compiler/LCNF/ToMono.lean
  tests/lean/run/erased.lean
  tests/lean/run/noncomputableUnused.lean
Labels: toolchain-available, changelog-compiler

#10041 chore: set `experimental.module=true` when running `grind` benchmarks
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#10005 feat: more convenient creation of polymorphic range instances
  src/Init/Data.lean
  src/Init/Data/Ord.lean
  src/Init/Data/Order/Lemmas.lean
  src/Init/Data/Range/Polymorphic/Basic.lean
  src/Init/Data/Range/Polymorphic/Instances.lean
  src/Init/Data/Range/Polymorphic/Lemmas.lean
  src/Init/Data/Range/Polymorphic/Nat.lean
  src/Init/Data/Range/Polymorphic/PRange.lean
  src/Init/Data/Range/Polymorphic/RangeIterator.lean
  src/Init/Data/Range/Polymorphic/UpwardEnumerable.lean
  src/Init/Data/Slice/Array/Iterator.lean
Labels: toolchain-available, changelog-library

#10024 feat: improvements to `Min`/`Max`-related classes
  src/Init/Data/List/MinMax.lean
  src/Init/Data/Nat/Order.lean
  src/Init/Data/Order/Factories.lean
  src/Init/Data/Order/Lemmas.lean
  src/Init/Data/Order/PackageFactories.lean
  src/Std/Data/Internal/List/Associative.lean
  tests/lean/run/order.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#10042 chore: fix spelling errors
  doc/dev/bootstrap.md
  src/Init/Data/Order/PackageFactories.lean
  src/Init/Meta.lean
  src/Lean/Compiler/IR/CompilerM.lean
  src/Lean/Compiler/MetaAttr.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Induction.lean
  src/Lean/Elab/PreDefinition/Structural/Preprocess.lean
  src/Lean/Elab/PreDefinition/WF/GuessLex.lean
  src/Lean/Elab/PreDefinition/WF/Unfold.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/EmbeddedConstraint.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/Environment.lean
  src/Lean/Meta/Closure.lean
  src/Lean/Meta/LetToHave.lean
  src/Lean/Meta/NatTable.lean
  src/Lean/Meta/Tactic/FunInd.lean
  src/Lean/Parser/Extra.lean
  src/Lean/Server/CodeActions/UnknownIdentifier.lean
  src/Lean/Server/Completion/CompletionUtils.lean
  src/Std/Do/SPred/Notation.lean
  src/Std/Tactic/Do/Syntax.lean
  src/cmake/Modules/GetGitRevisionDescription.cmake
  src/lake/Lake/CLI/Translate/Lean.lean
  src/lake/Lake/CLI/Translate/Toml.lean
  src/lake/Makefile
  src/lake/examples/scripts/test.sh
  src/lake/schemas/lakefile-toml-schema.json
  src/lake/tests/toml/tests/valid/array/heterogeneous.json
  src/lake/tests/toml/tests/valid/array/heterogeneous.toml
  tests/lean/interactive/hoverBinderUnderscore.lean
  tests/lean/interactive/hoverBinderUnderscore.lean.expected.out
  tests/lean/motiveNotTypeCorrect.lean
  tests/lean/motiveNotTypeCorrect.lean.expected.out
  tests/lean/run/8815.lean
  tests/lean/run/bv_decide_rewriter_ac_nf.lean
  tests/lean/run/defaultValueParamIssue.lean
  tests/lean/run/explicitOpenDeclIssue.lean
  tests/lean/run/funind_structural.lean
  tests/lean/run/grind_nochrono.lean
  tests/lean/run/hmulDefaultInstance.lean
  tests/lean/run/issue8939.lean
  tests/lean/traceStateBacktracking.lean
  tests/lean/traceStateBacktracking.lean.expected.out
Labels: toolchain-available

#10039 chore: allow `module` in `LakeMain`
  src/Lean/Language/Lean.lean
  stage0/src/stdlib_flags.h
Labels: builds-mathlib, toolchain-available, changelog-no, builds-manual

#10046 perf: fast version of `Nat.log2`
  src/Init/Data/Nat/Lemmas.lean
  src/Init/Data/Nat/Log2.lean
Labels: builds-mathlib, toolchain-available

#10053 fix: auto params on private structure fields
  src/Lean/Elab/Structure.lean
  tests/pkg/module/Module/Basic.lean
Labels: changelog-no

#10027 perf: make macro scope numbering less dependent on surrounding context
  src/Init/Prelude.lean
  src/Lean/CoreM.lean
  src/Lean/Data/NameMap/Basic.lean
  src/Lean/Elab/Command.lean
  src/Lean/Elab/Declaration.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Quotation.lean
  src/Lean/Elab/Term.lean
  src/Lean/Elab/Util.lean
  src/Lean/Environment.lean
  src/Lean/Hygiene.lean
  src/Lean/Meta/Basic.lean
  src/Lean/MetavarContext.lean
  src/Lean/PrettyPrinter/Parenthesizer.lean
  tests/lean/1275.lean.expected.out
  tests/lean/StxQuot.lean.expected.out
  tests/lean/macroscopes.lean
  tests/lean/ppNotationCode.lean.expected.out
  tests/lean/run/methodsRetInhabited.lean
  tests/lean/shadow.lean.expected.out
  tests/pkg/rebuild/test.sh
Labels: toolchain-available

#10045 feat: introduce `Int` range notation
  src/Init/Data/Range/Polymorphic.lean
  src/Init/Data/Range/Polymorphic/Int.lean
  src/Init/Data/Range/Polymorphic/Nat.lean
  tests/lean/run/rangePolymorphic.lean
Labels: toolchain-available, changelog-library

#10080 perf: inline dependent instances into specialized decls
  src/Lean/Compiler/LCNF/Specialize.lean
Labels: toolchain-available

#10093 feat: AC theorems for `grind`
  src/Init/Grind.lean
  src/Init/Grind/AC.lean
  tests/lean/run/constructor_as_variable.lean
Labels: changelog-language

#10097 chore: protect some theorems in the Rat namespace
  src/Init/Data/Rat/Lemmas.lean
Labels: changelog-library

#10096 chore: fix error in Grind/Arith/Linear/StructId
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
Labels: toolchain-available

#10106 test: `grind cutsat`
  tests/lean/run/grind_cutsat_pow.lean
Labels: changelog-no

#10077 feat: upstream several `Rat` lemmas from mathlib
  src/Init/Data/Rat/Basic.lean
  src/Init/Data/Rat/Lemmas.lean
  src/Init/Grind/Ordered.lean
  src/Init/Grind/Ordered/Rat.lean
  src/Init/GrindInstances.lean
  src/Init/GrindInstances/Rat.lean
  src/Init/GrindInstances/Ring.lean
  src/Init/GrindInstances/Ring/Rat.lean
  tests/lean/hpow.lean
  tests/lean/run/grind_field_norm.lean
Labels: toolchain-available, changelog-library

#10047 fix: de-prioritize `PartialTermInfo` in hover info selection
  src/Lean/Server/InfoUtils.lean
  tests/lean/interactive/hoverMatch.lean
  tests/lean/interactive/hoverMatch.lean.expected.out
Labels: toolchain-available, changelog-server

#10052 fix: don't block fileworker with `lake setup-file`
  src/Lean/Server/FileWorker.lean
Labels: toolchain-available, changelog-server

#9951 feat: `.ctorIdx` for all inductives
  src/Init/Core.lean
  src/Init/Data/ByteArray/Basic.lean
  src/Init/Data/Float.lean
  src/Init/Data/Float32.lean
  src/Init/Data/FloatArray/Basic.lean
  src/Init/Data/Int/Basic.lean
  src/Init/Prelude.lean
  src/Lean/Elab/Deriving/DecEq.lean
  src/Lean/Elab/GenInjective.lean
  src/Lean/Elab/MutualInductive.lean
  src/Lean/EnvExtension.lean
  src/Lean/Meta/Constructions/CtorIdx.lean
  src/Lean/Meta/Constructions/NoConfusion.lean
  src/Lean/Meta/DiscrTree.lean
  src/Lean/Meta/Injective.lean
  src/Lean/Parser/Command.lean
  stage0/src/stdlib_flags.h
  tests/lean/3057.lean
  tests/lean/computedFieldsCode.lean.expected.out
  tests/lean/interactive/completionFallback.lean.expected.out
  tests/lean/run/1985.lean
  tests/lean/run/ctorIdx.lean
  tests/lean/run/decEq.lean
  tests/lean/run/enumNoConfusionIssue.lean
  tests/lean/run/omegaCanon.lean
Labels: builds-mathlib, toolchain-available, changelog-language, builds-manual

#10112 chore: minimize `Lean.Expr` import
  src/Lean/Expr.lean
Labels: toolchain-available

#10113 feat: deprecate `.toCtorIdx` for `.ctorIdx`
  src/Init/Data/Ord/Basic.lean
  src/Lean/Data/Lsp/LanguageFeatures.lean
  src/Lean/Elab/Binders.lean
  src/Lean/Elab/Deriving/BEq.lean
  src/Lean/Elab/Deriving/DecEq.lean
  src/Lean/Elab/Inductive.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Elab/Tactic/Lets.lean
  src/Lean/Environment.lean
  src/Lean/Linter/Deprecated.lean
  src/Lean/Linter/List.lean
  src/Lean/Meta/Constructions/CtorIdx.lean
  tests/lean/run/decEq.lean
Labels: toolchain-available, changelog-language

#10109 fix: public structures with private field types under the module system
  src/Lean/Elab/MutualInductive.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Meta/Structure.lean
  src/Lean/Parser/Basic.lean
  tests/pkg/module/Module/Basic.lean
Labels: merge-ci, changelog-no

#10115 chore: make UInt.Lemmas a private import of String.Extra
  src/Init/Data/String/Extra.lean
Labels: toolchain-available

#10120 fix: dot notation for recursive invocation of private definitions
  src/Lean/Elab/App.lean
  tests/lean/run/1910.lean
  tests/lean/run/dotNotationRecDecl.lean
  tests/lean/run/invalid_field_notation_unusable_param.lean
Labels: toolchain-available, changelog-language

#10121 chore: use `ofConstName` in error messages
  src/Lean/Attributes.lean
  src/Lean/Compiler/IR/Checker.lean
  src/Lean/Compiler/ImplementedByAttr.lean
  src/Lean/Compiler/InlineAttrs.lean
  src/Lean/Compiler/LCNF/Check.lean
  src/Lean/Compiler/LCNF/Simp/SimpM.lean
  src/Lean/Compiler/LCNF/ToDecl.lean
  src/Lean/Compiler/LCNF/ToLCNF.lean
  src/Lean/CoreM.lean
  src/Lean/DocString/Add.lean
  src/Lean/DocString/Extension.lean
  src/Lean/Elab/DeclModifiers.lean
  src/Lean/Elab/Deriving/Basic.lean
  src/Lean/Elab/Deriving/Inhabited.lean
  src/Lean/Elab/LetRec.lean
  src/Lean/Elab/PreDefinition/Eqns.lean
  src/Lean/Elab/PreDefinition/PartialFixpoint/Eqns.lean
  src/Lean/Elab/PreDefinition/Structural/Eqns.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/Enums.lean
  src/Lean/Elab/Tactic/Rewrite.lean
  src/Lean/Elab/Tactic/Simp.lean
  src/Lean/KeyedDeclsAttribute.lean
  src/Lean/Meta/Instances.lean
  src/Lean/Meta/Match/MatchPatternAttr.lean
  src/Lean/Meta/RecursorInfo.lean
  src/Lean/Meta/Structure.lean
  src/Lean/Meta/Tactic/Ext.lean
  src/Lean/Meta/Tactic/Simp/Attr.lean
  src/Lean/Meta/Tactic/Simp/Simproc.lean
  src/Lean/Meta/Tactic/Unfold.lean
  src/Lean/Parser/Extension.lean
  src/Lean/Parser/Tactic/Doc.lean
  src/Lean/ReducibilityAttrs.lean
  src/Lean/ResolveName.lean
  tests/lean/implementedByIssue.lean.expected.out
Labels: toolchain-available, changelog-no

#10124 refactor: grind build times
  src/Lean/Meta/Match/Basic.lean
  src/Lean/Meta/Match/MatchEqs.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Functions.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/GetSet.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Inv.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/MonadRing.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/PP.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/RingId.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/RingM.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/SafePoly.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/SemiringM.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Var.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/CommRing.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/MBTC.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/DenoteExpr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/MBTC.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Util.lean
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Grind/EMatchTheorem.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/MBTC.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: changelog-no

#10127 refactor: `grind` build times
  src/Lean/Meta/Tactic/Grind/AC/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith.lean
  src/Lean/Meta/Tactic/Grind/Arith/Internalize.lean
  src/Lean/Meta/Tactic/Grind/EMatch.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: changelog-no

#10128 chore: simplify `grind` import graph
  src/Lean/Meta/Offset.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Arith/EvalNum.lean
  src/Lean/Meta/Tactic/Grind/Canon.lean
  src/Lean/Meta/Tactic/Simp/Arith/Nat/Basic.lean
  src/Lean/Meta/Tactic/Simp/Arith/Nat/Simp.lean
Labels: changelog-no

#10130 chore: create `.toCtorIdx` alias only for enumeration types
  src/Lean/Meta/Constructions/CtorIdx.lean
  tests/lean/computedFieldsCode.lean.expected.out
  tests/lean/run/ctorIdx.lean
Labels: toolchain-available

#10134 fix: FunInd: handle let-vars-in-match-better
  src/Lean/Elab/Tactic/Do/VCGen/Split.lean
  src/Lean/Meta/Tactic/FunInd.lean
  stage0/src/stdlib_flags.h
  tests/lean/run/issue10132.lean
Labels: changelog-language

#10095 chore: use SMul rather than HMul in grind algebra typeclasses
  src/Init/Data/Dyadic/Instances.lean
  src/Init/Data/Vector/Algebra.lean
  src/Init/Grind/Module/Basic.lean
  src/Init/Grind/Module/Envelope.lean
  src/Init/Grind/Norm.lean
  src/Init/Grind/Ordered/Linarith.lean
  src/Init/Grind/Ordered/Module.lean
  src/Init/Grind/Ring/Basic.lean
  src/Init/Grind/Ring/Poly.lean
  src/Init/Grind/Tactics.lean
  src/Init/GrindInstances/Ring/Fin.lean
  src/Init/GrindInstances/Ring/Rat.lean
  src/Init/GrindInstances/Ring/SInt.lean
  src/Init/GrindInstances/Ring/UInt.lean
  src/Lean/Meta/Tactic/Grind/Arith/CommRing/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/Reify.lean
  src/Lean/Meta/Tactic/Grind/Arith/Linear/StructId.lean
  src/Lean/Meta/Tactic/Grind/Arith/ModelUtil.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  tests/lean/run/grind_linarith_1.lean
  tests/lean/run/grind_module_eqs.lean
  tests/lean/run/grind_module_normalization.lean
  tests/lean/run/grind_module_relations.lean
  tests/lean/run/grind_ord_module.lean
  tests/lean/run/grind_preord_module.lean
Labels: toolchain-available, changelog-language
