Repository leanprover/lean4, pull requests merged in 2025-04, with the labels that each got.

#7763 fix: lake: target kinds & keys
  src/lake/Lake/Build/Data.lean
  src/lake/Lake/Build/Job/Monad.lean
  src/lake/Lake/Build/Key.lean
  src/lake/Lake/Build/Target/Fetch.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/Config/FacetConfig.lean
  src/lake/Lake/DSL/Key.lean
  src/lake/tests/api/keys.lean
  src/lake/tests/api/test.sh
  src/lake/tests/kinds/.gitignore
  src/lake/tests/kinds/clean.sh
  src/lake/tests/kinds/lakefile.lean
  src/lake/tests/kinds/test.sh
Labels: builds-mathlib, toolchain-available, changelog-lake

#7765 feat: dependent implication introduction in `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
Labels: toolchain-available, changelog-language

#7764 fix: use more reduction when computing parent types
  src/Lean/Elab/StructInst.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#7758 chore: lake: rm excess `-lstdcpp` from FFI example
  src/lake/examples/ffi/lib/lakefile.lean
Labels: builds-mathlib, toolchain-available, release-ci, changelog-lake

#7766 chore: fix statement of List/Array/Vector.all_filter
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
Labels: toolchain-available

#7767 chore: failing test cases for grind proving List lemmas
  tests/lean/grind/list_problems.lean
Labels: toolchain-available

#7768 chore: add List.head_singleton theorem
  src/Init/Data/List/Lemmas.lean
Labels: toolchain-available

#7747 chore: add script to generate release steps
  doc/dev/release_checklist.md
  script/release_steps.py
Labels: toolchain-available

#7755 feat: add `Std.RecursiveMutex`
  src/Std/Sync.lean
  src/Std/Sync/Basic.lean
  src/Std/Sync/Mutex.lean
  src/Std/Sync/RecursiveMutex.lean
  src/runtime/mutex.cpp
  tests/lean/run/sync_recursive_mutex.lean
Labels: toolchain-available, changelog-library

#7757 feat: BitVec.append_add_append_eq_append
  src/Init/Data/BitVec/Bitblast.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7769 feat: upgrades to release automation
  script/merge_remote.py
  script/release_checklist.py
  script/release_repos.yml
  script/release_steps.py
Labels: toolchain-available, changelog-other

#7772 fix: sanitize build and mimalloc
  CMakeLists.txt
  CMakePresets.json
Labels: toolchain-available, changelog-no

#7773 doc: `AsyncMode.mainOnly` is the default
  src/Lean/Environment.lean
Labels: toolchain-available

#7316 fix: make new codegen async realization-compatible
  src/Lean/Compiler/LCNF/AuxDeclCache.lean
  src/Lean/Compiler/LCNF/BaseTypes.lean
  src/Lean/Compiler/LCNF/CompilerM.lean
  src/Lean/Compiler/LCNF/ElimDeadBranches.lean
  src/Lean/Compiler/LCNF/MonoTypes.lean
  src/Lean/Compiler/LCNF/Passes.lean
  src/Lean/Compiler/LCNF/PhaseExt.lean
  src/Lean/Compiler/LCNF/Simp/ConstantFold.lean
  src/Lean/Compiler/LCNF/SpecInfo.lean
  src/Lean/Compiler/LCNF/Specialize.lean
Labels: toolchain-available, changelog-no

#7756 feat: `Nat.gcd` lemmas
  src/Init/Data/Nat/Basic.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Dvd.lean
  src/Init/Data/Nat/Gcd.lean
  src/Init/Data/Nat/Lemmas.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7775 feat: `NatCast.natCast` unexpander
  src/Init/Grind/Util.lean
  tests/lean/run/grind_canon_insts.lean
  tests/lean/run/grind_eq.lean
  tests/lean/run/grind_offset.lean
Labels: toolchain-available, changelog-no

#7776 feat: improve `grind` equality proof discharger
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/ProveEq.lean
  tests/lean/grind/list_problems.lean
  tests/lean/run/grind_proveEqIssue.lean
Labels: toolchain-available, changelog-language

#7777 fix: prop local instances in `grind`
  src/Lean/Meta/Tactic/Grind/Intro.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#7085 chore: derive more type classes for IR data structures
  src/Lean/Compiler/IR/Basic.lean
  src/Lean/Compiler/IR/CtorLayout.lean
Labels: toolchain-available

#7778 fix: missing propagation rules for non decidable lawful `BEq` in `grind`
  src/Init/Grind/Lemmas.lean
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  tests/lean/grind/list_problems.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#7781 fix: `Bool` disequality propagation in `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/Propagate.lean
  tests/lean/grind/list_problems.lean
  tests/lean/run/grind_bool_diseq.lean
  tests/lean/run/grind_list_issue.lean
Labels: toolchain-available, changelog-language

#7783 feat: helper theorems
  src/Init/Data/Int/Linear.lean
Labels: toolchain-available, changelog-no

#7782 chore: normalize URLs to the language reference in test results
  tests/common.sh
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/interactive/hoverDot.lean.expected.out
Labels: toolchain-available

#6325 feat: `importModules` without loading environment extensions
  releases_drafts/environment.md
  src/Lean/Elab/Import.lean
  src/Lean/Environment.lean
  src/lake/Lake/Load/Lean/Elab.lean
  tests/lean/ctor_layout.lean
  tests/lean/run/instances.lean
  tests/lean/run/instuniv.lean
  tests/lean/run/meta1.lean
  tests/lean/run/meta3.lean
  tests/pkg/user_attr_app/Main.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7665 feat: 'unknown identifier' code actions
  src/Lean/Data/Lsp/Diagnostics.lean
  src/Lean/Data/Lsp/Internal.lean
  src/Lean/Elab/App.lean
  src/Lean/Elab/Term.lean
  src/Lean/Exception.lean
  src/Lean/Server/AsyncList.lean
  src/Lean/Server/CodeActions/Basic.lean
  src/Lean/Server/CodeActions/UnknownIdentifier.lean
  src/Lean/Server/Completion/CompletionCollectors.lean
  src/Lean/Server/Completion/CompletionUtils.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/InlayHints.lean
  src/Lean/Server/FileWorker/SemanticHighlighting.lean
  src/Lean/Server/References.lean
  src/Lean/Server/RequestCancellation.lean
  src/Lean/Server/Requests.lean
  src/Lean/Server/Watchdog.lean
  src/Lean/Widget/InteractiveDiagnostic.lean
Labels: builds-mathlib, toolchain-available, changelog-server

#7761 feat: BitVec.add_shiftLeft_eq_or_shiftLeft
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#7784 test: re-elaboration benchmarks
  script/benchReelabRss.lean
  src/Init/System/IO.lean
  src/runtime/process.cpp
  src/util/shell.cpp
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#7643 chore: CI: improve ccache
  .github/workflows/build-template.yml
Labels: toolchain-available

#7793 fix: filter empty arguments from FFI flags
  src/Lean/Compiler/FFI.lean
Labels: toolchain-available, changelog-no

#7794 refactor: split Lean.EnvironmentExtension from Lean.Environment
  src/Lean.lean
  src/Lean/AuxRecursor.lean
  src/Lean/Compiler/NoncomputableAttr.lean
  src/Lean/EnvExtension.lean
  src/Lean/Environment.lean
  src/Lean/Modifiers.lean
  src/Lean/Namespace.lean
  src/Lean/ProjFns.lean
Labels: toolchain-available

#7785 feat: further release checklist automation
  script/merge_remote.py
  script/release_checklist.py
  script/release_repos.yml
  script/release_steps.py
Labels: toolchain-available, changelog-other

#7796 fix: lake: Lean shared lib path before the workspace's
  src/lake/Lake/Config/Workspace.lean
Labels: needs-update-stage0, builds-mathlib, toolchain-available, changelog-lake

#7798 chore: begin development cycle for v4.20.0
  doc/dev/release_checklist.md
  src/CMakeLists.txt
Labels: toolchain-available

#7770 feat: add `Std.SharedMutex`
  src/Std/Sync.lean
  src/Std/Sync/RecursiveMutex.lean
  src/Std/Sync/SharedMutex.lean
  src/runtime/mutex.cpp
  src/runtime/thread.h
  tests/lean/run/sync_shared_mutex.lean
Labels: toolchain-available, changelog-library

#7791 feat: `Nat.lcm` lemmas
  src/Init/Data/Nat/Gcd.lean
  src/Init/Data/Nat/Lcm.lean
  src/Init/Data/Nat/Lemmas.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7797 feat: `grind` internal `CommRing` class
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/SInt/Lemmas.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Init/Data/Zero.lean
  src/Init/Grind.lean
  src/Init/Grind/CommRing.lean
  src/Init/Grind/CommRing/Basic.lean
  src/Init/Grind/CommRing/BitVec.lean
  src/Init/Grind/CommRing/Int.lean
  src/Init/Grind/CommRing/SInt.lean
  src/Init/Grind/CommRing/UInt.lean
  src/Init/Prelude.lean
  tests/lean/1018unknowMVarIssue.lean.expected.out
  tests/lean/1870.lean
  tests/lean/1870.lean.expected.out
  tests/lean/948.lean
  tests/lean/diamond7.lean
  tests/lean/diamond8.lean
  tests/lean/infoFromFailure.lean
  tests/lean/infoFromFailure.lean.expected.out
  tests/lean/interactive/completionPrefixIssue.lean.expected.out
  tests/lean/run/1711.lean
  tests/lean/run/1870.lean
  tests/lean/run/1907.lean
  tests/lean/run/1907orig.lean
  tests/lean/run/1951.lean
  tests/lean/run/2461.lean
  tests/lean/run/2736.lean
  tests/lean/run/3150.lean
  tests/lean/run/3807.lean
  tests/lean/run/KyleAlg.lean
  tests/lean/run/KyleAlgAbbrev.lean
  tests/lean/run/alg.lean
  tests/lean/run/binop_binrel_perf_issue.lean
  tests/lean/run/grind_canon_insts.lean
  tests/lean/run/grind_regression.lean
  tests/lean/run/grind_shelf.lean
  tests/lean/run/infoFromFailure.lean
  tests/lean/run/linearCategory_perf_issue.lean
  tests/lean/run/mathlibetaissue.lean
  tests/lean/run/matrix.lean
  tests/lean/run/ofNatNormNum.lean
  tests/lean/run/proofAsSorry.lean
  tests/lean/run/regressions3210.lean
  tests/lean/run/structWithAlgTCSynth.lean
  tests/lean/run/unfoldPartialRegression.lean
  tests/lean/synthorder.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7659 feat: add `BitVec.umulOverflow` and `BitVec.smulOverflow` definitions and additional theorems
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Int/LemmasAux.lean
  src/Init/Data/Int/Pow.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  tests/lean/run/bv_decide_rewriter.lean
Labels: awaiting-review, toolchain-available, changelog-library

#7801 chore: more failing test cases for grind
  src/Init/Data/List/Lemmas.lean
  src/Init/GetElem.lean
  tests/lean/grind/list_problems.lean
  tests/lean/run/grind_ematch1.lean
  tests/lean/run/grind_ematch2.lean
Labels: toolchain-available

#7800 chore: avoid mimalloc warnings
  src/runtime/CMakeLists.txt
Labels: toolchain-available

#7803 feat: function composition normalization rules in `grind`
  src/Init/Grind/Norm.lean
  tests/lean/grind/list_problems.lean
  tests/lean/run/grind_list_issue.lean
Labels: toolchain-available, changelog-language

#7805 feat: have raw nat lits pretty print with `nat_lit` when `pp.explicit` is set
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  tests/lean/236.lean.expected.out
  tests/lean/delabOverApp.lean.expected.out
  tests/lean/eagerCoeExpansion.lean.expected.out
  tests/lean/ppNumericTypes.lean
  tests/lean/ppNumericTypes.lean.expected.out
  tests/lean/run/2220.lean
  tests/lean/run/2611.lean
  tests/lean/run/7353.lean
  tests/lean/run/coeIssues4.lean
  tests/lean/run/delabProjectionApp.lean
  tests/lean/run/delabStructInst.lean
  tests/lean/run/grind_canon_insts.lean
  tests/lean/run/ppNumericTypes.lean
  tests/lean/rwWithSynthesizeBug.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-pp

#7808 fix: missing forall normalization rules in `grind`
  src/Init/Grind/Norm.lean
  tests/lean/grind/list_problems.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#7810 chore: update .gitignore for release checklist scripts
  .gitignore
Labels: toolchain-available

#7806 feat: let conv tactics `ext`/`intro`/`enter` take `_`
  src/Init/Conv.lean
  src/Lean/Elab/Tactic/Conv/Congr.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7807 doc: fix typo in error message
  src/Lean/Elab/Term.lean
Labels: builds-mathlib, toolchain-available

#7812 feat: pretty print props with `→` only if domain is prop, add `pp.foralls`
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
  src/Lean/PrettyPrinter/Delaborator/Options.lean
  tests/lean/1682.lean.expected.out
  tests/lean/2115.lean.expected.out
  tests/lean/815b.lean.expected.out
  tests/lean/PPRoundtrip.lean.expected.out
  tests/lean/funParen.lean.expected.out
  tests/lean/interactive/Diff.lean.expected.out
  tests/lean/interactive/incrementalTactic.lean.expected.out
  tests/lean/interactive/plainGoal.lean.expected.out
  tests/lean/lcnfTypes.lean.expected.out
  tests/lean/match1.lean.expected.out
  tests/lean/precissues.lean.expected.out
  tests/lean/run/1156.lean
  tests/lean/run/1834.lean
  tests/lean/run/4365.lean
  tests/lean/run/funind_tests.lean
  tests/lean/run/genindices.lean
  tests/lean/run/print_cmd.lean
  tests/lean/sanitychecks.lean.expected.out
  tests/lean/synthorder.lean.expected.out
Labels: builds-mathlib, toolchain-available, changelog-pp

#7815 test: add test for mixed autoParam/optParam for structure field defaults
  tests/lean/run/structInst.lean
Labels: toolchain-available, changelog-no

#7817 chore: updates to release_checklist.md
  .github/workflows/ci.yml
  RELEASES.md
  doc/dev/release_checklist.md
  releases/v4.0.0-m4.md
  releases/v4.0.0-m5.md
  releases/v4.0.0.md
  releases/v4.1.0.md
  releases/v4.10.0.md
  releases/v4.11.0.md
  releases/v4.12.0.md
  releases/v4.13.0.md
  releases/v4.14.0.md
  releases/v4.15.0.md
  releases/v4.16.0.md
  releases/v4.17.0.md
  releases/v4.2.0.md
  releases/v4.3.0.md
  releases/v4.4.0.md
  releases/v4.5.0.md
  releases/v4.6.0.md
  releases/v4.6.1.md
  releases/v4.7.0.md
  releases/v4.8.0.md
  releases/v4.9.0.md
  releases_drafts/README.md
  script/release_repos.yml
  script/release_steps.py
Labels: toolchain-available

#7499 chore: fix naming of several theorems
  src/Init/Control/Basic.lean
  src/Init/Core.lean
  src/Init/Data/Array/Lemmas.lean
  src/Init/Data/BitVec/Bitblast.lean
  src/Init/Data/BitVec/Lemmas.lean
  src/Init/Data/Bool.lean
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Bitwise/Lemmas.lean
  src/Init/Data/Nat/Power2.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Data/SInt/Bitwise.lean
  src/Init/Data/SInt/Lemmas.lean
  src/Init/Data/UInt/Bitwise.lean
  src/Init/Data/UInt/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Init/Util.lean
  src/Init/WF.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DTreeMap/Internal/WF/Lemmas.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Expr.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/GetLsbD.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Mul.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftLeft.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/ShiftRight.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Operations/Sub.lean
  src/Std/Tactic/BVDecide/Bitblast/BVExpr/Circuit/Lemmas/Pred.lean
  src/Std/Tactic/BVDecide/Normalize/BitVec.lean
  src/Std/Tactic/BVDecide/Normalize/Equal.lean
Labels: awaiting-review, builds-mathlib, toolchain-available

#7802 feat: `Int.gcd`/`Int.lcm` lemmas
  src/Init/Data/Int/Cooper.lean
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Int/Gcd.lean
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/Order.lean
  src/Init/Data/Int/Pow.lean
  src/Init/Data/Nat/Gcd.lean
  src/Init/Data/Nat/Lcm.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7818 chore: deprecate `Option.merge` and `Option.liftOrGet` in favor of `Option.zipWith`
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Omega/Constraint.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/AC.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7816 fix: have nested field notation use consistent rules
  src/Lean/Elab/App.lean
  tests/lean/run/6400.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7795 perf: `Task.bind` short circuit
  src/runtime/object.cpp
Labels: builds-mathlib, toolchain-available, release-ci

#7825 feat: improve cutsat `Nat` support
  src/Init/Data/Int/OfNat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Foreign.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/LeCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Norm.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Var.lean
  tests/lean/run/grind_canon_insts.lean
  tests/lean/run/grind_eq.lean
  tests/lean/run/grind_offset.lean
Labels: toolchain-available, changelog-language

#7822 feat: lake: use absolute paths
  src/lake/Lake/CLI/Error.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Load/Config.lean
  src/lake/Lake/Load/Lean.lean
  src/lake/Lake/Load/Package.lean
  src/lake/Lake/Load/Resolve.lean
  src/lake/Lake/Load/Toml.lean
  src/lake/Lake/Util/FilePath.lean
  src/lake/Lake/Util/IO.lean
  src/lake/examples/deps/bar/lake-manifest.expected.json
  src/lake/examples/deps/test.sh
  src/lake/tests/env/test.sh
  src/lake/tests/manifest/lake-manifest-latest.json
  src/lake/tests/manifest/test.sh
  src/lake/tests/order/test.sh
  tests/pkg/test_extern/expected.txt
  tests/pkg/test_extern/test.sh
Labels: builds-mathlib, toolchain-available, release-ci, changelog-lake

#7828 fix: redundant `markAsCutsatTerm`
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Foreign.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Var.lean
  tests/lean/run/grind_cutsat_nat_le.lean
Labels: toolchain-available, changelog-no

#7829 fix: cutsat counterexamples
  src/Init/Data/Int/Linear.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  tests/lean/run/grind_cutsat_diseq_2.lean
  tests/lean/run/grind_cutsat_eq_1.lean
  tests/lean/run/grind_mbtc_1.lean
Labels: toolchain-available, changelog-language

#7831 feat: extensible `evalAndSuggest` for `try?`
  src/Lean/Elab/Tactic/Try.lean
  tests/lean/run/grind_try_extend.lean
Labels: toolchain-available, changelog-language

#7834 fix: `shareCommon` issues in `grind`
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Foreign.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/LeCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Norm.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Var.lean
  src/Lean/Meta/Tactic/Grind/Simp.lean
Labels: toolchain-available, changelog-no

#7824 fix: perform an earlier 'noncomputable' check to avoid misoptimizations
  src/Lean/Compiler/NoncomputableAttr.lean
  src/library/compiler/CMakeLists.txt
  src/library/compiler/erase_irrelevant.cpp
  src/library/compiler/noncomputable_attribute.cpp
  src/library/compiler/noncomputable_attribute.h
  tests/lean/noncompSection.lean.expected.out
  tests/lean/run/1785.lean
  tests/lean/run/noncomputable_decide.lean
Labels: toolchain-available, changelog-compiler

#7836 chore: introduce reldebug preset, replace debug CI job with it
  .github/workflows/ci.yml
  CMakePresets.json
Labels: toolchain-available

#7838 feat: support `mpz` in the `shareCommon` APIs
  src/runtime/sharecommon.cpp
  tests/lean/run/sharecommon_mpz.lean
Labels: toolchain-available, changelog-compiler

#7611 chore: generalize some type classes
  src/Init/Control/Basic.lean
  src/Init/Control/Lawful/Basic.lean
  src/Init/Control/Lawful/Instances.lean
  src/Init/Data/List/Find.lean
  src/Init/GetElem.lean
  src/Lean/Elab/SetOption.lean
  src/Std/Classes/Ord.lean
  src/Std/Data/Internal/List/Associative.lean
  src/Std/Sync/Mutex.lean
Labels: builds-mathlib, toolchain-available, P-medium

#7474 feat: validate, expose names, and add hovers for all suggestion tactics
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/LibrarySearch.lean
  src/Lean/Elab/Tactic/Rewrites.lean
  src/Lean/Elab/Tactic/ShowTerm.lean
  src/Lean/Meta/Tactic/Rewrites.lean
  src/Lean/Meta/Tactic/TryThis.lean
  tests/lean/run/3922.lean
  tests/lean/run/5407.lean
  tests/lean/run/5993.lean
  tests/lean/run/rewrites.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7230 chore: omega calls assumption first
  src/Lean/Elab/Tactic/Omega/Frontend.lean
Labels: builds-mathlib, toolchain-available

#7108 feat: two new lemmas on `List.head` / `List.getLast`
  src/Init/Data/List/Lemmas.lean
Labels: builds-mathlib, toolchain-available, P-medium, changelog-library

#7845 chore: add failing grind tests about decide
  tests/lean/grind/decide.lean
Labels: toolchain-available

#7840 feat: tag structure instances when `pp.tagAppFn` is set
  src/Lean/PrettyPrinter/Delaborator/Builtins.lean
Labels: builds-mathlib, toolchain-available, changelog-pp

#7846 chore: deprecate Option.mem_iff
  src/Init/Data/Option/Lemmas.lean
Labels: toolchain-available

#7847 chore: remove @[simp] from @[deprecated] theorems
  src/Init/Data/List/Basic.lean
  src/Init/Data/List/Lemmas.lean
  src/Std/Data/DHashMap/Lemmas.lean
  src/Std/Data/DHashMap/RawLemmas.lean
  src/Std/Data/HashMap/Lemmas.lean
  src/Std/Data/HashMap/RawLemmas.lean
Labels: toolchain-available, changelog-library

#7848 chore: another failing `grind` test
  tests/lean/grind/list_problems.lean
Labels: toolchain-available

#7850 chore: a failing `grind` test about `Bool` equality
  tests/lean/grind/bool.lean
Labels: toolchain-available

#7852 fix: avoid blocking wait in `sync` task
  src/Lean/Environment.lean
Labels: toolchain-available, changelog-no, backport releases/v4.19.0

#7861 fix: `grind` ematch theorem activation issue
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  tests/lean/run/grind_ematch_theorem_activation.lean
  tests/lean/run/grind_erase_attr.lean
  tests/lean/run/grind_pattern2.lean
  tests/lean/run/grind_usr.lean
Labels: toolchain-available, changelog-language

#7862 feat: improve `Bool` normalization in `grind`
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/SimpUtil.lean
  tests/lean/grind/bool.lean
  tests/lean/grind/decide.lean
  tests/lean/run/grind_decide_bool_issues.lean
Labels: toolchain-available, changelog-language

#7859 feat: allow empty clause anywhere in LRAT proof
  src/Lean/Elab/Tactic/BVDecide/LRAT/Trim.lean
Labels: toolchain-available, changelog-language

#7864 feat: case split on implications in `grind`
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  tests/lean/grind/list_problems.lean
  tests/lean/grind/model_conjectures.lean
  tests/lean/run/grind_split_arith_imp.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available, changelog-language

#7865 fix: missing propagation rule for implication in `grind`
  src/Init/Grind/Lemmas.lean
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  tests/lean/run/grind_ctor_ematch.lean
  tests/lean/run/grind_implies.lean
  tests/lean/run/grind_split_arith_imp.lean
Labels: toolchain-available, changelog-language

#7866 chore: remove not very useful `reportIssue`
  src/Lean/Meta/Tactic/Grind/Main.lean
  tests/lean/run/grind_pre.lean
  tests/lean/run/grind_split_issue.lean
Labels: toolchain-available, changelog-no

#7860 chore: lake: builtins for DSL & plugin for server
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/DSL.lean
  src/lake/Lake/DSL/Attributes.lean
  src/lake/Lake/DSL/AttributesCore.lean
  src/lake/Lake/DSL/Config.lean
  src/lake/Lake/DSL/Extensions.lean
  src/lake/Lake/DSL/Meta.lean
  src/lake/Lake/DSL/Package.lean
  src/lake/Lake/DSL/Require.lean
  src/lake/Lake/DSL/Script.lean
  src/lake/Lake/DSL/Targets.lean
  src/lake/Lake/DSL/VerLit.lean
  src/lake/Lake/Load/Lean/Elab.lean
  src/lake/Lake/Util/Version.lean
  src/lake/tests/setupFile/test.sh
Labels: needs-update-stage0, builds-mathlib, toolchain-available, changelog-lake

#7863 perf: use `Array.emptyWithCapacity` in `toArray` for `HashMap` and `TreeMap`
  src/Std/Data/DHashMap/Raw.lean
  src/Std/Data/DTreeMap/Internal/Queries.lean
Labels: builds-mathlib, toolchain-available

#7856 chore: remove membership instance on `Option` from most theorem statements
  src/Init/Data/Array/Find.lean
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/List/Nat/TakeDrop.lean
  src/Init/Data/List/Pairwise.lean
  src/Init/Data/Option/Attach.lean
  src/Init/Data/Option/Instances.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Data/Option/List.lean
  src/Std/Data/DTreeMap/Internal/WF/Lemmas.lean
  src/Std/Data/Internal/List/Associative.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7851 chore: drop `Option.zipWith`, use `Option.merge` instead
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Omega/Constraint.lean
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/AC.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7871 chore: cleanup of monadic `Option` functions
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Monadic.lean
  src/Init/Internal/Order/Lemmas.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7853 chore: panic on blocking waits in `sync` tasks
  src/Init/Core.lean
  src/runtime/object.cpp
Labels: toolchain-available

#7610 feat: make TryThis work in widget messages
  src/Lean/Message.lean
  src/Lean/Meta/Tactic/TryThis.lean
  src/Lean/Widget/Types.lean
  src/Lean/Widget/UserWidget.lean
Labels: awaiting-author, toolchain-available, changelog-server

#7876 feat: improve cutsat `Nat` support
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Var.lean
  tests/lean/run/grind_canon_insts.lean
  tests/lean/run/grind_offset.lean
Labels: toolchain-available, changelog-no

#7877 chore: avoid unnecessary quotations in cutsat traces and counterexamples
  src/Lean/Message.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Model.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Util.lean
  src/Lean/Meta/Tactic/Grind/Arith/Offset/Model.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  src/Lean/Meta/Tactic/Grind/PP.lean
  tests/lean/run/grind_cutsat_div_1.lean
  tests/lean/run/grind_cutsat_eq_1.lean
  tests/lean/run/grind_cutsat_nat_le.lean
  tests/lean/run/grind_mbtc_1.lean
Labels: toolchain-available, changelog-no

#7879 chore: add Int.toNat_emod
  src/Init/Data/Int/DivMod/Lemmas.lean
Labels: toolchain-available, changelog-library

#7881 chore: remove stray test output file
  tests/lean/ll_infer_type_bug.lean.expected.out
Labels: toolchain-available

#7873 fix: search path related bugs
  nix/buildLeanPackage.nix
  src/Lean/Data/Lsp/Extra.lean
  src/Lean/Data/Lsp/Ipc.lean
  src/Lean/Elab/Import.lean
  src/Lean/Server/Completion/ImportCompletion.lean
  src/Lean/Server/FileWorker.lean
  src/Lean/Server/FileWorker/InlayHints.lean
  src/Lean/Server/FileWorker/RequestHandling.lean
  src/Lean/Server/FileWorker/SetupFile.lean
  src/Lean/Server/FileWorker/WidgetRequests.lean
  src/Lean/Server/GoTo.lean
  src/Lean/Server/References.lean
  src/Lean/Server/Requests.lean
  src/Lean/Server/Test/Runner.lean
  src/Lean/Server/Utils.lean
  src/Lean/Server/Watchdog.lean
  src/Lean/Util/Path.lean
  src/Lean/Util/Paths.lean
  tests/lean/interactive/completionPrivateTypes.lean.expected.out
  tests/lean/interactive/completionPrv.lean.expected.out
  tests/lean/interactive/goTo.lean
  tests/lean/interactive/goTo.lean.expected.out
  tests/lean/interactive/goTo2.lean
  tests/lean/interactive/goTo2.lean.expected.out
  tests/lean/interactive/hover.lean
  tests/lean/interactive/hover.lean.expected.out
  tests/lean/interactive/jumpMutual.lean
  tests/lean/interactive/jumpMutual.lean.expected.out
Labels: toolchain-available, merge-ci, changelog-server

#7885 fix: `Nat` counterexamples in `grind`
  src/Init/Data/Int/Linear.lean
  src/Init/Data/Int/OfNat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Types.lean
  tests/lean/run/grind_cutsat_nat_eq.lean
Labels: toolchain-available, changelog-language

#7886 feat: `UIntX.pow` and `Pow UIntX Nat` instances
  src/Init/Data/SInt/Basic.lean
  src/Init/Data/SInt/Lemmas.lean
  src/Init/Data/UInt/Basic.lean
  src/Init/Data/UInt/Lemmas.lean
Labels: toolchain-available, changelog-library

#7888 chore: `Fin.ofNat'_mul`, analogous to existing add lemmas
  src/Init/Data/Fin/Lemmas.lean
Labels: toolchain-available, changelog-library

#7889 chore: variant of Int.toNat_sub
  src/Init/Data/Int/Order.lean
Labels: toolchain-available, changelog-library

#7890 chore: add Int.dvd_iff_bmod_eq_zero
  src/Init/Data/Int/DivMod/Lemmas.lean
Labels: toolchain-available, changelog-library

#7892 feat: improve `funext` support in `grind`
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Ext.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/grind/clear_aux_decls.lean
  tests/lean/run/grind_bintree.lean
  tests/lean/run/grind_funext.lean
Labels: toolchain-available, changelog-language

#7891 chore: add simp lemma `Int.cast x = x` for `x : Int`
  src/Init/Data/Int/Basic.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7893 feat: `BitVec.pow` and `Pow (BitVec w) Nat`
  src/Init/Data/BitVec/Basic.lean
  src/Init/Data/BitVec/Lemmas.lean
Labels: toolchain-available, changelog-library

#7870 feat: Lean.Grind.IsCharP
  src/Init/Grind/CommRing/Basic.lean
  src/Init/Grind/CommRing/BitVec.lean
  src/Init/Grind/CommRing/Int.lean
  src/Init/Grind/CommRing/SInt.lean
  src/Init/Grind/CommRing/UInt.lean
  tests/lean/1018unknowMVarIssue.lean.expected.out
  tests/lean/interactive/completionPrefixIssue.lean.expected.out
  tests/lean/run/info_trees.lean
Labels: breaks-mathlib, toolchain-available, changelog-language

#7882 fix: cancellation of synchronous part of previous elaboration
  src/Lean/Elab/Command.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Elab/Tactic/Basic.lean
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  src/Lean/Elab/Tactic/Induction.lean
  src/Lean/Language/Basic.lean
  src/Lean/Language/Lean.lean
  src/Lean/Meta/Basic.lean
  src/Lean/Server/Test/Cancel.lean
  tests/lean/interactive/cancellation.lean
  tests/lean/interactive/cancellation.lean.expected.out
Labels: toolchain-available, changelog-server, backport releases/v4.19.0

#7899 chore: move `bmod` results from `LemmasAux.lean` to `DivMod/Lemmas.lean`
  src/Init/Data/Int/DivMod/Lemmas.lean
  src/Init/Data/Int/Lemmas.lean
  src/Init/Data/Int/LemmasAux.lean
  src/Init/Data/Int/Order.lean
Labels: toolchain-available, changelog-library

#7902 feat: introduce `Elab.inServer` option
  src/Lean/CoreM.lean
  src/Lean/Elab/MutualDef.lean
  src/Lean/Server/FileWorker.lean
Labels: toolchain-available, changelog-language

#7897 chore: `Option` cleanup
  src/Init/Data/List/Attach.lean
  src/Init/Data/List/Find.lean
  src/Init/Data/List/MapIdx.lean
  src/Init/Data/Option/Attach.lean
  src/Init/Data/Option/Basic.lean
  src/Init/Data/Option/Instances.lean
  src/Init/Data/Option/Lemmas.lean
  src/Init/Data/Vector/Lemmas.lean
  src/Std/Data/DHashMap/Internal/AssocList/Lemmas.lean
  src/Std/Data/DHashMap/Internal/Model.lean
  src/Std/Data/DHashMap/Internal/WF.lean
  src/Std/Data/DTreeMap/Internal/WF/Lemmas.lean
  src/Std/Data/Internal/List/Associative.lean
  tests/lean/run/grind_list.lean
  tests/lean/run/grind_t1.lean
  tests/lean/run/grind_trace.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7813 fix: `sorry` in Infoview shouldn't show module name
  src/Lean/Server/FileWorker/WidgetRequests.lean
  src/Lean/Widget/InteractiveCode.lean
  tests/lean/run/sorry.lean
Labels: builds-mathlib, toolchain-available, changelog-pp

#7907 fix: `mbtc` and cast issue in `grind`
  src/Init/Grind/Norm.lean
  src/Lean/Meta/Tactic/Grind/Arith/Util.lean
  src/Lean/Meta/Tactic/Grind/MBTC.lean
  tests/lean/run/grind_cutsat_natCast_propagation.lean
Labels: toolchain-available, changelog-language

#7905 fix: eliminate panic when `inductive` has autoparam parameter with underdetermined type
  src/Lean/Elab/MutualInductive.lean
  src/Lean/Elab/Structure.lean
  src/Lean/Elab/Term.lean
  tests/lean/run/7788.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7908 chore: cleanup `grind` cutsat trace messages
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/DvdCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/EqCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Foreign.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/LeCnstr.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Nat.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Proof.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Search.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/SearchM.lean
  src/Lean/Meta/Tactic/Grind/Arith/Cutsat/Var.lean
  tests/lean/run/grind_cutsat_diseq_1.lean
  tests/lean/run/grind_cutsat_diseq_2.lean
  tests/lean/run/grind_cutsat_div_1.lean
  tests/lean/run/grind_cutsat_eq_1.lean
  tests/lean/run/grind_cutsat_le_1.lean
  tests/lean/run/grind_cutsat_nat_le.lean
Labels: toolchain-available, changelog-no

#7910 chore: add failing grind test
  tests/lean/grind/min.lean
Labels: toolchain-available, changelog-language

#7912 feat: lemmas about permutations
  src/Init/Data/Array/Perm.lean
  src/Init/Data/List/Nat/Perm.lean
  src/Init/Data/List/Perm.lean
Labels: toolchain-available, changelog-library

#7916 test: make test deterministic
  tests/lean/interactive/definition.lean
  tests/lean/interactive/definition.lean.expected.out
Labels: toolchain-available, changelog-no

#7914 feat: environment extension data can be split into `.olean.server`
  src/Lean/Elab/Import.lean
  src/Lean/EnvExtension.lean
  src/Lean/Environment.lean
  src/library/module.cpp
  src/util/shell.cpp
  stage0/src/stdlib_flags.h
Labels: breaks-mathlib, toolchain-available, changelog-language, force-mathlib-ci

#7918 chore: add "Init size" benchmark
  tests/bench/speedcenter.exec.velcom.yaml
Labels: toolchain-available

#7868 perf: use mimalloc with important C++ hash maps
  src/kernel/replace_fn.cpp
  src/runtime/sharecommon.h
  src/util/alloc.h
Labels: builds-mathlib, toolchain-available

#7926 fix: missing propagation and split filter in `grind`
  src/Lean/Meta/Tactic/Grind/ForallProp.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  tests/lean/grind/list_problems.lean
  tests/lean/run/grind_getElem.lean
  tests/lean/run/grind_min.lean
Labels: toolchain-available, changelog-language

#7928 fix: nontermination in `grind`
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/MBTC.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
Labels: toolchain-available, changelog-no

#7930 chore: another `grind` fixed test
  build/release/grind_append_issue.lean
  tests/lean/grind/list_problems.lean
Labels: toolchain-available, changelog-no

#7932 chore: move test to correct directory
  tests/lean/run/grind_append_issue.lean
Labels: changelog-no

#7931 chore: improve `grind.clear_aux_decls` error message
  src/Lean/Meta/Tactic/Grind/Util.lean
  tests/lean/run/grind_clear_error.lean
  tests/lean/run/grind_ite.lean
Labels: toolchain-available, changelog-no

#7924 chore: CI: disable Linux 32bit
  .github/workflows/ci.yml
Labels: toolchain-available

#7819 refactor: more complete channel implementation for `Std.Channel`
  src/Init/Data.lean
  src/Init/Data/Channel.lean
  src/Lean/Data/JsonRpc.lean
  src/Lean/Server/FileWorker.lean
  src/Std/Sync/Channel.lean
  tests/bench/channel.lean
  tests/bench/speedcenter.exec.velcom.yaml
  tests/lean/promise.lean
  tests/lean/run/sync_channel.lean
Labels: builds-mathlib, toolchain-available, changelog-library

#7935 chore: cleanup 'if normalization' grind example
  tests/lean/run/grind_ite.lean
Labels: toolchain-available

#7936 chore: generalize List.Perm.take
  src/Init/Data/Array/Perm.lean
  src/Init/Data/List/Nat/Perm.lean
  src/Init/Data/List/Perm.lean
Labels: toolchain-available, changelog-library

#7934 chore: add grind annotations for Nat/Int.min/max
  src/Init/Data/Int/Order.lean
  src/Init/Data/List/Lemmas.lean
  src/Init/Data/Nat/Basic.lean
  tests/lean/run/grind_cutsat_omega.lean
  tests/lean/run/grind_ite_split_issue.lean
  tests/lean/run/grind_min.lean
  tests/lean/run/grind_t1.lean
Labels: toolchain-available

#7937 feat: lookahead in `grind`
  src/Init/Grind/Lemmas.lean
  src/Init/Grind/Tactics.lean
  src/Lean/Meta/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Intro.lean
  src/Lean/Meta/Tactic/Grind/Lookahead.lean
  src/Lean/Meta/Tactic/Grind/ProveEq.lean
  src/Lean/Meta/Tactic/Grind/Solve.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_funext.lean
  tests/lean/run/grind_lookahead.lean
  tests/lean/run/grind_split_arith_imp.lean
  tests/lean/run/grind_trace.lean
Labels: toolchain-available, changelog-language

#7938 feat: `List/Array/Vector.count_replace` lemmas
  src/Init/Data/Array/Count.lean
  src/Init/Data/List/Nat/Count.lean
  src/Init/Data/Vector/Count.lean
Labels: toolchain-available, changelog-library

#7941 chore: fix cmake install exclude patterns
  src/CMakeLists.txt
Labels: toolchain-available, backport releases/v4.19.0

#7946 feat: improve case split heuristics in `grind`
  src/Lean/Meta/Tactic/Grind/Internalize.lean
  src/Lean/Meta/Tactic/Grind/Lookahead.lean
  src/Lean/Meta/Tactic/Grind/MBTC.lean
  src/Lean/Meta/Tactic/Grind/Split.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_bintree.lean
Labels: toolchain-available, changelog-no

#7949 feat: add `[grind ext]` attribute
  src/Init/Grind/Tactics.lean
  src/Lean/Elab/Tactic/Grind.lean
  src/Lean/Meta/Tactic/Ext.lean
  src/Lean/Meta/Tactic/Grind/Attr.lean
  src/Lean/Meta/Tactic/Grind/ExtAttr.lean
  src/Lean/Meta/Tactic/Grind/Types.lean
  tests/lean/run/grind_bintree.lean
  tests/lean/run/grind_cat.lean
  tests/lean/run/grind_cat2.lean
  tests/lean/run/grind_funext.lean
  tests/lean/run/grind_ite.lean
  tests/lean/run/grind_list.lean
  tests/lean/run/grind_t1.lean
  tests/lean/run/grind_trace.lean
Labels: toolchain-available, changelog-language

#7953 feat: updates to List/Array.Perm API
  src/Init/Data/Array/Perm.lean
  src/Init/Data/List/Perm.lean
Labels: toolchain-available, changelog-library

#7951 chore: add `[grind ext] funext`
  src/Init/Grind.lean
  src/Init/Grind/Ext.lean
  src/Lean/Meta/Tactic/Grind/ExtAttr.lean
  tests/lean/run/grind_bintree.lean
  tests/lean/run/grind_cat.lean
  tests/lean/run/grind_cat2.lean
  tests/lean/run/grind_funext.lean
  tests/lean/run/grind_ite.lean
  tests/lean/run/grind_list.lean
Labels: toolchain-available, changelog-no

#7950 fix: make sure `all_goals` restores state on failure
  src/Lean/Elab/Tactic/BuiltinTactic.lean
  tests/lean/run/allGoals.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7947 doc: add docstrings to `mkFreshUserName` etc
  src/Init/Meta.lean
  src/Lean/CoreM.lean
  src/Lean/Elab/Term.lean
  src/Lean/Meta/Tactic/Intro.lean
Labels: builds-mathlib, toolchain-available, changelog-doc

#7955 feat: preparation for #7830
  src/Lean/Elab/Tactic/Induction.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#7929 perf: use mimalloc in compactor hashmaps
  src/runtime/compact.cpp
  src/runtime/compact.h
Labels: toolchain-available, changelog-no

#7958 feat: wait on dedicated tasks after main is finished
  src/runtime/object.cpp
  tests/compiler/wait_dedicated.lean
  tests/compiler/wait_dedicated.lean.expected.out
Labels: toolchain-available, changelog-compiler

#7945 fix: race condition in `IO.getTaskState`
  src/runtime/object.cpp
Labels: toolchain-available, changelog-compiler

#7961 fix: bv_decide default match with as many arms as constructors
  src/Lean/Elab/Tactic/BVDecide/Frontend/Normalize/TypeAnalysis.lean
  tests/lean/run/bv_decide_enums_two.lean
Labels: toolchain-available, changelog-language

#7964 chore: lake: rm unused import in `DSL.DeclUtil`
  src/lake/Lake/DSL/DeclUtil.lean
Labels: builds-mathlib, toolchain-available, changelog-no

#7963 feat: link `Lake.EStateT` with `EStateM`
  src/lake/Lake/Util/EStateT.lean
Labels: awaiting-review, toolchain-available, changelog-lake

#7939 feat: Array.count_erase lemma
  src/Init/Data/Array/Count.lean
Labels: toolchain-available, changelog-library

#7975 fix: reduce priorities of `CommRing` parent projections
  src/Init/Grind/CommRing/Basic.lean
Labels: toolchain-available, changelog-language

#7976 feat: make bv_decide work on simp normal forms of shifts
  src/Std/Tactic/BVDecide/Normalize/Canonicalize.lean
  src/Std/Tactic/BVDecide/Syntax.lean
  tests/lean/run/bv_decide_shift_to_nat.lean
Labels: toolchain-available, changelog-language

#7906 feat: lake: track trace inputs & related fixes
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Job/Basic.lean
  src/lake/Lake/Build/Job/Monad.lean
  src/lake/Lake/Build/Job/Register.lean
  src/lake/Lake/Build/Library.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Build/Package.lean
  src/lake/Lake/Build/Run.lean
  src/lake/Lake/Build/Target/Fetch.lean
  src/lake/Lake/Build/Trace.lean
Labels: builds-mathlib, toolchain-available, changelog-lake

#7830 feat: allow omission of `=> ?_` in induction/cases tactics
  src/Init/Tactics.lean
  src/Lean/Elab/Tactic/Induction.lean
  tests/lean/run/induction1.lean
Labels: builds-mathlib, toolchain-available, changelog-language

#7909 feat: lake: build by source path
  src/lake/Lake/CLI/Build.lean
  src/lake/Lake/CLI/Error.lean
  src/lake/Lake/CLI/Help.lean
  src/lake/Lake/CLI/Main.lean
  src/lake/Lake/CLI/Serve.lean
  src/lake/Lake/Config/LeanExe.lean
  src/lake/Lake/Config/LeanLib.lean
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Config/Package.lean
  src/lake/Lake/Config/Workspace.lean
  src/lake/Lake/Load/Package.lean
  src/lake/Lake/Util/FilePath.lean
  src/lake/examples/targets/test.sh
  src/lake/tests/common.sh
  src/lake/tests/lean/lakefile.lean
  src/lake/tests/lean/test.sh
  src/lake/tests/setupFile/Test.lean
  src/lake/tests/setupFile/lakefile.toml
  src/lake/tests/setupFile/test.sh
Labels: builds-mathlib, toolchain-available, changelog-lake

#7967 chore: lake: bootstrap Lean include directory
  CMakeLists.txt
  src/Lean/Compiler/FFI.lean
  src/lake/Lake/Build/Common.lean
  src/lake/Lake/Build/Module.lean
  src/lake/Lake/Config/InstallPath.lean
  src/lake/Lake/Config/Module.lean
  src/lake/Lake/Config/Package.lean
  src/lake/examples/ffi/lib/lakefile.lean
  src/lakefile.toml.in
Labels: needs-update-stage0, builds-mathlib, toolchain-available, release-ci, changelog-lake

#6081 feat: `IO.Process.SpawnArgs.inheritEnv`
  src/Init/System/IO.lean
  src/runtime/process.cpp
Labels: builds-mathlib, toolchain-available, release-ci, changelog-library

#7979 chore: lake: temporarily disable tests in `tests`
  src/shell/CMakeLists.txt
Labels: toolchain-available, changelog-no

#7980 feat: monomials for `CommRing`
  src/Init/Grind/CommRing/Basic.lean
  src/Init/Grind/CommRing/SOM.lean
Labels: toolchain-available, changelog-language
